// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public abstract partial class ConversionFunctions
{
    
    #region Private fields
    [EditorBrowsable(EditorBrowsableState.Never)]
    private AnyConvertStrType _toString;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private AnyConvertNumType _toNum;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private StringConvertDateTimeType _toDateTime;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private AnyConvertBoolType _toBool;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ListConvertListType _listToList;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ListConvertStringType _listToString;
    
    private static XmlSerializer serializer;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public virtual AnyConvertStrType ToString
    {
        get
        {
            return this._toString;
        }
        set
        {
            this._toString = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public virtual AnyConvertNumType ToNum
    {
        get
        {
            return this._toNum;
        }
        set
        {
            this._toNum = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public virtual StringConvertDateTimeType ToDateTime
    {
        get
        {
            return this._toDateTime;
        }
        set
        {
            this._toDateTime = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public virtual AnyConvertBoolType ToBool
    {
        get
        {
            return this._toBool;
        }
        set
        {
            this._toBool = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public virtual ListConvertListType ListToList
    {
        get
        {
            return this._listToList;
        }
        set
        {
            this._listToList = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public virtual ListConvertStringType ListToString
    {
        get
        {
            return this._listToString;
        }
        set
        {
            this._listToString = value;
        }
    }
    
    private static XmlSerializer Serializer
    {
        get
        {
            if ((serializer == null))
            {
                serializer = new XmlSerializerFactory().CreateSerializer(typeof(ConversionFunctions));
            }
            return serializer;
        }
    }
    
    /// <summary>
    /// Test whether ToString should be serialized
    /// </summary>
    public virtual bool ShouldSerializeToString()
    {
        return (_toString != null);
    }
    
    /// <summary>
    /// Test whether ToNum should be serialized
    /// </summary>
    public virtual bool ShouldSerializeToNum()
    {
        return (_toNum != null);
    }
    
    /// <summary>
    /// Test whether ToDateTime should be serialized
    /// </summary>
    public virtual bool ShouldSerializeToDateTime()
    {
        return (_toDateTime != null);
    }
    
    /// <summary>
    /// Test whether ToBool should be serialized
    /// </summary>
    public virtual bool ShouldSerializeToBool()
    {
        return (_toBool != null);
    }
    
    /// <summary>
    /// Test whether ListToList should be serialized
    /// </summary>
    public virtual bool ShouldSerializeListToList()
    {
        return (_listToList != null);
    }
    
    /// <summary>
    /// Test whether ListToString should be serialized
    /// </summary>
    public virtual bool ShouldSerializeListToString()
    {
        return (_listToString != null);
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current ConversionFunctions object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public virtual string Serialize(System.Text.Encoding encoding)
    {
        System.IO.StreamReader streamReader = null;
        System.IO.MemoryStream memoryStream = null;
        try
        {
            memoryStream = new System.IO.MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Encoding = encoding;
            xmlWriterSettings.Indent = true;
            xmlWriterSettings.IndentChars = " ";
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, SeekOrigin.Begin);
            streamReader = new System.IO.StreamReader(memoryStream, encoding);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }
    
    public virtual string Serialize()
    {
        return Serialize(System.Text.Encoding.UTF8);
    }
    
    /// <summary>
    /// Deserializes workflow markup into an ConversionFunctions object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output ConversionFunctions object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out ConversionFunctions obj, out System.Exception exception)
    {
        exception = null;
        obj = default(ConversionFunctions);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (System.Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out ConversionFunctions obj)
    {
        System.Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public static ConversionFunctions Deserialize(string input)
    {
        System.IO.StringReader stringReader = null;
        try
        {
            stringReader = new System.IO.StringReader(input);
            return ((ConversionFunctions)(Serializer.Deserialize(XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }
    
    public static ConversionFunctions Deserialize(System.IO.Stream s)
    {
        return ((ConversionFunctions)(Serializer.Deserialize(s)));
    }
    #endregion
    
    /// <summary>
    /// Serializes current ConversionFunctions object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName, encoding);
            return true;
        }
        catch (System.Exception e)
        {
            exception = e;
            return false;
        }
    }
    
    public virtual bool SaveToFile(string fileName, out System.Exception exception)
    {
        return SaveToFile(fileName, System.Text.Encoding.UTF8, out exception);
    }
    
    public virtual void SaveToFile(string fileName)
    {
        SaveToFile(fileName, System.Text.Encoding.UTF8);
    }
    
    public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
    {
        System.IO.StreamWriter streamWriter = null;
        try
        {
            string xmlString = Serialize(encoding);
            streamWriter = new System.IO.StreamWriter(fileName, false, encoding);
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes xml markup from file into an ConversionFunctions object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output ConversionFunctions object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out ConversionFunctions obj, out System.Exception exception)
    {
        exception = null;
        obj = default(ConversionFunctions);
        try
        {
            obj = LoadFromFile(fileName, encoding);
            return true;
        }
        catch (System.Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool LoadFromFile(string fileName, out ConversionFunctions obj, out System.Exception exception)
    {
        return LoadFromFile(fileName, System.Text.Encoding.UTF8, out obj, out exception);
    }
    
    public static bool LoadFromFile(string fileName, out ConversionFunctions obj)
    {
        System.Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }
    
    public static ConversionFunctions LoadFromFile(string fileName)
    {
        return LoadFromFile(fileName, System.Text.Encoding.UTF8);
    }
    
    public static ConversionFunctions LoadFromFile(string fileName, System.Text.Encoding encoding)
    {
        System.IO.FileStream file = null;
        System.IO.StreamReader sr = null;
        try
        {
            file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new System.IO.StreamReader(file, encoding);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
}
}
#pragma warning restore
