// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

/// <summary>
/// MOVED from SDCDataTypes:
/// SDC datatypes in Simple (S) format, based mostly on W3C specifications.  Uses baseAttributes and Extension capability to enhance the list of Data Types.        **CHECK for ERRORS and completeness**
/// </summary>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterValueType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyType1))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public partial class DataTypes_SType : ExtensionBaseType
{
    
    #region Private fields
    [EditorBrowsable(EditorBrowsableState.Never)]
    private BaseType _item;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ItemChoiceType _itemElementName;
    
    private static XmlSerializer serializer;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute("HTML", typeof(HTML_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("XML", typeof(XML_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("anyType", typeof(anyType_DEtype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("anyURI", typeof(anyURI_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("base64Binary", typeof(base64Binary_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("boolean", typeof(boolean_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("byte", typeof(byte_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(date_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("dateTime", typeof(dateTimeStamp_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("dateTimeStamp", typeof(dateTimeStamp_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("decimal", typeof(decimal_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("double", typeof(double_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("duration", typeof(duration_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("float", typeof(float_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("gDay", typeof(gDay_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("gMonth", typeof(gMonth_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("gMonthDay", typeof(gMonthDay_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("gYear", typeof(gYear_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("gYearMonth", typeof(gMonth_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("hexBinary", typeof(hexBinary_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("int", typeof(int_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("integer", typeof(integer_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("long", typeof(long_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("negativeInteger", typeof(negativeInteger_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("nonNegativeInteger", typeof(nonNegativeInteger_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("nonPositiveInteger", typeof(nonPositiveInteger_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("positiveInteger", typeof(positiveInteger_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("short", typeof(short_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("string", typeof(string_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("time", typeof(time_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("unsignedByte", typeof(unsignedByte_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("unsignedInt", typeof(unsignedInt_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("unsignedLong", typeof(unsignedLong_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("unsignedShort", typeof(unsignedShort_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("yearMonthDuration", typeof(yearMonthDuration_Stype), IsNullable=true, Order=0)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public virtual BaseType Item
    {
        get
        {
            return this._item;
        }
        set
        {
            this._item = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public virtual ItemChoiceType ItemElementName
    {
        get
        {
            return this._itemElementName;
        }
        set
        {
            this._itemElementName = value;
        }
    }
    
    private static XmlSerializer Serializer
    {
        get
        {
            if ((serializer == null))
            {
                serializer = new XmlSerializerFactory().CreateSerializer(typeof(DataTypes_SType));
            }
            return serializer;
        }
    }
    
    /// <summary>
    /// Test whether Item should be serialized
    /// </summary>
    public virtual bool ShouldSerializeItem()
    {
        return (_item != null);
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current DataTypes_SType object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public virtual string Serialize(System.Text.Encoding encoding)
    {
        System.IO.StreamReader streamReader = null;
        System.IO.MemoryStream memoryStream = null;
        try
        {
            memoryStream = new System.IO.MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Encoding = encoding;
            xmlWriterSettings.Indent = true;
            xmlWriterSettings.IndentChars = " ";
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, SeekOrigin.Begin);
            streamReader = new System.IO.StreamReader(memoryStream, encoding);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }
    
    public virtual string Serialize()
    {
        return Serialize(System.Text.Encoding.UTF8);
    }
    
    /// <summary>
    /// Deserializes workflow markup into an DataTypes_SType object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output DataTypes_SType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out DataTypes_SType obj, out System.Exception exception)
    {
        exception = null;
        obj = default(DataTypes_SType);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (System.Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out DataTypes_SType obj)
    {
        System.Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public new static DataTypes_SType Deserialize(string input)
    {
        System.IO.StringReader stringReader = null;
        try
        {
            stringReader = new System.IO.StringReader(input);
            return ((DataTypes_SType)(Serializer.Deserialize(XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }
    
    public static DataTypes_SType Deserialize(System.IO.Stream s)
    {
        return ((DataTypes_SType)(Serializer.Deserialize(s)));
    }
    #endregion
    
    /// <summary>
    /// Serializes current DataTypes_SType object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName, encoding);
            return true;
        }
        catch (System.Exception e)
        {
            exception = e;
            return false;
        }
    }
    
    public virtual bool SaveToFile(string fileName, out System.Exception exception)
    {
        return SaveToFile(fileName, System.Text.Encoding.UTF8, out exception);
    }
    
    public virtual void SaveToFile(string fileName)
    {
        SaveToFile(fileName, System.Text.Encoding.UTF8);
    }
    
    public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
    {
        System.IO.StreamWriter streamWriter = null;
        try
        {
            string xmlString = Serialize(encoding);
            streamWriter = new System.IO.StreamWriter(fileName, false, encoding);
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes xml markup from file into an DataTypes_SType object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output DataTypes_SType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out DataTypes_SType obj, out System.Exception exception)
    {
        exception = null;
        obj = default(DataTypes_SType);
        try
        {
            obj = LoadFromFile(fileName, encoding);
            return true;
        }
        catch (System.Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool LoadFromFile(string fileName, out DataTypes_SType obj, out System.Exception exception)
    {
        return LoadFromFile(fileName, System.Text.Encoding.UTF8, out obj, out exception);
    }
    
    public static bool LoadFromFile(string fileName, out DataTypes_SType obj)
    {
        System.Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }
    
    public static DataTypes_SType LoadFromFile(string fileName)
    {
        return LoadFromFile(fileName, System.Text.Encoding.UTF8);
    }
    
    public new static DataTypes_SType LoadFromFile(string fileName, System.Text.Encoding encoding)
    {
        System.IO.FileStream file = null;
        System.IO.StreamReader sr = null;
        try
        {
            file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new System.IO.StreamReader(file, encoding);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
}
}
#pragma warning restore
