SDC::gMonthDay_Stype
string SDC.gMonthDay_Stype::_val
dtQuantEnum SDC.gMonthDay_Stype::_quantEnum
Referenced by SDC.gMonthDay_Stype.gMonthDay_Stype.
ObjectChangeTracker SDC.gMonthDay_Stype.changeTrackerField
static XmlSerializer SDC.gMonthDay_Stype::serializer
string SDC.gMonthDay_Stype::val
Referenced by SDC.gMonthDay_Stype.ShouldSerializeval.
dtQuantEnum SDC.gMonthDay_Stype::quantEnum
static XmlSerializer SDC.gMonthDay_Stype::Serializer
Referenced by SDC.gMonthDay_Stype.Deserialize.
ObjectChangeTracker SDC.gMonthDay_Stype.ChangeTracker
SDC.gMonthDay_Stype.gMonthDay_Stype()
SDC.gMonthDay_Stype.gMonthDay_Stype(BaseType parentNode)
virtual bool SDC.gMonthDay_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.gMonthDay_Stype.val.
virtual string SDC.gMonthDay_Stype.Serialize(System.Text.Encoding encoding)
Serializes current gMonthDay_Stype object into an XML string
string XML value
virtual string SDC.gMonthDay_Stype.Serialize()
Referenced by SDC.gMonthDay_Stype.SaveToFile.
virtual bool SDC.gMonthDay_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current gMonthDay_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.gMonthDay_Stype.SaveToFile.
virtual bool SDC.gMonthDay_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.gMonthDay_Stype.SaveToFile.
virtual void SDC.gMonthDay_Stype.SaveToFile(string fileName)
References SDC.gMonthDay_Stype.SaveToFile.
virtual void SDC.gMonthDay_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.gMonthDay_Stype.Serialize.
SDC.gMonthDay_Stype.gMonthDay_Stype()
gMonthDay_Stype class constructor
References SDC.gMonthDay_Stype._quantEnum.
virtual bool SDC.gMonthDay_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.gMonthDay_Stype.val.
virtual string SDC.gMonthDay_Stype.Serialize()
Serializes current gMonthDay_Stype object into an XML string
string XML value
virtual bool SDC.gMonthDay_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current gMonthDay_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.gMonthDay_Stype.SaveToFile.
virtual void SDC.gMonthDay_Stype.SaveToFile(string fileName)
References SDC.null, SDC.gMonthDay_Stype.Serialize.
virtual gMonthDay_Stype SDC.gMonthDay_Stype.Clone()
Create a clone of this gMonthDay_Stype object
static bool SDC.gMonthDay_Stype.Deserialize(string input, out gMonthDay_Stype obj, out System.Exception exception)
Deserializes workflow markup into an gMonthDay_Stype object
input string workflow markup to deserialize obj Output gMonthDay_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gMonthDay_Stype.Deserialize, SDC.gMonthDay_Stype.LoadFromFile.
static bool SDC.gMonthDay_Stype.Deserialize(string input, out gMonthDay_Stype obj)
References SDC.gMonthDay_Stype.Deserialize, SDC.null.
static new gMonthDay_Stype SDC.gMonthDay_Stype.Deserialize(string input)
References SDC.null.
static gMonthDay_Stype SDC.gMonthDay_Stype.Deserialize(System.IO.Stream s)
References SDC.gMonthDay_Stype.Serializer.
static bool SDC.gMonthDay_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out gMonthDay_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an gMonthDay_Stype object
fileName string xml file to load and deserialize obj Output gMonthDay_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gMonthDay_Stype.LoadFromFile.
static bool SDC.gMonthDay_Stype.LoadFromFile(string fileName, out gMonthDay_Stype obj, out System.Exception exception)
References SDC.gMonthDay_Stype.LoadFromFile.
static bool SDC.gMonthDay_Stype.LoadFromFile(string fileName, out gMonthDay_Stype obj)
References SDC.gMonthDay_Stype.LoadFromFile, SDC.null.
static gMonthDay_Stype SDC.gMonthDay_Stype.LoadFromFile(string fileName)
References SDC.gMonthDay_Stype.LoadFromFile.
static new gMonthDay_Stype SDC.gMonthDay_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.gMonthDay_Stype.Deserialize, SDC.null.
static bool SDC.gMonthDay_Stype.Deserialize(string input, out gMonthDay_Stype obj, out Exception exception)
Deserializes workflow markup into an gMonthDay_Stype object
input string workflow markup to deserialize obj Output gMonthDay_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gMonthDay_Stype.Deserialize, SDC.null.
static bool SDC.gMonthDay_Stype.Deserialize(string input, out gMonthDay_Stype obj)
References SDC.gMonthDay_Stype.Deserialize, SDC.null.
static new gMonthDay_Stype SDC.gMonthDay_Stype.Deserialize(string input)
References SDC.null, SDC.gMonthDay_Stype.Serializer.
static gMonthDay_Stype SDC.gMonthDay_Stype.Deserialize(Stream s)
References SDC.gMonthDay_Stype.Serializer.
static bool SDC.gMonthDay_Stype.LoadFromFile(string fileName, out gMonthDay_Stype obj, out Exception exception)
Deserializes xml markup from file into an gMonthDay_Stype object
fileName string xml file to load and deserialize obj Output gMonthDay_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gMonthDay_Stype.LoadFromFile, SDC.null.
static bool SDC.gMonthDay_Stype.LoadFromFile(string fileName, out gMonthDay_Stype obj)
References SDC.gMonthDay_Stype.LoadFromFile, SDC.null.
static new gMonthDay_Stype SDC.gMonthDay_Stype.LoadFromFile(string fileName)
References SDC.gMonthDay_Stype.Deserialize, SDC.null.