SDC::HashType
string SDC.HashType::_hashAlgorithm
ObjectChangeTracker SDC.HashType.changeTrackerField
static XmlSerializer SDC.HashType::serializer
string SDC.HashType::hashAlgorithm
Referenced by SDC.HashType.ShouldSerializehashAlgorithm.
static XmlSerializer SDC.HashType::Serializer
Referenced by SDC.HashType.Deserialize.
ObjectChangeTracker SDC.HashType.ChangeTracker
SDC.HashType.HashType()
SDC.HashType.HashType(BaseType parentNode)
virtual bool SDC.HashType.ShouldSerializehashAlgorithm()
Test whether hashAlgorithm should be serialized
virtual string SDC.HashType.Serialize(System.Text.Encoding encoding)
Serializes current HashType object into an XML string
string XML value
virtual string SDC.HashType.Serialize()
Referenced by SDC.HashType.SaveToFile.
virtual bool SDC.HashType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current HashType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.HashType.SaveToFile.
virtual bool SDC.HashType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.HashType.SaveToFile(string fileName)
virtual void SDC.HashType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.HashType.ShouldSerializehashAlgorithm()
Test whether hashAlgorithm should be serialized
References SDC.HashType.hashAlgorithm.
virtual string SDC.HashType.Serialize()
Serializes current HashType object into an XML string
string XML value
virtual bool SDC.HashType.SaveToFile(string fileName, out Exception exception)
Serializes current HashType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.HashType.SaveToFile.
virtual void SDC.HashType.SaveToFile(string fileName)
References SDC.null, SDC.HashType.Serialize.
virtual HashType SDC.HashType.Clone()
Create a clone of this HashType object
static bool SDC.HashType.Deserialize(string input, out HashType obj, out System.Exception exception)
Deserializes workflow markup into an HashType object
input string workflow markup to deserialize obj Output HashType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.HashType.Deserialize, SDC.HashType.LoadFromFile.
static bool SDC.HashType.Deserialize(string input, out HashType obj)
References SDC.null.
static new HashType SDC.HashType.Deserialize(string input)
References SDC.null.
static HashType SDC.HashType.Deserialize(System.IO.Stream s)
static bool SDC.HashType.LoadFromFile(string fileName, System.Text.Encoding encoding, out HashType obj, out System.Exception exception)
Deserializes xml markup from file into an HashType object
fileName string xml file to load and deserialize obj Output HashType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.HashType.LoadFromFile.
static bool SDC.HashType.LoadFromFile(string fileName, out HashType obj, out System.Exception exception)
static bool SDC.HashType.LoadFromFile(string fileName, out HashType obj)
References SDC.null.
static HashType SDC.HashType.LoadFromFile(string fileName)
static new HashType SDC.HashType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.HashType.Deserialize(string input, out HashType obj, out Exception exception)
Deserializes workflow markup into an HashType object
input string workflow markup to deserialize obj Output HashType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.HashType.Deserialize, SDC.null.
static bool SDC.HashType.Deserialize(string input, out HashType obj)
References SDC.HashType.Deserialize, SDC.null.
static new HashType SDC.HashType.Deserialize(string input)
References SDC.null, SDC.HashType.Serializer.
static HashType SDC.HashType.Deserialize(Stream s)
References SDC.HashType.Serializer.
static bool SDC.HashType.LoadFromFile(string fileName, out HashType obj, out Exception exception)
Deserializes xml markup from file into an HashType object
fileName string xml file to load and deserialize obj Output HashType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.HashType.LoadFromFile, SDC.null.
static bool SDC.HashType.LoadFromFile(string fileName, out HashType obj)
References SDC.HashType.LoadFromFile, SDC.null.
static new HashType SDC.HashType.LoadFromFile(string fileName)
References SDC.HashType.Deserialize, SDC.null.