SDC::nonPositiveInteger_Stype
string SDC.nonPositiveInteger_Stype::_val
dtQuantEnum SDC.nonPositiveInteger_Stype::_quantEnum
Referenced by SDC.nonPositiveInteger_Stype.nonPositiveInteger_Stype.
ObjectChangeTracker SDC.nonPositiveInteger_Stype.changeTrackerField
static XmlSerializer SDC.nonPositiveInteger_Stype::serializer
string SDC.nonPositiveInteger_Stype::val
Referenced by SDC.nonPositiveInteger_Stype.ShouldSerializeval.
dtQuantEnum SDC.nonPositiveInteger_Stype::quantEnum
static XmlSerializer SDC.nonPositiveInteger_Stype::Serializer
Referenced by SDC.nonPositiveInteger_Stype.Deserialize.
ObjectChangeTracker SDC.nonPositiveInteger_Stype.ChangeTracker
SDC.nonPositiveInteger_Stype.nonPositiveInteger_Stype()
SDC.nonPositiveInteger_Stype.nonPositiveInteger_Stype(BaseType parentNode)
virtual bool SDC.nonPositiveInteger_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.nonPositiveInteger_Stype.val.
virtual string SDC.nonPositiveInteger_Stype.Serialize(System.Text.Encoding encoding)
Serializes current nonPositiveInteger_Stype object into an XML string
string XML value
virtual string SDC.nonPositiveInteger_Stype.Serialize()
Referenced by SDC.nonPositiveInteger_Stype.SaveToFile.
virtual bool SDC.nonPositiveInteger_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current nonPositiveInteger_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.nonPositiveInteger_Stype.SaveToFile.
virtual bool SDC.nonPositiveInteger_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.nonPositiveInteger_Stype.SaveToFile.
virtual void SDC.nonPositiveInteger_Stype.SaveToFile(string fileName)
References SDC.nonPositiveInteger_Stype.SaveToFile.
virtual void SDC.nonPositiveInteger_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.nonPositiveInteger_Stype.Serialize.
SDC.nonPositiveInteger_Stype.nonPositiveInteger_Stype()
nonPositiveInteger_Stype class constructor
References SDC.nonPositiveInteger_Stype._quantEnum.
virtual bool SDC.nonPositiveInteger_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.nonPositiveInteger_Stype.val.
virtual string SDC.nonPositiveInteger_Stype.Serialize()
Serializes current nonPositiveInteger_Stype object into an XML string
string XML value
virtual bool SDC.nonPositiveInteger_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current nonPositiveInteger_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.nonPositiveInteger_Stype.SaveToFile.
virtual void SDC.nonPositiveInteger_Stype.SaveToFile(string fileName)
References SDC.null, SDC.nonPositiveInteger_Stype.Serialize.
virtual nonPositiveInteger_Stype SDC.nonPositiveInteger_Stype.Clone()
Create a clone of this nonPositiveInteger_Stype object
static bool SDC.nonPositiveInteger_Stype.Deserialize(string input, out nonPositiveInteger_Stype obj, out System.Exception exception)
Deserializes workflow markup into an nonPositiveInteger_Stype object
input string workflow markup to deserialize obj Output nonPositiveInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.nonPositiveInteger_Stype.Deserialize, SDC.nonPositiveInteger_Stype.LoadFromFile.
static bool SDC.nonPositiveInteger_Stype.Deserialize(string input, out nonPositiveInteger_Stype obj)
References SDC.nonPositiveInteger_Stype.Deserialize, SDC.null.
static new nonPositiveInteger_Stype SDC.nonPositiveInteger_Stype.Deserialize(string input)
References SDC.null.
static nonPositiveInteger_Stype SDC.nonPositiveInteger_Stype.Deserialize(System.IO.Stream s)
References SDC.nonPositiveInteger_Stype.Serializer.
static bool SDC.nonPositiveInteger_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out nonPositiveInteger_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an nonPositiveInteger_Stype object
fileName string xml file to load and deserialize obj Output nonPositiveInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.nonPositiveInteger_Stype.LoadFromFile.
static bool SDC.nonPositiveInteger_Stype.LoadFromFile(string fileName, out nonPositiveInteger_Stype obj, out System.Exception exception)
References SDC.nonPositiveInteger_Stype.LoadFromFile.
static bool SDC.nonPositiveInteger_Stype.LoadFromFile(string fileName, out nonPositiveInteger_Stype obj)
References SDC.nonPositiveInteger_Stype.LoadFromFile, SDC.null.
static nonPositiveInteger_Stype SDC.nonPositiveInteger_Stype.LoadFromFile(string fileName)
References SDC.nonPositiveInteger_Stype.LoadFromFile.
static new nonPositiveInteger_Stype SDC.nonPositiveInteger_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.nonPositiveInteger_Stype.Deserialize, SDC.null.
static bool SDC.nonPositiveInteger_Stype.Deserialize(string input, out nonPositiveInteger_Stype obj, out Exception exception)
Deserializes workflow markup into an nonPositiveInteger_Stype object
input string workflow markup to deserialize obj Output nonPositiveInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.nonPositiveInteger_Stype.Deserialize, SDC.null.
static bool SDC.nonPositiveInteger_Stype.Deserialize(string input, out nonPositiveInteger_Stype obj)
References SDC.nonPositiveInteger_Stype.Deserialize, SDC.null.
static new nonPositiveInteger_Stype SDC.nonPositiveInteger_Stype.Deserialize(string input)
References SDC.null, SDC.nonPositiveInteger_Stype.Serializer.
static nonPositiveInteger_Stype SDC.nonPositiveInteger_Stype.Deserialize(Stream s)
References SDC.nonPositiveInteger_Stype.Serializer.
static bool SDC.nonPositiveInteger_Stype.LoadFromFile(string fileName, out nonPositiveInteger_Stype obj, out Exception exception)
Deserializes xml markup from file into an nonPositiveInteger_Stype object
fileName string xml file to load and deserialize obj Output nonPositiveInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.nonPositiveInteger_Stype.LoadFromFile, SDC.null.
static bool SDC.nonPositiveInteger_Stype.LoadFromFile(string fileName, out nonPositiveInteger_Stype obj)
References SDC.nonPositiveInteger_Stype.LoadFromFile, SDC.null.
static new nonPositiveInteger_Stype SDC.nonPositiveInteger_Stype.LoadFromFile(string fileName)
References SDC.nonPositiveInteger_Stype.Deserialize, SDC.null.