SDC::IfBoolCompareType
bool SDC.IfBoolCompareType._shouldSerializenot
Referenced by SDC.IfBoolCompareType.ShouldSerializenot.
IfType SDC.IfBoolCompareType._if
Referenced by SDC.IfBoolCompareType.ShouldSerializeIf.
bool SDC.IfBoolCompareType._not
Referenced by SDC.IfBoolCompareType.IfBoolCompareType, SDC.IfBoolCompareType.ShouldSerializenot.
GetPropertyValuesTypeBoolOpEnum SDC.IfBoolCompareType._boolOpEnum
Referenced by SDC.IfBoolCompareType.IfBoolCompareType.
ObjectChangeTracker SDC.IfBoolCompareType.changeTrackerField
XmlSerializer SDC.IfBoolCompareType.serializer
virtual IfType SDC.IfBoolCompareType.If
virtual bool SDC.IfBoolCompareType.not
virtual GetPropertyValuesTypeBoolOpEnum SDC.IfBoolCompareType.boolOpEnum
XmlSerializer SDC.IfBoolCompareType.Serializer
Referenced by SDC.IfBoolCompareType.Deserialize.
ObjectChangeTracker SDC.IfBoolCompareType.ChangeTracker
void SDC.IfBoolCompareType.Fill_IfBoolCompareType()
SDC.IfBoolCompareType.IfBoolCompareType()
IfBoolCompareType class constructor
References SDC.IfBoolCompareType._boolOpEnum, SDC.IfBoolCompareType._not.
virtual bool SDC.IfBoolCompareType.ShouldSerializenot()
Test whether not should be serialized
References SDC.IfBoolCompareType._not, SDC.IfBoolCompareType._shouldSerializenot.
virtual bool SDC.IfBoolCompareType.ShouldSerializeIf()
Test whether If should be serialized
References SDC.IfBoolCompareType._if, SDC.null.
virtual string SDC.IfBoolCompareType.Serialize()
Serializes current IfBoolCompareType object into an XML string
string XML value
Referenced by SDC.IfBoolCompareType.SaveToFile.
virtual bool SDC.IfBoolCompareType.SaveToFile(string fileName, out Exception exception)
Serializes current IfBoolCompareType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.IfBoolCompareType.SaveToFile(string fileName)
References SDC.null, SDC.IfBoolCompareType.Serialize.
virtual IfBoolCompareType SDC.IfBoolCompareType.Clone()
Create a clone of this IfBoolCompareType object
static bool SDC.IfBoolCompareType.Deserialize(string input, out IfBoolCompareType obj, out Exception exception)
Deserializes workflow markup into an IfBoolCompareType object
input string workflow markup to deserialize obj Output IfBoolCompareType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.IfBoolCompareType.Deserialize, SDC.IfBoolCompareType.LoadFromFile.
static bool SDC.IfBoolCompareType.Deserialize(string input, out IfBoolCompareType obj)
References SDC.IfBoolCompareType.Deserialize, SDC.null.
static new IfBoolCompareType SDC.IfBoolCompareType.Deserialize(string input)
References SDC.null, SDC.IfBoolCompareType.Serializer.
static IfBoolCompareType SDC.IfBoolCompareType.Deserialize(Stream s)
References SDC.IfBoolCompareType.Serializer.
static bool SDC.IfBoolCompareType.LoadFromFile(string fileName, out IfBoolCompareType obj, out Exception exception)
Deserializes xml markup from file into an IfBoolCompareType object
fileName string xml file to load and deserialize obj Output IfBoolCompareType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.IfBoolCompareType.LoadFromFile.
static bool SDC.IfBoolCompareType.LoadFromFile(string fileName, out IfBoolCompareType obj)
References SDC.IfBoolCompareType.LoadFromFile, SDC.null.
static new IfBoolCompareType SDC.IfBoolCompareType.LoadFromFile(string fileName)
References SDC.IfBoolCompareType.Deserialize, SDC.null.