SDC::SDCTreeBuilder
DataRow SDC.SDCTreeBuilder.dr
Referenced by SDC.SDCTreeBuilder.AddBaseTypeItems, SDC.SDCTreeBuilder.AddBlob, SDC.SDCTreeBuilder.AddCodedValue, SDC.SDCTreeBuilder.AddCodeSystemItems, SDC.SDCTreeBuilder.AddComment, SDC.SDCTreeBuilder.AddDataTypesDE, SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.SDCTreeBuilderEcc.AddFillFormDesignProperties, SDC.SDCTreeBuilder.AddHTML, SDC.SDCTreeBuilder.AddIdentifiedTypeItems, SDC.SDCTreeBuilder.AddInjectedForm< T >, SDC.SDCTreeBuilder.AddLink, SDC.SDCTreeBuilder.AddListItemProperties, SDC.SDCTreeBuilder.AddListItemResponseField, SDC.SDCTreeBuilder.AddListMemberToQuestion, SDC.SDCTreeBuilder.AddOrganizationItems, SDC.SDCTreeBuilder.AddPersonItems, SDC.SDCTreeBuilder.AddQuestion< T >, SDC.SDCTreeBuilder.AddUnits< T >, SDC.SDCTreeBuilder.CreateFormDesignTree, SDC.SDCTreeBuilderEcc.CreateHeader.
DataTable SDC.SDCTreeBuilder::dtFormDesign
Referenced by SDC.SDCTreeBuilder.CreateFormDesignTree, SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc.
DataTable SDC.SDCTreeBuilder::dtHeaderDesign
Referenced by SDC.SDCTreeBuilderEcc.CreateFooter, SDC.SDCTreeBuilderEcc.CreateHeader, SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc.
DataRow SDC.SDCTreeBuilder::drFormDesign
Referenced by SDC.SDCTreeBuilderEcc.AddActSendMessage, SDC.SDCTreeBuilder.AddActSendMessage, SDC.SDCTreeBuilderEcc.AddBaseTypeItems, SDC.SDCTreeBuilder.AddBaseTypeItems, SDC.SDCTreeBuilderEcc.AddBlob, SDC.SDCTreeBuilder.AddBlob, SDC.SDCTreeBuilderEcc.AddCodedValue, SDC.SDCTreeBuilder.AddCodedValue, SDC.SDCTreeBuilderEcc.AddCodeSystemItems, SDC.SDCTreeBuilder.AddCodeSystemItems, SDC.SDCTreeBuilderEcc.AddComment, SDC.SDCTreeBuilder.AddComment, SDC.SDCTreeBuilderEcc.AddDataTypesDE, SDC.SDCTreeBuilder.AddDataTypesDE, SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems, SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.SDCTreeBuilderEcc.AddFillActSendMessage, SDC.SDCTreeBuilderEcc.AddFillDataTypesDE, SDC.SDCTreeBuilderEcc.AddFillExtension, SDC.SDCTreeBuilderEcc.AddFillHTML, SDC.SDCTreeBuilderEcc.AddFillOrganizationItems, SDC.SDCTreeBuilderEcc.AddFillResponseUnits, SDC.SDCTreeBuilderEcc.AddHTML, SDC.SDCTreeBuilder.AddHTML, SDC.SDCTreeBuilderEcc.AddIdentifiedTypeItems, SDC.SDCTreeBuilder.AddIdentifiedTypeItems, SDC.SDCTreeBuilderEcc.AddInjectedForm< T >, SDC.SDCTreeBuilder.AddInjectedForm< T >, SDC.SDCTreeBuilderEcc.AddLink, SDC.SDCTreeBuilder.AddLink, SDC.SDCTreeBuilderEcc.AddListItemResponseField, SDC.SDCTreeBuilderEcc.AddListMemberToQuestion, SDC.SDCTreeBuilderEcc.AddOrganizationItems, SDC.SDCTreeBuilder.AddOrganizationItems, SDC.SDCTreeBuilderEcc.AddPersonItems, SDC.SDCTreeBuilder.AddPersonItems, SDC.SDCTreeBuilderEcc.AddPropertyAltText, SDC.SDCTreeBuilderEcc.AddPropertyDescription, SDC.SDCTreeBuilderEcc.AddPropertyInstruction, SDC.SDCTreeBuilderEcc.AddPropertyPopupText, SDC.SDCTreeBuilderEcc.AddPropertyReportText, SDC.SDCTreeBuilderEcc.AddPropertyShortText, SDC.SDCTreeBuilderEcc.AddPropertySpanishText, SDC.SDCTreeBuilderEcc.AddPropertyTooltip, SDC.SDCTreeBuilderEcc.AddQuestion< T >, SDC.SDCTreeBuilder.AddQuestion< T >, SDC.SDCTreeBuilderEcc.AddRepeatingTypeItems, SDC.SDCTreeBuilder.AddSectionItems, SDC.SDCTreeBuilderEcc.AddUnits< T >, SDC.SDCTreeBuilder.CreateFormDesignTree, SDC.SDCTreeBuilderEcc.FillBaseTypeItemData, SDC.SDCTreeBuilderEcc.FillBlob, SDC.SDCTreeBuilderEcc.FillCodeSystemItems, SDC.SDCTreeBuilderEcc.FillDisplayedTypeItemData, SDC.SDCTreeBuilderEcc.FillIdentifiedTypeItemData, SDC.SDCTreeBuilderEcc.FillInjectedForm, SDC.SDCTreeBuilderEcc.FillLinkText, SDC.SDCTreeBuilderEcc.FillListField, SDC.SDCTreeBuilderEcc.FillListItemBase, SDC.SDCTreeBuilderEcc.FillListItemResponseField, SDC.SDCTreeBuilderEcc.FillLookupEndpoint, SDC.SDCTreeBuilderEcc.FillQuantifier, SDC.SDCTreeBuilderEcc.FillQuestionItemBase, SDC.SDCTreeBuilderEcc.FillRepeatingTypeItemData, SDC.SDCTreeBuilderEcc.FillResponseField, SDC.SDCTreeBuilderEcc.FillSectionBase, SDC.SDCTreeBuilderEcc.FillUnits, SDC.SDCTreeBuilderEcc.InitRow.
decimal SDC.SDCTreeBuilder.Order
Referenced by SDC.SDCTreeBuilder.SDCTreeBuilder.
string SDC.SDCTreeBuilder::XsltFileName
raise event when form is created, so it can be serialized and/or transformed
Referenced by SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc, SDC.SDCTreeBuilderEcc.SerializeFormDesignTree, SDC.SDCTreeBuilder.SerializeFormDesignTree.
FormDesignType SDC.SDCTreeBuilder::FormDesign
Referenced by SDC.SDCTreeBuilder.AddBody, SDC.SDCTreeBuilder.AddFooter, SDC.SDCTreeBuilder.AddHeader, SDC.SDCTreeBuilder.CreateFormDesignTree, SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc, SDC.SDCTreeBuilderEcc.SerializeFormDesignTree, SDC.SDCTreeBuilder.SerializeFormDesignTree.
decimal SDC.SDCTreeBuilder.FormDesignID
+raise event when form is created, so it can be serialized and/or transformed
Referenced by SDC.SDCTreeBuilder.CreateFormDesignTree, SDC.SDCTreeBuilder.GetTemplateByCkey, SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc.
SectionItemType SDC.SDCTreeBuilder.Header
SectionItemType SDC.SDCTreeBuilder.Body
SectionItemType SDC.SDCTreeBuilder.Footer
SectionItemType SDC.SDCTreeBuilder._Header
SectionItemType SDC.SDCTreeBuilder._Body
SectionItemType SDC.SDCTreeBuilder._Footer
SDC.SDCTreeBuilder.SDCTreeBuilder()
SectionItemType SDC.SDCTreeBuilder.AddSectionToFormDesign(FormDesignType fd)
References SDC.SDCTreeBuilder.AddRepeatingTypeItems, SDC.SectionItemType, SDC.var.
RepeatingType SDC.SDCTreeBuilder.AddRepeatingTypeItems(RepeatingType rt)
Base type functions.
Referenced by SDC.SDCTreeBuilder.AddQuestion< T >, SDC.SDCTreeBuilder.AddSection< T >, SDC.SDCTreeBuilder.AddSectionItems, SDC.SDCTreeBuilder.AddSectionToFormDesign.
DisplayedType SDC.SDCTreeBuilder.AddDisplayedTypeItems(DisplayedType dt)
References SDC.SDCTreeBuilder.AddBlob, SDC.SDCTreeBuilder.AddCodedValue, SDC.SDCTreeBuilder.AddContact, SDC.SDCTreeBuilder.AddIdentifiedTypeItems, SDC.SDCTreeBuilder.AddLink, SDC.SDCTreeBuilder.AddOtherText, SDC.SDCTreeBuilder.dr, SDC.string.
Referenced by SDC.SDCTreeBuilder.AddButtonAction< T >, SDC.SDCTreeBuilder.AddDisplayedItem< T >, SDC.SDCTreeBuilder.AddDisplayedItemToList, SDC.SDCTreeBuilder.AddListItemProperties.
IdentifiedExtensionType SDC.SDCTreeBuilder.AddIdentifiedTypeItems(IdentifiedExtensionType iet)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.dr, SDC.string.
Referenced by SDC.SDCTreeBuilder.AddDisplayedTypeItems.
ExtensionBaseType SDC.SDCTreeBuilder.AddExtensionBaseTypeItems(ExtensionBaseType ebt)
References SDC.SDCTreeBuilder.AddBaseTypeItems, SDC.SDCTreeBuilder.AddComment, SDC.SDCTreeBuilder.AddExtension.
Referenced by SDC.SDCTreeBuilder.AddActionToThenType, SDC.SDCTreeBuilderEcc.AddCodeSystemItems, SDC.SDCTreeBuilder.AddCodeSystemItems, SDC.SDCTreeBuilderEcc.AddIdentifiedTypeItems, SDC.SDCTreeBuilder.AddIdentifiedTypeItems, SDC.SDCTreeBuilderEcc.AddInjectedForm< T >, SDC.SDCTreeBuilder.AddInjectedForm< T >, SDC.SDCTreeBuilderEcc.AddLink, SDC.SDCTreeBuilder.AddLink, SDC.SDCTreeBuilderEcc.AddListItemResponseField, SDC.SDCTreeBuilder.AddListItemResponseField.
BaseType SDC.SDCTreeBuilder.AddBaseTypeItems(BaseType bt)
References SDC.decimal, SDC.SDCTreeBuilder.dr, SDC.string.
Referenced by SDC.SDCTreeBuilder.AddDataTypesDE, SDC.SDCTreeBuilder.AddExtensionBaseTypeItems.
CommentType SDC.SDCTreeBuilder.AddComment(ExtensionBaseType ebt)
References SDC.ExtensionBaseType.Comment, SDC.CommentType, SDC.SDCTreeBuilder.dr, SDC.null, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddExtensionBaseTypeItems.
ExtensionType SDC.SDCTreeBuilder.AddExtension(ExtensionBaseType ebt)
References SDC.e, SDC.ExtensionBaseType.Extension, SDC.ExtensionType, SDC.null, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddExtensionBaseTypeItems.
HTML_Stype SDC.SDCTreeBuilder.AddHTML(RichTextType rtf)
References SDC.SDCTreeBuilder.dr, SDC.HTML_Stype, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddBlob, SDC.SDCTreeBuilder.AddCodedValue, SDC.SDCTreeBuilder.AddLink, SDC.SDCTreeBuilder.AddOtherText, SDC.SDCTreeBuilder.AddRichText< T >.
XmlElement SDC.SDCTreeBuilder.StringToXMLElement(string rawXML)
References SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddActSendMessage, SDC.SDCTreeBuilder.AddActSendMessage, SDC.SDCTreeBuilderEcc.AddFillActSendMessage, SDC.SDCTreeBuilderEcc.AddFillExtension, SDC.SDCTreeBuilderEcc.AddFillHTML, SDC.SDCTreeBuilderEcc.AddHTML, SDC.SDCTreeBuilder.AddHTML.
WebServiceType SDC.SDCTreeBuilder.AddWebService(LookupEndPointType lep)
DataTypes_SType SDC.SDCTreeBuilder.AddDataTypesS(CodingType coding)
DataTypes_DEType SDC.SDCTreeBuilder.AddDataTypesDE(ResponseFieldType RF)
References SDC.SDCTreeBuilder.AddBaseTypeItems, SDC.anyType_DEtype, SDC.anyURI_DEtype, SDC.SDCTreeBuilder.AssignQuantifier, SDC.base64Binary_DEtype, SDC.boolean_DEtype, SDC.byte, SDC.byte_DEtype, SDC.DataTypes_DEType, SDC.date_DEtype, SDC.dateTime_DEtype, SDC.dateTimeStamp_DEtype, SDC.decimal, SDC.decimal_DEtype, SDC.double, SDC.double_DEtype, SDC.SDCTreeBuilder.dr, SDC.duration_DEtype, SDC.float, SDC.float_DEtype, SDC.gDay_DEtype, SDC.gMonth_DEtype, SDC.gMonthDay_DEtype, SDC.gYear_DEtype, SDC.gYearMonth_DEtype, SDC.hexBinary_DEtype, SDC.HTML_DEtype, SDC.int, SDC.int_DEtype, SDC.integer_DEtype, SDC.DataTypes_DEType.Item, SDC.long, SDC.long_DEtype, SDC.negativeInteger_DEtype, SDC.nonNegativeInteger_DEtype, SDC.nonPositiveInteger_DEtype, SDC.positiveInteger_DEtype, SDC.ResponseFieldType.Response, SDC.short, SDC.short_DEtype, SDC.string, SDC.string_DEtype, SDC.time_DEtype, SDC.unsignedByte_DEtype, SDC.unsignedInt_DEtype, SDC.unsignedLong_DEtype, SDC.unsignedShort_DEtype, SDC.var, SDC.XML_DEtype, SDC.yearMonthDuration_DEtype.
DataTypes_DEType SDC.SDCTreeBuilder.AddDataTypesDE(ListFieldType lft, QuestionItemBaseTypeResponseTypeEnum dataType)
ContactType SDC.SDCTreeBuilder.AddContact(FileType ft)
Add Contact to the Contacts type inside FileType
cts dr
References SDC.SDCTreeBuilder.AddContactsListToFileType, SDC.SDCTreeBuilder.AddOrganization, SDC.SDCTreeBuilder.AddPerson, SDC.FileType.Contacts, SDC.ContactType, SDC.null, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems, SDC.SDCTreeBuilder.AddDisplayedTypeItems.
ContactType SDC.SDCTreeBuilder.AddContact(DisplayedType dt)
References SDC.DisplayedType.Contact, SDC.ContactType, SDC.null, SDC.var.
ContactsType SDC.SDCTreeBuilder.AddContactsListToFileType(FileType ft)
Add a Contacts grouper to FileType; Contacts contains a List<ContactType>
ft dr
References SDC.FileType.Contacts, SDC.ContactsType, SDC.null.
Referenced by SDC.SDCTreeBuilder.AddContact.
AddressType SDC.SDCTreeBuilder.AddAddress(PersonType pt)
Referenced by SDC.SDCTreeBuilder.AddOrganizationItems.
AddressType SDC.SDCTreeBuilder.AddAddress(OrganizationType ot)
PersonType SDC.SDCTreeBuilder.AddPerson(ContactType contact)
References SDC.SDCTreeBuilder.AddPersonItems, SDC.ContactType, SDC.null, SDC.PersonType, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddContact, SDC.SDCTreeBuilder.AddPerson.
PersonType SDC.SDCTreeBuilder.AddPerson(DisplayedType dt)
References SDC.SDCTreeBuilder.AddPerson, SDC.DisplayedType.Contact, SDC.ContactType, SDC.null, SDC.var.
PersonType SDC.SDCTreeBuilder.AddContactPerson(OrganizationType ot)
References SDC.SDCTreeBuilder.AddPersonItems, SDC.OrganizationType.ContactPerson, SDC.null, SDC.PersonType, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddFillOrganizationItems, SDC.SDCTreeBuilderEcc.AddOrganizationItems, SDC.SDCTreeBuilder.AddOrganizationItems.
PersonType SDC.SDCTreeBuilder.AddPersonItems(PersonType pt)
References SDC.SDCTreeBuilder.dr, SDC.EmailType, SDC.NameType, SDC.string, SDC.string_Stype, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddContactPerson, SDC.SDCTreeBuilder.AddPerson.
NameType SDC.SDCTreeBuilder.AddPersonName(PersonType pt)
JobType SDC.SDCTreeBuilder.AddJob(PersonType pt)
EmailType SDC.SDCTreeBuilder.AddEmail(OrganizationType ot)
EmailType SDC.SDCTreeBuilder.AddEmail(PersonType pt)
PhoneType SDC.SDCTreeBuilder.AddPhone(OrganizationType ot)
IdentifierType SDC.SDCTreeBuilder.AddIdentifier(OrganizationType ot)
anyURI_Stype SDC.SDCTreeBuilder.AddWebURL(OrganizationType ot)
OrganizationType SDC.SDCTreeBuilder.AddOrganization(ContactType contact)
References SDC.SDCTreeBuilder.AddOrganizationItems, SDC.OrganizationType, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddContact.
OrganizationType SDC.SDCTreeBuilder.AddOrganization(JobType job)
References SDC.SDCTreeBuilder.AddOrganizationItems, SDC.OrganizationType, SDC.var.
OrganizationType SDC.SDCTreeBuilder.AddOrganizationItems(OrganizationType ot)
References SDC.SDCTreeBuilder.AddAddress, SDC.SDCTreeBuilder.AddContactPerson, SDC.SDCTreeBuilder.dr, SDC.EmailType, SDC.IdentifierType, SDC.PhoneNumberType, SDC.PhoneType, SDC.string, SDC.string_Stype, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddOrganization.
DisplayedType SDC.SDCTreeBuilder.AddDisplayedItem< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.DisplayedType, SDC.var.
SectionItemType SDC.SDCTreeBuilder.AddSection< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddRepeatingTypeItems, SDC.SectionItemType, SDC.var.
QuestionItemType SDC.SDCTreeBuilder.AddQuestion< T >(T T_Parent, ItemType qType)
References SDC.SDCTreeBuilder.AddListFieldToQuestion, SDC.SDCTreeBuilder.AddRepeatingTypeItems, SDC.SDCTreeBuilder.AddResponseField, SDC.SDCTreeBuilder.dr, SDC.QuestionItemType, SDC.var.
InjectFormType SDC.SDCTreeBuilder.AddInjectedForm< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.dr, SDC.InjectFormType, SDC.string, SDC.var.
ButtonItemType SDC.SDCTreeBuilder.AddButtonAction< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.ButtonItemType, SDC.var.
ChildItemsType SDC.SDCTreeBuilder.AddChildItems< T >(T T_Parent)
References SDC.ChildItemsType, SDC.null.
RichTextType SDC.SDCTreeBuilder.AddOtherText(DisplayedType dt)
References SDC.SDCTreeBuilder.AddHTML, SDC.null, SDC.DisplayedType.OtherText, SDC.RichTextType, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems, SDC.SDCTreeBuilder.AddDisplayedTypeItems.
LinkType SDC.SDCTreeBuilder.AddLink(DisplayedType dt)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.AddHTML, SDC.anyURI_Stype, SDC.SDCTreeBuilder.dr, SDC.DisplayedType.Link, SDC.LinkType, SDC.null, SDC.RichTextType, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddDisplayedTypeItems.
BlobType SDC.SDCTreeBuilder.AddBlob(DisplayedType dt)
References SDC.SDCTreeBuilder.AddHTML, SDC.anyURI_Stype, SDC.base64Binary_DEtype, SDC.BlobType, SDC.SDCTreeBuilder.dr, SDC.RichTextType, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddDisplayedTypeItems.
IfThenType SDC.SDCTreeBuilder.AddOnEvent(DisplayedType dt)
IfThenType SDC.SDCTreeBuilder.AddOnEnter(DisplayedType dt)
OnEventType SDC.SDCTreeBuilder.AddOnExit(DisplayedType dt)
WatchedPropertyType SDC.SDCTreeBuilder.AddActivateIf(DisplayedType dt)
WatchedPropertyType SDC.SDCTreeBuilder.AddDeActivateIf(DisplayedType dt)
UnitsType SDC.SDCTreeBuilder.AddUnits(CodingType cf)
+CodedValues
References SDC.UnitsType, SDC.var.
CodeMatchType SDC.SDCTreeBuilder.AddCodeMatch(CodingType cf)
References SDC.CodeMatchType, SDC.var.
RichTextType SDC.SDCTreeBuilder.AddCodeText(CodingType cf)
References SDC.RichTextType, SDC.var.
CodeSystemType SDC.SDCTreeBuilder.AddCodeSystem(CodingType code)
References SDC.SDCTreeBuilder.AddCodeSystemItems, SDC.CodeSystemType, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddCodedValue, SDC.SDCTreeBuilder.AddCodedValue.
CodeSystemType SDC.SDCTreeBuilder.AddCodeSystem(ListFieldType lf)
References SDC.SDCTreeBuilder.AddCodeSystemItems, SDC.CodeSystemType, SDC.var.
CodeSystemType SDC.SDCTreeBuilder.AddCodeSystemItems(CodeSystemType cs)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.dr, SDC.string.
Referenced by SDC.SDCTreeBuilder.AddCodeSystem.
CodingType SDC.SDCTreeBuilder.AddCodedValue(DisplayedType dt)
References SDC.SDCTreeBuilder.AddCodeSystem, SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilder.AddHTML, SDC.CodeMatchType, SDC.CodingType, SDC.SDCTreeBuilder.dr, SDC.RichTextType, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddDisplayedTypeItems.
CodingType SDC.SDCTreeBuilder.AddCodedValue(LookupEndPointType lep)
Handles Response derived from a LookupEndpoint
lep LookupEndPointType dr DataRow
References SDC.SDCTreeBuilder.AddCodeSystem, SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilder.AddHTML, SDC.CodeMatchType, SDC.CodingType, SDC.SDCTreeBuilder.dr, SDC.RichTextType, SDC.string, SDC.var.
List<CodingType> SDC.SDCTreeBuilder.AddCodingList(DisplayedType dt)
References SDC.DisplayedType.CodedValue, SDC.null.
Referenced by SDC.SDCTreeBuilderEcc.AddCodedValue, SDC.SDCTreeBuilder.AddCodedValue.
List<CodingType> SDC.SDCTreeBuilder.AddCodingList(LookupEndPointType ep)
References SDC.null, SDC.LookupEndPointType.ResponseValue.
void SDC.SDCTreeBuilder.AddActionToThenType(ThenType thenType)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems.
ListFieldType SDC.SDCTreeBuilder.AddListFieldToQuestion(QuestionItemType q)
+List
Referenced by SDC.SDCTreeBuilderEcc.AddListMemberToQuestion, SDC.SDCTreeBuilder.AddListMemberToQuestion, SDC.SDCTreeBuilderEcc.AddQuestion< T >, SDC.SDCTreeBuilder.AddQuestion< T >.
ListType SDC.SDCTreeBuilder.AddListToListField(ListFieldType listField)
References SDC.ListType.DisplayedItem_List, SDC.ListFieldType.List_Item, SDC.ListType, SDC.null.
Referenced by SDC.SDCTreeBuilderEcc.AddListMemberToQuestion, SDC.SDCTreeBuilder.AddListMemberToQuestion, SDC.SDCTreeBuilder.AddQuestion< T >.
void SDC.SDCTreeBuilder.AddListItemProperties(ListItemType li)
References SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.SDCTreeBuilder.AddListItemResponseField, SDC.SDCTreeBuilder.dr, SDC.string.
Referenced by SDC.SDCTreeBuilder.AddListItemToList.
DisplayedType SDC.SDCTreeBuilder.AddListMemberToQuestion(QuestionItemType qNode)
References SDC.SDCTreeBuilder.AddDisplayedItemToList, SDC.SDCTreeBuilder.AddListFieldToQuestion, SDC.SDCTreeBuilder.AddListItemToList, SDC.SDCTreeBuilder.AddListToListField, SDC.DisplayedType, SDC.SDCTreeBuilder.dr, SDC.int, SDC.QuestionItemBaseType.ListField_Item, SDC.null, SDC.var.
ListItemType SDC.SDCTreeBuilder.AddListItemToList(ListType list)
References SDC.SDCTreeBuilder.AddListItemProperties, SDC.SDCTreeBuilder.AddListItemResponseField, SDC.ListItemType, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddFillListItemToQuestion, SDC.SDCTreeBuilderEcc.AddListMemberToQuestion, SDC.SDCTreeBuilder.AddListMemberToQuestion.
DisplayedType SDC.SDCTreeBuilder.AddDisplayedItemToList(ListType list)
References SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.DisplayedType, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddListMemberToQuestion, SDC.SDCTreeBuilder.AddListMemberToQuestion.
ResponseFieldType SDC.SDCTreeBuilder.AddResponseField(QuestionItemType q)
+Create Response Items
Referenced by SDC.SDCTreeBuilder.AddQuestion< T >.
ListItemResponseFieldType SDC.SDCTreeBuilder.AddListItemResponseField(ListItemType li)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.AddResponseItems, SDC.SDCTreeBuilder.dr, SDC.ListItemResponseFieldType, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddListItemProperties, SDC.SDCTreeBuilder.AddListItemToList.
ResponseFieldType SDC.SDCTreeBuilder.AddResponseItems(ResponseFieldType rf)
References SDC.string, SDC.string_DEtype, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddListItemResponseField, SDC.SDCTreeBuilder.AddListItemResponseField.
BaseType SDC.SDCTreeBuilder.AddDataTypeToResponseType(ResponseFieldType dd)
void SDC.SDCTreeBuilder.AddResponseHistoryToQuestion(QuestionItemType q)
References SDC.SDCTreeBuilder.AddReplacedResponseToResponseHistory, SDC.QuestionItemBaseType.ResponseHistory.
void SDC.SDCTreeBuilder.AddReplacedResponseToResponseHistory(List< ResponseChangeType > respChange)
Referenced by SDC.SDCTreeBuilder.AddResponseHistoryToQuestion.
LookupEndPointType SDC.SDCTreeBuilder.AddEndpointToQuestion(DisplayedType nodeToAdd, DisplayedType parentNode)
Add LookupEndpoint to Question w ListField.
RulesType SDC.SDCTreeBuilder.AddRuleToDisplayedType(DisplayedType parent)
+Rules
Tenum SDC.SDCTreeBuilder.ConvertStringToEnum< Tenum >(string inputString)
Converts the string expression of an enum value to the desired type. Example: var qType= reeBuilder.ConvertStringToEnum<ItemType>("answer");
Tenum The enum type that the inputString will be converted into. inputString The string that must represent one of the Tenum enumerated values; not case sensitive
ActSendMessageType SDC.SDCTreeBuilder.AddActSendMessage(ThenType tt)
References SDC.ActSendMessageType, SDC.ThenType.Items, SDC.null, SDC.string, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
UnitsType SDC.SDCTreeBuilder.AddUnits< T >(T t)
References SDC.SDCTreeBuilder.dr, SDC.string, SDC.UnitsType, SDC.var.
UnitsType SDC.SDCTreeBuilder.AddUnits(ResponseFieldType rf)
References SDC.UnitsType, SDC.var.
abstract ItemTypeEnum SDC.SDCTreeBuilder.GetEccRowTypeEnum(string strRowType)
abstract QuestionEnum SDC.SDCTreeBuilder.GetEccQuestionTypeEnum(string strRowType)
virtual FormDesignType SDC.SDCTreeBuilder.CreateFormDesignTree()
//make sure FormDesign has injected and primed ITreeBuilder and IFormDesignDataSet objects
References SDC.SDCTreeBuilder.AddFillListItemToQuestion, SDC.SDCTreeBuilder.AddListNoteToQuestion, SDC.FormDesignType.Body, SDC.SDCTreeBuilder.dr, SDC.SDCTreeBuilder.drFormDesign, SDC.SDCTreeBuilder.dtFormDesign, SDC.FormDesignType.Footer, SDC.SDCTreeBuilder.FormDesign, SDC.SDCHelpers.GetParentIETypeNode, SDC.FormDesignType.Header, SDC.SDCTreeBuilder.InitRow, SDC.ListItemType, SDC.null, SDC.QuestionItemType, SDC.SectionItemType, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc.
virtual String SDC.SDCTreeBuilder.GetTemplateByCkey(String formDesignID, out String BESTfilename, String USERfilename)
Gets template by Ckey
formDesignID Ckey of template to get BESTfilename The preferred file name. Use USERfilename in preference to the Database supplied filename USERfilename The preferred filename, if available retirns FormDesign XML or "" if an error occursTemplate XML
References SDC.SDCTreeBuilder.SerializeFormDesignTree.
virtual String SDC.SDCTreeBuilder.SerializeFormDesignTree()
Creates template with information from data tables
templateVersion Data table with information about the template version templateItems Data table with information about the template items templateProcedures Data table with information about the template procedures Template Xml
References SDC.SDCTreeBuilder.FormDesign, SDC.null, SDC.var.
Referenced by SDC.SDCTreeBuilder.GetTemplateByCkey.
virtual SectionItemType SDC.SDCTreeBuilder.AddBody(Boolean fillData=false, string id=null)
References SDC.FormDesignType.Body, SDC.SDCTreeBuilder.FormDesign, SDC.IdentifiedExtensionType.ID, SDC.null, SDC.SectionItemType.
virtual SectionItemType SDC.SDCTreeBuilder.AddHeader(Boolean fillData=false, string id=null)
References SDC.SDCTreeBuilder.FormDesign, SDC.FormDesignType.Header, SDC.IdentifiedExtensionType.ID, SDC.null, SDC.SectionItemType.
Referenced by SDC.SDCTreeBuilderEcc.CreateHeader.
virtual SectionItemType SDC.SDCTreeBuilder.AddFooter(Boolean fillData=false, string id=null)
References SDC.FormDesignType.Footer, SDC.SDCTreeBuilder.FormDesign, SDC.IdentifiedExtensionType.ID, SDC.null, SDC.SectionItemType.
Referenced by SDC.SDCTreeBuilderEcc.CreateFooter.
virtual RepeatingType SDC.SDCTreeBuilder.FillRepeatingTypeItems(RepeatingType rt, Boolean fillData=true)
References SDC.SDCTreeBuilder.FillRepeatingTypeItemData.
abstract RepeatingType SDC.SDCTreeBuilder.FillRepeatingTypeItemData(RepeatingType rt)
Referenced by SDC.SDCTreeBuilder.FillRepeatingTypeItems.
virtual DisplayedType SDC.SDCTreeBuilder.FillDisplayedTypeItems(DisplayedType dt, Boolean fillData=true)
References SDC.SDCTreeBuilder.FillDisplayedTypeItemData.
abstract DisplayedType SDC.SDCTreeBuilder.FillDisplayedTypeItemData(DisplayedType dt)
Referenced by SDC.SDCTreeBuilder.FillDisplayedTypeItems.
virtual IdentifiedExtensionType SDC.SDCTreeBuilder.FillIdentifiedTypeItems(IdentifiedExtensionType iet, Boolean fillData=true)
References SDC.SDCTreeBuilder.FillIdentifiedTypeItemData.
abstract IdentifiedExtensionType SDC.SDCTreeBuilder.FillIdentifiedTypeItemData(IdentifiedExtensionType iet)
Referenced by SDC.SDCTreeBuilder.FillIdentifiedTypeItems.
virtual ExtensionBaseType SDC.SDCTreeBuilder.AddFillExtensionBaseTypeItems(ExtensionBaseType ebt, Boolean fillData=true)
References SDC.SDCTreeBuilder.AddFillComment, SDC.SDCTreeBuilder.AddFillExtension.
Referenced by SDC.SDCTreeBuilderEcc.AddInjectedForm< T >.
virtual BaseType SDC.SDCTreeBuilder.FillBaseTypeItem(BaseType bt, Boolean fillData=true)
References SDC.SDCTreeBuilder.FillBaseTypeItemData.
Referenced by SDC.SDCTreeBuilderEcc.AddFillDataTypesDE.
virtual CommentType SDC.SDCTreeBuilder.AddFillComment(ExtensionBaseType ebtParent, Boolean fillData=true, string comment="")
References SDC.ExtensionBaseType.Comment, SDC.SDCTreeBuilder.FillCommentData, SDC.null.
Referenced by SDC.SDCTreeBuilder.AddFillExtensionBaseTypeItems.
abstract ExtensionType SDC.SDCTreeBuilder.AddFillExtension(ExtensionBaseType ebtParent, Boolean fillData=true, string InXML="")
Referenced by SDC.SDCTreeBuilder.AddFillExtensionBaseTypeItems.
ContactType SDC.SDCTreeBuilder.AddContact(FileType ftParent, Boolean fillData=true)
Add Contact to the Contacts type inside FileType
cts dr
References SDC.SDCTreeBuilder.AddContactsListToFileType, SDC.SDCTreeBuilder.AddFillOrganization, SDC.SDCTreeBuilder.AddPerson, SDC.FileType.Contacts, SDC.ContactType, SDC.null, SDC.var.
ContactType SDC.SDCTreeBuilder.AddContact(DisplayedType dtParent, Boolean fillData=true)
References SDC.DisplayedType.Contact, SDC.ContactType, SDC.null, SDC.var.
ContactsType SDC.SDCTreeBuilder.AddContactsListToFileType(FileType ftParent)
Add a Contacts grouper to FileType; Contacts contains a List<ContactType>
ftParent dr
References SDC.FileType.Contacts, SDC.ContactsType, SDC.null.
virtual AddressType SDC.SDCTreeBuilder.AddFillAddress(PersonType ptParent, Boolean fillData=true)
virtual AddressType SDC.SDCTreeBuilder.AddFillAddress(OrganizationType otParent, Boolean fillData=true)
virtual PersonType SDC.SDCTreeBuilder.AddPerson(ContactType contactParent)
References SDC.SDCTreeBuilder.AddFillPersonItems, SDC.PersonType, SDC.var.
virtual PersonType SDC.SDCTreeBuilder.AddPerson(DisplayedType dtParent)
References SDC.SDCTreeBuilder.AddPerson, SDC.DisplayedType.Contact, SDC.ContactType, SDC.null, SDC.var.
virtual PersonType SDC.SDCTreeBuilder.AddContactPerson(OrganizationType otParent)
References SDC.SDCTreeBuilder.AddFillPersonItems, SDC.OrganizationType.ContactPerson, SDC.null, SDC.PersonType, SDC.var.
virtual PersonType SDC.SDCTreeBuilder.AddFillPersonItems(PersonType pt, Boolean fillData=true)
References SDC.EmailType, SDC.NameType, SDC.string_Stype, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddContactPerson, SDC.SDCTreeBuilder.AddPerson.
virtual OrganizationType SDC.SDCTreeBuilder.AddFillOrganization(ContactType contactParent, Boolean fillData=true)
References SDC.SDCTreeBuilder.AddFillOrganizationItems, SDC.OrganizationType, SDC.var.
Referenced by SDC.SDCTreeBuilder.AddContact.
virtual OrganizationType SDC.SDCTreeBuilder.AddFillOrganization(JobType jobParent, Boolean fillData=true)
References SDC.SDCTreeBuilder.AddFillOrganizationItems, SDC.OrganizationType, SDC.var.
abstract OrganizationType SDC.SDCTreeBuilder.AddFillOrganizationItems(OrganizationType ot, Boolean fillData=true)
Referenced by SDC.SDCTreeBuilder.AddFillOrganization.
virtual DisplayedType SDC.SDCTreeBuilder.AddDisplayedItem< T >(T T_Parent, Boolean fillData=true, string id=null)
References SDC.DisplayedType, SDC.var.
virtual SectionItemType SDC.SDCTreeBuilder.AddSection< T >(T T_Parent, Boolean fillData=true, string id=null)
References SDC.SectionItemType, SDC.var.
abstract SectionBaseType SDC.SDCTreeBuilder.FillSectionBase(SectionBaseType s)
virtual InjectFormType SDC.SDCTreeBuilder.AddInjectedForm< T >(T T_Parent, Boolean fillData=true, string id=null)
References SDC.InjectFormType, SDC.var.
abstract InjectFormType SDC.SDCTreeBuilder.FillInjectedForm(InjectFormType injForm)
ButtonItemType SDC.SDCTreeBuilder.AddButtonAction< T >(T T_Parent, Boolean fillData=true, string id=null)
References SDC.ButtonItemType, SDC.var.
abstract ButtonItemType SDC.SDCTreeBuilder.FillButton(ButtonItemType button)
virtual PropertyType SDC.SDCTreeBuilder.AddProperty(IdentifiedExtensionType dtParent, Boolean fillData=true)
References SDC.null, SDC.ExtensionBaseType.Property, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddPropertyAltText, SDC.SDCTreeBuilderEcc.AddPropertyDescription, SDC.SDCTreeBuilderEcc.AddPropertyInstruction, SDC.SDCTreeBuilderEcc.AddPropertyPopupText, SDC.SDCTreeBuilderEcc.AddPropertyReportText, SDC.SDCTreeBuilderEcc.AddPropertyShortText, SDC.SDCTreeBuilderEcc.AddPropertySpanishText, SDC.SDCTreeBuilderEcc.AddPropertyTooltip, SDC.SDCTreeBuilderEcc.CreateStaticProperty.
abstract PropertyType SDC.SDCTreeBuilder.FillProperty(PropertyType ot, Boolean fillData=true)
virtual LinkType SDC.SDCTreeBuilder.AddLink(DisplayedType dtParent, Boolean fillData=true)
References SDC.DisplayedType.Link, SDC.LinkType, SDC.null, SDC.RichTextType, SDC.var.
abstract LinkType SDC.SDCTreeBuilder.FillLinkText(LinkType lt)
virtual SDC.BlobType SDC.SDCTreeBuilder.AddBlob(DisplayedType dtParent, Boolean fillData=true)
References SDC.DisplayedType.BlobContent, SDC.BlobType, SDC.null, SDC.var.
abstract BlobType SDC.SDCTreeBuilder.FillBlob(BlobType bt)
virtual IfThenType SDC.SDCTreeBuilder.AddOnEvent(DisplayedType dtParent, Boolean fillData=true)
virtual IfThenType SDC.SDCTreeBuilder.AddOnEnter(DisplayedType dtParent, Boolean fillData=true)
virtual OnEventType SDC.SDCTreeBuilder.AddOnExit(DisplayedType dtParent, Boolean fillData=true)
virtual WatchedPropertyType SDC.SDCTreeBuilder.AddActivateIf(DisplayedType dtParent, Boolean fillData=true)
virtual WatchedPropertyType SDC.SDCTreeBuilder.AddDeActivateIf(DisplayedType dtParent, Boolean fillData=true)
abstract CodeSystemType SDC.SDCTreeBuilder.FillCodeSystemItems(CodeSystemType cs)
abstract CodingType SDC.SDCTreeBuilder.AddCodedValue(DisplayedType dtParent, Boolean fillData=true)
abstract CodingType SDC.SDCTreeBuilder.AddCodedValue(LookupEndPointType lepParent, Boolean fillData=true)
Handles Response derived from a LookupEndpoint
lepParent LookupEndPointType dr DataRow
virtual QuestionItemType SDC.SDCTreeBuilder.AddQuestion< T >(T T_Parent, QuestionEnum qType, Boolean fillData=true, string id=null)
References SDC.SDCTreeBuilder.AddListFieldToQuestion, SDC.SDCTreeBuilder.AddListToListField, SDC.SDCTreeBuilder.AddQuestionResponseField, SDC.QuestionItemType, SDC.var.
abstract QuestionItemBaseType SDC.SDCTreeBuilder.FillQuestionItemBase(QuestionItemBaseType q)
abstract ListFieldType SDC.SDCTreeBuilder.FillListField(ListFieldType lf)
abstract ListItemBaseType SDC.SDCTreeBuilder.FillListItemBase(ListItemBaseType li)
virtual DisplayedType SDC.SDCTreeBuilder.AddListNoteToQuestion(QuestionItemType qParent, Boolean fillData=true, string id=null)
References SDC.DisplayedType, SDC.var.
Referenced by SDC.SDCTreeBuilder.CreateFormDesignTree.
virtual ListItemType SDC.SDCTreeBuilder.AddFillListItemToQuestion(QuestionItemType qParent, Boolean fillData=true, string id=null)
References SDC.SDCTreeBuilder.AddListItemToList.
Referenced by SDC.SDCTreeBuilder.CreateFormDesignTree.
virtual DisplayedType SDC.SDCTreeBuilder.xAddDisplayedItemToList(QuestionItemType qParent, Boolean fillData=true, string id=null)
References SDC.DisplayedType, SDC.var.
virtual ListItemResponseFieldType SDC.SDCTreeBuilder.AddListItemResponseField(ListItemBaseType liParent, Boolean fillData=true)
References SDC.SDCTreeBuilder.AddFillResponseFieldItems, SDC.ListItemResponseFieldType, SDC.var.
abstract UnitsType SDC.SDCTreeBuilder.FillUnits(UnitsType ut)
abstract ListItemResponseFieldType SDC.SDCTreeBuilder.FillListItemResponseField(ListItemResponseFieldType lirf)
abstract LookupEndPointType SDC.SDCTreeBuilder.FillLookupEndpoint(LookupEndPointType lep)
abstract ActSendMessageType SDC.SDCTreeBuilder.AddFillActSendMessage(ThenType tt, Boolean fillData=true)
abstract ActActionType SDC.SDCTreeBuilder.AddAction(ThenType tt, Boolean fillData=true)
abstract ActAddCodeType SDC.SDCTreeBuilder.AddAddCode(ThenType tt, Boolean fillData=true)
abstract ActInjectType SDC.SDCTreeBuilder.AddInject(ThenType tt, Boolean fillData=true)
abstract ActShowMessageType SDC.SDCTreeBuilder.AddShowMessage(ThenType tt, Boolean fillData=true)
abstract FuncType SDC.SDCTreeBuilder.AddShowURL(ThenType tt, Boolean fillData=true)
abstract ActShowFormType SDC.SDCTreeBuilder.AddShowForm(ThenType tt, Boolean fillData=true)
abstract ActSaveResponsesType SDC.SDCTreeBuilder.AddSave(ThenType tt, Boolean fillData=true)
abstract ActSendReportType SDC.SDCTreeBuilder.AddShowReport(ThenType tt, Boolean fillData=true)
abstract ActSendMessageType SDC.SDCTreeBuilder.AddSendMessage(ThenType tt, Boolean fillData=true)
abstract ActValidateFormType SDC.SDCTreeBuilder.AddValidateForm(ThenType tt, Boolean fillData=true)
abstract IfThenType SDC.SDCTreeBuilder.AddIfThen(ThenType tt, Boolean fillData=true)
abstract ItemNameType SDC.SDCTreeBuilder.AddCallIfThen(ThenType tt, Boolean fillData=true)
abstract HTML_Stype SDC.SDCTreeBuilder.AddFillHTML(RichTextType rt, Boolean fillData=true, string InXhtml="")
SDC.SDCTreeBuilder.SDCTreeBuilder()
We can initialize dtFormDesign here - can pass initializer into the constructor, also can pass in FormDesignID
virtual FormDesignType SDC.SDCTreeBuilder.CreateFormDesignTree()
//make sure FormDesign has injected and primed ITreeBuilder and IFormDesignDataSet objects
References SDC.SDCTreeBuilder.drFormDesign, SDC.FormDesignType.Footer, SDC.SDCTreeBuilder.FormDesign, SDC.SDCTreeBuilder.FormDesignID, SDC.SDCTreeBuilder.GetRowType, SDC.FormDesignType.Header, SDC.null, SDC.SectionItemType, SDC.string, SDC.var.
virtual void SDC.SDCTreeBuilder.AddTemplateMetadataToForm(IdentifiedExtensionType n, DisplayedType parentNode)
virtual String SDC.SDCTreeBuilder.GetTemplateByCkey(String formDesignID, out String BESTfilename, String USERfilename)
Gets template by Ckey
formDesignID Ckey of template to get BESTfilename The preferred file name. Use USERfilename in preference to the Database supplied filename USERfilename The preferred filename, if available retirns FormDesign XML or "" if an error occursTemplate XML
References SDC.SDCTreeBuilder.FormDesignID, SDC.SDCTreeBuilder.SerializeFormDesignTree, SDC.Trim.
virtual String SDC.SDCTreeBuilder.SerializeFormDesignTree()
Creates template with information from data tables
templateVersion Data table with information about the template version templateItems Data table with information about the template items templateProcedures Data table with information about the template procedures Template Xml
References SDC.SDCTreeBuilder.FormDesign, SDC.null, SDC.var, SDC.SDCTreeBuilder.XsltFileName.
SectionBaseType SDC.SDCTreeBuilder.AddSectionItems(SectionBaseType s)
References SDC.SDCTreeBuilder.AddRepeatingTypeItems, SDC.SDCTreeBuilder.drFormDesign.
virtual RepeatingType SDC.SDCTreeBuilder.AddRepeatingTypeItems(RepeatingType rt)
Base type functions.
virtual DisplayedType SDC.SDCTreeBuilder.AddDisplayedTypeItems(DisplayedType dt)
References SDC.SDCTreeBuilder.AddBlob, SDC.SDCTreeBuilder.AddCodedValue, SDC.SDCTreeBuilder.AddContact, SDC.SDCTreeBuilder.AddIdentifiedTypeItems, SDC.SDCTreeBuilder.AddLink, SDC.SDCTreeBuilder.AddOtherText, SDC.SDCTreeBuilder.drFormDesign, SDC.string.
virtual IdentifiedExtensionType SDC.SDCTreeBuilder.AddIdentifiedTypeItems(IdentifiedExtensionType iet)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.drFormDesign, SDC.string.
ExtensionBaseType SDC.SDCTreeBuilder.AddExtensionBaseTypeItems(ExtensionBaseType ebt)
References SDC.SDCTreeBuilder.AddBaseTypeItems, SDC.SDCTreeBuilder.AddComment, SDC.SDCTreeBuilder.AddExtension.
virtual IdentifiedExtensionType SDC.SDCTreeBuilder.AddBaseTypeItems(IdentifiedExtensionType bt)
References SDC.decimal, SDC.SDCTreeBuilder.drFormDesign, SDC.string.
virtual CommentType SDC.SDCTreeBuilder.AddComment(ExtensionBaseType ebt)
References SDC.ExtensionBaseType.Comment, SDC.CommentType, SDC.SDCTreeBuilder.drFormDesign, SDC.null, SDC.string, SDC.var.
virtual ExtensionType SDC.SDCTreeBuilder.AddExtension(ExtensionBaseType ebt)
References SDC.e, SDC.ExtensionBaseType.Extension, SDC.ExtensionType, SDC.null, SDC.var.
virtual HTML_Stype SDC.SDCTreeBuilder.AddHTML(RichTextType rtf)
References SDC.SDCTreeBuilder.drFormDesign, SDC.HTML_Stype, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
XmlElement SDC.SDCTreeBuilder.StringToXMLElement(string rawXML)
References SDC.var.
virtual WebServiceType SDC.SDCTreeBuilder.AddWebService(LookupEndPointType lep)
virtual DataTypes_SType SDC.SDCTreeBuilder.AddDataTypesS(CodingType coding)
virtual DataTypes_DEType SDC.SDCTreeBuilder.AddDataTypesDE(ResponseFieldType RF)
References SDC.SDCTreeBuilder.AddBaseTypeItems, SDC.anyType_DEtype, SDC.anyURI_DEtype, SDC.SDCTreeBuilder.AssignQuantifier, SDC.base64Binary_DEtype, SDC.boolean_DEtype, SDC.byte, SDC.byte_DEtype, SDC.DataTypes_DEType, SDC.date_DEtype, SDC.dateTime_DEtype, SDC.dateTimeStamp_DEtype, SDC.decimal, SDC.decimal_DEtype, SDC.double, SDC.double_DEtype, SDC.SDCTreeBuilder.drFormDesign, SDC.duration_DEtype, SDC.float, SDC.float_DEtype, SDC.gDay_DEtype, SDC.gMonth_DEtype, SDC.gMonthDay_DEtype, SDC.gYear_DEtype, SDC.gYearMonth_DEtype, SDC.hexBinary_DEtype, SDC.HTML_DEtype, SDC.int, SDC.int_DEtype, SDC.integer_DEtype, SDC.DataTypes_DEType.Item, SDC.long, SDC.long_DEtype, SDC.negativeInteger_DEtype, SDC.nonNegativeInteger_DEtype, SDC.nonPositiveInteger_DEtype, SDC.positiveInteger_DEtype, SDC.ResponseFieldType.Response, SDC.short, SDC.short_DEtype, SDC.string, SDC.string_DEtype, SDC.time_DEtype, SDC.unsignedByte_DEtype, SDC.unsignedInt_DEtype, SDC.unsignedLong_DEtype, SDC.unsignedShort_DEtype, SDC.var, SDC.XML_DEtype, SDC.yearMonthDuration_DEtype.
virtual DataTypes_DEType SDC.SDCTreeBuilder.AddDataTypesDE(ListFieldType lft, QuestionItemBaseTypeResponseTypeEnum dataType)
ContactType SDC.SDCTreeBuilder.AddContact(FileType ft)
Add Contact to the Contacts type inside FileType
cts dr
References SDC.SDCTreeBuilder.AddContactsListToFileType, SDC.SDCTreeBuilder.AddOrganization, SDC.SDCTreeBuilder.AddPerson, SDC.FileType.Contacts, SDC.ContactType, SDC.null, SDC.var.
ContactType SDC.SDCTreeBuilder.AddContact(DisplayedType dt)
References SDC.DisplayedType.Contact, SDC.ContactType, SDC.null, SDC.var.
ContactsType SDC.SDCTreeBuilder.AddContactsListToFileType(FileType ft)
Add a Contacts grouper to FileType; Contacts contains a List<ContactType>
ft dr
References SDC.FileType.Contacts, SDC.ContactsType, SDC.null.
virtual AddressType SDC.SDCTreeBuilder.AddAddress(PersonType pt)
virtual AddressType SDC.SDCTreeBuilder.AddAddress(OrganizationType ot)
PersonType SDC.SDCTreeBuilder.AddPerson(ContactType contact)
References SDC.SDCTreeBuilder.AddPersonItems, SDC.ContactType, SDC.null, SDC.PersonType, SDC.var.
PersonType SDC.SDCTreeBuilder.AddPerson(DisplayedType dt)
References SDC.SDCTreeBuilder.AddPerson, SDC.DisplayedType.Contact, SDC.ContactType, SDC.null, SDC.var.
PersonType SDC.SDCTreeBuilder.AddContactPerson(OrganizationType ot)
References SDC.SDCTreeBuilder.AddPersonItems, SDC.OrganizationType.ContactPerson, SDC.null, SDC.PersonType, SDC.var.
virtual PersonType SDC.SDCTreeBuilder.AddPersonItems(PersonType pt)
References SDC.SDCTreeBuilder.drFormDesign, SDC.EmailType, SDC.NameType, SDC.string, SDC.string_Stype, SDC.var.
virtual NameType SDC.SDCTreeBuilder.AddPersonName(PersonType pt)
virtual JobType SDC.SDCTreeBuilder.AddJob(PersonType pt)
virtual EmailType SDC.SDCTreeBuilder.AddEmail(OrganizationType ot)
virtual EmailType SDC.SDCTreeBuilder.AddEmail(PersonType pt)
virtual PhoneType SDC.SDCTreeBuilder.AddPhone(OrganizationType ot)
virtual PhoneType SDC.SDCTreeBuilder.AddPhone(PersonType ot)
virtual IdentifierType SDC.SDCTreeBuilder.AddIdentifier(OrganizationType ot)
virtual anyURI_Stype SDC.SDCTreeBuilder.AddWebURL(OrganizationType ot)
OrganizationType SDC.SDCTreeBuilder.AddOrganization(ContactType contact)
References SDC.SDCTreeBuilder.AddOrganizationItems, SDC.OrganizationType, SDC.var.
OrganizationType SDC.SDCTreeBuilder.AddOrganization(JobType job)
References SDC.SDCTreeBuilder.AddOrganizationItems, SDC.OrganizationType, SDC.var.
virtual OrganizationType SDC.SDCTreeBuilder.AddOrganizationItems(OrganizationType ot)
References SDC.SDCTreeBuilder.AddAddress, SDC.SDCTreeBuilder.AddContactPerson, SDC.SDCTreeBuilder.drFormDesign, SDC.EmailType, SDC.IdentifierType, SDC.PhoneNumberType, SDC.PhoneType, SDC.string, SDC.string_Stype, SDC.var.
DisplayedType SDC.SDCTreeBuilder.AddDisplayedItem< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.DisplayedType, SDC.var.
SectionItemType SDC.SDCTreeBuilder.AddSection< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddRepeatingTypeItems, SDC.SectionItemType, SDC.var.
virtual QuestionItemType SDC.SDCTreeBuilder.AddQuestion< T >(T T_Parent, ItemType qType)
References SDC.SDCTreeBuilder.AddListFieldToQuestion, SDC.SDCTreeBuilder.AddRepeatingTypeItems, SDC.SDCTreeBuilder.AddResponseField, SDC.SDCTreeBuilder.drFormDesign, SDC.QuestionItemType, SDC.var.
virtual InjectFormType SDC.SDCTreeBuilder.AddInjectedForm< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.drFormDesign, SDC.InjectFormType, SDC.string, SDC.var.
ButtonItemType SDC.SDCTreeBuilder.AddButtonAction< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.ButtonItemType, SDC.var.
ChildItemsType SDC.SDCTreeBuilder.AddChildItems< T >(T T_Parent)
References SDC.ChildItemsType, SDC.null.
RichTextType SDC.SDCTreeBuilder.AddOtherText(DisplayedType dt)
References SDC.SDCTreeBuilder.AddHTML, SDC.null, SDC.DisplayedType.OtherText, SDC.RichTextType, SDC.var.
virtual LinkType SDC.SDCTreeBuilder.AddLink(DisplayedType dt)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.AddHTML, SDC.anyURI_Stype, SDC.SDCTreeBuilder.drFormDesign, SDC.DisplayedType.Link, SDC.LinkType, SDC.null, SDC.RichTextType, SDC.string, SDC.var.
virtual BlobType SDC.SDCTreeBuilder.AddBlob(DisplayedType dt)
References SDC.SDCTreeBuilder.AddHTML, SDC.anyURI_Stype, SDC.base64Binary_DEtype, SDC.BlobType, SDC.SDCTreeBuilder.drFormDesign, SDC.RichTextType, SDC.string, SDC.var.
virtual IfThenType SDC.SDCTreeBuilder.AddOnEvent(DisplayedType dt)
virtual IfThenType SDC.SDCTreeBuilder.AddOnEnter(DisplayedType dt)
virtual OnEventType SDC.SDCTreeBuilder.AddOnExit(DisplayedType dt)
virtual WatchedPropertyType SDC.SDCTreeBuilder.AddActivateIf(DisplayedType dt)
virtual WatchedPropertyType SDC.SDCTreeBuilder.AddDeActivateIf(DisplayedType dt)
UnitsType SDC.SDCTreeBuilder.AddUnits(CodingType cf)
+CodedValues
References SDC.UnitsType, SDC.var.
CodeMatchType SDC.SDCTreeBuilder.AddCodeMatch(CodingType cf)
References SDC.CodeMatchType, SDC.var.
RichTextType SDC.SDCTreeBuilder.AddCodeText(CodingType cf)
References SDC.RichTextType, SDC.var.
CodeSystemType SDC.SDCTreeBuilder.AddCodeSystem(CodingType code)
References SDC.SDCTreeBuilder.AddCodeSystemItems, SDC.CodeSystemType, SDC.var.
CodeSystemType SDC.SDCTreeBuilder.AddCodeSystem(ListFieldType lf)
References SDC.SDCTreeBuilder.AddCodeSystemItems, SDC.CodeSystemType, SDC.var.
virtual CodeSystemType SDC.SDCTreeBuilder.AddCodeSystemItems(CodeSystemType cs)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.drFormDesign, SDC.string.
virtual CodingType SDC.SDCTreeBuilder.AddCodedValue(DisplayedType dt)
References SDC.SDCTreeBuilder.AddCodeSystem, SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilder.AddHTML, SDC.CodeMatchType, SDC.CodingType, SDC.SDCTreeBuilder.drFormDesign, SDC.RichTextType, SDC.string, SDC.var.
virtual CodingType SDC.SDCTreeBuilder.AddCodedValue(LookupEndPointType lep)
Handles Response derived from a LookupEndpoint
lep LookupEndPointType dr DataRow
References SDC.SDCTreeBuilder.AddCodeSystem, SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilder.AddHTML, SDC.CodeMatchType, SDC.CodingType, SDC.SDCTreeBuilder.drFormDesign, SDC.RichTextType, SDC.string, SDC.var.
List<CodingType> SDC.SDCTreeBuilder.AddCodingList(DisplayedType dt)
References SDC.DisplayedType.CodedValue, SDC.null.
List<CodingType> SDC.SDCTreeBuilder.AddCodingList(LookupEndPointType ep)
References SDC.null, SDC.LookupEndPointType.ResponseValue.
void SDC.SDCTreeBuilder.AddActionToThenType(ThenType thenType)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems.
ListFieldType SDC.SDCTreeBuilder.AddListFieldToQuestion(QuestionItemType q)
+List
ListType SDC.SDCTreeBuilder.AddListToListField(ListFieldType listField)
References SDC.ListType.DisplayedItem_List, SDC.ListFieldType.List_Item, SDC.ListType, SDC.null.
virtual void SDC.SDCTreeBuilder.AddListItemProperties(ListItemType li)
References SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.SDCTreeBuilder.AddListItemResponseField.
virtual DisplayedType SDC.SDCTreeBuilder.AddListMemberToQuestion(QuestionItemType qNode)
References SDC.SDCTreeBuilder.AddDisplayedItemToList, SDC.SDCTreeBuilder.AddListFieldToQuestion, SDC.SDCTreeBuilder.AddListItemToList, SDC.SDCTreeBuilder.AddListToListField, SDC.QuestionItemBaseType.ListField_Item, SDC.null, SDC.var.
ListItemType SDC.SDCTreeBuilder.AddListItemToList(ListType list)
References SDC.SDCTreeBuilder.AddListItemProperties, SDC.SDCTreeBuilder.AddListItemResponseField, SDC.ListItemType, SDC.var.
DisplayedType SDC.SDCTreeBuilder.AddDisplayedItemToList(ListType list)
References SDC.SDCTreeBuilder.AddDisplayedTypeItems, SDC.DisplayedType, SDC.var.
virtual ResponseFieldType SDC.SDCTreeBuilder.AddResponseField(QuestionItemType q)
+Create Response Items
virtual ListItemResponseFieldType SDC.SDCTreeBuilder.AddListItemResponseField(ListItemType li)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.AddResponseItems, SDC.ListItemResponseFieldType, SDC.var.
ResponseFieldType SDC.SDCTreeBuilder.AddResponseItems(ResponseFieldType rf)
References SDC.string, SDC.string_DEtype, SDC.var.
virtual IdentifiedExtensionType SDC.SDCTreeBuilder.AddDataTypeToResponseType(ResponseFieldType dd)
virtual void SDC.SDCTreeBuilder.AddResponseHistoryToQuestion(QuestionItemType q)
References SDC.SDCTreeBuilder.AddReplacedResponseToResponseHistory, SDC.QuestionItemBaseType.ResponseHistory.
virtual void SDC.SDCTreeBuilder.AddReplacedResponseToResponseHistory(List< ResponseChangeType > respChange)
virtual LookupEndPointType SDC.SDCTreeBuilder.AddEndpointToQuestion(DisplayedType nodeToAdd, DisplayedType parentNode)
Add LookupEndpoint to Question w ListField.
virtual RulesType SDC.SDCTreeBuilder.AddRuleToDisplayedType(DisplayedType parent)
+Rules
Tenum SDC.SDCTreeBuilder.ConvertStringToEnum< Tenum >(string inputString)
Converts the string expression of an enum value to the desired type. Example: var qType= reeBuilder.ConvertStringToEnum<ItemType>("answer");
Tenum The enum type that the inputString will be converted into. inputString The string that must represent one of the Tenum enumerated values; not case sensitive
virtual ActSendMessageType SDC.SDCTreeBuilder.AddActSendMessage(ThenType tt)
References SDC.ActSendMessageType, SDC.SDCTreeBuilder.drFormDesign, SDC.ThenType.Items, SDC.null, SDC.string, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
virtual UnitsType SDC.SDCTreeBuilder.AddUnits< T >(T t)
References SDC.UnitsType, SDC.var.
UnitsType SDC.SDCTreeBuilder.AddUnits(ResponseFieldType rf)
References SDC.UnitsType, SDC.var.
dtQuantEnum SDC.SDCTreeBuilder.AssignQuantifier(DataRow dr)
References SDC.null, SDC.string, SDC.var.
SDC.SDCTreeBuilder.SDCTreeBuilder()
We can initialize dtFormDesign here - can pass initializer into the constructor, also can pass in FormDesignID.
References SDC.SDCTreeBuilder.Order.
abstract SectionEnum SDC.SDCTreeBuilder.GetSectionType(string strSectionType)
abstract void SDC.SDCTreeBuilder.InitRow(out ItemTypeEnum rowType, out string parentID, out string type)
Referenced by SDC.SDCTreeBuilder.CreateFormDesignTree.
dtQuantEnum SDC.SDCTreeBuilder.AssignQuantifier(DataRow dr)
References SDC.null, SDC.string, SDC.var.
RichTextType SDC.SDCTreeBuilder.AddRichText< T >(T t, string strHTML="", string val="")
References SDC.SDCTreeBuilder.AddHTML, SDC.RichTextType, SDC.var.
RichTextType SDC.SDCTreeBuilder.AddRichText< T >(T t, string strHTML="", string val="")
References SDC.SDCTreeBuilder.AddHTML, SDC.RichTextType, SDC.var.
abstract DisplayedType SDC.SDCTreeBuilder.FillDisplayedTypeListItemData(DisplayedType dt, string title, QuestionItemType qNode)
abstract BaseType SDC.SDCTreeBuilder.FillBaseTypeItemData(BaseType btParent)
Referenced by SDC.SDCTreeBuilder.FillBaseTypeItem.
abstract CommentType SDC.SDCTreeBuilder.FillCommentData(BaseType bt, string comment)
Referenced by SDC.SDCTreeBuilder.AddFillComment.
abstract FuncType SDC.SDCTreeBuilder.AddFillWebService(LookupEndPointType lepParent, Boolean fillData=true)
abstract FuncType SDC.SDCTreeBuilder.FillWebService(FuncType wst)
abstract DataTypes_SType SDC.SDCTreeBuilder.AddFillDataTypesS(CodingType codingParent)
abstract DataTypes_DEType SDC.SDCTreeBuilder.AddFillDataTypesDE(ResponseFieldType rfParent)
Referenced by SDC.SDCTreeBuilder.AddFillResponseFieldItems.
abstract DataTypes_DEType SDC.SDCTreeBuilder.AddFillDataTypesDE(ListFieldType lftParent, SectionBaseTypeResponseTypeEnum dataType)
virtual DataTypes_DEType SDC.SDCTreeBuilder.AddDataTypesDE(ResponseFieldType rfParent, object value, ItemChoiceType dataTypeEnum=ItemChoiceType.@string, dtQuantEnum quantifierEnum=dtQuantEnum.EQ)
References SDC.anyType_DEtype, SDC.anyURI_DEtype, SDC.base64Binary_DEtype, SDC.boolean_DEtype, SDC.byte, SDC.byte_DEtype, SDC.DataTypes_DEType, SDC.date_DEtype, SDC.dateTime, SDC.dateTime_DEtype, SDC.dateTimeStamp, SDC.dateTimeStamp_DEtype, SDC.decimal, SDC.decimal_DEtype, SDC.double, SDC.double_DEtype, SDC.duration_DEtype, SDC.float, SDC.float_DEtype, SDC.gDay_DEtype, SDC.gMonth_DEtype, SDC.gMonthDay_DEtype, SDC.gYear_DEtype, SDC.gYearMonth_DEtype, SDC.hexBinary_DEtype, SDC.HTML_DEtype, SDC.int, SDC.int_DEtype, SDC.integer_DEtype, SDC.long, SDC.long_DEtype, SDC.negativeInteger_DEtype, SDC.nonNegativeInteger_DEtype, SDC.nonPositiveInteger_DEtype, SDC.null, SDC.positiveInteger_DEtype, SDC.ResponseFieldType.Response, SDC.short, SDC.short_DEtype, SDC.string, SDC.string_DEtype, SDC.time_DEtype, SDC.unsignedByte_DEtype, SDC.unsignedInt_DEtype, SDC.unsignedLong_DEtype, SDC.unsignedShort_DEtype, SDC.var, SDC.XML_DEtype, SDC.yearMonthDuration_DEtype.
virtual dtQuantEnum SDC.SDCTreeBuilder.AssignQuantifier()
References SDC.SDCTreeBuilder.FillQuantifier, SDC.null, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddDataTypesDE, SDC.SDCTreeBuilder.AddDataTypesDE, SDC.SDCTreeBuilderEcc.AddFillDataTypesDE.
abstract string SDC.SDCTreeBuilder.FillQuantifier()
Referenced by SDC.SDCTreeBuilder.AssignQuantifier.
virtual XmlElement SDC.SDCTreeBuilder.StringToXMLElement(string rawXML)
References SDC.var.
abstract ContactType SDC.SDCTreeBuilder.FillContact(ContactType ct)
abstract AddressType SDC.SDCTreeBuilder.FillAddress(AddressType at)
abstract NameType SDC.SDCTreeBuilder.FillPersonName(PersonType pt)
abstract JobType SDC.SDCTreeBuilder.FillPersonJob(JobType pt)
abstract EmailType SDC.SDCTreeBuilder.FillPersonEmail(EmailType ot)
abstract PhoneType SDC.SDCTreeBuilder.FillPersonPhone(PhoneType ot)
abstract string_Stype SDC.SDCTreeBuilder.FillPersonUsage(string_Stype ut)
abstract IdentifierType SDC.SDCTreeBuilder.FillPersonIdentifier(IdentifierType ot)
abstract string SDC.SDCTreeBuilder.FillPersonWebURL(string ot)
abstract string SDC.SDCTreeBuilder.FillPersonAddress1(string ot)
abstract string SDC.SDCTreeBuilder.FillPersonAddress2(string ot)
abstract string SDC.SDCTreeBuilder.FillPersonAddress3(string ot)
abstract string SDC.SDCTreeBuilder.FillPersonAddress4(string ot)
abstract string_Stype SDC.SDCTreeBuilder.FillOrgName(string_Stype ot)
abstract string SDC.SDCTreeBuilder.FillOrgDept(string ot)
abstract string SDC.SDCTreeBuilder.FillOrgAddress1(string ot)
abstract string SDC.SDCTreeBuilder.FillOrgAddress2(string ot)
abstract string SDC.SDCTreeBuilder.FillOrgAddress3(string ot)
abstract string SDC.SDCTreeBuilder.FillOrgAddress4(string ot)
abstract NameType SDC.SDCTreeBuilder.FillOrgName(PersonType pt)
abstract string SDC.SDCTreeBuilder.FillOrgRole(string rt)
abstract EmailType SDC.SDCTreeBuilder.FillOrgEmail(EmailType et)
abstract PhoneType SDC.SDCTreeBuilder.FillOrgPhone(PhoneType ot)
abstract string SDC.SDCTreeBuilder.FillOrgUsage(string ut)
abstract IdentifierType SDC.SDCTreeBuilder.FillOrgIdentifier(IdentifierType ot)
abstract anyURI_Stype SDC.SDCTreeBuilder.FillOrgWebURL(anyURI_Stype wt)
abstract SectionItemType SDC.SDCTreeBuilder.FillSection(SectionItemType s)
virtual ChildItemsType SDC.SDCTreeBuilder.AddChildItemsNode< T >(T T_Parent, bool fillData=true)
References SDC.ChildItemsType, SDC.ChildItemsType.ListOfItems, SDC.null.
abstract IfThenType SDC.SDCTreeBuilder.FillOnEvent(IfThenType oe)
abstract IfThenType SDC.SDCTreeBuilder.FillOnEnter(IfThenType oe)
abstract OnEventType SDC.SDCTreeBuilder.FillOnExit(OnEventType oe)
abstract WatchedPropertyType SDC.SDCTreeBuilder.FillActivateIf(WatchedPropertyType oe)
abstract WatchedPropertyType SDC.SDCTreeBuilder.FillDeActivateIf(WatchedPropertyType oeParent)
virtual UnitsType SDC.SDCTreeBuilder.AddUnits(CodingType ctParent, Boolean fillData=true)
+CodedValues
References SDC.UnitsType, SDC.var.
virtual CodeMatchType SDC.SDCTreeBuilder.AddCodeMatch(CodingType ctParent, Boolean fillData=true)
References SDC.CodeMatchType, SDC.var.
virtual RichTextType SDC.SDCTreeBuilder.AddCodeText(CodingType ctParent, Boolean fillData=true)
References SDC.RichTextType, SDC.var.
virtual CodeSystemType SDC.SDCTreeBuilder.AddFillCodeSystem(CodingType ctParent, Boolean fillData=true)
References SDC.CodeSystemType, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddCodedValue.
virtual CodeSystemType SDC.SDCTreeBuilder.AddFillCodeSystem(ListFieldType lfParent, Boolean fillData=true)
References SDC.CodeSystemType, SDC.var.
abstract CodingType SDC.SDCTreeBuilder.FillCodedValue(DisplayedType dt)
virtual List<CodingType> SDC.SDCTreeBuilder.AddCodingList(DisplayedType dtParent, Boolean fillData=true)
References SDC.DisplayedType.CodedValue, SDC.null.
virtual List<CodingType> SDC.SDCTreeBuilder.AddCodingList(LookupEndPointType epParent)
References SDC.null, SDC.LookupEndPointType.ResponseValue.
virtual void SDC.SDCTreeBuilder.AddFillActionToThenType(ThenType thenType, Boolean fillData=true)
virtual ListFieldType SDC.SDCTreeBuilder.AddListFieldToQuestion(QuestionItemType qParent)
+List
virtual ListType SDC.SDCTreeBuilder.AddListToListField(ListFieldType listFieldParent)
References SDC.ListType.DisplayedItem_List, SDC.ListFieldType.List_Item, SDC.ListType, SDC.null.
virtual ListItemType SDC.SDCTreeBuilder.AddListItemToList(QuestionItemType qParent, Boolean fillData=true, string id=null)
References SDC.ListItemType, SDC.var.
virtual ResponseFieldType SDC.SDCTreeBuilder.AddQuestionResponseField(QuestionItemType qParent, Boolean fillData=true)
+Create Response Items
Referenced by SDC.SDCTreeBuilder.AddQuestion< T >.
virtual ResponseFieldType SDC.SDCTreeBuilder.AddFillResponseFieldItems(ResponseFieldType rfParent, Boolean fillData=true)
References SDC.SDCTreeBuilder.AddFillDataTypesDE, SDC.SDCTreeBuilder.AddFillResponseUnits, SDC.SDCTreeBuilder.FillResponseField.
Referenced by SDC.SDCTreeBuilder.AddListItemResponseField.
abstract ResponseFieldType SDC.SDCTreeBuilder.FillResponseField(ResponseFieldType rf)
Referenced by SDC.SDCTreeBuilder.AddFillResponseFieldItems.
abstract UnitsType SDC.SDCTreeBuilder.AddFillResponseUnits(ResponseFieldType rfParent, Boolean fillData=true)
Referenced by SDC.SDCTreeBuilder.AddFillResponseFieldItems.
virtual LookupEndPointType SDC.SDCTreeBuilder.AddEndpointToQuestion(ListFieldType listFieldParent, Boolean fillData=true)
Add LookupEndpoint to Question w ListField.
virtual RulesType SDC.SDCTreeBuilder.AddRuleToDisplayedType(DisplayedType parent)
+Rules
abstract ItemType SDC.SDCTreeBuilder.GetRowType(string strRowType)
Referenced by SDC.SDCTreeBuilder.CreateFormDesignTree.