SDC::ActShowMessageType
List<RichTextType> SDC.ActShowMessageType._message
string SDC.ActShowMessageType::_alertLevel
string SDC.ActShowMessageType::_alertType
string SDC.ActShowMessageType::_messageType
string SDC.ActShowMessageType::_messageCode
BindingList<RichTextType> SDC.ActShowMessageType._message
ObjectChangeTracker SDC.ActShowMessageType.changeTrackerField
static XmlSerializer SDC.ActShowMessageType::serializer
virtual List<RichTextType> SDC.ActShowMessageType.Message
string SDC.ActShowMessageType::alertLevel
Referenced by SDC.ActShowMessageType.ShouldSerializealertLevel.
string SDC.ActShowMessageType::alertType
Referenced by SDC.ActShowMessageType.ShouldSerializealertType.
string SDC.ActShowMessageType::messageType
Referenced by SDC.ActShowMessageType.ShouldSerializemessageType.
string SDC.ActShowMessageType::messageCode
Referenced by SDC.ActShowMessageType.ShouldSerializemessageCode.
static XmlSerializer SDC.ActShowMessageType::Serializer
Referenced by SDC.ActShowMessageType.Deserialize.
virtual BindingList<RichTextType> SDC.ActShowMessageType.Message
ObjectChangeTracker SDC.ActShowMessageType.ChangeTracker
SDC.ActShowMessageType.ActShowMessageType()
SDC.ActShowMessageType.ActShowMessageType(ThenType parentNode)
SDC.ActShowMessageType.ActShowMessageType()
virtual bool SDC.ActShowMessageType.ShouldSerializeMessage()
Test whether Message should be serialized
References SDC.null.
virtual bool SDC.ActShowMessageType.ShouldSerializealertLevel()
Test whether alertLevel should be serialized
virtual bool SDC.ActShowMessageType.ShouldSerializealertType()
Test whether alertType should be serialized
virtual bool SDC.ActShowMessageType.ShouldSerializemessageType()
Test whether messageType should be serialized
virtual bool SDC.ActShowMessageType.ShouldSerializemessageCode()
Test whether messageCode should be serialized
virtual string SDC.ActShowMessageType.Serialize(System.Text.Encoding encoding)
Serializes current ActShowMessageType object into an XML string
string XML value
virtual string SDC.ActShowMessageType.Serialize()
Referenced by SDC.ActShowMessageType.SaveToFile.
virtual bool SDC.ActShowMessageType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ActShowMessageType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ActShowMessageType.SaveToFile.
virtual bool SDC.ActShowMessageType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ActShowMessageType.SaveToFile(string fileName)
virtual void SDC.ActShowMessageType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ActShowMessageType.ShouldSerializealertLevel()
Test whether alertLevel should be serialized
References SDC.ActShowMessageType.alertLevel.
virtual bool SDC.ActShowMessageType.ShouldSerializealertType()
Test whether alertType should be serialized
References SDC.ActShowMessageType.alertType.
virtual bool SDC.ActShowMessageType.ShouldSerializemessageType()
Test whether messageType should be serialized
References SDC.ActShowMessageType.messageType.
virtual bool SDC.ActShowMessageType.ShouldSerializemessageCode()
Test whether messageCode should be serialized
References SDC.ActShowMessageType.messageCode.
virtual string SDC.ActShowMessageType.Serialize()
Serializes current ActShowMessageType object into an XML string
string XML value
virtual bool SDC.ActShowMessageType.SaveToFile(string fileName, out Exception exception)
Serializes current ActShowMessageType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ActShowMessageType.SaveToFile.
virtual void SDC.ActShowMessageType.SaveToFile(string fileName)
References SDC.null, SDC.ActShowMessageType.Serialize.
virtual ActShowMessageType SDC.ActShowMessageType.Clone()
Create a clone of this ActShowMessageType object
static bool SDC.ActShowMessageType.Deserialize(string input, out ActShowMessageType obj, out System.Exception exception)
Deserializes workflow markup into an ActShowMessageType object
input string workflow markup to deserialize obj Output ActShowMessageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActShowMessageType.Deserialize, SDC.ActShowMessageType.LoadFromFile.
static bool SDC.ActShowMessageType.Deserialize(string input, out ActShowMessageType obj)
References SDC.null.
static new ActShowMessageType SDC.ActShowMessageType.Deserialize(string input)
References SDC.null.
static ActShowMessageType SDC.ActShowMessageType.Deserialize(System.IO.Stream s)
static bool SDC.ActShowMessageType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ActShowMessageType obj, out System.Exception exception)
Deserializes xml markup from file into an ActShowMessageType object
fileName string xml file to load and deserialize obj Output ActShowMessageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActShowMessageType.LoadFromFile.
static bool SDC.ActShowMessageType.LoadFromFile(string fileName, out ActShowMessageType obj, out System.Exception exception)
static bool SDC.ActShowMessageType.LoadFromFile(string fileName, out ActShowMessageType obj)
References SDC.null.
static ActShowMessageType SDC.ActShowMessageType.LoadFromFile(string fileName)
static new ActShowMessageType SDC.ActShowMessageType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ActShowMessageType.Deserialize(string input, out ActShowMessageType obj, out Exception exception)
Deserializes workflow markup into an ActShowMessageType object
input string workflow markup to deserialize obj Output ActShowMessageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActShowMessageType.Deserialize, SDC.null.
static bool SDC.ActShowMessageType.Deserialize(string input, out ActShowMessageType obj)
References SDC.ActShowMessageType.Deserialize, SDC.null.
static new ActShowMessageType SDC.ActShowMessageType.Deserialize(string input)
References SDC.null, SDC.ActShowMessageType.Serializer.
static ActShowMessageType SDC.ActShowMessageType.Deserialize(Stream s)
References SDC.ActShowMessageType.Serializer.
static bool SDC.ActShowMessageType.LoadFromFile(string fileName, out ActShowMessageType obj, out Exception exception)
Deserializes xml markup from file into an ActShowMessageType object
fileName string xml file to load and deserialize obj Output ActShowMessageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActShowMessageType.LoadFromFile, SDC.null.
static bool SDC.ActShowMessageType.LoadFromFile(string fileName, out ActShowMessageType obj)
References SDC.ActShowMessageType.LoadFromFile, SDC.null.
static new ActShowMessageType SDC.ActShowMessageType.LoadFromFile(string fileName)
References SDC.ActShowMessageType.Deserialize, SDC.null.