SDC::PersonType
NameType SDC.PersonType::_personName
Referenced by SDC.PersonType.ShouldSerializePersonName.
List<NameType> SDC.PersonType._aliasName
List<JobType> SDC.PersonType._job
List<AddressType> SDC.PersonType._streetAddress
List<EmailType> SDC.PersonType._email
List<PhoneType> SDC.PersonType._phone
List<anyURI_Stype> SDC.PersonType._webURL
string_Stype SDC.PersonType::_role
Referenced by SDC.PersonType.ShouldSerializeRole.
List<IdentifierType> SDC.PersonType._identifier
string_Stype SDC.PersonType::_usage
Referenced by SDC.PersonType.ShouldSerializeUsage.
BindingList<JobType> SDC.PersonType._job
BindingList<AddressType> SDC.PersonType._streetAddress
BindingList<EmailType> SDC.PersonType._email
BindingList<PhoneType> SDC.PersonType._phone
BindingList<anyURI_Stype> SDC.PersonType._webURL
BindingList<IdentifierType> SDC.PersonType._identifier
ObjectChangeTracker SDC.PersonType.changeTrackerField
static XmlSerializer SDC.PersonType::serializer
NameType SDC.PersonType::PersonName
virtual List<NameType> SDC.PersonType.AliasName
virtual List<JobType> SDC.PersonType.Job
virtual List<AddressType> SDC.PersonType.StreetAddress
virtual List<EmailType> SDC.PersonType.Email
virtual List<PhoneType> SDC.PersonType.Phone
virtual List<anyURI_Stype> SDC.PersonType.WebURL
string_Stype SDC.PersonType::Role
Role of the person, e.g., creator, copyright holder, accreditor, certifier, curator, etc.
virtual List<IdentifierType> SDC.PersonType.Identifier
string_Stype SDC.PersonType::Usage
When this person should be contacted.
static XmlSerializer SDC.PersonType::Serializer
Referenced by SDC.PersonType.Deserialize.
virtual BindingList<JobType> SDC.PersonType.Job
virtual BindingList<AddressType> SDC.PersonType.StreetAddress
virtual BindingList<EmailType> SDC.PersonType.Email
virtual BindingList<PhoneType> SDC.PersonType.Phone
virtual BindingList<anyURI_Stype> SDC.PersonType.WebURL
virtual BindingList<IdentifierType> SDC.PersonType.Identifier
ObjectChangeTracker SDC.PersonType.ChangeTracker
SDC.PersonType.PersonType()
SDC.PersonType.PersonType(BaseType parentNode)
SDC.PersonType.PersonType()
virtual bool SDC.PersonType.ShouldSerializeAliasName()
Test whether AliasName should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializeJob()
Test whether Job should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializeStreetAddress()
Test whether StreetAddress should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializeEmail()
Test whether Email should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializePhone()
Test whether Phone should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializeWebURL()
Test whether WebURL should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializeIdentifier()
Test whether Identifier should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializePersonName()
Test whether PersonName should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializeRole()
Test whether Role should be serialized
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.null.
virtual string SDC.PersonType.Serialize(System.Text.Encoding encoding)
Serializes current PersonType object into an XML string
string XML value
virtual string SDC.PersonType.Serialize()
Referenced by SDC.PersonType.SaveToFile.
virtual bool SDC.PersonType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current PersonType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.PersonType.SaveToFile.
virtual bool SDC.PersonType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.PersonType.SaveToFile(string fileName)
virtual void SDC.PersonType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.PersonType.ShouldSerializePersonName()
Test whether PersonName should be serialized
References SDC.PersonType._personName, SDC.null.
virtual bool SDC.PersonType.ShouldSerializeRole()
Test whether Role should be serialized
References SDC.PersonType._role, SDC.null.
virtual bool SDC.PersonType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.PersonType._usage, SDC.null.
virtual string SDC.PersonType.Serialize()
Serializes current PersonType object into an XML string
string XML value
virtual bool SDC.PersonType.SaveToFile(string fileName, out Exception exception)
Serializes current PersonType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.PersonType.SaveToFile.
virtual void SDC.PersonType.SaveToFile(string fileName)
References SDC.null, SDC.PersonType.Serialize.
virtual PersonType SDC.PersonType.Clone()
Create a clone of this PersonType object
static bool SDC.PersonType.Deserialize(string input, out PersonType obj, out System.Exception exception)
Deserializes workflow markup into an PersonType object
input string workflow markup to deserialize obj Output PersonType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PersonType.Deserialize, SDC.PersonType.LoadFromFile.
static bool SDC.PersonType.Deserialize(string input, out PersonType obj)
References SDC.null.
static new PersonType SDC.PersonType.Deserialize(string input)
References SDC.null.
static PersonType SDC.PersonType.Deserialize(System.IO.Stream s)
static bool SDC.PersonType.LoadFromFile(string fileName, System.Text.Encoding encoding, out PersonType obj, out System.Exception exception)
Deserializes xml markup from file into an PersonType object
fileName string xml file to load and deserialize obj Output PersonType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PersonType.LoadFromFile.
static bool SDC.PersonType.LoadFromFile(string fileName, out PersonType obj, out System.Exception exception)
static bool SDC.PersonType.LoadFromFile(string fileName, out PersonType obj)
References SDC.null.
static PersonType SDC.PersonType.LoadFromFile(string fileName)
static new PersonType SDC.PersonType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.PersonType.Deserialize(string input, out PersonType obj, out Exception exception)
Deserializes workflow markup into an PersonType object
input string workflow markup to deserialize obj Output PersonType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.PersonType.Deserialize, SDC.null.
static bool SDC.PersonType.Deserialize(string input, out PersonType obj)
References SDC.PersonType.Deserialize, SDC.null.
static new PersonType SDC.PersonType.Deserialize(string input)
References SDC.null, SDC.PersonType.Serializer.
static PersonType SDC.PersonType.Deserialize(Stream s)
References SDC.PersonType.Serializer.
static bool SDC.PersonType.LoadFromFile(string fileName, out PersonType obj, out Exception exception)
Deserializes xml markup from file into an PersonType object
fileName string xml file to load and deserialize obj Output PersonType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.PersonType.LoadFromFile, SDC.null.
static bool SDC.PersonType.LoadFromFile(string fileName, out PersonType obj)
References SDC.PersonType.LoadFromFile, SDC.null.
static new PersonType SDC.PersonType.LoadFromFile(string fileName)
References SDC.PersonType.Deserialize, SDC.null.