SDC::IfThenType
PredicateType SDC.IfThenType._if
Referenced by SDC.IfThenType.ShouldSerializeIf.
ThenType SDC.IfThenType::_then
Referenced by SDC.IfThenType.ShouldSerializeThen.
ThenType SDC.IfThenType::_else
Referenced by SDC.IfThenType.ShouldSerializeElse.
IfType SDC.IfThenType._if
ObjectChangeTracker SDC.IfThenType.changeTrackerField
static XmlSerializer SDC.IfThenType::serializer
virtual PredicateType SDC.IfThenType.If
*** TODO: Add choice with optional wrapper element that can be used to group predicate statements and combine with a Boolean operator.
ThenType SDC.IfThenType::Then
ThenType SDC.IfThenType::Else
static XmlSerializer SDC.IfThenType::Serializer
Referenced by SDC.IfThenType.Deserialize.
virtual IfType SDC.IfThenType.If
ObjectChangeTracker SDC.IfThenType.ChangeTracker
SDC.IfThenType.IfThenType()
SDC.IfThenType.IfThenType(BaseType parentNode)
SDC.IfThenType.IfThenType()
virtual bool SDC.IfThenType.ShouldSerializeIf()
Test whether If should be serialized
References SDC.IfThenType._if, SDC.null.
virtual bool SDC.IfThenType.ShouldSerializeThen()
Test whether Then should be serialized
References SDC.IfThenType._then, SDC.null.
virtual bool SDC.IfThenType.ShouldSerializeElse()
Test whether Else should be serialized
References SDC.IfThenType._else, SDC.null.
virtual string SDC.IfThenType.Serialize(System.Text.Encoding encoding)
Serializes current IfThenType object into an XML string
string XML value
virtual string SDC.IfThenType.Serialize()
Referenced by SDC.IfThenType.SaveToFile.
virtual bool SDC.IfThenType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current IfThenType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.IfThenType.SaveToFile.
virtual bool SDC.IfThenType.SaveToFile(string fileName, out System.Exception exception)
References SDC.IfThenType.SaveToFile.
virtual void SDC.IfThenType.SaveToFile(string fileName)
References SDC.IfThenType.SaveToFile.
virtual void SDC.IfThenType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.IfThenType.Serialize.
virtual bool SDC.IfThenType.ShouldSerializeIf()
Test whether If should be serialized
References SDC.IfThenType._if, SDC.null.
virtual bool SDC.IfThenType.ShouldSerializeThen()
Test whether Then should be serialized
References SDC.IfThenType._then, SDC.null.
virtual bool SDC.IfThenType.ShouldSerializeElse()
Test whether Else should be serialized
References SDC.IfThenType._else, SDC.null.
virtual string SDC.IfThenType.Serialize()
Serializes current IfThenType object into an XML string
string XML value
virtual bool SDC.IfThenType.SaveToFile(string fileName, out Exception exception)
Serializes current IfThenType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.IfThenType.SaveToFile.
virtual void SDC.IfThenType.SaveToFile(string fileName)
References SDC.null, SDC.IfThenType.Serialize.
virtual IfThenType SDC.IfThenType.Clone()
Create a clone of this IfThenType object
static bool SDC.IfThenType.Deserialize(string input, out IfThenType obj, out System.Exception exception)
Deserializes workflow markup into an IfThenType object
input string workflow markup to deserialize obj Output IfThenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.IfThenType.Deserialize, SDC.IfThenType.LoadFromFile.
static bool SDC.IfThenType.Deserialize(string input, out IfThenType obj)
References SDC.IfThenType.Deserialize, SDC.null.
static new IfThenType SDC.IfThenType.Deserialize(string input)
References SDC.null.
static IfThenType SDC.IfThenType.Deserialize(System.IO.Stream s)
References SDC.IfThenType.Serializer.
static bool SDC.IfThenType.LoadFromFile(string fileName, System.Text.Encoding encoding, out IfThenType obj, out System.Exception exception)
Deserializes xml markup from file into an IfThenType object
fileName string xml file to load and deserialize obj Output IfThenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.IfThenType.LoadFromFile.
static bool SDC.IfThenType.LoadFromFile(string fileName, out IfThenType obj, out System.Exception exception)
References SDC.IfThenType.LoadFromFile.
static bool SDC.IfThenType.LoadFromFile(string fileName, out IfThenType obj)
References SDC.IfThenType.LoadFromFile, SDC.null.
static IfThenType SDC.IfThenType.LoadFromFile(string fileName)
References SDC.IfThenType.LoadFromFile.
static new IfThenType SDC.IfThenType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.IfThenType.Deserialize, SDC.null.
static bool SDC.IfThenType.Deserialize(string input, out IfThenType obj, out Exception exception)
Deserializes workflow markup into an IfThenType object
input string workflow markup to deserialize obj Output IfThenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.IfThenType.Deserialize, SDC.null.
static bool SDC.IfThenType.Deserialize(string input, out IfThenType obj)
References SDC.IfThenType.Deserialize, SDC.null.
static new IfThenType SDC.IfThenType.Deserialize(string input)
References SDC.null, SDC.IfThenType.Serializer.
static IfThenType SDC.IfThenType.Deserialize(Stream s)
References SDC.IfThenType.Serializer.
static bool SDC.IfThenType.LoadFromFile(string fileName, out IfThenType obj, out Exception exception)
Deserializes xml markup from file into an IfThenType object
fileName string xml file to load and deserialize obj Output IfThenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.IfThenType.LoadFromFile, SDC.null.
static bool SDC.IfThenType.LoadFromFile(string fileName, out IfThenType obj)
References SDC.IfThenType.LoadFromFile, SDC.null.
static new IfThenType SDC.IfThenType.LoadFromFile(string fileName)
References SDC.IfThenType.Deserialize, SDC.null.