SDC::QuestionItemBaseType
ListFieldType SDC.QuestionItemBaseType::ListField_Item
ListField (ListFieldType)
Referenced by SDC.SDCTreeBuilderEcc.AddListMemberToQuestion, SDC.SDCTreeBuilder.AddListMemberToQuestion.
QuestionEnum SDC.QuestionItemBaseType.QuestionType
ResponseFieldType SDC.QuestionItemBaseType::ResponseField_Item
ResponseField (ResponseFieldType)
ExtensionBaseType SDC.QuestionItemBaseType::Item
QuestionItemBaseType class constructor
bool SDC.QuestionItemBaseType::readOnly
If is set to true, the this field may not be edited by the user, and any default values set by template should be considered part of the stored data set responses, and transmitted by the SubmitForm transaction.
virtual SectionBaseTypeResponseTypeEnum SDC.QuestionItemBaseType.responseTypeEnum
bool SDC.QuestionItemBaseType::responseTypeEnumSpecified
virtual SectionBaseTypeResponseStatusEnum SDC.QuestionItemBaseType.responseStatusEnum
bool SDC.QuestionItemBaseType::responseStatusEnumSpecified
static XmlSerializer SDC.QuestionItemBaseType::Serializer
Referenced by SDC.QuestionItemBaseType.Deserialize.
virtual BindingList<ResponseChangeType> SDC.QuestionItemBaseType.ResponseHistory
For recording metadata and changes about the current answer and any previous (replaced) answers to the current question. Each ResponseHistory element is single unit of response(s), taking place at the same time, to the question. It records the person who made the change, the DateTime of the change, and the the previous ReplacedResponse. ReplacedResponse includes each answer selection or fill-in response to the question at the time the change was submitted.
Referenced by SDC.SDCTreeBuilderEcc.AddResponseHistoryToQuestion, SDC.SDCTreeBuilder.AddResponseHistoryToQuestion.
virtual QuestionItemBaseTypeResponseTypeEnum SDC.QuestionItemBaseType.responseTypeEnum
virtual QuestionItemBaseTypeResponseStatusEnum SDC.QuestionItemBaseType.responseStatusEnum
ObjectChangeTracker SDC.QuestionItemBaseType.ChangeTracker
bool SDC.QuestionItemBaseType::_shouldSerializereadOnly
Referenced by SDC.QuestionItemBaseType.ShouldSerializereadOnly.
ExtensionBaseType SDC.QuestionItemBaseType::_item
Referenced by SDC.QuestionItemBaseType.ShouldSerializeItem.
bool SDC.QuestionItemBaseType::_readOnly
Referenced by SDC.QuestionItemBaseType.QuestionItemBaseType, SDC.QuestionItemBaseType.ShouldSerializereadOnly.
System.Nullable<SectionBaseTypeResponseTypeEnum> SDC.QuestionItemBaseType._responseTypeEnum
System.Nullable<SectionBaseTypeResponseStatusEnum> SDC.QuestionItemBaseType._responseStatusEnum
BindingList<ResponseChangeType> SDC.QuestionItemBaseType._responseHistory
System.Nullable<QuestionItemBaseTypeResponseTypeEnum> SDC.QuestionItemBaseType._responseTypeEnum
System.Nullable<QuestionItemBaseTypeResponseStatusEnum> SDC.QuestionItemBaseType._responseStatusEnum
ObjectChangeTracker SDC.QuestionItemBaseType.changeTrackerField
static XmlSerializer SDC.QuestionItemBaseType::serializer
SDC.QuestionItemBaseType.QuestionItemBaseType()
SDC.QuestionItemBaseType.QuestionItemBaseType(BaseType parentNode, bool fillData=true, string id=null)
References SDC.QuestionItemBaseType.FillQuestionItemBase.
QuestionItemBaseType SDC.QuestionItemBaseType.FillQuestionItemBase()
+Replaced in original class: protected QuestionItemBaseType() { }
Referenced by SDC.QuestionItemBaseType.QuestionItemBaseType.
void SDC.QuestionItemBaseType.Fill_QuestionItemBaseType()
virtual bool SDC.QuestionItemBaseType.ShouldSerializereadOnly()
Test whether readOnly should be serialized
References SDC.QuestionItemBaseType._readOnly, SDC.QuestionItemBaseType._shouldSerializereadOnly.
virtual bool SDC.QuestionItemBaseType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.QuestionItemBaseType._item, SDC.null.
virtual string SDC.QuestionItemBaseType.Serialize(System.Text.Encoding encoding)
Serializes current QuestionItemBaseType object into an XML string
string XML value
virtual string SDC.QuestionItemBaseType.Serialize()
Referenced by SDC.QuestionItemBaseType.SaveToFile.
virtual bool SDC.QuestionItemBaseType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current QuestionItemBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.QuestionItemBaseType.SaveToFile.
virtual bool SDC.QuestionItemBaseType.SaveToFile(string fileName, out System.Exception exception)
References SDC.QuestionItemBaseType.SaveToFile.
virtual void SDC.QuestionItemBaseType.SaveToFile(string fileName)
References SDC.QuestionItemBaseType.SaveToFile.
virtual void SDC.QuestionItemBaseType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.QuestionItemBaseType.Serialize.
SDC.QuestionItemBaseType.QuestionItemBaseType()
QuestionItemBaseType class constructor
References SDC.QuestionItemBaseType._readOnly.
virtual bool SDC.QuestionItemBaseType.ShouldSerializereadOnly()
Test whether readOnly should be serialized
References SDC.QuestionItemBaseType._readOnly, SDC.QuestionItemBaseType._shouldSerializereadOnly.
virtual bool SDC.QuestionItemBaseType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.QuestionItemBaseType._item, SDC.null.
virtual string SDC.QuestionItemBaseType.Serialize()
Serializes current QuestionItemBaseType object into an XML string
string XML value
virtual bool SDC.QuestionItemBaseType.SaveToFile(string fileName, out Exception exception)
Serializes current QuestionItemBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.QuestionItemBaseType.SaveToFile.
virtual void SDC.QuestionItemBaseType.SaveToFile(string fileName)
References SDC.null, SDC.QuestionItemBaseType.Serialize.
virtual QuestionItemBaseType SDC.QuestionItemBaseType.Clone()
Create a clone of this QuestionItemBaseType object
static bool SDC.QuestionItemBaseType.Deserialize(string input, out QuestionItemBaseType obj, out System.Exception exception)
Deserializes workflow markup into an QuestionItemBaseType object
input string workflow markup to deserialize obj Output QuestionItemBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.QuestionItemBaseType.Deserialize, SDC.QuestionItemBaseType.LoadFromFile.
static bool SDC.QuestionItemBaseType.Deserialize(string input, out QuestionItemBaseType obj)
References SDC.QuestionItemBaseType.Deserialize, SDC.null.
static new QuestionItemBaseType SDC.QuestionItemBaseType.Deserialize(string input)
References SDC.null.
static QuestionItemBaseType SDC.QuestionItemBaseType.Deserialize(System.IO.Stream s)
References SDC.QuestionItemBaseType.Serializer.
static bool SDC.QuestionItemBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding, out QuestionItemBaseType obj, out System.Exception exception)
Deserializes xml markup from file into an QuestionItemBaseType object
fileName string xml file to load and deserialize obj Output QuestionItemBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.QuestionItemBaseType.LoadFromFile.
static bool SDC.QuestionItemBaseType.LoadFromFile(string fileName, out QuestionItemBaseType obj, out System.Exception exception)
References SDC.QuestionItemBaseType.LoadFromFile.
static bool SDC.QuestionItemBaseType.LoadFromFile(string fileName, out QuestionItemBaseType obj)
References SDC.QuestionItemBaseType.LoadFromFile, SDC.null.
static QuestionItemBaseType SDC.QuestionItemBaseType.LoadFromFile(string fileName)
References SDC.QuestionItemBaseType.LoadFromFile.
static new QuestionItemBaseType SDC.QuestionItemBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.QuestionItemBaseType.Deserialize, SDC.null.
static bool SDC.QuestionItemBaseType.Deserialize(string input, out QuestionItemBaseType obj, out Exception exception)
Deserializes workflow markup into an QuestionItemBaseType object
input string workflow markup to deserialize obj Output QuestionItemBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.QuestionItemBaseType.Deserialize, SDC.null.
static bool SDC.QuestionItemBaseType.Deserialize(string input, out QuestionItemBaseType obj)
References SDC.QuestionItemBaseType.Deserialize, SDC.null.
static new QuestionItemBaseType SDC.QuestionItemBaseType.Deserialize(string input)
References SDC.null, SDC.QuestionItemBaseType.Serializer.
static QuestionItemBaseType SDC.QuestionItemBaseType.Deserialize(Stream s)
References SDC.QuestionItemBaseType.Serializer.
static bool SDC.QuestionItemBaseType.LoadFromFile(string fileName, out QuestionItemBaseType obj, out Exception exception)
Deserializes xml markup from file into an QuestionItemBaseType object
fileName string xml file to load and deserialize obj Output QuestionItemBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.QuestionItemBaseType.LoadFromFile, SDC.null.
static bool SDC.QuestionItemBaseType.LoadFromFile(string fileName, out QuestionItemBaseType obj)
References SDC.QuestionItemBaseType.LoadFromFile, SDC.null.
static new QuestionItemBaseType SDC.QuestionItemBaseType.LoadFromFile(string fileName)
References SDC.QuestionItemBaseType.Deserialize, SDC.null.