SDC::negativeInteger_Stype
string SDC.negativeInteger_Stype::_val
dtQuantEnum SDC.negativeInteger_Stype::_quantEnum
Referenced by SDC.negativeInteger_Stype.negativeInteger_Stype.
ObjectChangeTracker SDC.negativeInteger_Stype.changeTrackerField
static XmlSerializer SDC.negativeInteger_Stype::serializer
string SDC.negativeInteger_Stype::val
Referenced by SDC.negativeInteger_Stype.ShouldSerializeval.
dtQuantEnum SDC.negativeInteger_Stype::quantEnum
static XmlSerializer SDC.negativeInteger_Stype::Serializer
Referenced by SDC.negativeInteger_Stype.Deserialize.
ObjectChangeTracker SDC.negativeInteger_Stype.ChangeTracker
SDC.negativeInteger_Stype.negativeInteger_Stype()
SDC.negativeInteger_Stype.negativeInteger_Stype(BaseType parentNode)
virtual bool SDC.negativeInteger_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.negativeInteger_Stype.val.
virtual string SDC.negativeInteger_Stype.Serialize(System.Text.Encoding encoding)
Serializes current negativeInteger_Stype object into an XML string
string XML value
virtual string SDC.negativeInteger_Stype.Serialize()
Referenced by SDC.negativeInteger_Stype.SaveToFile.
virtual bool SDC.negativeInteger_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current negativeInteger_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.negativeInteger_Stype.SaveToFile.
virtual bool SDC.negativeInteger_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.negativeInteger_Stype.SaveToFile.
virtual void SDC.negativeInteger_Stype.SaveToFile(string fileName)
References SDC.negativeInteger_Stype.SaveToFile.
virtual void SDC.negativeInteger_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.negativeInteger_Stype.Serialize.
SDC.negativeInteger_Stype.negativeInteger_Stype()
negativeInteger_Stype class constructor
References SDC.negativeInteger_Stype._quantEnum.
virtual bool SDC.negativeInteger_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.negativeInteger_Stype.val.
virtual string SDC.negativeInteger_Stype.Serialize()
Serializes current negativeInteger_Stype object into an XML string
string XML value
virtual bool SDC.negativeInteger_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current negativeInteger_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.negativeInteger_Stype.SaveToFile.
virtual void SDC.negativeInteger_Stype.SaveToFile(string fileName)
References SDC.null, SDC.negativeInteger_Stype.Serialize.
virtual negativeInteger_Stype SDC.negativeInteger_Stype.Clone()
Create a clone of this negativeInteger_Stype object
static bool SDC.negativeInteger_Stype.Deserialize(string input, out negativeInteger_Stype obj, out System.Exception exception)
Deserializes workflow markup into an negativeInteger_Stype object
input string workflow markup to deserialize obj Output negativeInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.negativeInteger_Stype.Deserialize, SDC.negativeInteger_Stype.LoadFromFile.
static bool SDC.negativeInteger_Stype.Deserialize(string input, out negativeInteger_Stype obj)
References SDC.negativeInteger_Stype.Deserialize, SDC.null.
static new negativeInteger_Stype SDC.negativeInteger_Stype.Deserialize(string input)
References SDC.null.
static negativeInteger_Stype SDC.negativeInteger_Stype.Deserialize(System.IO.Stream s)
References SDC.negativeInteger_Stype.Serializer.
static bool SDC.negativeInteger_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out negativeInteger_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an negativeInteger_Stype object
fileName string xml file to load and deserialize obj Output negativeInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.negativeInteger_Stype.LoadFromFile.
static bool SDC.negativeInteger_Stype.LoadFromFile(string fileName, out negativeInteger_Stype obj, out System.Exception exception)
References SDC.negativeInteger_Stype.LoadFromFile.
static bool SDC.negativeInteger_Stype.LoadFromFile(string fileName, out negativeInteger_Stype obj)
References SDC.negativeInteger_Stype.LoadFromFile, SDC.null.
static negativeInteger_Stype SDC.negativeInteger_Stype.LoadFromFile(string fileName)
References SDC.negativeInteger_Stype.LoadFromFile.
static new negativeInteger_Stype SDC.negativeInteger_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.negativeInteger_Stype.Deserialize, SDC.null.
static bool SDC.negativeInteger_Stype.Deserialize(string input, out negativeInteger_Stype obj, out Exception exception)
Deserializes workflow markup into an negativeInteger_Stype object
input string workflow markup to deserialize obj Output negativeInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.negativeInteger_Stype.Deserialize, SDC.null.
static bool SDC.negativeInteger_Stype.Deserialize(string input, out negativeInteger_Stype obj)
References SDC.negativeInteger_Stype.Deserialize, SDC.null.
static new negativeInteger_Stype SDC.negativeInteger_Stype.Deserialize(string input)
References SDC.null, SDC.negativeInteger_Stype.Serializer.
static negativeInteger_Stype SDC.negativeInteger_Stype.Deserialize(Stream s)
References SDC.negativeInteger_Stype.Serializer.
static bool SDC.negativeInteger_Stype.LoadFromFile(string fileName, out negativeInteger_Stype obj, out Exception exception)
Deserializes xml markup from file into an negativeInteger_Stype object
fileName string xml file to load and deserialize obj Output negativeInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.negativeInteger_Stype.LoadFromFile, SDC.null.
static bool SDC.negativeInteger_Stype.LoadFromFile(string fileName, out negativeInteger_Stype obj)
References SDC.negativeInteger_Stype.LoadFromFile, SDC.null.
static new negativeInteger_Stype SDC.negativeInteger_Stype.LoadFromFile(string fileName)
References SDC.negativeInteger_Stype.Deserialize, SDC.null.