SDC::AddressType
string_Stype SDC.AddressType::_addressType1
Referenced by SDC.AddressType.ShouldSerializeAddressType1.
List<string_Stype> SDC.AddressType._internalAddress
List<string_Stype> SDC.AddressType._addressLine
string_Stype SDC.AddressType::_city
Referenced by SDC.AddressType.ShouldSerializeCity.
string_Stype SDC.AddressType::_jurisdiction
Referenced by SDC.AddressType.ShouldSerializeJurisdiction.
string_Stype SDC.AddressType::_state
Referenced by SDC.AddressType.ShouldSerializeState.
string_Stype SDC.AddressType::_postalCode
Referenced by SDC.AddressType.ShouldSerializePostalCode.
string_Stype SDC.AddressType::_country
Referenced by SDC.AddressType.ShouldSerializeCountry.
string_Stype SDC.AddressType::_usage
Referenced by SDC.AddressType.ShouldSerializeUsage.
BindingList<string_Stype> SDC.AddressType._internalAddress
BindingList<string_Stype> SDC.AddressType._addressLine
ObjectChangeTracker SDC.AddressType.changeTrackerField
static XmlSerializer SDC.AddressType::serializer
string_Stype SDC.AddressType::AddressType1
virtual List<string_Stype> SDC.AddressType.InternalAddress
Address instructions for directing mail within an organizations buildings or corporate infrastructure.
virtual List<string_Stype> SDC.AddressType.AddressLine
Address instructions for directing mail to a street address.
string_Stype SDC.AddressType::City
string_Stype SDC.AddressType::Jurisdiction
Other optional locale identifier.
string_Stype SDC.AddressType::State
State, Province, etc.
string_Stype SDC.AddressType::PostalCode
Local postal code, e.g., zip code.
string_Stype SDC.AddressType::Country
**Need list of official country codes or text?
string_Stype SDC.AddressType::Usage
When this address should be used
static XmlSerializer SDC.AddressType::Serializer
Referenced by SDC.AddressType.Deserialize.
virtual BindingList<string_Stype> SDC.AddressType.InternalAddress
virtual BindingList<string_Stype> SDC.AddressType.AddressLine
ObjectChangeTracker SDC.AddressType.ChangeTracker
SDC.AddressType.AddressType()
SDC.AddressType.AddressType(BaseType parentNode)
SDC.AddressType.AddressType()
virtual bool SDC.AddressType.ShouldSerializeInternalAddress()
Test whether InternalAddress should be serialized
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializeAddressLine()
Test whether AddressLine should be serialized
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializeAddressType1()
Test whether AddressType1 should be serialized
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializeCity()
Test whether City should be serialized
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializeJurisdiction()
Test whether Jurisdiction should be serialized
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializeState()
Test whether State should be serialized
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializePostalCode()
Test whether PostalCode should be serialized
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializeCountry()
Test whether Country should be serialized
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.null.
virtual string SDC.AddressType.Serialize(System.Text.Encoding encoding)
Serializes current AddressType object into an XML string
string XML value
virtual string SDC.AddressType.Serialize()
Referenced by SDC.AddressType.SaveToFile.
virtual bool SDC.AddressType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current AddressType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.AddressType.SaveToFile.
virtual bool SDC.AddressType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.AddressType.SaveToFile(string fileName)
virtual void SDC.AddressType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.AddressType.ShouldSerializeAddressType1()
Test whether AddressType1 should be serialized
References SDC.AddressType._addressType1, SDC.null.
virtual bool SDC.AddressType.ShouldSerializeCity()
Test whether City should be serialized
References SDC.AddressType._city, SDC.null.
virtual bool SDC.AddressType.ShouldSerializeJurisdiction()
Test whether Jurisdiction should be serialized
References SDC.AddressType._jurisdiction, SDC.null.
virtual bool SDC.AddressType.ShouldSerializeState()
Test whether State should be serialized
References SDC.AddressType._state, SDC.null.
virtual bool SDC.AddressType.ShouldSerializePostalCode()
Test whether PostalCode should be serialized
References SDC.AddressType._postalCode, SDC.null.
virtual bool SDC.AddressType.ShouldSerializeCountry()
Test whether Country should be serialized
References SDC.AddressType._country, SDC.null.
virtual bool SDC.AddressType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.AddressType._usage, SDC.null.
virtual string SDC.AddressType.Serialize()
Serializes current AddressType object into an XML string
string XML value
virtual bool SDC.AddressType.SaveToFile(string fileName, out Exception exception)
Serializes current AddressType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.AddressType.SaveToFile.
virtual void SDC.AddressType.SaveToFile(string fileName)
References SDC.null, SDC.AddressType.Serialize.
virtual AddressType SDC.AddressType.Clone()
Create a clone of this AddressType object
static bool SDC.AddressType.Deserialize(string input, out AddressType obj, out System.Exception exception)
Deserializes workflow markup into an AddressType object
input string workflow markup to deserialize obj Output AddressType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AddressType.Deserialize, SDC.AddressType.LoadFromFile.
static bool SDC.AddressType.Deserialize(string input, out AddressType obj)
References SDC.null.
static new AddressType SDC.AddressType.Deserialize(string input)
References SDC.null.
static AddressType SDC.AddressType.Deserialize(System.IO.Stream s)
static bool SDC.AddressType.LoadFromFile(string fileName, System.Text.Encoding encoding, out AddressType obj, out System.Exception exception)
Deserializes xml markup from file into an AddressType object
fileName string xml file to load and deserialize obj Output AddressType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AddressType.LoadFromFile.
static bool SDC.AddressType.LoadFromFile(string fileName, out AddressType obj, out System.Exception exception)
static bool SDC.AddressType.LoadFromFile(string fileName, out AddressType obj)
References SDC.null.
static AddressType SDC.AddressType.LoadFromFile(string fileName)
static new AddressType SDC.AddressType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.AddressType.Deserialize(string input, out AddressType obj, out Exception exception)
Deserializes workflow markup into an AddressType object
input string workflow markup to deserialize obj Output AddressType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.AddressType.Deserialize, SDC.null.
static bool SDC.AddressType.Deserialize(string input, out AddressType obj)
References SDC.AddressType.Deserialize, SDC.null.
static new AddressType SDC.AddressType.Deserialize(string input)
References SDC.null, SDC.AddressType.Serializer.
static AddressType SDC.AddressType.Deserialize(Stream s)
References SDC.AddressType.Serializer.
static bool SDC.AddressType.LoadFromFile(string fileName, out AddressType obj, out Exception exception)
Deserializes xml markup from file into an AddressType object
fileName string xml file to load and deserialize obj Output AddressType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.AddressType.LoadFromFile, SDC.null.
static bool SDC.AddressType.LoadFromFile(string fileName, out AddressType obj)
References SDC.AddressType.LoadFromFile, SDC.null.
static new AddressType SDC.AddressType.LoadFromFile(string fileName)
References SDC.AddressType.Deserialize, SDC.null.