SDC::BlobType
List<RichTextType> SDC.BlobType._description
HashType SDC.BlobType::_hash
Referenced by SDC.BlobType.ShouldSerializeHash.
BaseType SDC.BlobType::_item
Referenced by SDC.BlobType.ShouldSerializeItem.
string SDC.BlobType::_mimeType
string SDC.BlobType::_fileExtension
BindingList<RichTextType> SDC.BlobType._description
ObjectChangeTracker SDC.BlobType.changeTrackerField
static XmlSerializer SDC.BlobType::serializer
virtual List<RichTextType> SDC.BlobType.Description
Referenced by SDC.SDCTreeBuilderEcc.FillBlob.
HashType SDC.BlobType::Hash
Binary hash of the blob data
BaseType SDC.BlobType::Item
string SDC.BlobType::mimeType
TBD: Must be a valid MIME type - needs enumeration
Referenced by SDC.BlobType.ShouldSerializemimeType.
string SDC.BlobType::fileExtension
Use a common file extension (e.g., docx) if there is no available
Referenced by SDC.BlobType.ShouldSerializefileExtension.
static XmlSerializer SDC.BlobType::Serializer
Referenced by SDC.BlobType.Deserialize.
virtual BindingList<RichTextType> SDC.BlobType.Description
ObjectChangeTracker SDC.BlobType.ChangeTracker
SDC.BlobType.BlobType()
SDC.BlobType.BlobType(BaseType parentNode, bool fillData=true)
virtual bool SDC.BlobType.ShouldSerializeDescription()
Test whether Description should be serialized
References SDC.Description, SDC.null.
virtual bool SDC.BlobType.ShouldSerializeHash()
Test whether Hash should be serialized
References SDC.null.
virtual bool SDC.BlobType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.null.
virtual bool SDC.BlobType.ShouldSerializemimeType()
Test whether mimeType should be serialized
virtual bool SDC.BlobType.ShouldSerializefileExtension()
Test whether fileExtension should be serialized
virtual string SDC.BlobType.Serialize(System.Text.Encoding encoding)
Serializes current BlobType object into an XML string
string XML value
virtual string SDC.BlobType.Serialize()
Referenced by SDC.BlobType.SaveToFile.
virtual bool SDC.BlobType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current BlobType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.BlobType.SaveToFile.
virtual bool SDC.BlobType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.BlobType.SaveToFile(string fileName)
virtual void SDC.BlobType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.BlobType.ShouldSerializeHash()
Test whether Hash should be serialized
References SDC.BlobType._hash, SDC.null.
virtual bool SDC.BlobType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.BlobType._item, SDC.null.
virtual bool SDC.BlobType.ShouldSerializemimeType()
Test whether mimeType should be serialized
References SDC.BlobType.mimeType.
virtual bool SDC.BlobType.ShouldSerializefileExtension()
Test whether fileExtension should be serialized
References SDC.BlobType.fileExtension.
virtual string SDC.BlobType.Serialize()
Serializes current BlobType object into an XML string
string XML value
virtual bool SDC.BlobType.SaveToFile(string fileName, out Exception exception)
Serializes current BlobType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.BlobType.SaveToFile.
virtual void SDC.BlobType.SaveToFile(string fileName)
References SDC.null, SDC.BlobType.Serialize.
virtual BlobType SDC.BlobType.Clone()
Create a clone of this BlobType object
static bool SDC.BlobType.Deserialize(string input, out BlobType obj, out System.Exception exception)
Deserializes workflow markup into an BlobType object
input string workflow markup to deserialize obj Output BlobType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.BlobType.Deserialize, SDC.BlobType.LoadFromFile.
static bool SDC.BlobType.Deserialize(string input, out BlobType obj)
References SDC.null.
static new BlobType SDC.BlobType.Deserialize(string input)
References SDC.null.
static BlobType SDC.BlobType.Deserialize(System.IO.Stream s)
static bool SDC.BlobType.LoadFromFile(string fileName, System.Text.Encoding encoding, out BlobType obj, out System.Exception exception)
Deserializes xml markup from file into an BlobType object
fileName string xml file to load and deserialize obj Output BlobType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.BlobType.LoadFromFile.
static bool SDC.BlobType.LoadFromFile(string fileName, out BlobType obj, out System.Exception exception)
static bool SDC.BlobType.LoadFromFile(string fileName, out BlobType obj)
References SDC.null.
static BlobType SDC.BlobType.LoadFromFile(string fileName)
static new BlobType SDC.BlobType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.BlobType.Deserialize(string input, out BlobType obj, out Exception exception)
Deserializes workflow markup into an BlobType object
input string workflow markup to deserialize obj Output BlobType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.BlobType.Deserialize, SDC.null.
static bool SDC.BlobType.Deserialize(string input, out BlobType obj)
References SDC.BlobType.Deserialize, SDC.null.
static new BlobType SDC.BlobType.Deserialize(string input)
References SDC.null, SDC.BlobType.Serializer.
static BlobType SDC.BlobType.Deserialize(Stream s)
References SDC.BlobType.Serializer.
static bool SDC.BlobType.LoadFromFile(string fileName, out BlobType obj, out Exception exception)
Deserializes xml markup from file into an BlobType object
fileName string xml file to load and deserialize obj Output BlobType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.BlobType.LoadFromFile, SDC.null.
static bool SDC.BlobType.LoadFromFile(string fileName, out BlobType obj)
References SDC.BlobType.LoadFromFile, SDC.null.
static new BlobType SDC.BlobType.LoadFromFile(string fileName)
References SDC.BlobType.Deserialize, SDC.null.