SDC::ComplianceRuleType
string_Stype SDC.ComplianceRuleType::_description
Referenced by SDC.ComplianceRuleType.ShouldSerializeDescription.
List<OrganizationType> SDC.ComplianceRuleType._complianceOrganization
string SDC.ComplianceRuleType::_ruleID
string SDC.ComplianceRuleType::_formID
BindingList<OrganizationType> SDC.ComplianceRuleType._complianceOrganization
ObjectChangeTracker SDC.ComplianceRuleType.changeTrackerField
static XmlSerializer SDC.ComplianceRuleType::serializer
string_Stype SDC.ComplianceRuleType::Description
virtual List<OrganizationType> SDC.ComplianceRuleType.ComplianceOrganization
string SDC.ComplianceRuleType::ruleID
Referenced by SDC.ComplianceRuleType.ShouldSerializeruleID.
string SDC.ComplianceRuleType::formID
Referenced by SDC.ComplianceRuleType.ShouldSerializeformID.
static XmlSerializer SDC.ComplianceRuleType::Serializer
Referenced by SDC.ComplianceRuleType.Deserialize.
virtual BindingList<OrganizationType> SDC.ComplianceRuleType.ComplianceOrganization
ObjectChangeTracker SDC.ComplianceRuleType.ChangeTracker
SDC.ComplianceRuleType.ComplianceRuleType(BaseType parentNode)
virtual bool SDC.ComplianceRuleType.ShouldSerializeComplianceOrganization()
Test whether ComplianceOrganization should be serialized
References SDC.null.
virtual bool SDC.ComplianceRuleType.ShouldSerializeDescription()
Test whether Description should be serialized
References SDC.null.
virtual bool SDC.ComplianceRuleType.ShouldSerializeruleID()
Test whether ruleID should be serialized
virtual bool SDC.ComplianceRuleType.ShouldSerializeformID()
Test whether formID should be serialized
virtual string SDC.ComplianceRuleType.Serialize(System.Text.Encoding encoding)
Serializes current ComplianceRuleType object into an XML string
string XML value
virtual string SDC.ComplianceRuleType.Serialize()
Referenced by SDC.ComplianceRuleType.SaveToFile.
virtual bool SDC.ComplianceRuleType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ComplianceRuleType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ComplianceRuleType.SaveToFile.
virtual bool SDC.ComplianceRuleType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ComplianceRuleType.SaveToFile(string fileName)
virtual void SDC.ComplianceRuleType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ComplianceRuleType.ShouldSerializeDescription()
Test whether Description should be serialized
References SDC.ComplianceRuleType._description, SDC.null.
virtual bool SDC.ComplianceRuleType.ShouldSerializeruleID()
Test whether ruleID should be serialized
References SDC.ComplianceRuleType.ruleID.
virtual bool SDC.ComplianceRuleType.ShouldSerializeformID()
Test whether formID should be serialized
References SDC.ComplianceRuleType.formID.
virtual string SDC.ComplianceRuleType.Serialize()
Serializes current ComplianceRuleType object into an XML string
string XML value
virtual bool SDC.ComplianceRuleType.SaveToFile(string fileName, out Exception exception)
Serializes current ComplianceRuleType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ComplianceRuleType.SaveToFile.
virtual void SDC.ComplianceRuleType.SaveToFile(string fileName)
References SDC.null, SDC.ComplianceRuleType.Serialize.
virtual ComplianceRuleType SDC.ComplianceRuleType.Clone()
Create a clone of this ComplianceRuleType object
SDC.ComplianceRuleType.ComplianceRuleType()
static bool SDC.ComplianceRuleType.Deserialize(string input, out ComplianceRuleType obj, out System.Exception exception)
Deserializes workflow markup into an ComplianceRuleType object
input string workflow markup to deserialize obj Output ComplianceRuleType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ComplianceRuleType.Deserialize, SDC.ComplianceRuleType.LoadFromFile.
static bool SDC.ComplianceRuleType.Deserialize(string input, out ComplianceRuleType obj)
References SDC.null.
static new ComplianceRuleType SDC.ComplianceRuleType.Deserialize(string input)
References SDC.null.
static ComplianceRuleType SDC.ComplianceRuleType.Deserialize(System.IO.Stream s)
static bool SDC.ComplianceRuleType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ComplianceRuleType obj, out System.Exception exception)
Deserializes xml markup from file into an ComplianceRuleType object
fileName string xml file to load and deserialize obj Output ComplianceRuleType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ComplianceRuleType.LoadFromFile.
static bool SDC.ComplianceRuleType.LoadFromFile(string fileName, out ComplianceRuleType obj, out System.Exception exception)
static bool SDC.ComplianceRuleType.LoadFromFile(string fileName, out ComplianceRuleType obj)
References SDC.null.
static ComplianceRuleType SDC.ComplianceRuleType.LoadFromFile(string fileName)
static new ComplianceRuleType SDC.ComplianceRuleType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ComplianceRuleType.Deserialize(string input, out ComplianceRuleType obj, out Exception exception)
Deserializes workflow markup into an ComplianceRuleType object
input string workflow markup to deserialize obj Output ComplianceRuleType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ComplianceRuleType.Deserialize, SDC.null.
static bool SDC.ComplianceRuleType.Deserialize(string input, out ComplianceRuleType obj)
References SDC.ComplianceRuleType.Deserialize, SDC.null.
static new ComplianceRuleType SDC.ComplianceRuleType.Deserialize(string input)
References SDC.null, SDC.ComplianceRuleType.Serializer.
static ComplianceRuleType SDC.ComplianceRuleType.Deserialize(Stream s)
References SDC.ComplianceRuleType.Serializer.
static bool SDC.ComplianceRuleType.LoadFromFile(string fileName, out ComplianceRuleType obj, out Exception exception)
Deserializes xml markup from file into an ComplianceRuleType object
fileName string xml file to load and deserialize obj Output ComplianceRuleType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ComplianceRuleType.LoadFromFile, SDC.null.
static bool SDC.ComplianceRuleType.LoadFromFile(string fileName, out ComplianceRuleType obj)
References SDC.ComplianceRuleType.LoadFromFile, SDC.null.
static new ComplianceRuleType SDC.ComplianceRuleType.LoadFromFile(string fileName)
References SDC.ComplianceRuleType.Deserialize, SDC.null.