SDC::short_DEtype
bool SDC.short_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.short_DEtype.ShouldSerializemaxExclusive.
bool SDC.short_DEtype::_shouldSerializeminExclusive
Referenced by SDC.short_DEtype.ShouldSerializeminExclusive.
bool SDC.short_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.short_DEtype.ShouldSerializemaxInclusive.
bool SDC.short_DEtype::_shouldSerializeminInclusive
Referenced by SDC.short_DEtype.ShouldSerializeminInclusive.
System Nullable< short > SDC.short_DEtype::_minInclusive
Referenced by SDC.short_DEtype.ShouldSerializeminInclusive.
System Nullable< short > SDC.short_DEtype::_maxInclusive
Referenced by SDC.short_DEtype.ShouldSerializemaxInclusive.
System Nullable< short > SDC.short_DEtype::_minExclusive
Referenced by SDC.short_DEtype.ShouldSerializeminExclusive.
System Nullable< short > SDC.short_DEtype::_maxExclusive
Referenced by SDC.short_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.short_DEtype::_totalDigits
string SDC.short_DEtype::_mask
ObjectChangeTracker SDC.short_DEtype.changeTrackerField
static XmlSerializer SDC.short_DEtype::serializer
short SDC.short_DEtype::minInclusive
bool SDC.short_DEtype::minInclusiveSpecified
short SDC.short_DEtype::maxInclusive
bool SDC.short_DEtype::maxInclusiveSpecified
short SDC.short_DEtype::minExclusive
bool SDC.short_DEtype::minExclusiveSpecified
short SDC.short_DEtype::maxExclusive
bool SDC.short_DEtype::maxExclusiveSpecified
byte SDC.short_DEtype::totalDigits
bool SDC.short_DEtype::totalDigitsSpecified
string SDC.short_DEtype::mask
Referenced by SDC.short_DEtype.ShouldSerializemask.
static XmlSerializer SDC.short_DEtype::Serializer
Referenced by SDC.short_DEtype.Deserialize.
ObjectChangeTracker SDC.short_DEtype.ChangeTracker
SDC.short_DEtype.short_DEtype()
SDC.short_DEtype.short_DEtype(BaseType parentNode)
virtual bool SDC.short_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.short_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.short_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.short_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.short_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.short_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current short_DEtype object into an XML string
string XML value
virtual string SDC.short_DEtype.Serialize()
Referenced by SDC.short_DEtype.SaveToFile.
virtual bool SDC.short_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current short_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.short_DEtype.SaveToFile.
virtual bool SDC.short_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.short_DEtype.SaveToFile(string fileName)
virtual void SDC.short_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.short_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.short_DEtype._minInclusive, SDC.short_DEtype._shouldSerializeminInclusive.
virtual bool SDC.short_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.short_DEtype._maxInclusive, SDC.short_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.short_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.short_DEtype._minExclusive, SDC.short_DEtype._shouldSerializeminExclusive.
virtual bool SDC.short_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.short_DEtype._maxExclusive, SDC.short_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.short_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.short_DEtype.mask.
virtual string SDC.short_DEtype.Serialize()
Serializes current short_DEtype object into an XML string
string XML value
virtual bool SDC.short_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current short_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.short_DEtype.SaveToFile.
virtual void SDC.short_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.short_DEtype.Serialize.
virtual short_DEtype SDC.short_DEtype.Clone()
Create a clone of this short_DEtype object
static bool SDC.short_DEtype.Deserialize(string input, out short_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an short_DEtype object
input string workflow markup to deserialize obj Output short_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.short_DEtype.Deserialize, SDC.short_DEtype.LoadFromFile.
static bool SDC.short_DEtype.Deserialize(string input, out short_DEtype obj)
References SDC.null.
static new short_DEtype SDC.short_DEtype.Deserialize(string input)
References SDC.null.
static short_DEtype SDC.short_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.short_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out short_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an short_DEtype object
fileName string xml file to load and deserialize obj Output short_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.short_DEtype.LoadFromFile.
static bool SDC.short_DEtype.LoadFromFile(string fileName, out short_DEtype obj, out System.Exception exception)
static bool SDC.short_DEtype.LoadFromFile(string fileName, out short_DEtype obj)
References SDC.null.
static short_DEtype SDC.short_DEtype.LoadFromFile(string fileName)
static new short_DEtype SDC.short_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.short_DEtype.Deserialize(string input, out short_DEtype obj, out Exception exception)
Deserializes workflow markup into an short_DEtype object
input string workflow markup to deserialize obj Output short_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.short_DEtype.Deserialize, SDC.null.
static bool SDC.short_DEtype.Deserialize(string input, out short_DEtype obj)
References SDC.short_DEtype.Deserialize, SDC.null.
static new short_DEtype SDC.short_DEtype.Deserialize(string input)
References SDC.null, SDC.short_DEtype.Serializer.
static short_DEtype SDC.short_DEtype.Deserialize(Stream s)
References SDC.short_DEtype.Serializer.
static bool SDC.short_DEtype.LoadFromFile(string fileName, out short_DEtype obj, out Exception exception)
Deserializes xml markup from file into an short_DEtype object
fileName string xml file to load and deserialize obj Output short_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.short_DEtype.LoadFromFile, SDC.null.
static bool SDC.short_DEtype.LoadFromFile(string fileName, out short_DEtype obj)
References SDC.short_DEtype.LoadFromFile, SDC.null.
static new short_DEtype SDC.short_DEtype.LoadFromFile(string fileName)
References SDC.short_DEtype.Deserialize, SDC.null.