SDC::ReturnDateTimeType
DataTypes_DEType SDC.ReturnDateTimeType._item1
Referenced by SDC.ReturnDateTimeType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnDateTimeType.serializer
virtual DataTypes_DEType SDC.ReturnDateTimeType.Item1
XmlSerializer SDC.ReturnDateTimeType.Serializer
Referenced by SDC.ReturnDateTimeType.Deserialize.
virtual bool SDC.ReturnDateTimeType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnDateTimeType._item1, SDC.null.
virtual string SDC.ReturnDateTimeType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnDateTimeType object into an XML string
string XML value
virtual string SDC.ReturnDateTimeType.Serialize()
Referenced by SDC.ReturnDateTimeType.SaveToFile.
virtual bool SDC.ReturnDateTimeType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnDateTimeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnDateTimeType.SaveToFile.
virtual bool SDC.ReturnDateTimeType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnDateTimeType.SaveToFile.
virtual void SDC.ReturnDateTimeType.SaveToFile(string fileName)
References SDC.ReturnDateTimeType.SaveToFile.
virtual void SDC.ReturnDateTimeType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnDateTimeType.Serialize.
static bool SDC.ReturnDateTimeType.Deserialize(string input, out ReturnDateTimeType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnDateTimeType object
input string workflow markup to deserialize obj Output ReturnDateTimeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnDateTimeType.Deserialize, SDC.ReturnDateTimeType.LoadFromFile.
static bool SDC.ReturnDateTimeType.Deserialize(string input, out ReturnDateTimeType obj)
References SDC.ReturnDateTimeType.Deserialize, SDC.null.
static new ReturnDateTimeType SDC.ReturnDateTimeType.Deserialize(string input)
References SDC.null.
static ReturnDateTimeType SDC.ReturnDateTimeType.Deserialize(System.IO.Stream s)
References SDC.ReturnDateTimeType.Serializer.
static bool SDC.ReturnDateTimeType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnDateTimeType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnDateTimeType object
fileName string xml file to load and deserialize obj Output ReturnDateTimeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnDateTimeType.LoadFromFile.
static bool SDC.ReturnDateTimeType.LoadFromFile(string fileName, out ReturnDateTimeType obj, out System.Exception exception)
References SDC.ReturnDateTimeType.LoadFromFile.
static bool SDC.ReturnDateTimeType.LoadFromFile(string fileName, out ReturnDateTimeType obj)
References SDC.ReturnDateTimeType.LoadFromFile, SDC.null.
static ReturnDateTimeType SDC.ReturnDateTimeType.LoadFromFile(string fileName)
References SDC.ReturnDateTimeType.LoadFromFile.
static new ReturnDateTimeType SDC.ReturnDateTimeType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnDateTimeType.Deserialize, SDC.null.