SDC::PredicateCompareType
ExpressionType SDC.PredicateCompareType.RHS_Expression_Item
"RHS_Expression", typeof(ExpressionType)
ExtensionBaseType SDC.PredicateCompareType.RHS_Extension_Item
"RHS_Extension", typeof(ExtensionBaseType)
GetCodeType SDC.PredicateCompareType.RHS_GetCode_Item
"RHS_GetCode", typeof(GetCodeType)
ItemNameType SDC.PredicateCompareType.RHS_GetResponse_Item
"RHS_GetResponse", typeof(ItemNameType)
DataTypes_SType SDC.PredicateCompareType.RHS_Value_Item
"RHS_Value", typeof(DataTypes_SType)
virtual BaseType SDC.PredicateCompareType.Item
virtual PredicateCompareTypeArithOpEnum SDC.PredicateCompareType.ArithOpEnum
Arithmetic operator for comparisons tha result in a Boolean value.
XmlSerializer SDC.PredicateCompareType.Serializer
Referenced by SDC.PredicateCompareType.Deserialize.
ObjectChangeTracker SDC.PredicateCompareType.ChangeTracker
BaseType SDC.PredicateCompareType._item
Referenced by SDC.PredicateCompareType.ShouldSerializeItem.
PredicateCompareTypeArithOpEnum SDC.PredicateCompareType._arithOpEnum
ObjectChangeTracker SDC.PredicateCompareType.changeTrackerField
XmlSerializer SDC.PredicateCompareType.serializer
SDC.PredicateCompareType.PredicateCompareType()
virtual bool SDC.PredicateCompareType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.PredicateCompareType._item, SDC.null.
virtual string SDC.PredicateCompareType.Serialize()
Serializes current PredicateCompareType object into an XML string
string XML value
Referenced by SDC.PredicateCompareType.SaveToFile.
virtual bool SDC.PredicateCompareType.SaveToFile(string fileName, out Exception exception)
Serializes current PredicateCompareType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.PredicateCompareType.SaveToFile(string fileName)
References SDC.null, SDC.PredicateCompareType.Serialize.
virtual PredicateCompareType SDC.PredicateCompareType.Clone()
Create a clone of this PredicateCompareType object
static bool SDC.PredicateCompareType.Deserialize(string input, out PredicateCompareType obj, out Exception exception)
Deserializes workflow markup into an PredicateCompareType object
input string workflow markup to deserialize obj Output PredicateCompareType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PredicateCompareType.Deserialize, SDC.PredicateCompareType.LoadFromFile.
static bool SDC.PredicateCompareType.Deserialize(string input, out PredicateCompareType obj)
References SDC.PredicateCompareType.Deserialize, SDC.null.
static new PredicateCompareType SDC.PredicateCompareType.Deserialize(string input)
References SDC.null, SDC.PredicateCompareType.Serializer.
static PredicateCompareType SDC.PredicateCompareType.Deserialize(Stream s)
References SDC.PredicateCompareType.Serializer.
static bool SDC.PredicateCompareType.LoadFromFile(string fileName, out PredicateCompareType obj, out Exception exception)
Deserializes xml markup from file into an PredicateCompareType object
fileName string xml file to load and deserialize obj Output PredicateCompareType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PredicateCompareType.LoadFromFile.
static bool SDC.PredicateCompareType.LoadFromFile(string fileName, out PredicateCompareType obj)
References SDC.PredicateCompareType.LoadFromFile, SDC.null.
static new PredicateCompareType SDC.PredicateCompareType.LoadFromFile(string fileName)
References SDC.PredicateCompareType.Deserialize, SDC.null.