SDC::DataElementType
List<IdentifiedExtensionType> SDC.DataElementType._items
string SDC.DataElementType._prevVersionURI
string SDC.DataElementType._basedOnURI
string SDC.DataElementType._filename
string SDC.DataElementType._title
XmlSerializer SDC.DataElementType.serializer
virtual List<IdentifiedExtensionType> SDC.DataElementType.Items
Referenced by SDC.DataElementType.ShouldSerializeItems.
virtual string SDC.DataElementType.prevVersionURI
NEW: URI used to identify the form that is the immediate previous version of the current FormDesign
Referenced by SDC.DataElementType.ShouldSerializeprevVersionURI.
virtual string SDC.DataElementType.basedOnURI
URI used to identify the original DE that that this DE is based upon.
The current DE may reuse the original whenever the question/answer/semantic context is identical to the original. However, a clear policy for DE reuse must be extablished.Relying on a CodedValue, mapping file or table may be a better and more flexible approach than . In this way, users could compare data elements to determine if they contain semantic matches, and this is supported better with a more robust code map section.
Referenced by SDC.DataElementType.ShouldSerializebasedOnURI.
virtual string SDC.DataElementType.filename
Filename to use when the current DE XML is saved as a file.
Referenced by SDC.DataElementType.ShouldSerializefilename.
virtual string SDC.DataElementType.title
Human readable title for display when choosing DEs
Referenced by SDC.DataElementType.ShouldSerializetitle.
XmlSerializer SDC.DataElementType.Serializer
Referenced by SDC.DataElementType.Deserialize.
virtual bool SDC.DataElementType.ShouldSerializeItems()
Test whether Items should be serialized
References SDC.DataElementType.Items, SDC.null.
virtual bool SDC.DataElementType.ShouldSerializeprevVersionURI()
Test whether prevVersionURI should be serialized
References SDC.DataElementType.prevVersionURI.
virtual bool SDC.DataElementType.ShouldSerializebasedOnURI()
Test whether basedOnURI should be serialized
References SDC.DataElementType.basedOnURI.
virtual bool SDC.DataElementType.ShouldSerializefilename()
Test whether filename should be serialized
References SDC.DataElementType.filename.
virtual bool SDC.DataElementType.ShouldSerializetitle()
Test whether title should be serialized
References SDC.DataElementType.title.
virtual string SDC.DataElementType.Serialize(System.Text.Encoding encoding)
Serializes current DataElementType object into an XML string
string XML value
virtual string SDC.DataElementType.Serialize()
Referenced by SDC.DataElementType.SaveToFile.
virtual bool SDC.DataElementType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current DataElementType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.DataElementType.SaveToFile.
virtual bool SDC.DataElementType.SaveToFile(string fileName, out System.Exception exception)
References SDC.DataElementType.SaveToFile.
virtual void SDC.DataElementType.SaveToFile(string fileName)
References SDC.DataElementType.SaveToFile.
virtual void SDC.DataElementType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.DataElementType.Serialize.
static bool SDC.DataElementType.Deserialize(string input, out DataElementType obj, out System.Exception exception)
Deserializes workflow markup into an DataElementType object
input string workflow markup to deserialize obj Output DataElementType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DataElementType.Deserialize, SDC.DataElementType.LoadFromFile.
static bool SDC.DataElementType.Deserialize(string input, out DataElementType obj)
References SDC.DataElementType.Deserialize, SDC.null.
static new DataElementType SDC.DataElementType.Deserialize(string input)
References SDC.null.
static DataElementType SDC.DataElementType.Deserialize(System.IO.Stream s)
References SDC.DataElementType.Serializer.
static bool SDC.DataElementType.LoadFromFile(string fileName, System.Text.Encoding encoding, out DataElementType obj, out System.Exception exception)
Deserializes xml markup from file into an DataElementType object
fileName string xml file to load and deserialize obj Output DataElementType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DataElementType.LoadFromFile.
static bool SDC.DataElementType.LoadFromFile(string fileName, out DataElementType obj, out System.Exception exception)
References SDC.DataElementType.LoadFromFile.
static bool SDC.DataElementType.LoadFromFile(string fileName, out DataElementType obj)
References SDC.DataElementType.LoadFromFile, SDC.null.
static DataElementType SDC.DataElementType.LoadFromFile(string fileName)
References SDC.DataElementType.LoadFromFile.
static new DataElementType SDC.DataElementType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.DataElementType.Deserialize, SDC.null.