SDC::PredicateType
ExpressionType SDC.PredicateType.LHS_Expression_Item
"LHS_Expression", typeof(ExpressionType)
ExtensionBaseType SDC.PredicateType.LHS_Extension_Item
"LHS_Extension", typeof(ExtensionBaseType)
GetCodeType SDC.PredicateType.LHS_GetCode_Item
"LHS_GetCode", typeof(GetCodeType),
ItemNameType SDC.PredicateType.LHS_GetResponse_Item
"LHS_GetResponse", typeof(ItemNameType)
PredicateBetweenType SDC.PredicateType.Between_Item
"Between", typeof(PredicateBetweenType),
PredicateCompareType SDC.PredicateType.Compare_Item
"Compare", typeof(PredicateCompareType),
PredicateInListType SDC.PredicateType.InList_Item
"InList", typeof(PredicateInListType)
virtual List<ReturnBoolType> SDC.PredicateType.Items
PredicateType class constructor
Referenced by SDC.PredicateType.ShouldSerializeItems.
virtual bool SDC.PredicateType.not
virtual bool SDC.PredicateType.notSpecified
virtual BoolListTypeBoolOp SDC.PredicateType.boolOp
static XmlSerializer SDC.PredicateType::Serializer
Referenced by SDC.PredicateType.Deserialize.
virtual BaseType SDC.PredicateType.Item
virtual ExtensionBaseType SDC.PredicateType.Item1
ObjectChangeTracker SDC.PredicateType.ChangeTracker
bool SDC.PredicateType._shouldSerializenot
Referenced by SDC.PredicateType.ShouldSerializenot.
List<ReturnBoolType> SDC.PredicateType._items
System.Nullable<bool> SDC.PredicateType._not
Referenced by SDC.PredicateType.ShouldSerializenot.
BoolListTypeBoolOp SDC.PredicateType._boolOp
BaseType SDC.PredicateType._item
Referenced by SDC.PredicateType.ShouldSerializeItem.
ExtensionBaseType SDC.PredicateType._item1
Referenced by SDC.PredicateType.ShouldSerializeItem1.
ObjectChangeTracker SDC.PredicateType.changeTrackerField
static XmlSerializer SDC.PredicateType::serializer
SDC.PredicateType.PredicateType()
SDC.PredicateType.PredicateType(BaseType parentNode, bool fillData=true)
SDC.PredicateType.PredicateType()
virtual bool SDC.PredicateType.ShouldSerializeItems()
Test whether Items should be serialized
References SDC.PredicateType.Items, SDC.null.
virtual bool SDC.PredicateType.ShouldSerializenot()
Test whether not should be serialized
References SDC.PredicateType._not, SDC.PredicateType._shouldSerializenot.
virtual string SDC.PredicateType.Serialize(System.Text.Encoding encoding)
Serializes current PredicateType object into an XML string
string XML value
virtual string SDC.PredicateType.Serialize()
Referenced by SDC.PredicateType.SaveToFile.
virtual bool SDC.PredicateType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current PredicateType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.PredicateType.SaveToFile.
virtual bool SDC.PredicateType.SaveToFile(string fileName, out System.Exception exception)
References SDC.PredicateType.SaveToFile.
virtual void SDC.PredicateType.SaveToFile(string fileName)
References SDC.PredicateType.SaveToFile.
virtual void SDC.PredicateType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.PredicateType.Serialize.
virtual bool SDC.PredicateType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.PredicateType._item, SDC.null.
virtual bool SDC.PredicateType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.PredicateType._item1, SDC.null.
virtual string SDC.PredicateType.Serialize()
Serializes current PredicateType object into an XML string
string XML value
virtual bool SDC.PredicateType.SaveToFile(string fileName, out Exception exception)
Serializes current PredicateType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.PredicateType.SaveToFile.
virtual void SDC.PredicateType.SaveToFile(string fileName)
References SDC.null, SDC.PredicateType.Serialize.
virtual PredicateType SDC.PredicateType.Clone()
Create a clone of this PredicateType object
static bool SDC.PredicateType.Deserialize(string input, out PredicateType obj, out System.Exception exception)
Deserializes workflow markup into an PredicateType object
input string workflow markup to deserialize obj Output PredicateType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PredicateType.Deserialize, SDC.PredicateType.LoadFromFile.
static bool SDC.PredicateType.Deserialize(string input, out PredicateType obj)
References SDC.PredicateType.Deserialize, SDC.null.
static new PredicateType SDC.PredicateType.Deserialize(string input)
References SDC.null.
static PredicateType SDC.PredicateType.Deserialize(System.IO.Stream s)
References SDC.PredicateType.Serializer.
static bool SDC.PredicateType.LoadFromFile(string fileName, System.Text.Encoding encoding, out PredicateType obj, out System.Exception exception)
Deserializes xml markup from file into an PredicateType object
fileName string xml file to load and deserialize obj Output PredicateType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PredicateType.LoadFromFile.
static bool SDC.PredicateType.LoadFromFile(string fileName, out PredicateType obj, out System.Exception exception)
References SDC.PredicateType.LoadFromFile.
static bool SDC.PredicateType.LoadFromFile(string fileName, out PredicateType obj)
References SDC.PredicateType.LoadFromFile, SDC.null.
static PredicateType SDC.PredicateType.LoadFromFile(string fileName)
References SDC.PredicateType.LoadFromFile.
static new PredicateType SDC.PredicateType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.PredicateType.Deserialize, SDC.null.
static bool SDC.PredicateType.Deserialize(string input, out PredicateType obj, out Exception exception)
Deserializes workflow markup into an PredicateType object
input string workflow markup to deserialize obj Output PredicateType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.PredicateType.Deserialize, SDC.null.
static bool SDC.PredicateType.Deserialize(string input, out PredicateType obj)
References SDC.PredicateType.Deserialize, SDC.null.
static new PredicateType SDC.PredicateType.Deserialize(string input)
References SDC.null, SDC.PredicateType.Serializer.
static PredicateType SDC.PredicateType.Deserialize(Stream s)
References SDC.PredicateType.Serializer.
static bool SDC.PredicateType.LoadFromFile(string fileName, out PredicateType obj, out Exception exception)
Deserializes xml markup from file into an PredicateType object
fileName string xml file to load and deserialize obj Output PredicateType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.PredicateType.LoadFromFile, SDC.null.
static bool SDC.PredicateType.LoadFromFile(string fileName, out PredicateType obj)
References SDC.PredicateType.LoadFromFile, SDC.null.
static new PredicateType SDC.PredicateType.LoadFromFile(string fileName)
References SDC.PredicateType.Deserialize, SDC.null.