SDC::ResponseChangeType
PersonType SDC.ResponseChangeType._changeEditor
Referenced by SDC.ResponseChangeType.ShouldSerializeChangeEditor.
dateTime_Stype SDC.ResponseChangeType._changeDateTime
Referenced by SDC.ResponseChangeType.ShouldSerializeChangeDateTime.
string_Stype SDC.ResponseChangeType._changeComment
Referenced by SDC.ResponseChangeType.ShouldSerializeChangeComment.
ReplacedResponseType SDC.ResponseChangeType._replacedResponse
Referenced by SDC.ResponseChangeType.ShouldSerializeReplacedResponse.
string SDC.ResponseChangeType._changeID
ObjectChangeTracker SDC.ResponseChangeType.changeTrackerField
XmlSerializer SDC.ResponseChangeType.serializer
virtual PersonType SDC.ResponseChangeType.ChangeEditor
The person who changed the previous response to the new response.
virtual dateTime_Stype SDC.ResponseChangeType.ChangeDateTime
The time when the previous response was changed to the new response.
virtual string_Stype SDC.ResponseChangeType.ChangeComment
A comment describing the change from the previous response to the new response.
virtual ReplacedResponseType SDC.ResponseChangeType.ReplacedResponse
A single unit of changes (taking place at the same time) to the question response(s). This section records the person who made the change, the DateTime of the change, and the change details. This includes each answer selection or fill-in response to the question at the time the change was submitted.
virtual string SDC.ResponseChangeType.changeID
Referenced by SDC.ResponseChangeType.ShouldSerializechangeID.
XmlSerializer SDC.ResponseChangeType.Serializer
Referenced by SDC.ResponseChangeType.Deserialize.
ObjectChangeTracker SDC.ResponseChangeType.ChangeTracker
virtual bool SDC.ResponseChangeType.ShouldSerializeChangeEditor()
Test whether ChangeEditor should be serialized
References SDC.ResponseChangeType._changeEditor, SDC.null.
virtual bool SDC.ResponseChangeType.ShouldSerializeChangeDateTime()
Test whether ChangeDateTime should be serialized
References SDC.ResponseChangeType._changeDateTime, SDC.null.
virtual bool SDC.ResponseChangeType.ShouldSerializeChangeComment()
Test whether ChangeComment should be serialized
References SDC.ResponseChangeType._changeComment, SDC.null.
virtual bool SDC.ResponseChangeType.ShouldSerializeReplacedResponse()
Test whether ReplacedResponse should be serialized
References SDC.ResponseChangeType._replacedResponse, SDC.null.
virtual bool SDC.ResponseChangeType.ShouldSerializechangeID()
Test whether changeID should be serialized
References SDC.ResponseChangeType.changeID.
virtual string SDC.ResponseChangeType.Serialize()
Serializes current ResponseChangeType object into an XML string
string XML value
Referenced by SDC.ResponseChangeType.SaveToFile.
virtual bool SDC.ResponseChangeType.SaveToFile(string fileName, out Exception exception)
Serializes current ResponseChangeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.ResponseChangeType.SaveToFile(string fileName)
References SDC.null, SDC.ResponseChangeType.Serialize.
virtual ResponseChangeType SDC.ResponseChangeType.Clone()
Create a clone of this ResponseChangeType object
static bool SDC.ResponseChangeType.Deserialize(string input, out ResponseChangeType obj, out Exception exception)
Deserializes workflow markup into an ResponseChangeType object
input string workflow markup to deserialize obj Output ResponseChangeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ResponseChangeType.Deserialize, SDC.ResponseChangeType.LoadFromFile.
static bool SDC.ResponseChangeType.Deserialize(string input, out ResponseChangeType obj)
References SDC.ResponseChangeType.Deserialize, SDC.null.
static new ResponseChangeType SDC.ResponseChangeType.Deserialize(string input)
References SDC.null, SDC.ResponseChangeType.Serializer.
static ResponseChangeType SDC.ResponseChangeType.Deserialize(Stream s)
References SDC.ResponseChangeType.Serializer.
static bool SDC.ResponseChangeType.LoadFromFile(string fileName, out ResponseChangeType obj, out Exception exception)
Deserializes xml markup from file into an ResponseChangeType object
fileName string xml file to load and deserialize obj Output ResponseChangeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ResponseChangeType.LoadFromFile.
static bool SDC.ResponseChangeType.LoadFromFile(string fileName, out ResponseChangeType obj)
References SDC.ResponseChangeType.LoadFromFile, SDC.null.
static new ResponseChangeType SDC.ResponseChangeType.LoadFromFile(string fileName)
References SDC.ResponseChangeType.Deserialize, SDC.null.