SDC::CodeMatchType
string_Stype SDC.CodeMatchType::_codingMatchComment
Referenced by SDC.CodeMatchType.ShouldSerializeCodingMatchComment.
CodeMatchTypeCodeMatchEnum SDC.CodeMatchType::_codeMatchEnum
Referenced by SDC.CodeMatchType.CodeMatchType.
ObjectChangeTracker SDC.CodeMatchType.changeTrackerField
static XmlSerializer SDC.CodeMatchType::serializer
string_Stype SDC.CodeMatchType::CodingMatchComment
Comment about the degree of match between the mapped item and the assigned code.
CodeMatchTypeCodeMatchEnum SDC.CodeMatchType::codeMatchEnum
The degree of match between the coded item and the assigned code.
static XmlSerializer SDC.CodeMatchType::Serializer
Referenced by SDC.CodeMatchType.Deserialize.
ObjectChangeTracker SDC.CodeMatchType.ChangeTracker
SDC.CodeMatchType.CodeMatchType()
SDC.CodeMatchType.CodeMatchType(BaseType parentNode, bool fillData=true)
virtual bool SDC.CodeMatchType.ShouldSerializeCodingMatchComment()
Test whether CodingMatchComment should be serialized
References SDC.null.
virtual string SDC.CodeMatchType.Serialize(System.Text.Encoding encoding)
Serializes current CodeMatchType object into an XML string
string XML value
virtual string SDC.CodeMatchType.Serialize()
Referenced by SDC.CodeMatchType.SaveToFile.
virtual bool SDC.CodeMatchType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current CodeMatchType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.CodeMatchType.SaveToFile.
virtual bool SDC.CodeMatchType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.CodeMatchType.SaveToFile(string fileName)
virtual void SDC.CodeMatchType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.CodeMatchType.CodeMatchType()
CodeMatchType class constructor
References SDC.CodeMatchType._codeMatchEnum.
virtual bool SDC.CodeMatchType.ShouldSerializeCodingMatchComment()
Test whether CodingMatchComment should be serialized
References SDC.CodeMatchType._codingMatchComment, SDC.null.
virtual string SDC.CodeMatchType.Serialize()
Serializes current CodeMatchType object into an XML string
string XML value
virtual bool SDC.CodeMatchType.SaveToFile(string fileName, out Exception exception)
Serializes current CodeMatchType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.CodeMatchType.SaveToFile.
virtual void SDC.CodeMatchType.SaveToFile(string fileName)
References SDC.null, SDC.CodeMatchType.Serialize.
virtual CodeMatchType SDC.CodeMatchType.Clone()
Create a clone of this CodeMatchType object
static bool SDC.CodeMatchType.Deserialize(string input, out CodeMatchType obj, out System.Exception exception)
Deserializes workflow markup into an CodeMatchType object
input string workflow markup to deserialize obj Output CodeMatchType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CodeMatchType.Deserialize, SDC.CodeMatchType.LoadFromFile.
static bool SDC.CodeMatchType.Deserialize(string input, out CodeMatchType obj)
References SDC.null.
static new CodeMatchType SDC.CodeMatchType.Deserialize(string input)
References SDC.null.
static CodeMatchType SDC.CodeMatchType.Deserialize(System.IO.Stream s)
static bool SDC.CodeMatchType.LoadFromFile(string fileName, System.Text.Encoding encoding, out CodeMatchType obj, out System.Exception exception)
Deserializes xml markup from file into an CodeMatchType object
fileName string xml file to load and deserialize obj Output CodeMatchType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CodeMatchType.LoadFromFile.
static bool SDC.CodeMatchType.LoadFromFile(string fileName, out CodeMatchType obj, out System.Exception exception)
static bool SDC.CodeMatchType.LoadFromFile(string fileName, out CodeMatchType obj)
References SDC.null.
static CodeMatchType SDC.CodeMatchType.LoadFromFile(string fileName)
static new CodeMatchType SDC.CodeMatchType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.CodeMatchType.Deserialize(string input, out CodeMatchType obj, out Exception exception)
Deserializes workflow markup into an CodeMatchType object
input string workflow markup to deserialize obj Output CodeMatchType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CodeMatchType.Deserialize, SDC.null.
static bool SDC.CodeMatchType.Deserialize(string input, out CodeMatchType obj)
References SDC.CodeMatchType.Deserialize, SDC.null.
static new CodeMatchType SDC.CodeMatchType.Deserialize(string input)
References SDC.null, SDC.CodeMatchType.Serializer.
static CodeMatchType SDC.CodeMatchType.Deserialize(Stream s)
References SDC.CodeMatchType.Serializer.
static bool SDC.CodeMatchType.LoadFromFile(string fileName, out CodeMatchType obj, out Exception exception)
Deserializes xml markup from file into an CodeMatchType object
fileName string xml file to load and deserialize obj Output CodeMatchType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CodeMatchType.LoadFromFile, SDC.null.
static bool SDC.CodeMatchType.LoadFromFile(string fileName, out CodeMatchType obj)
References SDC.CodeMatchType.LoadFromFile, SDC.null.
static new CodeMatchType SDC.CodeMatchType.LoadFromFile(string fileName)
References SDC.CodeMatchType.Deserialize, SDC.null.