SDC::ActSendReportType
List<ExtensionBaseType> SDC.ActSendReportType.Email_Phone_WebSvc_List
List<BaseType> SDC.ActSendReportType.Email_Phone_WebSvc_List
virtual List<ExtensionBaseType> SDC.ActSendReportType.Items
virtual string SDC.ActSendReportType.reportID
string SDC.ActSendReportType::reportInstanceGuid
Referenced by SDC.ActSendReportType.ShouldSerializereportInstanceGuid.
virtual string SDC.ActSendReportType.reportInstanceVersonGuid
static XmlSerializer SDC.ActSendReportType::Serializer
Referenced by SDC.ActSendReportType.Deserialize.
virtual BindingList<BaseType> SDC.ActSendReportType.Items
virtual string SDC.ActSendReportType.reportURI
Referenced by SDC.ActSendReportType.ShouldSerializereportURI.
ObjectChangeTracker SDC.ActSendReportType.ChangeTracker
List<ExtensionBaseType> SDC.ActSendReportType._items
string SDC.ActSendReportType._reportID
string SDC.ActSendReportType::_reportInstanceGuid
string SDC.ActSendReportType._reportInstanceVersonGuid
BindingList<BaseType> SDC.ActSendReportType._items
string SDC.ActSendReportType._reportURI
ObjectChangeTracker SDC.ActSendReportType.changeTrackerField
static XmlSerializer SDC.ActSendReportType::serializer
SDC.ActSendReportType.ActSendReportType()
SDC.ActSendReportType.ActSendReportType(ThenType parentNode)
virtual bool SDC.ActSendReportType.ShouldSerializeItems()
Test whether Items should be serialized
References SDC.null.
virtual bool SDC.ActSendReportType.ShouldSerializereportID()
Test whether reportID should be serialized
virtual bool SDC.ActSendReportType.ShouldSerializereportInstanceGuid()
Test whether reportInstanceGuid should be serialized
virtual bool SDC.ActSendReportType.ShouldSerializereportInstanceVersonGuid()
Test whether reportInstanceVersonGuid should be serialized
virtual string SDC.ActSendReportType.Serialize(System.Text.Encoding encoding)
Serializes current ActSendReportType object into an XML string
string XML value
virtual string SDC.ActSendReportType.Serialize()
Referenced by SDC.ActSendReportType.SaveToFile.
virtual bool SDC.ActSendReportType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ActSendReportType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ActSendReportType.SaveToFile.
virtual bool SDC.ActSendReportType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ActSendReportType.SaveToFile(string fileName)
virtual void SDC.ActSendReportType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ActSendReportType.ShouldSerializereportURI()
Test whether reportURI should be serialized
References SDC.ActSendReportType.reportURI.
virtual bool SDC.ActSendReportType.ShouldSerializereportInstanceGuid()
Test whether reportInstanceGuid should be serialized
References SDC.ActSendReportType.reportInstanceGuid.
virtual string SDC.ActSendReportType.Serialize()
Serializes current ActSendReportType object into an XML string
string XML value
virtual bool SDC.ActSendReportType.SaveToFile(string fileName, out Exception exception)
Serializes current ActSendReportType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ActSendReportType.SaveToFile.
virtual void SDC.ActSendReportType.SaveToFile(string fileName)
References SDC.null, SDC.ActSendReportType.Serialize.
virtual ActSendReportType SDC.ActSendReportType.Clone()
Create a clone of this ActSendReportType object
static bool SDC.ActSendReportType.Deserialize(string input, out ActSendReportType obj, out System.Exception exception)
Deserializes workflow markup into an ActSendReportType object
input string workflow markup to deserialize obj Output ActSendReportType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActSendReportType.Deserialize, SDC.ActSendReportType.LoadFromFile.
static bool SDC.ActSendReportType.Deserialize(string input, out ActSendReportType obj)
References SDC.null.
static new ActSendReportType SDC.ActSendReportType.Deserialize(string input)
References SDC.null.
static ActSendReportType SDC.ActSendReportType.Deserialize(System.IO.Stream s)
static bool SDC.ActSendReportType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ActSendReportType obj, out System.Exception exception)
Deserializes xml markup from file into an ActSendReportType object
fileName string xml file to load and deserialize obj Output ActSendReportType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActSendReportType.LoadFromFile.
static bool SDC.ActSendReportType.LoadFromFile(string fileName, out ActSendReportType obj, out System.Exception exception)
static bool SDC.ActSendReportType.LoadFromFile(string fileName, out ActSendReportType obj)
References SDC.null.
static ActSendReportType SDC.ActSendReportType.LoadFromFile(string fileName)
static new ActSendReportType SDC.ActSendReportType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ActSendReportType.Deserialize(string input, out ActSendReportType obj, out Exception exception)
Deserializes workflow markup into an ActSendReportType object
input string workflow markup to deserialize obj Output ActSendReportType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActSendReportType.Deserialize, SDC.null.
static bool SDC.ActSendReportType.Deserialize(string input, out ActSendReportType obj)
References SDC.ActSendReportType.Deserialize, SDC.null.
static new ActSendReportType SDC.ActSendReportType.Deserialize(string input)
References SDC.null, SDC.ActSendReportType.Serializer.
static ActSendReportType SDC.ActSendReportType.Deserialize(Stream s)
References SDC.ActSendReportType.Serializer.
static bool SDC.ActSendReportType.LoadFromFile(string fileName, out ActSendReportType obj, out Exception exception)
Deserializes xml markup from file into an ActSendReportType object
fileName string xml file to load and deserialize obj Output ActSendReportType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActSendReportType.LoadFromFile, SDC.null.
static bool SDC.ActSendReportType.LoadFromFile(string fileName, out ActSendReportType obj)
References SDC.ActSendReportType.LoadFromFile, SDC.null.
static new ActSendReportType SDC.ActSendReportType.LoadFromFile(string fileName)
References SDC.ActSendReportType.Deserialize, SDC.null.