SDC::XML_DEtype
bool SDC.XML_DEtype::_shouldSerializemaxLength
Referenced by SDC.XML_DEtype.ShouldSerializemaxLength.
bool SDC.XML_DEtype::_shouldSerializeminLength
Referenced by SDC.XML_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.XML_DEtype::_minLength
Referenced by SDC.XML_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.XML_DEtype::_maxLength
Referenced by SDC.XML_DEtype.ShouldSerializemaxLength.
ObjectChangeTracker SDC.XML_DEtype.changeTrackerField
static XmlSerializer SDC.XML_DEtype::serializer
long SDC.XML_DEtype::minLength
bool SDC.XML_DEtype::minLengthSpecified
long SDC.XML_DEtype::maxLength
bool SDC.XML_DEtype::maxLengthSpecified
static XmlSerializer SDC.XML_DEtype::Serializer
Referenced by SDC.XML_DEtype.Deserialize.
ObjectChangeTracker SDC.XML_DEtype.ChangeTracker
SDC.XML_DEtype.XML_DEtype()
SDC.XML_DEtype.XML_DEtype(BaseType parentNode)
SDC.XML_DEtype.XML_DEtype()
virtual bool SDC.XML_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
virtual bool SDC.XML_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
virtual string SDC.XML_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current XML_DEtype object into an XML string
string XML value
virtual string SDC.XML_DEtype.Serialize()
Referenced by SDC.XML_DEtype.SaveToFile.
virtual bool SDC.XML_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current XML_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.XML_DEtype.SaveToFile.
virtual bool SDC.XML_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.XML_DEtype.SaveToFile(string fileName)
virtual void SDC.XML_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.XML_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
References SDC.XML_DEtype._minLength, SDC.XML_DEtype._shouldSerializeminLength.
virtual bool SDC.XML_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
References SDC.XML_DEtype._maxLength, SDC.XML_DEtype._shouldSerializemaxLength.
virtual string SDC.XML_DEtype.Serialize()
Serializes current XML_DEtype object into an XML string
string XML value
virtual bool SDC.XML_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current XML_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.XML_DEtype.SaveToFile.
virtual void SDC.XML_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.XML_DEtype.Serialize.
virtual XML_DEtype SDC.XML_DEtype.Clone()
Create a clone of this XML_DEtype object
static bool SDC.XML_DEtype.Deserialize(string input, out XML_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an XML_DEtype object
input string workflow markup to deserialize obj Output XML_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.XML_DEtype.Deserialize, SDC.XML_DEtype.LoadFromFile.
static bool SDC.XML_DEtype.Deserialize(string input, out XML_DEtype obj)
References SDC.null.
static new XML_DEtype SDC.XML_DEtype.Deserialize(string input)
References SDC.null.
static XML_DEtype SDC.XML_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.XML_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out XML_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an XML_DEtype object
fileName string xml file to load and deserialize obj Output XML_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.XML_DEtype.LoadFromFile.
static bool SDC.XML_DEtype.LoadFromFile(string fileName, out XML_DEtype obj, out System.Exception exception)
static bool SDC.XML_DEtype.LoadFromFile(string fileName, out XML_DEtype obj)
References SDC.null.
static XML_DEtype SDC.XML_DEtype.LoadFromFile(string fileName)
static new XML_DEtype SDC.XML_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.XML_DEtype.Deserialize(string input, out XML_DEtype obj, out Exception exception)
Deserializes workflow markup into an XML_DEtype object
input string workflow markup to deserialize obj Output XML_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.XML_DEtype.Deserialize, SDC.null.
static bool SDC.XML_DEtype.Deserialize(string input, out XML_DEtype obj)
References SDC.XML_DEtype.Deserialize, SDC.null.
static new XML_DEtype SDC.XML_DEtype.Deserialize(string input)
References SDC.null, SDC.XML_DEtype.Serializer.
static XML_DEtype SDC.XML_DEtype.Deserialize(Stream s)
References SDC.XML_DEtype.Serializer.
static bool SDC.XML_DEtype.LoadFromFile(string fileName, out XML_DEtype obj, out Exception exception)
Deserializes xml markup from file into an XML_DEtype object
fileName string xml file to load and deserialize obj Output XML_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.XML_DEtype.LoadFromFile, SDC.null.
static bool SDC.XML_DEtype.LoadFromFile(string fileName, out XML_DEtype obj)
References SDC.XML_DEtype.LoadFromFile, SDC.null.
static new XML_DEtype SDC.XML_DEtype.LoadFromFile(string fileName)
References SDC.XML_DEtype.Deserialize, SDC.null.