SDC::ReplacedResponseType
ChangedSelectedItemsType SDC.ReplacedResponseType.SelectedItems_Item
"SelectedItems", typeof(ChangedSelectedItemsType), IsNullable = true
DataTypes_SType SDC.ReplacedResponseType.Response_Item
"Response", typeof(DataTypes_SType), IsNullable = true,
virtual string_Stype SDC.ReplacedResponseType.ResponseComment
Comment added to the original response that was replaced, at the time it was first entered. This comment refers to the response that was replaced, not the replacement activity or the replacement values.
virtual PersonType SDC.ReplacedResponseType.ResponseEditor
Original editor of the response that was replaced, when it was first entered. This editor refers to the response that was replaced, not the replacement activity.
virtual dateTime_Stype SDC.ReplacedResponseType.ResponseDateTime
Date/Time that the response was first entered. This date/time refers to the response that was replaced, not the replacement activity.
virtual ExtensionBaseType SDC.ReplacedResponseType.Item
XmlSerializer SDC.ReplacedResponseType.Serializer
Referenced by SDC.ReplacedResponseType.Deserialize.
ObjectChangeTracker SDC.ReplacedResponseType.ChangeTracker
string_Stype SDC.ReplacedResponseType._responseComment
Referenced by SDC.ReplacedResponseType.ShouldSerializeResponseComment.
PersonType SDC.ReplacedResponseType._responseEditor
Referenced by SDC.ReplacedResponseType.ShouldSerializeResponseEditor.
dateTime_Stype SDC.ReplacedResponseType._responseDateTime
Referenced by SDC.ReplacedResponseType.ShouldSerializeResponseDateTime.
ExtensionBaseType SDC.ReplacedResponseType._item
Referenced by SDC.ReplacedResponseType.ShouldSerializeItem.
ObjectChangeTracker SDC.ReplacedResponseType.changeTrackerField
XmlSerializer SDC.ReplacedResponseType.serializer
SDC.ReplacedResponseType.ReplacedResponseType()
virtual bool SDC.ReplacedResponseType.ShouldSerializeResponseComment()
Test whether ResponseComment should be serialized
References SDC.ReplacedResponseType._responseComment, SDC.null.
virtual bool SDC.ReplacedResponseType.ShouldSerializeResponseEditor()
Test whether ResponseEditor should be serialized
References SDC.ReplacedResponseType._responseEditor, SDC.null.
virtual bool SDC.ReplacedResponseType.ShouldSerializeResponseDateTime()
Test whether ResponseDateTime should be serialized
References SDC.ReplacedResponseType._responseDateTime, SDC.null.
virtual bool SDC.ReplacedResponseType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.ReplacedResponseType._item, SDC.null.
virtual string SDC.ReplacedResponseType.Serialize()
Serializes current ReplacedResponseType object into an XML string
string XML value
Referenced by SDC.ReplacedResponseType.SaveToFile.
virtual bool SDC.ReplacedResponseType.SaveToFile(string fileName, out Exception exception)
Serializes current ReplacedResponseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.ReplacedResponseType.SaveToFile(string fileName)
References SDC.null, SDC.ReplacedResponseType.Serialize.
virtual ReplacedResponseType SDC.ReplacedResponseType.Clone()
Create a clone of this ReplacedResponseType object
static bool SDC.ReplacedResponseType.Deserialize(string input, out ReplacedResponseType obj, out Exception exception)
Deserializes workflow markup into an ReplacedResponseType object
input string workflow markup to deserialize obj Output ReplacedResponseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReplacedResponseType.Deserialize, SDC.ReplacedResponseType.LoadFromFile.
static bool SDC.ReplacedResponseType.Deserialize(string input, out ReplacedResponseType obj)
References SDC.ReplacedResponseType.Deserialize, SDC.null.
static new ReplacedResponseType SDC.ReplacedResponseType.Deserialize(string input)
References SDC.null, SDC.ReplacedResponseType.Serializer.
static ReplacedResponseType SDC.ReplacedResponseType.Deserialize(Stream s)
References SDC.ReplacedResponseType.Serializer.
static bool SDC.ReplacedResponseType.LoadFromFile(string fileName, out ReplacedResponseType obj, out Exception exception)
Deserializes xml markup from file into an ReplacedResponseType object
fileName string xml file to load and deserialize obj Output ReplacedResponseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReplacedResponseType.LoadFromFile.
static bool SDC.ReplacedResponseType.LoadFromFile(string fileName, out ReplacedResponseType obj)
References SDC.ReplacedResponseType.LoadFromFile, SDC.null.
static new ReplacedResponseType SDC.ReplacedResponseType.LoadFromFile(string fileName)
References SDC.ReplacedResponseType.Deserialize, SDC.null.