SDC::AreaCodeType
bool SDC.AreaCodeType::_shouldSerializeval
Referenced by SDC.AreaCodeType.ShouldSerializeval.
System Nullable< ushort > SDC.AreaCodeType::_val
Referenced by SDC.AreaCodeType.ShouldSerializeval.
ObjectChangeTracker SDC.AreaCodeType.changeTrackerField
static XmlSerializer SDC.AreaCodeType::serializer
ushort SDC.AreaCodeType::val
bool SDC.AreaCodeType::valSpecified
static XmlSerializer SDC.AreaCodeType::Serializer
Referenced by SDC.AreaCodeType.Deserialize.
ObjectChangeTracker SDC.AreaCodeType.ChangeTracker
SDC.AreaCodeType.AreaCodeType()
SDC.AreaCodeType.AreaCodeType(BaseType parentNode)
virtual bool SDC.AreaCodeType.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.AreaCodeType.Serialize(System.Text.Encoding encoding)
Serializes current AreaCodeType object into an XML string
string XML value
virtual string SDC.AreaCodeType.Serialize()
Referenced by SDC.AreaCodeType.SaveToFile.
virtual bool SDC.AreaCodeType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current AreaCodeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.AreaCodeType.SaveToFile.
virtual bool SDC.AreaCodeType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.AreaCodeType.SaveToFile(string fileName)
virtual void SDC.AreaCodeType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.AreaCodeType.ShouldSerializeval()
Test whether val should be serialized
References SDC.AreaCodeType._shouldSerializeval, SDC.AreaCodeType._val.
virtual string SDC.AreaCodeType.Serialize()
Serializes current AreaCodeType object into an XML string
string XML value
virtual bool SDC.AreaCodeType.SaveToFile(string fileName, out Exception exception)
Serializes current AreaCodeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.AreaCodeType.SaveToFile.
virtual void SDC.AreaCodeType.SaveToFile(string fileName)
References SDC.null, SDC.AreaCodeType.Serialize.
virtual AreaCodeType SDC.AreaCodeType.Clone()
Create a clone of this AreaCodeType object
static bool SDC.AreaCodeType.Deserialize(string input, out AreaCodeType obj, out System.Exception exception)
Deserializes workflow markup into an AreaCodeType object
input string workflow markup to deserialize obj Output AreaCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AreaCodeType.Deserialize, SDC.AreaCodeType.LoadFromFile.
static bool SDC.AreaCodeType.Deserialize(string input, out AreaCodeType obj)
References SDC.null.
static new AreaCodeType SDC.AreaCodeType.Deserialize(string input)
References SDC.null.
static AreaCodeType SDC.AreaCodeType.Deserialize(System.IO.Stream s)
static bool SDC.AreaCodeType.LoadFromFile(string fileName, System.Text.Encoding encoding, out AreaCodeType obj, out System.Exception exception)
Deserializes xml markup from file into an AreaCodeType object
fileName string xml file to load and deserialize obj Output AreaCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AreaCodeType.LoadFromFile.
static bool SDC.AreaCodeType.LoadFromFile(string fileName, out AreaCodeType obj, out System.Exception exception)
static bool SDC.AreaCodeType.LoadFromFile(string fileName, out AreaCodeType obj)
References SDC.null.
static AreaCodeType SDC.AreaCodeType.LoadFromFile(string fileName)
static new AreaCodeType SDC.AreaCodeType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.AreaCodeType.Deserialize(string input, out AreaCodeType obj, out Exception exception)
Deserializes workflow markup into an AreaCodeType object
input string workflow markup to deserialize obj Output AreaCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.AreaCodeType.Deserialize, SDC.null.
static bool SDC.AreaCodeType.Deserialize(string input, out AreaCodeType obj)
References SDC.AreaCodeType.Deserialize, SDC.null.
static new AreaCodeType SDC.AreaCodeType.Deserialize(string input)
References SDC.null, SDC.AreaCodeType.Serializer.
static AreaCodeType SDC.AreaCodeType.Deserialize(Stream s)
References SDC.AreaCodeType.Serializer.
static bool SDC.AreaCodeType.LoadFromFile(string fileName, out AreaCodeType obj, out Exception exception)
Deserializes xml markup from file into an AreaCodeType object
fileName string xml file to load and deserialize obj Output AreaCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.AreaCodeType.LoadFromFile, SDC.null.
static bool SDC.AreaCodeType.LoadFromFile(string fileName, out AreaCodeType obj)
References SDC.AreaCodeType.LoadFromFile, SDC.null.
static new AreaCodeType SDC.AreaCodeType.LoadFromFile(string fileName)
References SDC.AreaCodeType.Deserialize, SDC.null.