SDC::unsignedByte_DEtype
System Nullable< byte > SDC.unsignedByte_DEtype::_minInclusive
System Nullable< byte > SDC.unsignedByte_DEtype::_maxInclusive
System Nullable< byte > SDC.unsignedByte_DEtype::_minExclusive
System Nullable< byte > SDC.unsignedByte_DEtype::_maxExclusive
System Nullable< byte > SDC.unsignedByte_DEtype::_totalDigits
string SDC.unsignedByte_DEtype::_mask
ObjectChangeTracker SDC.unsignedByte_DEtype.changeTrackerField
static XmlSerializer SDC.unsignedByte_DEtype::serializer
byte SDC.unsignedByte_DEtype::minInclusive
bool SDC.unsignedByte_DEtype::minInclusiveSpecified
byte SDC.unsignedByte_DEtype::maxInclusive
bool SDC.unsignedByte_DEtype::maxInclusiveSpecified
byte SDC.unsignedByte_DEtype::minExclusive
bool SDC.unsignedByte_DEtype::minExclusiveSpecified
byte SDC.unsignedByte_DEtype::maxExclusive
bool SDC.unsignedByte_DEtype::maxExclusiveSpecified
byte SDC.unsignedByte_DEtype::totalDigits
bool SDC.unsignedByte_DEtype::totalDigitsSpecified
string SDC.unsignedByte_DEtype::mask
Referenced by SDC.unsignedByte_DEtype.ShouldSerializemask.
static XmlSerializer SDC.unsignedByte_DEtype::Serializer
Referenced by SDC.unsignedByte_DEtype.Deserialize.
ObjectChangeTracker SDC.unsignedByte_DEtype.ChangeTracker
SDC.unsignedByte_DEtype.unsignedByte_DEtype()
SDC.unsignedByte_DEtype.unsignedByte_DEtype(BaseType parentNode)
virtual bool SDC.unsignedByte_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.unsignedByte_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current unsignedByte_DEtype object into an XML string
string XML value
virtual string SDC.unsignedByte_DEtype.Serialize()
Referenced by SDC.unsignedByte_DEtype.SaveToFile.
virtual bool SDC.unsignedByte_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current unsignedByte_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.unsignedByte_DEtype.SaveToFile.
virtual bool SDC.unsignedByte_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.unsignedByte_DEtype.SaveToFile(string fileName)
virtual void SDC.unsignedByte_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.unsignedByte_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.unsignedByte_DEtype.mask.
virtual string SDC.unsignedByte_DEtype.Serialize()
Serializes current unsignedByte_DEtype object into an XML string
string XML value
virtual bool SDC.unsignedByte_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current unsignedByte_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.unsignedByte_DEtype.SaveToFile.
virtual void SDC.unsignedByte_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.unsignedByte_DEtype.Serialize.
virtual unsignedByte_DEtype SDC.unsignedByte_DEtype.Clone()
Create a clone of this unsignedByte_DEtype object
static bool SDC.unsignedByte_DEtype.Deserialize(string input, out unsignedByte_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an unsignedByte_DEtype object
input string workflow markup to deserialize obj Output unsignedByte_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedByte_DEtype.Deserialize, SDC.unsignedByte_DEtype.LoadFromFile.
static bool SDC.unsignedByte_DEtype.Deserialize(string input, out unsignedByte_DEtype obj)
References SDC.null.
static new unsignedByte_DEtype SDC.unsignedByte_DEtype.Deserialize(string input)
References SDC.null.
static unsignedByte_DEtype SDC.unsignedByte_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.unsignedByte_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out unsignedByte_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an unsignedByte_DEtype object
fileName string xml file to load and deserialize obj Output unsignedByte_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedByte_DEtype.LoadFromFile.
static bool SDC.unsignedByte_DEtype.LoadFromFile(string fileName, out unsignedByte_DEtype obj, out System.Exception exception)
static bool SDC.unsignedByte_DEtype.LoadFromFile(string fileName, out unsignedByte_DEtype obj)
References SDC.null.
static unsignedByte_DEtype SDC.unsignedByte_DEtype.LoadFromFile(string fileName)
static new unsignedByte_DEtype SDC.unsignedByte_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.unsignedByte_DEtype.Deserialize(string input, out unsignedByte_DEtype obj, out Exception exception)
Deserializes workflow markup into an unsignedByte_DEtype object
input string workflow markup to deserialize obj Output unsignedByte_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedByte_DEtype.Deserialize, SDC.null.
static bool SDC.unsignedByte_DEtype.Deserialize(string input, out unsignedByte_DEtype obj)
References SDC.unsignedByte_DEtype.Deserialize, SDC.null.
static new unsignedByte_DEtype SDC.unsignedByte_DEtype.Deserialize(string input)
References SDC.null, SDC.unsignedByte_DEtype.Serializer.
static unsignedByte_DEtype SDC.unsignedByte_DEtype.Deserialize(Stream s)
References SDC.unsignedByte_DEtype.Serializer.
static bool SDC.unsignedByte_DEtype.LoadFromFile(string fileName, out unsignedByte_DEtype obj, out Exception exception)
Deserializes xml markup from file into an unsignedByte_DEtype object
fileName string xml file to load and deserialize obj Output unsignedByte_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedByte_DEtype.LoadFromFile, SDC.null.
static bool SDC.unsignedByte_DEtype.LoadFromFile(string fileName, out unsignedByte_DEtype obj)
References SDC.unsignedByte_DEtype.LoadFromFile, SDC.null.
static new unsignedByte_DEtype SDC.unsignedByte_DEtype.LoadFromFile(string fileName)
References SDC.unsignedByte_DEtype.Deserialize, SDC.null.