SDC::InputStr_ReturnIntegerListType
bool SDC.InputStr_ReturnIntegerListType._shouldSerializeuseDelimiter
Referenced by SDC.InputStr_ReturnIntegerListType.ShouldSerializeuseDelimiter.
StringFunctionsStrType SDC.InputStr_ReturnIntegerListType._inputStr
Referenced by SDC.InputStr_ReturnIntegerListType.ShouldSerializeInputStr.
System.Nullable<bool> SDC.InputStr_ReturnIntegerListType._useDelimiter
Referenced by SDC.InputStr_ReturnIntegerListType.ShouldSerializeuseDelimiter.
InputStr_ReturnStrListTypeDelimiter SDC.InputStr_ReturnIntegerListType._delimiter
XmlSerializer SDC.InputStr_ReturnIntegerListType.serializer
virtual StringFunctionsStrType SDC.InputStr_ReturnIntegerListType.InputStr
virtual bool SDC.InputStr_ReturnIntegerListType.useDelimiter
If a delimiter is not used, then any white space will delimit the list items. The default delimiter is a space.
virtual bool SDC.InputStr_ReturnIntegerListType.useDelimiterSpecified
virtual InputStr_ReturnStrListTypeDelimiter SDC.InputStr_ReturnIntegerListType.delimiter
XmlSerializer SDC.InputStr_ReturnIntegerListType.Serializer
Referenced by SDC.InputStr_ReturnIntegerListType.Deserialize.
SDC.InputStr_ReturnIntegerListType.InputStr_ReturnIntegerListType()
InputStr_ReturnIntegerListType class constructor
virtual bool SDC.InputStr_ReturnIntegerListType.ShouldSerializeuseDelimiter()
Test whether useDelimiter should be serialized
References SDC.InputStr_ReturnIntegerListType._shouldSerializeuseDelimiter, SDC.InputStr_ReturnIntegerListType._useDelimiter.
virtual bool SDC.InputStr_ReturnIntegerListType.ShouldSerializeInputStr()
Test whether InputStr should be serialized
References SDC.InputStr_ReturnIntegerListType._inputStr, SDC.null.
virtual string SDC.InputStr_ReturnIntegerListType.Serialize(System.Text.Encoding encoding)
Serializes current InputStr_ReturnIntegerListType object into an XML string
string XML value
virtual string SDC.InputStr_ReturnIntegerListType.Serialize()
Referenced by SDC.InputStr_ReturnIntegerListType.SaveToFile.
virtual bool SDC.InputStr_ReturnIntegerListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InputStr_ReturnIntegerListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InputStr_ReturnIntegerListType.SaveToFile.
virtual bool SDC.InputStr_ReturnIntegerListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.InputStr_ReturnIntegerListType.SaveToFile.
virtual void SDC.InputStr_ReturnIntegerListType.SaveToFile(string fileName)
References SDC.InputStr_ReturnIntegerListType.SaveToFile.
virtual void SDC.InputStr_ReturnIntegerListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InputStr_ReturnIntegerListType.Serialize.
static bool SDC.InputStr_ReturnIntegerListType.Deserialize(string input, out InputStr_ReturnIntegerListType obj, out System.Exception exception)
Deserializes workflow markup into an InputStr_ReturnIntegerListType object
input string workflow markup to deserialize obj Output InputStr_ReturnIntegerListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnIntegerListType.Deserialize, SDC.InputStr_ReturnIntegerListType.LoadFromFile.
static bool SDC.InputStr_ReturnIntegerListType.Deserialize(string input, out InputStr_ReturnIntegerListType obj)
References SDC.InputStr_ReturnIntegerListType.Deserialize, SDC.null.
static new InputStr_ReturnIntegerListType SDC.InputStr_ReturnIntegerListType.Deserialize(string input)
References SDC.null.
static InputStr_ReturnIntegerListType SDC.InputStr_ReturnIntegerListType.Deserialize(System.IO.Stream s)
References SDC.InputStr_ReturnIntegerListType.Serializer.
static bool SDC.InputStr_ReturnIntegerListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out InputStr_ReturnIntegerListType obj, out System.Exception exception)
Deserializes xml markup from file into an InputStr_ReturnIntegerListType object
fileName string xml file to load and deserialize obj Output InputStr_ReturnIntegerListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnIntegerListType.LoadFromFile.
static bool SDC.InputStr_ReturnIntegerListType.LoadFromFile(string fileName, out InputStr_ReturnIntegerListType obj, out System.Exception exception)
References SDC.InputStr_ReturnIntegerListType.LoadFromFile.
static bool SDC.InputStr_ReturnIntegerListType.LoadFromFile(string fileName, out InputStr_ReturnIntegerListType obj)
References SDC.InputStr_ReturnIntegerListType.LoadFromFile, SDC.null.
static InputStr_ReturnIntegerListType SDC.InputStr_ReturnIntegerListType.LoadFromFile(string fileName)
References SDC.InputStr_ReturnIntegerListType.LoadFromFile.
static new InputStr_ReturnIntegerListType SDC.InputStr_ReturnIntegerListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InputStr_ReturnIntegerListType.Deserialize, SDC.null.