SDC::byte_DEtype
bool SDC.byte_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.byte_DEtype.ShouldSerializemaxExclusive.
bool SDC.byte_DEtype::_shouldSerializeminExclusive
Referenced by SDC.byte_DEtype.ShouldSerializeminExclusive.
bool SDC.byte_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.byte_DEtype.ShouldSerializemaxInclusive.
bool SDC.byte_DEtype::_shouldSerializeminInclusive
Referenced by SDC.byte_DEtype.ShouldSerializeminInclusive.
System Nullable< sbyte > SDC.byte_DEtype::_minInclusive
Referenced by SDC.byte_DEtype.ShouldSerializeminInclusive.
System Nullable< sbyte > SDC.byte_DEtype::_maxInclusive
Referenced by SDC.byte_DEtype.ShouldSerializemaxInclusive.
System Nullable< sbyte > SDC.byte_DEtype::_minExclusive
Referenced by SDC.byte_DEtype.ShouldSerializeminExclusive.
System Nullable< sbyte > SDC.byte_DEtype::_maxExclusive
Referenced by SDC.byte_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.byte_DEtype::_totalDigits
string SDC.byte_DEtype::_mask
ObjectChangeTracker SDC.byte_DEtype.changeTrackerField
static XmlSerializer SDC.byte_DEtype::serializer
sbyte SDC.byte_DEtype::minInclusive
bool SDC.byte_DEtype::minInclusiveSpecified
sbyte SDC.byte_DEtype::maxInclusive
bool SDC.byte_DEtype::maxInclusiveSpecified
sbyte SDC.byte_DEtype::minExclusive
bool SDC.byte_DEtype::minExclusiveSpecified
sbyte SDC.byte_DEtype::maxExclusive
bool SDC.byte_DEtype::maxExclusiveSpecified
byte SDC.byte_DEtype::totalDigits
bool SDC.byte_DEtype::totalDigitsSpecified
string SDC.byte_DEtype::mask
Referenced by SDC.byte_DEtype.ShouldSerializemask.
static XmlSerializer SDC.byte_DEtype::Serializer
Referenced by SDC.byte_DEtype.Deserialize.
ObjectChangeTracker SDC.byte_DEtype.ChangeTracker
SDC.byte_DEtype.byte_DEtype()
SDC.byte_DEtype.byte_DEtype(BaseType parentNode)
virtual bool SDC.byte_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.byte_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.byte_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.byte_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.byte_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.byte_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current byte_DEtype object into an XML string
string XML value
virtual string SDC.byte_DEtype.Serialize()
Referenced by SDC.byte_DEtype.SaveToFile.
virtual bool SDC.byte_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current byte_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.byte_DEtype.SaveToFile.
virtual bool SDC.byte_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.byte_DEtype.SaveToFile(string fileName)
virtual void SDC.byte_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.byte_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.byte_DEtype._minInclusive, SDC.byte_DEtype._shouldSerializeminInclusive.
virtual bool SDC.byte_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.byte_DEtype._maxInclusive, SDC.byte_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.byte_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.byte_DEtype._minExclusive, SDC.byte_DEtype._shouldSerializeminExclusive.
virtual bool SDC.byte_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.byte_DEtype._maxExclusive, SDC.byte_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.byte_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.byte_DEtype.mask.
virtual string SDC.byte_DEtype.Serialize()
Serializes current byte_DEtype object into an XML string
string XML value
virtual bool SDC.byte_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current byte_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.byte_DEtype.SaveToFile.
virtual void SDC.byte_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.byte_DEtype.Serialize.
virtual byte_DEtype SDC.byte_DEtype.Clone()
Create a clone of this byte_DEtype object
static bool SDC.byte_DEtype.Deserialize(string input, out byte_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an byte_DEtype object
input string workflow markup to deserialize obj Output byte_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.byte_DEtype.Deserialize, SDC.byte_DEtype.LoadFromFile.
static bool SDC.byte_DEtype.Deserialize(string input, out byte_DEtype obj)
References SDC.null.
static new byte_DEtype SDC.byte_DEtype.Deserialize(string input)
References SDC.null.
static byte_DEtype SDC.byte_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.byte_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out byte_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an byte_DEtype object
fileName string xml file to load and deserialize obj Output byte_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.byte_DEtype.LoadFromFile.
static bool SDC.byte_DEtype.LoadFromFile(string fileName, out byte_DEtype obj, out System.Exception exception)
static bool SDC.byte_DEtype.LoadFromFile(string fileName, out byte_DEtype obj)
References SDC.null.
static byte_DEtype SDC.byte_DEtype.LoadFromFile(string fileName)
static new byte_DEtype SDC.byte_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.byte_DEtype.Deserialize(string input, out byte_DEtype obj, out Exception exception)
Deserializes workflow markup into an byte_DEtype object
input string workflow markup to deserialize obj Output byte_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.byte_DEtype.Deserialize, SDC.null.
static bool SDC.byte_DEtype.Deserialize(string input, out byte_DEtype obj)
References SDC.byte_DEtype.Deserialize, SDC.null.
static new byte_DEtype SDC.byte_DEtype.Deserialize(string input)
References SDC.null, SDC.byte_DEtype.Serializer.
static byte_DEtype SDC.byte_DEtype.Deserialize(Stream s)
References SDC.byte_DEtype.Serializer.
static bool SDC.byte_DEtype.LoadFromFile(string fileName, out byte_DEtype obj, out Exception exception)
Deserializes xml markup from file into an byte_DEtype object
fileName string xml file to load and deserialize obj Output byte_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.byte_DEtype.LoadFromFile, SDC.null.
static bool SDC.byte_DEtype.LoadFromFile(string fileName, out byte_DEtype obj)
References SDC.byte_DEtype.LoadFromFile, SDC.null.
static new byte_DEtype SDC.byte_DEtype.LoadFromFile(string fileName)
References SDC.byte_DEtype.Deserialize, SDC.null.