SDC::MaxInclusiveType
string SDC.MaxInclusiveType._val
ObjectChangeTracker SDC.MaxInclusiveType.changeTrackerField
XmlSerializer SDC.MaxInclusiveType.serializer
virtual string SDC.MaxInclusiveType.val
Referenced by SDC.MaxInclusiveType.ShouldSerializeval.
XmlSerializer SDC.MaxInclusiveType.Serializer
Referenced by SDC.MaxInclusiveType.Deserialize.
ObjectChangeTracker SDC.MaxInclusiveType.ChangeTracker
SDC.MaxInclusiveType.MaxInclusiveType()
virtual bool SDC.MaxInclusiveType.ShouldSerializeval()
Test whether val should be serialized
References SDC.MaxInclusiveType.val.
virtual string SDC.MaxInclusiveType.Serialize()
Serializes current MaxInclusiveType object into an XML string
string XML value
Referenced by SDC.MaxInclusiveType.SaveToFile.
virtual bool SDC.MaxInclusiveType.SaveToFile(string fileName, out Exception exception)
Serializes current MaxInclusiveType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.MaxInclusiveType.SaveToFile(string fileName)
References SDC.null, SDC.MaxInclusiveType.Serialize.
virtual MaxInclusiveType SDC.MaxInclusiveType.Clone()
Create a clone of this MaxInclusiveType object
static bool SDC.MaxInclusiveType.Deserialize(string input, out MaxInclusiveType obj, out Exception exception)
Deserializes workflow markup into an MaxInclusiveType object
input string workflow markup to deserialize obj Output MaxInclusiveType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.MaxInclusiveType.Deserialize, SDC.MaxInclusiveType.LoadFromFile.
static bool SDC.MaxInclusiveType.Deserialize(string input, out MaxInclusiveType obj)
References SDC.MaxInclusiveType.Deserialize, SDC.null.
static new MaxInclusiveType SDC.MaxInclusiveType.Deserialize(string input)
References SDC.null, SDC.MaxInclusiveType.Serializer.
static MaxInclusiveType SDC.MaxInclusiveType.Deserialize(Stream s)
References SDC.MaxInclusiveType.Serializer.
static bool SDC.MaxInclusiveType.LoadFromFile(string fileName, out MaxInclusiveType obj, out Exception exception)
Deserializes xml markup from file into an MaxInclusiveType object
fileName string xml file to load and deserialize obj Output MaxInclusiveType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.MaxInclusiveType.LoadFromFile.
static bool SDC.MaxInclusiveType.LoadFromFile(string fileName, out MaxInclusiveType obj)
References SDC.MaxInclusiveType.LoadFromFile, SDC.null.
static new MaxInclusiveType SDC.MaxInclusiveType.LoadFromFile(string fileName)
References SDC.MaxInclusiveType.Deserialize, SDC.null.