SDC::ExtensionBaseType
List<CommentType> SDC.ExtensionBaseType._comment
List<ExtensionType> SDC.ExtensionBaseType._extension
List<PropertyType> SDC.ExtensionBaseType._property
BindingList<CommentType> SDC.ExtensionBaseType._comment
BindingList<ExtensionType> SDC.ExtensionBaseType._extension
ObjectChangeTracker SDC.ExtensionBaseType.changeTrackerField
static XmlSerializer SDC.ExtensionBaseType::serializer
virtual List<CommentType> SDC.ExtensionBaseType.Comment
Referenced by SDC.SDCTreeBuilderEcc.AddComment, SDC.SDCTreeBuilder.AddComment, SDC.SDCTreeBuilder.AddFillComment.
virtual List<ExtensionType> SDC.ExtensionBaseType.Extension
Referenced by SDC.SDCTreeBuilderEcc.AddExtension, SDC.SDCTreeBuilder.AddExtension, SDC.SDCTreeBuilderEcc.AddFillExtension.
virtual List<PropertyType> SDC.ExtensionBaseType.Property
Referenced by SDC.SDCTreeBuilder.AddProperty.
static XmlSerializer SDC.ExtensionBaseType::Serializer
Referenced by SDC.ExtensionBaseType.Deserialize.
virtual BindingList<CommentType> SDC.ExtensionBaseType.Comment
virtual BindingList<ExtensionType> SDC.ExtensionBaseType.Extension
ObjectChangeTracker SDC.ExtensionBaseType.ChangeTracker
SDC.ExtensionBaseType.ExtensionBaseType()
SDC.ExtensionBaseType.ExtensionBaseType(BaseType parentNode, bool fillData=true)
References SDC.ExtensionBaseType.AddFillExtensionBaseType.
CommentType SDC.ExtensionBaseType.AddFillComment(Boolean fillData=true)
ExtensionType SDC.ExtensionBaseType.AddFillExtension(Boolean fillData=true)
ExtensionBaseType SDC.ExtensionBaseType.AddFillExtensionBaseType(Boolean fillData=true)
Referenced by SDC.ExtensionBaseType.ExtensionBaseType.
SDC.ExtensionBaseType.ExtensionBaseType()
ExtensionBaseType SDC.ExtensionBaseType.FillExtensionBaseType()
ExtensionType SDC.ExtensionBaseType.AddExtension()
CommentType SDC.ExtensionBaseType.AddComment()
virtual bool SDC.ExtensionBaseType.ShouldSerializeComment()
Test whether Comment should be serialized
References SDC.null.
virtual bool SDC.ExtensionBaseType.ShouldSerializeExtension()
Test whether Extension should be serialized
References SDC.null.
virtual bool SDC.ExtensionBaseType.ShouldSerializeProperty()
Test whether Property should be serialized
References SDC.null.
virtual string SDC.ExtensionBaseType.Serialize(System.Text.Encoding encoding)
Serializes current ExtensionBaseType object into an XML string
string XML value
virtual string SDC.ExtensionBaseType.Serialize()
Referenced by SDC.ExtensionBaseType.SaveToFile.
virtual bool SDC.ExtensionBaseType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ExtensionBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ExtensionBaseType.SaveToFile.
virtual bool SDC.ExtensionBaseType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ExtensionBaseType.SaveToFile(string fileName)
virtual void SDC.ExtensionBaseType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ExtensionBaseType.Serialize()
Serializes current ExtensionBaseType object into an XML string
string XML value
virtual bool SDC.ExtensionBaseType.SaveToFile(string fileName, out Exception exception)
Serializes current ExtensionBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ExtensionBaseType.SaveToFile.
virtual void SDC.ExtensionBaseType.SaveToFile(string fileName)
References SDC.null, SDC.ExtensionBaseType.Serialize.
virtual ExtensionBaseType SDC.ExtensionBaseType.Clone()
Create a clone of this ExtensionBaseType object
static bool SDC.ExtensionBaseType.Deserialize(string input, out ExtensionBaseType obj, out System.Exception exception)
Deserializes workflow markup into an ExtensionBaseType object
input string workflow markup to deserialize obj Output ExtensionBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ExtensionBaseType.Deserialize, SDC.ExtensionBaseType.LoadFromFile.
static bool SDC.ExtensionBaseType.Deserialize(string input, out ExtensionBaseType obj)
References SDC.null.
static new ExtensionBaseType SDC.ExtensionBaseType.Deserialize(string input)
References SDC.null.
static ExtensionBaseType SDC.ExtensionBaseType.Deserialize(System.IO.Stream s)
static bool SDC.ExtensionBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ExtensionBaseType obj, out System.Exception exception)
Deserializes xml markup from file into an ExtensionBaseType object
fileName string xml file to load and deserialize obj Output ExtensionBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ExtensionBaseType.LoadFromFile.
static bool SDC.ExtensionBaseType.LoadFromFile(string fileName, out ExtensionBaseType obj, out System.Exception exception)
static bool SDC.ExtensionBaseType.LoadFromFile(string fileName, out ExtensionBaseType obj)
References SDC.null.
static ExtensionBaseType SDC.ExtensionBaseType.LoadFromFile(string fileName)
static new ExtensionBaseType SDC.ExtensionBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ExtensionBaseType.Deserialize(string input, out ExtensionBaseType obj, out Exception exception)
Deserializes workflow markup into an ExtensionBaseType object
input string workflow markup to deserialize obj Output ExtensionBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ExtensionBaseType.Deserialize, SDC.null.
static bool SDC.ExtensionBaseType.Deserialize(string input, out ExtensionBaseType obj)
References SDC.ExtensionBaseType.Deserialize, SDC.null.
static new ExtensionBaseType SDC.ExtensionBaseType.Deserialize(string input)
References SDC.null, SDC.ExtensionBaseType.Serializer.
static ExtensionBaseType SDC.ExtensionBaseType.Deserialize(Stream s)
References SDC.ExtensionBaseType.Serializer.
static bool SDC.ExtensionBaseType.LoadFromFile(string fileName, out ExtensionBaseType obj, out Exception exception)
Deserializes xml markup from file into an ExtensionBaseType object
fileName string xml file to load and deserialize obj Output ExtensionBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ExtensionBaseType.LoadFromFile, SDC.null.
static bool SDC.ExtensionBaseType.LoadFromFile(string fileName, out ExtensionBaseType obj)
References SDC.ExtensionBaseType.LoadFromFile, SDC.null.
static new ExtensionBaseType SDC.ExtensionBaseType.LoadFromFile(string fileName)
References SDC.ExtensionBaseType.Deserialize, SDC.null.