SDC::LanguageCodeISO6393_Type
static XmlSerializer SDC.LanguageCodeISO6393_Type::serializer
static XmlSerializer SDC.LanguageCodeISO6393_Type::Serializer
Referenced by SDC.LanguageCodeISO6393_Type.Deserialize.
ObjectChangeTracker SDC.LanguageCodeISO6393_Type.ChangeTracker
ObjectChangeTracker SDC.LanguageCodeISO6393_Type.changeTrackerField
SDC.LanguageCodeISO6393_Type.LanguageCodeISO6393_Type()
SDC.LanguageCodeISO6393_Type.LanguageCodeISO6393_Type(BaseType parentNode)
virtual string SDC.LanguageCodeISO6393_Type.Serialize(System.Text.Encoding encoding)
Serializes current LanguageCodeISO6393_Type object into an XML string
string XML value
virtual string SDC.LanguageCodeISO6393_Type.Serialize()
Referenced by SDC.LanguageCodeISO6393_Type.SaveToFile.
virtual bool SDC.LanguageCodeISO6393_Type.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current LanguageCodeISO6393_Type object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.LanguageCodeISO6393_Type.SaveToFile.
virtual bool SDC.LanguageCodeISO6393_Type.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.LanguageCodeISO6393_Type.SaveToFile(string fileName)
virtual void SDC.LanguageCodeISO6393_Type.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.LanguageCodeISO6393_Type.Serialize()
Serializes current LanguageCodeISO6393_Type object into an XML string
string XML value
virtual bool SDC.LanguageCodeISO6393_Type.SaveToFile(string fileName, out Exception exception)
Serializes current LanguageCodeISO6393_Type object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.LanguageCodeISO6393_Type.SaveToFile.
virtual void SDC.LanguageCodeISO6393_Type.SaveToFile(string fileName)
References SDC.null, SDC.LanguageCodeISO6393_Type.Serialize.
virtual LanguageCodeISO6393_Type SDC.LanguageCodeISO6393_Type.Clone()
Create a clone of this LanguageCodeISO6393_Type object
static bool SDC.LanguageCodeISO6393_Type.Deserialize(string input, out LanguageCodeISO6393_Type obj, out System.Exception exception)
Deserializes workflow markup into an LanguageCodeISO6393_Type object
input string workflow markup to deserialize obj Output LanguageCodeISO6393_Type object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.LanguageCodeISO6393_Type.Deserialize, SDC.LanguageCodeISO6393_Type.LoadFromFile.
static bool SDC.LanguageCodeISO6393_Type.Deserialize(string input, out LanguageCodeISO6393_Type obj)
References SDC.null.
static new LanguageCodeISO6393_Type SDC.LanguageCodeISO6393_Type.Deserialize(string input)
References SDC.null.
static LanguageCodeISO6393_Type SDC.LanguageCodeISO6393_Type.Deserialize(System.IO.Stream s)
static bool SDC.LanguageCodeISO6393_Type.LoadFromFile(string fileName, System.Text.Encoding encoding, out LanguageCodeISO6393_Type obj, out System.Exception exception)
Deserializes xml markup from file into an LanguageCodeISO6393_Type object
fileName string xml file to load and deserialize obj Output LanguageCodeISO6393_Type object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.LanguageCodeISO6393_Type.LoadFromFile.
static bool SDC.LanguageCodeISO6393_Type.LoadFromFile(string fileName, out LanguageCodeISO6393_Type obj, out System.Exception exception)
static bool SDC.LanguageCodeISO6393_Type.LoadFromFile(string fileName, out LanguageCodeISO6393_Type obj)
References SDC.null.
static LanguageCodeISO6393_Type SDC.LanguageCodeISO6393_Type.LoadFromFile(string fileName)
static new LanguageCodeISO6393_Type SDC.LanguageCodeISO6393_Type.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.LanguageCodeISO6393_Type.Deserialize(string input, out LanguageCodeISO6393_Type obj, out Exception exception)
Deserializes workflow markup into an LanguageCodeISO6393_Type object
input string workflow markup to deserialize obj Output LanguageCodeISO6393_Type object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.LanguageCodeISO6393_Type.Deserialize, SDC.null.
static bool SDC.LanguageCodeISO6393_Type.Deserialize(string input, out LanguageCodeISO6393_Type obj)
References SDC.LanguageCodeISO6393_Type.Deserialize, SDC.null.
static new LanguageCodeISO6393_Type SDC.LanguageCodeISO6393_Type.Deserialize(string input)
References SDC.null, SDC.LanguageCodeISO6393_Type.Serializer.
static LanguageCodeISO6393_Type SDC.LanguageCodeISO6393_Type.Deserialize(Stream s)
References SDC.LanguageCodeISO6393_Type.Serializer.
static bool SDC.LanguageCodeISO6393_Type.LoadFromFile(string fileName, out LanguageCodeISO6393_Type obj, out Exception exception)
Deserializes xml markup from file into an LanguageCodeISO6393_Type object
fileName string xml file to load and deserialize obj Output LanguageCodeISO6393_Type object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.LanguageCodeISO6393_Type.LoadFromFile, SDC.null.
static bool SDC.LanguageCodeISO6393_Type.LoadFromFile(string fileName, out LanguageCodeISO6393_Type obj)
References SDC.LanguageCodeISO6393_Type.LoadFromFile, SDC.null.
static new LanguageCodeISO6393_Type SDC.LanguageCodeISO6393_Type.LoadFromFile(string fileName)
References SDC.LanguageCodeISO6393_Type.Deserialize, SDC.null.