SDC::anyType_DEtype
bool SDC.anyType_DEtype::_shouldSerializemaxLength
Referenced by SDC.anyType_DEtype.ShouldSerializemaxLength.
bool SDC.anyType_DEtype::_shouldSerializeminLength
Referenced by SDC.anyType_DEtype.ShouldSerializeminLength.
List<System.Xml.XmlElement> SDC.anyType_DEtype._any
System Nullable< long > SDC.anyType_DEtype::_minLength
Referenced by SDC.anyType_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.anyType_DEtype::_maxLength
Referenced by SDC.anyType_DEtype.ShouldSerializemaxLength.
string SDC.anyType_DEtype::_schema
string SDC.anyType_DEtype::_namespace
List<System.Xml.XmlAttribute> SDC.anyType_DEtype._anyAttr
BindingList<System.Xml.XmlElement> SDC.anyType_DEtype._any
BindingList<System.Xml.XmlAttribute> SDC.anyType_DEtype._anyAttr
ObjectChangeTracker SDC.anyType_DEtype.changeTrackerField
static XmlSerializer SDC.anyType_DEtype::serializer
virtual List<System.Xml.XmlElement> SDC.anyType_DEtype.Any
long SDC.anyType_DEtype::minLength
bool SDC.anyType_DEtype::minLengthSpecified
long SDC.anyType_DEtype::maxLength
bool SDC.anyType_DEtype::maxLengthSpecified
string SDC.anyType_DEtype::schema
Referenced by SDC.anyType_DEtype.ShouldSerializeschema.
virtual List<System.Xml.XmlAttribute> SDC.anyType_DEtype.AnyAttr
static XmlSerializer SDC.anyType_DEtype::Serializer
Referenced by SDC.anyType_DEtype.Deserialize.
virtual BindingList<System.Xml.XmlElement> SDC.anyType_DEtype.Any
virtual BindingList<System.Xml.XmlAttribute> SDC.anyType_DEtype.AnyAttr
ObjectChangeTracker SDC.anyType_DEtype.ChangeTracker
SDC.anyType_DEtype.anyType_DEtype(BaseType parentNode)
virtual bool SDC.anyType_DEtype.ShouldSerializeAny()
Test whether Any should be serialized
References SDC.null.
virtual bool SDC.anyType_DEtype.ShouldSerializeAnyAttr()
Test whether AnyAttr should be serialized
References SDC.null.
virtual bool SDC.anyType_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
virtual bool SDC.anyType_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
virtual bool SDC.anyType_DEtype.ShouldSerializeschema()
Test whether schema should be serialized
virtual bool SDC.anyType_DEtype.ShouldSerializenamespace()
Test whether namespace should be serialized
virtual string SDC.anyType_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current anyType_DEtype object into an XML string
string XML value
virtual string SDC.anyType_DEtype.Serialize()
Referenced by SDC.anyType_DEtype.SaveToFile.
virtual bool SDC.anyType_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current anyType_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.anyType_DEtype.SaveToFile.
virtual bool SDC.anyType_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.anyType_DEtype.SaveToFile(string fileName)
virtual void SDC.anyType_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.anyType_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
References SDC.anyType_DEtype._minLength, SDC.anyType_DEtype._shouldSerializeminLength.
virtual bool SDC.anyType_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
References SDC.anyType_DEtype._maxLength, SDC.anyType_DEtype._shouldSerializemaxLength.
virtual bool SDC.anyType_DEtype.ShouldSerializeschema()
Test whether schema should be serialized
References SDC.anyType_DEtype.schema.
virtual bool SDC.anyType_DEtype.ShouldSerializenamespace()
Test whether namespace should be serialized
virtual string SDC.anyType_DEtype.Serialize()
Serializes current anyType_DEtype object into an XML string
string XML value
virtual bool SDC.anyType_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current anyType_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.anyType_DEtype.SaveToFile.
virtual void SDC.anyType_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.anyType_DEtype.Serialize.
virtual anyType_DEtype SDC.anyType_DEtype.Clone()
Create a clone of this anyType_DEtype object
SDC.anyType_DEtype.anyType_DEtype()
static bool SDC.anyType_DEtype.Deserialize(string input, out anyType_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an anyType_DEtype object
input string workflow markup to deserialize obj Output anyType_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.anyType_DEtype.Deserialize, SDC.anyType_DEtype.LoadFromFile.
static bool SDC.anyType_DEtype.Deserialize(string input, out anyType_DEtype obj)
References SDC.null.
static new anyType_DEtype SDC.anyType_DEtype.Deserialize(string input)
References SDC.null.
static anyType_DEtype SDC.anyType_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.anyType_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out anyType_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an anyType_DEtype object
fileName string xml file to load and deserialize obj Output anyType_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.anyType_DEtype.LoadFromFile.
static bool SDC.anyType_DEtype.LoadFromFile(string fileName, out anyType_DEtype obj, out System.Exception exception)
static bool SDC.anyType_DEtype.LoadFromFile(string fileName, out anyType_DEtype obj)
References SDC.null.
static anyType_DEtype SDC.anyType_DEtype.LoadFromFile(string fileName)
static new anyType_DEtype SDC.anyType_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.anyType_DEtype.Deserialize(string input, out anyType_DEtype obj, out Exception exception)
Deserializes workflow markup into an anyType_DEtype object
input string workflow markup to deserialize obj Output anyType_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.anyType_DEtype.Deserialize, SDC.null.
static bool SDC.anyType_DEtype.Deserialize(string input, out anyType_DEtype obj)
References SDC.anyType_DEtype.Deserialize, SDC.null.
static new anyType_DEtype SDC.anyType_DEtype.Deserialize(string input)
References SDC.null, SDC.anyType_DEtype.Serializer.
static anyType_DEtype SDC.anyType_DEtype.Deserialize(Stream s)
References SDC.anyType_DEtype.Serializer.
static bool SDC.anyType_DEtype.LoadFromFile(string fileName, out anyType_DEtype obj, out Exception exception)
Deserializes xml markup from file into an anyType_DEtype object
fileName string xml file to load and deserialize obj Output anyType_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.anyType_DEtype.LoadFromFile, SDC.null.
static bool SDC.anyType_DEtype.LoadFromFile(string fileName, out anyType_DEtype obj)
References SDC.anyType_DEtype.LoadFromFile, SDC.null.
static new anyType_DEtype SDC.anyType_DEtype.LoadFromFile(string fileName)
References SDC.anyType_DEtype.Deserialize, SDC.null.