SDC::time_DEtype
bool SDC.time_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.time_DEtype.ShouldSerializemaxExclusive.
bool SDC.time_DEtype::_shouldSerializeminExclusive
Referenced by SDC.time_DEtype.ShouldSerializeminExclusive.
bool SDC.time_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.time_DEtype.ShouldSerializemaxInclusive.
bool SDC.time_DEtype::_shouldSerializeminInclusive
Referenced by SDC.time_DEtype.ShouldSerializeminInclusive.
System.Nullable<System.DateTime> SDC.time_DEtype._minInclusive
Referenced by SDC.time_DEtype.ShouldSerializeminInclusive.
System.Nullable<System.DateTime> SDC.time_DEtype._maxInclusive
Referenced by SDC.time_DEtype.ShouldSerializemaxInclusive.
System.Nullable<System.DateTime> SDC.time_DEtype._minExclusive
Referenced by SDC.time_DEtype.ShouldSerializeminExclusive.
System.Nullable<System.DateTime> SDC.time_DEtype._maxExclusive
Referenced by SDC.time_DEtype.ShouldSerializemaxExclusive.
string SDC.time_DEtype::_mask
DateTime SDC.time_DEtype._minInclusive
DateTime SDC.time_DEtype._maxInclusive
DateTime SDC.time_DEtype._minExclusive
DateTime SDC.time_DEtype._maxExclusive
ObjectChangeTracker SDC.time_DEtype.changeTrackerField
static XmlSerializer SDC.time_DEtype::serializer
System DateTime SDC.time_DEtype::minInclusive
bool SDC.time_DEtype::minInclusiveSpecified
System DateTime SDC.time_DEtype::maxInclusive
bool SDC.time_DEtype::maxInclusiveSpecified
System DateTime SDC.time_DEtype::minExclusive
bool SDC.time_DEtype::minExclusiveSpecified
System DateTime SDC.time_DEtype::maxExclusive
bool SDC.time_DEtype::maxExclusiveSpecified
string SDC.time_DEtype::mask
Referenced by SDC.time_DEtype.ShouldSerializemask.
static XmlSerializer SDC.time_DEtype::Serializer
Referenced by SDC.time_DEtype.Deserialize.
ObjectChangeTracker SDC.time_DEtype.ChangeTracker
SDC.time_DEtype.time_DEtype()
SDC.time_DEtype.time_DEtype(BaseType parentNode)
virtual bool SDC.time_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.time_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.time_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.time_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.time_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.time_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current time_DEtype object into an XML string
string XML value
virtual string SDC.time_DEtype.Serialize()
Referenced by SDC.time_DEtype.SaveToFile.
virtual bool SDC.time_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current time_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.time_DEtype.SaveToFile.
virtual bool SDC.time_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.time_DEtype.SaveToFile(string fileName)
virtual void SDC.time_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.time_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.time_DEtype._minInclusive, SDC.time_DEtype._shouldSerializeminInclusive.
virtual bool SDC.time_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.time_DEtype._maxInclusive, SDC.time_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.time_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.time_DEtype._minExclusive, SDC.time_DEtype._shouldSerializeminExclusive.
virtual bool SDC.time_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.time_DEtype._maxExclusive, SDC.time_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.time_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.time_DEtype.mask.
virtual string SDC.time_DEtype.Serialize()
Serializes current time_DEtype object into an XML string
string XML value
virtual bool SDC.time_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current time_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.time_DEtype.SaveToFile.
virtual void SDC.time_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.time_DEtype.Serialize.
virtual time_DEtype SDC.time_DEtype.Clone()
Create a clone of this time_DEtype object
static bool SDC.time_DEtype.Deserialize(string input, out time_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an time_DEtype object
input string workflow markup to deserialize obj Output time_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.time_DEtype.Deserialize, SDC.time_DEtype.LoadFromFile.
static bool SDC.time_DEtype.Deserialize(string input, out time_DEtype obj)
References SDC.null.
static new time_DEtype SDC.time_DEtype.Deserialize(string input)
References SDC.null.
static time_DEtype SDC.time_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.time_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out time_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an time_DEtype object
fileName string xml file to load and deserialize obj Output time_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.time_DEtype.LoadFromFile.
static bool SDC.time_DEtype.LoadFromFile(string fileName, out time_DEtype obj, out System.Exception exception)
static bool SDC.time_DEtype.LoadFromFile(string fileName, out time_DEtype obj)
References SDC.null.
static time_DEtype SDC.time_DEtype.LoadFromFile(string fileName)
static new time_DEtype SDC.time_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.time_DEtype.Deserialize(string input, out time_DEtype obj, out Exception exception)
Deserializes workflow markup into an time_DEtype object
input string workflow markup to deserialize obj Output time_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.time_DEtype.Deserialize, SDC.null.
static bool SDC.time_DEtype.Deserialize(string input, out time_DEtype obj)
References SDC.time_DEtype.Deserialize, SDC.null.
static new time_DEtype SDC.time_DEtype.Deserialize(string input)
References SDC.null, SDC.time_DEtype.Serializer.
static time_DEtype SDC.time_DEtype.Deserialize(Stream s)
References SDC.time_DEtype.Serializer.
static bool SDC.time_DEtype.LoadFromFile(string fileName, out time_DEtype obj, out Exception exception)
Deserializes xml markup from file into an time_DEtype object
fileName string xml file to load and deserialize obj Output time_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.time_DEtype.LoadFromFile, SDC.null.
static bool SDC.time_DEtype.LoadFromFile(string fileName, out time_DEtype obj)
References SDC.time_DEtype.LoadFromFile, SDC.null.
static new time_DEtype SDC.time_DEtype.LoadFromFile(string fileName)
References SDC.time_DEtype.Deserialize, SDC.null.