SDC::PhoneNumberType
string SDC.PhoneNumberType::_val
ObjectChangeTracker SDC.PhoneNumberType.changeTrackerField
static XmlSerializer SDC.PhoneNumberType::serializer
string SDC.PhoneNumberType::val
Referenced by SDC.PhoneNumberType.ShouldSerializeval.
static XmlSerializer SDC.PhoneNumberType::Serializer
Referenced by SDC.PhoneNumberType.Deserialize.
ObjectChangeTracker SDC.PhoneNumberType.ChangeTracker
SDC.PhoneNumberType.PhoneNumberType()
SDC.PhoneNumberType.PhoneNumberType(BaseType parentNode)
virtual bool SDC.PhoneNumberType.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.PhoneNumberType.Serialize(System.Text.Encoding encoding)
Serializes current PhoneNumberType object into an XML string
string XML value
virtual string SDC.PhoneNumberType.Serialize()
Referenced by SDC.PhoneNumberType.SaveToFile.
virtual bool SDC.PhoneNumberType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current PhoneNumberType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.PhoneNumberType.SaveToFile.
virtual bool SDC.PhoneNumberType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.PhoneNumberType.SaveToFile(string fileName)
virtual void SDC.PhoneNumberType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.PhoneNumberType.ShouldSerializeval()
Test whether val should be serialized
References SDC.PhoneNumberType.val.
virtual string SDC.PhoneNumberType.Serialize()
Serializes current PhoneNumberType object into an XML string
string XML value
virtual bool SDC.PhoneNumberType.SaveToFile(string fileName, out Exception exception)
Serializes current PhoneNumberType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.PhoneNumberType.SaveToFile.
virtual void SDC.PhoneNumberType.SaveToFile(string fileName)
References SDC.null, SDC.PhoneNumberType.Serialize.
virtual PhoneNumberType SDC.PhoneNumberType.Clone()
Create a clone of this PhoneNumberType object
static bool SDC.PhoneNumberType.Deserialize(string input, out PhoneNumberType obj, out System.Exception exception)
Deserializes workflow markup into an PhoneNumberType object
input string workflow markup to deserialize obj Output PhoneNumberType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PhoneNumberType.Deserialize, SDC.PhoneNumberType.LoadFromFile.
static bool SDC.PhoneNumberType.Deserialize(string input, out PhoneNumberType obj)
References SDC.null.
static new PhoneNumberType SDC.PhoneNumberType.Deserialize(string input)
References SDC.null.
static PhoneNumberType SDC.PhoneNumberType.Deserialize(System.IO.Stream s)
static bool SDC.PhoneNumberType.LoadFromFile(string fileName, System.Text.Encoding encoding, out PhoneNumberType obj, out System.Exception exception)
Deserializes xml markup from file into an PhoneNumberType object
fileName string xml file to load and deserialize obj Output PhoneNumberType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PhoneNumberType.LoadFromFile.
static bool SDC.PhoneNumberType.LoadFromFile(string fileName, out PhoneNumberType obj, out System.Exception exception)
static bool SDC.PhoneNumberType.LoadFromFile(string fileName, out PhoneNumberType obj)
References SDC.null.
static PhoneNumberType SDC.PhoneNumberType.LoadFromFile(string fileName)
static new PhoneNumberType SDC.PhoneNumberType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.PhoneNumberType.Deserialize(string input, out PhoneNumberType obj, out Exception exception)
Deserializes workflow markup into an PhoneNumberType object
input string workflow markup to deserialize obj Output PhoneNumberType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.PhoneNumberType.Deserialize, SDC.null.
static bool SDC.PhoneNumberType.Deserialize(string input, out PhoneNumberType obj)
References SDC.PhoneNumberType.Deserialize, SDC.null.
static new PhoneNumberType SDC.PhoneNumberType.Deserialize(string input)
References SDC.null, SDC.PhoneNumberType.Serializer.
static PhoneNumberType SDC.PhoneNumberType.Deserialize(Stream s)
References SDC.PhoneNumberType.Serializer.
static bool SDC.PhoneNumberType.LoadFromFile(string fileName, out PhoneNumberType obj, out Exception exception)
Deserializes xml markup from file into an PhoneNumberType object
fileName string xml file to load and deserialize obj Output PhoneNumberType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.PhoneNumberType.LoadFromFile, SDC.null.
static bool SDC.PhoneNumberType.LoadFromFile(string fileName, out PhoneNumberType obj)
References SDC.PhoneNumberType.LoadFromFile, SDC.null.
static new PhoneNumberType SDC.PhoneNumberType.LoadFromFile(string fileName)
References SDC.PhoneNumberType.Deserialize, SDC.null.