SDC::ApprovalType
List<ContactType> SDC.ApprovalType._approvalContact
List<string_Stype> SDC.ApprovalType._description
BindingList<ContactType> SDC.ApprovalType._approvalContact
BindingList<string_Stype> SDC.ApprovalType._description
ObjectChangeTracker SDC.ApprovalType.changeTrackerField
static XmlSerializer SDC.ApprovalType::serializer
virtual List<ContactType> SDC.ApprovalType.ApprovalContact
virtual List<string_Stype> SDC.ApprovalType.Description
Non-structured text describing file approval.
static XmlSerializer SDC.ApprovalType::Serializer
Referenced by SDC.ApprovalType.Deserialize.
virtual BindingList<ContactType> SDC.ApprovalType.ApprovalContact
virtual BindingList<string_Stype> SDC.ApprovalType.Description
Non-structured text describing file approval.
ObjectChangeTracker SDC.ApprovalType.ChangeTracker
SDC.ApprovalType.ApprovalType(BaseType parentNode)
virtual bool SDC.ApprovalType.ShouldSerializeApprovalContact()
Test whether ApprovalContact should be serialized
References SDC.null.
virtual bool SDC.ApprovalType.ShouldSerializeDescription()
Test whether Description should be serialized
References SDC.Description, SDC.null.
virtual string SDC.ApprovalType.Serialize(System.Text.Encoding encoding)
Serializes current ApprovalType object into an XML string
string XML value
virtual string SDC.ApprovalType.Serialize()
Referenced by SDC.ApprovalType.SaveToFile.
virtual bool SDC.ApprovalType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ApprovalType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ApprovalType.SaveToFile.
virtual bool SDC.ApprovalType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ApprovalType.SaveToFile(string fileName)
virtual void SDC.ApprovalType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ApprovalType.Serialize()
Serializes current ApprovalType object into an XML string
string XML value
virtual bool SDC.ApprovalType.SaveToFile(string fileName, out Exception exception)
Serializes current ApprovalType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ApprovalType.SaveToFile.
virtual void SDC.ApprovalType.SaveToFile(string fileName)
References SDC.null, SDC.ApprovalType.Serialize.
virtual ApprovalType SDC.ApprovalType.Clone()
Create a clone of this ApprovalType object
SDC.ApprovalType.ApprovalType()
static bool SDC.ApprovalType.Deserialize(string input, out ApprovalType obj, out System.Exception exception)
Deserializes workflow markup into an ApprovalType object
input string workflow markup to deserialize obj Output ApprovalType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ApprovalType.Deserialize, SDC.ApprovalType.LoadFromFile.
static bool SDC.ApprovalType.Deserialize(string input, out ApprovalType obj)
References SDC.null.
static new ApprovalType SDC.ApprovalType.Deserialize(string input)
References SDC.null.
static ApprovalType SDC.ApprovalType.Deserialize(System.IO.Stream s)
static bool SDC.ApprovalType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ApprovalType obj, out System.Exception exception)
Deserializes xml markup from file into an ApprovalType object
fileName string xml file to load and deserialize obj Output ApprovalType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ApprovalType.LoadFromFile.
static bool SDC.ApprovalType.LoadFromFile(string fileName, out ApprovalType obj, out System.Exception exception)
static bool SDC.ApprovalType.LoadFromFile(string fileName, out ApprovalType obj)
References SDC.null.
static ApprovalType SDC.ApprovalType.LoadFromFile(string fileName)
static new ApprovalType SDC.ApprovalType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ApprovalType.Deserialize(string input, out ApprovalType obj, out Exception exception)
Deserializes workflow markup into an ApprovalType object
input string workflow markup to deserialize obj Output ApprovalType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ApprovalType.Deserialize, SDC.null.
static bool SDC.ApprovalType.Deserialize(string input, out ApprovalType obj)
References SDC.ApprovalType.Deserialize, SDC.null.
static new ApprovalType SDC.ApprovalType.Deserialize(string input)
References SDC.null, SDC.ApprovalType.Serializer.
static ApprovalType SDC.ApprovalType.Deserialize(Stream s)
References SDC.ApprovalType.Serializer.
static bool SDC.ApprovalType.LoadFromFile(string fileName, out ApprovalType obj, out Exception exception)
Deserializes xml markup from file into an ApprovalType object
fileName string xml file to load and deserialize obj Output ApprovalType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ApprovalType.LoadFromFile, SDC.null.
static bool SDC.ApprovalType.LoadFromFile(string fileName, out ApprovalType obj)
References SDC.ApprovalType.LoadFromFile, SDC.null.
static new ApprovalType SDC.ApprovalType.LoadFromFile(string fileName)
References SDC.ApprovalType.Deserialize, SDC.null.