SDC::gDay_DEtype
string SDC.gDay_DEtype::_minInclusive
string SDC.gDay_DEtype::_maxInclusive
string SDC.gDay_DEtype::_minExclusive
string SDC.gDay_DEtype::_maxExclusive
string SDC.gDay_DEtype::_mask
ObjectChangeTracker SDC.gDay_DEtype.changeTrackerField
static XmlSerializer SDC.gDay_DEtype::serializer
string SDC.gDay_DEtype::minInclusive
Referenced by SDC.gDay_DEtype.ShouldSerializeminInclusive.
string SDC.gDay_DEtype::maxInclusive
Referenced by SDC.gDay_DEtype.ShouldSerializemaxInclusive.
string SDC.gDay_DEtype::minExclusive
Referenced by SDC.gDay_DEtype.ShouldSerializeminExclusive.
string SDC.gDay_DEtype::maxExclusive
Referenced by SDC.gDay_DEtype.ShouldSerializemaxExclusive.
string SDC.gDay_DEtype::mask
Referenced by SDC.gDay_DEtype.ShouldSerializemask.
static XmlSerializer SDC.gDay_DEtype::Serializer
Referenced by SDC.gDay_DEtype.Deserialize.
ObjectChangeTracker SDC.gDay_DEtype.ChangeTracker
SDC.gDay_DEtype.gDay_DEtype()
SDC.gDay_DEtype.gDay_DEtype(BaseType parentNode)
virtual bool SDC.gDay_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.gDay_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.gDay_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.gDay_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.gDay_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.gDay_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current gDay_DEtype object into an XML string
string XML value
virtual string SDC.gDay_DEtype.Serialize()
Referenced by SDC.gDay_DEtype.SaveToFile.
virtual bool SDC.gDay_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current gDay_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.gDay_DEtype.SaveToFile.
virtual bool SDC.gDay_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.gDay_DEtype.SaveToFile(string fileName)
virtual void SDC.gDay_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.gDay_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.gDay_DEtype.minInclusive.
virtual bool SDC.gDay_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.gDay_DEtype.maxInclusive.
virtual bool SDC.gDay_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.gDay_DEtype.minExclusive.
virtual bool SDC.gDay_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.gDay_DEtype.maxExclusive.
virtual bool SDC.gDay_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.gDay_DEtype.mask.
virtual string SDC.gDay_DEtype.Serialize()
Serializes current gDay_DEtype object into an XML string
string XML value
virtual bool SDC.gDay_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current gDay_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.gDay_DEtype.SaveToFile.
virtual void SDC.gDay_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.gDay_DEtype.Serialize.
virtual gDay_DEtype SDC.gDay_DEtype.Clone()
Create a clone of this gDay_DEtype object
static bool SDC.gDay_DEtype.Deserialize(string input, out gDay_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an gDay_DEtype object
input string workflow markup to deserialize obj Output gDay_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gDay_DEtype.Deserialize, SDC.gDay_DEtype.LoadFromFile.
static bool SDC.gDay_DEtype.Deserialize(string input, out gDay_DEtype obj)
References SDC.null.
static new gDay_DEtype SDC.gDay_DEtype.Deserialize(string input)
References SDC.null.
static gDay_DEtype SDC.gDay_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.gDay_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out gDay_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an gDay_DEtype object
fileName string xml file to load and deserialize obj Output gDay_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gDay_DEtype.LoadFromFile.
static bool SDC.gDay_DEtype.LoadFromFile(string fileName, out gDay_DEtype obj, out System.Exception exception)
static bool SDC.gDay_DEtype.LoadFromFile(string fileName, out gDay_DEtype obj)
References SDC.null.
static gDay_DEtype SDC.gDay_DEtype.LoadFromFile(string fileName)
static new gDay_DEtype SDC.gDay_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.gDay_DEtype.Deserialize(string input, out gDay_DEtype obj, out Exception exception)
Deserializes workflow markup into an gDay_DEtype object
input string workflow markup to deserialize obj Output gDay_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gDay_DEtype.Deserialize, SDC.null.
static bool SDC.gDay_DEtype.Deserialize(string input, out gDay_DEtype obj)
References SDC.gDay_DEtype.Deserialize, SDC.null.
static new gDay_DEtype SDC.gDay_DEtype.Deserialize(string input)
References SDC.null, SDC.gDay_DEtype.Serializer.
static gDay_DEtype SDC.gDay_DEtype.Deserialize(Stream s)
References SDC.gDay_DEtype.Serializer.
static bool SDC.gDay_DEtype.LoadFromFile(string fileName, out gDay_DEtype obj, out Exception exception)
Deserializes xml markup from file into an gDay_DEtype object
fileName string xml file to load and deserialize obj Output gDay_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gDay_DEtype.LoadFromFile, SDC.null.
static bool SDC.gDay_DEtype.LoadFromFile(string fileName, out gDay_DEtype obj)
References SDC.gDay_DEtype.LoadFromFile, SDC.null.
static new gDay_DEtype SDC.gDay_DEtype.LoadFromFile(string fileName)
References SDC.gDay_DEtype.Deserialize, SDC.null.