SDC::ReturnListBaseType
ExceptionType SDC.ReturnListBaseType._item
Referenced by SDC.ReturnListBaseType.ShouldSerializeItem.
XmlSerializer SDC.ReturnListBaseType.serializer
virtual ExceptionType SDC.ReturnListBaseType.Item
XmlSerializer SDC.ReturnListBaseType.Serializer
Referenced by SDC.ReturnListBaseType.Deserialize.
virtual bool SDC.ReturnListBaseType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.ReturnListBaseType._item, SDC.null.
virtual string SDC.ReturnListBaseType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnListBaseType object into an XML string
string XML value
virtual string SDC.ReturnListBaseType.Serialize()
Referenced by SDC.ReturnListBaseType.SaveToFile.
virtual bool SDC.ReturnListBaseType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnListBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnListBaseType.SaveToFile.
virtual bool SDC.ReturnListBaseType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnListBaseType.SaveToFile.
virtual void SDC.ReturnListBaseType.SaveToFile(string fileName)
References SDC.ReturnListBaseType.SaveToFile.
virtual void SDC.ReturnListBaseType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnListBaseType.Serialize.
static bool SDC.ReturnListBaseType.Deserialize(string input, out ReturnListBaseType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnListBaseType object
input string workflow markup to deserialize obj Output ReturnListBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnListBaseType.Deserialize, SDC.ReturnListBaseType.LoadFromFile.
static bool SDC.ReturnListBaseType.Deserialize(string input, out ReturnListBaseType obj)
References SDC.ReturnListBaseType.Deserialize, SDC.null.
static new ReturnListBaseType SDC.ReturnListBaseType.Deserialize(string input)
References SDC.null.
static ReturnListBaseType SDC.ReturnListBaseType.Deserialize(System.IO.Stream s)
References SDC.ReturnListBaseType.Serializer.
static bool SDC.ReturnListBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnListBaseType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnListBaseType object
fileName string xml file to load and deserialize obj Output ReturnListBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnListBaseType.LoadFromFile.
static bool SDC.ReturnListBaseType.LoadFromFile(string fileName, out ReturnListBaseType obj, out System.Exception exception)
References SDC.ReturnListBaseType.LoadFromFile.
static bool SDC.ReturnListBaseType.LoadFromFile(string fileName, out ReturnListBaseType obj)
References SDC.ReturnListBaseType.LoadFromFile, SDC.null.
static ReturnListBaseType SDC.ReturnListBaseType.LoadFromFile(string fileName)
References SDC.ReturnListBaseType.LoadFromFile.
static new ReturnListBaseType SDC.ReturnListBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnListBaseType.Deserialize, SDC.null.