SDC::SetPropertyType
bool SDC.SetPropertyType._shouldSerializeonlyIf
Referenced by SDC.SetPropertyType.ShouldSerializeonlyIf.
bool SDC.SetPropertyType._shouldSerializeactReadOnly
Referenced by SDC.SetPropertyType.ShouldSerializeactReadOnly.
bool SDC.SetPropertyType._shouldSerializeactDeleteResponse
Referenced by SDC.SetPropertyType.ShouldSerializeactDeleteResponse.
bool SDC.SetPropertyType._shouldSerializeactSelect
Referenced by SDC.SetPropertyType.ShouldSerializeactSelect.
bool SDC.SetPropertyType._shouldSerializeactActivate
Referenced by SDC.SetPropertyType.ShouldSerializeactActivate.
bool SDC.SetPropertyType._shouldSerializeactEnable
Referenced by SDC.SetPropertyType.ShouldSerializeactEnable.
bool SDC.SetPropertyType._shouldSerializeactVisible
Referenced by SDC.SetPropertyType.ShouldSerializeactVisible.
bool SDC.SetPropertyType._actVisible
Referenced by SDC.SetPropertyType.ShouldSerializeactVisible.
bool SDC.SetPropertyType._actEnable
Referenced by SDC.SetPropertyType.ShouldSerializeactEnable.
string SDC.SetPropertyType._actMinCard
string SDC.SetPropertyType._actMaxCard
bool SDC.SetPropertyType._actActivate
Referenced by SDC.SetPropertyType.ShouldSerializeactActivate.
bool SDC.SetPropertyType._actSelect
Referenced by SDC.SetPropertyType.ShouldSerializeactSelect.
bool SDC.SetPropertyType._actDeleteResponse
Referenced by SDC.SetPropertyType.ShouldSerializeactDeleteResponse.
bool SDC.SetPropertyType._actReadOnly
Referenced by SDC.SetPropertyType.ShouldSerializeactReadOnly.
string SDC.SetPropertyType._actType
string SDC.SetPropertyType._actStyleClass
string SDC.SetPropertyType._actSetTitleText
string SDC.SetPropertyType._actSetCode
string SDC.SetPropertyType._targetNames
bool SDC.SetPropertyType._onlyIf
Referenced by SDC.SetPropertyType.ShouldSerializeonlyIf.
ObjectChangeTracker SDC.SetPropertyType.changeTrackerField
XmlSerializer SDC.SetPropertyType.serializer
virtual bool SDC.SetPropertyType.actVisible
virtual bool SDC.SetPropertyType.actVisibleSpecified
virtual bool SDC.SetPropertyType.actEnable
virtual bool SDC.SetPropertyType.actEnableSpecified
virtual string SDC.SetPropertyType.actMinCard
Controls requirement to answer the question and the minimum number of repeats.
Referenced by SDC.SetPropertyType.ShouldSerializeactMinCard.
virtual string SDC.SetPropertyType.actMaxCard
Controls requirement to answer the question
Referenced by SDC.SetPropertyType.ShouldSerializeactMaxCard.
virtual bool SDC.SetPropertyType.actActivate
Toggle visible and enabled together. Setting this to false will de-activate all descendents but will not change their enabled or visible properties.
virtual bool SDC.SetPropertyType.actActivateSpecified
virtual bool SDC.SetPropertyType.actSelect
Toggle selection of a List Item; not applicable to other items.
virtual bool SDC.SetPropertyType.actSelectSpecified
virtual bool SDC.SetPropertyType.actDeleteResponse
Delete any response in a Response field on a question or ListItem. Not applicable to other item types.
virtual bool SDC.SetPropertyType.actDeleteResponseSpecified
virtual bool SDC.SetPropertyType.actReadOnly
Delete any response in a Response field on a question or ListItem. Not applicable to other item types.
virtual bool SDC.SetPropertyType.actReadOnlySpecified
virtual string SDC.SetPropertyType.actType
Set the attribute value
Referenced by SDC.SetPropertyType.ShouldSerializeactType.
virtual string SDC.SetPropertyType.actStyleClass
Set the attribute value
Referenced by SDC.SetPropertyType.ShouldSerializeactStyleClass.
virtual string SDC.SetPropertyType.actSetTitleText
Referenced by SDC.SetPropertyType.ShouldSerializeactSetTitleText.
virtual string SDC.SetPropertyType.actSetCode
Referenced by SDC.SetPropertyType.ShouldSerializeactSetCode.
virtual string SDC.SetPropertyType.targetNames
The names of the items affected by property actions
Referenced by SDC.SetPropertyType.ShouldSerializetargetNames.
virtual bool SDC.SetPropertyType.onlyIf
virtual bool SDC.SetPropertyType.onlyIfSpecified
XmlSerializer SDC.SetPropertyType.Serializer
Referenced by SDC.SetPropertyType.Deserialize.
ObjectChangeTracker SDC.SetPropertyType.ChangeTracker
SDC.SetPropertyType.SetPropertyType()
virtual bool SDC.SetPropertyType.ShouldSerializeactVisible()
Test whether actVisible should be serialized
References SDC.SetPropertyType._actVisible, SDC.SetPropertyType._shouldSerializeactVisible.
virtual bool SDC.SetPropertyType.ShouldSerializeactEnable()
Test whether actEnable should be serialized
References SDC.SetPropertyType._actEnable, SDC.SetPropertyType._shouldSerializeactEnable.
virtual bool SDC.SetPropertyType.ShouldSerializeactActivate()
Test whether actActivate should be serialized
References SDC.SetPropertyType._actActivate, SDC.SetPropertyType._shouldSerializeactActivate.
virtual bool SDC.SetPropertyType.ShouldSerializeactSelect()
Test whether actSelect should be serialized
References SDC.SetPropertyType._actSelect, SDC.SetPropertyType._shouldSerializeactSelect.
virtual bool SDC.SetPropertyType.ShouldSerializeactDeleteResponse()
Test whether actDeleteResponse should be serialized
References SDC.SetPropertyType._actDeleteResponse, SDC.SetPropertyType._shouldSerializeactDeleteResponse.
virtual bool SDC.SetPropertyType.ShouldSerializeactReadOnly()
Test whether actReadOnly should be serialized
References SDC.SetPropertyType._actReadOnly, SDC.SetPropertyType._shouldSerializeactReadOnly.
virtual bool SDC.SetPropertyType.ShouldSerializeonlyIf()
Test whether onlyIf should be serialized
References SDC.SetPropertyType._onlyIf, SDC.SetPropertyType._shouldSerializeonlyIf.
virtual bool SDC.SetPropertyType.ShouldSerializeactMinCard()
Test whether actMinCard should be serialized
References SDC.SetPropertyType.actMinCard.
virtual bool SDC.SetPropertyType.ShouldSerializeactMaxCard()
Test whether actMaxCard should be serialized
References SDC.SetPropertyType.actMaxCard.
virtual bool SDC.SetPropertyType.ShouldSerializeactType()
Test whether actType should be serialized
References SDC.SetPropertyType.actType.
virtual bool SDC.SetPropertyType.ShouldSerializeactStyleClass()
Test whether actStyleClass should be serialized
References SDC.SetPropertyType.actStyleClass.
virtual bool SDC.SetPropertyType.ShouldSerializeactSetTitleText()
Test whether actSetTitleText should be serialized
References SDC.SetPropertyType.actSetTitleText.
virtual bool SDC.SetPropertyType.ShouldSerializeactSetCode()
Test whether actSetCode should be serialized
References SDC.SetPropertyType.actSetCode.
virtual bool SDC.SetPropertyType.ShouldSerializetargetNames()
Test whether targetNames should be serialized
References SDC.SetPropertyType.targetNames.
virtual string SDC.SetPropertyType.Serialize()
Serializes current SetPropertyType object into an XML string
string XML value
Referenced by SDC.SetPropertyType.SaveToFile.
virtual bool SDC.SetPropertyType.SaveToFile(string fileName, out Exception exception)
Serializes current SetPropertyType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.SetPropertyType.SaveToFile(string fileName)
References SDC.null, SDC.SetPropertyType.Serialize.
virtual SetPropertyType SDC.SetPropertyType.Clone()
Create a clone of this SetPropertyType object
static bool SDC.SetPropertyType.Deserialize(string input, out SetPropertyType obj, out Exception exception)
Deserializes workflow markup into an SetPropertyType object
input string workflow markup to deserialize obj Output SetPropertyType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.SetPropertyType.Deserialize, SDC.SetPropertyType.LoadFromFile.
static bool SDC.SetPropertyType.Deserialize(string input, out SetPropertyType obj)
References SDC.SetPropertyType.Deserialize, SDC.null.
static new SetPropertyType SDC.SetPropertyType.Deserialize(string input)
References SDC.null, SDC.SetPropertyType.Serializer.
static SetPropertyType SDC.SetPropertyType.Deserialize(Stream s)
References SDC.SetPropertyType.Serializer.
static bool SDC.SetPropertyType.LoadFromFile(string fileName, out SetPropertyType obj, out Exception exception)
Deserializes xml markup from file into an SetPropertyType object
fileName string xml file to load and deserialize obj Output SetPropertyType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.SetPropertyType.LoadFromFile.
static bool SDC.SetPropertyType.LoadFromFile(string fileName, out SetPropertyType obj)
References SDC.SetPropertyType.LoadFromFile, SDC.null.
static new SetPropertyType SDC.SetPropertyType.LoadFromFile(string fileName)
References SDC.SetPropertyType.Deserialize, SDC.null.