SDC::CodingType
string_Stype SDC.CodingType::_code
Referenced by SDC.CodingType.ShouldSerializeCode.
RichTextType SDC.CodingType::_codeText
Referenced by SDC.CodingType.ShouldSerializeCodeText.
CodeMatchType SDC.CodingType::_codeMatch
Referenced by SDC.CodingType.ShouldSerializeCodeMatch.
CodeSystemType SDC.CodingType::_codeSystem
Referenced by SDC.CodingType.ShouldSerializeCodeSystem.
anyURI_Stype SDC.CodingType._codeURI
DataTypes_SType SDC.CodingType::_dataType
Referenced by SDC.CodingType.ShouldSerializeDataType.
UnitsType SDC.CodingType::_units
Referenced by SDC.CodingType.ShouldSerializeUnits.
ObjectChangeTracker SDC.CodingType.changeTrackerField
static XmlSerializer SDC.CodingType::serializer
string_Stype SDC.CodingType::Code
A standard code, or a local value from a custom coding system, that can be used to consistently identify, or provide a standard value for, the coded item.
RichTextType SDC.CodingType::CodeText
The human readable text that accompanies the assigned code and represents the code's precise meaning (semantics) or usage.
CodeMatchType SDC.CodingType::CodeMatch
Degree of match between the mapped item and the assigned code - holds an entry from an enumerated list of match types.
CodeSystemType SDC.CodingType::CodeSystem
virtual anyURI_Stype SDC.CodingType.CodeURI
NEW: Web resource that provides information about the code
DataTypes_SType SDC.CodingType::DataType
Data type enumeration derived from W3C XML Schema. If the code is derived from a local value system (e.g., numbered answer choices such as clock positions, tumor grades, or clinical scoring systems), then the data type of the local value may be specified here. This may be important if the code value will need to me manipulated mathematically.
UnitsType SDC.CodingType::Units
static XmlSerializer SDC.CodingType::Serializer
Referenced by SDC.CodingType.Deserialize.
ObjectChangeTracker SDC.CodingType.ChangeTracker
SDC.CodingType.CodingType()
SDC.CodingType.CodingType(BaseType parentNode, bool fillData=true)
virtual bool SDC.CodingType.ShouldSerializeCode()
Test whether Code should be serialized
References SDC.null.
virtual bool SDC.CodingType.ShouldSerializeCodeText()
Test whether CodeText should be serialized
References SDC.null.
virtual bool SDC.CodingType.ShouldSerializeCodeMatch()
Test whether CodeMatch should be serialized
References SDC.null.
virtual bool SDC.CodingType.ShouldSerializeCodeSystem()
Test whether CodeSystem should be serialized
References SDC.null.
virtual bool SDC.CodingType.ShouldSerializeCodeURI()
Test whether CodeURI should be serialized
References SDC.null.
virtual bool SDC.CodingType.ShouldSerializeDataType()
Test whether DataType should be serialized
References SDC.null.
virtual bool SDC.CodingType.ShouldSerializeUnits()
Test whether Units should be serialized
References SDC.null.
virtual string SDC.CodingType.Serialize(System.Text.Encoding encoding)
Serializes current CodingType object into an XML string
string XML value
virtual string SDC.CodingType.Serialize()
Referenced by SDC.CodingType.SaveToFile.
virtual bool SDC.CodingType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current CodingType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.CodingType.SaveToFile.
virtual bool SDC.CodingType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.CodingType.SaveToFile(string fileName)
virtual void SDC.CodingType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.CodingType.ShouldSerializeCode()
Test whether Code should be serialized
References SDC.CodingType._code, SDC.null.
virtual bool SDC.CodingType.ShouldSerializeCodeText()
Test whether CodeText should be serialized
References SDC.CodingType._codeText, SDC.null.
virtual bool SDC.CodingType.ShouldSerializeCodeMatch()
Test whether CodeMatch should be serialized
References SDC.CodingType._codeMatch, SDC.null.
virtual bool SDC.CodingType.ShouldSerializeCodeSystem()
Test whether CodeSystem should be serialized
References SDC.CodingType._codeSystem, SDC.null.
virtual bool SDC.CodingType.ShouldSerializeDataType()
Test whether DataType should be serialized
References SDC.CodingType._dataType, SDC.null.
virtual bool SDC.CodingType.ShouldSerializeUnits()
Test whether Units should be serialized
References SDC.CodingType._units, SDC.null.
virtual string SDC.CodingType.Serialize()
Serializes current CodingType object into an XML string
string XML value
virtual bool SDC.CodingType.SaveToFile(string fileName, out Exception exception)
Serializes current CodingType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.CodingType.SaveToFile.
virtual void SDC.CodingType.SaveToFile(string fileName)
References SDC.null, SDC.CodingType.Serialize.
virtual CodingType SDC.CodingType.Clone()
Create a clone of this CodingType object
static bool SDC.CodingType.Deserialize(string input, out CodingType obj, out System.Exception exception)
Deserializes workflow markup into an CodingType object
input string workflow markup to deserialize obj Output CodingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CodingType.Deserialize, SDC.CodingType.LoadFromFile.
static bool SDC.CodingType.Deserialize(string input, out CodingType obj)
References SDC.null.
static new CodingType SDC.CodingType.Deserialize(string input)
References SDC.null.
static CodingType SDC.CodingType.Deserialize(System.IO.Stream s)
static bool SDC.CodingType.LoadFromFile(string fileName, System.Text.Encoding encoding, out CodingType obj, out System.Exception exception)
Deserializes xml markup from file into an CodingType object
fileName string xml file to load and deserialize obj Output CodingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CodingType.LoadFromFile.
static bool SDC.CodingType.LoadFromFile(string fileName, out CodingType obj, out System.Exception exception)
static bool SDC.CodingType.LoadFromFile(string fileName, out CodingType obj)
References SDC.null.
static CodingType SDC.CodingType.LoadFromFile(string fileName)
static new CodingType SDC.CodingType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.CodingType.Deserialize(string input, out CodingType obj, out Exception exception)
Deserializes workflow markup into an CodingType object
input string workflow markup to deserialize obj Output CodingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CodingType.Deserialize, SDC.null.
static bool SDC.CodingType.Deserialize(string input, out CodingType obj)
References SDC.CodingType.Deserialize, SDC.null.
static new CodingType SDC.CodingType.Deserialize(string input)
References SDC.null, SDC.CodingType.Serializer.
static CodingType SDC.CodingType.Deserialize(Stream s)
References SDC.CodingType.Serializer.
static bool SDC.CodingType.LoadFromFile(string fileName, out CodingType obj, out Exception exception)
Deserializes xml markup from file into an CodingType object
fileName string xml file to load and deserialize obj Output CodingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CodingType.LoadFromFile, SDC.null.
static bool SDC.CodingType.LoadFromFile(string fileName, out CodingType obj)
References SDC.CodingType.LoadFromFile, SDC.null.
static new CodingType SDC.CodingType.LoadFromFile(string fileName)
References SDC.CodingType.Deserialize, SDC.null.