SDC::TargetItemNameType
string SDC.TargetItemNameType::_val
string SDC.TargetItemNameType::_targetItemText
string SDC.TargetItemNameType::_targetProperty
ObjectChangeTracker SDC.TargetItemNameType.changeTrackerField
static XmlSerializer SDC.TargetItemNameType::serializer
string SDC.TargetItemNameType::val
Referenced by SDC.TargetItemNameType.ShouldSerializeval.
string SDC.TargetItemNameType::targetItemText
Displayed text on the targetted item.
Referenced by SDC.TargetItemNameType.ShouldSerializetargetItemText.
string SDC.TargetItemNameType::targetProperty
Referenced by SDC.TargetItemNameType.ShouldSerializetargetProperty.
static XmlSerializer SDC.TargetItemNameType::Serializer
Referenced by SDC.TargetItemNameType.Deserialize.
ObjectChangeTracker SDC.TargetItemNameType.ChangeTracker
SDC.TargetItemNameType.TargetItemNameType()
SDC.TargetItemNameType.TargetItemNameType(BaseType parentNode)
virtual bool SDC.TargetItemNameType.ShouldSerializeval()
Test whether val should be serialized
virtual bool SDC.TargetItemNameType.ShouldSerializetargetItemText()
Test whether targetItemText should be serialized
virtual bool SDC.TargetItemNameType.ShouldSerializetargetProperty()
Test whether targetProperty should be serialized
virtual string SDC.TargetItemNameType.Serialize(System.Text.Encoding encoding)
Serializes current TargetItemNameType object into an XML string
string XML value
virtual string SDC.TargetItemNameType.Serialize()
Referenced by SDC.TargetItemNameType.SaveToFile.
virtual bool SDC.TargetItemNameType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current TargetItemNameType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.TargetItemNameType.SaveToFile.
virtual bool SDC.TargetItemNameType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.TargetItemNameType.SaveToFile(string fileName)
virtual void SDC.TargetItemNameType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.TargetItemNameType.ShouldSerializeval()
Test whether val should be serialized
References SDC.TargetItemNameType.val.
virtual bool SDC.TargetItemNameType.ShouldSerializetargetItemText()
Test whether targetItemText should be serialized
References SDC.TargetItemNameType.targetItemText.
virtual bool SDC.TargetItemNameType.ShouldSerializetargetProperty()
Test whether targetProperty should be serialized
References SDC.TargetItemNameType.targetProperty.
virtual string SDC.TargetItemNameType.Serialize()
Serializes current TargetItemNameType object into an XML string
string XML value
virtual bool SDC.TargetItemNameType.SaveToFile(string fileName, out Exception exception)
Serializes current TargetItemNameType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.TargetItemNameType.SaveToFile.
virtual void SDC.TargetItemNameType.SaveToFile(string fileName)
References SDC.null, SDC.TargetItemNameType.Serialize.
virtual TargetItemNameType SDC.TargetItemNameType.Clone()
Create a clone of this TargetItemNameType object
static bool SDC.TargetItemNameType.Deserialize(string input, out TargetItemNameType obj, out System.Exception exception)
Deserializes workflow markup into an TargetItemNameType object
input string workflow markup to deserialize obj Output TargetItemNameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.TargetItemNameType.Deserialize, SDC.TargetItemNameType.LoadFromFile.
static bool SDC.TargetItemNameType.Deserialize(string input, out TargetItemNameType obj)
References SDC.null.
static new TargetItemNameType SDC.TargetItemNameType.Deserialize(string input)
References SDC.null.
static TargetItemNameType SDC.TargetItemNameType.Deserialize(System.IO.Stream s)
static bool SDC.TargetItemNameType.LoadFromFile(string fileName, System.Text.Encoding encoding, out TargetItemNameType obj, out System.Exception exception)
Deserializes xml markup from file into an TargetItemNameType object
fileName string xml file to load and deserialize obj Output TargetItemNameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.TargetItemNameType.LoadFromFile.
static bool SDC.TargetItemNameType.LoadFromFile(string fileName, out TargetItemNameType obj, out System.Exception exception)
static bool SDC.TargetItemNameType.LoadFromFile(string fileName, out TargetItemNameType obj)
References SDC.null.
static TargetItemNameType SDC.TargetItemNameType.LoadFromFile(string fileName)
static new TargetItemNameType SDC.TargetItemNameType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.TargetItemNameType.Deserialize(string input, out TargetItemNameType obj, out Exception exception)
Deserializes workflow markup into an TargetItemNameType object
input string workflow markup to deserialize obj Output TargetItemNameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.TargetItemNameType.Deserialize, SDC.null.
static bool SDC.TargetItemNameType.Deserialize(string input, out TargetItemNameType obj)
References SDC.TargetItemNameType.Deserialize, SDC.null.
static new TargetItemNameType SDC.TargetItemNameType.Deserialize(string input)
References SDC.null, SDC.TargetItemNameType.Serializer.
static TargetItemNameType SDC.TargetItemNameType.Deserialize(Stream s)
References SDC.TargetItemNameType.Serializer.
static bool SDC.TargetItemNameType.LoadFromFile(string fileName, out TargetItemNameType obj, out Exception exception)
Deserializes xml markup from file into an TargetItemNameType object
fileName string xml file to load and deserialize obj Output TargetItemNameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.TargetItemNameType.LoadFromFile, SDC.null.
static bool SDC.TargetItemNameType.LoadFromFile(string fileName, out TargetItemNameType obj)
References SDC.TargetItemNameType.LoadFromFile, SDC.null.
static new TargetItemNameType SDC.TargetItemNameType.LoadFromFile(string fileName)
References SDC.TargetItemNameType.Deserialize, SDC.null.