SDC::VersionType
FileType SDC.VersionType::_versioningReference
Referenced by SDC.VersionType.ShouldSerializeVersioningReference.
RichTextType SDC.VersionType::_versionComments
Referenced by SDC.VersionType.ShouldSerializeVersionComments.
VersionTypeChanges SDC.VersionType::_changes
Referenced by SDC.VersionType.ShouldSerializeChanges.
string SDC.VersionType::_fullVersion
string SDC.VersionType::_versionRegExPattern
string SDC.VersionType::_versionLevel1
string SDC.VersionType::_versionLevel2
string SDC.VersionType::_versionLevel3
string SDC.VersionType::_versionLevel4
string SDC.VersionType::_versionLevel5
ObjectChangeTracker SDC.VersionType.changeTrackerField
static XmlSerializer SDC.VersionType::serializer
FileType SDC.VersionType::VersioningReference
Information about the document that describes the versioning methodology nomenclature.
RichTextType SDC.VersionType::VersionComments
Comments about the changes in this version
VersionTypeChanges SDC.VersionType::Changes
Itemized list of changes in the new version
string SDC.VersionType::fullVersion
Referenced by SDC.VersionType.ShouldSerializefullVersion.
string SDC.VersionType::versionRegExPattern
Referenced by SDC.VersionType.ShouldSerializeversionRegExPattern.
string SDC.VersionType::versionLevel1
Referenced by SDC.VersionType.ShouldSerializeversionLevel1.
string SDC.VersionType::versionLevel2
Referenced by SDC.VersionType.ShouldSerializeversionLevel2.
string SDC.VersionType::versionLevel3
Referenced by SDC.VersionType.ShouldSerializeversionLevel3.
string SDC.VersionType::versionLevel4
Referenced by SDC.VersionType.ShouldSerializeversionLevel4.
string SDC.VersionType::versionLevel5
Referenced by SDC.VersionType.ShouldSerializeversionLevel5.
static XmlSerializer SDC.VersionType::Serializer
Referenced by SDC.VersionType.Deserialize.
ObjectChangeTracker SDC.VersionType.ChangeTracker
SDC.VersionType.VersionType()
SDC.VersionType.VersionType(BaseType parentNode)
virtual bool SDC.VersionType.ShouldSerializeVersioningReference()
Test whether VersioningReference should be serialized
References SDC.null.
virtual bool SDC.VersionType.ShouldSerializeVersionComments()
Test whether VersionComments should be serialized
References SDC.null.
virtual bool SDC.VersionType.ShouldSerializeChanges()
Test whether Changes should be serialized
References SDC.null.
virtual bool SDC.VersionType.ShouldSerializefullVersion()
Test whether fullVersion should be serialized
virtual bool SDC.VersionType.ShouldSerializeversionRegExPattern()
Test whether versionRegExPattern should be serialized
virtual bool SDC.VersionType.ShouldSerializeversionLevel1()
Test whether versionLevel1 should be serialized
virtual bool SDC.VersionType.ShouldSerializeversionLevel2()
Test whether versionLevel2 should be serialized
virtual bool SDC.VersionType.ShouldSerializeversionLevel3()
Test whether versionLevel3 should be serialized
virtual bool SDC.VersionType.ShouldSerializeversionLevel4()
Test whether versionLevel4 should be serialized
virtual bool SDC.VersionType.ShouldSerializeversionLevel5()
Test whether versionLevel5 should be serialized
virtual string SDC.VersionType.Serialize(System.Text.Encoding encoding)
Serializes current VersionType object into an XML string
string XML value
virtual string SDC.VersionType.Serialize()
Referenced by SDC.VersionType.SaveToFile.
virtual bool SDC.VersionType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current VersionType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.VersionType.SaveToFile.
virtual bool SDC.VersionType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.VersionType.SaveToFile(string fileName)
virtual void SDC.VersionType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.VersionType.ShouldSerializeVersioningReference()
Test whether VersioningReference should be serialized
References SDC.VersionType._versioningReference, SDC.null.
virtual bool SDC.VersionType.ShouldSerializeVersionComments()
Test whether VersionComments should be serialized
References SDC.VersionType._versionComments, SDC.null.
virtual bool SDC.VersionType.ShouldSerializeChanges()
Test whether Changes should be serialized
References SDC.VersionType._changes, SDC.null.
virtual bool SDC.VersionType.ShouldSerializefullVersion()
Test whether fullVersion should be serialized
References SDC.VersionType.fullVersion.
virtual bool SDC.VersionType.ShouldSerializeversionRegExPattern()
Test whether versionRegExPattern should be serialized
References SDC.VersionType.versionRegExPattern.
virtual bool SDC.VersionType.ShouldSerializeversionLevel1()
Test whether versionLevel1 should be serialized
References SDC.VersionType.versionLevel1.
virtual bool SDC.VersionType.ShouldSerializeversionLevel2()
Test whether versionLevel2 should be serialized
References SDC.VersionType.versionLevel2.
virtual bool SDC.VersionType.ShouldSerializeversionLevel3()
Test whether versionLevel3 should be serialized
References SDC.VersionType.versionLevel3.
virtual bool SDC.VersionType.ShouldSerializeversionLevel4()
Test whether versionLevel4 should be serialized
References SDC.VersionType.versionLevel4.
virtual bool SDC.VersionType.ShouldSerializeversionLevel5()
Test whether versionLevel5 should be serialized
References SDC.VersionType.versionLevel5.
virtual string SDC.VersionType.Serialize()
Serializes current VersionType object into an XML string
string XML value
virtual bool SDC.VersionType.SaveToFile(string fileName, out Exception exception)
Serializes current VersionType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.VersionType.SaveToFile.
virtual void SDC.VersionType.SaveToFile(string fileName)
References SDC.null, SDC.VersionType.Serialize.
virtual VersionType SDC.VersionType.Clone()
Create a clone of this VersionType object
static bool SDC.VersionType.Deserialize(string input, out VersionType obj, out System.Exception exception)
Deserializes workflow markup into an VersionType object
input string workflow markup to deserialize obj Output VersionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.VersionType.Deserialize, SDC.VersionType.LoadFromFile.
static bool SDC.VersionType.Deserialize(string input, out VersionType obj)
References SDC.null.
static new VersionType SDC.VersionType.Deserialize(string input)
References SDC.null.
static VersionType SDC.VersionType.Deserialize(System.IO.Stream s)
static bool SDC.VersionType.LoadFromFile(string fileName, System.Text.Encoding encoding, out VersionType obj, out System.Exception exception)
Deserializes xml markup from file into an VersionType object
fileName string xml file to load and deserialize obj Output VersionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.VersionType.LoadFromFile.
static bool SDC.VersionType.LoadFromFile(string fileName, out VersionType obj, out System.Exception exception)
static bool SDC.VersionType.LoadFromFile(string fileName, out VersionType obj)
References SDC.null.
static VersionType SDC.VersionType.LoadFromFile(string fileName)
static new VersionType SDC.VersionType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.VersionType.Deserialize(string input, out VersionType obj, out Exception exception)
Deserializes workflow markup into an VersionType object
input string workflow markup to deserialize obj Output VersionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.VersionType.Deserialize, SDC.null.
static bool SDC.VersionType.Deserialize(string input, out VersionType obj)
References SDC.VersionType.Deserialize, SDC.null.
static new VersionType SDC.VersionType.Deserialize(string input)
References SDC.null, SDC.VersionType.Serializer.
static VersionType SDC.VersionType.Deserialize(Stream s)
References SDC.VersionType.Serializer.
static bool SDC.VersionType.LoadFromFile(string fileName, out VersionType obj, out Exception exception)
Deserializes xml markup from file into an VersionType object
fileName string xml file to load and deserialize obj Output VersionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.VersionType.LoadFromFile, SDC.null.
static bool SDC.VersionType.LoadFromFile(string fileName, out VersionType obj)
References SDC.VersionType.LoadFromFile, SDC.null.
static new VersionType SDC.VersionType.LoadFromFile(string fileName)
References SDC.VersionType.Deserialize, SDC.null.