SDC::ExpressionType
virtual List<BaseType> SDC.ExpressionType.Ref_Script_WebSvc_List
Replaces Items List<BaseType>: Reference, ScriptCode, WebService
virtual BindingList<BaseType> SDC.ExpressionType.Items
XmlSerializer SDC.ExpressionType.Serializer
Referenced by SDC.ExpressionType.Deserialize.
ObjectChangeTracker SDC.ExpressionType.ChangeTracker
BindingList<BaseType> SDC.ExpressionType._items
ObjectChangeTracker SDC.ExpressionType.changeTrackerField
XmlSerializer SDC.ExpressionType.serializer
SDC.ExpressionType.ExpressionType()
virtual string SDC.ExpressionType.Serialize()
Serializes current ExpressionType object into an XML string
string XML value
Referenced by SDC.ExpressionType.SaveToFile.
virtual bool SDC.ExpressionType.SaveToFile(string fileName, out Exception exception)
Serializes current ExpressionType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.ExpressionType.SaveToFile(string fileName)
References SDC.null, SDC.ExpressionType.Serialize.
virtual ExpressionType SDC.ExpressionType.Clone()
Create a clone of this ExpressionType object
static bool SDC.ExpressionType.Deserialize(string input, out ExpressionType obj, out Exception exception)
Deserializes workflow markup into an ExpressionType object
input string workflow markup to deserialize obj Output ExpressionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ExpressionType.Deserialize, SDC.ExpressionType.LoadFromFile.
static bool SDC.ExpressionType.Deserialize(string input, out ExpressionType obj)
References SDC.ExpressionType.Deserialize, SDC.null.
static new ExpressionType SDC.ExpressionType.Deserialize(string input)
References SDC.null, SDC.ExpressionType.Serializer.
static ExpressionType SDC.ExpressionType.Deserialize(Stream s)
References SDC.ExpressionType.Serializer.
static bool SDC.ExpressionType.LoadFromFile(string fileName, out ExpressionType obj, out Exception exception)
Deserializes xml markup from file into an ExpressionType object
fileName string xml file to load and deserialize obj Output ExpressionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ExpressionType.LoadFromFile.
static bool SDC.ExpressionType.LoadFromFile(string fileName, out ExpressionType obj)
References SDC.ExpressionType.LoadFromFile, SDC.null.
static new ExpressionType SDC.ExpressionType.LoadFromFile(string fileName)
References SDC.ExpressionType.Deserialize, SDC.null.