SDC::ActInjectType
string SDC.ActInjectType::_targetNames
ObjectChangeTracker SDC.ActInjectType.changeTrackerField
static XmlSerializer SDC.ActInjectType::serializer
string SDC.ActInjectType::targetNames
The names of the parent items that will have the form (or form section) injected as child node(s).
Referenced by SDC.ActInjectType.ShouldSerializetargetNames.
static XmlSerializer SDC.ActInjectType::Serializer
Referenced by SDC.ActInjectType.Deserialize.
ObjectChangeTracker SDC.ActInjectType.ChangeTracker
SDC.ActInjectType.ActInjectType()
SDC.ActInjectType.ActInjectType(ThenType parentNode)
virtual bool SDC.ActInjectType.ShouldSerializetargetNames()
Test whether targetNames should be serialized
virtual string SDC.ActInjectType.Serialize(System.Text.Encoding encoding)
Serializes current ActInjectType object into an XML string
string XML value
virtual string SDC.ActInjectType.Serialize()
Referenced by SDC.ActInjectType.SaveToFile.
virtual bool SDC.ActInjectType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ActInjectType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ActInjectType.SaveToFile.
virtual bool SDC.ActInjectType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ActInjectType.SaveToFile(string fileName)
virtual void SDC.ActInjectType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ActInjectType.ShouldSerializetargetNames()
Test whether targetNames should be serialized
References SDC.ActInjectType.targetNames.
virtual string SDC.ActInjectType.Serialize()
Serializes current ActInjectType object into an XML string
string XML value
virtual bool SDC.ActInjectType.SaveToFile(string fileName, out Exception exception)
Serializes current ActInjectType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ActInjectType.SaveToFile.
virtual void SDC.ActInjectType.SaveToFile(string fileName)
References SDC.null, SDC.ActInjectType.Serialize.
virtual ActInjectType SDC.ActInjectType.Clone()
Create a clone of this ActInjectType object
static bool SDC.ActInjectType.Deserialize(string input, out ActInjectType obj, out System.Exception exception)
Deserializes workflow markup into an ActInjectType object
input string workflow markup to deserialize obj Output ActInjectType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActInjectType.Deserialize, SDC.ActInjectType.LoadFromFile.
static bool SDC.ActInjectType.Deserialize(string input, out ActInjectType obj)
References SDC.null.
static new ActInjectType SDC.ActInjectType.Deserialize(string input)
References SDC.null.
static ActInjectType SDC.ActInjectType.Deserialize(System.IO.Stream s)
static bool SDC.ActInjectType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ActInjectType obj, out System.Exception exception)
Deserializes xml markup from file into an ActInjectType object
fileName string xml file to load and deserialize obj Output ActInjectType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActInjectType.LoadFromFile.
static bool SDC.ActInjectType.LoadFromFile(string fileName, out ActInjectType obj, out System.Exception exception)
static bool SDC.ActInjectType.LoadFromFile(string fileName, out ActInjectType obj)
References SDC.null.
static ActInjectType SDC.ActInjectType.LoadFromFile(string fileName)
static new ActInjectType SDC.ActInjectType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ActInjectType.Deserialize(string input, out ActInjectType obj, out Exception exception)
Deserializes workflow markup into an ActInjectType object
input string workflow markup to deserialize obj Output ActInjectType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActInjectType.Deserialize, SDC.null.
static bool SDC.ActInjectType.Deserialize(string input, out ActInjectType obj)
References SDC.ActInjectType.Deserialize, SDC.null.
static new ActInjectType SDC.ActInjectType.Deserialize(string input)
References SDC.null, SDC.ActInjectType.Serializer.
static ActInjectType SDC.ActInjectType.Deserialize(Stream s)
References SDC.ActInjectType.Serializer.
static bool SDC.ActInjectType.LoadFromFile(string fileName, out ActInjectType obj, out Exception exception)
Deserializes xml markup from file into an ActInjectType object
fileName string xml file to load and deserialize obj Output ActInjectType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActInjectType.LoadFromFile, SDC.null.
static bool SDC.ActInjectType.LoadFromFile(string fileName, out ActInjectType obj)
References SDC.ActInjectType.LoadFromFile, SDC.null.
static new ActInjectType SDC.ActInjectType.LoadFromFile(string fileName)
References SDC.ActInjectType.Deserialize, SDC.null.