SDC::DataTypes_DEType
BaseType SDC.DataTypes_DEType::DataTypeDE_Item
any *_DEType data type
Referenced by SDC.SDCTreeBuilderEcc.AddFillDataTypesDE.
BaseType SDC.DataTypes_DEType::Item
Referenced by SDC.SDCTreeBuilderEcc.AddDataTypesDE, SDC.SDCTreeBuilder.AddDataTypesDE.
ItemChoiceType SDC.DataTypes_DEType::ItemElementName
static XmlSerializer SDC.DataTypes_DEType::Serializer
Referenced by SDC.DataTypes_DEType.Deserialize.
ObjectChangeTracker SDC.DataTypes_DEType.ChangeTracker
BaseType SDC.DataTypes_DEType::_item
Referenced by SDC.DataTypes_DEType.ShouldSerializeItem.
ItemChoiceType SDC.DataTypes_DEType::_itemElementName
ObjectChangeTracker SDC.DataTypes_DEType.changeTrackerField
static XmlSerializer SDC.DataTypes_DEType::serializer
SDC.DataTypes_DEType.DataTypes_DEType()
SDC.DataTypes_DEType.DataTypes_DEType(BaseType parentNode)
SDC.DataTypes_DEType.DataTypes_DEType()
virtual bool SDC.DataTypes_DEType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.null.
virtual string SDC.DataTypes_DEType.Serialize(System.Text.Encoding encoding)
Serializes current DataTypes_DEType object into an XML string
string XML value
virtual string SDC.DataTypes_DEType.Serialize()
Referenced by SDC.DataTypes_DEType.SaveToFile.
virtual bool SDC.DataTypes_DEType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current DataTypes_DEType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.DataTypes_DEType.SaveToFile.
virtual bool SDC.DataTypes_DEType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.DataTypes_DEType.SaveToFile(string fileName)
virtual void SDC.DataTypes_DEType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.DataTypes_DEType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.DataTypes_DEType._item, SDC.null.
virtual string SDC.DataTypes_DEType.Serialize()
Serializes current DataTypes_DEType object into an XML string
string XML value
virtual bool SDC.DataTypes_DEType.SaveToFile(string fileName, out Exception exception)
Serializes current DataTypes_DEType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.DataTypes_DEType.SaveToFile.
virtual void SDC.DataTypes_DEType.SaveToFile(string fileName)
References SDC.null, SDC.DataTypes_DEType.Serialize.
virtual DataTypes_DEType SDC.DataTypes_DEType.Clone()
Create a clone of this DataTypes_DEType object
static bool SDC.DataTypes_DEType.Deserialize(string input, out DataTypes_DEType obj, out System.Exception exception)
Deserializes workflow markup into an DataTypes_DEType object
input string workflow markup to deserialize obj Output DataTypes_DEType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DataTypes_DEType.Deserialize, SDC.DataTypes_DEType.LoadFromFile.
static bool SDC.DataTypes_DEType.Deserialize(string input, out DataTypes_DEType obj)
References SDC.null.
static new DataTypes_DEType SDC.DataTypes_DEType.Deserialize(string input)
References SDC.null.
static DataTypes_DEType SDC.DataTypes_DEType.Deserialize(System.IO.Stream s)
static bool SDC.DataTypes_DEType.LoadFromFile(string fileName, System.Text.Encoding encoding, out DataTypes_DEType obj, out System.Exception exception)
Deserializes xml markup from file into an DataTypes_DEType object
fileName string xml file to load and deserialize obj Output DataTypes_DEType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DataTypes_DEType.LoadFromFile.
static bool SDC.DataTypes_DEType.LoadFromFile(string fileName, out DataTypes_DEType obj, out System.Exception exception)
static bool SDC.DataTypes_DEType.LoadFromFile(string fileName, out DataTypes_DEType obj)
References SDC.null.
static DataTypes_DEType SDC.DataTypes_DEType.LoadFromFile(string fileName)
static new DataTypes_DEType SDC.DataTypes_DEType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.DataTypes_DEType.Deserialize(string input, out DataTypes_DEType obj, out Exception exception)
Deserializes workflow markup into an DataTypes_DEType object
input string workflow markup to deserialize obj Output DataTypes_DEType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.DataTypes_DEType.Deserialize, SDC.null.
static bool SDC.DataTypes_DEType.Deserialize(string input, out DataTypes_DEType obj)
References SDC.DataTypes_DEType.Deserialize, SDC.null.
static new DataTypes_DEType SDC.DataTypes_DEType.Deserialize(string input)
References SDC.null, SDC.DataTypes_DEType.Serializer.
static DataTypes_DEType SDC.DataTypes_DEType.Deserialize(Stream s)
References SDC.DataTypes_DEType.Serializer.
static bool SDC.DataTypes_DEType.LoadFromFile(string fileName, out DataTypes_DEType obj, out Exception exception)
Deserializes xml markup from file into an DataTypes_DEType object
fileName string xml file to load and deserialize obj Output DataTypes_DEType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.DataTypes_DEType.LoadFromFile, SDC.null.
static bool SDC.DataTypes_DEType.LoadFromFile(string fileName, out DataTypes_DEType obj)
References SDC.DataTypes_DEType.LoadFromFile, SDC.null.
static new DataTypes_DEType SDC.DataTypes_DEType.LoadFromFile(string fileName)
References SDC.DataTypes_DEType.Deserialize, SDC.null.