SDC::HTML_Stype
List<System.Xml.XmlElement> SDC.HTML_Stype._any
List<System.Xml.XmlAttribute> SDC.HTML_Stype._anyAttr
BindingList<System.Xml.XmlElement> SDC.HTML_Stype._any
BindingList<System.Xml.XmlAttribute> SDC.HTML_Stype._anyAttr
ObjectChangeTracker SDC.HTML_Stype.changeTrackerField
static XmlSerializer SDC.HTML_Stype::serializer
virtual List<System.Xml.XmlElement> SDC.HTML_Stype.Any
Referenced by SDC.HTML_Stype.ShouldSerializeAny.
virtual List<System.Xml.XmlAttribute> SDC.HTML_Stype.AnyAttr
Referenced by SDC.HTML_Stype.ShouldSerializeAnyAttr.
static XmlSerializer SDC.HTML_Stype::Serializer
Referenced by SDC.HTML_Stype.Deserialize.
virtual BindingList<System.Xml.XmlElement> SDC.HTML_Stype.Any
virtual BindingList<System.Xml.XmlAttribute> SDC.HTML_Stype.AnyAttr
ObjectChangeTracker SDC.HTML_Stype.ChangeTracker
SDC.HTML_Stype.HTML_Stype()
SDC.HTML_Stype.HTML_Stype(BaseType parentNode)
SDC.HTML_Stype.HTML_Stype()
virtual bool SDC.HTML_Stype.ShouldSerializeAny()
Test whether Any should be serialized
References SDC.HTML_Stype.Any, SDC.null.
virtual bool SDC.HTML_Stype.ShouldSerializeAnyAttr()
Test whether AnyAttr should be serialized
References SDC.HTML_Stype.AnyAttr, SDC.null.
virtual string SDC.HTML_Stype.Serialize(System.Text.Encoding encoding)
Serializes current HTML_Stype object into an XML string
string XML value
virtual string SDC.HTML_Stype.Serialize()
Referenced by SDC.HTML_Stype.SaveToFile.
virtual bool SDC.HTML_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current HTML_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.HTML_Stype.SaveToFile.
virtual bool SDC.HTML_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.HTML_Stype.SaveToFile.
virtual void SDC.HTML_Stype.SaveToFile(string fileName)
References SDC.HTML_Stype.SaveToFile.
virtual void SDC.HTML_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.HTML_Stype.Serialize.
virtual string SDC.HTML_Stype.Serialize()
Serializes current HTML_Stype object into an XML string
string XML value
virtual bool SDC.HTML_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current HTML_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.HTML_Stype.SaveToFile.
virtual void SDC.HTML_Stype.SaveToFile(string fileName)
References SDC.null, SDC.HTML_Stype.Serialize.
virtual HTML_Stype SDC.HTML_Stype.Clone()
Create a clone of this HTML_Stype object
static bool SDC.HTML_Stype.Deserialize(string input, out HTML_Stype obj, out System.Exception exception)
Deserializes workflow markup into an HTML_Stype object
input string workflow markup to deserialize obj Output HTML_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.HTML_Stype.Deserialize, SDC.HTML_Stype.LoadFromFile.
static bool SDC.HTML_Stype.Deserialize(string input, out HTML_Stype obj)
References SDC.HTML_Stype.Deserialize, SDC.null.
static new HTML_Stype SDC.HTML_Stype.Deserialize(string input)
References SDC.null.
static HTML_Stype SDC.HTML_Stype.Deserialize(System.IO.Stream s)
References SDC.HTML_Stype.Serializer.
static bool SDC.HTML_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out HTML_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an HTML_Stype object
fileName string xml file to load and deserialize obj Output HTML_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.HTML_Stype.LoadFromFile.
static bool SDC.HTML_Stype.LoadFromFile(string fileName, out HTML_Stype obj, out System.Exception exception)
References SDC.HTML_Stype.LoadFromFile.
static bool SDC.HTML_Stype.LoadFromFile(string fileName, out HTML_Stype obj)
References SDC.HTML_Stype.LoadFromFile, SDC.null.
static HTML_Stype SDC.HTML_Stype.LoadFromFile(string fileName)
References SDC.HTML_Stype.LoadFromFile.
static new HTML_Stype SDC.HTML_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.HTML_Stype.Deserialize, SDC.null.
static bool SDC.HTML_Stype.Deserialize(string input, out HTML_Stype obj, out Exception exception)
Deserializes workflow markup into an HTML_Stype object
input string workflow markup to deserialize obj Output HTML_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.HTML_Stype.Deserialize, SDC.null.
static bool SDC.HTML_Stype.Deserialize(string input, out HTML_Stype obj)
References SDC.HTML_Stype.Deserialize, SDC.null.
static new HTML_Stype SDC.HTML_Stype.Deserialize(string input)
References SDC.null, SDC.HTML_Stype.Serializer.
static HTML_Stype SDC.HTML_Stype.Deserialize(Stream s)
References SDC.HTML_Stype.Serializer.
static bool SDC.HTML_Stype.LoadFromFile(string fileName, out HTML_Stype obj, out Exception exception)
Deserializes xml markup from file into an HTML_Stype object
fileName string xml file to load and deserialize obj Output HTML_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.HTML_Stype.LoadFromFile, SDC.null.
static bool SDC.HTML_Stype.LoadFromFile(string fileName, out HTML_Stype obj)
References SDC.HTML_Stype.LoadFromFile, SDC.null.
static new HTML_Stype SDC.HTML_Stype.LoadFromFile(string fileName)
References SDC.HTML_Stype.Deserialize, SDC.null.