SDC::gMonth_DEtype
string SDC.gMonth_DEtype::_minInclusive
string SDC.gMonth_DEtype::_maxInclusive
string SDC.gMonth_DEtype::_minExclusive
string SDC.gMonth_DEtype::_maxExclusive
string SDC.gMonth_DEtype::_mask
ObjectChangeTracker SDC.gMonth_DEtype.changeTrackerField
static XmlSerializer SDC.gMonth_DEtype::serializer
string SDC.gMonth_DEtype::minInclusive
Referenced by SDC.gMonth_DEtype.ShouldSerializeminInclusive.
string SDC.gMonth_DEtype::maxInclusive
Referenced by SDC.gMonth_DEtype.ShouldSerializemaxInclusive.
string SDC.gMonth_DEtype::minExclusive
Referenced by SDC.gMonth_DEtype.ShouldSerializeminExclusive.
string SDC.gMonth_DEtype::maxExclusive
Referenced by SDC.gMonth_DEtype.ShouldSerializemaxExclusive.
string SDC.gMonth_DEtype::mask
Referenced by SDC.gMonth_DEtype.ShouldSerializemask.
static XmlSerializer SDC.gMonth_DEtype::Serializer
Referenced by SDC.gMonth_DEtype.Deserialize.
ObjectChangeTracker SDC.gMonth_DEtype.ChangeTracker
SDC.gMonth_DEtype.gMonth_DEtype()
SDC.gMonth_DEtype.gMonth_DEtype(BaseType parentNode)
virtual bool SDC.gMonth_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.gMonth_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.gMonth_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.gMonth_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.gMonth_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.gMonth_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current gMonth_DEtype object into an XML string
string XML value
virtual string SDC.gMonth_DEtype.Serialize()
Referenced by SDC.gMonth_DEtype.SaveToFile.
virtual bool SDC.gMonth_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current gMonth_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.gMonth_DEtype.SaveToFile.
virtual bool SDC.gMonth_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.gMonth_DEtype.SaveToFile(string fileName)
virtual void SDC.gMonth_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.gMonth_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.gMonth_DEtype.minInclusive.
virtual bool SDC.gMonth_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.gMonth_DEtype.maxInclusive.
virtual bool SDC.gMonth_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.gMonth_DEtype.minExclusive.
virtual bool SDC.gMonth_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.gMonth_DEtype.maxExclusive.
virtual bool SDC.gMonth_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.gMonth_DEtype.mask.
virtual string SDC.gMonth_DEtype.Serialize()
Serializes current gMonth_DEtype object into an XML string
string XML value
virtual bool SDC.gMonth_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current gMonth_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.gMonth_DEtype.SaveToFile.
virtual void SDC.gMonth_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.gMonth_DEtype.Serialize.
virtual gMonth_DEtype SDC.gMonth_DEtype.Clone()
Create a clone of this gMonth_DEtype object
static bool SDC.gMonth_DEtype.Deserialize(string input, out gMonth_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an gMonth_DEtype object
input string workflow markup to deserialize obj Output gMonth_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gMonth_DEtype.Deserialize, SDC.gMonth_DEtype.LoadFromFile.
static bool SDC.gMonth_DEtype.Deserialize(string input, out gMonth_DEtype obj)
References SDC.null.
static new gMonth_DEtype SDC.gMonth_DEtype.Deserialize(string input)
References SDC.null.
static gMonth_DEtype SDC.gMonth_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.gMonth_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out gMonth_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an gMonth_DEtype object
fileName string xml file to load and deserialize obj Output gMonth_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gMonth_DEtype.LoadFromFile.
static bool SDC.gMonth_DEtype.LoadFromFile(string fileName, out gMonth_DEtype obj, out System.Exception exception)
static bool SDC.gMonth_DEtype.LoadFromFile(string fileName, out gMonth_DEtype obj)
References SDC.null.
static gMonth_DEtype SDC.gMonth_DEtype.LoadFromFile(string fileName)
static new gMonth_DEtype SDC.gMonth_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.gMonth_DEtype.Deserialize(string input, out gMonth_DEtype obj, out Exception exception)
Deserializes workflow markup into an gMonth_DEtype object
input string workflow markup to deserialize obj Output gMonth_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gMonth_DEtype.Deserialize, SDC.null.
static bool SDC.gMonth_DEtype.Deserialize(string input, out gMonth_DEtype obj)
References SDC.gMonth_DEtype.Deserialize, SDC.null.
static new gMonth_DEtype SDC.gMonth_DEtype.Deserialize(string input)
References SDC.null, SDC.gMonth_DEtype.Serializer.
static gMonth_DEtype SDC.gMonth_DEtype.Deserialize(Stream s)
References SDC.gMonth_DEtype.Serializer.
static bool SDC.gMonth_DEtype.LoadFromFile(string fileName, out gMonth_DEtype obj, out Exception exception)
Deserializes xml markup from file into an gMonth_DEtype object
fileName string xml file to load and deserialize obj Output gMonth_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gMonth_DEtype.LoadFromFile, SDC.null.
static bool SDC.gMonth_DEtype.LoadFromFile(string fileName, out gMonth_DEtype obj)
References SDC.gMonth_DEtype.LoadFromFile, SDC.null.
static new gMonth_DEtype SDC.gMonth_DEtype.LoadFromFile(string fileName)
References SDC.gMonth_DEtype.Deserialize, SDC.null.