SDC::DestinationType
anyURI_Stype SDC.DestinationType::_endpoint
Referenced by SDC.DestinationType.ShouldSerializeEndpoint.
string_Stype SDC.DestinationType::_endpointDescription
Referenced by SDC.DestinationType.ShouldSerializeEndpointDescription.
List<string_Stype> SDC.DestinationType._submissionTechnology
OrganizationType SDC.DestinationType::_organization
Referenced by SDC.DestinationType.ShouldSerializeOrganization.
BindingList<string_Stype> SDC.DestinationType._submissionTechnology
ObjectChangeTracker SDC.DestinationType.changeTrackerField
static XmlSerializer SDC.DestinationType::serializer
anyURI_Stype SDC.DestinationType::Endpoint
string_Stype SDC.DestinationType::EndpointDescription
virtual List<string_Stype> SDC.DestinationType.SubmissionTechnology
OrganizationType SDC.DestinationType::Organization
static XmlSerializer SDC.DestinationType::Serializer
Referenced by SDC.DestinationType.Deserialize.
virtual BindingList<string_Stype> SDC.DestinationType.SubmissionTechnology
ObjectChangeTracker SDC.DestinationType.ChangeTracker
SDC.DestinationType.DestinationType()
SDC.DestinationType.DestinationType(BaseType parentNode)
virtual bool SDC.DestinationType.ShouldSerializeSubmissionTechnology()
Test whether SubmissionTechnology should be serialized
References SDC.null.
virtual bool SDC.DestinationType.ShouldSerializeEndpoint()
Test whether Endpoint should be serialized
References SDC.null.
virtual bool SDC.DestinationType.ShouldSerializeEndpointDescription()
Test whether EndpointDescription should be serialized
References SDC.null.
virtual bool SDC.DestinationType.ShouldSerializeOrganization()
Test whether Organization should be serialized
References SDC.null.
virtual string SDC.DestinationType.Serialize(System.Text.Encoding encoding)
Serializes current DestinationType object into an XML string
string XML value
virtual string SDC.DestinationType.Serialize()
Referenced by SDC.DestinationType.SaveToFile.
virtual bool SDC.DestinationType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current DestinationType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.DestinationType.SaveToFile.
virtual bool SDC.DestinationType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.DestinationType.SaveToFile(string fileName)
virtual void SDC.DestinationType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.DestinationType.ShouldSerializeEndpoint()
Test whether Endpoint should be serialized
References SDC.DestinationType._endpoint, SDC.null.
virtual bool SDC.DestinationType.ShouldSerializeEndpointDescription()
Test whether EndpointDescription should be serialized
References SDC.DestinationType._endpointDescription, SDC.null.
virtual bool SDC.DestinationType.ShouldSerializeOrganization()
Test whether Organization should be serialized
References SDC.DestinationType._organization, SDC.null.
virtual string SDC.DestinationType.Serialize()
Serializes current DestinationType object into an XML string
string XML value
virtual bool SDC.DestinationType.SaveToFile(string fileName, out Exception exception)
Serializes current DestinationType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.DestinationType.SaveToFile.
virtual void SDC.DestinationType.SaveToFile(string fileName)
References SDC.null, SDC.DestinationType.Serialize.
virtual DestinationType SDC.DestinationType.Clone()
Create a clone of this DestinationType object
static bool SDC.DestinationType.Deserialize(string input, out DestinationType obj, out System.Exception exception)
Deserializes workflow markup into an DestinationType object
input string workflow markup to deserialize obj Output DestinationType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DestinationType.Deserialize, SDC.DestinationType.LoadFromFile.
static bool SDC.DestinationType.Deserialize(string input, out DestinationType obj)
References SDC.null.
static new DestinationType SDC.DestinationType.Deserialize(string input)
References SDC.null.
static DestinationType SDC.DestinationType.Deserialize(System.IO.Stream s)
static bool SDC.DestinationType.LoadFromFile(string fileName, System.Text.Encoding encoding, out DestinationType obj, out System.Exception exception)
Deserializes xml markup from file into an DestinationType object
fileName string xml file to load and deserialize obj Output DestinationType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DestinationType.LoadFromFile.
static bool SDC.DestinationType.LoadFromFile(string fileName, out DestinationType obj, out System.Exception exception)
static bool SDC.DestinationType.LoadFromFile(string fileName, out DestinationType obj)
References SDC.null.
static DestinationType SDC.DestinationType.LoadFromFile(string fileName)
static new DestinationType SDC.DestinationType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.DestinationType.Deserialize(string input, out DestinationType obj, out Exception exception)
Deserializes workflow markup into an DestinationType object
input string workflow markup to deserialize obj Output DestinationType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.DestinationType.Deserialize, SDC.null.
static bool SDC.DestinationType.Deserialize(string input, out DestinationType obj)
References SDC.DestinationType.Deserialize, SDC.null.
static new DestinationType SDC.DestinationType.Deserialize(string input)
References SDC.null, SDC.DestinationType.Serializer.
static DestinationType SDC.DestinationType.Deserialize(Stream s)
References SDC.DestinationType.Serializer.
static bool SDC.DestinationType.LoadFromFile(string fileName, out DestinationType obj, out Exception exception)
Deserializes xml markup from file into an DestinationType object
fileName string xml file to load and deserialize obj Output DestinationType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.DestinationType.LoadFromFile, SDC.null.
static bool SDC.DestinationType.LoadFromFile(string fileName, out DestinationType obj)
References SDC.DestinationType.LoadFromFile, SDC.null.
static new DestinationType SDC.DestinationType.LoadFromFile(string fileName)
References SDC.DestinationType.Deserialize, SDC.null.