SDC::ListType
List< DisplayedType > SDC.ListType::DisplayedItem_List
Replaces Items; ListItem or DisplayedItem
Referenced by SDC.SDCTreeBuilder.AddListToListField.
virtual List<DisplayedType> SDC.ListType.Items
static XmlSerializer SDC.ListType::Serializer
Referenced by SDC.ListType.Deserialize.
virtual BindingList<DisplayedType> SDC.ListType.DisplayedItem
virtual BindingList<DisplayedType> SDC.ListType.Items
ObjectChangeTracker SDC.ListType.ChangeTracker
List<DisplayedType> SDC.ListType._items
BindingList<DisplayedType> SDC.ListType._displayedItem
BindingList<DisplayedType> SDC.ListType._items
ObjectChangeTracker SDC.ListType.changeTrackerField
static XmlSerializer SDC.ListType::serializer
SDC.ListType.ListType(BaseType parentNode, bool fillData=true)
SDC.ListType.ListType()
virtual bool SDC.ListType.ShouldSerializeItems()
Test whether Items should be serialized
References SDC.null.
virtual string SDC.ListType.Serialize(System.Text.Encoding encoding)
Serializes current ListType object into an XML string
string XML value
virtual string SDC.ListType.Serialize()
Referenced by SDC.ListType.SaveToFile.
virtual bool SDC.ListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ListType.SaveToFile.
virtual bool SDC.ListType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ListType.SaveToFile(string fileName)
virtual void SDC.ListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ListType.Serialize()
Serializes current ListType object into an XML string
string XML value
virtual bool SDC.ListType.SaveToFile(string fileName, out Exception exception)
Serializes current ListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ListType.SaveToFile.
virtual void SDC.ListType.SaveToFile(string fileName)
References SDC.null, SDC.ListType.Serialize.
virtual ListType SDC.ListType.Clone()
Create a clone of this ListType object
SDC.ListType.ListType()
static bool SDC.ListType.Deserialize(string input, out ListType obj, out System.Exception exception)
Deserializes workflow markup into an ListType object
input string workflow markup to deserialize obj Output ListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListType.Deserialize, SDC.ListType.LoadFromFile.
static bool SDC.ListType.Deserialize(string input, out ListType obj)
References SDC.null.
static new ListType SDC.ListType.Deserialize(string input)
References SDC.null.
static ListType SDC.ListType.Deserialize(System.IO.Stream s)
static bool SDC.ListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ListType obj, out System.Exception exception)
Deserializes xml markup from file into an ListType object
fileName string xml file to load and deserialize obj Output ListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListType.LoadFromFile.
static bool SDC.ListType.LoadFromFile(string fileName, out ListType obj, out System.Exception exception)
static bool SDC.ListType.LoadFromFile(string fileName, out ListType obj)
References SDC.null.
static ListType SDC.ListType.LoadFromFile(string fileName)
static new ListType SDC.ListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ListType.Deserialize(string input, out ListType obj, out Exception exception)
Deserializes workflow markup into an ListType object
input string workflow markup to deserialize obj Output ListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListType.Deserialize, SDC.null.
static bool SDC.ListType.Deserialize(string input, out ListType obj)
References SDC.ListType.Deserialize, SDC.null.
static new ListType SDC.ListType.Deserialize(string input)
References SDC.null, SDC.ListType.Serializer.
static ListType SDC.ListType.Deserialize(Stream s)
References SDC.ListType.Serializer.
static bool SDC.ListType.LoadFromFile(string fileName, out ListType obj, out Exception exception)
Deserializes xml markup from file into an ListType object
fileName string xml file to load and deserialize obj Output ListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListType.LoadFromFile, SDC.null.
static bool SDC.ListType.LoadFromFile(string fileName, out ListType obj)
References SDC.ListType.LoadFromFile, SDC.null.
static new ListType SDC.ListType.LoadFromFile(string fileName)
References SDC.ListType.Deserialize, SDC.null.