SDC::int_Stype
bool SDC.int_Stype::_shouldSerializeval
Referenced by SDC.int_Stype.ShouldSerializeval.
System.Nullable<int> SDC.int_Stype._val
Referenced by SDC.int_Stype.ShouldSerializeval.
dtQuantEnum SDC.int_Stype::_quantEnum
Referenced by SDC.int_Stype.int_Stype.
int SDC.int_Stype._val
ObjectChangeTracker SDC.int_Stype.changeTrackerField
static XmlSerializer SDC.int_Stype::serializer
int SDC.int_Stype::val
bool SDC.int_Stype::valSpecified
dtQuantEnum SDC.int_Stype::quantEnum
static XmlSerializer SDC.int_Stype::Serializer
Referenced by SDC.int_Stype.Deserialize.
ObjectChangeTracker SDC.int_Stype.ChangeTracker
SDC.int_Stype.int_Stype()
SDC.int_Stype.int_Stype(BaseType parentNode)
virtual bool SDC.int_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.int_Stype._shouldSerializeval, SDC.int_Stype._val.
virtual string SDC.int_Stype.Serialize(System.Text.Encoding encoding)
Serializes current int_Stype object into an XML string
string XML value
virtual string SDC.int_Stype.Serialize()
Referenced by SDC.int_Stype.SaveToFile.
virtual bool SDC.int_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current int_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.int_Stype.SaveToFile.
virtual bool SDC.int_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.int_Stype.SaveToFile.
virtual void SDC.int_Stype.SaveToFile(string fileName)
References SDC.int_Stype.SaveToFile.
virtual void SDC.int_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.int_Stype.Serialize.
SDC.int_Stype.int_Stype()
int_Stype class constructor
References SDC.int_Stype._quantEnum.
virtual bool SDC.int_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.int_Stype._shouldSerializeval, SDC.int_Stype._val.
virtual string SDC.int_Stype.Serialize()
Serializes current int_Stype object into an XML string
string XML value
virtual bool SDC.int_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current int_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.int_Stype.SaveToFile.
virtual void SDC.int_Stype.SaveToFile(string fileName)
References SDC.null, SDC.int_Stype.Serialize.
virtual int_Stype SDC.int_Stype.Clone()
Create a clone of this int_Stype object
static bool SDC.int_Stype.Deserialize(string input, out int_Stype obj, out System.Exception exception)
Deserializes workflow markup into an int_Stype object
input string workflow markup to deserialize obj Output int_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.int_Stype.Deserialize, SDC.int_Stype.LoadFromFile.
static bool SDC.int_Stype.Deserialize(string input, out int_Stype obj)
References SDC.int_Stype.Deserialize, SDC.null.
static new int_Stype SDC.int_Stype.Deserialize(string input)
References SDC.null.
static int_Stype SDC.int_Stype.Deserialize(System.IO.Stream s)
References SDC.int_Stype.Serializer.
static bool SDC.int_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out int_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an int_Stype object
fileName string xml file to load and deserialize obj Output int_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.int_Stype.LoadFromFile.
static bool SDC.int_Stype.LoadFromFile(string fileName, out int_Stype obj, out System.Exception exception)
References SDC.int_Stype.LoadFromFile.
static bool SDC.int_Stype.LoadFromFile(string fileName, out int_Stype obj)
References SDC.int_Stype.LoadFromFile, SDC.null.
static int_Stype SDC.int_Stype.LoadFromFile(string fileName)
References SDC.int_Stype.LoadFromFile.
static new int_Stype SDC.int_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.int_Stype.Deserialize, SDC.null.
static bool SDC.int_Stype.Deserialize(string input, out int_Stype obj, out Exception exception)
Deserializes workflow markup into an int_Stype object
input string workflow markup to deserialize obj Output int_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.int_Stype.Deserialize, SDC.null.
static bool SDC.int_Stype.Deserialize(string input, out int_Stype obj)
References SDC.int_Stype.Deserialize, SDC.null.
static new int_Stype SDC.int_Stype.Deserialize(string input)
References SDC.null, SDC.int_Stype.Serializer.
static int_Stype SDC.int_Stype.Deserialize(Stream s)
References SDC.int_Stype.Serializer.
static bool SDC.int_Stype.LoadFromFile(string fileName, out int_Stype obj, out Exception exception)
Deserializes xml markup from file into an int_Stype object
fileName string xml file to load and deserialize obj Output int_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.int_Stype.LoadFromFile, SDC.null.
static bool SDC.int_Stype.LoadFromFile(string fileName, out int_Stype obj)
References SDC.int_Stype.LoadFromFile, SDC.null.
static new int_Stype SDC.int_Stype.LoadFromFile(string fileName)
References SDC.int_Stype.Deserialize, SDC.null.