SDC::EmailType
EmailAddressType SDC.EmailType::_emailAddress
Referenced by SDC.EmailType.ShouldSerializeEmailAddress.
string_Stype SDC.EmailType::_emailClass
Referenced by SDC.EmailType.ShouldSerializeEmailClass.
string_Stype SDC.EmailType::_usage
Referenced by SDC.EmailType.ShouldSerializeUsage.
ObjectChangeTracker SDC.EmailType.changeTrackerField
static XmlSerializer SDC.EmailType::serializer
EmailAddressType SDC.EmailType::EmailAddress
string_Stype SDC.EmailType::EmailClass
Type of email, e.g., home, office, etc
string_Stype SDC.EmailType::Usage
When this email should be used
static XmlSerializer SDC.EmailType::Serializer
Referenced by SDC.EmailType.Deserialize.
ObjectChangeTracker SDC.EmailType.ChangeTracker
SDC.EmailType.EmailType()
SDC.EmailType.EmailType(BaseType parentNode)
virtual bool SDC.EmailType.ShouldSerializeEmailAddress()
Test whether EmailAddress should be serialized
References SDC.null.
virtual bool SDC.EmailType.ShouldSerializeEmailClass()
Test whether EmailClass should be serialized
References SDC.null.
virtual bool SDC.EmailType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.null.
virtual string SDC.EmailType.Serialize(System.Text.Encoding encoding)
Serializes current EmailType object into an XML string
string XML value
virtual string SDC.EmailType.Serialize()
Referenced by SDC.EmailType.SaveToFile.
virtual bool SDC.EmailType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current EmailType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.EmailType.SaveToFile.
virtual bool SDC.EmailType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.EmailType.SaveToFile(string fileName)
virtual void SDC.EmailType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.EmailType.ShouldSerializeEmailAddress()
Test whether EmailAddress should be serialized
References SDC.EmailType._emailAddress, SDC.null.
virtual bool SDC.EmailType.ShouldSerializeEmailClass()
Test whether EmailClass should be serialized
References SDC.EmailType._emailClass, SDC.null.
virtual bool SDC.EmailType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.EmailType._usage, SDC.null.
virtual string SDC.EmailType.Serialize()
Serializes current EmailType object into an XML string
string XML value
virtual bool SDC.EmailType.SaveToFile(string fileName, out Exception exception)
Serializes current EmailType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.EmailType.SaveToFile.
virtual void SDC.EmailType.SaveToFile(string fileName)
References SDC.null, SDC.EmailType.Serialize.
virtual EmailType SDC.EmailType.Clone()
Create a clone of this EmailType object
static bool SDC.EmailType.Deserialize(string input, out EmailType obj, out System.Exception exception)
Deserializes workflow markup into an EmailType object
input string workflow markup to deserialize obj Output EmailType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.EmailType.Deserialize, SDC.EmailType.LoadFromFile.
static bool SDC.EmailType.Deserialize(string input, out EmailType obj)
References SDC.null.
static new EmailType SDC.EmailType.Deserialize(string input)
References SDC.null.
static EmailType SDC.EmailType.Deserialize(System.IO.Stream s)
static bool SDC.EmailType.LoadFromFile(string fileName, System.Text.Encoding encoding, out EmailType obj, out System.Exception exception)
Deserializes xml markup from file into an EmailType object
fileName string xml file to load and deserialize obj Output EmailType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.EmailType.LoadFromFile.
static bool SDC.EmailType.LoadFromFile(string fileName, out EmailType obj, out System.Exception exception)
static bool SDC.EmailType.LoadFromFile(string fileName, out EmailType obj)
References SDC.null.
static EmailType SDC.EmailType.LoadFromFile(string fileName)
static new EmailType SDC.EmailType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.EmailType.Deserialize(string input, out EmailType obj, out Exception exception)
Deserializes workflow markup into an EmailType object
input string workflow markup to deserialize obj Output EmailType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.EmailType.Deserialize, SDC.null.
static bool SDC.EmailType.Deserialize(string input, out EmailType obj)
References SDC.EmailType.Deserialize, SDC.null.
static new EmailType SDC.EmailType.Deserialize(string input)
References SDC.null, SDC.EmailType.Serializer.
static EmailType SDC.EmailType.Deserialize(Stream s)
References SDC.EmailType.Serializer.
static bool SDC.EmailType.LoadFromFile(string fileName, out EmailType obj, out Exception exception)
Deserializes xml markup from file into an EmailType object
fileName string xml file to load and deserialize obj Output EmailType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.EmailType.LoadFromFile, SDC.null.
static bool SDC.EmailType.LoadFromFile(string fileName, out EmailType obj)
References SDC.EmailType.LoadFromFile, SDC.null.
static new EmailType SDC.EmailType.LoadFromFile(string fileName)
References SDC.EmailType.Deserialize, SDC.null.