SDC::ChangeTrackingType
List<string_Stype> SDC.ChangeTrackingType._changeTrackingID
BindingList<string_Stype> SDC.ChangeTrackingType._changeTrackingID
ObjectChangeTracker SDC.ChangeTrackingType.changeTrackerField
static XmlSerializer SDC.ChangeTrackingType::serializer
virtual List<string_Stype> SDC.ChangeTrackingType.ChangeTrackingID
static XmlSerializer SDC.ChangeTrackingType::Serializer
Referenced by SDC.ChangeTrackingType.Deserialize.
virtual BindingList<string_Stype> SDC.ChangeTrackingType.ChangeTrackingID
ObjectChangeTracker SDC.ChangeTrackingType.ChangeTracker
virtual bool SDC.ChangeTrackingType.ShouldSerializeChangeTrackingID()
Test whether ChangeTrackingID should be serialized
References SDC.null.
virtual string SDC.ChangeTrackingType.Serialize(System.Text.Encoding encoding)
Serializes current ChangeTrackingType object into an XML string
string XML value
virtual string SDC.ChangeTrackingType.Serialize()
Referenced by SDC.ChangeTrackingType.SaveToFile.
virtual bool SDC.ChangeTrackingType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ChangeTrackingType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ChangeTrackingType.SaveToFile.
virtual bool SDC.ChangeTrackingType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ChangeTrackingType.SaveToFile(string fileName)
virtual void SDC.ChangeTrackingType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ChangeTrackingType.Serialize()
Serializes current ChangeTrackingType object into an XML string
string XML value
virtual bool SDC.ChangeTrackingType.SaveToFile(string fileName, out Exception exception)
Serializes current ChangeTrackingType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ChangeTrackingType.SaveToFile.
virtual void SDC.ChangeTrackingType.SaveToFile(string fileName)
References SDC.null, SDC.ChangeTrackingType.Serialize.
virtual ChangeTrackingType SDC.ChangeTrackingType.Clone()
Create a clone of this ChangeTrackingType object
static bool SDC.ChangeTrackingType.Deserialize(string input, out ChangeTrackingType obj, out System.Exception exception)
Deserializes workflow markup into an ChangeTrackingType object
input string workflow markup to deserialize obj Output ChangeTrackingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangeTrackingType.Deserialize, SDC.ChangeTrackingType.LoadFromFile.
static bool SDC.ChangeTrackingType.Deserialize(string input, out ChangeTrackingType obj)
References SDC.null.
static new ChangeTrackingType SDC.ChangeTrackingType.Deserialize(string input)
References SDC.null.
static ChangeTrackingType SDC.ChangeTrackingType.Deserialize(System.IO.Stream s)
static bool SDC.ChangeTrackingType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ChangeTrackingType obj, out System.Exception exception)
Deserializes xml markup from file into an ChangeTrackingType object
fileName string xml file to load and deserialize obj Output ChangeTrackingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangeTrackingType.LoadFromFile.
static bool SDC.ChangeTrackingType.LoadFromFile(string fileName, out ChangeTrackingType obj, out System.Exception exception)
static bool SDC.ChangeTrackingType.LoadFromFile(string fileName, out ChangeTrackingType obj)
References SDC.null.
static ChangeTrackingType SDC.ChangeTrackingType.LoadFromFile(string fileName)
static new ChangeTrackingType SDC.ChangeTrackingType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ChangeTrackingType.Deserialize(string input, out ChangeTrackingType obj, out Exception exception)
Deserializes workflow markup into an ChangeTrackingType object
input string workflow markup to deserialize obj Output ChangeTrackingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChangeTrackingType.Deserialize, SDC.null.
static bool SDC.ChangeTrackingType.Deserialize(string input, out ChangeTrackingType obj)
References SDC.ChangeTrackingType.Deserialize, SDC.null.
static new ChangeTrackingType SDC.ChangeTrackingType.Deserialize(string input)
References SDC.null, SDC.ChangeTrackingType.Serializer.
static ChangeTrackingType SDC.ChangeTrackingType.Deserialize(Stream s)
References SDC.ChangeTrackingType.Serializer.
static bool SDC.ChangeTrackingType.LoadFromFile(string fileName, out ChangeTrackingType obj, out Exception exception)
Deserializes xml markup from file into an ChangeTrackingType object
fileName string xml file to load and deserialize obj Output ChangeTrackingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChangeTrackingType.LoadFromFile, SDC.null.
static bool SDC.ChangeTrackingType.LoadFromFile(string fileName, out ChangeTrackingType obj)
References SDC.ChangeTrackingType.LoadFromFile, SDC.null.
static new ChangeTrackingType SDC.ChangeTrackingType.LoadFromFile(string fileName)
References SDC.ChangeTrackingType.Deserialize, SDC.null.