SDC::ChangedFieldType
TargetItemIDType SDC.ChangedFieldType::TargetItemID_Item
TargetItemID, TargetItemIDType
TargetItemNameType SDC.ChangedFieldType::TargetItemName_Item
TargetItemName, TargetItemNameType
TargetItemXPathType SDC.ChangedFieldType::TargetItemXPath_Item
TargetItemXPath, TargetItemXPathType
BaseType SDC.ChangedFieldType::Item
static XmlSerializer SDC.ChangedFieldType::Serializer
Referenced by SDC.ChangedFieldType.Deserialize.
ObjectChangeTracker SDC.ChangedFieldType.ChangeTracker
BaseType SDC.ChangedFieldType::_item
Referenced by SDC.ChangedFieldType.ShouldSerializeItem.
ObjectChangeTracker SDC.ChangedFieldType.changeTrackerField
static XmlSerializer SDC.ChangedFieldType::serializer
SDC.ChangedFieldType.ChangedFieldType()
virtual bool SDC.ChangedFieldType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.null.
virtual string SDC.ChangedFieldType.Serialize(System.Text.Encoding encoding)
Serializes current ChangedFieldType object into an XML string
string XML value
virtual string SDC.ChangedFieldType.Serialize()
Referenced by SDC.ChangedFieldType.SaveToFile.
virtual bool SDC.ChangedFieldType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ChangedFieldType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ChangedFieldType.SaveToFile.
virtual bool SDC.ChangedFieldType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ChangedFieldType.SaveToFile(string fileName)
virtual void SDC.ChangedFieldType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ChangedFieldType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.ChangedFieldType._item, SDC.null.
virtual string SDC.ChangedFieldType.Serialize()
Serializes current ChangedFieldType object into an XML string
string XML value
virtual bool SDC.ChangedFieldType.SaveToFile(string fileName, out Exception exception)
Serializes current ChangedFieldType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ChangedFieldType.SaveToFile.
virtual void SDC.ChangedFieldType.SaveToFile(string fileName)
References SDC.null, SDC.ChangedFieldType.Serialize.
virtual ChangedFieldType SDC.ChangedFieldType.Clone()
Create a clone of this ChangedFieldType object
static bool SDC.ChangedFieldType.Deserialize(string input, out ChangedFieldType obj, out System.Exception exception)
Deserializes workflow markup into an ChangedFieldType object
input string workflow markup to deserialize obj Output ChangedFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangedFieldType.Deserialize, SDC.ChangedFieldType.LoadFromFile.
static bool SDC.ChangedFieldType.Deserialize(string input, out ChangedFieldType obj)
References SDC.null.
static new ChangedFieldType SDC.ChangedFieldType.Deserialize(string input)
References SDC.null.
static ChangedFieldType SDC.ChangedFieldType.Deserialize(System.IO.Stream s)
static bool SDC.ChangedFieldType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ChangedFieldType obj, out System.Exception exception)
Deserializes xml markup from file into an ChangedFieldType object
fileName string xml file to load and deserialize obj Output ChangedFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangedFieldType.LoadFromFile.
static bool SDC.ChangedFieldType.LoadFromFile(string fileName, out ChangedFieldType obj, out System.Exception exception)
static bool SDC.ChangedFieldType.LoadFromFile(string fileName, out ChangedFieldType obj)
References SDC.null.
static ChangedFieldType SDC.ChangedFieldType.LoadFromFile(string fileName)
static new ChangedFieldType SDC.ChangedFieldType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ChangedFieldType.Deserialize(string input, out ChangedFieldType obj, out Exception exception)
Deserializes workflow markup into an ChangedFieldType object
input string workflow markup to deserialize obj Output ChangedFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChangedFieldType.Deserialize, SDC.null.
static bool SDC.ChangedFieldType.Deserialize(string input, out ChangedFieldType obj)
References SDC.ChangedFieldType.Deserialize, SDC.null.
static new ChangedFieldType SDC.ChangedFieldType.Deserialize(string input)
References SDC.null, SDC.ChangedFieldType.Serializer.
static ChangedFieldType SDC.ChangedFieldType.Deserialize(Stream s)
References SDC.ChangedFieldType.Serializer.
static bool SDC.ChangedFieldType.LoadFromFile(string fileName, out ChangedFieldType obj, out Exception exception)
Deserializes xml markup from file into an ChangedFieldType object
fileName string xml file to load and deserialize obj Output ChangedFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChangedFieldType.LoadFromFile, SDC.null.
static bool SDC.ChangedFieldType.LoadFromFile(string fileName, out ChangedFieldType obj)
References SDC.ChangedFieldType.LoadFromFile, SDC.null.
static new ChangedFieldType SDC.ChangedFieldType.LoadFromFile(string fileName)
References SDC.ChangedFieldType.Deserialize, SDC.null.