SDC::InputStr_ReturnIntegerType
StringFunctionsStrType SDC.InputStr_ReturnIntegerType._inputStr
Referenced by SDC.InputStr_ReturnIntegerType.ShouldSerializeInputStr.
XmlSerializer SDC.InputStr_ReturnIntegerType.serializer
virtual StringFunctionsStrType SDC.InputStr_ReturnIntegerType.InputStr
XmlSerializer SDC.InputStr_ReturnIntegerType.Serializer
Referenced by SDC.InputStr_ReturnIntegerType.Deserialize.
virtual bool SDC.InputStr_ReturnIntegerType.ShouldSerializeInputStr()
Test whether InputStr should be serialized
References SDC.InputStr_ReturnIntegerType._inputStr, SDC.null.
virtual string SDC.InputStr_ReturnIntegerType.Serialize(System.Text.Encoding encoding)
Serializes current InputStr_ReturnIntegerType object into an XML string
string XML value
virtual string SDC.InputStr_ReturnIntegerType.Serialize()
Referenced by SDC.InputStr_ReturnIntegerType.SaveToFile.
virtual bool SDC.InputStr_ReturnIntegerType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InputStr_ReturnIntegerType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InputStr_ReturnIntegerType.SaveToFile.
virtual bool SDC.InputStr_ReturnIntegerType.SaveToFile(string fileName, out System.Exception exception)
References SDC.InputStr_ReturnIntegerType.SaveToFile.
virtual void SDC.InputStr_ReturnIntegerType.SaveToFile(string fileName)
References SDC.InputStr_ReturnIntegerType.SaveToFile.
virtual void SDC.InputStr_ReturnIntegerType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InputStr_ReturnIntegerType.Serialize.
static bool SDC.InputStr_ReturnIntegerType.Deserialize(string input, out InputStr_ReturnIntegerType obj, out System.Exception exception)
Deserializes workflow markup into an InputStr_ReturnIntegerType object
input string workflow markup to deserialize obj Output InputStr_ReturnIntegerType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnIntegerType.Deserialize, SDC.InputStr_ReturnIntegerType.LoadFromFile.
static bool SDC.InputStr_ReturnIntegerType.Deserialize(string input, out InputStr_ReturnIntegerType obj)
References SDC.InputStr_ReturnIntegerType.Deserialize, SDC.null.
static new InputStr_ReturnIntegerType SDC.InputStr_ReturnIntegerType.Deserialize(string input)
References SDC.null.
static InputStr_ReturnIntegerType SDC.InputStr_ReturnIntegerType.Deserialize(System.IO.Stream s)
References SDC.InputStr_ReturnIntegerType.Serializer.
static bool SDC.InputStr_ReturnIntegerType.LoadFromFile(string fileName, System.Text.Encoding encoding, out InputStr_ReturnIntegerType obj, out System.Exception exception)
Deserializes xml markup from file into an InputStr_ReturnIntegerType object
fileName string xml file to load and deserialize obj Output InputStr_ReturnIntegerType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnIntegerType.LoadFromFile.
static bool SDC.InputStr_ReturnIntegerType.LoadFromFile(string fileName, out InputStr_ReturnIntegerType obj, out System.Exception exception)
References SDC.InputStr_ReturnIntegerType.LoadFromFile.
static bool SDC.InputStr_ReturnIntegerType.LoadFromFile(string fileName, out InputStr_ReturnIntegerType obj)
References SDC.InputStr_ReturnIntegerType.LoadFromFile, SDC.null.
static InputStr_ReturnIntegerType SDC.InputStr_ReturnIntegerType.LoadFromFile(string fileName)
References SDC.InputStr_ReturnIntegerType.LoadFromFile.
static new InputStr_ReturnIntegerType SDC.InputStr_ReturnIntegerType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InputStr_ReturnIntegerType.Deserialize, SDC.null.