SDC::MaxExclusiveType
string SDC.MaxExclusiveType._val
ObjectChangeTracker SDC.MaxExclusiveType.changeTrackerField
XmlSerializer SDC.MaxExclusiveType.serializer
virtual string SDC.MaxExclusiveType.val
Referenced by SDC.MaxExclusiveType.ShouldSerializeval.
XmlSerializer SDC.MaxExclusiveType.Serializer
Referenced by SDC.MaxExclusiveType.Deserialize.
ObjectChangeTracker SDC.MaxExclusiveType.ChangeTracker
SDC.MaxExclusiveType.MaxExclusiveType()
virtual bool SDC.MaxExclusiveType.ShouldSerializeval()
Test whether val should be serialized
References SDC.MaxExclusiveType.val.
virtual string SDC.MaxExclusiveType.Serialize()
Serializes current MaxExclusiveType object into an XML string
string XML value
Referenced by SDC.MaxExclusiveType.SaveToFile.
virtual bool SDC.MaxExclusiveType.SaveToFile(string fileName, out Exception exception)
Serializes current MaxExclusiveType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.MaxExclusiveType.SaveToFile(string fileName)
References SDC.null, SDC.MaxExclusiveType.Serialize.
virtual MaxExclusiveType SDC.MaxExclusiveType.Clone()
Create a clone of this MaxExclusiveType object
static bool SDC.MaxExclusiveType.Deserialize(string input, out MaxExclusiveType obj, out Exception exception)
Deserializes workflow markup into an MaxExclusiveType object
input string workflow markup to deserialize obj Output MaxExclusiveType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.MaxExclusiveType.Deserialize, SDC.MaxExclusiveType.LoadFromFile.
static bool SDC.MaxExclusiveType.Deserialize(string input, out MaxExclusiveType obj)
References SDC.MaxExclusiveType.Deserialize, SDC.null.
static new MaxExclusiveType SDC.MaxExclusiveType.Deserialize(string input)
References SDC.null, SDC.MaxExclusiveType.Serializer.
static MaxExclusiveType SDC.MaxExclusiveType.Deserialize(Stream s)
References SDC.MaxExclusiveType.Serializer.
static bool SDC.MaxExclusiveType.LoadFromFile(string fileName, out MaxExclusiveType obj, out Exception exception)
Deserializes xml markup from file into an MaxExclusiveType object
fileName string xml file to load and deserialize obj Output MaxExclusiveType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.MaxExclusiveType.LoadFromFile.
static bool SDC.MaxExclusiveType.LoadFromFile(string fileName, out MaxExclusiveType obj)
References SDC.MaxExclusiveType.LoadFromFile, SDC.null.
static new MaxExclusiveType SDC.MaxExclusiveType.LoadFromFile(string fileName)
References SDC.MaxExclusiveType.Deserialize, SDC.null.