SDC::WatchedPropertyType
bool SDC.WatchedPropertyType::_shouldSerializeonlyIf
Referenced by SDC.WatchedPropertyType.ShouldSerializeonlyIf.
bool SDC.WatchedPropertyType::_onlyIf
Referenced by SDC.WatchedPropertyType.ShouldSerializeonlyIf.
ObjectChangeTracker SDC.WatchedPropertyType.changeTrackerField
static XmlSerializer SDC.WatchedPropertyType::serializer
bool SDC.WatchedPropertyType::onlyIf
WatchedPropertyType class constructor
static XmlSerializer SDC.WatchedPropertyType::Serializer
Referenced by SDC.WatchedPropertyType.Deserialize.
virtual bool SDC.WatchedPropertyType.onlyIfSpecified
ObjectChangeTracker SDC.WatchedPropertyType.ChangeTracker
SDC.WatchedPropertyType.WatchedPropertyType()
SDC.WatchedPropertyType.WatchedPropertyType(BaseType parentNode, bool fillData=true)
SDC.WatchedPropertyType.WatchedPropertyType()
virtual bool SDC.WatchedPropertyType.ShouldSerializeonlyIf()
Test whether onlyIf should be serialized
virtual string SDC.WatchedPropertyType.Serialize(System.Text.Encoding encoding)
Serializes current WatchedPropertyType object into an XML string
string XML value
virtual string SDC.WatchedPropertyType.Serialize()
Referenced by SDC.WatchedPropertyType.SaveToFile.
virtual bool SDC.WatchedPropertyType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current WatchedPropertyType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.WatchedPropertyType.SaveToFile.
virtual bool SDC.WatchedPropertyType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.WatchedPropertyType.SaveToFile(string fileName)
virtual void SDC.WatchedPropertyType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.WatchedPropertyType.ShouldSerializeonlyIf()
Test whether onlyIf should be serialized
References SDC.WatchedPropertyType._onlyIf, SDC.WatchedPropertyType._shouldSerializeonlyIf.
virtual string SDC.WatchedPropertyType.Serialize()
Serializes current WatchedPropertyType object into an XML string
string XML value
virtual bool SDC.WatchedPropertyType.SaveToFile(string fileName, out Exception exception)
Serializes current WatchedPropertyType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.WatchedPropertyType.SaveToFile.
virtual void SDC.WatchedPropertyType.SaveToFile(string fileName)
References SDC.null, SDC.WatchedPropertyType.Serialize.
virtual WatchedPropertyType SDC.WatchedPropertyType.Clone()
Create a clone of this WatchedPropertyType object
static bool SDC.WatchedPropertyType.Deserialize(string input, out WatchedPropertyType obj, out System.Exception exception)
Deserializes workflow markup into an WatchedPropertyType object
input string workflow markup to deserialize obj Output WatchedPropertyType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.WatchedPropertyType.Deserialize, SDC.WatchedPropertyType.LoadFromFile.
static bool SDC.WatchedPropertyType.Deserialize(string input, out WatchedPropertyType obj)
References SDC.null.
static new WatchedPropertyType SDC.WatchedPropertyType.Deserialize(string input)
References SDC.null.
static WatchedPropertyType SDC.WatchedPropertyType.Deserialize(System.IO.Stream s)
static bool SDC.WatchedPropertyType.LoadFromFile(string fileName, System.Text.Encoding encoding, out WatchedPropertyType obj, out System.Exception exception)
Deserializes xml markup from file into an WatchedPropertyType object
fileName string xml file to load and deserialize obj Output WatchedPropertyType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.WatchedPropertyType.LoadFromFile.
static bool SDC.WatchedPropertyType.LoadFromFile(string fileName, out WatchedPropertyType obj, out System.Exception exception)
static bool SDC.WatchedPropertyType.LoadFromFile(string fileName, out WatchedPropertyType obj)
References SDC.null.
static WatchedPropertyType SDC.WatchedPropertyType.LoadFromFile(string fileName)
static new WatchedPropertyType SDC.WatchedPropertyType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.WatchedPropertyType.Deserialize(string input, out WatchedPropertyType obj, out Exception exception)
Deserializes workflow markup into an WatchedPropertyType object
input string workflow markup to deserialize obj Output WatchedPropertyType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.WatchedPropertyType.Deserialize, SDC.null.
static bool SDC.WatchedPropertyType.Deserialize(string input, out WatchedPropertyType obj)
References SDC.WatchedPropertyType.Deserialize, SDC.null.
static new WatchedPropertyType SDC.WatchedPropertyType.Deserialize(string input)
References SDC.null, SDC.WatchedPropertyType.Serializer.
static WatchedPropertyType SDC.WatchedPropertyType.Deserialize(Stream s)
References SDC.WatchedPropertyType.Serializer.
static bool SDC.WatchedPropertyType.LoadFromFile(string fileName, out WatchedPropertyType obj, out Exception exception)
Deserializes xml markup from file into an WatchedPropertyType object
fileName string xml file to load and deserialize obj Output WatchedPropertyType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.WatchedPropertyType.LoadFromFile, SDC.null.
static bool SDC.WatchedPropertyType.LoadFromFile(string fileName, out WatchedPropertyType obj)
References SDC.WatchedPropertyType.LoadFromFile, SDC.null.
static new WatchedPropertyType SDC.WatchedPropertyType.LoadFromFile(string fileName)
References SDC.WatchedPropertyType.Deserialize, SDC.null.