SDC::InputList_ReturnStrType111
AnyFunctionsListType SDC.InputList_ReturnStrType111._inputList
Referenced by SDC.InputList_ReturnStrType111.ShouldSerializeInputList.
XmlSerializer SDC.InputList_ReturnStrType111.serializer
virtual AnyFunctionsListType SDC.InputList_ReturnStrType111.InputList
XmlSerializer SDC.InputList_ReturnStrType111.Serializer
Referenced by SDC.InputList_ReturnStrType111.Deserialize.
virtual bool SDC.InputList_ReturnStrType111.ShouldSerializeInputList()
Test whether InputList should be serialized
References SDC.InputList_ReturnStrType111._inputList, SDC.null.
virtual string SDC.InputList_ReturnStrType111.Serialize(System.Text.Encoding encoding)
Serializes current InputList_ReturnStrType111 object into an XML string
string XML value
virtual string SDC.InputList_ReturnStrType111.Serialize()
Referenced by SDC.InputList_ReturnStrType111.SaveToFile.
virtual bool SDC.InputList_ReturnStrType111.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InputList_ReturnStrType111 object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InputList_ReturnStrType111.SaveToFile.
virtual bool SDC.InputList_ReturnStrType111.SaveToFile(string fileName, out System.Exception exception)
References SDC.InputList_ReturnStrType111.SaveToFile.
virtual void SDC.InputList_ReturnStrType111.SaveToFile(string fileName)
References SDC.InputList_ReturnStrType111.SaveToFile.
virtual void SDC.InputList_ReturnStrType111.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InputList_ReturnStrType111.Serialize.
static bool SDC.InputList_ReturnStrType111.Deserialize(string input, out InputList_ReturnStrType111 obj, out System.Exception exception)
Deserializes workflow markup into an InputList_ReturnStrType111 object
input string workflow markup to deserialize obj Output InputList_ReturnStrType111 object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputList_ReturnStrType111.Deserialize, SDC.InputList_ReturnStrType111.LoadFromFile.
static bool SDC.InputList_ReturnStrType111.Deserialize(string input, out InputList_ReturnStrType111 obj)
References SDC.InputList_ReturnStrType111.Deserialize, SDC.null.
static new InputList_ReturnStrType111 SDC.InputList_ReturnStrType111.Deserialize(string input)
References SDC.null.
static InputList_ReturnStrType111 SDC.InputList_ReturnStrType111.Deserialize(System.IO.Stream s)
References SDC.InputList_ReturnStrType111.Serializer.
static bool SDC.InputList_ReturnStrType111.LoadFromFile(string fileName, System.Text.Encoding encoding, out InputList_ReturnStrType111 obj, out System.Exception exception)
Deserializes xml markup from file into an InputList_ReturnStrType111 object
fileName string xml file to load and deserialize obj Output InputList_ReturnStrType111 object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputList_ReturnStrType111.LoadFromFile.
static bool SDC.InputList_ReturnStrType111.LoadFromFile(string fileName, out InputList_ReturnStrType111 obj, out System.Exception exception)
References SDC.InputList_ReturnStrType111.LoadFromFile.
static bool SDC.InputList_ReturnStrType111.LoadFromFile(string fileName, out InputList_ReturnStrType111 obj)
References SDC.InputList_ReturnStrType111.LoadFromFile, SDC.null.
static InputList_ReturnStrType111 SDC.InputList_ReturnStrType111.LoadFromFile(string fileName)
References SDC.InputList_ReturnStrType111.LoadFromFile.
static new InputList_ReturnStrType111 SDC.InputList_ReturnStrType111.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InputList_ReturnStrType111.Deserialize, SDC.null.