SDC::ListItemType
ChildItemsType SDC.ListItemType.ChildItemsNode
The ChildItems node replaces "Item" (MainNodesType), and may contain: "ButtonAction", typeof(ButtonItemType), "DisplayedItem", typeof(DisplayedType), "InjectForm", typeof(InjectFormType), "Question", typeof(QuestionItemType), "Section", typeof(SectionItemType),
ChildItemsType SDC.ListItemType.ChildItems_Item
The ChildItems node replaces "Item" (MainNodesType), and may contain: "ButtonAction", typeof(ButtonItemType), "DisplayedItem", typeof(DisplayedType), "InjectForm", typeof(InjectFormType), "Question", typeof(QuestionItemType), "Section", typeof(SectionItemType),
ChildItemsType SDC.ListItemType::Item
static XmlSerializer SDC.ListItemType::Serializer
Referenced by SDC.ListItemType.Deserialize.
ObjectChangeTracker SDC.ListItemType.ChangeTracker
ChildItemsType SDC.ListItemType::_item
Referenced by SDC.ListItemType.ShouldSerializeItem.
ObjectChangeTracker SDC.ListItemType.changeTrackerField
static XmlSerializer SDC.ListItemType::serializer
SDC.ListItemType.ListItemType()
SDC.ListItemType.ListItemType(BaseType parentNode, bool fillData=true, string id=null)
+Replaced in original class: need public parameterless constructor to support generics
ListItemResponseFieldType SDC.ListItemType.AddListItemResponseField(ListItemBaseType li)
SectionItemType SDC.ListItemType.AddSection(Boolean fillData=true, string id=null)
QuestionItemType SDC.ListItemType.AddQuestion(QuestionEnum qType, Boolean fillData=true, string id=null)
InjectFormType SDC.ListItemType.AddInjectedForm(Boolean fillData=true, string id=null)
ButtonItemType SDC.ListItemType.AddButtonAction(Boolean fillData=true, string id=null)
DisplayedType SDC.ListItemType.AddDisplayedItem(Boolean fillData=true, string id=null)
SDC.ListItemType.ListItemType()
ListItemResponseFieldType SDC.ListItemType.AddListItemResponseField(ListItemBaseType li)
SectionItemType SDC.ListItemType.AddSection()
QuestionItemType SDC.ListItemType.AddQuestion(ItemType qType)
InjectFormType SDC.ListItemType.AddInjectedForm()
ButtonItemType SDC.ListItemType.AddButtonAction()
DisplayedType SDC.ListItemType.AddDisplayedItem()
virtual bool SDC.ListItemType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.null.
virtual string SDC.ListItemType.Serialize(System.Text.Encoding encoding)
Serializes current ListItemType object into an XML string
string XML value
virtual string SDC.ListItemType.Serialize()
Referenced by SDC.ListItemType.SaveToFile.
virtual bool SDC.ListItemType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ListItemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ListItemType.SaveToFile.
virtual bool SDC.ListItemType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ListItemType.SaveToFile(string fileName)
virtual void SDC.ListItemType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ListItemType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.ListItemType._item, SDC.null.
virtual string SDC.ListItemType.Serialize()
Serializes current ListItemType object into an XML string
string XML value
virtual bool SDC.ListItemType.SaveToFile(string fileName, out Exception exception)
Serializes current ListItemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ListItemType.SaveToFile.
virtual void SDC.ListItemType.SaveToFile(string fileName)
References SDC.null, SDC.ListItemType.Serialize.
virtual ListItemType SDC.ListItemType.Clone()
Create a clone of this ListItemType object
static bool SDC.ListItemType.Deserialize(string input, out ListItemType obj, out System.Exception exception)
Deserializes workflow markup into an ListItemType object
input string workflow markup to deserialize obj Output ListItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListItemType.Deserialize, SDC.ListItemType.LoadFromFile.
static bool SDC.ListItemType.Deserialize(string input, out ListItemType obj)
References SDC.null.
static new ListItemType SDC.ListItemType.Deserialize(string input)
References SDC.null.
static ListItemType SDC.ListItemType.Deserialize(System.IO.Stream s)
static bool SDC.ListItemType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ListItemType obj, out System.Exception exception)
Deserializes xml markup from file into an ListItemType object
fileName string xml file to load and deserialize obj Output ListItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListItemType.LoadFromFile.
static bool SDC.ListItemType.LoadFromFile(string fileName, out ListItemType obj, out System.Exception exception)
static bool SDC.ListItemType.LoadFromFile(string fileName, out ListItemType obj)
References SDC.null.
static ListItemType SDC.ListItemType.LoadFromFile(string fileName)
static new ListItemType SDC.ListItemType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ListItemType.Deserialize(string input, out ListItemType obj, out Exception exception)
Deserializes workflow markup into an ListItemType object
input string workflow markup to deserialize obj Output ListItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListItemType.Deserialize, SDC.null.
static bool SDC.ListItemType.Deserialize(string input, out ListItemType obj)
References SDC.ListItemType.Deserialize, SDC.null.
static new ListItemType SDC.ListItemType.Deserialize(string input)
References SDC.null, SDC.ListItemType.Serializer.
static ListItemType SDC.ListItemType.Deserialize(Stream s)
References SDC.ListItemType.Serializer.
static bool SDC.ListItemType.LoadFromFile(string fileName, out ListItemType obj, out Exception exception)
Deserializes xml markup from file into an ListItemType object
fileName string xml file to load and deserialize obj Output ListItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListItemType.LoadFromFile, SDC.null.
static bool SDC.ListItemType.LoadFromFile(string fileName, out ListItemType obj)
References SDC.ListItemType.LoadFromFile, SDC.null.
static new ListItemType SDC.ListItemType.LoadFromFile(string fileName)
References SDC.ListItemType.Deserialize, SDC.null.