SDC::CommentType
string SDC.CommentType::_val
ObjectChangeTracker SDC.CommentType.changeTrackerField
static XmlSerializer SDC.CommentType::serializer
string SDC.CommentType::val
Referenced by SDC.CommentType.ShouldSerializeval.
static XmlSerializer SDC.CommentType::Serializer
Referenced by SDC.CommentType.Deserialize.
ObjectChangeTracker SDC.CommentType.ChangeTracker
SDC.CommentType.CommentType()
SDC.CommentType.CommentType(BaseType parentNode)
SDC.CommentType.CommentType()
virtual bool SDC.CommentType.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.CommentType.Serialize(System.Text.Encoding encoding)
Serializes current CommentType object into an XML string
string XML value
virtual string SDC.CommentType.Serialize()
Referenced by SDC.CommentType.SaveToFile.
virtual bool SDC.CommentType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current CommentType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.CommentType.SaveToFile.
virtual bool SDC.CommentType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.CommentType.SaveToFile(string fileName)
virtual void SDC.CommentType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.CommentType.ShouldSerializeval()
Test whether val should be serialized
References SDC.CommentType.val.
virtual string SDC.CommentType.Serialize()
Serializes current CommentType object into an XML string
string XML value
virtual bool SDC.CommentType.SaveToFile(string fileName, out Exception exception)
Serializes current CommentType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.CommentType.SaveToFile.
virtual void SDC.CommentType.SaveToFile(string fileName)
References SDC.null, SDC.CommentType.Serialize.
virtual CommentType SDC.CommentType.Clone()
Create a clone of this CommentType object
static bool SDC.CommentType.Deserialize(string input, out CommentType obj, out System.Exception exception)
Deserializes workflow markup into an CommentType object
input string workflow markup to deserialize obj Output CommentType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CommentType.Deserialize, SDC.CommentType.LoadFromFile.
static bool SDC.CommentType.Deserialize(string input, out CommentType obj)
References SDC.null.
static new CommentType SDC.CommentType.Deserialize(string input)
References SDC.null.
static CommentType SDC.CommentType.Deserialize(System.IO.Stream s)
static bool SDC.CommentType.LoadFromFile(string fileName, System.Text.Encoding encoding, out CommentType obj, out System.Exception exception)
Deserializes xml markup from file into an CommentType object
fileName string xml file to load and deserialize obj Output CommentType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CommentType.LoadFromFile.
static bool SDC.CommentType.LoadFromFile(string fileName, out CommentType obj, out System.Exception exception)
static bool SDC.CommentType.LoadFromFile(string fileName, out CommentType obj)
References SDC.null.
static CommentType SDC.CommentType.LoadFromFile(string fileName)
static new CommentType SDC.CommentType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.CommentType.Deserialize(string input, out CommentType obj, out Exception exception)
Deserializes workflow markup into an CommentType object
input string workflow markup to deserialize obj Output CommentType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CommentType.Deserialize, SDC.null.
static bool SDC.CommentType.Deserialize(string input, out CommentType obj)
References SDC.CommentType.Deserialize, SDC.null.
static new CommentType SDC.CommentType.Deserialize(string input)
References SDC.null, SDC.CommentType.Serializer.
static CommentType SDC.CommentType.Deserialize(Stream s)
References SDC.CommentType.Serializer.
static bool SDC.CommentType.LoadFromFile(string fileName, out CommentType obj, out Exception exception)
Deserializes xml markup from file into an CommentType object
fileName string xml file to load and deserialize obj Output CommentType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CommentType.LoadFromFile, SDC.null.
static bool SDC.CommentType.LoadFromFile(string fileName, out CommentType obj)
References SDC.CommentType.LoadFromFile, SDC.null.
static new CommentType SDC.CommentType.LoadFromFile(string fileName)
References SDC.CommentType.Deserialize, SDC.null.