SDC::gDay_Stype
string SDC.gDay_Stype::_val
dtQuantEnum SDC.gDay_Stype::_quantEnum
Referenced by SDC.gDay_Stype.gDay_Stype.
ObjectChangeTracker SDC.gDay_Stype.changeTrackerField
static XmlSerializer SDC.gDay_Stype::serializer
string SDC.gDay_Stype::val
Referenced by SDC.gDay_Stype.ShouldSerializeval.
dtQuantEnum SDC.gDay_Stype::quantEnum
static XmlSerializer SDC.gDay_Stype::Serializer
Referenced by SDC.gDay_Stype.Deserialize.
ObjectChangeTracker SDC.gDay_Stype.ChangeTracker
SDC.gDay_Stype.gDay_Stype()
SDC.gDay_Stype.gDay_Stype(BaseType parentNode)
virtual bool SDC.gDay_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.gDay_Stype.val.
virtual string SDC.gDay_Stype.Serialize(System.Text.Encoding encoding)
Serializes current gDay_Stype object into an XML string
string XML value
virtual string SDC.gDay_Stype.Serialize()
Referenced by SDC.gDay_Stype.SaveToFile.
virtual bool SDC.gDay_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current gDay_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.gDay_Stype.SaveToFile.
virtual bool SDC.gDay_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.gDay_Stype.SaveToFile.
virtual void SDC.gDay_Stype.SaveToFile(string fileName)
References SDC.gDay_Stype.SaveToFile.
virtual void SDC.gDay_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.gDay_Stype.Serialize.
SDC.gDay_Stype.gDay_Stype()
gDay_Stype class constructor
References SDC.gDay_Stype._quantEnum.
virtual bool SDC.gDay_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.gDay_Stype.val.
virtual string SDC.gDay_Stype.Serialize()
Serializes current gDay_Stype object into an XML string
string XML value
virtual bool SDC.gDay_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current gDay_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.gDay_Stype.SaveToFile.
virtual void SDC.gDay_Stype.SaveToFile(string fileName)
References SDC.null, SDC.gDay_Stype.Serialize.
virtual gDay_Stype SDC.gDay_Stype.Clone()
Create a clone of this gDay_Stype object
static bool SDC.gDay_Stype.Deserialize(string input, out gDay_Stype obj, out System.Exception exception)
Deserializes workflow markup into an gDay_Stype object
input string workflow markup to deserialize obj Output gDay_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gDay_Stype.Deserialize, SDC.gDay_Stype.LoadFromFile.
static bool SDC.gDay_Stype.Deserialize(string input, out gDay_Stype obj)
References SDC.gDay_Stype.Deserialize, SDC.null.
static new gDay_Stype SDC.gDay_Stype.Deserialize(string input)
References SDC.null.
static gDay_Stype SDC.gDay_Stype.Deserialize(System.IO.Stream s)
References SDC.gDay_Stype.Serializer.
static bool SDC.gDay_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out gDay_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an gDay_Stype object
fileName string xml file to load and deserialize obj Output gDay_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gDay_Stype.LoadFromFile.
static bool SDC.gDay_Stype.LoadFromFile(string fileName, out gDay_Stype obj, out System.Exception exception)
References SDC.gDay_Stype.LoadFromFile.
static bool SDC.gDay_Stype.LoadFromFile(string fileName, out gDay_Stype obj)
References SDC.gDay_Stype.LoadFromFile, SDC.null.
static gDay_Stype SDC.gDay_Stype.LoadFromFile(string fileName)
References SDC.gDay_Stype.LoadFromFile.
static new gDay_Stype SDC.gDay_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.gDay_Stype.Deserialize, SDC.null.
static bool SDC.gDay_Stype.Deserialize(string input, out gDay_Stype obj, out Exception exception)
Deserializes workflow markup into an gDay_Stype object
input string workflow markup to deserialize obj Output gDay_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gDay_Stype.Deserialize, SDC.null.
static bool SDC.gDay_Stype.Deserialize(string input, out gDay_Stype obj)
References SDC.gDay_Stype.Deserialize, SDC.null.
static new gDay_Stype SDC.gDay_Stype.Deserialize(string input)
References SDC.null, SDC.gDay_Stype.Serializer.
static gDay_Stype SDC.gDay_Stype.Deserialize(Stream s)
References SDC.gDay_Stype.Serializer.
static bool SDC.gDay_Stype.LoadFromFile(string fileName, out gDay_Stype obj, out Exception exception)
Deserializes xml markup from file into an gDay_Stype object
fileName string xml file to load and deserialize obj Output gDay_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gDay_Stype.LoadFromFile, SDC.null.
static bool SDC.gDay_Stype.LoadFromFile(string fileName, out gDay_Stype obj)
References SDC.gDay_Stype.LoadFromFile, SDC.null.
static new gDay_Stype SDC.gDay_Stype.LoadFromFile(string fileName)
References SDC.gDay_Stype.Deserialize, SDC.null.