SDC::float_Stype
bool SDC.float_Stype::_shouldSerializeval
Referenced by SDC.float_Stype.ShouldSerializeval.
System Nullable< float > SDC.float_Stype::_val
Referenced by SDC.float_Stype.ShouldSerializeval.
dtQuantEnum SDC.float_Stype::_quantEnum
Referenced by SDC.float_Stype.float_Stype.
ObjectChangeTracker SDC.float_Stype.changeTrackerField
static XmlSerializer SDC.float_Stype::serializer
float SDC.float_Stype::val
bool SDC.float_Stype::valSpecified
dtQuantEnum SDC.float_Stype::quantEnum
static XmlSerializer SDC.float_Stype::Serializer
Referenced by SDC.float_Stype.Deserialize.
ObjectChangeTracker SDC.float_Stype.ChangeTracker
SDC.float_Stype.float_Stype()
SDC.float_Stype.float_Stype(BaseType parentNode)
virtual bool SDC.float_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.float_Stype._shouldSerializeval, SDC.float_Stype._val.
virtual string SDC.float_Stype.Serialize(System.Text.Encoding encoding)
Serializes current float_Stype object into an XML string
string XML value
virtual string SDC.float_Stype.Serialize()
Referenced by SDC.float_Stype.SaveToFile.
virtual bool SDC.float_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current float_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.float_Stype.SaveToFile.
virtual bool SDC.float_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.float_Stype.SaveToFile.
virtual void SDC.float_Stype.SaveToFile(string fileName)
References SDC.float_Stype.SaveToFile.
virtual void SDC.float_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.float_Stype.Serialize.
SDC.float_Stype.float_Stype()
float_Stype class constructor
References SDC.float_Stype._quantEnum.
virtual bool SDC.float_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.float_Stype._shouldSerializeval, SDC.float_Stype._val.
virtual string SDC.float_Stype.Serialize()
Serializes current float_Stype object into an XML string
string XML value
virtual bool SDC.float_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current float_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.float_Stype.SaveToFile.
virtual void SDC.float_Stype.SaveToFile(string fileName)
References SDC.null, SDC.float_Stype.Serialize.
virtual float_Stype SDC.float_Stype.Clone()
Create a clone of this float_Stype object
static bool SDC.float_Stype.Deserialize(string input, out float_Stype obj, out System.Exception exception)
Deserializes workflow markup into an float_Stype object
input string workflow markup to deserialize obj Output float_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.float_Stype.Deserialize, SDC.float_Stype.LoadFromFile.
static bool SDC.float_Stype.Deserialize(string input, out float_Stype obj)
References SDC.float_Stype.Deserialize, SDC.null.
static new float_Stype SDC.float_Stype.Deserialize(string input)
References SDC.null.
static float_Stype SDC.float_Stype.Deserialize(System.IO.Stream s)
References SDC.float_Stype.Serializer.
static bool SDC.float_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out float_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an float_Stype object
fileName string xml file to load and deserialize obj Output float_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.float_Stype.LoadFromFile.
static bool SDC.float_Stype.LoadFromFile(string fileName, out float_Stype obj, out System.Exception exception)
References SDC.float_Stype.LoadFromFile.
static bool SDC.float_Stype.LoadFromFile(string fileName, out float_Stype obj)
References SDC.float_Stype.LoadFromFile, SDC.null.
static float_Stype SDC.float_Stype.LoadFromFile(string fileName)
References SDC.float_Stype.LoadFromFile.
static new float_Stype SDC.float_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.float_Stype.Deserialize, SDC.null.
static bool SDC.float_Stype.Deserialize(string input, out float_Stype obj, out Exception exception)
Deserializes workflow markup into an float_Stype object
input string workflow markup to deserialize obj Output float_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.float_Stype.Deserialize, SDC.null.
static bool SDC.float_Stype.Deserialize(string input, out float_Stype obj)
References SDC.float_Stype.Deserialize, SDC.null.
static new float_Stype SDC.float_Stype.Deserialize(string input)
References SDC.null, SDC.float_Stype.Serializer.
static float_Stype SDC.float_Stype.Deserialize(Stream s)
References SDC.float_Stype.Serializer.
static bool SDC.float_Stype.LoadFromFile(string fileName, out float_Stype obj, out Exception exception)
Deserializes xml markup from file into an float_Stype object
fileName string xml file to load and deserialize obj Output float_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.float_Stype.LoadFromFile, SDC.null.
static bool SDC.float_Stype.LoadFromFile(string fileName, out float_Stype obj)
References SDC.float_Stype.LoadFromFile, SDC.null.
static new float_Stype SDC.float_Stype.LoadFromFile(string fileName)
References SDC.float_Stype.Deserialize, SDC.null.