SDC::NameType
string_Stype SDC.NameType::_namePrefix
Referenced by SDC.NameType.ShouldSerializeNamePrefix.
string_Stype SDC.NameType::_firstName
Referenced by SDC.NameType.ShouldSerializeFirstName.
string_Stype SDC.NameType::_middleName
Referenced by SDC.NameType.ShouldSerializeMiddleName.
string_Stype SDC.NameType::_lastName
Referenced by SDC.NameType.ShouldSerializeLastName.
string_Stype SDC.NameType::_nameSuffix
Referenced by SDC.NameType.ShouldSerializeNameSuffix.
List<string_Stype> SDC.NameType._degreeCert
string_Stype SDC.NameType::_title
Referenced by SDC.NameType.ShouldSerializeTitle.
BindingList<string_Stype> SDC.NameType._degreeCert
ObjectChangeTracker SDC.NameType.changeTrackerField
static XmlSerializer SDC.NameType::serializer
string_Stype SDC.NameType::NamePrefix
string_Stype SDC.NameType::FirstName
string_Stype SDC.NameType::MiddleName
string_Stype SDC.NameType::LastName
string_Stype SDC.NameType::NameSuffix
virtual List<string_Stype> SDC.NameType.DegreeCert
Acronyms for degrees and certifications, e.g., MD, PhD, FACP (repeat element for each acronym)
string_Stype SDC.NameType::Title
static XmlSerializer SDC.NameType::Serializer
Referenced by SDC.NameType.Deserialize.
virtual BindingList<string_Stype> SDC.NameType.DegreeCert
Acronyms for degrees and certifications, e.g., MD, PhD, FACP (repeat element for each acronym)
ObjectChangeTracker SDC.NameType.ChangeTracker
SDC.NameType.NameType()
SDC.NameType.NameType(BaseType parentNode)
virtual bool SDC.NameType.ShouldSerializeDegreeCert()
Test whether DegreeCert should be serialized
References SDC.null.
virtual bool SDC.NameType.ShouldSerializeNamePrefix()
Test whether NamePrefix should be serialized
References SDC.null.
virtual bool SDC.NameType.ShouldSerializeFirstName()
Test whether FirstName should be serialized
References SDC.null.
virtual bool SDC.NameType.ShouldSerializeMiddleName()
Test whether MiddleName should be serialized
References SDC.null.
virtual bool SDC.NameType.ShouldSerializeLastName()
Test whether LastName should be serialized
References SDC.null.
virtual bool SDC.NameType.ShouldSerializeNameSuffix()
Test whether NameSuffix should be serialized
References SDC.null.
virtual bool SDC.NameType.ShouldSerializeTitle()
Test whether Title should be serialized
References SDC.null.
virtual string SDC.NameType.Serialize(System.Text.Encoding encoding)
Serializes current NameType object into an XML string
string XML value
virtual string SDC.NameType.Serialize()
Referenced by SDC.NameType.SaveToFile.
virtual bool SDC.NameType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current NameType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.NameType.SaveToFile.
virtual bool SDC.NameType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.NameType.SaveToFile(string fileName)
virtual void SDC.NameType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.NameType.ShouldSerializeNamePrefix()
Test whether NamePrefix should be serialized
References SDC.NameType._namePrefix, SDC.null.
virtual bool SDC.NameType.ShouldSerializeFirstName()
Test whether FirstName should be serialized
References SDC.NameType._firstName, SDC.null.
virtual bool SDC.NameType.ShouldSerializeMiddleName()
Test whether MiddleName should be serialized
References SDC.NameType._middleName, SDC.null.
virtual bool SDC.NameType.ShouldSerializeLastName()
Test whether LastName should be serialized
References SDC.NameType._lastName, SDC.null.
virtual bool SDC.NameType.ShouldSerializeNameSuffix()
Test whether NameSuffix should be serialized
References SDC.NameType._nameSuffix, SDC.null.
virtual bool SDC.NameType.ShouldSerializeTitle()
Test whether Title should be serialized
References SDC.NameType._title, SDC.null.
virtual string SDC.NameType.Serialize()
Serializes current NameType object into an XML string
string XML value
virtual bool SDC.NameType.SaveToFile(string fileName, out Exception exception)
Serializes current NameType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.NameType.SaveToFile.
virtual void SDC.NameType.SaveToFile(string fileName)
References SDC.null, SDC.NameType.Serialize.
virtual NameType SDC.NameType.Clone()
Create a clone of this NameType object
static bool SDC.NameType.Deserialize(string input, out NameType obj, out System.Exception exception)
Deserializes workflow markup into an NameType object
input string workflow markup to deserialize obj Output NameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.NameType.Deserialize, SDC.NameType.LoadFromFile.
static bool SDC.NameType.Deserialize(string input, out NameType obj)
References SDC.null.
static new NameType SDC.NameType.Deserialize(string input)
References SDC.null.
static NameType SDC.NameType.Deserialize(System.IO.Stream s)
static bool SDC.NameType.LoadFromFile(string fileName, System.Text.Encoding encoding, out NameType obj, out System.Exception exception)
Deserializes xml markup from file into an NameType object
fileName string xml file to load and deserialize obj Output NameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.NameType.LoadFromFile.
static bool SDC.NameType.LoadFromFile(string fileName, out NameType obj, out System.Exception exception)
static bool SDC.NameType.LoadFromFile(string fileName, out NameType obj)
References SDC.null.
static NameType SDC.NameType.LoadFromFile(string fileName)
static new NameType SDC.NameType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.NameType.Deserialize(string input, out NameType obj, out Exception exception)
Deserializes workflow markup into an NameType object
input string workflow markup to deserialize obj Output NameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.NameType.Deserialize, SDC.null.
static bool SDC.NameType.Deserialize(string input, out NameType obj)
References SDC.NameType.Deserialize, SDC.null.
static new NameType SDC.NameType.Deserialize(string input)
References SDC.null, SDC.NameType.Serializer.
static NameType SDC.NameType.Deserialize(Stream s)
References SDC.NameType.Serializer.
static bool SDC.NameType.LoadFromFile(string fileName, out NameType obj, out Exception exception)
Deserializes xml markup from file into an NameType object
fileName string xml file to load and deserialize obj Output NameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.NameType.LoadFromFile, SDC.null.
static bool SDC.NameType.LoadFromFile(string fileName, out NameType obj)
References SDC.NameType.LoadFromFile, SDC.null.
static new NameType SDC.NameType.LoadFromFile(string fileName)
References SDC.NameType.Deserialize, SDC.null.