SDC::SDCTreeBuilderEcc
override RulesType SDC.SDCTreeBuilderEcc.AddRuleToDisplayedType(DisplayedType parent)
+Rules
References SDC.RulesType.
override BaseType SDC.SDCTreeBuilderEcc.FillBaseTypeItemData(BaseType bt)
References SDC.SDCTreeBuilderEcc.CreateName, SDC.SDCTreeBuilder.drFormDesign, SDC.SDCTreeBuilderEcc.GetEccRowTypeEnum, SDC.BaseType.NodeType, SDC.string, SDC.var.
string SDC.SDCTreeBuilderEcc.CreateName(BaseType bt)
If an Identified ancestor (the closest ancestor with an IdentifiedExtensionType) has a name, then we can it's name and ID to name non-repeating child elements such as ResponseField
prefix prefix iindicating the type of object to name. The default is "BT" for BaseType bt an object of type BaseType
Referenced by SDC.SDCTreeBuilderEcc.FillBaseTypeItemData, SDC.SDCTreeBuilderEcc.FillProperty.
override CommentType SDC.SDCTreeBuilderEcc.FillCommentData(BaseType bt, string comment)
References SDC.CommentType, SDC.null.
override SectionItemType SDC.SDCTreeBuilderEcc.FillSection(SectionItemType s)
References SDC.SDCTreeBuilderEcc.FillSectionBase.
override CodingType SDC.SDCTreeBuilderEcc.FillCodedValue(DisplayedType dt)
override AddressType SDC.SDCTreeBuilderEcc.FillAddress(AddressType at)
override ContactType SDC.SDCTreeBuilderEcc.FillContact(ContactType ct)
override string SDC.SDCTreeBuilderEcc.FillPersonAddress1(string ot)
override string SDC.SDCTreeBuilderEcc.FillPersonAddress2(string ot)
override string SDC.SDCTreeBuilderEcc.FillPersonAddress3(string ot)
override string SDC.SDCTreeBuilderEcc.FillPersonAddress4(string ot)
override EmailType SDC.SDCTreeBuilderEcc.FillPersonEmail(EmailType ot)
override IdentifierType SDC.SDCTreeBuilderEcc.FillPersonIdentifier(IdentifierType ot)
override JobType SDC.SDCTreeBuilderEcc.FillPersonJob(JobType pt)
override NameType SDC.SDCTreeBuilderEcc.FillPersonName(PersonType pt)
override PhoneType SDC.SDCTreeBuilderEcc.FillPersonPhone(PhoneType ot)
override string_Stype SDC.SDCTreeBuilderEcc.FillPersonUsage(string_Stype ut)
override string SDC.SDCTreeBuilderEcc.FillPersonWebURL(string ot)
override DataTypes_DEType SDC.SDCTreeBuilderEcc.AddFillDataTypesDE(ListFieldType lft, SectionBaseTypeResponseTypeEnum dataType)
override DataTypes_DEType SDC.SDCTreeBuilderEcc.AddFillDataTypesDE(ResponseFieldType rfParent)
References SDC.anyType_DEtype, SDC.anyURI_DEtype, SDC.SDCTreeBuilder.AssignQuantifier, SDC.base64Binary_DEtype, SDC.boolean_DEtype, SDC.byte, SDC.byte_DEtype, SDC.DataTypes_DEType.DataTypeDE_Item, SDC.DataTypes_DEType, SDC.date_DEtype, SDC.dateTime, SDC.dateTime_DEtype, SDC.dateTimeStamp, SDC.dateTimeStamp_DEtype, SDC.decimal, SDC.decimal_DEtype, SDC.double, SDC.double_DEtype, SDC.SDCTreeBuilder.drFormDesign, SDC.duration_DEtype, SDC.SDCTreeBuilder.FillBaseTypeItem, SDC.float, SDC.float_DEtype, SDC.gDay_DEtype, SDC.gMonth_DEtype, SDC.gMonthDay_DEtype, SDC.gYear_DEtype, SDC.gYearMonth_DEtype, SDC.hexBinary_DEtype, SDC.HTML_DEtype, SDC.int, SDC.int_DEtype, SDC.integer_DEtype, SDC.long, SDC.long_DEtype, SDC.negativeInteger_DEtype, SDC.nonNegativeInteger_DEtype, SDC.nonPositiveInteger_DEtype, SDC.positiveInteger_DEtype, SDC.ResponseFieldType.Response, SDC.short, SDC.short_DEtype, SDC.string, SDC.string_DEtype, SDC.time_DEtype, SDC.unsignedByte_DEtype, SDC.unsignedInt_DEtype, SDC.unsignedLong_DEtype, SDC.unsignedShort_DEtype, SDC.var, SDC.XML_DEtype, SDC.yearMonthDuration_DEtype.
override DataTypes_SType SDC.SDCTreeBuilderEcc.AddFillDataTypesS(CodingType coding)
override FuncType SDC.SDCTreeBuilderEcc.AddFillWebService(LookupEndPointType lep, Boolean fillData=true)
override string SDC.SDCTreeBuilderEcc.FillQuantifier()
References SDC.SDCTreeBuilder.drFormDesign, SDC.string.
override FuncType SDC.SDCTreeBuilderEcc.FillWebService(FuncType wst)
override WatchedPropertyType SDC.SDCTreeBuilderEcc.FillActivateIf(WatchedPropertyType oe)
override WatchedPropertyType SDC.SDCTreeBuilderEcc.FillDeActivateIf(WatchedPropertyType oe)
override IfThenType SDC.SDCTreeBuilderEcc.FillOnEnter(IfThenType oe)
override IfThenType SDC.SDCTreeBuilderEcc.FillOnEvent(IfThenType oe)
override OnEventType SDC.SDCTreeBuilderEcc.FillOnExit(OnEventType oe)
PropertyType SDC.SDCTreeBuilderEcc.AddPropertyAltText(DisplayedType parent)
References SDC.SDCTreeBuilder.AddProperty, SDC.SDCTreeBuilder.drFormDesign, SDC.var.
PropertyType SDC.SDCTreeBuilderEcc.AddPropertyDescription(DisplayedType parent)
References SDC.SDCTreeBuilder.AddProperty, SDC.SDCTreeBuilder.drFormDesign, SDC.var.
PropertyType SDC.SDCTreeBuilderEcc.AddPropertyInstruction(DisplayedType parent)
References SDC.SDCTreeBuilder.AddProperty, SDC.SDCTreeBuilder.drFormDesign, SDC.var.
PropertyType SDC.SDCTreeBuilderEcc.AddPropertyPopupText(DisplayedType parent)
References SDC.SDCTreeBuilder.AddProperty, SDC.SDCTreeBuilder.drFormDesign, SDC.var.
PropertyType SDC.SDCTreeBuilderEcc.AddPropertyReportText(DisplayedType parent)
References SDC.SDCTreeBuilder.AddProperty, SDC.SDCTreeBuilder.drFormDesign, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.FillDisplayedTypeItemData.
PropertyType SDC.SDCTreeBuilderEcc.AddPropertyShortText(DisplayedType parent)
References SDC.SDCTreeBuilder.AddProperty, SDC.SDCTreeBuilder.drFormDesign, SDC.var.
PropertyType SDC.SDCTreeBuilderEcc.AddPropertySpanishText(DisplayedType parent)
References SDC.SDCTreeBuilder.AddProperty, SDC.SDCTreeBuilder.drFormDesign, SDC.var.
PropertyType SDC.SDCTreeBuilderEcc.AddPropertyTooltip(DisplayedType parent)
References SDC.SDCTreeBuilder.AddProperty, SDC.SDCTreeBuilder.drFormDesign, SDC.var.
override string SDC.SDCTreeBuilderEcc.FillOrgAddress1(string ot)
override string SDC.SDCTreeBuilderEcc.FillOrgAddress2(string ot)
override string SDC.SDCTreeBuilderEcc.FillOrgAddress3(string ot)
override string SDC.SDCTreeBuilderEcc.FillOrgAddress4(string ot)
override string SDC.SDCTreeBuilderEcc.FillOrgDept(string ot)
override EmailType SDC.SDCTreeBuilderEcc.FillOrgEmail(EmailType et)
override IdentifierType SDC.SDCTreeBuilderEcc.FillOrgIdentifier(IdentifierType ot)
override NameType SDC.SDCTreeBuilderEcc.FillOrgName(PersonType pt)
override string_Stype SDC.SDCTreeBuilderEcc.FillOrgName(string_Stype ot)
override PhoneType SDC.SDCTreeBuilderEcc.FillOrgPhone(PhoneType ot)
override string SDC.SDCTreeBuilderEcc.FillOrgRole(string rt)
override string SDC.SDCTreeBuilderEcc.FillOrgUsage(string ut)
override anyURI_Stype SDC.SDCTreeBuilderEcc.FillOrgWebURL(anyURI_Stype wt)
override DisplayedType SDC.SDCTreeBuilderEcc.FillDisplayedTypeListItemData(DisplayedType di, string title, QuestionItemType qNode)
References SDC.DisplayedType.mustImplement, SDC.var.
override ResponseFieldType SDC.SDCTreeBuilderEcc.FillResponseField(ResponseFieldType rf)
+Create Response Items
References SDC.SDCTreeBuilder.drFormDesign, SDC.Empty, SDC.RichTextType, SDC.string.
Referenced by SDC.SDCTreeBuilderEcc.FillListItemResponseField.
override UnitsType SDC.SDCTreeBuilderEcc.AddFillResponseUnits(ResponseFieldType rf, Boolean fillData=true)
References SDC.SDCTreeBuilder.drFormDesign, SDC.Empty, SDC.null, SDC.string, SDC.UnitsType.
Referenced by SDC.SDCTreeBuilderEcc.FillListItemResponseField.
override ItemType SDC.SDCTreeBuilderEcc.GetRowType(string strRowType)
SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc(string CTV_Ckey, IFormDesignDataSets dataSets, string xsltPath="")
References SDC.SDCTreeBuilderEcc.AddFillFormDesignProperties, SDC.SDCTreeBuilderEcc.CreateFooter, SDC.SDCTreeBuilder.CreateFormDesignTree, SDC.decimal.
override ActSendMessageType SDC.SDCTreeBuilderEcc.AddFillActSendMessage(ThenType tt, Boolean fillData=true)
References SDC.ActSendMessageType, SDC.SDCTreeBuilder.drFormDesign, SDC.ThenType.Items, SDC.null, SDC.string, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
override ActActionType SDC.SDCTreeBuilderEcc.AddAction(ThenType tt, Boolean fillData=true)
override ActAddCodeType SDC.SDCTreeBuilderEcc.AddAddCode(ThenType tt, Boolean fillData=true)
override ActInjectType SDC.SDCTreeBuilderEcc.AddInject(ThenType tt, Boolean fillData=true)
References SDC.ActInjectType.
override ActShowMessageType SDC.SDCTreeBuilderEcc.AddShowMessage(ThenType tt, Boolean fillData=true)
References SDC.ActShowMessageType.
override FuncType SDC.SDCTreeBuilderEcc.AddShowURL(ThenType tt, Boolean fillData=true)
override ActShowFormType SDC.SDCTreeBuilderEcc.AddShowForm(ThenType tt, Boolean fillData=true)
References SDC.ActShowFormType.
override ActSaveResponsesType SDC.SDCTreeBuilderEcc.AddSave(ThenType tt, Boolean fillData=true)
References SDC.ActSaveResponsesType.
override ActSendReportType SDC.SDCTreeBuilderEcc.AddShowReport(ThenType tt, Boolean fillData=true)
References SDC.ActSendReportType.
override ActSendMessageType SDC.SDCTreeBuilderEcc.AddSendMessage(ThenType tt, Boolean fillData=true)
References SDC.ActSendMessageType.
override ActValidateFormType SDC.SDCTreeBuilderEcc.AddValidateForm(ThenType tt, Boolean fillData=true)
References SDC.ActValidateFormType.
override IfThenType SDC.SDCTreeBuilderEcc.AddIfThen(ThenType tt, Boolean fillData=true)
References SDC.IfThenType.
override ItemNameType SDC.SDCTreeBuilderEcc.AddCallIfThen(ThenType tt, Boolean fillData=true)
References SDC.ItemNameType.
override DisplayedType SDC.SDCTreeBuilderEcc.FillDisplayedTypeItemData(DisplayedType dt)
References SDC.SDCTreeBuilderEcc.AddPropertyReportText, SDC.SDCTreeBuilder.drFormDesign, SDC.string, SDC.var.
override IdentifiedExtensionType SDC.SDCTreeBuilderEcc.FillIdentifiedTypeItemData(IdentifiedExtensionType iet)
References SDC.SDCTreeBuilder.drFormDesign.
override RepeatingType SDC.SDCTreeBuilderEcc.FillRepeatingTypeItemData(RepeatingType rt)
References SDC.SDCTreeBuilder.drFormDesign, SDC.RepeatingType.minCard, SDC.DisplayedType.title, SDC.var.
override InjectFormType SDC.SDCTreeBuilderEcc.AddInjectedForm< T >(T T_Parent, Boolean fillData=true, string id=null)
References SDC.SDCTreeBuilder.AddFillExtensionBaseTypeItems, SDC.SDCTreeBuilder.drFormDesign, SDC.InjectFormType, SDC.string, SDC.var.
override ButtonItemType SDC.SDCTreeBuilderEcc.FillButton(ButtonItemType button)
override InjectFormType SDC.SDCTreeBuilderEcc.FillInjectedForm(InjectFormType injForm)
References SDC.SDCTreeBuilder.drFormDesign, SDC.string.
override SectionBaseType SDC.SDCTreeBuilderEcc.FillSectionBase(SectionBaseType s)
References SDC.SDCTreeBuilder.drFormDesign.
Referenced by SDC.SDCTreeBuilderEcc.FillSection.
override CodingType SDC.SDCTreeBuilderEcc.AddCodedValue(DisplayedType dt, Boolean fillData=true)
References SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilder.AddFillCodeSystem, SDC.SDCTreeBuilderEcc.AddFillHTML, SDC.CodeMatchType, SDC.CodingType, SDC.SDCTreeBuilder.drFormDesign, SDC.RichTextType, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems.
override CodingType SDC.SDCTreeBuilderEcc.AddCodedValue(LookupEndPointType lep, Boolean fillData=true)
Handles Response derived from a LookupEndpoint
lep LookupEndPointType dr DataRow
References SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilder.AddFillCodeSystem, SDC.SDCTreeBuilderEcc.AddFillHTML, SDC.CodeMatchType, SDC.CodingType, SDC.SDCTreeBuilder.drFormDesign, SDC.RichTextType, SDC.string, SDC.var.
override CodeSystemType SDC.SDCTreeBuilderEcc.FillCodeSystemItems(CodeSystemType cs)
References SDC.SDCTreeBuilder.drFormDesign, SDC.string.
override AddressType SDC.SDCTreeBuilderEcc.AddFillAddress(OrganizationType ot, Boolean fillData=true)
Referenced by SDC.SDCTreeBuilderEcc.AddFillOrganizationItems.
override AddressType SDC.SDCTreeBuilderEcc.AddFillAddress(PersonType pt, Boolean fillData=true)
override OrganizationType SDC.SDCTreeBuilderEcc.AddFillOrganizationItems(OrganizationType ot, Boolean fillData=true)
References SDC.SDCTreeBuilder.AddContactPerson, SDC.SDCTreeBuilderEcc.AddFillAddress, SDC.anyURI_Stype, SDC.SDCTreeBuilder.drFormDesign, SDC.EmailType, SDC.IdentifierType, SDC.PhoneNumberType, SDC.PhoneType, SDC.string, SDC.string_Stype, SDC.var.
override ExtensionType SDC.SDCTreeBuilderEcc.AddFillExtension(ExtensionBaseType parent, Boolean fillData=true, string inXML="")
References SDC.SDCTreeBuilder.drFormDesign, SDC.Empty, SDC.ExtensionBaseType.Extension, SDC.ExtensionType, SDC.null, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.CreateStaticExtension.
override HTML_Stype SDC.SDCTreeBuilderEcc.AddFillHTML(RichTextType rt, Boolean fillData=true, string InXhtml="")
References SDC.SDCTreeBuilder.drFormDesign, SDC.Empty, SDC.HTML_Stype, SDC.null, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddCodedValue, SDC.SDCTreeBuilderEcc.FillBlob, SDC.SDCTreeBuilderEcc.FillLinkText.
override WatchedPropertyType SDC.SDCTreeBuilderEcc.AddActivateIf(DisplayedType dt, Boolean fillData=true)
override WatchedPropertyType SDC.SDCTreeBuilderEcc.AddDeActivateIf(DisplayedType dt, Boolean fillData=true)
override IfThenType SDC.SDCTreeBuilderEcc.AddOnEnter(DisplayedType dt, Boolean fillData=true)
override IfThenType SDC.SDCTreeBuilderEcc.AddOnEvent(DisplayedType dt, Boolean fillData=true)
override OnEventType SDC.SDCTreeBuilderEcc.AddOnExit(DisplayedType dt, Boolean fillData=true)
override PropertyType SDC.SDCTreeBuilderEcc.FillProperty(PropertyType pt, Boolean fillData=true)
References SDC.SDCTreeBuilderEcc.CreateName.
override BlobType SDC.SDCTreeBuilderEcc.FillBlob(BlobType blob)
References SDC.SDCTreeBuilderEcc.AddFillHTML, SDC.anyURI_Stype, SDC.base64Binary_DEtype, SDC.BlobType.Description, SDC.SDCTreeBuilder.drFormDesign, SDC.null, SDC.RichTextType, SDC.string, SDC.var.
override LinkType SDC.SDCTreeBuilderEcc.FillLinkText(LinkType link)
References SDC.SDCTreeBuilderEcc.AddFillHTML, SDC.anyURI_Stype, SDC.SDCTreeBuilder.drFormDesign, SDC.LinkType.LinkText, SDC.null, SDC.RichTextType, SDC.string, SDC.var.
override QuestionItemBaseType SDC.SDCTreeBuilderEcc.FillQuestionItemBase(QuestionItemBaseType q)
References SDC.SDCTreeBuilder.drFormDesign.
override ListItemBaseType SDC.SDCTreeBuilderEcc.FillListItemBase(ListItemBaseType li)
References SDC.SDCTreeBuilderEcc.AddListItemResponseField, SDC.SDCTreeBuilder.drFormDesign, SDC.int, SDC.string, SDC.DisplayedType.title, SDC.var.
override ListFieldType SDC.SDCTreeBuilderEcc.FillListField(ListFieldType lf)
References SDC.SDCTreeBuilder.drFormDesign.
override LookupEndPointType SDC.SDCTreeBuilderEcc.FillLookupEndpoint(LookupEndPointType lep)
References SDC.SDCTreeBuilder.drFormDesign, SDC.FuncType.Items, SDC.null, SDC.LookupEndPointType.ResponseValue, SDC.RichTextType, SDC.var.
override ListItemResponseFieldType SDC.SDCTreeBuilderEcc.FillListItemResponseField(ListItemResponseFieldType liRF)
References SDC.SDCTreeBuilderEcc.AddFillResponseUnits, SDC.SDCTreeBuilder.drFormDesign, SDC.SDCTreeBuilderEcc.FillResponseField, SDC.ListItemType, SDC.BaseType.ParentNode, SDC.var.
override UnitsType SDC.SDCTreeBuilderEcc.FillUnits(UnitsType ut)
References SDC.SDCTreeBuilder.drFormDesign.
override QuestionEnum SDC.SDCTreeBuilderEcc.GetEccQuestionTypeEnum(string strRowType)
override ItemTypeEnum SDC.SDCTreeBuilderEcc.GetEccRowTypeEnum(string strRowType)
override String SDC.SDCTreeBuilderEcc.GetTemplateByCkey(String formDesignID, out String BESTfilename, String USERfilename="")
Gets template by Ckey
formDesignID Ckey of template to get BESTfilename The preferred file name. Use USERfilename in preference to the Database supplied filename USERfilename The preferred filename, if available Template XML
References SDC.Empty, SDC.SDCTreeBuilderEcc.SerializeFormDesignTree.
SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc(string formDesignID, IFormDesignDataSets dataSets, string xsltPath="")
References SDC.SDCTreeBuilder.CreateFormDesignTree, SDC.decimal, SDC.SDCTreeBuilder.dtFormDesign, SDC.SDCTreeBuilder.dtHeaderDesign, SDC.SDCTreeBuilder.FormDesign, SDC.SDCTreeBuilder.FormDesignID, SDC.FormDesignType, SDC.var, SDC.SDCTreeBuilder.XsltFileName.
override String SDC.SDCTreeBuilderEcc.GetTemplateByCkey(String formDesignID, out String BESTfilename, String USERfilename="")
Gets template by Ckey
formDesignID Ckey of template to get BESTfilename The preferred file name. Use USERfilename in preference to the Database supplied filename USERfilename The preferred filename, if available Template XML
References SDC.Empty, SDC.SDCTreeBuilderEcc.SerializeFormDesignTree, SDC.Trim.
override String SDC.SDCTreeBuilderEcc.SerializeFormDesignTree()
Creates template with information from data tables
templateVersion Data table with information about the template version templateItems Data table with information about the template items templateProcedures Data table with information about the template procedures Template Xml
References SDC.SDCTreeBuilder.FormDesign, SDC.null, SDC.var, SDC.SDCTreeBuilder.XsltFileName.
Referenced by SDC.SDCTreeBuilderEcc.GetTemplateByCkey.
override void SDC.SDCTreeBuilderEcc.AddTemplateMetadataToForm(IdentifiedExtensionType n, DisplayedType parentNode)
override RepeatingType SDC.SDCTreeBuilderEcc.AddRepeatingTypeItems(RepeatingType rt)
Base type functions.
References SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems, SDC.SDCTreeBuilder.drFormDesign.
Referenced by SDC.SDCTreeBuilderEcc.AddQuestion< T >.
override DisplayedType SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems(DisplayedType dt)
References SDC.SDCTreeBuilderEcc.AddBlob, SDC.SDCTreeBuilderEcc.AddCodedValue, SDC.SDCTreeBuilder.AddContact, SDC.SDCTreeBuilderEcc.AddIdentifiedTypeItems, SDC.SDCTreeBuilderEcc.AddLink, SDC.SDCTreeBuilder.AddOtherText, SDC.SDCTreeBuilder.drFormDesign, SDC.string.
Referenced by SDC.SDCTreeBuilderEcc.AddRepeatingTypeItems.
override IdentifiedExtensionType SDC.SDCTreeBuilderEcc.AddIdentifiedTypeItems(IdentifiedExtensionType iet)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.drFormDesign, SDC.string.
Referenced by SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems.
override IdentifiedExtensionType SDC.SDCTreeBuilderEcc.AddBaseTypeItems(IdentifiedExtensionType bt)
References SDC.decimal, SDC.SDCTreeBuilder.drFormDesign, SDC.string.
Referenced by SDC.SDCTreeBuilderEcc.AddDataTypesDE.
override CommentType SDC.SDCTreeBuilderEcc.AddComment(ExtensionBaseType ebt)
References SDC.ExtensionBaseType.Comment, SDC.CommentType, SDC.SDCTreeBuilder.drFormDesign, SDC.null, SDC.string, SDC.var.
override ExtensionType SDC.SDCTreeBuilderEcc.AddExtension(ExtensionBaseType ebt)
References SDC.e, SDC.ExtensionBaseType.Extension, SDC.ExtensionType, SDC.null, SDC.var.
override HTML_Stype SDC.SDCTreeBuilderEcc.AddHTML(RichTextType rtf)
References SDC.SDCTreeBuilder.drFormDesign, SDC.HTML_Stype, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddBlob, SDC.SDCTreeBuilderEcc.AddCodedValue, SDC.SDCTreeBuilderEcc.AddLink.
override WebServiceType SDC.SDCTreeBuilderEcc.AddWebService(LookupEndPointType lep)
override DataTypes_SType SDC.SDCTreeBuilderEcc.AddDataTypesS(CodingType coding)
override DataTypes_DEType SDC.SDCTreeBuilderEcc.AddDataTypesDE(ResponseFieldType RF)
References SDC.SDCTreeBuilderEcc.AddBaseTypeItems, SDC.anyType_DEtype, SDC.anyURI_DEtype, SDC.SDCTreeBuilder.AssignQuantifier, SDC.base64Binary_DEtype, SDC.boolean_DEtype, SDC.byte, SDC.byte_DEtype, SDC.DataTypes_DEType, SDC.date_DEtype, SDC.dateTime_DEtype, SDC.dateTimeStamp_DEtype, SDC.decimal, SDC.decimal_DEtype, SDC.double, SDC.double_DEtype, SDC.SDCTreeBuilder.drFormDesign, SDC.duration_DEtype, SDC.float, SDC.float_DEtype, SDC.gDay_DEtype, SDC.gMonth_DEtype, SDC.gMonthDay_DEtype, SDC.gYear_DEtype, SDC.gYearMonth_DEtype, SDC.hexBinary_DEtype, SDC.HTML_DEtype, SDC.int, SDC.int_DEtype, SDC.integer_DEtype, SDC.DataTypes_DEType.Item, SDC.long, SDC.long_DEtype, SDC.negativeInteger_DEtype, SDC.nonNegativeInteger_DEtype, SDC.nonPositiveInteger_DEtype, SDC.positiveInteger_DEtype, SDC.ResponseFieldType.Response, SDC.short, SDC.short_DEtype, SDC.string, SDC.string_DEtype, SDC.time_DEtype, SDC.unsignedByte_DEtype, SDC.unsignedInt_DEtype, SDC.unsignedLong_DEtype, SDC.unsignedShort_DEtype, SDC.var, SDC.XML_DEtype, SDC.yearMonthDuration_DEtype.
Referenced by SDC.SDCTreeBuilderEcc.CreateStaticQF< T >.
override DataTypes_DEType SDC.SDCTreeBuilderEcc.AddDataTypesDE(ListFieldType lft, QuestionItemBaseTypeResponseTypeEnum dataType)
override AddressType SDC.SDCTreeBuilderEcc.AddAddress(PersonType pt)
Referenced by SDC.SDCTreeBuilderEcc.AddOrganizationItems.
override AddressType SDC.SDCTreeBuilderEcc.AddAddress(OrganizationType ot)
override PersonType SDC.SDCTreeBuilderEcc.AddPersonItems(PersonType pt)
References SDC.SDCTreeBuilder.drFormDesign, SDC.EmailType, SDC.NameType, SDC.string, SDC.string_Stype, SDC.var.
override NameType SDC.SDCTreeBuilderEcc.AddPersonName(PersonType pt)
override JobType SDC.SDCTreeBuilderEcc.AddJob(PersonType pt)
override EmailType SDC.SDCTreeBuilderEcc.AddEmail(OrganizationType ot)
override EmailType SDC.SDCTreeBuilderEcc.AddEmail(PersonType pt)
override PhoneType SDC.SDCTreeBuilderEcc.AddPhone(OrganizationType ot)
override PhoneType SDC.SDCTreeBuilderEcc.AddPhone(PersonType ot)
override IdentifierType SDC.SDCTreeBuilderEcc.AddIdentifier(OrganizationType ot)
override anyURI_Stype SDC.SDCTreeBuilderEcc.AddWebURL(OrganizationType ot)
override OrganizationType SDC.SDCTreeBuilderEcc.AddOrganizationItems(OrganizationType ot)
References SDC.SDCTreeBuilderEcc.AddAddress, SDC.SDCTreeBuilder.AddContactPerson, SDC.SDCTreeBuilder.drFormDesign, SDC.EmailType, SDC.IdentifierType, SDC.PhoneNumberType, SDC.PhoneType, SDC.string, SDC.string_Stype, SDC.var.
override QuestionItemType SDC.SDCTreeBuilderEcc.AddQuestion< T >(T T_Parent, ItemType qType)
References SDC.SDCTreeBuilder.AddListFieldToQuestion, SDC.SDCTreeBuilderEcc.AddRepeatingTypeItems, SDC.SDCTreeBuilderEcc.AddResponseField, SDC.SDCTreeBuilder.drFormDesign, SDC.QuestionItemType, SDC.var.
override InjectFormType SDC.SDCTreeBuilderEcc.AddInjectedForm< T >(T T_Parent)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.drFormDesign, SDC.InjectFormType, SDC.string, SDC.var.
override LinkType SDC.SDCTreeBuilderEcc.AddLink(DisplayedType dt)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilderEcc.AddHTML, SDC.anyURI_Stype, SDC.SDCTreeBuilder.drFormDesign, SDC.DisplayedType.Link, SDC.LinkType, SDC.null, SDC.RichTextType, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems.
override BlobType SDC.SDCTreeBuilderEcc.AddBlob(DisplayedType dt)
References SDC.SDCTreeBuilderEcc.AddHTML, SDC.anyURI_Stype, SDC.base64Binary_DEtype, SDC.BlobType, SDC.SDCTreeBuilder.drFormDesign, SDC.RichTextType, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddDisplayedTypeItems.
override IfThenType SDC.SDCTreeBuilderEcc.AddOnEvent(DisplayedType dt)
override IfThenType SDC.SDCTreeBuilderEcc.AddOnEnter(DisplayedType dt)
override OnEventType SDC.SDCTreeBuilderEcc.AddOnExit(DisplayedType dt)
override WatchedPropertyType SDC.SDCTreeBuilderEcc.AddActivateIf(DisplayedType dt)
override WatchedPropertyType SDC.SDCTreeBuilderEcc.AddDeActivateIf(DisplayedType dt)
override CodeSystemType SDC.SDCTreeBuilderEcc.AddCodeSystemItems(CodeSystemType cs)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.drFormDesign, SDC.string.
override CodingType SDC.SDCTreeBuilderEcc.AddCodedValue(DisplayedType dt)
References SDC.SDCTreeBuilder.AddCodeSystem, SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilderEcc.AddHTML, SDC.CodeMatchType, SDC.CodingType, SDC.SDCTreeBuilder.drFormDesign, SDC.RichTextType, SDC.string, SDC.var.
override CodingType SDC.SDCTreeBuilderEcc.AddCodedValue(LookupEndPointType lep)
Handles Response derived from a LookupEndpoint
lep LookupEndPointType dr DataRow
References SDC.SDCTreeBuilder.AddCodeSystem, SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilderEcc.AddHTML, SDC.CodeMatchType, SDC.CodingType, SDC.SDCTreeBuilder.drFormDesign, SDC.RichTextType, SDC.string, SDC.var.
override void SDC.SDCTreeBuilderEcc.AddListItemProperties(ListItemType li)
+List
override DisplayedType SDC.SDCTreeBuilderEcc.AddListMemberToQuestion(QuestionItemType qNode)
References SDC.SDCTreeBuilder.AddDisplayedItemToList, SDC.SDCTreeBuilder.AddListFieldToQuestion, SDC.SDCTreeBuilder.AddListItemToList, SDC.SDCTreeBuilder.AddListToListField, SDC.SDCTreeBuilder.drFormDesign, SDC.int, SDC.QuestionItemBaseType.ListField_Item, SDC.null, SDC.var.
override ResponseFieldType SDC.SDCTreeBuilderEcc.AddResponseField(QuestionItemType q)
+Create Response Items
Referenced by SDC.SDCTreeBuilderEcc.AddQuestion< T >.
override ListItemResponseFieldType SDC.SDCTreeBuilderEcc.AddListItemResponseField(ListItemType li)
References SDC.SDCTreeBuilder.AddExtensionBaseTypeItems, SDC.SDCTreeBuilder.AddResponseItems, SDC.SDCTreeBuilder.drFormDesign, SDC.ListItemResponseFieldType, SDC.string, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.FillListItemBase.
override IdentifiedExtensionType SDC.SDCTreeBuilderEcc.AddDataTypeToResponseType(ResponseFieldType dd)
override void SDC.SDCTreeBuilderEcc.AddResponseHistoryToQuestion(QuestionItemType q)
References SDC.SDCTreeBuilderEcc.AddReplacedResponseToResponseHistory, SDC.QuestionItemBaseType.ResponseHistory.
override void SDC.SDCTreeBuilderEcc.AddReplacedResponseToResponseHistory(List< ResponseChangeType > respChange)
Referenced by SDC.SDCTreeBuilderEcc.AddResponseHistoryToQuestion.
override LookupEndPointType SDC.SDCTreeBuilderEcc.AddEndpointToQuestion(DisplayedType nodeToAdd, DisplayedType parentNode)
Add LookupEndpoint to Question w ListField.
override RulesType SDC.SDCTreeBuilderEcc.AddRuleToDisplayedType(DisplayedType parent)
+Rules
override ActSendMessageType SDC.SDCTreeBuilderEcc.AddActSendMessage(ThenType tt)
References SDC.ActSendMessageType, SDC.SDCTreeBuilder.drFormDesign, SDC.ThenType.Items, SDC.null, SDC.string, SDC.SDCTreeBuilder.StringToXMLElement, SDC.var.
override UnitsType SDC.SDCTreeBuilderEcc.AddUnits< T >(T t)
References SDC.SDCTreeBuilder.drFormDesign, SDC.string, SDC.UnitsType, SDC.var.
void SDC.SDCTreeBuilderEcc.AddFillFormDesignProperties()
References SDC.SDCTreeBuilderEcc.CreateStaticProperty, SDC.SDCTreeBuilder.dr, SDC.Empty, SDC.FormDesignType, SDC.SDCTreeBuilderEcc.MapDBNullToDateTime, SDC.null, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc.
void SDC.SDCTreeBuilderEcc.CreateHeader()
References SDC.SDCTreeBuilder.AddHeader, SDC.SDCTreeBuilderEcc.CreateStaticProperty, SDC.SDCTreeBuilder.dr, SDC.SDCTreeBuilder.dtHeaderDesign, SDC.Empty, SDC.SDCTreeBuilderEcc.MapDBNullToDateTime, SDC.null, SDC.var.
QuestionItemType SDC.SDCTreeBuilderEcc.CreateStaticQF< T >(T parent, string ID, ItemChoiceType dataType, string title="", object response=null, string name="", string type="", string style="", Boolean isReadOnly=true, Boolean isVisible=true)
Create Question-Fillin (QF). This is a Question Item that takes a Repsonse Field. In most cases, this method is used to create a read-only field in a form.
dataType DataTypes_DEType response type style readOnly
References SDC.SDCTreeBuilderEcc.AddDataTypesDE, SDC.SDCTreeBuilderEcc.CreateStaticBaseItems, SDC.null, SDC.var.
QuestionItemType SDC.SDCTreeBuilderEcc.CreateStaticQS< T >(T parent, ItemChoiceType dataType, string title="", object response=null, string name="", string type="", string style="", Boolean isReadOnly=true, Boolean isVisible=true)
QuestionItemType SDC.SDCTreeBuilderEcc.CreateStaticQM< T >(T parent, ItemChoiceType dataType, string title="", object response=null, string name="", string type="", string style="", Boolean isReadOnly=true, Boolean isVisible=true)
PropertyType SDC.SDCTreeBuilderEcc.CreateStaticProperty(IdentifiedExtensionType parent, string val, string type, string style, string propertyName="", Boolean visible=true, string comment="", XmlElement xml=null, string xhtml="", string name="", string propertyClass="", bool fillData=false)
References SDC.SDCTreeBuilder.AddProperty, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddFillFormDesignProperties, SDC.SDCTreeBuilderEcc.CreateFooter, SDC.SDCTreeBuilderEcc.CreateHeader.
CodingType SDC.SDCTreeBuilderEcc.CreateStaticCoding(ExtensionBaseType parent)
References SDC.CodingType, SDC.var.
void SDC.SDCTreeBuilderEcc.CreateFooter()
References SDC.SDCTreeBuilder.AddFooter, SDC.SDCTreeBuilderEcc.CreateStaticProperty, SDC.SDCTreeBuilder.dtHeaderDesign, SDC.null, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.SDCTreeBuilderEcc.
BaseType SDC.SDCTreeBuilderEcc.CreateStaticBaseItems(BaseType parent, string type, string style, string name)
Referenced by SDC.SDCTreeBuilderEcc.CreateStaticQF< T >.
ExtensionType SDC.SDCTreeBuilderEcc.CreateStaticExtension(ExtensionBaseType parent, XmlElement xml)
References SDC.SDCTreeBuilderEcc.AddFillExtension, SDC.null, SDC.var.
CommentType SDC.SDCTreeBuilderEcc.CreateStaticComment(ExtensionBaseType parent, string comment)
References SDC.var.
void SDC.SDCTreeBuilderEcc.AddTooltip(DisplayedType q)
RichTextType SDC.SDCTreeBuilderEcc.AddNote(DisplayedType q)
static DateTime SDC.SDCTreeBuilderEcc.MapDBNullToDateTime(object value)
Maps a DateTime value
value value to be mapped return datetime if value is not DBNull or else returns null
References SDC.dateTime, SDC.null, SDC.var.
Referenced by SDC.SDCTreeBuilderEcc.AddFillFormDesignProperties, SDC.SDCTreeBuilderEcc.CreateHeader.
static ItemTypeEnum SDC.SDCTreeBuilderEcc.GetEccRowTypeEnum(Int32 rowType)
Referenced by SDC.SDCTreeBuilderEcc.FillBaseTypeItemData, SDC.SDCTreeBuilderEcc.InitRow.
static ItemChoiceType SDC.SDCTreeBuilderEcc.ConvertEccDataTypeToSDC(string EccDataType)
References SDC.byte, SDC.decimal, SDC.float, SDC.long, SDC.short, SDC.string.
override SectionEnum SDC.SDCTreeBuilderEcc.GetSectionType(string strSectionType)
References SDC.Empty, SDC.var.
override void SDC.SDCTreeBuilderEcc.InitRow(out ItemTypeEnum rowType, out string parentID, out string type)
References SDC.SDCTreeBuilder.drFormDesign, SDC.SDCTreeBuilderEcc.GetEccRowTypeEnum.