SDC::___ScriptCode___
bool SDC.___ScriptCode___._shouldSerialize___DateTimeFunctions___
Referenced by SDC.___ScriptCode___.ShouldSerialize___DateTimeFunctions___.
object SDC.___ScriptCode___.___DateTimeFunctions___Field
Referenced by SDC.___ScriptCode___.ShouldSerialize___DateTimeFunctions___.
XmlSerializer SDC.___ScriptCode___.serializer
virtual object SDC.___ScriptCode___.___DateTimeFunctions___
XmlSerializer SDC.___ScriptCode___.Serializer
Referenced by SDC.___ScriptCode___.Deserialize.
virtual bool SDC.___ScriptCode___.ShouldSerialize___DateTimeFunctions___()
Test whether ___DateTimeFunctions___ should be serialized
References SDC.___ScriptCode___.___DateTimeFunctions___Field, SDC.___ScriptCode___._shouldSerialize___DateTimeFunctions___.
virtual string SDC.___ScriptCode___.Serialize(System.Text.Encoding encoding)
Serializes current ___ScriptCode___ object into an XML string
string XML value
virtual string SDC.___ScriptCode___.Serialize()
Referenced by SDC.___ScriptCode___.SaveToFile.
virtual bool SDC.___ScriptCode___.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ___ScriptCode___ object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.___ScriptCode___.SaveToFile.
virtual bool SDC.___ScriptCode___.SaveToFile(string fileName, out System.Exception exception)
References SDC.___ScriptCode___.SaveToFile.
virtual void SDC.___ScriptCode___.SaveToFile(string fileName)
References SDC.___ScriptCode___.SaveToFile.
virtual void SDC.___ScriptCode___.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.___ScriptCode___.Serialize.
static bool SDC.___ScriptCode___.Deserialize(string input, out ___ScriptCode___ obj, out System.Exception exception)
Deserializes workflow markup into an ___ScriptCode___ object
input string workflow markup to deserialize obj Output ___ScriptCode___ object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.___ScriptCode___.Deserialize, SDC.___ScriptCode___.LoadFromFile.
static bool SDC.___ScriptCode___.Deserialize(string input, out ___ScriptCode___ obj)
References SDC.___ScriptCode___.Deserialize, SDC.null.
static ___ScriptCode___ SDC.___ScriptCode___.Deserialize(string input)
References SDC.null.
static ___ScriptCode___ SDC.___ScriptCode___.Deserialize(System.IO.Stream s)
References SDC.___ScriptCode___.Serializer.
static bool SDC.___ScriptCode___.LoadFromFile(string fileName, System.Text.Encoding encoding, out ___ScriptCode___ obj, out System.Exception exception)
Deserializes xml markup from file into an ___ScriptCode___ object
fileName string xml file to load and deserialize obj Output ___ScriptCode___ object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.___ScriptCode___.LoadFromFile.
static bool SDC.___ScriptCode___.LoadFromFile(string fileName, out ___ScriptCode___ obj, out System.Exception exception)
References SDC.___ScriptCode___.LoadFromFile.
static bool SDC.___ScriptCode___.LoadFromFile(string fileName, out ___ScriptCode___ obj)
References SDC.___ScriptCode___.LoadFromFile, SDC.null.
static ___ScriptCode___ SDC.___ScriptCode___.LoadFromFile(string fileName)
References SDC.___ScriptCode___.LoadFromFile.
static ___ScriptCode___ SDC.___ScriptCode___.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.___ScriptCode___.Deserialize, SDC.null.