SDC::FileType
string_Stype SDC.FileType::_fileID
Referenced by SDC.FileType.ShouldSerializeFileID.
anyURI_Stype SDC.FileType::_fileURI
Referenced by SDC.FileType.ShouldSerializeFileURI.
string_Stype SDC.FileType::_displayName
Referenced by SDC.FileType.ShouldSerializeDisplayName.
string_Stype SDC.FileType::_title
Referenced by SDC.FileType.ShouldSerializeTitle.
VersionType SDC.FileType::_version
Referenced by SDC.FileType.ShouldSerializeVersion.
string_Stype SDC.FileType::_fileName
Referenced by SDC.FileType.ShouldSerializeFileName.
string_Stype SDC.FileType::_fileExtension
Referenced by SDC.FileType.ShouldSerializeFileExtension.
string_Stype SDC.FileType::_fileClass
Referenced by SDC.FileType.ShouldSerializeFileClass.
positiveInteger_Stype SDC.FileType::_fileSizeKB
Referenced by SDC.FileType.ShouldSerializeFileSizeKB.
List<string_Stype> SDC.FileType._description
string_Stype SDC.FileType::_copyright
Referenced by SDC.FileType.ShouldSerializeCopyright.
string_Stype SDC.FileType::_termsofUse
Referenced by SDC.FileType.ShouldSerializeTermsofUse.
FileUsageType SDC.FileType::_usage
Referenced by SDC.FileType.ShouldSerializeUsage.
FileDatesType SDC.FileType::_dates
Referenced by SDC.FileType.ShouldSerializeDates.
ContactsType SDC.FileType::_contacts
Referenced by SDC.FileType.ShouldSerializeContacts.
List<ApprovalType> SDC.FileType._approval
FileHashType SDC.FileType::_fileHash
Referenced by SDC.FileType.ShouldSerializeFileHash.
List<LanguageType> SDC.FileType._language
AssociatedFilesType SDC.FileType::_associatedFiles
Referenced by SDC.FileType.ShouldSerializeAssociatedFiles.
ProvenanceType SDC.FileType::_provenance
Referenced by SDC.FileType.ShouldSerializeProvenance.
List<SubmissionRuleType> SDC.FileType._defaultSubmissionRule
List<ComplianceRuleType> SDC.FileType._defaultComplianceRule
BindingList<string_Stype> SDC.FileType._description
BindingList<ApprovalType> SDC.FileType._approval
BindingList<LanguageType> SDC.FileType._language
BindingList<SubmissionRuleType> SDC.FileType._defaultSubmissionRule
BindingList<ComplianceRuleType> SDC.FileType._defaultComplianceRule
ObjectChangeTracker SDC.FileType.changeTrackerField
static XmlSerializer SDC.FileType::serializer
string_Stype SDC.FileType::FileID
Internal/local File ID, not necessarily in the format of the FileURI used for all SDC FormDesign items.
anyURI_Stype SDC.FileType::FileURI
string_Stype SDC.FileType::DisplayName
Text to be displayed that encapulates the file contents. This may be the same as the internal Title of the file.
string_Stype SDC.FileType::Title
Official title of the file.
VersionType SDC.FileType::Version
File version
string_Stype SDC.FileType::FileName
The name of the file as saved on disk or other persistant storage.
string_Stype SDC.FileType::FileExtension
The file type extension that describes the file's internal format. This is usually the 3-4 character text that appears after the last period in the file name, e.g., txt, docx, etc.
string_Stype SDC.FileType::FileClass
A short description of the class of file, such as "FormDesign XML"
positiveInteger_Stype SDC.FileType::FileSizeKB
virtual List<string_Stype> SDC.FileType.Description
Any additional information about the template or file. The type of information should be specified in the attribute.
string_Stype SDC.FileType::Copyright
string_Stype SDC.FileType::TermsofUse
FileUsageType SDC.FileType::Usage
Guidance for when this file should be used, and when it should not be used.
Guidenace for when this file should be used, and when it should not be used.
FileDatesType SDC.FileType::Dates
Various dates associated with the file release, versioning and usage.
ContactsType SDC.FileType::Contacts
People and Organizations associated with the file. Specify the type of Contact in the attribute. Examples of include Curator, Author, and Authority.
Referenced by SDC.SDCTreeBuilder.AddContact, SDC.SDCTreeBuilder.AddContactsListToFileType.
virtual List<ApprovalType> SDC.FileType.Approval
Documentation of review and acceptance of the file for production usage.
FileHashType SDC.FileType::FileHash
virtual List<LanguageType> SDC.FileType.Language
AssociatedFilesType SDC.FileType::AssociatedFiles
Link to any associated files, such as schemas, reference documents, manuals, etc.
ProvenanceType SDC.FileType::Provenance
virtual List<SubmissionRuleType> SDC.FileType.DefaultSubmissionRule
virtual List<ComplianceRuleType> SDC.FileType.DefaultComplianceRule
static XmlSerializer SDC.FileType::Serializer
Referenced by SDC.FileType.Deserialize.
virtual BindingList<string_Stype> SDC.FileType.Description
Any additional information about the template or file. The type of information should be specified in the attribute.
virtual BindingList<ApprovalType> SDC.FileType.Approval
Documentation of review and acceptance of the file for production usage.
virtual BindingList<LanguageType> SDC.FileType.Language
virtual BindingList<SubmissionRuleType> SDC.FileType.DefaultSubmissionRule
virtual BindingList<ComplianceRuleType> SDC.FileType.DefaultComplianceRule
ObjectChangeTracker SDC.FileType.ChangeTracker
SDC.FileType.FileType()
SDC.FileType.FileType(BaseType parentNode)
virtual bool SDC.FileType.ShouldSerializeDescription()
Test whether Description should be serialized
References SDC.Description, SDC.null.
virtual bool SDC.FileType.ShouldSerializeApproval()
Test whether Approval should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeLanguage()
Test whether Language should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeDefaultSubmissionRule()
Test whether DefaultSubmissionRule should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeDefaultComplianceRule()
Test whether DefaultComplianceRule should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileID()
Test whether FileID should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileURI()
Test whether FileURI should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeDisplayName()
Test whether DisplayName should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeTitle()
Test whether Title should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeVersion()
Test whether Version should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileName()
Test whether FileName should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileExtension()
Test whether FileExtension should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileClass()
Test whether FileClass should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileSizeKB()
Test whether FileSizeKB should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeCopyright()
Test whether Copyright should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeTermsofUse()
Test whether TermsofUse should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeDates()
Test whether Dates should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeContacts()
Test whether Contacts should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileHash()
Test whether FileHash should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeAssociatedFiles()
Test whether AssociatedFiles should be serialized
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeProvenance()
Test whether Provenance should be serialized
References SDC.null.
virtual string SDC.FileType.Serialize(System.Text.Encoding encoding)
Serializes current FileType object into an XML string
string XML value
virtual string SDC.FileType.Serialize()
Referenced by SDC.FileType.SaveToFile.
virtual bool SDC.FileType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current FileType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.FileType.SaveToFile.
virtual bool SDC.FileType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.FileType.SaveToFile(string fileName)
virtual void SDC.FileType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileID()
Test whether FileID should be serialized
References SDC.FileType._fileID, SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileURI()
Test whether FileURI should be serialized
References SDC.FileType._fileURI, SDC.null.
virtual bool SDC.FileType.ShouldSerializeDisplayName()
Test whether DisplayName should be serialized
References SDC.FileType._displayName, SDC.null.
virtual bool SDC.FileType.ShouldSerializeTitle()
Test whether Title should be serialized
References SDC.FileType._title, SDC.null.
virtual bool SDC.FileType.ShouldSerializeVersion()
Test whether Version should be serialized
References SDC.FileType._version, SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileName()
Test whether FileName should be serialized
References SDC.FileType._fileName, SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileExtension()
Test whether FileExtension should be serialized
References SDC.FileType._fileExtension, SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileClass()
Test whether FileClass should be serialized
References SDC.FileType._fileClass, SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileSizeKB()
Test whether FileSizeKB should be serialized
References SDC.FileType._fileSizeKB, SDC.null.
virtual bool SDC.FileType.ShouldSerializeCopyright()
Test whether Copyright should be serialized
References SDC.FileType._copyright, SDC.null.
virtual bool SDC.FileType.ShouldSerializeTermsofUse()
Test whether TermsofUse should be serialized
References SDC.FileType._termsofUse, SDC.null.
virtual bool SDC.FileType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.FileType._usage, SDC.null.
virtual bool SDC.FileType.ShouldSerializeDates()
Test whether Dates should be serialized
References SDC.FileType._dates, SDC.null.
virtual bool SDC.FileType.ShouldSerializeContacts()
Test whether Contacts should be serialized
References SDC.FileType._contacts, SDC.null.
virtual bool SDC.FileType.ShouldSerializeFileHash()
Test whether FileHash should be serialized
References SDC.FileType._fileHash, SDC.null.
virtual bool SDC.FileType.ShouldSerializeAssociatedFiles()
Test whether AssociatedFiles should be serialized
References SDC.FileType._associatedFiles, SDC.null.
virtual bool SDC.FileType.ShouldSerializeProvenance()
Test whether Provenance should be serialized
References SDC.FileType._provenance, SDC.null.
virtual string SDC.FileType.Serialize()
Serializes current FileType object into an XML string
string XML value
virtual bool SDC.FileType.SaveToFile(string fileName, out Exception exception)
Serializes current FileType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.FileType.SaveToFile.
virtual void SDC.FileType.SaveToFile(string fileName)
References SDC.null, SDC.FileType.Serialize.
virtual FileType SDC.FileType.Clone()
Create a clone of this FileType object
static bool SDC.FileType.Deserialize(string input, out FileType obj, out System.Exception exception)
Deserializes workflow markup into an FileType object
input string workflow markup to deserialize obj Output FileType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.FileType.Deserialize, SDC.FileType.LoadFromFile.
static bool SDC.FileType.Deserialize(string input, out FileType obj)
References SDC.null.
static new FileType SDC.FileType.Deserialize(string input)
References SDC.null.
static FileType SDC.FileType.Deserialize(System.IO.Stream s)
static bool SDC.FileType.LoadFromFile(string fileName, System.Text.Encoding encoding, out FileType obj, out System.Exception exception)
Deserializes xml markup from file into an FileType object
fileName string xml file to load and deserialize obj Output FileType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.FileType.LoadFromFile.
static bool SDC.FileType.LoadFromFile(string fileName, out FileType obj, out System.Exception exception)
static bool SDC.FileType.LoadFromFile(string fileName, out FileType obj)
References SDC.null.
static FileType SDC.FileType.LoadFromFile(string fileName)
static new FileType SDC.FileType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.FileType.Deserialize(string input, out FileType obj, out Exception exception)
Deserializes workflow markup into an FileType object
input string workflow markup to deserialize obj Output FileType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.FileType.Deserialize, SDC.null.
static bool SDC.FileType.Deserialize(string input, out FileType obj)
References SDC.FileType.Deserialize, SDC.null.
static new FileType SDC.FileType.Deserialize(string input)
References SDC.null, SDC.FileType.Serializer.
static FileType SDC.FileType.Deserialize(Stream s)
References SDC.FileType.Serializer.
static bool SDC.FileType.LoadFromFile(string fileName, out FileType obj, out Exception exception)
Deserializes xml markup from file into an FileType object
fileName string xml file to load and deserialize obj Output FileType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.FileType.LoadFromFile, SDC.null.
static bool SDC.FileType.LoadFromFile(string fileName, out FileType obj)
References SDC.FileType.LoadFromFile, SDC.null.
static new FileType SDC.FileType.LoadFromFile(string fileName)
References SDC.FileType.Deserialize, SDC.null.