SDC::ScriptCodeType
BindingList<ParameterType> SDC.ScriptCodeType._parameter
string SDC.ScriptCodeType._language
string SDC.ScriptCodeType._val
ObjectChangeTracker SDC.ScriptCodeType.changeTrackerField
XmlSerializer SDC.ScriptCodeType.serializer
virtual BindingList<ParameterType> SDC.ScriptCodeType.Parameter
Parameters are named FormDesign items which have property values that need to be supplied to a scripted function or a web service URI.
virtual string SDC.ScriptCodeType.language
Referenced by SDC.ScriptCodeType.ShouldSerializelanguage.
virtual string SDC.ScriptCodeType.val
Referenced by SDC.ScriptCodeType.ShouldSerializeval.
XmlSerializer SDC.ScriptCodeType.Serializer
Referenced by SDC.ScriptCodeType.Deserialize.
ObjectChangeTracker SDC.ScriptCodeType.ChangeTracker
SDC.ScriptCodeType.ScriptCodeType()
virtual bool SDC.ScriptCodeType.ShouldSerializelanguage()
Test whether language should be serialized
References SDC.ScriptCodeType.language.
virtual bool SDC.ScriptCodeType.ShouldSerializeval()
Test whether val should be serialized
References SDC.ScriptCodeType.val.
virtual string SDC.ScriptCodeType.Serialize()
Serializes current ScriptCodeType object into an XML string
string XML value
Referenced by SDC.ScriptCodeType.SaveToFile.
virtual bool SDC.ScriptCodeType.SaveToFile(string fileName, out Exception exception)
Serializes current ScriptCodeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.ScriptCodeType.SaveToFile(string fileName)
References SDC.null, SDC.ScriptCodeType.Serialize.
virtual ScriptCodeType SDC.ScriptCodeType.Clone()
Create a clone of this ScriptCodeType object
static bool SDC.ScriptCodeType.Deserialize(string input, out ScriptCodeType obj, out Exception exception)
Deserializes workflow markup into an ScriptCodeType object
input string workflow markup to deserialize obj Output ScriptCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ScriptCodeType.Deserialize, SDC.ScriptCodeType.LoadFromFile.
static bool SDC.ScriptCodeType.Deserialize(string input, out ScriptCodeType obj)
References SDC.ScriptCodeType.Deserialize, SDC.null.
static new ScriptCodeType SDC.ScriptCodeType.Deserialize(string input)
References SDC.null, SDC.ScriptCodeType.Serializer.
static ScriptCodeType SDC.ScriptCodeType.Deserialize(Stream s)
References SDC.ScriptCodeType.Serializer.
static bool SDC.ScriptCodeType.LoadFromFile(string fileName, out ScriptCodeType obj, out Exception exception)
Deserializes xml markup from file into an ScriptCodeType object
fileName string xml file to load and deserialize obj Output ScriptCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ScriptCodeType.LoadFromFile.
static bool SDC.ScriptCodeType.LoadFromFile(string fileName, out ScriptCodeType obj)
References SDC.ScriptCodeType.LoadFromFile, SDC.null.
static new ScriptCodeType SDC.ScriptCodeType.LoadFromFile(string fileName)
References SDC.ScriptCodeType.Deserialize, SDC.null.