SDC::ReturnNumType
DataTypesNumeric_DEType SDC.ReturnNumType._item1
Referenced by SDC.ReturnNumType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnNumType.serializer
virtual DataTypesNumeric_DEType SDC.ReturnNumType.Item1
XmlSerializer SDC.ReturnNumType.Serializer
Referenced by SDC.ReturnNumType.Deserialize.
virtual bool SDC.ReturnNumType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnNumType._item1, SDC.null.
virtual string SDC.ReturnNumType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnNumType object into an XML string
string XML value
virtual string SDC.ReturnNumType.Serialize()
Referenced by SDC.ReturnNumType.SaveToFile.
virtual bool SDC.ReturnNumType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnNumType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnNumType.SaveToFile.
virtual bool SDC.ReturnNumType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnNumType.SaveToFile.
virtual void SDC.ReturnNumType.SaveToFile(string fileName)
References SDC.ReturnNumType.SaveToFile.
virtual void SDC.ReturnNumType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnNumType.Serialize.
static bool SDC.ReturnNumType.Deserialize(string input, out ReturnNumType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnNumType object
input string workflow markup to deserialize obj Output ReturnNumType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnNumType.Deserialize, SDC.ReturnNumType.LoadFromFile.
static bool SDC.ReturnNumType.Deserialize(string input, out ReturnNumType obj)
References SDC.ReturnNumType.Deserialize, SDC.null.
static new ReturnNumType SDC.ReturnNumType.Deserialize(string input)
References SDC.null.
static ReturnNumType SDC.ReturnNumType.Deserialize(System.IO.Stream s)
References SDC.ReturnNumType.Serializer.
static bool SDC.ReturnNumType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnNumType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnNumType object
fileName string xml file to load and deserialize obj Output ReturnNumType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnNumType.LoadFromFile.
static bool SDC.ReturnNumType.LoadFromFile(string fileName, out ReturnNumType obj, out System.Exception exception)
References SDC.ReturnNumType.LoadFromFile.
static bool SDC.ReturnNumType.LoadFromFile(string fileName, out ReturnNumType obj)
References SDC.ReturnNumType.LoadFromFile, SDC.null.
static ReturnNumType SDC.ReturnNumType.LoadFromFile(string fileName)
References SDC.ReturnNumType.LoadFromFile.
static new ReturnNumType SDC.ReturnNumType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnNumType.Deserialize, SDC.null.