SDC::ActShowReportType
string SDC.ActShowReportType::_reportID
string SDC.ActShowReportType::_packageID
string SDC.ActShowReportType::_reportInstanceGuid
string SDC.ActShowReportType._reportInstanceVersonGuid
string SDC.ActShowReportType::_displayState
ObjectChangeTracker SDC.ActShowReportType.changeTrackerField
static XmlSerializer SDC.ActShowReportType::serializer
string SDC.ActShowReportType::reportID
This ID represents the report to be displayed.
Referenced by SDC.ActShowReportType.ShouldSerializereportID.
string SDC.ActShowReportType::packageID
This ID represents the Package that contains the report to be displayed.
Referenced by SDC.ActShowReportType.ShouldSerializepackageID.
string SDC.ActShowReportType::reportInstanceGuid
Referenced by SDC.ActShowReportType.ShouldSerializereportInstanceGuid.
virtual string SDC.ActShowReportType.reportInstanceVersonGuid
string SDC.ActShowReportType::displayState
Referenced by SDC.ActShowReportType.ShouldSerializedisplayState.
static XmlSerializer SDC.ActShowReportType::Serializer
Referenced by SDC.ActShowReportType.Deserialize.
ObjectChangeTracker SDC.ActShowReportType.ChangeTracker
SDC.ActShowReportType.ActShowReportType()
SDC.ActShowReportType.ActShowReportType(ThenType parentNode)
SDC.ActShowReportType.ActShowReportType()
virtual bool SDC.ActShowReportType.ShouldSerializereportID()
Test whether reportID should be serialized
virtual bool SDC.ActShowReportType.ShouldSerializepackageID()
Test whether packageID should be serialized
virtual bool SDC.ActShowReportType.ShouldSerializereportInstanceGuid()
Test whether reportInstanceGuid should be serialized
virtual bool SDC.ActShowReportType.ShouldSerializereportInstanceVersonGuid()
Test whether reportInstanceVersonGuid should be serialized
virtual bool SDC.ActShowReportType.ShouldSerializedisplayState()
Test whether displayState should be serialized
virtual string SDC.ActShowReportType.Serialize(System.Text.Encoding encoding)
Serializes current ActShowReportType object into an XML string
string XML value
virtual string SDC.ActShowReportType.Serialize()
Referenced by SDC.ActShowReportType.SaveToFile.
virtual bool SDC.ActShowReportType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ActShowReportType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ActShowReportType.SaveToFile.
virtual bool SDC.ActShowReportType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ActShowReportType.SaveToFile(string fileName)
virtual void SDC.ActShowReportType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ActShowReportType.ShouldSerializereportID()
Test whether reportID should be serialized
References SDC.ActShowReportType.reportID.
virtual bool SDC.ActShowReportType.ShouldSerializepackageID()
Test whether packageID should be serialized
References SDC.ActShowReportType.packageID.
virtual bool SDC.ActShowReportType.ShouldSerializereportInstanceGuid()
Test whether reportInstanceGuid should be serialized
References SDC.ActShowReportType.reportInstanceGuid.
virtual bool SDC.ActShowReportType.ShouldSerializedisplayState()
Test whether displayState should be serialized
References SDC.ActShowReportType.displayState.
virtual string SDC.ActShowReportType.Serialize()
Serializes current ActShowReportType object into an XML string
string XML value
virtual bool SDC.ActShowReportType.SaveToFile(string fileName, out Exception exception)
Serializes current ActShowReportType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ActShowReportType.SaveToFile.
virtual void SDC.ActShowReportType.SaveToFile(string fileName)
References SDC.null, SDC.ActShowReportType.Serialize.
virtual ActShowReportType SDC.ActShowReportType.Clone()
Create a clone of this ActShowReportType object
static bool SDC.ActShowReportType.Deserialize(string input, out ActShowReportType obj, out System.Exception exception)
Deserializes workflow markup into an ActShowReportType object
input string workflow markup to deserialize obj Output ActShowReportType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActShowReportType.Deserialize, SDC.ActShowReportType.LoadFromFile.
static bool SDC.ActShowReportType.Deserialize(string input, out ActShowReportType obj)
References SDC.null.
static new ActShowReportType SDC.ActShowReportType.Deserialize(string input)
References SDC.null.
static ActShowReportType SDC.ActShowReportType.Deserialize(System.IO.Stream s)
static bool SDC.ActShowReportType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ActShowReportType obj, out System.Exception exception)
Deserializes xml markup from file into an ActShowReportType object
fileName string xml file to load and deserialize obj Output ActShowReportType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActShowReportType.LoadFromFile.
static bool SDC.ActShowReportType.LoadFromFile(string fileName, out ActShowReportType obj, out System.Exception exception)
static bool SDC.ActShowReportType.LoadFromFile(string fileName, out ActShowReportType obj)
References SDC.null.
static ActShowReportType SDC.ActShowReportType.LoadFromFile(string fileName)
static new ActShowReportType SDC.ActShowReportType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ActShowReportType.Deserialize(string input, out ActShowReportType obj, out Exception exception)
Deserializes workflow markup into an ActShowReportType object
input string workflow markup to deserialize obj Output ActShowReportType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActShowReportType.Deserialize, SDC.null.
static bool SDC.ActShowReportType.Deserialize(string input, out ActShowReportType obj)
References SDC.ActShowReportType.Deserialize, SDC.null.
static new ActShowReportType SDC.ActShowReportType.Deserialize(string input)
References SDC.null, SDC.ActShowReportType.Serializer.
static ActShowReportType SDC.ActShowReportType.Deserialize(Stream s)
References SDC.ActShowReportType.Serializer.
static bool SDC.ActShowReportType.LoadFromFile(string fileName, out ActShowReportType obj, out Exception exception)
Deserializes xml markup from file into an ActShowReportType object
fileName string xml file to load and deserialize obj Output ActShowReportType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActShowReportType.LoadFromFile, SDC.null.
static bool SDC.ActShowReportType.LoadFromFile(string fileName, out ActShowReportType obj)
References SDC.ActShowReportType.LoadFromFile, SDC.null.
static new ActShowReportType SDC.ActShowReportType.LoadFromFile(string fileName)
References SDC.ActShowReportType.Deserialize, SDC.null.