SDC::MinExclusiveType
string SDC.MinExclusiveType._val
ObjectChangeTracker SDC.MinExclusiveType.changeTrackerField
XmlSerializer SDC.MinExclusiveType.serializer
virtual string SDC.MinExclusiveType.val
Referenced by SDC.MinExclusiveType.ShouldSerializeval.
XmlSerializer SDC.MinExclusiveType.Serializer
Referenced by SDC.MinExclusiveType.Deserialize.
ObjectChangeTracker SDC.MinExclusiveType.ChangeTracker
SDC.MinExclusiveType.MinExclusiveType()
virtual bool SDC.MinExclusiveType.ShouldSerializeval()
Test whether val should be serialized
References SDC.MinExclusiveType.val.
virtual string SDC.MinExclusiveType.Serialize()
Serializes current MinExclusiveType object into an XML string
string XML value
Referenced by SDC.MinExclusiveType.SaveToFile.
virtual bool SDC.MinExclusiveType.SaveToFile(string fileName, out Exception exception)
Serializes current MinExclusiveType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.MinExclusiveType.SaveToFile(string fileName)
References SDC.null, SDC.MinExclusiveType.Serialize.
virtual MinExclusiveType SDC.MinExclusiveType.Clone()
Create a clone of this MinExclusiveType object
static bool SDC.MinExclusiveType.Deserialize(string input, out MinExclusiveType obj, out Exception exception)
Deserializes workflow markup into an MinExclusiveType object
input string workflow markup to deserialize obj Output MinExclusiveType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.MinExclusiveType.Deserialize, SDC.MinExclusiveType.LoadFromFile.
static bool SDC.MinExclusiveType.Deserialize(string input, out MinExclusiveType obj)
References SDC.MinExclusiveType.Deserialize, SDC.null.
static new MinExclusiveType SDC.MinExclusiveType.Deserialize(string input)
References SDC.null, SDC.MinExclusiveType.Serializer.
static MinExclusiveType SDC.MinExclusiveType.Deserialize(Stream s)
References SDC.MinExclusiveType.Serializer.
static bool SDC.MinExclusiveType.LoadFromFile(string fileName, out MinExclusiveType obj, out Exception exception)
Deserializes xml markup from file into an MinExclusiveType object
fileName string xml file to load and deserialize obj Output MinExclusiveType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.MinExclusiveType.LoadFromFile.
static bool SDC.MinExclusiveType.LoadFromFile(string fileName, out MinExclusiveType obj)
References SDC.MinExclusiveType.LoadFromFile, SDC.null.
static new MinExclusiveType SDC.MinExclusiveType.LoadFromFile(string fileName)
References SDC.MinExclusiveType.Deserialize, SDC.null.