SDC::ExclusiveItemPairsType
bool SDC.ExclusiveItemPairsType._shouldSerializenot
Referenced by SDC.ExclusiveItemPairsType.ShouldSerializenot.
bool SDC.ExclusiveItemPairsType._not
Referenced by SDC.ExclusiveItemPairsType.ExclusiveItemPairsType, SDC.ExclusiveItemPairsType.ShouldSerializenot.
string SDC.ExclusiveItemPairsType._testItemName
string SDC.ExclusiveItemPairsType._exclusiveSet
string SDC.ExclusiveItemPairsType._validationMessage
ObjectChangeTracker SDC.ExclusiveItemPairsType.changeTrackerField
XmlSerializer SDC.ExclusiveItemPairsType.serializer
virtual bool SDC.ExclusiveItemPairsType.not
If ="true" then the logical value of the conditions of the parent element is negated; true becomes false and false becomes true.
virtual string SDC.ExclusiveItemPairsType.testItemName
The ListItem that is being evaluated for the presence of disallowed selections (in )
Referenced by SDC.ExclusiveItemPairsType.ShouldSerializetestItemName.
virtual string SDC.ExclusiveItemPairsType.exclusiveSet
If no is present, then this attribute contains ListItems that may not be selected together in any combination. IF any 2 of them are selected, then the parent element (ExclusiveSelectedItems) evaluates to true.
If has a value and is selected, then the items in are evaluated to see if any of them are also selected. If one or more is also selected, then the parent element (ExclusiveSelectedItems) evaluates to true.If has a value, the items are not tested against each other.
Referenced by SDC.ExclusiveItemPairsType.ShouldSerializeexclusiveSet.
virtual string SDC.ExclusiveItemPairsType.validationMessage
Message that appears when an illegal combination of ListItems is selected.
Referenced by SDC.ExclusiveItemPairsType.ShouldSerializevalidationMessage.
XmlSerializer SDC.ExclusiveItemPairsType.Serializer
Referenced by SDC.ExclusiveItemPairsType.Deserialize.
ObjectChangeTracker SDC.ExclusiveItemPairsType.ChangeTracker
SDC.ExclusiveItemPairsType.ExclusiveItemPairsType()
ExclusiveItemPairsType class constructor
References SDC.ExclusiveItemPairsType._not.
virtual bool SDC.ExclusiveItemPairsType.ShouldSerializenot()
Test whether not should be serialized
References SDC.ExclusiveItemPairsType._not, SDC.ExclusiveItemPairsType._shouldSerializenot.
virtual bool SDC.ExclusiveItemPairsType.ShouldSerializetestItemName()
Test whether testItemName should be serialized
References SDC.ExclusiveItemPairsType.testItemName.
virtual bool SDC.ExclusiveItemPairsType.ShouldSerializeexclusiveSet()
Test whether exclusiveSet should be serialized
References SDC.ExclusiveItemPairsType.exclusiveSet.
virtual bool SDC.ExclusiveItemPairsType.ShouldSerializevalidationMessage()
Test whether validationMessage should be serialized
References SDC.ExclusiveItemPairsType.validationMessage.
virtual string SDC.ExclusiveItemPairsType.Serialize()
Serializes current ExclusiveItemPairsType object into an XML string
string XML value
Referenced by SDC.ExclusiveItemPairsType.SaveToFile.
virtual bool SDC.ExclusiveItemPairsType.SaveToFile(string fileName, out Exception exception)
Serializes current ExclusiveItemPairsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.ExclusiveItemPairsType.SaveToFile(string fileName)
References SDC.null, SDC.ExclusiveItemPairsType.Serialize.
virtual ExclusiveItemPairsType SDC.ExclusiveItemPairsType.Clone()
Create a clone of this ExclusiveItemPairsType object
static bool SDC.ExclusiveItemPairsType.Deserialize(string input, out ExclusiveItemPairsType obj, out Exception exception)
Deserializes workflow markup into an ExclusiveItemPairsType object
input string workflow markup to deserialize obj Output ExclusiveItemPairsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ExclusiveItemPairsType.Deserialize, SDC.ExclusiveItemPairsType.LoadFromFile.
static bool SDC.ExclusiveItemPairsType.Deserialize(string input, out ExclusiveItemPairsType obj)
References SDC.ExclusiveItemPairsType.Deserialize, SDC.null.
static new ExclusiveItemPairsType SDC.ExclusiveItemPairsType.Deserialize(string input)
References SDC.null, SDC.ExclusiveItemPairsType.Serializer.
static ExclusiveItemPairsType SDC.ExclusiveItemPairsType.Deserialize(Stream s)
References SDC.ExclusiveItemPairsType.Serializer.
static bool SDC.ExclusiveItemPairsType.LoadFromFile(string fileName, out ExclusiveItemPairsType obj, out Exception exception)
Deserializes xml markup from file into an ExclusiveItemPairsType object
fileName string xml file to load and deserialize obj Output ExclusiveItemPairsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ExclusiveItemPairsType.LoadFromFile.
static bool SDC.ExclusiveItemPairsType.LoadFromFile(string fileName, out ExclusiveItemPairsType obj)
References SDC.ExclusiveItemPairsType.LoadFromFile, SDC.null.
static new ExclusiveItemPairsType SDC.ExclusiveItemPairsType.LoadFromFile(string fileName)
References SDC.ExclusiveItemPairsType.Deserialize, SDC.null.