SDC::InputList_ReturnDateTimeType
AnyFunctionsListType SDC.InputList_ReturnDateTimeType._inputList
Referenced by SDC.InputList_ReturnDateTimeType.ShouldSerializeInputList.
XmlSerializer SDC.InputList_ReturnDateTimeType.serializer
virtual AnyFunctionsListType SDC.InputList_ReturnDateTimeType.InputList
XmlSerializer SDC.InputList_ReturnDateTimeType.Serializer
Referenced by SDC.InputList_ReturnDateTimeType.Deserialize.
virtual bool SDC.InputList_ReturnDateTimeType.ShouldSerializeInputList()
Test whether InputList should be serialized
References SDC.InputList_ReturnDateTimeType._inputList, SDC.null.
virtual string SDC.InputList_ReturnDateTimeType.Serialize(System.Text.Encoding encoding)
Serializes current InputList_ReturnDateTimeType object into an XML string
string XML value
virtual string SDC.InputList_ReturnDateTimeType.Serialize()
Referenced by SDC.InputList_ReturnDateTimeType.SaveToFile.
virtual bool SDC.InputList_ReturnDateTimeType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InputList_ReturnDateTimeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InputList_ReturnDateTimeType.SaveToFile.
virtual bool SDC.InputList_ReturnDateTimeType.SaveToFile(string fileName, out System.Exception exception)
References SDC.InputList_ReturnDateTimeType.SaveToFile.
virtual void SDC.InputList_ReturnDateTimeType.SaveToFile(string fileName)
References SDC.InputList_ReturnDateTimeType.SaveToFile.
virtual void SDC.InputList_ReturnDateTimeType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InputList_ReturnDateTimeType.Serialize.
static bool SDC.InputList_ReturnDateTimeType.Deserialize(string input, out InputList_ReturnDateTimeType obj, out System.Exception exception)
Deserializes workflow markup into an InputList_ReturnDateTimeType object
input string workflow markup to deserialize obj Output InputList_ReturnDateTimeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputList_ReturnDateTimeType.Deserialize, SDC.InputList_ReturnDateTimeType.LoadFromFile.
static bool SDC.InputList_ReturnDateTimeType.Deserialize(string input, out InputList_ReturnDateTimeType obj)
References SDC.InputList_ReturnDateTimeType.Deserialize, SDC.null.
static new InputList_ReturnDateTimeType SDC.InputList_ReturnDateTimeType.Deserialize(string input)
References SDC.null.
static InputList_ReturnDateTimeType SDC.InputList_ReturnDateTimeType.Deserialize(System.IO.Stream s)
References SDC.InputList_ReturnDateTimeType.Serializer.
static bool SDC.InputList_ReturnDateTimeType.LoadFromFile(string fileName, System.Text.Encoding encoding, out InputList_ReturnDateTimeType obj, out System.Exception exception)
Deserializes xml markup from file into an InputList_ReturnDateTimeType object
fileName string xml file to load and deserialize obj Output InputList_ReturnDateTimeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputList_ReturnDateTimeType.LoadFromFile.
static bool SDC.InputList_ReturnDateTimeType.LoadFromFile(string fileName, out InputList_ReturnDateTimeType obj, out System.Exception exception)
References SDC.InputList_ReturnDateTimeType.LoadFromFile.
static bool SDC.InputList_ReturnDateTimeType.LoadFromFile(string fileName, out InputList_ReturnDateTimeType obj)
References SDC.InputList_ReturnDateTimeType.LoadFromFile, SDC.null.
static InputList_ReturnDateTimeType SDC.InputList_ReturnDateTimeType.LoadFromFile(string fileName)
References SDC.InputList_ReturnDateTimeType.LoadFromFile.
static new InputList_ReturnDateTimeType SDC.InputList_ReturnDateTimeType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InputList_ReturnDateTimeType.Deserialize, SDC.null.