SDC::short_Stype
bool SDC.short_Stype::_shouldSerializeval
Referenced by SDC.short_Stype.ShouldSerializeval.
System Nullable< short > SDC.short_Stype::_val
Referenced by SDC.short_Stype.ShouldSerializeval.
dtQuantEnum SDC.short_Stype::_quantEnum
Referenced by SDC.short_Stype.short_Stype.
ObjectChangeTracker SDC.short_Stype.changeTrackerField
static XmlSerializer SDC.short_Stype::serializer
short SDC.short_Stype::val
bool SDC.short_Stype::valSpecified
dtQuantEnum SDC.short_Stype::quantEnum
static XmlSerializer SDC.short_Stype::Serializer
Referenced by SDC.short_Stype.Deserialize.
ObjectChangeTracker SDC.short_Stype.ChangeTracker
SDC.short_Stype.short_Stype()
SDC.short_Stype.short_Stype(BaseType parentNode)
virtual bool SDC.short_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.short_Stype._shouldSerializeval, SDC.short_Stype._val.
virtual string SDC.short_Stype.Serialize(System.Text.Encoding encoding)
Serializes current short_Stype object into an XML string
string XML value
virtual string SDC.short_Stype.Serialize()
Referenced by SDC.short_Stype.SaveToFile.
virtual bool SDC.short_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current short_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.short_Stype.SaveToFile.
virtual bool SDC.short_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.short_Stype.SaveToFile.
virtual void SDC.short_Stype.SaveToFile(string fileName)
References SDC.short_Stype.SaveToFile.
virtual void SDC.short_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.short_Stype.Serialize.
SDC.short_Stype.short_Stype()
short_Stype class constructor
References SDC.short_Stype._quantEnum.
virtual bool SDC.short_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.short_Stype._shouldSerializeval, SDC.short_Stype._val.
virtual string SDC.short_Stype.Serialize()
Serializes current short_Stype object into an XML string
string XML value
virtual bool SDC.short_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current short_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.short_Stype.SaveToFile.
virtual void SDC.short_Stype.SaveToFile(string fileName)
References SDC.null, SDC.short_Stype.Serialize.
virtual short_Stype SDC.short_Stype.Clone()
Create a clone of this short_Stype object
static bool SDC.short_Stype.Deserialize(string input, out short_Stype obj, out System.Exception exception)
Deserializes workflow markup into an short_Stype object
input string workflow markup to deserialize obj Output short_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.short_Stype.Deserialize, SDC.short_Stype.LoadFromFile.
static bool SDC.short_Stype.Deserialize(string input, out short_Stype obj)
References SDC.short_Stype.Deserialize, SDC.null.
static new short_Stype SDC.short_Stype.Deserialize(string input)
References SDC.null.
static short_Stype SDC.short_Stype.Deserialize(System.IO.Stream s)
References SDC.short_Stype.Serializer.
static bool SDC.short_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out short_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an short_Stype object
fileName string xml file to load and deserialize obj Output short_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.short_Stype.LoadFromFile.
static bool SDC.short_Stype.LoadFromFile(string fileName, out short_Stype obj, out System.Exception exception)
References SDC.short_Stype.LoadFromFile.
static bool SDC.short_Stype.LoadFromFile(string fileName, out short_Stype obj)
References SDC.short_Stype.LoadFromFile, SDC.null.
static short_Stype SDC.short_Stype.LoadFromFile(string fileName)
References SDC.short_Stype.LoadFromFile.
static new short_Stype SDC.short_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.short_Stype.Deserialize, SDC.null.
static bool SDC.short_Stype.Deserialize(string input, out short_Stype obj, out Exception exception)
Deserializes workflow markup into an short_Stype object
input string workflow markup to deserialize obj Output short_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.short_Stype.Deserialize, SDC.null.
static bool SDC.short_Stype.Deserialize(string input, out short_Stype obj)
References SDC.short_Stype.Deserialize, SDC.null.
static new short_Stype SDC.short_Stype.Deserialize(string input)
References SDC.null, SDC.short_Stype.Serializer.
static short_Stype SDC.short_Stype.Deserialize(Stream s)
References SDC.short_Stype.Serializer.
static bool SDC.short_Stype.LoadFromFile(string fileName, out short_Stype obj, out Exception exception)
Deserializes xml markup from file into an short_Stype object
fileName string xml file to load and deserialize obj Output short_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.short_Stype.LoadFromFile, SDC.null.
static bool SDC.short_Stype.LoadFromFile(string fileName, out short_Stype obj)
References SDC.short_Stype.LoadFromFile, SDC.null.
static new short_Stype SDC.short_Stype.LoadFromFile(string fileName)
References SDC.short_Stype.Deserialize, SDC.null.