SDC::ActValidateFormType
bool SDC.ActValidateFormType::_shouldSerializevalidateRules
Referenced by SDC.ActValidateFormType.ShouldSerializevalidateRules.
bool SDC.ActValidateFormType::_shouldSerializevalidateDataTypes
Referenced by SDC.ActValidateFormType.ShouldSerializevalidateDataTypes.
FuncType SDC.ActValidateFormType._validationWebService
Referenced by SDC.ActValidateFormType.ShouldSerializeValidationWebService.
bool SDC.ActValidateFormType::_validateDataTypes
Referenced by SDC.ActValidateFormType.ActValidateFormType, SDC.ActValidateFormType.ShouldSerializevalidateDataTypes.
bool SDC.ActValidateFormType::_validateRules
Referenced by SDC.ActValidateFormType.ActValidateFormType, SDC.ActValidateFormType.ShouldSerializevalidateRules.
string SDC.ActValidateFormType::_validationType
WebServiceType SDC.ActValidateFormType._validationWebService
ObjectChangeTracker SDC.ActValidateFormType.changeTrackerField
static XmlSerializer SDC.ActValidateFormType::serializer
virtual FuncType SDC.ActValidateFormType.ValidationWebService
bool SDC.ActValidateFormType::validateDataTypes
bool SDC.ActValidateFormType::validateRules
string SDC.ActValidateFormType::validationType
Referenced by SDC.ActValidateFormType.ShouldSerializevalidationType.
static XmlSerializer SDC.ActValidateFormType::Serializer
Referenced by SDC.ActValidateFormType.Deserialize.
virtual WebServiceType SDC.ActValidateFormType.ValidationWebService
ObjectChangeTracker SDC.ActValidateFormType.ChangeTracker
SDC.ActValidateFormType.ActValidateFormType()
SDC.ActValidateFormType.ActValidateFormType(ThenType parentNode)
ActValidateFormType SDC.ActValidateFormType.Fill_ActValidateFormType()
+Replaced in original class: protected ActValidateFormType() { }
References SDC.null.
void SDC.ActValidateFormType.Fill_ActValidateFormType()
virtual bool SDC.ActValidateFormType.ShouldSerializevalidateDataTypes()
Test whether validateDataTypes should be serialized
virtual bool SDC.ActValidateFormType.ShouldSerializevalidateRules()
Test whether validateRules should be serialized
virtual bool SDC.ActValidateFormType.ShouldSerializeValidationWebService()
Test whether ValidationWebService should be serialized
References SDC.null.
virtual bool SDC.ActValidateFormType.ShouldSerializevalidationType()
Test whether validationType should be serialized
virtual string SDC.ActValidateFormType.Serialize(System.Text.Encoding encoding)
Serializes current ActValidateFormType object into an XML string
string XML value
virtual string SDC.ActValidateFormType.Serialize()
Referenced by SDC.ActValidateFormType.SaveToFile.
virtual bool SDC.ActValidateFormType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ActValidateFormType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ActValidateFormType.SaveToFile.
virtual bool SDC.ActValidateFormType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ActValidateFormType.SaveToFile(string fileName)
virtual void SDC.ActValidateFormType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.ActValidateFormType.ActValidateFormType()
ActValidateFormType class constructor
References SDC.ActValidateFormType._validateDataTypes, SDC.ActValidateFormType._validateRules.
virtual bool SDC.ActValidateFormType.ShouldSerializevalidateDataTypes()
Test whether validateDataTypes should be serialized
References SDC.ActValidateFormType._shouldSerializevalidateDataTypes, SDC.ActValidateFormType._validateDataTypes.
virtual bool SDC.ActValidateFormType.ShouldSerializevalidateRules()
Test whether validateRules should be serialized
References SDC.ActValidateFormType._shouldSerializevalidateRules, SDC.ActValidateFormType._validateRules.
virtual bool SDC.ActValidateFormType.ShouldSerializeValidationWebService()
Test whether ValidationWebService should be serialized
References SDC.ActValidateFormType._validationWebService, SDC.null.
virtual bool SDC.ActValidateFormType.ShouldSerializevalidationType()
Test whether validationType should be serialized
References SDC.ActValidateFormType.validationType.
virtual string SDC.ActValidateFormType.Serialize()
Serializes current ActValidateFormType object into an XML string
string XML value
virtual bool SDC.ActValidateFormType.SaveToFile(string fileName, out Exception exception)
Serializes current ActValidateFormType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ActValidateFormType.SaveToFile.
virtual void SDC.ActValidateFormType.SaveToFile(string fileName)
References SDC.null, SDC.ActValidateFormType.Serialize.
virtual ActValidateFormType SDC.ActValidateFormType.Clone()
Create a clone of this ActValidateFormType object
static bool SDC.ActValidateFormType.Deserialize(string input, out ActValidateFormType obj, out System.Exception exception)
Deserializes workflow markup into an ActValidateFormType object
input string workflow markup to deserialize obj Output ActValidateFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActValidateFormType.Deserialize, SDC.ActValidateFormType.LoadFromFile.
static bool SDC.ActValidateFormType.Deserialize(string input, out ActValidateFormType obj)
References SDC.null.
static new ActValidateFormType SDC.ActValidateFormType.Deserialize(string input)
References SDC.null.
static ActValidateFormType SDC.ActValidateFormType.Deserialize(System.IO.Stream s)
static bool SDC.ActValidateFormType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ActValidateFormType obj, out System.Exception exception)
Deserializes xml markup from file into an ActValidateFormType object
fileName string xml file to load and deserialize obj Output ActValidateFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActValidateFormType.LoadFromFile.
static bool SDC.ActValidateFormType.LoadFromFile(string fileName, out ActValidateFormType obj, out System.Exception exception)
static bool SDC.ActValidateFormType.LoadFromFile(string fileName, out ActValidateFormType obj)
References SDC.null.
static ActValidateFormType SDC.ActValidateFormType.LoadFromFile(string fileName)
static new ActValidateFormType SDC.ActValidateFormType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ActValidateFormType.Deserialize(string input, out ActValidateFormType obj, out Exception exception)
Deserializes workflow markup into an ActValidateFormType object
input string workflow markup to deserialize obj Output ActValidateFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActValidateFormType.Deserialize, SDC.null.
static bool SDC.ActValidateFormType.Deserialize(string input, out ActValidateFormType obj)
References SDC.ActValidateFormType.Deserialize, SDC.null.
static new ActValidateFormType SDC.ActValidateFormType.Deserialize(string input)
References SDC.null, SDC.ActValidateFormType.Serializer.
static ActValidateFormType SDC.ActValidateFormType.Deserialize(Stream s)
References SDC.ActValidateFormType.Serializer.
static bool SDC.ActValidateFormType.LoadFromFile(string fileName, out ActValidateFormType obj, out Exception exception)
Deserializes xml markup from file into an ActValidateFormType object
fileName string xml file to load and deserialize obj Output ActValidateFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActValidateFormType.LoadFromFile, SDC.null.
static bool SDC.ActValidateFormType.LoadFromFile(string fileName, out ActValidateFormType obj)
References SDC.ActValidateFormType.LoadFromFile, SDC.null.
static new ActValidateFormType SDC.ActValidateFormType.LoadFromFile(string fileName)
References SDC.ActValidateFormType.Deserialize, SDC.null.