SDC::ReturnListType
AnyListType SDC.ReturnListType._item1
Referenced by SDC.ReturnListType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnListType.serializer
virtual AnyListType SDC.ReturnListType.Item1
XmlSerializer SDC.ReturnListType.Serializer
Referenced by SDC.ReturnListType.Deserialize.
virtual bool SDC.ReturnListType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnListType._item1, SDC.null.
virtual string SDC.ReturnListType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnListType object into an XML string
string XML value
virtual string SDC.ReturnListType.Serialize()
Referenced by SDC.ReturnListType.SaveToFile.
virtual bool SDC.ReturnListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnListType.SaveToFile.
virtual bool SDC.ReturnListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnListType.SaveToFile.
virtual void SDC.ReturnListType.SaveToFile(string fileName)
References SDC.ReturnListType.SaveToFile.
virtual void SDC.ReturnListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnListType.Serialize.
static bool SDC.ReturnListType.Deserialize(string input, out ReturnListType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnListType object
input string workflow markup to deserialize obj Output ReturnListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnListType.Deserialize, SDC.ReturnListType.LoadFromFile.
static bool SDC.ReturnListType.Deserialize(string input, out ReturnListType obj)
References SDC.ReturnListType.Deserialize, SDC.null.
static new ReturnListType SDC.ReturnListType.Deserialize(string input)
References SDC.null.
static ReturnListType SDC.ReturnListType.Deserialize(System.IO.Stream s)
References SDC.ReturnListType.Serializer.
static bool SDC.ReturnListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnListType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnListType object
fileName string xml file to load and deserialize obj Output ReturnListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnListType.LoadFromFile.
static bool SDC.ReturnListType.LoadFromFile(string fileName, out ReturnListType obj, out System.Exception exception)
References SDC.ReturnListType.LoadFromFile.
static bool SDC.ReturnListType.LoadFromFile(string fileName, out ReturnListType obj)
References SDC.ReturnListType.LoadFromFile, SDC.null.
static ReturnListType SDC.ReturnListType.LoadFromFile(string fileName)
References SDC.ReturnListType.LoadFromFile.
static new ReturnListType SDC.ReturnListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnListType.Deserialize, SDC.null.