SDC::anyURI_Stype
string SDC.anyURI_Stype::_val
ObjectChangeTracker SDC.anyURI_Stype.changeTrackerField
static XmlSerializer SDC.anyURI_Stype::serializer
string SDC.anyURI_Stype::val
Referenced by SDC.anyURI_Stype.ShouldSerializeval.
static XmlSerializer SDC.anyURI_Stype::Serializer
Referenced by SDC.anyURI_Stype.Deserialize.
ObjectChangeTracker SDC.anyURI_Stype.ChangeTracker
SDC.anyURI_Stype.anyURI_Stype()
SDC.anyURI_Stype.anyURI_Stype(BaseType parentNode)
virtual bool SDC.anyURI_Stype.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.anyURI_Stype.Serialize(System.Text.Encoding encoding)
Serializes current anyURI_Stype object into an XML string
string XML value
virtual string SDC.anyURI_Stype.Serialize()
Referenced by SDC.anyURI_Stype.SaveToFile.
virtual bool SDC.anyURI_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current anyURI_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.anyURI_Stype.SaveToFile.
virtual bool SDC.anyURI_Stype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.anyURI_Stype.SaveToFile(string fileName)
virtual void SDC.anyURI_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.anyURI_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.anyURI_Stype.val.
virtual string SDC.anyURI_Stype.Serialize()
Serializes current anyURI_Stype object into an XML string
string XML value
virtual bool SDC.anyURI_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current anyURI_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.anyURI_Stype.SaveToFile.
virtual void SDC.anyURI_Stype.SaveToFile(string fileName)
References SDC.null, SDC.anyURI_Stype.Serialize.
virtual anyURI_Stype SDC.anyURI_Stype.Clone()
Create a clone of this anyURI_Stype object
static bool SDC.anyURI_Stype.Deserialize(string input, out anyURI_Stype obj, out System.Exception exception)
Deserializes workflow markup into an anyURI_Stype object
input string workflow markup to deserialize obj Output anyURI_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.anyURI_Stype.Deserialize, SDC.anyURI_Stype.LoadFromFile.
static bool SDC.anyURI_Stype.Deserialize(string input, out anyURI_Stype obj)
References SDC.null.
static new anyURI_Stype SDC.anyURI_Stype.Deserialize(string input)
References SDC.null.
static anyURI_Stype SDC.anyURI_Stype.Deserialize(System.IO.Stream s)
static bool SDC.anyURI_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out anyURI_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an anyURI_Stype object
fileName string xml file to load and deserialize obj Output anyURI_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.anyURI_Stype.LoadFromFile.
static bool SDC.anyURI_Stype.LoadFromFile(string fileName, out anyURI_Stype obj, out System.Exception exception)
static bool SDC.anyURI_Stype.LoadFromFile(string fileName, out anyURI_Stype obj)
References SDC.null.
static anyURI_Stype SDC.anyURI_Stype.LoadFromFile(string fileName)
static new anyURI_Stype SDC.anyURI_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.anyURI_Stype.Deserialize(string input, out anyURI_Stype obj, out Exception exception)
Deserializes workflow markup into an anyURI_Stype object
input string workflow markup to deserialize obj Output anyURI_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.anyURI_Stype.Deserialize, SDC.null.
static bool SDC.anyURI_Stype.Deserialize(string input, out anyURI_Stype obj)
References SDC.anyURI_Stype.Deserialize, SDC.null.
static new anyURI_Stype SDC.anyURI_Stype.Deserialize(string input)
References SDC.null, SDC.anyURI_Stype.Serializer.
static anyURI_Stype SDC.anyURI_Stype.Deserialize(Stream s)
References SDC.anyURI_Stype.Serializer.
static bool SDC.anyURI_Stype.LoadFromFile(string fileName, out anyURI_Stype obj, out Exception exception)
Deserializes xml markup from file into an anyURI_Stype object
fileName string xml file to load and deserialize obj Output anyURI_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.anyURI_Stype.LoadFromFile, SDC.null.
static bool SDC.anyURI_Stype.LoadFromFile(string fileName, out anyURI_Stype obj)
References SDC.anyURI_Stype.LoadFromFile, SDC.null.
static new anyURI_Stype SDC.anyURI_Stype.LoadFromFile(string fileName)
References SDC.anyURI_Stype.Deserialize, SDC.null.