SDC::IdentifiedExtensionType
Dictionary<String, IdentifiedExtensionType> SDC.IdentifiedExtensionType.IdentExtNodes
Given an Item Node's URI, returns the Item's object reference as IdentifiedExtensionType.
string SDC.IdentifiedExtensionType::_id
string SDC.IdentifiedExtensionType::_baseURI
ObjectChangeTracker SDC.IdentifiedExtensionType.changeTrackerField
static XmlSerializer SDC.IdentifiedExtensionType::serializer
string SDC.IdentifiedExtensionType::ID
Referenced by SDC.SDCTreeBuilder.AddBody, SDC.SDCTreeBuilder.AddFooter, SDC.SDCTreeBuilder.AddHeader, SDC.IdentifiedExtensionType.AddToIdentExtNodes, SDC.IdentifiedExtensionType.ShouldSerializeID.
string SDC.IdentifiedExtensionType::baseURI
Referenced by SDC.IdentifiedExtensionType.ShouldSerializebaseURI.
static XmlSerializer SDC.IdentifiedExtensionType::Serializer
Referenced by SDC.IdentifiedExtensionType.Deserialize.
ObjectChangeTracker SDC.IdentifiedExtensionType.ChangeTracker
SDC.IdentifiedExtensionType.IdentifiedExtensionType()
SDC.IdentifiedExtensionType.IdentifiedExtensionType(BaseType parentNode, bool fillData=true, string id=null)
References SDC.IdentifiedExtensionType.AddToIdentExtNodes.
void SDC.IdentifiedExtensionType.AddToIdentExtNodes(string id=null)
References SDC.IdentifiedExtensionType.ID, SDC.null, SDC.BaseType.ObjectGUID.
Referenced by SDC.IdentifiedExtensionType.IdentifiedExtensionType.
SDC.IdentifiedExtensionType.IdentifiedExtensionType()
IdentifiedExtensionType SDC.IdentifiedExtensionType.FillIdentifiedExtensionType()
virtual bool SDC.IdentifiedExtensionType.ShouldSerializeID()
Test whether ID should be serialized
References SDC.IdentifiedExtensionType.ID.
virtual bool SDC.IdentifiedExtensionType.ShouldSerializebaseURI()
Test whether baseURI should be serialized
References SDC.IdentifiedExtensionType.baseURI.
virtual string SDC.IdentifiedExtensionType.Serialize(System.Text.Encoding encoding)
Serializes current IdentifiedExtensionType object into an XML string
string XML value
virtual string SDC.IdentifiedExtensionType.Serialize()
Referenced by SDC.IdentifiedExtensionType.SaveToFile.
virtual bool SDC.IdentifiedExtensionType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current IdentifiedExtensionType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.IdentifiedExtensionType.SaveToFile.
virtual bool SDC.IdentifiedExtensionType.SaveToFile(string fileName, out System.Exception exception)
References SDC.IdentifiedExtensionType.SaveToFile.
virtual void SDC.IdentifiedExtensionType.SaveToFile(string fileName)
References SDC.IdentifiedExtensionType.SaveToFile.
virtual void SDC.IdentifiedExtensionType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.IdentifiedExtensionType.Serialize.
virtual bool SDC.IdentifiedExtensionType.ShouldSerializeID()
Test whether ID should be serialized
References SDC.IdentifiedExtensionType.ID.
virtual bool SDC.IdentifiedExtensionType.ShouldSerializebaseURI()
Test whether baseURI should be serialized
References SDC.IdentifiedExtensionType.baseURI.
virtual string SDC.IdentifiedExtensionType.Serialize()
Serializes current IdentifiedExtensionType object into an XML string
string XML value
virtual bool SDC.IdentifiedExtensionType.SaveToFile(string fileName, out Exception exception)
Serializes current IdentifiedExtensionType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.IdentifiedExtensionType.SaveToFile.
virtual void SDC.IdentifiedExtensionType.SaveToFile(string fileName)
References SDC.null, SDC.IdentifiedExtensionType.Serialize.
virtual IdentifiedExtensionType SDC.IdentifiedExtensionType.Clone()
Create a clone of this IdentifiedExtensionType object
static bool SDC.IdentifiedExtensionType.Deserialize(string input, out IdentifiedExtensionType obj, out System.Exception exception)
Deserializes workflow markup into an IdentifiedExtensionType object
input string workflow markup to deserialize obj Output IdentifiedExtensionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.IdentifiedExtensionType.Deserialize, SDC.IdentifiedExtensionType.LoadFromFile.
static bool SDC.IdentifiedExtensionType.Deserialize(string input, out IdentifiedExtensionType obj)
References SDC.IdentifiedExtensionType.Deserialize, SDC.null.
static new IdentifiedExtensionType SDC.IdentifiedExtensionType.Deserialize(string input)
References SDC.null.
static IdentifiedExtensionType SDC.IdentifiedExtensionType.Deserialize(System.IO.Stream s)
References SDC.IdentifiedExtensionType.Serializer.
static bool SDC.IdentifiedExtensionType.LoadFromFile(string fileName, System.Text.Encoding encoding, out IdentifiedExtensionType obj, out System.Exception exception)
Deserializes xml markup from file into an IdentifiedExtensionType object
fileName string xml file to load and deserialize obj Output IdentifiedExtensionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.IdentifiedExtensionType.LoadFromFile.
static bool SDC.IdentifiedExtensionType.LoadFromFile(string fileName, out IdentifiedExtensionType obj, out System.Exception exception)
References SDC.IdentifiedExtensionType.LoadFromFile.
static bool SDC.IdentifiedExtensionType.LoadFromFile(string fileName, out IdentifiedExtensionType obj)
References SDC.IdentifiedExtensionType.LoadFromFile, SDC.null.
static IdentifiedExtensionType SDC.IdentifiedExtensionType.LoadFromFile(string fileName)
References SDC.IdentifiedExtensionType.LoadFromFile.
static new IdentifiedExtensionType SDC.IdentifiedExtensionType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.IdentifiedExtensionType.Deserialize, SDC.null.
static bool SDC.IdentifiedExtensionType.Deserialize(string input, out IdentifiedExtensionType obj, out Exception exception)
Deserializes workflow markup into an IdentifiedExtensionType object
input string workflow markup to deserialize obj Output IdentifiedExtensionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.IdentifiedExtensionType.Deserialize, SDC.null.
static bool SDC.IdentifiedExtensionType.Deserialize(string input, out IdentifiedExtensionType obj)
References SDC.IdentifiedExtensionType.Deserialize, SDC.null.
static new IdentifiedExtensionType SDC.IdentifiedExtensionType.Deserialize(string input)
References SDC.null, SDC.IdentifiedExtensionType.Serializer.
static IdentifiedExtensionType SDC.IdentifiedExtensionType.Deserialize(Stream s)
References SDC.IdentifiedExtensionType.Serializer.
static bool SDC.IdentifiedExtensionType.LoadFromFile(string fileName, out IdentifiedExtensionType obj, out Exception exception)
Deserializes xml markup from file into an IdentifiedExtensionType object
fileName string xml file to load and deserialize obj Output IdentifiedExtensionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.IdentifiedExtensionType.LoadFromFile, SDC.null.
static bool SDC.IdentifiedExtensionType.LoadFromFile(string fileName, out IdentifiedExtensionType obj)
References SDC.IdentifiedExtensionType.LoadFromFile, SDC.null.
static new IdentifiedExtensionType SDC.IdentifiedExtensionType.LoadFromFile(string fileName)
References SDC.IdentifiedExtensionType.Deserialize, SDC.null.