SDC::float_DEtype
bool SDC.float_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.float_DEtype.ShouldSerializemaxExclusive.
bool SDC.float_DEtype::_shouldSerializeminExclusive
Referenced by SDC.float_DEtype.ShouldSerializeminExclusive.
bool SDC.float_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.float_DEtype.ShouldSerializemaxInclusive.
bool SDC.float_DEtype::_shouldSerializeminInclusive
Referenced by SDC.float_DEtype.ShouldSerializeminInclusive.
System Nullable< float > SDC.float_DEtype::_minInclusive
Referenced by SDC.float_DEtype.ShouldSerializeminInclusive.
System Nullable< float > SDC.float_DEtype::_maxInclusive
Referenced by SDC.float_DEtype.ShouldSerializemaxInclusive.
System Nullable< float > SDC.float_DEtype::_minExclusive
Referenced by SDC.float_DEtype.ShouldSerializeminExclusive.
System Nullable< float > SDC.float_DEtype::_maxExclusive
Referenced by SDC.float_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.float_DEtype::_fractionDigits
System Nullable< byte > SDC.float_DEtype::_totalDigits
string SDC.float_DEtype::_mask
ObjectChangeTracker SDC.float_DEtype.changeTrackerField
static XmlSerializer SDC.float_DEtype::serializer
float SDC.float_DEtype::minInclusive
bool SDC.float_DEtype::minInclusiveSpecified
float SDC.float_DEtype::maxInclusive
bool SDC.float_DEtype::maxInclusiveSpecified
float SDC.float_DEtype::minExclusive
bool SDC.float_DEtype::minExclusiveSpecified
float SDC.float_DEtype::maxExclusive
bool SDC.float_DEtype::maxExclusiveSpecified
byte SDC.float_DEtype::fractionDigits
bool SDC.float_DEtype::fractionDigitsSpecified
byte SDC.float_DEtype::totalDigits
bool SDC.float_DEtype::totalDigitsSpecified
string SDC.float_DEtype::mask
Referenced by SDC.float_DEtype.ShouldSerializemask.
static XmlSerializer SDC.float_DEtype::Serializer
Referenced by SDC.float_DEtype.Deserialize.
ObjectChangeTracker SDC.float_DEtype.ChangeTracker
SDC.float_DEtype.float_DEtype()
SDC.float_DEtype.float_DEtype(BaseType parentNode)
virtual bool SDC.float_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.float_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.float_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.float_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.float_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.float_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current float_DEtype object into an XML string
string XML value
virtual string SDC.float_DEtype.Serialize()
Referenced by SDC.float_DEtype.SaveToFile.
virtual bool SDC.float_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current float_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.float_DEtype.SaveToFile.
virtual bool SDC.float_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.float_DEtype.SaveToFile(string fileName)
virtual void SDC.float_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.float_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.float_DEtype._minInclusive, SDC.float_DEtype._shouldSerializeminInclusive.
virtual bool SDC.float_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.float_DEtype._maxInclusive, SDC.float_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.float_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.float_DEtype._minExclusive, SDC.float_DEtype._shouldSerializeminExclusive.
virtual bool SDC.float_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.float_DEtype._maxExclusive, SDC.float_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.float_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.float_DEtype.mask.
virtual string SDC.float_DEtype.Serialize()
Serializes current float_DEtype object into an XML string
string XML value
virtual bool SDC.float_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current float_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.float_DEtype.SaveToFile.
virtual void SDC.float_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.float_DEtype.Serialize.
virtual float_DEtype SDC.float_DEtype.Clone()
Create a clone of this float_DEtype object
static bool SDC.float_DEtype.Deserialize(string input, out float_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an float_DEtype object
input string workflow markup to deserialize obj Output float_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.float_DEtype.Deserialize, SDC.float_DEtype.LoadFromFile.
static bool SDC.float_DEtype.Deserialize(string input, out float_DEtype obj)
References SDC.null.
static new float_DEtype SDC.float_DEtype.Deserialize(string input)
References SDC.null.
static float_DEtype SDC.float_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.float_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out float_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an float_DEtype object
fileName string xml file to load and deserialize obj Output float_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.float_DEtype.LoadFromFile.
static bool SDC.float_DEtype.LoadFromFile(string fileName, out float_DEtype obj, out System.Exception exception)
static bool SDC.float_DEtype.LoadFromFile(string fileName, out float_DEtype obj)
References SDC.null.
static float_DEtype SDC.float_DEtype.LoadFromFile(string fileName)
static new float_DEtype SDC.float_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.float_DEtype.Deserialize(string input, out float_DEtype obj, out Exception exception)
Deserializes workflow markup into an float_DEtype object
input string workflow markup to deserialize obj Output float_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.float_DEtype.Deserialize, SDC.null.
static bool SDC.float_DEtype.Deserialize(string input, out float_DEtype obj)
References SDC.float_DEtype.Deserialize, SDC.null.
static new float_DEtype SDC.float_DEtype.Deserialize(string input)
References SDC.null, SDC.float_DEtype.Serializer.
static float_DEtype SDC.float_DEtype.Deserialize(Stream s)
References SDC.float_DEtype.Serializer.
static bool SDC.float_DEtype.LoadFromFile(string fileName, out float_DEtype obj, out Exception exception)
Deserializes xml markup from file into an float_DEtype object
fileName string xml file to load and deserialize obj Output float_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.float_DEtype.LoadFromFile, SDC.null.
static bool SDC.float_DEtype.LoadFromFile(string fileName, out float_DEtype obj)
References SDC.float_DEtype.LoadFromFile, SDC.null.
static new float_DEtype SDC.float_DEtype.LoadFromFile(string fileName)
References SDC.float_DEtype.Deserialize, SDC.null.