SDC::ItemNameAttributeType
string SDC.ItemNameAttributeType._attributeName
XmlSerializer SDC.ItemNameAttributeType.serializer
virtual string SDC.ItemNameAttributeType.attributeName
Referenced by SDC.ItemNameAttributeType.ShouldSerializeattributeName.
XmlSerializer SDC.ItemNameAttributeType.Serializer
Referenced by SDC.ItemNameAttributeType.Deserialize.
SDC.ItemNameAttributeType.ItemNameAttributeType()
ItemNameAttributeType class constructor
virtual bool SDC.ItemNameAttributeType.ShouldSerializeattributeName()
Test whether attributeName should be serialized
References SDC.ItemNameAttributeType.attributeName.
virtual string SDC.ItemNameAttributeType.Serialize(System.Text.Encoding encoding)
Serializes current ItemNameAttributeType object into an XML string
string XML value
virtual string SDC.ItemNameAttributeType.Serialize()
Referenced by SDC.ItemNameAttributeType.SaveToFile.
virtual bool SDC.ItemNameAttributeType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ItemNameAttributeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ItemNameAttributeType.SaveToFile.
virtual bool SDC.ItemNameAttributeType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ItemNameAttributeType.SaveToFile.
virtual void SDC.ItemNameAttributeType.SaveToFile(string fileName)
References SDC.ItemNameAttributeType.SaveToFile.
virtual void SDC.ItemNameAttributeType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ItemNameAttributeType.Serialize.
static bool SDC.ItemNameAttributeType.Deserialize(string input, out ItemNameAttributeType obj, out System.Exception exception)
Deserializes workflow markup into an ItemNameAttributeType object
input string workflow markup to deserialize obj Output ItemNameAttributeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ItemNameAttributeType.Deserialize, SDC.ItemNameAttributeType.LoadFromFile.
static bool SDC.ItemNameAttributeType.Deserialize(string input, out ItemNameAttributeType obj)
References SDC.ItemNameAttributeType.Deserialize, SDC.null.
static new ItemNameAttributeType SDC.ItemNameAttributeType.Deserialize(string input)
References SDC.null.
static ItemNameAttributeType SDC.ItemNameAttributeType.Deserialize(System.IO.Stream s)
References SDC.ItemNameAttributeType.Serializer.
static bool SDC.ItemNameAttributeType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ItemNameAttributeType obj, out System.Exception exception)
Deserializes xml markup from file into an ItemNameAttributeType object
fileName string xml file to load and deserialize obj Output ItemNameAttributeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ItemNameAttributeType.LoadFromFile.
static bool SDC.ItemNameAttributeType.LoadFromFile(string fileName, out ItemNameAttributeType obj, out System.Exception exception)
References SDC.ItemNameAttributeType.LoadFromFile.
static bool SDC.ItemNameAttributeType.LoadFromFile(string fileName, out ItemNameAttributeType obj)
References SDC.ItemNameAttributeType.LoadFromFile, SDC.null.
static ItemNameAttributeType SDC.ItemNameAttributeType.LoadFromFile(string fileName)
References SDC.ItemNameAttributeType.LoadFromFile.
static new ItemNameAttributeType SDC.ItemNameAttributeType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ItemNameAttributeType.Deserialize, SDC.null.