SDC::decimal_Stype
bool SDC.decimal_Stype::_shouldSerializeval
Referenced by SDC.decimal_Stype.ShouldSerializeval.
System Nullable< decimal > SDC.decimal_Stype::_val
Referenced by SDC.decimal_Stype.ShouldSerializeval.
dtQuantEnum SDC.decimal_Stype::_quantEnum
Referenced by SDC.decimal_Stype.decimal_Stype.
ObjectChangeTracker SDC.decimal_Stype.changeTrackerField
static XmlSerializer SDC.decimal_Stype::serializer
decimal SDC.decimal_Stype::val
bool SDC.decimal_Stype::valSpecified
dtQuantEnum SDC.decimal_Stype::quantEnum
static XmlSerializer SDC.decimal_Stype::Serializer
Referenced by SDC.decimal_Stype.Deserialize.
ObjectChangeTracker SDC.decimal_Stype.ChangeTracker
SDC.decimal_Stype.decimal_Stype()
SDC.decimal_Stype.decimal_Stype(BaseType parentNode)
virtual bool SDC.decimal_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.decimal_Stype._shouldSerializeval, SDC.decimal_Stype._val, SDC.decimal.
virtual string SDC.decimal_Stype.Serialize(System.Text.Encoding encoding)
Serializes current decimal_Stype object into an XML string
string XML value
virtual string SDC.decimal_Stype.Serialize()
Referenced by SDC.decimal_Stype.SaveToFile.
virtual bool SDC.decimal_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current decimal_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.decimal_Stype.SaveToFile.
virtual bool SDC.decimal_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.decimal_Stype.SaveToFile.
virtual void SDC.decimal_Stype.SaveToFile(string fileName)
References SDC.decimal_Stype.SaveToFile.
virtual void SDC.decimal_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.decimal_Stype.Serialize.
SDC.decimal_Stype.decimal_Stype()
decimal_Stype class constructor
References SDC.decimal_Stype._quantEnum.
virtual bool SDC.decimal_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.decimal_Stype._shouldSerializeval, SDC.decimal_Stype._val, SDC.decimal.
virtual string SDC.decimal_Stype.Serialize()
Serializes current decimal_Stype object into an XML string
string XML value
virtual bool SDC.decimal_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current decimal_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.decimal_Stype.SaveToFile.
virtual void SDC.decimal_Stype.SaveToFile(string fileName)
References SDC.null, SDC.decimal_Stype.Serialize.
virtual decimal_Stype SDC.decimal_Stype.Clone()
Create a clone of this decimal_Stype object
static bool SDC.decimal_Stype.Deserialize(string input, out decimal_Stype obj, out System.Exception exception)
Deserializes workflow markup into an decimal_Stype object
input string workflow markup to deserialize obj Output decimal_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.decimal_Stype.Deserialize, SDC.decimal_Stype.LoadFromFile.
static bool SDC.decimal_Stype.Deserialize(string input, out decimal_Stype obj)
References SDC.decimal_Stype.Deserialize, SDC.null.
static new decimal_Stype SDC.decimal_Stype.Deserialize(string input)
References SDC.null.
static decimal_Stype SDC.decimal_Stype.Deserialize(System.IO.Stream s)
References SDC.decimal_Stype.Serializer.
static bool SDC.decimal_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out decimal_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an decimal_Stype object
fileName string xml file to load and deserialize obj Output decimal_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.decimal_Stype.LoadFromFile.
static bool SDC.decimal_Stype.LoadFromFile(string fileName, out decimal_Stype obj, out System.Exception exception)
References SDC.decimal_Stype.LoadFromFile.
static bool SDC.decimal_Stype.LoadFromFile(string fileName, out decimal_Stype obj)
References SDC.decimal_Stype.LoadFromFile, SDC.null.
static decimal_Stype SDC.decimal_Stype.LoadFromFile(string fileName)
References SDC.decimal_Stype.LoadFromFile.
static new decimal_Stype SDC.decimal_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.decimal_Stype.Deserialize, SDC.null.
static bool SDC.decimal_Stype.Deserialize(string input, out decimal_Stype obj, out Exception exception)
Deserializes workflow markup into an decimal_Stype object
input string workflow markup to deserialize obj Output decimal_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.decimal_Stype.Deserialize, SDC.null.
static bool SDC.decimal_Stype.Deserialize(string input, out decimal_Stype obj)
References SDC.decimal_Stype.Deserialize, SDC.null.
static new decimal_Stype SDC.decimal_Stype.Deserialize(string input)
References SDC.null, SDC.decimal_Stype.Serializer.
static decimal_Stype SDC.decimal_Stype.Deserialize(Stream s)
References SDC.decimal_Stype.Serializer.
static bool SDC.decimal_Stype.LoadFromFile(string fileName, out decimal_Stype obj, out Exception exception)
Deserializes xml markup from file into an decimal_Stype object
fileName string xml file to load and deserialize obj Output decimal_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.decimal_Stype.LoadFromFile, SDC.null.
static bool SDC.decimal_Stype.LoadFromFile(string fileName, out decimal_Stype obj)
References SDC.decimal_Stype.LoadFromFile, SDC.null.
static new decimal_Stype SDC.decimal_Stype.LoadFromFile(string fileName)
References SDC.decimal_Stype.Deserialize, SDC.null.