SDC::DataTypes_SType
BaseType SDC.DataTypes_SType::DataTypeS_Item
any *_SType data type
BaseType SDC.DataTypes_SType::Item
virtual ItemChoiceType SDC.DataTypes_SType.ItemElementName
static XmlSerializer SDC.DataTypes_SType::Serializer
Referenced by SDC.DataTypes_SType.Deserialize.
virtual ItemChoiceType1 SDC.DataTypes_SType.ItemElementName
ObjectChangeTracker SDC.DataTypes_SType.ChangeTracker
BaseType SDC.DataTypes_SType::_item
Referenced by SDC.DataTypes_SType.ShouldSerializeItem.
ItemChoiceType SDC.DataTypes_SType._itemElementName
ItemChoiceType1 SDC.DataTypes_SType._itemElementName
ObjectChangeTracker SDC.DataTypes_SType.changeTrackerField
static XmlSerializer SDC.DataTypes_SType::serializer
SDC.DataTypes_SType.DataTypes_SType()
SDC.DataTypes_SType.DataTypes_SType(BaseType parentNode)
SDC.DataTypes_SType.DataTypes_SType()
virtual bool SDC.DataTypes_SType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.null.
virtual string SDC.DataTypes_SType.Serialize(System.Text.Encoding encoding)
Serializes current DataTypes_SType object into an XML string
string XML value
virtual string SDC.DataTypes_SType.Serialize()
Referenced by SDC.DataTypes_SType.SaveToFile.
virtual bool SDC.DataTypes_SType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current DataTypes_SType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.DataTypes_SType.SaveToFile.
virtual bool SDC.DataTypes_SType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.DataTypes_SType.SaveToFile(string fileName)
virtual void SDC.DataTypes_SType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.DataTypes_SType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.DataTypes_SType._item, SDC.null.
virtual string SDC.DataTypes_SType.Serialize()
Serializes current DataTypes_SType object into an XML string
string XML value
virtual bool SDC.DataTypes_SType.SaveToFile(string fileName, out Exception exception)
Serializes current DataTypes_SType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.DataTypes_SType.SaveToFile.
virtual void SDC.DataTypes_SType.SaveToFile(string fileName)
References SDC.null, SDC.DataTypes_SType.Serialize.
virtual DataTypes_SType SDC.DataTypes_SType.Clone()
Create a clone of this DataTypes_SType object
static bool SDC.DataTypes_SType.Deserialize(string input, out DataTypes_SType obj, out System.Exception exception)
Deserializes workflow markup into an DataTypes_SType object
input string workflow markup to deserialize obj Output DataTypes_SType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DataTypes_SType.Deserialize, SDC.DataTypes_SType.LoadFromFile.
static bool SDC.DataTypes_SType.Deserialize(string input, out DataTypes_SType obj)
References SDC.null.
static new DataTypes_SType SDC.DataTypes_SType.Deserialize(string input)
References SDC.null.
static DataTypes_SType SDC.DataTypes_SType.Deserialize(System.IO.Stream s)
static bool SDC.DataTypes_SType.LoadFromFile(string fileName, System.Text.Encoding encoding, out DataTypes_SType obj, out System.Exception exception)
Deserializes xml markup from file into an DataTypes_SType object
fileName string xml file to load and deserialize obj Output DataTypes_SType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DataTypes_SType.LoadFromFile.
static bool SDC.DataTypes_SType.LoadFromFile(string fileName, out DataTypes_SType obj, out System.Exception exception)
static bool SDC.DataTypes_SType.LoadFromFile(string fileName, out DataTypes_SType obj)
References SDC.null.
static DataTypes_SType SDC.DataTypes_SType.LoadFromFile(string fileName)
static new DataTypes_SType SDC.DataTypes_SType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.DataTypes_SType.Deserialize(string input, out DataTypes_SType obj, out Exception exception)
Deserializes workflow markup into an DataTypes_SType object
input string workflow markup to deserialize obj Output DataTypes_SType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.DataTypes_SType.Deserialize, SDC.null.
static bool SDC.DataTypes_SType.Deserialize(string input, out DataTypes_SType obj)
References SDC.DataTypes_SType.Deserialize, SDC.null.
static new DataTypes_SType SDC.DataTypes_SType.Deserialize(string input)
References SDC.null, SDC.DataTypes_SType.Serializer.
static DataTypes_SType SDC.DataTypes_SType.Deserialize(Stream s)
References SDC.DataTypes_SType.Serializer.
static bool SDC.DataTypes_SType.LoadFromFile(string fileName, out DataTypes_SType obj, out Exception exception)
Deserializes xml markup from file into an DataTypes_SType object
fileName string xml file to load and deserialize obj Output DataTypes_SType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.DataTypes_SType.LoadFromFile, SDC.null.
static bool SDC.DataTypes_SType.LoadFromFile(string fileName, out DataTypes_SType obj)
References SDC.DataTypes_SType.LoadFromFile, SDC.null.
static new DataTypes_SType SDC.DataTypes_SType.LoadFromFile(string fileName)
References SDC.DataTypes_SType.Deserialize, SDC.null.