SDC::PhoneType
string_Stype SDC.PhoneType::_phoneType1
Referenced by SDC.PhoneType.ShouldSerializePhoneType1.
CountryCodeType SDC.PhoneType::_countryCode
Referenced by SDC.PhoneType.ShouldSerializeCountryCode.
AreaCodeType SDC.PhoneType::_areaCode
Referenced by SDC.PhoneType.ShouldSerializeAreaCode.
PhoneNumberType SDC.PhoneType::_phoneNumber
Referenced by SDC.PhoneType.ShouldSerializePhoneNumber.
string_Stype SDC.PhoneType::_phoneExtension
Referenced by SDC.PhoneType.ShouldSerializePhoneExtension.
string_Stype SDC.PhoneType::_usage
Referenced by SDC.PhoneType.ShouldSerializeUsage.
ObjectChangeTracker SDC.PhoneType.changeTrackerField
static XmlSerializer SDC.PhoneType::serializer
string_Stype SDC.PhoneType::PhoneType1
CountryCodeType SDC.PhoneType::CountryCode
AreaCodeType SDC.PhoneType::AreaCode
PhoneNumberType SDC.PhoneType::PhoneNumber
string_Stype SDC.PhoneType::PhoneExtension
string_Stype SDC.PhoneType::Usage
When this phone number should be used
static XmlSerializer SDC.PhoneType::Serializer
Referenced by SDC.PhoneType.Deserialize.
ObjectChangeTracker SDC.PhoneType.ChangeTracker
SDC.PhoneType.PhoneType()
SDC.PhoneType.PhoneType(BaseType parentNode)
virtual bool SDC.PhoneType.ShouldSerializePhoneType1()
Test whether PhoneType1 should be serialized
References SDC.null.
virtual bool SDC.PhoneType.ShouldSerializeCountryCode()
Test whether CountryCode should be serialized
References SDC.null.
virtual bool SDC.PhoneType.ShouldSerializeAreaCode()
Test whether AreaCode should be serialized
References SDC.null.
virtual bool SDC.PhoneType.ShouldSerializePhoneNumber()
Test whether PhoneNumber should be serialized
References SDC.null.
virtual bool SDC.PhoneType.ShouldSerializePhoneExtension()
Test whether PhoneExtension should be serialized
References SDC.null.
virtual bool SDC.PhoneType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.null.
virtual string SDC.PhoneType.Serialize(System.Text.Encoding encoding)
Serializes current PhoneType object into an XML string
string XML value
virtual string SDC.PhoneType.Serialize()
Referenced by SDC.PhoneType.SaveToFile.
virtual bool SDC.PhoneType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current PhoneType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.PhoneType.SaveToFile.
virtual bool SDC.PhoneType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.PhoneType.SaveToFile(string fileName)
virtual void SDC.PhoneType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.PhoneType.ShouldSerializePhoneType1()
Test whether PhoneType1 should be serialized
References SDC.PhoneType._phoneType1, SDC.null.
virtual bool SDC.PhoneType.ShouldSerializeCountryCode()
Test whether CountryCode should be serialized
References SDC.PhoneType._countryCode, SDC.null.
virtual bool SDC.PhoneType.ShouldSerializeAreaCode()
Test whether AreaCode should be serialized
References SDC.PhoneType._areaCode, SDC.null.
virtual bool SDC.PhoneType.ShouldSerializePhoneNumber()
Test whether PhoneNumber should be serialized
References SDC.PhoneType._phoneNumber, SDC.null.
virtual bool SDC.PhoneType.ShouldSerializePhoneExtension()
Test whether PhoneExtension should be serialized
References SDC.PhoneType._phoneExtension, SDC.null.
virtual bool SDC.PhoneType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.PhoneType._usage, SDC.null.
virtual string SDC.PhoneType.Serialize()
Serializes current PhoneType object into an XML string
string XML value
virtual bool SDC.PhoneType.SaveToFile(string fileName, out Exception exception)
Serializes current PhoneType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.PhoneType.SaveToFile.
virtual void SDC.PhoneType.SaveToFile(string fileName)
References SDC.null, SDC.PhoneType.Serialize.
virtual PhoneType SDC.PhoneType.Clone()
Create a clone of this PhoneType object
static bool SDC.PhoneType.Deserialize(string input, out PhoneType obj, out System.Exception exception)
Deserializes workflow markup into an PhoneType object
input string workflow markup to deserialize obj Output PhoneType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PhoneType.Deserialize, SDC.PhoneType.LoadFromFile.
static bool SDC.PhoneType.Deserialize(string input, out PhoneType obj)
References SDC.null.
static new PhoneType SDC.PhoneType.Deserialize(string input)
References SDC.null.
static PhoneType SDC.PhoneType.Deserialize(System.IO.Stream s)
static bool SDC.PhoneType.LoadFromFile(string fileName, System.Text.Encoding encoding, out PhoneType obj, out System.Exception exception)
Deserializes xml markup from file into an PhoneType object
fileName string xml file to load and deserialize obj Output PhoneType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PhoneType.LoadFromFile.
static bool SDC.PhoneType.LoadFromFile(string fileName, out PhoneType obj, out System.Exception exception)
static bool SDC.PhoneType.LoadFromFile(string fileName, out PhoneType obj)
References SDC.null.
static PhoneType SDC.PhoneType.LoadFromFile(string fileName)
static new PhoneType SDC.PhoneType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.PhoneType.Deserialize(string input, out PhoneType obj, out Exception exception)
Deserializes workflow markup into an PhoneType object
input string workflow markup to deserialize obj Output PhoneType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.PhoneType.Deserialize, SDC.null.
static bool SDC.PhoneType.Deserialize(string input, out PhoneType obj)
References SDC.PhoneType.Deserialize, SDC.null.
static new PhoneType SDC.PhoneType.Deserialize(string input)
References SDC.null, SDC.PhoneType.Serializer.
static PhoneType SDC.PhoneType.Deserialize(Stream s)
References SDC.PhoneType.Serializer.
static bool SDC.PhoneType.LoadFromFile(string fileName, out PhoneType obj, out Exception exception)
Deserializes xml markup from file into an PhoneType object
fileName string xml file to load and deserialize obj Output PhoneType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.PhoneType.LoadFromFile, SDC.null.
static bool SDC.PhoneType.LoadFromFile(string fileName, out PhoneType obj)
References SDC.PhoneType.LoadFromFile, SDC.null.
static new PhoneType SDC.PhoneType.LoadFromFile(string fileName)
References SDC.PhoneType.Deserialize, SDC.null.