SDC::SectionBaseType
bool SDC.SectionBaseType::_shouldSerializeordered
Referenced by SDC.SectionBaseType.ShouldSerializeordered.
bool SDC.SectionBaseType::_ordered
Referenced by SDC.SectionBaseType.SectionBaseType, SDC.SectionBaseType.ShouldSerializeordered.
System.Nullable<SectionBaseTypeResponseTypeEnum> SDC.SectionBaseType._responseTypeEnum
System.Nullable<SectionBaseTypeResponseStatusEnum> SDC.SectionBaseType._responseStatusEnum
ObjectChangeTracker SDC.SectionBaseType.changeTrackerField
static XmlSerializer SDC.SectionBaseType::serializer
bool SDC.SectionBaseType::ordered
SectionBaseType class constructor
If false, then the form implementation may change the order of items in the section.
virtual SectionBaseTypeResponseTypeEnum SDC.SectionBaseType.responseTypeEnum
virtual bool SDC.SectionBaseType.responseTypeEnumSpecified
virtual SectionBaseTypeResponseStatusEnum SDC.SectionBaseType.responseStatusEnum
virtual bool SDC.SectionBaseType.responseStatusEnumSpecified
static XmlSerializer SDC.SectionBaseType::Serializer
Referenced by SDC.SectionBaseType.Deserialize.
ObjectChangeTracker SDC.SectionBaseType.ChangeTracker
SDC.SectionBaseType.SectionBaseType()
SDC.SectionBaseType.SectionBaseType(BaseType parentNode, bool fillData=true, string id=null)
void SDC.SectionBaseType.Fill_SectionBaseType()
virtual bool SDC.SectionBaseType.ShouldSerializeordered()
Test whether ordered should be serialized
References SDC.SectionBaseType._ordered, SDC.SectionBaseType._shouldSerializeordered.
virtual string SDC.SectionBaseType.Serialize(System.Text.Encoding encoding)
Serializes current SectionBaseType object into an XML string
string XML value
virtual string SDC.SectionBaseType.Serialize()
Referenced by SDC.SectionBaseType.SaveToFile.
virtual bool SDC.SectionBaseType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current SectionBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.SectionBaseType.SaveToFile.
virtual bool SDC.SectionBaseType.SaveToFile(string fileName, out System.Exception exception)
References SDC.SectionBaseType.SaveToFile.
virtual void SDC.SectionBaseType.SaveToFile(string fileName)
References SDC.SectionBaseType.SaveToFile.
virtual void SDC.SectionBaseType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.SectionBaseType.Serialize.
SDC.SectionBaseType.SectionBaseType()
SectionBaseType class constructor
References SDC.SectionBaseType._ordered.
virtual bool SDC.SectionBaseType.ShouldSerializeordered()
Test whether ordered should be serialized
References SDC.SectionBaseType._ordered, SDC.SectionBaseType._shouldSerializeordered.
virtual string SDC.SectionBaseType.Serialize()
Serializes current SectionBaseType object into an XML string
string XML value
virtual bool SDC.SectionBaseType.SaveToFile(string fileName, out Exception exception)
Serializes current SectionBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.SectionBaseType.SaveToFile.
virtual void SDC.SectionBaseType.SaveToFile(string fileName)
References SDC.null, SDC.SectionBaseType.Serialize.
virtual SectionBaseType SDC.SectionBaseType.Clone()
Create a clone of this SectionBaseType object
static bool SDC.SectionBaseType.Deserialize(string input, out SectionBaseType obj, out System.Exception exception)
Deserializes workflow markup into an SectionBaseType object
input string workflow markup to deserialize obj Output SectionBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.SectionBaseType.Deserialize, SDC.SectionBaseType.LoadFromFile.
static bool SDC.SectionBaseType.Deserialize(string input, out SectionBaseType obj)
References SDC.SectionBaseType.Deserialize, SDC.null.
static new SectionBaseType SDC.SectionBaseType.Deserialize(string input)
References SDC.null.
static SectionBaseType SDC.SectionBaseType.Deserialize(System.IO.Stream s)
References SDC.SectionBaseType.Serializer.
static bool SDC.SectionBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding, out SectionBaseType obj, out System.Exception exception)
Deserializes xml markup from file into an SectionBaseType object
fileName string xml file to load and deserialize obj Output SectionBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.SectionBaseType.LoadFromFile.
static bool SDC.SectionBaseType.LoadFromFile(string fileName, out SectionBaseType obj, out System.Exception exception)
References SDC.SectionBaseType.LoadFromFile.
static bool SDC.SectionBaseType.LoadFromFile(string fileName, out SectionBaseType obj)
References SDC.SectionBaseType.LoadFromFile, SDC.null.
static SectionBaseType SDC.SectionBaseType.LoadFromFile(string fileName)
References SDC.SectionBaseType.LoadFromFile.
static new SectionBaseType SDC.SectionBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.SectionBaseType.Deserialize, SDC.null.
static bool SDC.SectionBaseType.Deserialize(string input, out SectionBaseType obj, out Exception exception)
Deserializes workflow markup into an SectionBaseType object
input string workflow markup to deserialize obj Output SectionBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.SectionBaseType.Deserialize, SDC.null.
static bool SDC.SectionBaseType.Deserialize(string input, out SectionBaseType obj)
References SDC.SectionBaseType.Deserialize, SDC.null.
static new SectionBaseType SDC.SectionBaseType.Deserialize(string input)
References SDC.null, SDC.SectionBaseType.Serializer.
static SectionBaseType SDC.SectionBaseType.Deserialize(Stream s)
References SDC.SectionBaseType.Serializer.
static bool SDC.SectionBaseType.LoadFromFile(string fileName, out SectionBaseType obj, out Exception exception)
Deserializes xml markup from file into an SectionBaseType object
fileName string xml file to load and deserialize obj Output SectionBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.SectionBaseType.LoadFromFile, SDC.null.
static bool SDC.SectionBaseType.LoadFromFile(string fileName, out SectionBaseType obj)
References SDC.SectionBaseType.LoadFromFile, SDC.null.
static new SectionBaseType SDC.SectionBaseType.LoadFromFile(string fileName)
References SDC.SectionBaseType.Deserialize, SDC.null.