SDC::boolean_Stype
bool SDC.boolean_Stype::_shouldSerializeval
Referenced by SDC.boolean_Stype.ShouldSerializeval.
System.Nullable<bool> SDC.boolean_Stype._val
Referenced by SDC.boolean_Stype.ShouldSerializeval.
bool SDC.boolean_Stype._val
ObjectChangeTracker SDC.boolean_Stype.changeTrackerField
static XmlSerializer SDC.boolean_Stype::serializer
bool SDC.boolean_Stype::val
bool SDC.boolean_Stype::valSpecified
static XmlSerializer SDC.boolean_Stype::Serializer
Referenced by SDC.boolean_Stype.Deserialize.
ObjectChangeTracker SDC.boolean_Stype.ChangeTracker
SDC.boolean_Stype.boolean_Stype()
SDC.boolean_Stype.boolean_Stype(BaseType parentNode)
virtual bool SDC.boolean_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.boolean_Stype._shouldSerializeval, SDC.boolean_Stype._val.
virtual string SDC.boolean_Stype.Serialize(System.Text.Encoding encoding)
Serializes current boolean_Stype object into an XML string
string XML value
virtual string SDC.boolean_Stype.Serialize()
Referenced by SDC.boolean_Stype.SaveToFile.
virtual bool SDC.boolean_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current boolean_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.boolean_Stype.SaveToFile.
virtual bool SDC.boolean_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.boolean_Stype.SaveToFile.
virtual void SDC.boolean_Stype.SaveToFile(string fileName)
References SDC.boolean_Stype.SaveToFile.
virtual void SDC.boolean_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.boolean_Stype.Serialize.
virtual bool SDC.boolean_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.boolean_Stype._shouldSerializeval, SDC.boolean_Stype._val.
virtual string SDC.boolean_Stype.Serialize()
Serializes current boolean_Stype object into an XML string
string XML value
virtual bool SDC.boolean_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current boolean_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.boolean_Stype.SaveToFile.
virtual void SDC.boolean_Stype.SaveToFile(string fileName)
References SDC.null, SDC.boolean_Stype.Serialize.
virtual boolean_Stype SDC.boolean_Stype.Clone()
Create a clone of this boolean_Stype object
static bool SDC.boolean_Stype.Deserialize(string input, out boolean_Stype obj, out System.Exception exception)
Deserializes workflow markup into an boolean_Stype object
input string workflow markup to deserialize obj Output boolean_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.boolean_Stype.Deserialize, SDC.boolean_Stype.LoadFromFile.
static bool SDC.boolean_Stype.Deserialize(string input, out boolean_Stype obj)
References SDC.boolean_Stype.Deserialize, SDC.null.
static new boolean_Stype SDC.boolean_Stype.Deserialize(string input)
References SDC.null.
static boolean_Stype SDC.boolean_Stype.Deserialize(System.IO.Stream s)
References SDC.boolean_Stype.Serializer.
static bool SDC.boolean_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out boolean_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an boolean_Stype object
fileName string xml file to load and deserialize obj Output boolean_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.boolean_Stype.LoadFromFile.
static bool SDC.boolean_Stype.LoadFromFile(string fileName, out boolean_Stype obj, out System.Exception exception)
References SDC.boolean_Stype.LoadFromFile.
static bool SDC.boolean_Stype.LoadFromFile(string fileName, out boolean_Stype obj)
References SDC.boolean_Stype.LoadFromFile, SDC.null.
static boolean_Stype SDC.boolean_Stype.LoadFromFile(string fileName)
References SDC.boolean_Stype.LoadFromFile.
static new boolean_Stype SDC.boolean_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.boolean_Stype.Deserialize, SDC.null.
static bool SDC.boolean_Stype.Deserialize(string input, out boolean_Stype obj, out Exception exception)
Deserializes workflow markup into an boolean_Stype object
input string workflow markup to deserialize obj Output boolean_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.boolean_Stype.Deserialize, SDC.null.
static bool SDC.boolean_Stype.Deserialize(string input, out boolean_Stype obj)
References SDC.boolean_Stype.Deserialize, SDC.null.
static new boolean_Stype SDC.boolean_Stype.Deserialize(string input)
References SDC.null, SDC.boolean_Stype.Serializer.
static boolean_Stype SDC.boolean_Stype.Deserialize(Stream s)
References SDC.boolean_Stype.Serializer.
static bool SDC.boolean_Stype.LoadFromFile(string fileName, out boolean_Stype obj, out Exception exception)
Deserializes xml markup from file into an boolean_Stype object
fileName string xml file to load and deserialize obj Output boolean_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.boolean_Stype.LoadFromFile, SDC.null.
static bool SDC.boolean_Stype.LoadFromFile(string fileName, out boolean_Stype obj)
References SDC.boolean_Stype.LoadFromFile, SDC.null.
static new boolean_Stype SDC.boolean_Stype.LoadFromFile(string fileName)
References SDC.boolean_Stype.Deserialize, SDC.null.