SDC::QuestionItemType
ChildItemsType SDC.QuestionItemType.ChildItemsNode
ChildItemsType SDC.QuestionItemType.ChildItems_Item
ChildItemsType SDC.QuestionItemType::Item1
static XmlSerializer SDC.QuestionItemType::Serializer
Referenced by SDC.QuestionItemType.Deserialize.
ObjectChangeTracker SDC.QuestionItemType.ChangeTracker
ChildItemsType SDC.QuestionItemType::_item1
Referenced by SDC.QuestionItemType.ShouldSerializeItem1.
ObjectChangeTracker SDC.QuestionItemType.changeTrackerField
static XmlSerializer SDC.QuestionItemType::serializer
SDC.QuestionItemType.QuestionItemType(BaseType parentNode, bool fillData=true, string id=null)
SDC.QuestionItemType.QuestionItemType()
SectionItemType SDC.QuestionItemType.AddSection(Boolean fillData=true, string id=null)
QuestionItemType SDC.QuestionItemType.AddQuestion(QuestionEnum qType, Boolean fillData=true, string id=null)
InjectFormType SDC.QuestionItemType.AddInjectedForm(Boolean fillData=true, string id=null)
ButtonItemType SDC.QuestionItemType.AddButtonAction(Boolean fillData=true, string id=null)
DisplayedType SDC.QuestionItemType.AddDisplayedItem(Boolean fillData=true, string id=null)
SDC.QuestionItemType.QuestionItemType()
SectionItemType SDC.QuestionItemType.AddSection()
QuestionItemType SDC.QuestionItemType.AddQuestion(ItemType qType)
InjectFormType SDC.QuestionItemType.AddInjectedForm()
ButtonItemType SDC.QuestionItemType.AddButtonAction()
DisplayedType SDC.QuestionItemType.AddDisplayedItem()
virtual bool SDC.QuestionItemType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.null.
virtual string SDC.QuestionItemType.Serialize(System.Text.Encoding encoding)
Serializes current QuestionItemType object into an XML string
string XML value
virtual string SDC.QuestionItemType.Serialize()
Referenced by SDC.QuestionItemType.SaveToFile.
virtual bool SDC.QuestionItemType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current QuestionItemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.QuestionItemType.SaveToFile.
virtual bool SDC.QuestionItemType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.QuestionItemType.SaveToFile(string fileName)
virtual void SDC.QuestionItemType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.QuestionItemType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.QuestionItemType._item1, SDC.null.
virtual string SDC.QuestionItemType.Serialize()
Serializes current QuestionItemType object into an XML string
string XML value
virtual bool SDC.QuestionItemType.SaveToFile(string fileName, out Exception exception)
Serializes current QuestionItemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.QuestionItemType.SaveToFile.
virtual void SDC.QuestionItemType.SaveToFile(string fileName)
References SDC.null, SDC.QuestionItemType.Serialize.
virtual QuestionItemType SDC.QuestionItemType.Clone()
Create a clone of this QuestionItemType object
static bool SDC.QuestionItemType.Deserialize(string input, out QuestionItemType obj, out System.Exception exception)
Deserializes workflow markup into an QuestionItemType object
input string workflow markup to deserialize obj Output QuestionItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.QuestionItemType.Deserialize, SDC.QuestionItemType.LoadFromFile.
static bool SDC.QuestionItemType.Deserialize(string input, out QuestionItemType obj)
References SDC.null.
static new QuestionItemType SDC.QuestionItemType.Deserialize(string input)
References SDC.null.
static QuestionItemType SDC.QuestionItemType.Deserialize(System.IO.Stream s)
static bool SDC.QuestionItemType.LoadFromFile(string fileName, System.Text.Encoding encoding, out QuestionItemType obj, out System.Exception exception)
Deserializes xml markup from file into an QuestionItemType object
fileName string xml file to load and deserialize obj Output QuestionItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.QuestionItemType.LoadFromFile.
static bool SDC.QuestionItemType.LoadFromFile(string fileName, out QuestionItemType obj, out System.Exception exception)
static bool SDC.QuestionItemType.LoadFromFile(string fileName, out QuestionItemType obj)
References SDC.null.
static QuestionItemType SDC.QuestionItemType.LoadFromFile(string fileName)
static new QuestionItemType SDC.QuestionItemType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.QuestionItemType.Deserialize(string input, out QuestionItemType obj, out Exception exception)
Deserializes workflow markup into an QuestionItemType object
input string workflow markup to deserialize obj Output QuestionItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.QuestionItemType.Deserialize, SDC.null.
static bool SDC.QuestionItemType.Deserialize(string input, out QuestionItemType obj)
References SDC.QuestionItemType.Deserialize, SDC.null.
static new QuestionItemType SDC.QuestionItemType.Deserialize(string input)
References SDC.null, SDC.QuestionItemType.Serializer.
static QuestionItemType SDC.QuestionItemType.Deserialize(Stream s)
References SDC.QuestionItemType.Serializer.
static bool SDC.QuestionItemType.LoadFromFile(string fileName, out QuestionItemType obj, out Exception exception)
Deserializes xml markup from file into an QuestionItemType object
fileName string xml file to load and deserialize obj Output QuestionItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.QuestionItemType.LoadFromFile, SDC.null.
static bool SDC.QuestionItemType.LoadFromFile(string fileName, out QuestionItemType obj)
References SDC.QuestionItemType.LoadFromFile, SDC.null.
static new QuestionItemType SDC.QuestionItemType.LoadFromFile(string fileName)
References SDC.QuestionItemType.Deserialize, SDC.null.