SDC::TargetItemIDType
string SDC.TargetItemIDType::_targetItemText
string SDC.TargetItemIDType::_targetProperty
ObjectChangeTracker SDC.TargetItemIDType.changeTrackerField
static XmlSerializer SDC.TargetItemIDType::serializer
string SDC.TargetItemIDType::targetItemText
Displayed text on the targetted item.
Referenced by SDC.TargetItemIDType.ShouldSerializetargetItemText.
string SDC.TargetItemIDType::targetProperty
Referenced by SDC.TargetItemIDType.ShouldSerializetargetProperty.
static XmlSerializer SDC.TargetItemIDType::Serializer
Referenced by SDC.TargetItemIDType.Deserialize.
ObjectChangeTracker SDC.TargetItemIDType.ChangeTracker
SDC.TargetItemIDType.TargetItemIDType()
SDC.TargetItemIDType.TargetItemIDType(BaseType parentNode)
virtual bool SDC.TargetItemIDType.ShouldSerializetargetItemText()
Test whether targetItemText should be serialized
virtual bool SDC.TargetItemIDType.ShouldSerializetargetProperty()
Test whether targetProperty should be serialized
virtual string SDC.TargetItemIDType.Serialize(System.Text.Encoding encoding)
Serializes current TargetItemIDType object into an XML string
string XML value
virtual string SDC.TargetItemIDType.Serialize()
Referenced by SDC.TargetItemIDType.SaveToFile.
virtual bool SDC.TargetItemIDType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current TargetItemIDType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.TargetItemIDType.SaveToFile.
virtual bool SDC.TargetItemIDType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.TargetItemIDType.SaveToFile(string fileName)
virtual void SDC.TargetItemIDType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.TargetItemIDType.ShouldSerializetargetItemText()
Test whether targetItemText should be serialized
References SDC.TargetItemIDType.targetItemText.
virtual bool SDC.TargetItemIDType.ShouldSerializetargetProperty()
Test whether targetProperty should be serialized
References SDC.TargetItemIDType.targetProperty.
virtual string SDC.TargetItemIDType.Serialize()
Serializes current TargetItemIDType object into an XML string
string XML value
virtual bool SDC.TargetItemIDType.SaveToFile(string fileName, out Exception exception)
Serializes current TargetItemIDType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.TargetItemIDType.SaveToFile.
virtual void SDC.TargetItemIDType.SaveToFile(string fileName)
References SDC.null, SDC.TargetItemIDType.Serialize.
virtual TargetItemIDType SDC.TargetItemIDType.Clone()
Create a clone of this TargetItemIDType object
static bool SDC.TargetItemIDType.Deserialize(string input, out TargetItemIDType obj, out System.Exception exception)
Deserializes workflow markup into an TargetItemIDType object
input string workflow markup to deserialize obj Output TargetItemIDType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.TargetItemIDType.Deserialize, SDC.TargetItemIDType.LoadFromFile.
static bool SDC.TargetItemIDType.Deserialize(string input, out TargetItemIDType obj)
References SDC.null.
static new TargetItemIDType SDC.TargetItemIDType.Deserialize(string input)
References SDC.null.
static TargetItemIDType SDC.TargetItemIDType.Deserialize(System.IO.Stream s)
static bool SDC.TargetItemIDType.LoadFromFile(string fileName, System.Text.Encoding encoding, out TargetItemIDType obj, out System.Exception exception)
Deserializes xml markup from file into an TargetItemIDType object
fileName string xml file to load and deserialize obj Output TargetItemIDType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.TargetItemIDType.LoadFromFile.
static bool SDC.TargetItemIDType.LoadFromFile(string fileName, out TargetItemIDType obj, out System.Exception exception)
static bool SDC.TargetItemIDType.LoadFromFile(string fileName, out TargetItemIDType obj)
References SDC.null.
static TargetItemIDType SDC.TargetItemIDType.LoadFromFile(string fileName)
static new TargetItemIDType SDC.TargetItemIDType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.TargetItemIDType.Deserialize(string input, out TargetItemIDType obj, out Exception exception)
Deserializes workflow markup into an TargetItemIDType object
input string workflow markup to deserialize obj Output TargetItemIDType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.TargetItemIDType.Deserialize, SDC.null.
static bool SDC.TargetItemIDType.Deserialize(string input, out TargetItemIDType obj)
References SDC.TargetItemIDType.Deserialize, SDC.null.
static new TargetItemIDType SDC.TargetItemIDType.Deserialize(string input)
References SDC.null, SDC.TargetItemIDType.Serializer.
static TargetItemIDType SDC.TargetItemIDType.Deserialize(Stream s)
References SDC.TargetItemIDType.Serializer.
static bool SDC.TargetItemIDType.LoadFromFile(string fileName, out TargetItemIDType obj, out Exception exception)
Deserializes xml markup from file into an TargetItemIDType object
fileName string xml file to load and deserialize obj Output TargetItemIDType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.TargetItemIDType.LoadFromFile, SDC.null.
static bool SDC.TargetItemIDType.LoadFromFile(string fileName, out TargetItemIDType obj)
References SDC.TargetItemIDType.LoadFromFile, SDC.null.
static new TargetItemIDType SDC.TargetItemIDType.LoadFromFile(string fileName)
References SDC.TargetItemIDType.Deserialize, SDC.null.