SDC::integer_DEtype
string SDC.integer_DEtype::_maxExclusive
string SDC.integer_DEtype::_minExclusive
string SDC.integer_DEtype::_maxInclusive
string SDC.integer_DEtype::_minInclusive
System Nullable< byte > SDC.integer_DEtype::_totalDigits
string SDC.integer_DEtype::_mask
ObjectChangeTracker SDC.integer_DEtype.changeTrackerField
static XmlSerializer SDC.integer_DEtype::serializer
string SDC.integer_DEtype::maxExclusive
Referenced by SDC.integer_DEtype.ShouldSerializemaxExclusive.
string SDC.integer_DEtype::minExclusive
Referenced by SDC.integer_DEtype.ShouldSerializeminExclusive.
string SDC.integer_DEtype::maxInclusive
Referenced by SDC.integer_DEtype.ShouldSerializemaxInclusive.
string SDC.integer_DEtype::minInclusive
Referenced by SDC.integer_DEtype.ShouldSerializeminInclusive.
byte SDC.integer_DEtype::totalDigits
bool SDC.integer_DEtype::totalDigitsSpecified
string SDC.integer_DEtype::mask
Referenced by SDC.integer_DEtype.ShouldSerializemask.
static XmlSerializer SDC.integer_DEtype::Serializer
Referenced by SDC.integer_DEtype.Deserialize.
ObjectChangeTracker SDC.integer_DEtype.ChangeTracker
SDC.integer_DEtype.integer_DEtype()
SDC.integer_DEtype.integer_DEtype(BaseType parentNode)
virtual bool SDC.integer_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.integer_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.integer_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.integer_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.integer_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.integer_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current integer_DEtype object into an XML string
string XML value
virtual string SDC.integer_DEtype.Serialize()
Referenced by SDC.integer_DEtype.SaveToFile.
virtual bool SDC.integer_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current integer_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.integer_DEtype.SaveToFile.
virtual bool SDC.integer_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.integer_DEtype.SaveToFile(string fileName)
virtual void SDC.integer_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.integer_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.integer_DEtype.maxExclusive.
virtual bool SDC.integer_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.integer_DEtype.minExclusive.
virtual bool SDC.integer_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.integer_DEtype.maxInclusive.
virtual bool SDC.integer_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.integer_DEtype.minInclusive.
virtual bool SDC.integer_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.integer_DEtype.mask.
virtual string SDC.integer_DEtype.Serialize()
Serializes current integer_DEtype object into an XML string
string XML value
virtual bool SDC.integer_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current integer_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.integer_DEtype.SaveToFile.
virtual void SDC.integer_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.integer_DEtype.Serialize.
virtual integer_DEtype SDC.integer_DEtype.Clone()
Create a clone of this integer_DEtype object
static bool SDC.integer_DEtype.Deserialize(string input, out integer_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an integer_DEtype object
input string workflow markup to deserialize obj Output integer_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.integer_DEtype.Deserialize, SDC.integer_DEtype.LoadFromFile.
static bool SDC.integer_DEtype.Deserialize(string input, out integer_DEtype obj)
References SDC.null.
static new integer_DEtype SDC.integer_DEtype.Deserialize(string input)
References SDC.null.
static integer_DEtype SDC.integer_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.integer_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out integer_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an integer_DEtype object
fileName string xml file to load and deserialize obj Output integer_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.integer_DEtype.LoadFromFile.
static bool SDC.integer_DEtype.LoadFromFile(string fileName, out integer_DEtype obj, out System.Exception exception)
static bool SDC.integer_DEtype.LoadFromFile(string fileName, out integer_DEtype obj)
References SDC.null.
static integer_DEtype SDC.integer_DEtype.LoadFromFile(string fileName)
static new integer_DEtype SDC.integer_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.integer_DEtype.Deserialize(string input, out integer_DEtype obj, out Exception exception)
Deserializes workflow markup into an integer_DEtype object
input string workflow markup to deserialize obj Output integer_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.integer_DEtype.Deserialize, SDC.null.
static bool SDC.integer_DEtype.Deserialize(string input, out integer_DEtype obj)
References SDC.integer_DEtype.Deserialize, SDC.null.
static new integer_DEtype SDC.integer_DEtype.Deserialize(string input)
References SDC.null, SDC.integer_DEtype.Serializer.
static integer_DEtype SDC.integer_DEtype.Deserialize(Stream s)
References SDC.integer_DEtype.Serializer.
static bool SDC.integer_DEtype.LoadFromFile(string fileName, out integer_DEtype obj, out Exception exception)
Deserializes xml markup from file into an integer_DEtype object
fileName string xml file to load and deserialize obj Output integer_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.integer_DEtype.LoadFromFile, SDC.null.
static bool SDC.integer_DEtype.LoadFromFile(string fileName, out integer_DEtype obj)
References SDC.integer_DEtype.LoadFromFile, SDC.null.
static new integer_DEtype SDC.integer_DEtype.LoadFromFile(string fileName)
References SDC.integer_DEtype.Deserialize, SDC.null.