SDC::boolean_DEtype
static XmlSerializer SDC.boolean_DEtype::serializer
static XmlSerializer SDC.boolean_DEtype::Serializer
Referenced by SDC.boolean_DEtype.Deserialize.
ObjectChangeTracker SDC.boolean_DEtype.ChangeTracker
ObjectChangeTracker SDC.boolean_DEtype.changeTrackerField
SDC.boolean_DEtype.boolean_DEtype()
SDC.boolean_DEtype.boolean_DEtype(BaseType parentNode)
virtual string SDC.boolean_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current boolean_DEtype object into an XML string
string XML value
virtual string SDC.boolean_DEtype.Serialize()
Referenced by SDC.boolean_DEtype.SaveToFile.
virtual bool SDC.boolean_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current boolean_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.boolean_DEtype.SaveToFile.
virtual bool SDC.boolean_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.boolean_DEtype.SaveToFile(string fileName)
virtual void SDC.boolean_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.boolean_DEtype.Serialize()
Serializes current boolean_DEtype object into an XML string
string XML value
virtual bool SDC.boolean_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current boolean_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.boolean_DEtype.SaveToFile.
virtual void SDC.boolean_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.boolean_DEtype.Serialize.
virtual boolean_DEtype SDC.boolean_DEtype.Clone()
Create a clone of this boolean_DEtype object
static bool SDC.boolean_DEtype.Deserialize(string input, out boolean_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an boolean_DEtype object
input string workflow markup to deserialize obj Output boolean_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.boolean_DEtype.Deserialize, SDC.boolean_DEtype.LoadFromFile.
static bool SDC.boolean_DEtype.Deserialize(string input, out boolean_DEtype obj)
References SDC.null.
static new boolean_DEtype SDC.boolean_DEtype.Deserialize(string input)
References SDC.null.
static boolean_DEtype SDC.boolean_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.boolean_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out boolean_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an boolean_DEtype object
fileName string xml file to load and deserialize obj Output boolean_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.boolean_DEtype.LoadFromFile.
static bool SDC.boolean_DEtype.LoadFromFile(string fileName, out boolean_DEtype obj, out System.Exception exception)
static bool SDC.boolean_DEtype.LoadFromFile(string fileName, out boolean_DEtype obj)
References SDC.null.
static boolean_DEtype SDC.boolean_DEtype.LoadFromFile(string fileName)
static new boolean_DEtype SDC.boolean_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.boolean_DEtype.Deserialize(string input, out boolean_DEtype obj, out Exception exception)
Deserializes workflow markup into an boolean_DEtype object
input string workflow markup to deserialize obj Output boolean_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.boolean_DEtype.Deserialize, SDC.null.
static bool SDC.boolean_DEtype.Deserialize(string input, out boolean_DEtype obj)
References SDC.boolean_DEtype.Deserialize, SDC.null.
static new boolean_DEtype SDC.boolean_DEtype.Deserialize(string input)
References SDC.null, SDC.boolean_DEtype.Serializer.
static boolean_DEtype SDC.boolean_DEtype.Deserialize(Stream s)
References SDC.boolean_DEtype.Serializer.
static bool SDC.boolean_DEtype.LoadFromFile(string fileName, out boolean_DEtype obj, out Exception exception)
Deserializes xml markup from file into an boolean_DEtype object
fileName string xml file to load and deserialize obj Output boolean_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.boolean_DEtype.LoadFromFile, SDC.null.
static bool SDC.boolean_DEtype.LoadFromFile(string fileName, out boolean_DEtype obj)
References SDC.boolean_DEtype.LoadFromFile, SDC.null.
static new boolean_DEtype SDC.boolean_DEtype.LoadFromFile(string fileName)
References SDC.boolean_DEtype.Deserialize, SDC.null.