SDC::ChangeLogType
ChangedFieldType SDC.ChangeLogType::_changedField
Referenced by SDC.ChangeLogType.ShouldSerializeChangedField.
DataTypes_SType SDC.ChangeLogType::_changedTo
Referenced by SDC.ChangeLogType.ShouldSerializeChangedTo.
DataTypes_SType SDC.ChangeLogType::_changedFrom
Referenced by SDC.ChangeLogType.ShouldSerializeChangedFrom.
List<string_Stype> SDC.ChangeLogType._changeType
ReplacedIDsType SDC.ChangeLogType::_replaces
Referenced by SDC.ChangeLogType.ShouldSerializeReplaces.
dateTime_Stype SDC.ChangeLogType::_changeDate
Referenced by SDC.ChangeLogType.ShouldSerializeChangeDate.
string_Stype SDC.ChangeLogType::_changeDescription
Referenced by SDC.ChangeLogType.ShouldSerializeChangeDescription.
ContactsType SDC.ChangeLogType::_editors
Referenced by SDC.ChangeLogType.ShouldSerializeEditors.
ChangeTrackingType SDC.ChangeLogType::_changeTracking
Referenced by SDC.ChangeLogType.ShouldSerializeChangeTracking.
BindingList<string_Stype> SDC.ChangeLogType._changeType
ObjectChangeTracker SDC.ChangeLogType.changeTrackerField
static XmlSerializer SDC.ChangeLogType::serializer
ChangedFieldType SDC.ChangeLogType::ChangedField
DataTypes_SType SDC.ChangeLogType::ChangedTo
DataTypes_SType SDC.ChangeLogType::ChangedFrom
virtual List<string_Stype> SDC.ChangeLogType.ChangeType
ReplacedIDsType SDC.ChangeLogType::Replaces
The retired/deprecated item that is being replaced.
dateTime_Stype SDC.ChangeLogType::ChangeDate
string_Stype SDC.ChangeLogType::ChangeDescription
ContactsType SDC.ChangeLogType::Editors
ChangeTrackingType SDC.ChangeLogType::ChangeTracking
static XmlSerializer SDC.ChangeLogType::Serializer
Referenced by SDC.ChangeLogType.Deserialize.
virtual BindingList<string_Stype> SDC.ChangeLogType.ChangeType
ObjectChangeTracker SDC.ChangeLogType.ChangeTracker
virtual bool SDC.ChangeLogType.ShouldSerializeChangeType()
Test whether ChangeType should be serialized
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangedField()
Test whether ChangedField should be serialized
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangedTo()
Test whether ChangedTo should be serialized
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangedFrom()
Test whether ChangedFrom should be serialized
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeReplaces()
Test whether Replaces should be serialized
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangeDate()
Test whether ChangeDate should be serialized
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangeDescription()
Test whether ChangeDescription should be serialized
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeEditors()
Test whether Editors should be serialized
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangeTracking()
Test whether ChangeTracking should be serialized
References SDC.null.
virtual string SDC.ChangeLogType.Serialize(System.Text.Encoding encoding)
Serializes current ChangeLogType object into an XML string
string XML value
virtual string SDC.ChangeLogType.Serialize()
Referenced by SDC.ChangeLogType.SaveToFile.
virtual bool SDC.ChangeLogType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ChangeLogType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ChangeLogType.SaveToFile.
virtual bool SDC.ChangeLogType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ChangeLogType.SaveToFile(string fileName)
virtual void SDC.ChangeLogType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangedField()
Test whether ChangedField should be serialized
References SDC.ChangeLogType._changedField, SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangedTo()
Test whether ChangedTo should be serialized
References SDC.ChangeLogType._changedTo, SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangedFrom()
Test whether ChangedFrom should be serialized
References SDC.ChangeLogType._changedFrom, SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeReplaces()
Test whether Replaces should be serialized
References SDC.ChangeLogType._replaces, SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangeDate()
Test whether ChangeDate should be serialized
References SDC.ChangeLogType._changeDate, SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangeDescription()
Test whether ChangeDescription should be serialized
References SDC.ChangeLogType._changeDescription, SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeEditors()
Test whether Editors should be serialized
References SDC.ChangeLogType._editors, SDC.null.
virtual bool SDC.ChangeLogType.ShouldSerializeChangeTracking()
Test whether ChangeTracking should be serialized
References SDC.ChangeLogType._changeTracking, SDC.null.
virtual string SDC.ChangeLogType.Serialize()
Serializes current ChangeLogType object into an XML string
string XML value
virtual bool SDC.ChangeLogType.SaveToFile(string fileName, out Exception exception)
Serializes current ChangeLogType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ChangeLogType.SaveToFile.
virtual void SDC.ChangeLogType.SaveToFile(string fileName)
References SDC.null, SDC.ChangeLogType.Serialize.
virtual ChangeLogType SDC.ChangeLogType.Clone()
Create a clone of this ChangeLogType object
static bool SDC.ChangeLogType.Deserialize(string input, out ChangeLogType obj, out System.Exception exception)
Deserializes workflow markup into an ChangeLogType object
input string workflow markup to deserialize obj Output ChangeLogType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangeLogType.Deserialize, SDC.ChangeLogType.LoadFromFile.
static bool SDC.ChangeLogType.Deserialize(string input, out ChangeLogType obj)
References SDC.null.
static new ChangeLogType SDC.ChangeLogType.Deserialize(string input)
References SDC.null.
static ChangeLogType SDC.ChangeLogType.Deserialize(System.IO.Stream s)
static bool SDC.ChangeLogType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ChangeLogType obj, out System.Exception exception)
Deserializes xml markup from file into an ChangeLogType object
fileName string xml file to load and deserialize obj Output ChangeLogType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangeLogType.LoadFromFile.
static bool SDC.ChangeLogType.LoadFromFile(string fileName, out ChangeLogType obj, out System.Exception exception)
static bool SDC.ChangeLogType.LoadFromFile(string fileName, out ChangeLogType obj)
References SDC.null.
static ChangeLogType SDC.ChangeLogType.LoadFromFile(string fileName)
static new ChangeLogType SDC.ChangeLogType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ChangeLogType.Deserialize(string input, out ChangeLogType obj, out Exception exception)
Deserializes workflow markup into an ChangeLogType object
input string workflow markup to deserialize obj Output ChangeLogType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChangeLogType.Deserialize, SDC.null.
static bool SDC.ChangeLogType.Deserialize(string input, out ChangeLogType obj)
References SDC.ChangeLogType.Deserialize, SDC.null.
static new ChangeLogType SDC.ChangeLogType.Deserialize(string input)
References SDC.null, SDC.ChangeLogType.Serializer.
static ChangeLogType SDC.ChangeLogType.Deserialize(Stream s)
References SDC.ChangeLogType.Serializer.
static bool SDC.ChangeLogType.LoadFromFile(string fileName, out ChangeLogType obj, out Exception exception)
Deserializes xml markup from file into an ChangeLogType object
fileName string xml file to load and deserialize obj Output ChangeLogType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChangeLogType.LoadFromFile, SDC.null.
static bool SDC.ChangeLogType.LoadFromFile(string fileName, out ChangeLogType obj)
References SDC.ChangeLogType.LoadFromFile, SDC.null.
static new ChangeLogType SDC.ChangeLogType.LoadFromFile(string fileName)
References SDC.ChangeLogType.Deserialize, SDC.null.