SDC::anyURI_DEtype
bool SDC.anyURI_DEtype::_shouldSerializemaxLength
Referenced by SDC.anyURI_DEtype.ShouldSerializemaxLength.
bool SDC.anyURI_DEtype::_shouldSerializeminLength
Referenced by SDC.anyURI_DEtype.ShouldSerializeminLength.
bool SDC.anyURI_DEtype::_shouldSerializelength
Referenced by SDC.anyURI_DEtype.ShouldSerializelength.
System Nullable< long > SDC.anyURI_DEtype::_length
Referenced by SDC.anyURI_DEtype.ShouldSerializelength.
System Nullable< long > SDC.anyURI_DEtype::_minLength
Referenced by SDC.anyURI_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.anyURI_DEtype::_maxLength
Referenced by SDC.anyURI_DEtype.ShouldSerializemaxLength.
string SDC.anyURI_DEtype::_pattern
ObjectChangeTracker SDC.anyURI_DEtype.changeTrackerField
static XmlSerializer SDC.anyURI_DEtype::serializer
long SDC.anyURI_DEtype::length
bool SDC.anyURI_DEtype::lengthSpecified
long SDC.anyURI_DEtype::minLength
bool SDC.anyURI_DEtype::minLengthSpecified
long SDC.anyURI_DEtype::maxLength
bool SDC.anyURI_DEtype::maxLengthSpecified
string SDC.anyURI_DEtype::pattern
Referenced by SDC.anyURI_DEtype.ShouldSerializepattern.
static XmlSerializer SDC.anyURI_DEtype::Serializer
Referenced by SDC.anyURI_DEtype.Deserialize.
ObjectChangeTracker SDC.anyURI_DEtype.ChangeTracker
SDC.anyURI_DEtype.anyURI_DEtype()
SDC.anyURI_DEtype.anyURI_DEtype(BaseType parentNode)
virtual bool SDC.anyURI_DEtype.ShouldSerializelength()
Test whether length should be serialized
virtual bool SDC.anyURI_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
virtual bool SDC.anyURI_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
virtual bool SDC.anyURI_DEtype.ShouldSerializepattern()
Test whether pattern should be serialized
virtual string SDC.anyURI_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current anyURI_DEtype object into an XML string
string XML value
virtual string SDC.anyURI_DEtype.Serialize()
Referenced by SDC.anyURI_DEtype.SaveToFile.
virtual bool SDC.anyURI_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current anyURI_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.anyURI_DEtype.SaveToFile.
virtual bool SDC.anyURI_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.anyURI_DEtype.SaveToFile(string fileName)
virtual void SDC.anyURI_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.anyURI_DEtype.ShouldSerializelength()
Test whether length should be serialized
References SDC.anyURI_DEtype._length, SDC.anyURI_DEtype._shouldSerializelength.
virtual bool SDC.anyURI_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
References SDC.anyURI_DEtype._minLength, SDC.anyURI_DEtype._shouldSerializeminLength.
virtual bool SDC.anyURI_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
References SDC.anyURI_DEtype._maxLength, SDC.anyURI_DEtype._shouldSerializemaxLength.
virtual bool SDC.anyURI_DEtype.ShouldSerializepattern()
Test whether pattern should be serialized
References SDC.anyURI_DEtype.pattern.
virtual string SDC.anyURI_DEtype.Serialize()
Serializes current anyURI_DEtype object into an XML string
string XML value
virtual bool SDC.anyURI_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current anyURI_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.anyURI_DEtype.SaveToFile.
virtual void SDC.anyURI_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.anyURI_DEtype.Serialize.
virtual anyURI_DEtype SDC.anyURI_DEtype.Clone()
Create a clone of this anyURI_DEtype object
static bool SDC.anyURI_DEtype.Deserialize(string input, out anyURI_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an anyURI_DEtype object
input string workflow markup to deserialize obj Output anyURI_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.anyURI_DEtype.Deserialize, SDC.anyURI_DEtype.LoadFromFile.
static bool SDC.anyURI_DEtype.Deserialize(string input, out anyURI_DEtype obj)
References SDC.null.
static new anyURI_DEtype SDC.anyURI_DEtype.Deserialize(string input)
References SDC.null.
static anyURI_DEtype SDC.anyURI_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.anyURI_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out anyURI_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an anyURI_DEtype object
fileName string xml file to load and deserialize obj Output anyURI_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.anyURI_DEtype.LoadFromFile.
static bool SDC.anyURI_DEtype.LoadFromFile(string fileName, out anyURI_DEtype obj, out System.Exception exception)
static bool SDC.anyURI_DEtype.LoadFromFile(string fileName, out anyURI_DEtype obj)
References SDC.null.
static anyURI_DEtype SDC.anyURI_DEtype.LoadFromFile(string fileName)
static new anyURI_DEtype SDC.anyURI_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.anyURI_DEtype.Deserialize(string input, out anyURI_DEtype obj, out Exception exception)
Deserializes workflow markup into an anyURI_DEtype object
input string workflow markup to deserialize obj Output anyURI_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.anyURI_DEtype.Deserialize, SDC.null.
static bool SDC.anyURI_DEtype.Deserialize(string input, out anyURI_DEtype obj)
References SDC.anyURI_DEtype.Deserialize, SDC.null.
static new anyURI_DEtype SDC.anyURI_DEtype.Deserialize(string input)
References SDC.null, SDC.anyURI_DEtype.Serializer.
static anyURI_DEtype SDC.anyURI_DEtype.Deserialize(Stream s)
References SDC.anyURI_DEtype.Serializer.
static bool SDC.anyURI_DEtype.LoadFromFile(string fileName, out anyURI_DEtype obj, out Exception exception)
Deserializes xml markup from file into an anyURI_DEtype object
fileName string xml file to load and deserialize obj Output anyURI_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.anyURI_DEtype.LoadFromFile, SDC.null.
static bool SDC.anyURI_DEtype.LoadFromFile(string fileName, out anyURI_DEtype obj)
References SDC.anyURI_DEtype.LoadFromFile, SDC.null.
static new anyURI_DEtype SDC.anyURI_DEtype.LoadFromFile(string fileName)
References SDC.anyURI_DEtype.Deserialize, SDC.null.