SDC::unsignedLong_Stype
bool SDC.unsignedLong_Stype::_shouldSerializeval
Referenced by SDC.unsignedLong_Stype.ShouldSerializeval.
System Nullable< ulong > SDC.unsignedLong_Stype::_val
Referenced by SDC.unsignedLong_Stype.ShouldSerializeval.
dtQuantEnum SDC.unsignedLong_Stype::_quantEnum
Referenced by SDC.unsignedLong_Stype.unsignedLong_Stype.
ObjectChangeTracker SDC.unsignedLong_Stype.changeTrackerField
static XmlSerializer SDC.unsignedLong_Stype::serializer
ulong SDC.unsignedLong_Stype::val
bool SDC.unsignedLong_Stype::valSpecified
dtQuantEnum SDC.unsignedLong_Stype::quantEnum
static XmlSerializer SDC.unsignedLong_Stype::Serializer
Referenced by SDC.unsignedLong_Stype.Deserialize.
ObjectChangeTracker SDC.unsignedLong_Stype.ChangeTracker
SDC.unsignedLong_Stype.unsignedLong_Stype()
SDC.unsignedLong_Stype.unsignedLong_Stype(BaseType parentNode)
virtual bool SDC.unsignedLong_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.unsignedLong_Stype._shouldSerializeval, SDC.unsignedLong_Stype._val.
virtual string SDC.unsignedLong_Stype.Serialize(System.Text.Encoding encoding)
Serializes current unsignedLong_Stype object into an XML string
string XML value
virtual string SDC.unsignedLong_Stype.Serialize()
Referenced by SDC.unsignedLong_Stype.SaveToFile.
virtual bool SDC.unsignedLong_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current unsignedLong_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.unsignedLong_Stype.SaveToFile.
virtual bool SDC.unsignedLong_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.unsignedLong_Stype.SaveToFile.
virtual void SDC.unsignedLong_Stype.SaveToFile(string fileName)
References SDC.unsignedLong_Stype.SaveToFile.
virtual void SDC.unsignedLong_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.unsignedLong_Stype.Serialize.
SDC.unsignedLong_Stype.unsignedLong_Stype()
unsignedLong_Stype class constructor
References SDC.unsignedLong_Stype._quantEnum.
virtual bool SDC.unsignedLong_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.unsignedLong_Stype._shouldSerializeval, SDC.unsignedLong_Stype._val.
virtual string SDC.unsignedLong_Stype.Serialize()
Serializes current unsignedLong_Stype object into an XML string
string XML value
virtual bool SDC.unsignedLong_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current unsignedLong_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.unsignedLong_Stype.SaveToFile.
virtual void SDC.unsignedLong_Stype.SaveToFile(string fileName)
References SDC.null, SDC.unsignedLong_Stype.Serialize.
virtual unsignedLong_Stype SDC.unsignedLong_Stype.Clone()
Create a clone of this unsignedLong_Stype object
static bool SDC.unsignedLong_Stype.Deserialize(string input, out unsignedLong_Stype obj, out System.Exception exception)
Deserializes workflow markup into an unsignedLong_Stype object
input string workflow markup to deserialize obj Output unsignedLong_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedLong_Stype.Deserialize, SDC.unsignedLong_Stype.LoadFromFile.
static bool SDC.unsignedLong_Stype.Deserialize(string input, out unsignedLong_Stype obj)
References SDC.unsignedLong_Stype.Deserialize, SDC.null.
static new unsignedLong_Stype SDC.unsignedLong_Stype.Deserialize(string input)
References SDC.null.
static unsignedLong_Stype SDC.unsignedLong_Stype.Deserialize(System.IO.Stream s)
References SDC.unsignedLong_Stype.Serializer.
static bool SDC.unsignedLong_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out unsignedLong_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an unsignedLong_Stype object
fileName string xml file to load and deserialize obj Output unsignedLong_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedLong_Stype.LoadFromFile.
static bool SDC.unsignedLong_Stype.LoadFromFile(string fileName, out unsignedLong_Stype obj, out System.Exception exception)
References SDC.unsignedLong_Stype.LoadFromFile.
static bool SDC.unsignedLong_Stype.LoadFromFile(string fileName, out unsignedLong_Stype obj)
References SDC.unsignedLong_Stype.LoadFromFile, SDC.null.
static unsignedLong_Stype SDC.unsignedLong_Stype.LoadFromFile(string fileName)
References SDC.unsignedLong_Stype.LoadFromFile.
static new unsignedLong_Stype SDC.unsignedLong_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.unsignedLong_Stype.Deserialize, SDC.null.
static bool SDC.unsignedLong_Stype.Deserialize(string input, out unsignedLong_Stype obj, out Exception exception)
Deserializes workflow markup into an unsignedLong_Stype object
input string workflow markup to deserialize obj Output unsignedLong_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedLong_Stype.Deserialize, SDC.null.
static bool SDC.unsignedLong_Stype.Deserialize(string input, out unsignedLong_Stype obj)
References SDC.unsignedLong_Stype.Deserialize, SDC.null.
static new unsignedLong_Stype SDC.unsignedLong_Stype.Deserialize(string input)
References SDC.null, SDC.unsignedLong_Stype.Serializer.
static unsignedLong_Stype SDC.unsignedLong_Stype.Deserialize(Stream s)
References SDC.unsignedLong_Stype.Serializer.
static bool SDC.unsignedLong_Stype.LoadFromFile(string fileName, out unsignedLong_Stype obj, out Exception exception)
Deserializes xml markup from file into an unsignedLong_Stype object
fileName string xml file to load and deserialize obj Output unsignedLong_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedLong_Stype.LoadFromFile, SDC.null.
static bool SDC.unsignedLong_Stype.LoadFromFile(string fileName, out unsignedLong_Stype obj)
References SDC.unsignedLong_Stype.LoadFromFile, SDC.null.
static new unsignedLong_Stype SDC.unsignedLong_Stype.LoadFromFile(string fileName)
References SDC.unsignedLong_Stype.Deserialize, SDC.null.