SDC::gMonth_Stype
string SDC.gMonth_Stype::_val
dtQuantEnum SDC.gMonth_Stype::_quantEnum
Referenced by SDC.gMonth_Stype.gMonth_Stype.
ObjectChangeTracker SDC.gMonth_Stype.changeTrackerField
static XmlSerializer SDC.gMonth_Stype::serializer
string SDC.gMonth_Stype::val
Referenced by SDC.gMonth_Stype.ShouldSerializeval.
dtQuantEnum SDC.gMonth_Stype::quantEnum
static XmlSerializer SDC.gMonth_Stype::Serializer
Referenced by SDC.gMonth_Stype.Deserialize.
ObjectChangeTracker SDC.gMonth_Stype.ChangeTracker
SDC.gMonth_Stype.gMonth_Stype()
SDC.gMonth_Stype.gMonth_Stype(BaseType parentNode)
virtual bool SDC.gMonth_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.gMonth_Stype.val.
virtual string SDC.gMonth_Stype.Serialize(System.Text.Encoding encoding)
Serializes current gMonth_Stype object into an XML string
string XML value
virtual string SDC.gMonth_Stype.Serialize()
Referenced by SDC.gMonth_Stype.SaveToFile.
virtual bool SDC.gMonth_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current gMonth_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.gMonth_Stype.SaveToFile.
virtual bool SDC.gMonth_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.gMonth_Stype.SaveToFile.
virtual void SDC.gMonth_Stype.SaveToFile(string fileName)
References SDC.gMonth_Stype.SaveToFile.
virtual void SDC.gMonth_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.gMonth_Stype.Serialize.
SDC.gMonth_Stype.gMonth_Stype()
gMonth_Stype class constructor
References SDC.gMonth_Stype._quantEnum.
virtual bool SDC.gMonth_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.gMonth_Stype.val.
virtual string SDC.gMonth_Stype.Serialize()
Serializes current gMonth_Stype object into an XML string
string XML value
virtual bool SDC.gMonth_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current gMonth_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.gMonth_Stype.SaveToFile.
virtual void SDC.gMonth_Stype.SaveToFile(string fileName)
References SDC.null, SDC.gMonth_Stype.Serialize.
virtual gMonth_Stype SDC.gMonth_Stype.Clone()
Create a clone of this gMonth_Stype object
static bool SDC.gMonth_Stype.Deserialize(string input, out gMonth_Stype obj, out System.Exception exception)
Deserializes workflow markup into an gMonth_Stype object
input string workflow markup to deserialize obj Output gMonth_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gMonth_Stype.Deserialize, SDC.gMonth_Stype.LoadFromFile.
static bool SDC.gMonth_Stype.Deserialize(string input, out gMonth_Stype obj)
References SDC.gMonth_Stype.Deserialize, SDC.null.
static new gMonth_Stype SDC.gMonth_Stype.Deserialize(string input)
References SDC.null.
static gMonth_Stype SDC.gMonth_Stype.Deserialize(System.IO.Stream s)
References SDC.gMonth_Stype.Serializer.
static bool SDC.gMonth_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out gMonth_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an gMonth_Stype object
fileName string xml file to load and deserialize obj Output gMonth_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gMonth_Stype.LoadFromFile.
static bool SDC.gMonth_Stype.LoadFromFile(string fileName, out gMonth_Stype obj, out System.Exception exception)
References SDC.gMonth_Stype.LoadFromFile.
static bool SDC.gMonth_Stype.LoadFromFile(string fileName, out gMonth_Stype obj)
References SDC.gMonth_Stype.LoadFromFile, SDC.null.
static gMonth_Stype SDC.gMonth_Stype.LoadFromFile(string fileName)
References SDC.gMonth_Stype.LoadFromFile.
static new gMonth_Stype SDC.gMonth_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.gMonth_Stype.Deserialize, SDC.null.
static bool SDC.gMonth_Stype.Deserialize(string input, out gMonth_Stype obj, out Exception exception)
Deserializes workflow markup into an gMonth_Stype object
input string workflow markup to deserialize obj Output gMonth_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gMonth_Stype.Deserialize, SDC.null.
static bool SDC.gMonth_Stype.Deserialize(string input, out gMonth_Stype obj)
References SDC.gMonth_Stype.Deserialize, SDC.null.
static new gMonth_Stype SDC.gMonth_Stype.Deserialize(string input)
References SDC.null, SDC.gMonth_Stype.Serializer.
static gMonth_Stype SDC.gMonth_Stype.Deserialize(Stream s)
References SDC.gMonth_Stype.Serializer.
static bool SDC.gMonth_Stype.LoadFromFile(string fileName, out gMonth_Stype obj, out Exception exception)
Deserializes xml markup from file into an gMonth_Stype object
fileName string xml file to load and deserialize obj Output gMonth_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gMonth_Stype.LoadFromFile, SDC.null.
static bool SDC.gMonth_Stype.LoadFromFile(string fileName, out gMonth_Stype obj)
References SDC.gMonth_Stype.LoadFromFile, SDC.null.
static new gMonth_Stype SDC.gMonth_Stype.LoadFromFile(string fileName)
References SDC.gMonth_Stype.Deserialize, SDC.null.