SDC::InputStr_ReturnDateTimeListType
bool SDC.InputStr_ReturnDateTimeListType._shouldSerializeuseDelimiter
Referenced by SDC.InputStr_ReturnDateTimeListType.ShouldSerializeuseDelimiter.
StringFunctionsStrType SDC.InputStr_ReturnDateTimeListType._inputStr
Referenced by SDC.InputStr_ReturnDateTimeListType.ShouldSerializeInputStr.
System.Nullable<bool> SDC.InputStr_ReturnDateTimeListType._useDelimiter
Referenced by SDC.InputStr_ReturnDateTimeListType.ShouldSerializeuseDelimiter.
InputStr_ReturnStrListTypeDelimiter SDC.InputStr_ReturnDateTimeListType._delimiter
XmlSerializer SDC.InputStr_ReturnDateTimeListType.serializer
virtual StringFunctionsStrType SDC.InputStr_ReturnDateTimeListType.InputStr
virtual bool SDC.InputStr_ReturnDateTimeListType.useDelimiter
If a delimiter is not used, then any white space will delimit the list items. The default delimiter is a space.
virtual bool SDC.InputStr_ReturnDateTimeListType.useDelimiterSpecified
virtual InputStr_ReturnStrListTypeDelimiter SDC.InputStr_ReturnDateTimeListType.delimiter
XmlSerializer SDC.InputStr_ReturnDateTimeListType.Serializer
Referenced by SDC.InputStr_ReturnDateTimeListType.Deserialize.
SDC.InputStr_ReturnDateTimeListType.InputStr_ReturnDateTimeListType()
InputStr_ReturnDateTimeListType class constructor
virtual bool SDC.InputStr_ReturnDateTimeListType.ShouldSerializeuseDelimiter()
Test whether useDelimiter should be serialized
References SDC.InputStr_ReturnDateTimeListType._shouldSerializeuseDelimiter, SDC.InputStr_ReturnDateTimeListType._useDelimiter.
virtual bool SDC.InputStr_ReturnDateTimeListType.ShouldSerializeInputStr()
Test whether InputStr should be serialized
References SDC.InputStr_ReturnDateTimeListType._inputStr, SDC.null.
virtual string SDC.InputStr_ReturnDateTimeListType.Serialize(System.Text.Encoding encoding)
Serializes current InputStr_ReturnDateTimeListType object into an XML string
string XML value
virtual string SDC.InputStr_ReturnDateTimeListType.Serialize()
Referenced by SDC.InputStr_ReturnDateTimeListType.SaveToFile.
virtual bool SDC.InputStr_ReturnDateTimeListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InputStr_ReturnDateTimeListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InputStr_ReturnDateTimeListType.SaveToFile.
virtual bool SDC.InputStr_ReturnDateTimeListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.InputStr_ReturnDateTimeListType.SaveToFile.
virtual void SDC.InputStr_ReturnDateTimeListType.SaveToFile(string fileName)
References SDC.InputStr_ReturnDateTimeListType.SaveToFile.
virtual void SDC.InputStr_ReturnDateTimeListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InputStr_ReturnDateTimeListType.Serialize.
static bool SDC.InputStr_ReturnDateTimeListType.Deserialize(string input, out InputStr_ReturnDateTimeListType obj, out System.Exception exception)
Deserializes workflow markup into an InputStr_ReturnDateTimeListType object
input string workflow markup to deserialize obj Output InputStr_ReturnDateTimeListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnDateTimeListType.Deserialize, SDC.InputStr_ReturnDateTimeListType.LoadFromFile.
static bool SDC.InputStr_ReturnDateTimeListType.Deserialize(string input, out InputStr_ReturnDateTimeListType obj)
References SDC.InputStr_ReturnDateTimeListType.Deserialize, SDC.null.
static new InputStr_ReturnDateTimeListType SDC.InputStr_ReturnDateTimeListType.Deserialize(string input)
References SDC.null.
static InputStr_ReturnDateTimeListType SDC.InputStr_ReturnDateTimeListType.Deserialize(System.IO.Stream s)
References SDC.InputStr_ReturnDateTimeListType.Serializer.
static bool SDC.InputStr_ReturnDateTimeListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out InputStr_ReturnDateTimeListType obj, out System.Exception exception)
Deserializes xml markup from file into an InputStr_ReturnDateTimeListType object
fileName string xml file to load and deserialize obj Output InputStr_ReturnDateTimeListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnDateTimeListType.LoadFromFile.
static bool SDC.InputStr_ReturnDateTimeListType.LoadFromFile(string fileName, out InputStr_ReturnDateTimeListType obj, out System.Exception exception)
References SDC.InputStr_ReturnDateTimeListType.LoadFromFile.
static bool SDC.InputStr_ReturnDateTimeListType.LoadFromFile(string fileName, out InputStr_ReturnDateTimeListType obj)
References SDC.InputStr_ReturnDateTimeListType.LoadFromFile, SDC.null.
static InputStr_ReturnDateTimeListType SDC.InputStr_ReturnDateTimeListType.LoadFromFile(string fileName)
References SDC.InputStr_ReturnDateTimeListType.LoadFromFile.
static new InputStr_ReturnDateTimeListType SDC.InputStr_ReturnDateTimeListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InputStr_ReturnDateTimeListType.Deserialize, SDC.null.