SDC::unsignedShort_DEtype
bool SDC.unsignedShort_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.unsignedShort_DEtype.ShouldSerializemaxExclusive.
bool SDC.unsignedShort_DEtype::_shouldSerializeminExclusive
Referenced by SDC.unsignedShort_DEtype.ShouldSerializeminExclusive.
bool SDC.unsignedShort_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.unsignedShort_DEtype.ShouldSerializemaxInclusive.
bool SDC.unsignedShort_DEtype::_shouldSerializeminInclusive
Referenced by SDC.unsignedShort_DEtype.ShouldSerializeminInclusive.
System Nullable< ushort > SDC.unsignedShort_DEtype::_minInclusive
Referenced by SDC.unsignedShort_DEtype.ShouldSerializeminInclusive.
System Nullable< ushort > SDC.unsignedShort_DEtype::_maxInclusive
Referenced by SDC.unsignedShort_DEtype.ShouldSerializemaxInclusive.
System Nullable< ushort > SDC.unsignedShort_DEtype::_minExclusive
Referenced by SDC.unsignedShort_DEtype.ShouldSerializeminExclusive.
System Nullable< ushort > SDC.unsignedShort_DEtype::_maxExclusive
Referenced by SDC.unsignedShort_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.unsignedShort_DEtype::_totalDigits
string SDC.unsignedShort_DEtype::_mask
ObjectChangeTracker SDC.unsignedShort_DEtype.changeTrackerField
static XmlSerializer SDC.unsignedShort_DEtype::serializer
ushort SDC.unsignedShort_DEtype::minInclusive
bool SDC.unsignedShort_DEtype::minInclusiveSpecified
ushort SDC.unsignedShort_DEtype::maxInclusive
bool SDC.unsignedShort_DEtype::maxInclusiveSpecified
ushort SDC.unsignedShort_DEtype::minExclusive
bool SDC.unsignedShort_DEtype::minExclusiveSpecified
ushort SDC.unsignedShort_DEtype::maxExclusive
bool SDC.unsignedShort_DEtype::maxExclusiveSpecified
byte SDC.unsignedShort_DEtype::totalDigits
bool SDC.unsignedShort_DEtype::totalDigitsSpecified
string SDC.unsignedShort_DEtype::mask
Referenced by SDC.unsignedShort_DEtype.ShouldSerializemask.
static XmlSerializer SDC.unsignedShort_DEtype::Serializer
Referenced by SDC.unsignedShort_DEtype.Deserialize.
ObjectChangeTracker SDC.unsignedShort_DEtype.ChangeTracker
SDC.unsignedShort_DEtype.unsignedShort_DEtype()
SDC.unsignedShort_DEtype.unsignedShort_DEtype(BaseType parentNode)
virtual bool SDC.unsignedShort_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.unsignedShort_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.unsignedShort_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.unsignedShort_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.unsignedShort_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.unsignedShort_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current unsignedShort_DEtype object into an XML string
string XML value
virtual string SDC.unsignedShort_DEtype.Serialize()
Referenced by SDC.unsignedShort_DEtype.SaveToFile.
virtual bool SDC.unsignedShort_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current unsignedShort_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.unsignedShort_DEtype.SaveToFile.
virtual bool SDC.unsignedShort_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.unsignedShort_DEtype.SaveToFile(string fileName)
virtual void SDC.unsignedShort_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.unsignedShort_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.unsignedShort_DEtype._minInclusive, SDC.unsignedShort_DEtype._shouldSerializeminInclusive.
virtual bool SDC.unsignedShort_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.unsignedShort_DEtype._maxInclusive, SDC.unsignedShort_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.unsignedShort_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.unsignedShort_DEtype._minExclusive, SDC.unsignedShort_DEtype._shouldSerializeminExclusive.
virtual bool SDC.unsignedShort_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.unsignedShort_DEtype._maxExclusive, SDC.unsignedShort_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.unsignedShort_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.unsignedShort_DEtype.mask.
virtual string SDC.unsignedShort_DEtype.Serialize()
Serializes current unsignedShort_DEtype object into an XML string
string XML value
virtual bool SDC.unsignedShort_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current unsignedShort_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.unsignedShort_DEtype.SaveToFile.
virtual void SDC.unsignedShort_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.unsignedShort_DEtype.Serialize.
virtual unsignedShort_DEtype SDC.unsignedShort_DEtype.Clone()
Create a clone of this unsignedShort_DEtype object
static bool SDC.unsignedShort_DEtype.Deserialize(string input, out unsignedShort_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an unsignedShort_DEtype object
input string workflow markup to deserialize obj Output unsignedShort_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedShort_DEtype.Deserialize, SDC.unsignedShort_DEtype.LoadFromFile.
static bool SDC.unsignedShort_DEtype.Deserialize(string input, out unsignedShort_DEtype obj)
References SDC.null.
static new unsignedShort_DEtype SDC.unsignedShort_DEtype.Deserialize(string input)
References SDC.null.
static unsignedShort_DEtype SDC.unsignedShort_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.unsignedShort_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out unsignedShort_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an unsignedShort_DEtype object
fileName string xml file to load and deserialize obj Output unsignedShort_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedShort_DEtype.LoadFromFile.
static bool SDC.unsignedShort_DEtype.LoadFromFile(string fileName, out unsignedShort_DEtype obj, out System.Exception exception)
static bool SDC.unsignedShort_DEtype.LoadFromFile(string fileName, out unsignedShort_DEtype obj)
References SDC.null.
static unsignedShort_DEtype SDC.unsignedShort_DEtype.LoadFromFile(string fileName)
static new unsignedShort_DEtype SDC.unsignedShort_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.unsignedShort_DEtype.Deserialize(string input, out unsignedShort_DEtype obj, out Exception exception)
Deserializes workflow markup into an unsignedShort_DEtype object
input string workflow markup to deserialize obj Output unsignedShort_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedShort_DEtype.Deserialize, SDC.null.
static bool SDC.unsignedShort_DEtype.Deserialize(string input, out unsignedShort_DEtype obj)
References SDC.unsignedShort_DEtype.Deserialize, SDC.null.
static new unsignedShort_DEtype SDC.unsignedShort_DEtype.Deserialize(string input)
References SDC.null, SDC.unsignedShort_DEtype.Serializer.
static unsignedShort_DEtype SDC.unsignedShort_DEtype.Deserialize(Stream s)
References SDC.unsignedShort_DEtype.Serializer.
static bool SDC.unsignedShort_DEtype.LoadFromFile(string fileName, out unsignedShort_DEtype obj, out Exception exception)
Deserializes xml markup from file into an unsignedShort_DEtype object
fileName string xml file to load and deserialize obj Output unsignedShort_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedShort_DEtype.LoadFromFile, SDC.null.
static bool SDC.unsignedShort_DEtype.LoadFromFile(string fileName, out unsignedShort_DEtype obj)
References SDC.unsignedShort_DEtype.LoadFromFile, SDC.null.
static new unsignedShort_DEtype SDC.unsignedShort_DEtype.LoadFromFile(string fileName)
References SDC.unsignedShort_DEtype.Deserialize, SDC.null.