SDC::byte_Stype
bool SDC.byte_Stype::_shouldSerializeval
Referenced by SDC.byte_Stype.ShouldSerializeval.
System Nullable< sbyte > SDC.byte_Stype::_val
Referenced by SDC.byte_Stype.ShouldSerializeval.
ObjectChangeTracker SDC.byte_Stype.changeTrackerField
static XmlSerializer SDC.byte_Stype::serializer
sbyte SDC.byte_Stype::val
bool SDC.byte_Stype::valSpecified
static XmlSerializer SDC.byte_Stype::Serializer
Referenced by SDC.byte_Stype.Deserialize.
ObjectChangeTracker SDC.byte_Stype.ChangeTracker
SDC.byte_Stype.byte_Stype()
SDC.byte_Stype.byte_Stype(BaseType parentNode)
virtual bool SDC.byte_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.byte_Stype._shouldSerializeval, SDC.byte_Stype._val.
virtual string SDC.byte_Stype.Serialize(System.Text.Encoding encoding)
Serializes current byte_Stype object into an XML string
string XML value
virtual string SDC.byte_Stype.Serialize()
Referenced by SDC.byte_Stype.SaveToFile.
virtual bool SDC.byte_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current byte_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.byte_Stype.SaveToFile.
virtual bool SDC.byte_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.byte_Stype.SaveToFile.
virtual void SDC.byte_Stype.SaveToFile(string fileName)
References SDC.byte_Stype.SaveToFile.
virtual void SDC.byte_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.byte_Stype.Serialize.
virtual bool SDC.byte_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.byte_Stype._shouldSerializeval, SDC.byte_Stype._val.
virtual string SDC.byte_Stype.Serialize()
Serializes current byte_Stype object into an XML string
string XML value
virtual bool SDC.byte_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current byte_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.byte_Stype.SaveToFile.
virtual void SDC.byte_Stype.SaveToFile(string fileName)
References SDC.null, SDC.byte_Stype.Serialize.
virtual byte_Stype SDC.byte_Stype.Clone()
Create a clone of this byte_Stype object
static bool SDC.byte_Stype.Deserialize(string input, out byte_Stype obj, out System.Exception exception)
Deserializes workflow markup into an byte_Stype object
input string workflow markup to deserialize obj Output byte_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.byte_Stype.Deserialize, SDC.byte_Stype.LoadFromFile.
static bool SDC.byte_Stype.Deserialize(string input, out byte_Stype obj)
References SDC.byte_Stype.Deserialize, SDC.null.
static new byte_Stype SDC.byte_Stype.Deserialize(string input)
References SDC.null.
static byte_Stype SDC.byte_Stype.Deserialize(System.IO.Stream s)
References SDC.byte_Stype.Serializer.
static bool SDC.byte_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out byte_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an byte_Stype object
fileName string xml file to load and deserialize obj Output byte_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.byte_Stype.LoadFromFile.
static bool SDC.byte_Stype.LoadFromFile(string fileName, out byte_Stype obj, out System.Exception exception)
References SDC.byte_Stype.LoadFromFile.
static bool SDC.byte_Stype.LoadFromFile(string fileName, out byte_Stype obj)
References SDC.byte_Stype.LoadFromFile, SDC.null.
static byte_Stype SDC.byte_Stype.LoadFromFile(string fileName)
References SDC.byte_Stype.LoadFromFile.
static new byte_Stype SDC.byte_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.byte_Stype.Deserialize, SDC.null.
static bool SDC.byte_Stype.Deserialize(string input, out byte_Stype obj, out Exception exception)
Deserializes workflow markup into an byte_Stype object
input string workflow markup to deserialize obj Output byte_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.byte_Stype.Deserialize, SDC.null.
static bool SDC.byte_Stype.Deserialize(string input, out byte_Stype obj)
References SDC.byte_Stype.Deserialize, SDC.null.
static new byte_Stype SDC.byte_Stype.Deserialize(string input)
References SDC.null, SDC.byte_Stype.Serializer.
static byte_Stype SDC.byte_Stype.Deserialize(Stream s)
References SDC.byte_Stype.Serializer.
static bool SDC.byte_Stype.LoadFromFile(string fileName, out byte_Stype obj, out Exception exception)
Deserializes xml markup from file into an byte_Stype object
fileName string xml file to load and deserialize obj Output byte_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.byte_Stype.LoadFromFile, SDC.null.
static bool SDC.byte_Stype.LoadFromFile(string fileName, out byte_Stype obj)
References SDC.byte_Stype.LoadFromFile, SDC.null.
static new byte_Stype SDC.byte_Stype.LoadFromFile(string fileName)
References SDC.byte_Stype.Deserialize, SDC.null.