SDC::gYear_DEtype
string SDC.gYear_DEtype::_minInclusive
string SDC.gYear_DEtype::_maxInclusive
string SDC.gYear_DEtype::_minExclusive
string SDC.gYear_DEtype::_maxExclusive
string SDC.gYear_DEtype::_mask
ObjectChangeTracker SDC.gYear_DEtype.changeTrackerField
static XmlSerializer SDC.gYear_DEtype::serializer
string SDC.gYear_DEtype::minInclusive
Referenced by SDC.gYear_DEtype.ShouldSerializeminInclusive.
string SDC.gYear_DEtype::maxInclusive
Referenced by SDC.gYear_DEtype.ShouldSerializemaxInclusive.
string SDC.gYear_DEtype::minExclusive
Referenced by SDC.gYear_DEtype.ShouldSerializeminExclusive.
string SDC.gYear_DEtype::maxExclusive
Referenced by SDC.gYear_DEtype.ShouldSerializemaxExclusive.
string SDC.gYear_DEtype::mask
Referenced by SDC.gYear_DEtype.ShouldSerializemask.
static XmlSerializer SDC.gYear_DEtype::Serializer
Referenced by SDC.gYear_DEtype.Deserialize.
ObjectChangeTracker SDC.gYear_DEtype.ChangeTracker
SDC.gYear_DEtype.gYear_DEtype()
SDC.gYear_DEtype.gYear_DEtype(BaseType parentNode)
virtual bool SDC.gYear_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.gYear_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.gYear_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.gYear_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.gYear_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.gYear_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current gYear_DEtype object into an XML string
string XML value
virtual string SDC.gYear_DEtype.Serialize()
Referenced by SDC.gYear_DEtype.SaveToFile.
virtual bool SDC.gYear_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current gYear_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.gYear_DEtype.SaveToFile.
virtual bool SDC.gYear_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.gYear_DEtype.SaveToFile(string fileName)
virtual void SDC.gYear_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.gYear_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.gYear_DEtype.minInclusive.
virtual bool SDC.gYear_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.gYear_DEtype.maxInclusive.
virtual bool SDC.gYear_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.gYear_DEtype.minExclusive.
virtual bool SDC.gYear_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.gYear_DEtype.maxExclusive.
virtual bool SDC.gYear_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.gYear_DEtype.mask.
virtual string SDC.gYear_DEtype.Serialize()
Serializes current gYear_DEtype object into an XML string
string XML value
virtual bool SDC.gYear_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current gYear_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.gYear_DEtype.SaveToFile.
virtual void SDC.gYear_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.gYear_DEtype.Serialize.
virtual gYear_DEtype SDC.gYear_DEtype.Clone()
Create a clone of this gYear_DEtype object
static bool SDC.gYear_DEtype.Deserialize(string input, out gYear_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an gYear_DEtype object
input string workflow markup to deserialize obj Output gYear_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gYear_DEtype.Deserialize, SDC.gYear_DEtype.LoadFromFile.
static bool SDC.gYear_DEtype.Deserialize(string input, out gYear_DEtype obj)
References SDC.null.
static new gYear_DEtype SDC.gYear_DEtype.Deserialize(string input)
References SDC.null.
static gYear_DEtype SDC.gYear_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.gYear_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out gYear_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an gYear_DEtype object
fileName string xml file to load and deserialize obj Output gYear_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gYear_DEtype.LoadFromFile.
static bool SDC.gYear_DEtype.LoadFromFile(string fileName, out gYear_DEtype obj, out System.Exception exception)
static bool SDC.gYear_DEtype.LoadFromFile(string fileName, out gYear_DEtype obj)
References SDC.null.
static gYear_DEtype SDC.gYear_DEtype.LoadFromFile(string fileName)
static new gYear_DEtype SDC.gYear_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.gYear_DEtype.Deserialize(string input, out gYear_DEtype obj, out Exception exception)
Deserializes workflow markup into an gYear_DEtype object
input string workflow markup to deserialize obj Output gYear_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gYear_DEtype.Deserialize, SDC.null.
static bool SDC.gYear_DEtype.Deserialize(string input, out gYear_DEtype obj)
References SDC.gYear_DEtype.Deserialize, SDC.null.
static new gYear_DEtype SDC.gYear_DEtype.Deserialize(string input)
References SDC.null, SDC.gYear_DEtype.Serializer.
static gYear_DEtype SDC.gYear_DEtype.Deserialize(Stream s)
References SDC.gYear_DEtype.Serializer.
static bool SDC.gYear_DEtype.LoadFromFile(string fileName, out gYear_DEtype obj, out Exception exception)
Deserializes xml markup from file into an gYear_DEtype object
fileName string xml file to load and deserialize obj Output gYear_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gYear_DEtype.LoadFromFile, SDC.null.
static bool SDC.gYear_DEtype.LoadFromFile(string fileName, out gYear_DEtype obj)
References SDC.gYear_DEtype.LoadFromFile, SDC.null.
static new gYear_DEtype SDC.gYear_DEtype.LoadFromFile(string fileName)
References SDC.gYear_DEtype.Deserialize, SDC.null.