SDC::ObjectChangeTracker
bool SDC.ObjectChangeTracker.isDeserializingField
Referenced by SDC.ObjectChangeTracker.OnDeserializedMethod, SDC.ObjectChangeTracker.OnDeserializingMethod.
ObjectState SDC.ObjectChangeTracker.originalobjectStateField
Referenced by SDC.ObjectChangeTracker.ResetTracking, SDC.ObjectChangeTracker.UpdateChangeState.
bool SDC.ObjectChangeTracker.isInitilizedField
Referenced by SDC.ObjectChangeTracker.InitOriginalValue, SDC.ObjectChangeTracker.ResetOriginalValue.
readonly ObservableCollection<PropertyValueState> SDC.ObjectChangeTracker.changeSetsField
Delegate SDC.ObjectChangeTracker.collectionChangedDelegateField
Referenced by SDC.ObjectChangeTracker.InitOriginalValue, SDC.ObjectChangeTracker.ResetOriginalValue.
bool SDC.ObjectChangeTracker.objectTrackingEnabledField
Referenced by SDC.ObjectChangeTracker.RecordAdditionToCollectionProperties, SDC.ObjectChangeTracker.RecordCurrentValue, SDC.ObjectChangeTracker.RecordOriginalToCollectionProperties, SDC.ObjectChangeTracker.RecordRemovalFromCollectionProperties, SDC.ObjectChangeTracker.ResetTracking, SDC.ObjectChangeTracker.StartTracking, SDC.ObjectChangeTracker.StopTracking.
readonly object SDC.ObjectChangeTracker.trackedObjectField
Referenced by SDC.ObjectChangeTracker.InitOriginalValue, SDC.ObjectChangeTracker.ObjectChangeTracker, SDC.ObjectChangeTracker.ResetOriginalValue.
PropertyValueStatesDictionary SDC.ObjectChangeTracker.propertyValueStatesFields
ObjectsAddedToCollectionProperties SDC.ObjectChangeTracker.objectsAddedToCollectionsField
ObjectsRemovedFromCollectionProperties SDC.ObjectChangeTracker.objectsRemovedFromCollectionsField
ObjectsOriginalFromCollectionProperties SDC.ObjectChangeTracker.objectsOriginalFromCollectionsField
ObjectState SDC.ObjectChangeTracker.stateField
indicate current state
Referenced by SDC.ObjectChangeTracker.UpdateChangeState.
EventHandler<ObjectStateChangingEventArgs> SDC.ObjectChangeTracker.ObjectStateChanging
Referenced by SDC.ObjectChangeTracker.OnObjectStateChanging.
PropertyChangedEventHandler SDC.ObjectChangeTracker.PropertyChanged
Referenced by SDC.ObjectChangeTracker.OnPropertyChanged.
ObjectState SDC.ObjectChangeTracker.State
Gets the state.
The state.
Referenced by SDC.ObjectChangeTracker.RecordCurrentValue, SDC.ObjectChangeTracker.UpdateChangeState.
ObservableCollection<PropertyValueState> SDC.ObjectChangeTracker.ChangeSets
Referenced by SDC.ObjectChangeTracker.UpdateChangeState.
bool SDC.ObjectChangeTracker.ObjectTrackingEnabled
Gets or sets a value indicating whether [change tracking enabled].
true if [change tracking enabled]; otherwise, false.
ObjectsRemovedFromCollectionProperties SDC.ObjectChangeTracker.ObjectsRemovedFromCollectionProperties
PropertyValueStatesDictionary SDC.ObjectChangeTracker.PropertyValueStates
Referenced by SDC.ObjectChangeTracker.UpdateChangeState.
ObjectsAddedToCollectionProperties SDC.ObjectChangeTracker.ObjectsAddedToCollectionProperties
ObjectsOriginalFromCollectionProperties SDC.ObjectChangeTracker.ObjectsOriginalFromCollectionProperties
SDC.ObjectChangeTracker.ObjectChangeTracker(object trackedObject)
References SDC.ObjectChangeTracker.trackedObjectField.
void SDC.ObjectChangeTracker.StartTracking()
Starts record changes.
References SDC.ObjectChangeTracker.objectTrackingEnabledField, SDC.ObjectChangeTracker.ResetTracking.
Referenced by SDC.ObjectChangeTracker.StartTracking.
void SDC.ObjectChangeTracker.StartTracking(bool keepLastRecords)
Starts record changes.
References SDC.ObjectChangeTracker.objectTrackingEnabledField, SDC.ObjectChangeTracker.StartTracking.
void SDC.ObjectChangeTracker.StopTracking()
Starts record changes.
References SDC.ObjectChangeTracker.objectTrackingEnabledField.
void SDC.ObjectChangeTracker.ResetTracking()
References SDC.ObjectChangeTracker.InitOriginalValue, SDC.ObjectChangeTracker.objectTrackingEnabledField, SDC.ObjectChangeTracker.originalobjectStateField, SDC.ObjectChangeTracker.ResetOriginalValue, SDC.ObjectChangeTracker.UpdateChangeState.
Referenced by SDC.ObjectChangeTracker.StartTracking.
void SDC.ObjectChangeTracker.OnDeserializingMethod(StreamingContext context)
References SDC.ObjectChangeTracker.isDeserializingField.
void SDC.ObjectChangeTracker.OnDeserializedMethod(StreamingContext context)
References SDC.ObjectChangeTracker.isDeserializingField.
void SDC.ObjectChangeTracker.RecordCurrentValue(string propertyName, object value)
Captures the original value for a property that is changing.
propertyName Name of the property. value The value.
References SDC.null, SDC.ObjectChangeTracker.objectTrackingEnabledField, SDC.ObjectChangeTracker.State, SDC.ObjectChangeTracker.UpdateChangeState, SDC.var.
Referenced by SDC.ObjectChangeTracker.InitOriginalValue.
virtual void SDC.ObjectChangeTracker.OnPropertyChanged(string info)
Called when [property changed].
info The info.
References SDC.null, SDC.ObjectChangeTracker.PropertyChanged.
Referenced by SDC.ObjectChangeTracker.UpdateChangeState.
virtual void SDC.ObjectChangeTracker.OnObjectStateChanging(ObjectState newState)
References SDC.null, SDC.ObjectChangeTracker.ObjectStateChanging.
Referenced by SDC.ObjectChangeTracker.UpdateChangeState.
void SDC.ObjectChangeTracker.UpdateChangeState()
Updates the state of the change.
References SDC.ObjectChangeTracker.ChangeSets, SDC.ObjectChangeTracker.OnObjectStateChanging, SDC.ObjectChangeTracker.OnPropertyChanged, SDC.ObjectChangeTracker.originalobjectStateField, SDC.ObjectChangeTracker.PropertyValueStates, SDC.ObjectChangeTracker.State, SDC.ObjectChangeTracker.stateField, SDC.var.
Referenced by SDC.ObjectChangeTracker.RecordCurrentValue, SDC.ObjectChangeTracker.ResetTracking, SDC.ObjectChangeTracker.TrackableCollectionChanged.
void SDC.ObjectChangeTracker.InitOriginalValue()
Inits the original value.
References SDC.ObjectChangeTracker.collectionChangedDelegateField, SDC.ObjectChangeTracker.isInitilizedField, SDC.null, SDC.ObjectChangeTracker.RecordCurrentValue, SDC.ObjectChangeTracker.RecordOriginalToCollectionProperties, SDC.ObjectChangeTracker.trackedObjectField, SDC.var.
Referenced by SDC.ObjectChangeTracker.ResetTracking.
void SDC.ObjectChangeTracker.ResetOriginalValue()
Resets the original value.
References SDC.ObjectChangeTracker.collectionChangedDelegateField, SDC.ObjectChangeTracker.isInitilizedField, SDC.null, SDC.ObjectChangeTracker.trackedObjectField, SDC.var.
Referenced by SDC.ObjectChangeTracker.ResetTracking.
void SDC.ObjectChangeTracker.TrackableCollectionChanged(object sender, NotifyCollectionChangedEventArgs e, string propertyName)
Trackables the collection changed.
sender The sender. e The NotifyTrackableCollectionChangedEventArgs instance containing the event data. propertyName Name of the property.
References SDC.ObjectChangeTracker.RecordAdditionToCollectionProperties, SDC.ObjectChangeTracker.RecordRemovalFromCollectionProperties, SDC.ObjectChangeTracker.UpdateChangeState, SDC.var.
void SDC.ObjectChangeTracker.RecordOriginalToCollectionProperties(string propertyName, object value)
Records original items value of collection to collection valued properties on SelfTracking Entities.
propertyName Name of the property. value The value.
References SDC.ObjectChangeTracker.objectTrackingEnabledField.
Referenced by SDC.ObjectChangeTracker.InitOriginalValue.
void SDC.ObjectChangeTracker.RecordAdditionToCollectionProperties(string propertyName, object value)
Records an addition to collection valued properties on SelfTracking Entities.
propertyName Name of the property. value The value.
References SDC.Count, SDC.ObjectChangeTracker.objectTrackingEnabledField.
Referenced by SDC.ObjectChangeTracker.TrackableCollectionChanged.
void SDC.ObjectChangeTracker.RecordRemovalFromCollectionProperties(string propertyName, object value)
Records a removal to collection valued properties on SelfTracking Entities.
propertyName Name of the property. value The object value.
References SDC.Count, SDC.ObjectChangeTracker.objectTrackingEnabledField.
Referenced by SDC.ObjectChangeTracker.TrackableCollectionChanged.