SDC::ActSendMessageType
List<SDC.ExtensionBaseType> SDC.ActSendMessageType.Email_Phone_WebSvc_List
List<BaseType> accepts: EmailAddressType, PhoneNumberType, WebServiceType
List<SDC.BaseType> SDC.ActSendMessageType.Email_Phone_WebSvc_List
List<BaseType> accepts: EmailAddressType, PhoneNumberType, WebServiceType
virtual List<ExtensionBaseType> SDC.ActSendMessageType.Items
string SDC.ActSendMessageType::messageType
Referenced by SDC.ActSendMessageType.ShouldSerializemessageType.
static XmlSerializer SDC.ActSendMessageType::Serializer
Referenced by SDC.ActSendMessageType.Deserialize.
virtual RichTextType SDC.ActSendMessageType.MessageText
virtual BindingList<BaseType> SDC.ActSendMessageType.Items
ObjectChangeTracker SDC.ActSendMessageType.ChangeTracker
List<ExtensionBaseType> SDC.ActSendMessageType._items
string SDC.ActSendMessageType::_messageType
RichTextType SDC.ActSendMessageType._messageText
Referenced by SDC.ActSendMessageType.ShouldSerializeMessageText.
BindingList<BaseType> SDC.ActSendMessageType._items
ObjectChangeTracker SDC.ActSendMessageType.changeTrackerField
static XmlSerializer SDC.ActSendMessageType::serializer
SDC.ActSendMessageType.ActSendMessageType(ThenType parentNode)
virtual bool SDC.ActSendMessageType.ShouldSerializeItems()
Test whether Items should be serialized
References SDC.null.
virtual bool SDC.ActSendMessageType.ShouldSerializemessageType()
Test whether messageType should be serialized
virtual string SDC.ActSendMessageType.Serialize(System.Text.Encoding encoding)
Serializes current ActSendMessageType object into an XML string
string XML value
virtual string SDC.ActSendMessageType.Serialize()
Referenced by SDC.ActSendMessageType.SaveToFile.
virtual bool SDC.ActSendMessageType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ActSendMessageType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ActSendMessageType.SaveToFile.
virtual bool SDC.ActSendMessageType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ActSendMessageType.SaveToFile(string fileName)
virtual void SDC.ActSendMessageType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ActSendMessageType.ShouldSerializeMessageText()
Test whether MessageText should be serialized
References SDC.ActSendMessageType._messageText, SDC.null.
virtual bool SDC.ActSendMessageType.ShouldSerializemessageType()
Test whether messageType should be serialized
References SDC.ActSendMessageType.messageType.
virtual string SDC.ActSendMessageType.Serialize()
Serializes current ActSendMessageType object into an XML string
string XML value
virtual bool SDC.ActSendMessageType.SaveToFile(string fileName, out Exception exception)
Serializes current ActSendMessageType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ActSendMessageType.SaveToFile.
virtual void SDC.ActSendMessageType.SaveToFile(string fileName)
References SDC.null, SDC.ActSendMessageType.Serialize.
virtual ActSendMessageType SDC.ActSendMessageType.Clone()
Create a clone of this ActSendMessageType object
SDC.ActSendMessageType.ActSendMessageType()
static bool SDC.ActSendMessageType.Deserialize(string input, out ActSendMessageType obj, out System.Exception exception)
Deserializes workflow markup into an ActSendMessageType object
input string workflow markup to deserialize obj Output ActSendMessageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActSendMessageType.Deserialize, SDC.ActSendMessageType.LoadFromFile.
static bool SDC.ActSendMessageType.Deserialize(string input, out ActSendMessageType obj)
References SDC.null.
static new ActSendMessageType SDC.ActSendMessageType.Deserialize(string input)
References SDC.null.
static ActSendMessageType SDC.ActSendMessageType.Deserialize(System.IO.Stream s)
static bool SDC.ActSendMessageType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ActSendMessageType obj, out System.Exception exception)
Deserializes xml markup from file into an ActSendMessageType object
fileName string xml file to load and deserialize obj Output ActSendMessageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActSendMessageType.LoadFromFile.
static bool SDC.ActSendMessageType.LoadFromFile(string fileName, out ActSendMessageType obj, out System.Exception exception)
static bool SDC.ActSendMessageType.LoadFromFile(string fileName, out ActSendMessageType obj)
References SDC.null.
static ActSendMessageType SDC.ActSendMessageType.LoadFromFile(string fileName)
static new ActSendMessageType SDC.ActSendMessageType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ActSendMessageType.Deserialize(string input, out ActSendMessageType obj, out Exception exception)
Deserializes workflow markup into an ActSendMessageType object
input string workflow markup to deserialize obj Output ActSendMessageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActSendMessageType.Deserialize, SDC.null.
static bool SDC.ActSendMessageType.Deserialize(string input, out ActSendMessageType obj)
References SDC.ActSendMessageType.Deserialize, SDC.null.
static new ActSendMessageType SDC.ActSendMessageType.Deserialize(string input)
References SDC.null, SDC.ActSendMessageType.Serializer.
static ActSendMessageType SDC.ActSendMessageType.Deserialize(Stream s)
References SDC.ActSendMessageType.Serializer.
static bool SDC.ActSendMessageType.LoadFromFile(string fileName, out ActSendMessageType obj, out Exception exception)
Deserializes xml markup from file into an ActSendMessageType object
fileName string xml file to load and deserialize obj Output ActSendMessageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActSendMessageType.LoadFromFile, SDC.null.
static bool SDC.ActSendMessageType.LoadFromFile(string fileName, out ActSendMessageType obj)
References SDC.ActSendMessageType.LoadFromFile, SDC.null.
static new ActSendMessageType SDC.ActSendMessageType.LoadFromFile(string fileName)
References SDC.ActSendMessageType.Deserialize, SDC.null.