SDC::ExtensionType
List<System.Xml.XmlElement> SDC.ExtensionType._any
List<System.Xml.XmlAttribute> SDC.ExtensionType._anyAttr
BindingList<System.Xml.XmlElement> SDC.ExtensionType._any
BindingList<System.Xml.XmlAttribute> SDC.ExtensionType._anyAttr
ObjectChangeTracker SDC.ExtensionType.changeTrackerField
static XmlSerializer SDC.ExtensionType::serializer
virtual List<System.Xml.XmlElement> SDC.ExtensionType.Any
virtual List<System.Xml.XmlAttribute> SDC.ExtensionType.AnyAttr
static XmlSerializer SDC.ExtensionType::Serializer
Referenced by SDC.ExtensionType.Deserialize.
virtual BindingList<System.Xml.XmlElement> SDC.ExtensionType.Any
virtual BindingList<System.Xml.XmlAttribute> SDC.ExtensionType.AnyAttr
ObjectChangeTracker SDC.ExtensionType.ChangeTracker
SDC.ExtensionType.ExtensionType()
SDC.ExtensionType.ExtensionType(BaseType parentNode, bool fillData=true)
SDC.ExtensionType.ExtensionType()
virtual bool SDC.ExtensionType.ShouldSerializeAny()
Test whether Any should be serialized
References SDC.null.
virtual bool SDC.ExtensionType.ShouldSerializeAnyAttr()
Test whether AnyAttr should be serialized
References SDC.null.
virtual string SDC.ExtensionType.Serialize(System.Text.Encoding encoding)
Serializes current ExtensionType object into an XML string
string XML value
virtual string SDC.ExtensionType.Serialize()
Referenced by SDC.ExtensionType.SaveToFile.
virtual bool SDC.ExtensionType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ExtensionType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ExtensionType.SaveToFile.
virtual bool SDC.ExtensionType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ExtensionType.SaveToFile(string fileName)
virtual void SDC.ExtensionType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ExtensionType.Serialize()
Serializes current ExtensionType object into an XML string
string XML value
virtual bool SDC.ExtensionType.SaveToFile(string fileName, out Exception exception)
Serializes current ExtensionType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ExtensionType.SaveToFile.
virtual void SDC.ExtensionType.SaveToFile(string fileName)
References SDC.null, SDC.ExtensionType.Serialize.
virtual ExtensionType SDC.ExtensionType.Clone()
Create a clone of this ExtensionType object
static bool SDC.ExtensionType.Deserialize(string input, out ExtensionType obj, out System.Exception exception)
Deserializes workflow markup into an ExtensionType object
input string workflow markup to deserialize obj Output ExtensionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ExtensionType.Deserialize, SDC.ExtensionType.LoadFromFile.
static bool SDC.ExtensionType.Deserialize(string input, out ExtensionType obj)
References SDC.null.
static new ExtensionType SDC.ExtensionType.Deserialize(string input)
References SDC.null.
static ExtensionType SDC.ExtensionType.Deserialize(System.IO.Stream s)
static bool SDC.ExtensionType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ExtensionType obj, out System.Exception exception)
Deserializes xml markup from file into an ExtensionType object
fileName string xml file to load and deserialize obj Output ExtensionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ExtensionType.LoadFromFile.
static bool SDC.ExtensionType.LoadFromFile(string fileName, out ExtensionType obj, out System.Exception exception)
static bool SDC.ExtensionType.LoadFromFile(string fileName, out ExtensionType obj)
References SDC.null.
static ExtensionType SDC.ExtensionType.LoadFromFile(string fileName)
static new ExtensionType SDC.ExtensionType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ExtensionType.Deserialize(string input, out ExtensionType obj, out Exception exception)
Deserializes workflow markup into an ExtensionType object
input string workflow markup to deserialize obj Output ExtensionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ExtensionType.Deserialize, SDC.null.
static bool SDC.ExtensionType.Deserialize(string input, out ExtensionType obj)
References SDC.ExtensionType.Deserialize, SDC.null.
static new ExtensionType SDC.ExtensionType.Deserialize(string input)
References SDC.null, SDC.ExtensionType.Serializer.
static ExtensionType SDC.ExtensionType.Deserialize(Stream s)
References SDC.ExtensionType.Serializer.
static bool SDC.ExtensionType.LoadFromFile(string fileName, out ExtensionType obj, out Exception exception)
Deserializes xml markup from file into an ExtensionType object
fileName string xml file to load and deserialize obj Output ExtensionType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ExtensionType.LoadFromFile, SDC.null.
static bool SDC.ExtensionType.LoadFromFile(string fileName, out ExtensionType obj)
References SDC.ExtensionType.LoadFromFile, SDC.null.
static new ExtensionType SDC.ExtensionType.LoadFromFile(string fileName)
References SDC.ExtensionType.Deserialize, SDC.null.