SDC::EmailAddressType
string SDC.EmailAddressType::_val
ObjectChangeTracker SDC.EmailAddressType.changeTrackerField
static XmlSerializer SDC.EmailAddressType::serializer
string SDC.EmailAddressType::val
Referenced by SDC.EmailAddressType.ShouldSerializeval.
static XmlSerializer SDC.EmailAddressType::Serializer
Referenced by SDC.EmailAddressType.Deserialize.
ObjectChangeTracker SDC.EmailAddressType.ChangeTracker
SDC.EmailAddressType.EmailAddressType(BaseType parentNode)
virtual bool SDC.EmailAddressType.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.EmailAddressType.Serialize(System.Text.Encoding encoding)
Serializes current EmailAddressType object into an XML string
string XML value
virtual string SDC.EmailAddressType.Serialize()
Referenced by SDC.EmailAddressType.SaveToFile.
virtual bool SDC.EmailAddressType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current EmailAddressType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.EmailAddressType.SaveToFile.
virtual bool SDC.EmailAddressType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.EmailAddressType.SaveToFile(string fileName)
virtual void SDC.EmailAddressType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.EmailAddressType.ShouldSerializeval()
Test whether val should be serialized
References SDC.EmailAddressType.val.
virtual string SDC.EmailAddressType.Serialize()
Serializes current EmailAddressType object into an XML string
string XML value
virtual bool SDC.EmailAddressType.SaveToFile(string fileName, out Exception exception)
Serializes current EmailAddressType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.EmailAddressType.SaveToFile.
virtual void SDC.EmailAddressType.SaveToFile(string fileName)
References SDC.null, SDC.EmailAddressType.Serialize.
virtual EmailAddressType SDC.EmailAddressType.Clone()
Create a clone of this EmailAddressType object
SDC.EmailAddressType.EmailAddressType()
static bool SDC.EmailAddressType.Deserialize(string input, out EmailAddressType obj, out System.Exception exception)
Deserializes workflow markup into an EmailAddressType object
input string workflow markup to deserialize obj Output EmailAddressType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.EmailAddressType.Deserialize, SDC.EmailAddressType.LoadFromFile.
static bool SDC.EmailAddressType.Deserialize(string input, out EmailAddressType obj)
References SDC.null.
static new EmailAddressType SDC.EmailAddressType.Deserialize(string input)
References SDC.null.
static EmailAddressType SDC.EmailAddressType.Deserialize(System.IO.Stream s)
static bool SDC.EmailAddressType.LoadFromFile(string fileName, System.Text.Encoding encoding, out EmailAddressType obj, out System.Exception exception)
Deserializes xml markup from file into an EmailAddressType object
fileName string xml file to load and deserialize obj Output EmailAddressType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.EmailAddressType.LoadFromFile.
static bool SDC.EmailAddressType.LoadFromFile(string fileName, out EmailAddressType obj, out System.Exception exception)
static bool SDC.EmailAddressType.LoadFromFile(string fileName, out EmailAddressType obj)
References SDC.null.
static EmailAddressType SDC.EmailAddressType.LoadFromFile(string fileName)
static new EmailAddressType SDC.EmailAddressType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.EmailAddressType.Deserialize(string input, out EmailAddressType obj, out Exception exception)
Deserializes workflow markup into an EmailAddressType object
input string workflow markup to deserialize obj Output EmailAddressType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.EmailAddressType.Deserialize, SDC.null.
static bool SDC.EmailAddressType.Deserialize(string input, out EmailAddressType obj)
References SDC.EmailAddressType.Deserialize, SDC.null.
static new EmailAddressType SDC.EmailAddressType.Deserialize(string input)
References SDC.null, SDC.EmailAddressType.Serializer.
static EmailAddressType SDC.EmailAddressType.Deserialize(Stream s)
References SDC.EmailAddressType.Serializer.
static bool SDC.EmailAddressType.LoadFromFile(string fileName, out EmailAddressType obj, out Exception exception)
Deserializes xml markup from file into an EmailAddressType object
fileName string xml file to load and deserialize obj Output EmailAddressType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.EmailAddressType.LoadFromFile, SDC.null.
static bool SDC.EmailAddressType.LoadFromFile(string fileName, out EmailAddressType obj)
References SDC.EmailAddressType.LoadFromFile, SDC.null.
static new EmailAddressType SDC.EmailAddressType.LoadFromFile(string fileName)
References SDC.EmailAddressType.Deserialize, SDC.null.