SDC::ReplacedIDsType
List<anyURI_Stype> SDC.ReplacedIDsType._replacedID
BindingList<anyURI_Stype> SDC.ReplacedIDsType._replacedID
ObjectChangeTracker SDC.ReplacedIDsType.changeTrackerField
static XmlSerializer SDC.ReplacedIDsType::serializer
virtual List<anyURI_Stype> SDC.ReplacedIDsType.ReplacedID
static XmlSerializer SDC.ReplacedIDsType::Serializer
Referenced by SDC.ReplacedIDsType.Deserialize.
virtual BindingList<anyURI_Stype> SDC.ReplacedIDsType.ReplacedID
ObjectChangeTracker SDC.ReplacedIDsType.ChangeTracker
SDC.ReplacedIDsType.ReplacedIDsType()
SDC.ReplacedIDsType.ReplacedIDsType(BaseType parentNode)
virtual bool SDC.ReplacedIDsType.ShouldSerializeReplacedID()
Test whether ReplacedID should be serialized
References SDC.null.
virtual string SDC.ReplacedIDsType.Serialize(System.Text.Encoding encoding)
Serializes current ReplacedIDsType object into an XML string
string XML value
virtual string SDC.ReplacedIDsType.Serialize()
Referenced by SDC.ReplacedIDsType.SaveToFile.
virtual bool SDC.ReplacedIDsType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReplacedIDsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReplacedIDsType.SaveToFile.
virtual bool SDC.ReplacedIDsType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ReplacedIDsType.SaveToFile(string fileName)
virtual void SDC.ReplacedIDsType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ReplacedIDsType.Serialize()
Serializes current ReplacedIDsType object into an XML string
string XML value
virtual bool SDC.ReplacedIDsType.SaveToFile(string fileName, out Exception exception)
Serializes current ReplacedIDsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ReplacedIDsType.SaveToFile.
virtual void SDC.ReplacedIDsType.SaveToFile(string fileName)
References SDC.null, SDC.ReplacedIDsType.Serialize.
virtual ReplacedIDsType SDC.ReplacedIDsType.Clone()
Create a clone of this ReplacedIDsType object
static bool SDC.ReplacedIDsType.Deserialize(string input, out ReplacedIDsType obj, out System.Exception exception)
Deserializes workflow markup into an ReplacedIDsType object
input string workflow markup to deserialize obj Output ReplacedIDsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReplacedIDsType.Deserialize, SDC.ReplacedIDsType.LoadFromFile.
static bool SDC.ReplacedIDsType.Deserialize(string input, out ReplacedIDsType obj)
References SDC.null.
static new ReplacedIDsType SDC.ReplacedIDsType.Deserialize(string input)
References SDC.null.
static ReplacedIDsType SDC.ReplacedIDsType.Deserialize(System.IO.Stream s)
static bool SDC.ReplacedIDsType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReplacedIDsType obj, out System.Exception exception)
Deserializes xml markup from file into an ReplacedIDsType object
fileName string xml file to load and deserialize obj Output ReplacedIDsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReplacedIDsType.LoadFromFile.
static bool SDC.ReplacedIDsType.LoadFromFile(string fileName, out ReplacedIDsType obj, out System.Exception exception)
static bool SDC.ReplacedIDsType.LoadFromFile(string fileName, out ReplacedIDsType obj)
References SDC.null.
static ReplacedIDsType SDC.ReplacedIDsType.LoadFromFile(string fileName)
static new ReplacedIDsType SDC.ReplacedIDsType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ReplacedIDsType.Deserialize(string input, out ReplacedIDsType obj, out Exception exception)
Deserializes workflow markup into an ReplacedIDsType object
input string workflow markup to deserialize obj Output ReplacedIDsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ReplacedIDsType.Deserialize, SDC.null.
static bool SDC.ReplacedIDsType.Deserialize(string input, out ReplacedIDsType obj)
References SDC.ReplacedIDsType.Deserialize, SDC.null.
static new ReplacedIDsType SDC.ReplacedIDsType.Deserialize(string input)
References SDC.null, SDC.ReplacedIDsType.Serializer.
static ReplacedIDsType SDC.ReplacedIDsType.Deserialize(Stream s)
References SDC.ReplacedIDsType.Serializer.
static bool SDC.ReplacedIDsType.LoadFromFile(string fileName, out ReplacedIDsType obj, out Exception exception)
Deserializes xml markup from file into an ReplacedIDsType object
fileName string xml file to load and deserialize obj Output ReplacedIDsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ReplacedIDsType.LoadFromFile, SDC.null.
static bool SDC.ReplacedIDsType.LoadFromFile(string fileName, out ReplacedIDsType obj)
References SDC.ReplacedIDsType.LoadFromFile, SDC.null.
static new ReplacedIDsType SDC.ReplacedIDsType.LoadFromFile(string fileName)
References SDC.ReplacedIDsType.Deserialize, SDC.null.