SDC::FormDesignType
ITreeBuilder SDC.FormDesignType.InjectTreeBuilder
virtual EventType SDC.FormDesignType.BeforeLoadForm
NEW: This event is fired before the page is loaded into memory, and before stored form data is loaded. It may be used, e.g., for authentication, to retrieve/prepare stored data, and/or to control form rendering according to user preferences.
virtual EventType SDC.FormDesignType.BeforeLoadData
NEW: This event is fired after the page is loaded into memory, before stored form data is loaded, and before the form is visible. For example, It may be used to determine the data to be loaded and to perform the data loading.
virtual EventType SDC.FormDesignType.BeforeShowForm
NEW: This event is fired after the page is loaded is memory, after the data is loaded into the form, but before the form is displayed. It may be used to perform form activities that are controlled by the loaded data.
virtual EventType SDC.FormDesignType.BeforeDataSubmit
virtual EventType SDC.FormDesignType.BeforeCloseForm
SectionItemType SDC.FormDesignType::Header
Optional Section that stays at the top of a form.
Referenced by SDC.SDCTreeBuilder.AddHeader, SDC.SDCTreeBuilder.CreateFormDesignTree.
SectionItemType SDC.FormDesignType::Body
Main Section of form
Referenced by SDC.SDCTreeBuilder.AddBody, SDC.SDCTreeBuilder.CreateFormDesignTree.
SectionItemType SDC.FormDesignType::Footer
Optional Section that stays at the bottom of a form.
Referenced by SDC.SDCTreeBuilder.AddFooter, SDC.SDCTreeBuilder.CreateFormDesignTree.
RulesType SDC.FormDesignType::Rules
virtual string SDC.FormDesignType.formTitle
NEW: human readable title for display when choosing forms. Added 4/27/16
Referenced by SDC.FormDesignType.ShouldSerializeformTitle.
virtual string SDC.FormDesignType.filename
NEW: filename to use when the current FormDesign instance is saved as a file. For forms containing responses, the filename may include the formInstanceVersionURI, but the naming convention may be use-case-specific.
Referenced by SDC.FormDesignType.ShouldSerializefilename.
virtual string SDC.FormDesignType.basedOnURI
NEW: URI used to identify the form that that this FormDesign is based upon. In most cases, this should be a standard form that is modified and/or extended by the current FormDesign.
The current template reuses the basedOn IDs whenever the question/answer/semantic context is identical to the original.5/11/17: Relying on data element mapping may be a better and more flexible approach than . In this way, forms could compare data elements to determine if they contain semantic matches, and this is supported better with a more robust code map section.
Referenced by SDC.FormDesignType.ShouldSerializebasedOnURI.
virtual string SDC.FormDesignType.lineage
NEW: A text identifier that is used to group multiple versions of a single form. The lineage is constant for all versions of a single kind of form.
When appended to , it can be used to retrieve all versions of one particular form.
Referenced by SDC.FormDesignType.ShouldSerializelineage.
virtual string SDC.FormDesignType.version
NEW:
contains the version text for the current form. It is designed to be used in conjuction with and .
Referenced by SDC.FormDesignType.ShouldSerializeversion.
virtual string SDC.FormDesignType.fullURI
NEW: The full URI that uniquely identifies the current form. It is created by concatenating + lineage + version. Each of the componenets is separated by a single forward slash.
Referenced by SDC.FormDesignType.ShouldSerializefullURI.
virtual string SDC.FormDesignType.prevVersionURI
NEW: The full URI used to identify the form that is the immediate previous version of the current FormDesign
Referenced by SDC.FormDesignType.ShouldSerializeprevVersionURI.
string SDC.FormDesignType::formInstanceURI
NEW: Unique URI used to identify a unique instance of a form. Used for tracking form responses across time and across multiple episodes of editing by end-users. This URI does not change for each edit session of a form instance.
Referenced by SDC.FormDesignType.ShouldSerializeformInstanceURI.
string SDC.FormDesignType::formInstanceVersionURI
NEW: Unique URI used to identify a unique instance of a form's saved responses. It is used for tracking form responses across time and across multiple episodes of editing by end-users. This URI must change for each edit/save session of a form instance. It may be e.g., a new GUID, or a repeat of the formInstanceID followed by a version number.
NEW: Unique URI used to identify a unique instance of a form. Used for tracking form responses across time and across multiple episodes of editing by end-users. This URI must change for each edit session of a form instance.
Referenced by SDC.FormDesignType.ShouldSerializeformInstanceVersionURI.
virtual string SDC.FormDesignType.formPreviousInstanceVersionURI
NEW: Unique URI used to identify the immediate previous instance of a form containing responses. This is the that represents the instance of the form that the user opened up before beginning a new cycle of edit/save. This attribute is used for tracking form responses across time and across multiple episodes of editing by end-users. This URI must change for each edit session of a form instance.
Referenced by SDC.FormDesignType.ShouldSerializeformPreviousInstanceVersionURI.
virtual SectionBaseTypeResponseTypeEnum SDC.FormDesignType.responseTypeEnum
bool SDC.FormDesignType::responseTypeEnumSpecified
virtual SectionBaseTypeResponseStatusEnum SDC.FormDesignType.responseStatusEnum
bool SDC.FormDesignType::responseStatusEnumSpecified
static XmlSerializer SDC.FormDesignType::Serializer
Referenced by SDC.FormDesignType.Deserialize.
virtual QuestionItemBaseTypeResponseTypeEnum SDC.FormDesignType.responseTypeEnum
virtual QuestionItemBaseTypeResponseStatusEnum SDC.FormDesignType.responseStatusEnum
ObjectChangeTracker SDC.FormDesignType.ChangeTracker
EventType SDC.FormDesignType._beforeLoadForm
Referenced by SDC.FormDesignType.ShouldSerializeBeforeLoadForm.
EventType SDC.FormDesignType._beforeLoadData
Referenced by SDC.FormDesignType.ShouldSerializeBeforeLoadData.
EventType SDC.FormDesignType._beforeShowForm
Referenced by SDC.FormDesignType.ShouldSerializeBeforeShowForm.
EventType SDC.FormDesignType._beforeDataSubmit
Referenced by SDC.FormDesignType.ShouldSerializeBeforeDataSubmit.
EventType SDC.FormDesignType._beforeCloseForm
Referenced by SDC.FormDesignType.ShouldSerializeBeforeCloseForm.
SectionItemType SDC.FormDesignType::_header
Referenced by SDC.FormDesignType.ShouldSerializeHeader.
SectionItemType SDC.FormDesignType::_body
Referenced by SDC.FormDesignType.ShouldSerializeBody.
SectionItemType SDC.FormDesignType::_footer
Referenced by SDC.FormDesignType.ShouldSerializeFooter.
RulesType SDC.FormDesignType::_rules
Referenced by SDC.FormDesignType.ShouldSerializeRules.
string SDC.FormDesignType._formTitle
string SDC.FormDesignType._filename
string SDC.FormDesignType._basedOnURI
string SDC.FormDesignType._lineage
string SDC.FormDesignType._version
string SDC.FormDesignType._fullURI
string SDC.FormDesignType._prevVersionURI
string SDC.FormDesignType::_formInstanceURI
string SDC.FormDesignType::_formInstanceVersionURI
string SDC.FormDesignType._formPreviousInstanceVersionURI
System.Nullable<SectionBaseTypeResponseTypeEnum> SDC.FormDesignType._responseTypeEnum
System.Nullable<SectionBaseTypeResponseStatusEnum> SDC.FormDesignType._responseStatusEnum
System.Nullable<QuestionItemBaseTypeResponseTypeEnum> SDC.FormDesignType._responseTypeEnum
System.Nullable<QuestionItemBaseTypeResponseStatusEnum> SDC.FormDesignType._responseStatusEnum
ObjectChangeTracker SDC.FormDesignType.changeTrackerField
static XmlSerializer SDC.FormDesignType::serializer
SDC.FormDesignType.FormDesignType()
SDC.FormDesignType.FormDesignType(ITreeBuilder treeBuilder, BaseType parentNode=null, bool fillData=false, string id=null)
References SDC.BaseType.sdcTreeBuilder.
SectionItemType SDC.FormDesignType.AddBody(bool fillData=false, string id=null)
SectionItemType SDC.FormDesignType.AddFooter(bool fillData=false, string id=null)
SectionItemType SDC.FormDesignType.AddHeader(bool fillData=false, string id=null)
RulesType SDC.FormDesignType.AddRules()
References SDC.null.
SectionItemType SDC.FormDesignType.AddHeader()
References SDC.var.
SectionItemType SDC.FormDesignType.AddBody()
References SDC.SectionItemType, SDC.var.
SectionItemType SDC.FormDesignType.AddFooter()
References SDC.SectionItemType, SDC.var.
RulesType SDC.FormDesignType.AddRules()
References SDC.RulesType, SDC.var.
virtual bool SDC.FormDesignType.ShouldSerializeBeforeLoadForm()
Test whether BeforeLoadForm should be serialized
References SDC.FormDesignType._beforeLoadForm, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeBeforeLoadData()
Test whether BeforeLoadData should be serialized
References SDC.FormDesignType._beforeLoadData, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeBeforeShowForm()
Test whether BeforeShowForm should be serialized
References SDC.FormDesignType._beforeShowForm, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeBeforeDataSubmit()
Test whether BeforeDataSubmit should be serialized
References SDC.FormDesignType._beforeDataSubmit, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeBeforeCloseForm()
Test whether BeforeCloseForm should be serialized
References SDC.FormDesignType._beforeCloseForm, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeHeader()
Test whether Header should be serialized
References SDC.FormDesignType._header, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeBody()
Test whether Body should be serialized
References SDC.FormDesignType._body, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeFooter()
Test whether Footer should be serialized
References SDC.FormDesignType._footer, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeRules()
Test whether Rules should be serialized
References SDC.FormDesignType._rules, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeformTitle()
Test whether formTitle should be serialized
References SDC.FormDesignType.formTitle.
virtual bool SDC.FormDesignType.ShouldSerializefilename()
Test whether filename should be serialized
References SDC.FormDesignType.filename.
virtual bool SDC.FormDesignType.ShouldSerializebasedOnURI()
Test whether basedOnURI should be serialized
References SDC.FormDesignType.basedOnURI.
virtual bool SDC.FormDesignType.ShouldSerializelineage()
Test whether lineage should be serialized
References SDC.FormDesignType.lineage.
virtual bool SDC.FormDesignType.ShouldSerializeversion()
Test whether version should be serialized
References SDC.FormDesignType.version.
virtual bool SDC.FormDesignType.ShouldSerializefullURI()
Test whether fullURI should be serialized
References SDC.FormDesignType.fullURI.
virtual bool SDC.FormDesignType.ShouldSerializeprevVersionURI()
Test whether prevVersionURI should be serialized
References SDC.FormDesignType.prevVersionURI.
virtual bool SDC.FormDesignType.ShouldSerializeformInstanceURI()
Test whether formInstanceURI should be serialized
References SDC.FormDesignType.formInstanceURI.
virtual bool SDC.FormDesignType.ShouldSerializeformInstanceVersionURI()
Test whether formInstanceVersionURI should be serialized
References SDC.FormDesignType.formInstanceVersionURI.
virtual bool SDC.FormDesignType.ShouldSerializeformPreviousInstanceVersionURI()
Test whether formPreviousInstanceVersionURI should be serialized
References SDC.FormDesignType.formPreviousInstanceVersionURI.
virtual string SDC.FormDesignType.Serialize(System.Text.Encoding encoding)
Serializes current FormDesignType object into an XML string
string XML value
virtual string SDC.FormDesignType.Serialize()
Referenced by SDC.FormDesignType.SaveToFile.
virtual bool SDC.FormDesignType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current FormDesignType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.FormDesignType.SaveToFile.
virtual bool SDC.FormDesignType.SaveToFile(string fileName, out System.Exception exception)
References SDC.FormDesignType.SaveToFile.
virtual void SDC.FormDesignType.SaveToFile(string fileName)
References SDC.FormDesignType.SaveToFile.
virtual void SDC.FormDesignType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.FormDesignType.Serialize.
virtual bool SDC.FormDesignType.ShouldSerializeHeader()
Test whether Header should be serialized
References SDC.FormDesignType._header, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeBody()
Test whether Body should be serialized
References SDC.FormDesignType._body, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeFooter()
Test whether Footer should be serialized
References SDC.FormDesignType._footer, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeRules()
Test whether Rules should be serialized
References SDC.FormDesignType._rules, SDC.null.
virtual bool SDC.FormDesignType.ShouldSerializeformInstanceURI()
Test whether formInstanceURI should be serialized
References SDC.FormDesignType.formInstanceURI.
virtual bool SDC.FormDesignType.ShouldSerializeformInstanceVersionURI()
Test whether formInstanceVersionURI should be serialized
References SDC.FormDesignType.formInstanceVersionURI.
virtual string SDC.FormDesignType.Serialize()
Serializes current FormDesignType object into an XML string
string XML value
virtual bool SDC.FormDesignType.SaveToFile(string fileName, out Exception exception)
Serializes current FormDesignType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.FormDesignType.SaveToFile.
virtual void SDC.FormDesignType.SaveToFile(string fileName)
References SDC.null, SDC.FormDesignType.Serialize.
virtual FormDesignType SDC.FormDesignType.Clone()
Create a clone of this FormDesignType object
static bool SDC.FormDesignType.Deserialize(string input, out FormDesignType obj, out System.Exception exception)
Deserializes workflow markup into an FormDesignType object
input string workflow markup to deserialize obj Output FormDesignType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.FormDesignType.Deserialize, SDC.FormDesignType.LoadFromFile.
static bool SDC.FormDesignType.Deserialize(string input, out FormDesignType obj)
References SDC.FormDesignType.Deserialize, SDC.null.
static new FormDesignType SDC.FormDesignType.Deserialize(string input)
References SDC.null.
static FormDesignType SDC.FormDesignType.Deserialize(System.IO.Stream s)
References SDC.FormDesignType.Serializer.
static bool SDC.FormDesignType.LoadFromFile(string fileName, System.Text.Encoding encoding, out FormDesignType obj, out System.Exception exception)
Deserializes xml markup from file into an FormDesignType object
fileName string xml file to load and deserialize obj Output FormDesignType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.FormDesignType.LoadFromFile.
static bool SDC.FormDesignType.LoadFromFile(string fileName, out FormDesignType obj, out System.Exception exception)
References SDC.FormDesignType.LoadFromFile.
static bool SDC.FormDesignType.LoadFromFile(string fileName, out FormDesignType obj)
References SDC.FormDesignType.LoadFromFile, SDC.null.
static FormDesignType SDC.FormDesignType.LoadFromFile(string fileName)
References SDC.FormDesignType.LoadFromFile.
static new FormDesignType SDC.FormDesignType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.FormDesignType.Deserialize, SDC.null.
static bool SDC.FormDesignType.Deserialize(string input, out FormDesignType obj, out Exception exception)
Deserializes workflow markup into an FormDesignType object
input string workflow markup to deserialize obj Output FormDesignType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.FormDesignType.Deserialize, SDC.null.
static bool SDC.FormDesignType.Deserialize(string input, out FormDesignType obj)
References SDC.FormDesignType.Deserialize, SDC.null.
static new FormDesignType SDC.FormDesignType.Deserialize(string input)
References SDC.null, SDC.FormDesignType.Serializer.
static FormDesignType SDC.FormDesignType.Deserialize(Stream s)
References SDC.FormDesignType.Serializer.
static bool SDC.FormDesignType.LoadFromFile(string fileName, out FormDesignType obj, out Exception exception)
Deserializes xml markup from file into an FormDesignType object
fileName string xml file to load and deserialize obj Output FormDesignType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.FormDesignType.LoadFromFile, SDC.null.
static bool SDC.FormDesignType.LoadFromFile(string fileName, out FormDesignType obj)
References SDC.FormDesignType.LoadFromFile, SDC.null.
static new FormDesignType SDC.FormDesignType.LoadFromFile(string fileName)
References SDC.FormDesignType.Deserialize, SDC.null.