SDC::OrganizationType
string_Stype SDC.OrganizationType::_orgName
Referenced by SDC.OrganizationType.ShouldSerializeOrgName.
string_Stype SDC.OrganizationType::_department
Referenced by SDC.OrganizationType.ShouldSerializeDepartment.
List<AddressType> SDC.OrganizationType._streetAddress
List<EmailType> SDC.OrganizationType._email
List<PhoneType> SDC.OrganizationType._phone
List<anyURI_Stype> SDC.OrganizationType._webURL
List<string_Stype> SDC.OrganizationType._role
List<PersonType> SDC.OrganizationType._contactPerson
List<IdentifierType> SDC.OrganizationType._identifier
string_Stype SDC.OrganizationType::_usage
Referenced by SDC.OrganizationType.ShouldSerializeUsage.
BindingList<AddressType> SDC.OrganizationType._streetAddress
BindingList<EmailType> SDC.OrganizationType._email
BindingList<PhoneType> SDC.OrganizationType._phone
BindingList<anyURI_Stype> SDC.OrganizationType._webURL
BindingList<string_Stype> SDC.OrganizationType._role
BindingList<PersonType> SDC.OrganizationType._contactPerson
BindingList<IdentifierType> SDC.OrganizationType._identifier
ObjectChangeTracker SDC.OrganizationType.changeTrackerField
static XmlSerializer SDC.OrganizationType::serializer
string_Stype SDC.OrganizationType::OrgName
string_Stype SDC.OrganizationType::Department
virtual List<AddressType> SDC.OrganizationType.StreetAddress
virtual List<EmailType> SDC.OrganizationType.Email
virtual List<PhoneType> SDC.OrganizationType.Phone
virtual List<anyURI_Stype> SDC.OrganizationType.WebURL
virtual List<string_Stype> SDC.OrganizationType.Role
Role of the organization, e.g., creator, copyright holder, accreditor, certifier, curator, etc.
virtual List<PersonType> SDC.OrganizationType.ContactPerson
Referenced by SDC.SDCTreeBuilder.AddContactPerson.
virtual List<IdentifierType> SDC.OrganizationType.Identifier
string_Stype SDC.OrganizationType::Usage
When this organization should be contacted.
static XmlSerializer SDC.OrganizationType::Serializer
Referenced by SDC.OrganizationType.Deserialize.
virtual BindingList<AddressType> SDC.OrganizationType.StreetAddress
virtual BindingList<EmailType> SDC.OrganizationType.Email
virtual BindingList<PhoneType> SDC.OrganizationType.Phone
virtual BindingList<anyURI_Stype> SDC.OrganizationType.WebURL
virtual BindingList<string_Stype> SDC.OrganizationType.Role
Role of the organization, e.g., creator, copyright holder, accreditor, certifier, curator, etc.
virtual BindingList<PersonType> SDC.OrganizationType.ContactPerson
virtual BindingList<IdentifierType> SDC.OrganizationType.Identifier
ObjectChangeTracker SDC.OrganizationType.ChangeTracker
SDC.OrganizationType.OrganizationType()
SDC.OrganizationType.OrganizationType(BaseType parentNode)
SDC.OrganizationType.OrganizationType()
virtual bool SDC.OrganizationType.ShouldSerializeStreetAddress()
Test whether StreetAddress should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeEmail()
Test whether Email should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializePhone()
Test whether Phone should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeWebURL()
Test whether WebURL should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeRole()
Test whether Role should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeContactPerson()
Test whether ContactPerson should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeIdentifier()
Test whether Identifier should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeOrgName()
Test whether OrgName should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeDepartment()
Test whether Department should be serialized
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.null.
virtual string SDC.OrganizationType.Serialize(System.Text.Encoding encoding)
Serializes current OrganizationType object into an XML string
string XML value
virtual string SDC.OrganizationType.Serialize()
Referenced by SDC.OrganizationType.SaveToFile.
virtual bool SDC.OrganizationType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current OrganizationType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.OrganizationType.SaveToFile.
virtual bool SDC.OrganizationType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.OrganizationType.SaveToFile(string fileName)
virtual void SDC.OrganizationType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeOrgName()
Test whether OrgName should be serialized
References SDC.OrganizationType._orgName, SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeDepartment()
Test whether Department should be serialized
References SDC.OrganizationType._department, SDC.null.
virtual bool SDC.OrganizationType.ShouldSerializeUsage()
Test whether Usage should be serialized
References SDC.OrganizationType._usage, SDC.null.
virtual string SDC.OrganizationType.Serialize()
Serializes current OrganizationType object into an XML string
string XML value
virtual bool SDC.OrganizationType.SaveToFile(string fileName, out Exception exception)
Serializes current OrganizationType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.OrganizationType.SaveToFile.
virtual void SDC.OrganizationType.SaveToFile(string fileName)
References SDC.null, SDC.OrganizationType.Serialize.
virtual OrganizationType SDC.OrganizationType.Clone()
Create a clone of this OrganizationType object
static bool SDC.OrganizationType.Deserialize(string input, out OrganizationType obj, out System.Exception exception)
Deserializes workflow markup into an OrganizationType object
input string workflow markup to deserialize obj Output OrganizationType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.OrganizationType.Deserialize, SDC.OrganizationType.LoadFromFile.
static bool SDC.OrganizationType.Deserialize(string input, out OrganizationType obj)
References SDC.null.
static new OrganizationType SDC.OrganizationType.Deserialize(string input)
References SDC.null.
static OrganizationType SDC.OrganizationType.Deserialize(System.IO.Stream s)
static bool SDC.OrganizationType.LoadFromFile(string fileName, System.Text.Encoding encoding, out OrganizationType obj, out System.Exception exception)
Deserializes xml markup from file into an OrganizationType object
fileName string xml file to load and deserialize obj Output OrganizationType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.OrganizationType.LoadFromFile.
static bool SDC.OrganizationType.LoadFromFile(string fileName, out OrganizationType obj, out System.Exception exception)
static bool SDC.OrganizationType.LoadFromFile(string fileName, out OrganizationType obj)
References SDC.null.
static OrganizationType SDC.OrganizationType.LoadFromFile(string fileName)
static new OrganizationType SDC.OrganizationType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.OrganizationType.Deserialize(string input, out OrganizationType obj, out Exception exception)
Deserializes workflow markup into an OrganizationType object
input string workflow markup to deserialize obj Output OrganizationType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.OrganizationType.Deserialize, SDC.null.
static bool SDC.OrganizationType.Deserialize(string input, out OrganizationType obj)
References SDC.OrganizationType.Deserialize, SDC.null.
static new OrganizationType SDC.OrganizationType.Deserialize(string input)
References SDC.null, SDC.OrganizationType.Serializer.
static OrganizationType SDC.OrganizationType.Deserialize(Stream s)
References SDC.OrganizationType.Serializer.
static bool SDC.OrganizationType.LoadFromFile(string fileName, out OrganizationType obj, out Exception exception)
Deserializes xml markup from file into an OrganizationType object
fileName string xml file to load and deserialize obj Output OrganizationType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.OrganizationType.LoadFromFile, SDC.null.
static bool SDC.OrganizationType.LoadFromFile(string fileName, out OrganizationType obj)
References SDC.OrganizationType.LoadFromFile, SDC.null.
static new OrganizationType SDC.OrganizationType.LoadFromFile(string fileName)
References SDC.OrganizationType.Deserialize, SDC.null.