SDC::long_Stype
bool SDC.long_Stype::_shouldSerializeval
Referenced by SDC.long_Stype.ShouldSerializeval.
System Nullable< long > SDC.long_Stype::_val
Referenced by SDC.long_Stype.ShouldSerializeval.
dtQuantEnum SDC.long_Stype::_quantEnum
Referenced by SDC.long_Stype.long_Stype.
ObjectChangeTracker SDC.long_Stype.changeTrackerField
static XmlSerializer SDC.long_Stype::serializer
long SDC.long_Stype::val
bool SDC.long_Stype::valSpecified
dtQuantEnum SDC.long_Stype::quantEnum
static XmlSerializer SDC.long_Stype::Serializer
Referenced by SDC.long_Stype.Deserialize.
ObjectChangeTracker SDC.long_Stype.ChangeTracker
SDC.long_Stype.long_Stype()
SDC.long_Stype.long_Stype(BaseType parentNode)
virtual bool SDC.long_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.long_Stype._shouldSerializeval, SDC.long_Stype._val.
virtual string SDC.long_Stype.Serialize(System.Text.Encoding encoding)
Serializes current long_Stype object into an XML string
string XML value
virtual string SDC.long_Stype.Serialize()
Referenced by SDC.long_Stype.SaveToFile.
virtual bool SDC.long_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current long_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.long_Stype.SaveToFile.
virtual bool SDC.long_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.long_Stype.SaveToFile.
virtual void SDC.long_Stype.SaveToFile(string fileName)
References SDC.long_Stype.SaveToFile.
virtual void SDC.long_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.long_Stype.Serialize.
SDC.long_Stype.long_Stype()
long_Stype class constructor
References SDC.long_Stype._quantEnum.
virtual bool SDC.long_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.long_Stype._shouldSerializeval, SDC.long_Stype._val.
virtual string SDC.long_Stype.Serialize()
Serializes current long_Stype object into an XML string
string XML value
virtual bool SDC.long_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current long_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.long_Stype.SaveToFile.
virtual void SDC.long_Stype.SaveToFile(string fileName)
References SDC.null, SDC.long_Stype.Serialize.
virtual long_Stype SDC.long_Stype.Clone()
Create a clone of this long_Stype object
static bool SDC.long_Stype.Deserialize(string input, out long_Stype obj, out System.Exception exception)
Deserializes workflow markup into an long_Stype object
input string workflow markup to deserialize obj Output long_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.long_Stype.Deserialize, SDC.long_Stype.LoadFromFile.
static bool SDC.long_Stype.Deserialize(string input, out long_Stype obj)
References SDC.long_Stype.Deserialize, SDC.null.
static new long_Stype SDC.long_Stype.Deserialize(string input)
References SDC.null.
static long_Stype SDC.long_Stype.Deserialize(System.IO.Stream s)
References SDC.long_Stype.Serializer.
static bool SDC.long_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out long_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an long_Stype object
fileName string xml file to load and deserialize obj Output long_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.long_Stype.LoadFromFile.
static bool SDC.long_Stype.LoadFromFile(string fileName, out long_Stype obj, out System.Exception exception)
References SDC.long_Stype.LoadFromFile.
static bool SDC.long_Stype.LoadFromFile(string fileName, out long_Stype obj)
References SDC.long_Stype.LoadFromFile, SDC.null.
static long_Stype SDC.long_Stype.LoadFromFile(string fileName)
References SDC.long_Stype.LoadFromFile.
static new long_Stype SDC.long_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.long_Stype.Deserialize, SDC.null.
static bool SDC.long_Stype.Deserialize(string input, out long_Stype obj, out Exception exception)
Deserializes workflow markup into an long_Stype object
input string workflow markup to deserialize obj Output long_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.long_Stype.Deserialize, SDC.null.
static bool SDC.long_Stype.Deserialize(string input, out long_Stype obj)
References SDC.long_Stype.Deserialize, SDC.null.
static new long_Stype SDC.long_Stype.Deserialize(string input)
References SDC.null, SDC.long_Stype.Serializer.
static long_Stype SDC.long_Stype.Deserialize(Stream s)
References SDC.long_Stype.Serializer.
static bool SDC.long_Stype.LoadFromFile(string fileName, out long_Stype obj, out Exception exception)
Deserializes xml markup from file into an long_Stype object
fileName string xml file to load and deserialize obj Output long_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.long_Stype.LoadFromFile, SDC.null.
static bool SDC.long_Stype.LoadFromFile(string fileName, out long_Stype obj)
References SDC.long_Stype.LoadFromFile, SDC.null.
static new long_Stype SDC.long_Stype.LoadFromFile(string fileName)
References SDC.long_Stype.Deserialize, SDC.null.