SDC::ChildItemsType
List< IdentifiedExtensionType > SDC.ChildItemsType::ListOfItems
Referenced by SDC.SDCTreeBuilder.AddChildItemsNode< T >.
virtual List<IdentifiedExtensionType> SDC.ChildItemsType.Items
static XmlSerializer SDC.ChildItemsType::Serializer
Referenced by SDC.ChildItemsType.Deserialize.
virtual BindingList<IdentifiedExtensionType> SDC.ChildItemsType.Items
ObjectChangeTracker SDC.ChildItemsType.ChangeTracker
List<IdentifiedExtensionType> SDC.ChildItemsType._items
BindingList<IdentifiedExtensionType> SDC.ChildItemsType._items
ObjectChangeTracker SDC.ChildItemsType.changeTrackerField
static XmlSerializer SDC.ChildItemsType::serializer
SDC.ChildItemsType.ChildItemsType()
SDC.ChildItemsType.ChildItemsType(BaseType parentNode)
SDC.ChildItemsType.ChildItemsType()
virtual bool SDC.ChildItemsType.ShouldSerializeItems()
Test whether Items should be serialized
References SDC.null.
virtual string SDC.ChildItemsType.Serialize(System.Text.Encoding encoding)
Serializes current ChildItemsType object into an XML string
string XML value
virtual string SDC.ChildItemsType.Serialize()
Referenced by SDC.ChildItemsType.SaveToFile.
virtual bool SDC.ChildItemsType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ChildItemsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ChildItemsType.SaveToFile.
virtual bool SDC.ChildItemsType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ChildItemsType.SaveToFile(string fileName)
virtual void SDC.ChildItemsType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ChildItemsType.Serialize()
Serializes current ChildItemsType object into an XML string
string XML value
virtual bool SDC.ChildItemsType.SaveToFile(string fileName, out Exception exception)
Serializes current ChildItemsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ChildItemsType.SaveToFile.
virtual void SDC.ChildItemsType.SaveToFile(string fileName)
References SDC.null, SDC.ChildItemsType.Serialize.
virtual ChildItemsType SDC.ChildItemsType.Clone()
Create a clone of this ChildItemsType object
static bool SDC.ChildItemsType.Deserialize(string input, out ChildItemsType obj, out System.Exception exception)
Deserializes workflow markup into an ChildItemsType object
input string workflow markup to deserialize obj Output ChildItemsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChildItemsType.Deserialize, SDC.ChildItemsType.LoadFromFile.
static bool SDC.ChildItemsType.Deserialize(string input, out ChildItemsType obj)
References SDC.null.
static new ChildItemsType SDC.ChildItemsType.Deserialize(string input)
References SDC.null.
static ChildItemsType SDC.ChildItemsType.Deserialize(System.IO.Stream s)
static bool SDC.ChildItemsType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ChildItemsType obj, out System.Exception exception)
Deserializes xml markup from file into an ChildItemsType object
fileName string xml file to load and deserialize obj Output ChildItemsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChildItemsType.LoadFromFile.
static bool SDC.ChildItemsType.LoadFromFile(string fileName, out ChildItemsType obj, out System.Exception exception)
static bool SDC.ChildItemsType.LoadFromFile(string fileName, out ChildItemsType obj)
References SDC.null.
static ChildItemsType SDC.ChildItemsType.LoadFromFile(string fileName)
static new ChildItemsType SDC.ChildItemsType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ChildItemsType.Deserialize(string input, out ChildItemsType obj, out Exception exception)
Deserializes workflow markup into an ChildItemsType object
input string workflow markup to deserialize obj Output ChildItemsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChildItemsType.Deserialize, SDC.null.
static bool SDC.ChildItemsType.Deserialize(string input, out ChildItemsType obj)
References SDC.ChildItemsType.Deserialize, SDC.null.
static new ChildItemsType SDC.ChildItemsType.Deserialize(string input)
References SDC.null, SDC.ChildItemsType.Serializer.
static ChildItemsType SDC.ChildItemsType.Deserialize(Stream s)
References SDC.ChildItemsType.Serializer.
static bool SDC.ChildItemsType.LoadFromFile(string fileName, out ChildItemsType obj, out Exception exception)
Deserializes xml markup from file into an ChildItemsType object
fileName string xml file to load and deserialize obj Output ChildItemsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChildItemsType.LoadFromFile, SDC.null.
static bool SDC.ChildItemsType.LoadFromFile(string fileName, out ChildItemsType obj)
References SDC.ChildItemsType.LoadFromFile, SDC.null.
static new ChildItemsType SDC.ChildItemsType.LoadFromFile(string fileName)
References SDC.ChildItemsType.Deserialize, SDC.null.