SDC::JobType
List<string_Stype> SDC.JobType._jobTitle
OrganizationType SDC.JobType::_organization
Referenced by SDC.JobType.ShouldSerializeOrganization.
date_Stype SDC.JobType::_startDate
Referenced by SDC.JobType.ShouldSerializeStartDate.
date_Stype SDC.JobType::_stopDate
Referenced by SDC.JobType.ShouldSerializeStopDate.
string_Stype SDC.JobType::_description
Referenced by SDC.JobType.ShouldSerializeDescription.
BindingList<string_Stype> SDC.JobType._jobTitle
ObjectChangeTracker SDC.JobType.changeTrackerField
static XmlSerializer SDC.JobType::serializer
virtual List<string_Stype> SDC.JobType.JobTitle
OrganizationType SDC.JobType::Organization
date_Stype SDC.JobType::StartDate
date_Stype SDC.JobType::StopDate
string_Stype SDC.JobType::Description
Job Description
static XmlSerializer SDC.JobType::Serializer
Referenced by SDC.JobType.Deserialize.
virtual BindingList<string_Stype> SDC.JobType.JobTitle
ObjectChangeTracker SDC.JobType.ChangeTracker
SDC.JobType.JobType()
SDC.JobType.JobType(BaseType parentNode)
virtual bool SDC.JobType.ShouldSerializeJobTitle()
Test whether JobTitle should be serialized
References SDC.null.
virtual bool SDC.JobType.ShouldSerializeOrganization()
Test whether Organization should be serialized
References SDC.null.
virtual bool SDC.JobType.ShouldSerializeStartDate()
Test whether StartDate should be serialized
References SDC.null.
virtual bool SDC.JobType.ShouldSerializeStopDate()
Test whether StopDate should be serialized
References SDC.null.
virtual bool SDC.JobType.ShouldSerializeDescription()
Test whether Description should be serialized
References SDC.null.
virtual string SDC.JobType.Serialize(System.Text.Encoding encoding)
Serializes current JobType object into an XML string
string XML value
virtual string SDC.JobType.Serialize()
Referenced by SDC.JobType.SaveToFile.
virtual bool SDC.JobType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current JobType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.JobType.SaveToFile.
virtual bool SDC.JobType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.JobType.SaveToFile(string fileName)
virtual void SDC.JobType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.JobType.ShouldSerializeOrganization()
Test whether Organization should be serialized
References SDC.JobType._organization, SDC.null.
virtual bool SDC.JobType.ShouldSerializeStartDate()
Test whether StartDate should be serialized
References SDC.JobType._startDate, SDC.null.
virtual bool SDC.JobType.ShouldSerializeStopDate()
Test whether StopDate should be serialized
References SDC.JobType._stopDate, SDC.null.
virtual bool SDC.JobType.ShouldSerializeDescription()
Test whether Description should be serialized
References SDC.JobType._description, SDC.null.
virtual string SDC.JobType.Serialize()
Serializes current JobType object into an XML string
string XML value
virtual bool SDC.JobType.SaveToFile(string fileName, out Exception exception)
Serializes current JobType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.JobType.SaveToFile.
virtual void SDC.JobType.SaveToFile(string fileName)
References SDC.null, SDC.JobType.Serialize.
virtual JobType SDC.JobType.Clone()
Create a clone of this JobType object
static bool SDC.JobType.Deserialize(string input, out JobType obj, out System.Exception exception)
Deserializes workflow markup into an JobType object
input string workflow markup to deserialize obj Output JobType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.JobType.Deserialize, SDC.JobType.LoadFromFile.
static bool SDC.JobType.Deserialize(string input, out JobType obj)
References SDC.null.
static new JobType SDC.JobType.Deserialize(string input)
References SDC.null.
static JobType SDC.JobType.Deserialize(System.IO.Stream s)
static bool SDC.JobType.LoadFromFile(string fileName, System.Text.Encoding encoding, out JobType obj, out System.Exception exception)
Deserializes xml markup from file into an JobType object
fileName string xml file to load and deserialize obj Output JobType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.JobType.LoadFromFile.
static bool SDC.JobType.LoadFromFile(string fileName, out JobType obj, out System.Exception exception)
static bool SDC.JobType.LoadFromFile(string fileName, out JobType obj)
References SDC.null.
static JobType SDC.JobType.LoadFromFile(string fileName)
static new JobType SDC.JobType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.JobType.Deserialize(string input, out JobType obj, out Exception exception)
Deserializes workflow markup into an JobType object
input string workflow markup to deserialize obj Output JobType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.JobType.Deserialize, SDC.null.
static bool SDC.JobType.Deserialize(string input, out JobType obj)
References SDC.JobType.Deserialize, SDC.null.
static new JobType SDC.JobType.Deserialize(string input)
References SDC.null, SDC.JobType.Serializer.
static JobType SDC.JobType.Deserialize(Stream s)
References SDC.JobType.Serializer.
static bool SDC.JobType.LoadFromFile(string fileName, out JobType obj, out Exception exception)
Deserializes xml markup from file into an JobType object
fileName string xml file to load and deserialize obj Output JobType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.JobType.LoadFromFile, SDC.null.
static bool SDC.JobType.LoadFromFile(string fileName, out JobType obj)
References SDC.JobType.LoadFromFile, SDC.null.
static new JobType SDC.JobType.LoadFromFile(string fileName)
References SDC.JobType.Deserialize, SDC.null.