SDC::ListItemBaseType
Dictionary<string, ListItemType> SDC.ListItemBaseType.ListItems
+Replaced in original class: protected ListItemBaseType (){}
bool SDC.ListItemBaseType::_shouldSerializeomitWhenSelected
Referenced by SDC.ListItemBaseType.ShouldSerializeomitWhenSelected.
bool SDC.ListItemBaseType::_shouldSerializeselectionDeselectsSiblings
Referenced by SDC.ListItemBaseType.ShouldSerializeselectionDeselectsSiblings.
bool SDC.ListItemBaseType::_shouldSerializeselectionDisablesChildren
Referenced by SDC.ListItemBaseType.ShouldSerializeselectionDisablesChildren.
bool SDC.ListItemBaseType::_shouldSerializeselected
Referenced by SDC.ListItemBaseType.ShouldSerializeselected.
ListItemResponseFieldType SDC.ListItemBaseType::_listItemResponseField
Referenced by SDC.ListItemBaseType.ShouldSerializeListItemResponseField.
List<EventType> SDC.ListItemBaseType._onSelect
List<EventType> SDC.ListItemBaseType._onDeselect
WatchedPropertyType SDC.ListItemBaseType._selectIf
Referenced by SDC.ListItemBaseType.ShouldSerializeSelectIf.
WatchedPropertyType SDC.ListItemBaseType._deselectIf
Referenced by SDC.ListItemBaseType.ShouldSerializeDeselectIf.
bool SDC.ListItemBaseType::_selected
Referenced by SDC.ListItemBaseType.ListItemBaseType, SDC.ListItemBaseType.ShouldSerializeselected.
bool SDC.ListItemBaseType::_selectionDisablesChildren
Referenced by SDC.ListItemBaseType.ListItemBaseType, SDC.ListItemBaseType.ShouldSerializeselectionDisablesChildren.
string SDC.ListItemBaseType._selectionActivatesItems
string SDC.ListItemBaseType._selectionSelectsListItems
bool SDC.ListItemBaseType::_selectionDeselectsSiblings
Referenced by SDC.ListItemBaseType.ListItemBaseType, SDC.ListItemBaseType.ShouldSerializeselectionDeselectsSiblings.
string SDC.ListItemBaseType._x_selectionDisablesItems
string SDC.ListItemBaseType._x_SelectionDeselectsListItems
bool SDC.ListItemBaseType::_omitWhenSelected
Referenced by SDC.ListItemBaseType.ListItemBaseType, SDC.ListItemBaseType.ShouldSerializeomitWhenSelected.
string SDC.ListItemBaseType::_repeat
Referenced by SDC.ListItemBaseType.ListItemBaseType.
string SDC.ListItemBaseType::_instanceGUID
string SDC.ListItemBaseType::_parentGUID
BindingList<IfThenType> SDC.ListItemBaseType._onSelect
BindingList<IfThenType> SDC.ListItemBaseType._onDeselect
IfType SDC.ListItemBaseType._selectIf
IfType SDC.ListItemBaseType._deselectIf
ObjectChangeTracker SDC.ListItemBaseType.changeTrackerField
static XmlSerializer SDC.ListItemBaseType::serializer
ListItemResponseFieldType SDC.ListItemBaseType::ListItemResponseField
ListItemBaseType class constructor
A place to enter values (of any data type) that are directly associated with, and attached to, a selected answer choice.
virtual List<EventType> SDC.ListItemBaseType.OnSelect
Referenced by SDC.ListItemBaseType.ShouldSerializeOnSelect.
virtual List<EventType> SDC.ListItemBaseType.OnDeselect
Referenced by SDC.ListItemBaseType.ShouldSerializeOnDeselect.
virtual WatchedPropertyType SDC.ListItemBaseType.SelectIf
virtual WatchedPropertyType SDC.ListItemBaseType.DeselectIf
bool SDC.ListItemBaseType::selected
Represents the default value of the ListItem in the FormDesign template, or the user's response in selecting one or more ListItems. If ='false' on ListField then only one item may be selected.
bool SDC.ListItemBaseType::selectionDisablesChildren
If set to true, then selecting this ListItem must deactivate all descendant parts of the form, and ignore any user-entered values in the deactivated part. Deselecting the ListItem should reactivate the descendant items in their state at the time the items were deactivated.
If set to true, then selecting this ListItem must deactivate all descendant parts of the form, and ignore any user-entered values in the deactivated part. Deselecting the ListItem should reactivate the descendant items in their state at the time the items were deactivated. If items are disabled, then any data stored in the disabled questions should be removed.
virtual string SDC.ListItemBaseType.selectionActivatesItems
NEW Selecting the current ListItem will enable the named items in this attribute's content.
Prefixing any named with a hyphen (-) will reverse the above behaviour (i.e., the named items will be disabled).Unselecting the ListItem will reverse this behaviour. Prefixing the name with a tilde (~) will supress this reversal behavior.
Referenced by SDC.ListItemBaseType.ShouldSerializeselectionActivatesItems.
virtual string SDC.ListItemBaseType.selectionSelectsListItems
NEW Selecting the current ListItem will select the named ListItems in this attribute's content.
Prefixing any named with a hyphen (-) will reverse the above behaviour.Unselecting the ListItem will reverse this behaviour. Prefixing the name with a tilde (~) will supress this reversal behavior.
Referenced by SDC.ListItemBaseType.ShouldSerializeselectionSelectsListItems.
bool SDC.ListItemBaseType::selectionDeselectsSiblings
If the ancestor ListField has = 'true', then selecting this ListItem should de-select all other ListItem (sibling) nodes except the current one.
virtual string SDC.ListItemBaseType.X_selectionDisablesItems
NEW
Referenced by SDC.ListItemBaseType.ShouldSerializeX_selectionDisablesItems.
virtual string SDC.ListItemBaseType.X_SelectionDeselectsListItems
NEW: Selecting the current ListItem will cause the named items in the list (or any other list) to be de-selected. All named items must be prefixed with the $ symbol, and must point to ListItems.
Referenced by SDC.ListItemBaseType.ShouldSerializeX_SelectionDeselectsListItems.
bool SDC.ListItemBaseType::omitWhenSelected
NEW:
If is set to true, then the question and its response(s) should not be present in a typical report derived from this template. This attribute is usually set to true when the answer choice is used to control form behavior (e.g., skip logic), or when the question provides unhelpful "negative" information about actions that did not occur or were not performed, or things that were not observed or could not be assessed. If is false (default) then the question and its response(s) should appear in the report. Added 11/29/15 to replace
string SDC.ListItemBaseType::repeat
Referenced by SDC.ListItemBaseType.ShouldSerializerepeat.
string SDC.ListItemBaseType::instanceGUID
Referenced by SDC.ListItemBaseType.ShouldSerializeinstanceGUID.
string SDC.ListItemBaseType::parentGUID
Referenced by SDC.ListItemBaseType.ShouldSerializeparentGUID.
static XmlSerializer SDC.ListItemBaseType::Serializer
Referenced by SDC.ListItemBaseType.Deserialize.
virtual BindingList<IfThenType> SDC.ListItemBaseType.OnSelect
virtual BindingList<IfThenType> SDC.ListItemBaseType.OnDeselect
virtual IfType SDC.ListItemBaseType.SelectIf
virtual IfType SDC.ListItemBaseType.DeselectIf
ObjectChangeTracker SDC.ListItemBaseType.ChangeTracker
SDC.ListItemBaseType.ListItemBaseType()
SDC.ListItemBaseType.ListItemBaseType(BaseType parentNode, bool fillData=true, string id=null)
void SDC.ListItemBaseType.Fill_ListItemBaseType()
virtual bool SDC.ListItemBaseType.ShouldSerializeOnSelect()
Test whether OnSelect should be serialized
References SDC.null, SDC.ListItemBaseType.OnSelect.
virtual bool SDC.ListItemBaseType.ShouldSerializeOnDeselect()
Test whether OnDeselect should be serialized
References SDC.null, SDC.ListItemBaseType.OnDeselect.
virtual bool SDC.ListItemBaseType.ShouldSerializeselected()
Test whether selected should be serialized
References SDC.ListItemBaseType._selected, SDC.ListItemBaseType._shouldSerializeselected.
virtual bool SDC.ListItemBaseType.ShouldSerializeselectionDisablesChildren()
Test whether selectionDisablesChildren should be serialized
References SDC.ListItemBaseType._selectionDisablesChildren, SDC.ListItemBaseType._shouldSerializeselectionDisablesChildren.
virtual bool SDC.ListItemBaseType.ShouldSerializeselectionDeselectsSiblings()
Test whether selectionDeselectsSiblings should be serialized
References SDC.ListItemBaseType._selectionDeselectsSiblings, SDC.ListItemBaseType._shouldSerializeselectionDeselectsSiblings.
virtual bool SDC.ListItemBaseType.ShouldSerializeomitWhenSelected()
Test whether omitWhenSelected should be serialized
References SDC.ListItemBaseType._omitWhenSelected, SDC.ListItemBaseType._shouldSerializeomitWhenSelected.
virtual bool SDC.ListItemBaseType.ShouldSerializeListItemResponseField()
Test whether ListItemResponseField should be serialized
References SDC.ListItemBaseType._listItemResponseField, SDC.null.
virtual bool SDC.ListItemBaseType.ShouldSerializeSelectIf()
Test whether SelectIf should be serialized
References SDC.ListItemBaseType._selectIf, SDC.null.
virtual bool SDC.ListItemBaseType.ShouldSerializeDeselectIf()
Test whether DeselectIf should be serialized
References SDC.ListItemBaseType._deselectIf, SDC.null.
virtual bool SDC.ListItemBaseType.ShouldSerializeselectionActivatesItems()
Test whether selectionActivatesItems should be serialized
References SDC.ListItemBaseType.selectionActivatesItems.
virtual bool SDC.ListItemBaseType.ShouldSerializeselectionSelectsListItems()
Test whether selectionSelectsListItems should be serialized
References SDC.ListItemBaseType.selectionSelectsListItems.
virtual bool SDC.ListItemBaseType.ShouldSerializeX_selectionDisablesItems()
Test whether X_selectionDisablesItems should be serialized
References SDC.ListItemBaseType.X_selectionDisablesItems.
virtual bool SDC.ListItemBaseType.ShouldSerializeX_SelectionDeselectsListItems()
Test whether X_SelectionDeselectsListItems should be serialized
References SDC.ListItemBaseType.X_SelectionDeselectsListItems.
virtual bool SDC.ListItemBaseType.ShouldSerializerepeat()
Test whether repeat should be serialized
References SDC.ListItemBaseType.repeat.
virtual bool SDC.ListItemBaseType.ShouldSerializeinstanceGUID()
Test whether instanceGUID should be serialized
References SDC.ListItemBaseType.instanceGUID.
virtual bool SDC.ListItemBaseType.ShouldSerializeparentGUID()
Test whether parentGUID should be serialized
References SDC.ListItemBaseType.parentGUID.
virtual string SDC.ListItemBaseType.Serialize(System.Text.Encoding encoding)
Serializes current ListItemBaseType object into an XML string
string XML value
virtual string SDC.ListItemBaseType.Serialize()
Referenced by SDC.ListItemBaseType.SaveToFile.
virtual bool SDC.ListItemBaseType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ListItemBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ListItemBaseType.SaveToFile.
virtual bool SDC.ListItemBaseType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ListItemBaseType.SaveToFile.
virtual void SDC.ListItemBaseType.SaveToFile(string fileName)
References SDC.ListItemBaseType.SaveToFile.
virtual void SDC.ListItemBaseType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ListItemBaseType.Serialize.
SDC.ListItemBaseType.ListItemBaseType()
ListItemBaseType class constructor
References SDC.ListItemBaseType._omitWhenSelected, SDC.ListItemBaseType._repeat, SDC.ListItemBaseType._selected, SDC.ListItemBaseType._selectionDeselectsSiblings, SDC.ListItemBaseType._selectionDisablesChildren.
virtual bool SDC.ListItemBaseType.ShouldSerializeselected()
Test whether selected should be serialized
References SDC.ListItemBaseType._selected, SDC.ListItemBaseType._shouldSerializeselected.
virtual bool SDC.ListItemBaseType.ShouldSerializeselectionDisablesChildren()
Test whether selectionDisablesChildren should be serialized
References SDC.ListItemBaseType._selectionDisablesChildren, SDC.ListItemBaseType._shouldSerializeselectionDisablesChildren.
virtual bool SDC.ListItemBaseType.ShouldSerializeselectionDeselectsSiblings()
Test whether selectionDeselectsSiblings should be serialized
References SDC.ListItemBaseType._selectionDeselectsSiblings, SDC.ListItemBaseType._shouldSerializeselectionDeselectsSiblings.
virtual bool SDC.ListItemBaseType.ShouldSerializeomitWhenSelected()
Test whether omitWhenSelected should be serialized
References SDC.ListItemBaseType._omitWhenSelected, SDC.ListItemBaseType._shouldSerializeomitWhenSelected.
virtual bool SDC.ListItemBaseType.ShouldSerializeListItemResponseField()
Test whether ListItemResponseField should be serialized
References SDC.ListItemBaseType._listItemResponseField, SDC.null.
virtual bool SDC.ListItemBaseType.ShouldSerializeSelectIf()
Test whether SelectIf should be serialized
References SDC.ListItemBaseType._selectIf, SDC.null.
virtual bool SDC.ListItemBaseType.ShouldSerializeDeselectIf()
Test whether DeselectIf should be serialized
References SDC.ListItemBaseType._deselectIf, SDC.null.
virtual bool SDC.ListItemBaseType.ShouldSerializerepeat()
Test whether repeat should be serialized
References SDC.ListItemBaseType.repeat.
virtual bool SDC.ListItemBaseType.ShouldSerializeinstanceGUID()
Test whether instanceGUID should be serialized
References SDC.ListItemBaseType.instanceGUID.
virtual bool SDC.ListItemBaseType.ShouldSerializeparentGUID()
Test whether parentGUID should be serialized
References SDC.ListItemBaseType.parentGUID.
virtual string SDC.ListItemBaseType.Serialize()
Serializes current ListItemBaseType object into an XML string
string XML value
virtual bool SDC.ListItemBaseType.SaveToFile(string fileName, out Exception exception)
Serializes current ListItemBaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ListItemBaseType.SaveToFile.
virtual void SDC.ListItemBaseType.SaveToFile(string fileName)
References SDC.null, SDC.ListItemBaseType.Serialize.
virtual ListItemBaseType SDC.ListItemBaseType.Clone()
Create a clone of this ListItemBaseType object
static bool SDC.ListItemBaseType.Deserialize(string input, out ListItemBaseType obj, out System.Exception exception)
Deserializes workflow markup into an ListItemBaseType object
input string workflow markup to deserialize obj Output ListItemBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListItemBaseType.Deserialize, SDC.ListItemBaseType.LoadFromFile.
static bool SDC.ListItemBaseType.Deserialize(string input, out ListItemBaseType obj)
References SDC.ListItemBaseType.Deserialize, SDC.null.
static new ListItemBaseType SDC.ListItemBaseType.Deserialize(string input)
References SDC.null.
static ListItemBaseType SDC.ListItemBaseType.Deserialize(System.IO.Stream s)
References SDC.ListItemBaseType.Serializer.
static bool SDC.ListItemBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ListItemBaseType obj, out System.Exception exception)
Deserializes xml markup from file into an ListItemBaseType object
fileName string xml file to load and deserialize obj Output ListItemBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListItemBaseType.LoadFromFile.
static bool SDC.ListItemBaseType.LoadFromFile(string fileName, out ListItemBaseType obj, out System.Exception exception)
References SDC.ListItemBaseType.LoadFromFile.
static bool SDC.ListItemBaseType.LoadFromFile(string fileName, out ListItemBaseType obj)
References SDC.ListItemBaseType.LoadFromFile, SDC.null.
static ListItemBaseType SDC.ListItemBaseType.LoadFromFile(string fileName)
References SDC.ListItemBaseType.LoadFromFile.
static new ListItemBaseType SDC.ListItemBaseType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ListItemBaseType.Deserialize, SDC.null.
static bool SDC.ListItemBaseType.Deserialize(string input, out ListItemBaseType obj, out Exception exception)
Deserializes workflow markup into an ListItemBaseType object
input string workflow markup to deserialize obj Output ListItemBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListItemBaseType.Deserialize, SDC.null.
static bool SDC.ListItemBaseType.Deserialize(string input, out ListItemBaseType obj)
References SDC.ListItemBaseType.Deserialize, SDC.null.
static new ListItemBaseType SDC.ListItemBaseType.Deserialize(string input)
References SDC.null, SDC.ListItemBaseType.Serializer.
static ListItemBaseType SDC.ListItemBaseType.Deserialize(Stream s)
References SDC.ListItemBaseType.Serializer.
static bool SDC.ListItemBaseType.LoadFromFile(string fileName, out ListItemBaseType obj, out Exception exception)
Deserializes xml markup from file into an ListItemBaseType object
fileName string xml file to load and deserialize obj Output ListItemBaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListItemBaseType.LoadFromFile, SDC.null.
static bool SDC.ListItemBaseType.LoadFromFile(string fileName, out ListItemBaseType obj)
References SDC.ListItemBaseType.LoadFromFile, SDC.null.
static new ListItemBaseType SDC.ListItemBaseType.LoadFromFile(string fileName)
References SDC.ListItemBaseType.Deserialize, SDC.null.