SDC::GetPropertyValuesType
bool SDC.GetPropertyValuesType._shouldSerializeisReadOnly
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisReadOnly.
bool SDC.GetPropertyValuesType._shouldSerializeisRequired
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisRequired.
bool SDC.GetPropertyValuesType._shouldSerializeisEnabled
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisEnabled.
bool SDC.GetPropertyValuesType._shouldSerializeisVisible
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisVisible.
bool SDC.GetPropertyValuesType._shouldSerializehasResponse
Referenced by SDC.GetPropertyValuesType.ShouldSerializehasResponse.
bool SDC.GetPropertyValuesType._shouldSerializeisActive
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisActive.
bool SDC.GetPropertyValuesType._shouldSerializeisSelected
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisSelected.
bool SDC.GetPropertyValuesType._shouldSerializenot
Referenced by SDC.GetPropertyValuesType.ShouldSerializenot.
bool SDC.GetPropertyValuesType._not
Referenced by SDC.GetPropertyValuesType.GetPropertyValuesType, SDC.GetPropertyValuesType.ShouldSerializenot.
GetPropertyValuesTypeBoolOpEnum SDC.GetPropertyValuesType._boolOpEnum
Referenced by SDC.GetPropertyValuesType.GetPropertyValuesType.
string SDC.GetPropertyValuesType._itemNames
bool SDC.GetPropertyValuesType._isSelected
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisSelected.
bool SDC.GetPropertyValuesType._isActive
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisActive.
bool SDC.GetPropertyValuesType._hasResponse
Referenced by SDC.GetPropertyValuesType.ShouldSerializehasResponse.
bool SDC.GetPropertyValuesType._isVisible
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisVisible.
bool SDC.GetPropertyValuesType._isEnabled
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisEnabled.
bool SDC.GetPropertyValuesType._isRequired
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisRequired.
bool SDC.GetPropertyValuesType._isReadOnly
Referenced by SDC.GetPropertyValuesType.ShouldSerializeisReadOnly.
string SDC.GetPropertyValuesType._hasType
string SDC.GetPropertyValuesType._hasStyleClass
ObjectChangeTracker SDC.GetPropertyValuesType.changeTrackerField
XmlSerializer SDC.GetPropertyValuesType.serializer
virtual bool SDC.GetPropertyValuesType.not
virtual GetPropertyValuesTypeBoolOpEnum SDC.GetPropertyValuesType.boolOpEnum
virtual string SDC.GetPropertyValuesType.itemNames
Required name(s) of the item(s) (Section, Question, List Item) that contains the item properties used in the other attributes.
Referenced by SDC.GetPropertyValuesType.ShouldSerializeitemNames.
virtual bool SDC.GetPropertyValuesType.isSelected
virtual bool SDC.GetPropertyValuesType.isSelectedSpecified
virtual bool SDC.GetPropertyValuesType.isActive
If visible and enabled are both true, then isActive is true. Otherwise, it is false.
virtual bool SDC.GetPropertyValuesType.isActiveSpecified
virtual bool SDC.GetPropertyValuesType.hasResponse
Applies only to items that have Response Fields (Questions and ListItems). If the ListItem or Question has a Response Field, and that field has a value in it, this property returns true. If it does not have a value, it returns false. If no Response Field is present, it retuns null and is not used for Boolean comparisons.
virtual bool SDC.GetPropertyValuesType.hasResponseSpecified
virtual bool SDC.GetPropertyValuesType.isVisible
virtual bool SDC.GetPropertyValuesType.isVisibleSpecified
virtual bool SDC.GetPropertyValuesType.isEnabled
virtual bool SDC.GetPropertyValuesType.isEnabledSpecified
virtual bool SDC.GetPropertyValuesType.isRequired
If the minCard value is greater than 0, then isRequired = "true" If the minCard = "0" then isRequired = "false"
virtual bool SDC.GetPropertyValuesType.isRequiredSpecified
virtual bool SDC.GetPropertyValuesType.isReadOnly
virtual bool SDC.GetPropertyValuesType.isReadOnlySpecified
virtual string SDC.GetPropertyValuesType.hasType
Referenced by SDC.GetPropertyValuesType.ShouldSerializehasType.
virtual string SDC.GetPropertyValuesType.hasStyleClass
Referenced by SDC.GetPropertyValuesType.ShouldSerializehasStyleClass.
XmlSerializer SDC.GetPropertyValuesType.Serializer
Referenced by SDC.GetPropertyValuesType.Deserialize.
ObjectChangeTracker SDC.GetPropertyValuesType.ChangeTracker
void SDC.GetPropertyValuesType.Fill_GetPropertyValuesType()
SDC.GetPropertyValuesType.GetPropertyValuesType()
GetPropertyValuesType class constructor
References SDC.GetPropertyValuesType._boolOpEnum, SDC.GetPropertyValuesType._not.
virtual bool SDC.GetPropertyValuesType.ShouldSerializenot()
Test whether not should be serialized
References SDC.GetPropertyValuesType._not, SDC.GetPropertyValuesType._shouldSerializenot.
virtual bool SDC.GetPropertyValuesType.ShouldSerializeisSelected()
Test whether isSelected should be serialized
References SDC.GetPropertyValuesType._isSelected, SDC.GetPropertyValuesType._shouldSerializeisSelected.
virtual bool SDC.GetPropertyValuesType.ShouldSerializeisActive()
Test whether isActive should be serialized
References SDC.GetPropertyValuesType._isActive, SDC.GetPropertyValuesType._shouldSerializeisActive.
virtual bool SDC.GetPropertyValuesType.ShouldSerializehasResponse()
Test whether hasResponse should be serialized
References SDC.GetPropertyValuesType._hasResponse, SDC.GetPropertyValuesType._shouldSerializehasResponse.
virtual bool SDC.GetPropertyValuesType.ShouldSerializeisVisible()
Test whether isVisible should be serialized
References SDC.GetPropertyValuesType._isVisible, SDC.GetPropertyValuesType._shouldSerializeisVisible.
virtual bool SDC.GetPropertyValuesType.ShouldSerializeisEnabled()
Test whether isEnabled should be serialized
References SDC.GetPropertyValuesType._isEnabled, SDC.GetPropertyValuesType._shouldSerializeisEnabled.
virtual bool SDC.GetPropertyValuesType.ShouldSerializeisRequired()
Test whether isRequired should be serialized
References SDC.GetPropertyValuesType._isRequired, SDC.GetPropertyValuesType._shouldSerializeisRequired.
virtual bool SDC.GetPropertyValuesType.ShouldSerializeisReadOnly()
Test whether isReadOnly should be serialized
References SDC.GetPropertyValuesType._isReadOnly, SDC.GetPropertyValuesType._shouldSerializeisReadOnly.
virtual bool SDC.GetPropertyValuesType.ShouldSerializeitemNames()
Test whether itemNames should be serialized
References SDC.GetPropertyValuesType.itemNames.
virtual bool SDC.GetPropertyValuesType.ShouldSerializehasType()
Test whether hasType should be serialized
References SDC.GetPropertyValuesType.hasType.
virtual bool SDC.GetPropertyValuesType.ShouldSerializehasStyleClass()
Test whether hasStyleClass should be serialized
References SDC.GetPropertyValuesType.hasStyleClass.
virtual string SDC.GetPropertyValuesType.Serialize()
Serializes current GetPropertyValuesType object into an XML string
string XML value
Referenced by SDC.GetPropertyValuesType.SaveToFile.
virtual bool SDC.GetPropertyValuesType.SaveToFile(string fileName, out Exception exception)
Serializes current GetPropertyValuesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.GetPropertyValuesType.SaveToFile(string fileName)
References SDC.null, SDC.GetPropertyValuesType.Serialize.
virtual GetPropertyValuesType SDC.GetPropertyValuesType.Clone()
Create a clone of this GetPropertyValuesType object
static bool SDC.GetPropertyValuesType.Deserialize(string input, out GetPropertyValuesType obj, out Exception exception)
Deserializes workflow markup into an GetPropertyValuesType object
input string workflow markup to deserialize obj Output GetPropertyValuesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.GetPropertyValuesType.Deserialize, SDC.GetPropertyValuesType.LoadFromFile.
static bool SDC.GetPropertyValuesType.Deserialize(string input, out GetPropertyValuesType obj)
References SDC.GetPropertyValuesType.Deserialize, SDC.null.
static new GetPropertyValuesType SDC.GetPropertyValuesType.Deserialize(string input)
References SDC.null, SDC.GetPropertyValuesType.Serializer.
static GetPropertyValuesType SDC.GetPropertyValuesType.Deserialize(Stream s)
References SDC.GetPropertyValuesType.Serializer.
static bool SDC.GetPropertyValuesType.LoadFromFile(string fileName, out GetPropertyValuesType obj, out Exception exception)
Deserializes xml markup from file into an GetPropertyValuesType object
fileName string xml file to load and deserialize obj Output GetPropertyValuesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.GetPropertyValuesType.LoadFromFile.
static bool SDC.GetPropertyValuesType.LoadFromFile(string fileName, out GetPropertyValuesType obj)
References SDC.GetPropertyValuesType.LoadFromFile, SDC.null.
static new GetPropertyValuesType SDC.GetPropertyValuesType.LoadFromFile(string fileName)
References SDC.GetPropertyValuesType.Deserialize, SDC.null.