SDC::time_Stype
bool SDC.time_Stype::_shouldSerializeval
Referenced by SDC.time_Stype.ShouldSerializeval.
System.Nullable<System.DateTime> SDC.time_Stype._val
Referenced by SDC.time_Stype.ShouldSerializeval.
dtQuantEnum SDC.time_Stype::_quantEnum
Referenced by SDC.time_Stype.time_Stype.
DateTime SDC.time_Stype._val
ObjectChangeTracker SDC.time_Stype.changeTrackerField
static XmlSerializer SDC.time_Stype::serializer
System DateTime SDC.time_Stype::val
bool SDC.time_Stype::valSpecified
dtQuantEnum SDC.time_Stype::quantEnum
static XmlSerializer SDC.time_Stype::Serializer
Referenced by SDC.time_Stype.Deserialize.
ObjectChangeTracker SDC.time_Stype.ChangeTracker
SDC.time_Stype.time_Stype()
SDC.time_Stype.time_Stype(BaseType parentNode)
virtual bool SDC.time_Stype.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.time_Stype.Serialize(System.Text.Encoding encoding)
Serializes current time_Stype object into an XML string
string XML value
virtual string SDC.time_Stype.Serialize()
Referenced by SDC.time_Stype.SaveToFile.
virtual bool SDC.time_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current time_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.time_Stype.SaveToFile.
virtual bool SDC.time_Stype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.time_Stype.SaveToFile(string fileName)
virtual void SDC.time_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.time_Stype.time_Stype()
time_Stype class constructor
References SDC.time_Stype._quantEnum.
virtual bool SDC.time_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.time_Stype._shouldSerializeval, SDC.time_Stype._val.
virtual string SDC.time_Stype.Serialize()
Serializes current time_Stype object into an XML string
string XML value
virtual bool SDC.time_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current time_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.time_Stype.SaveToFile.
virtual void SDC.time_Stype.SaveToFile(string fileName)
References SDC.null, SDC.time_Stype.Serialize.
virtual time_Stype SDC.time_Stype.Clone()
Create a clone of this time_Stype object
static bool SDC.time_Stype.Deserialize(string input, out time_Stype obj, out System.Exception exception)
Deserializes workflow markup into an time_Stype object
input string workflow markup to deserialize obj Output time_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.time_Stype.Deserialize, SDC.time_Stype.LoadFromFile.
static bool SDC.time_Stype.Deserialize(string input, out time_Stype obj)
References SDC.null.
static new time_Stype SDC.time_Stype.Deserialize(string input)
References SDC.null.
static time_Stype SDC.time_Stype.Deserialize(System.IO.Stream s)
static bool SDC.time_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out time_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an time_Stype object
fileName string xml file to load and deserialize obj Output time_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.time_Stype.LoadFromFile.
static bool SDC.time_Stype.LoadFromFile(string fileName, out time_Stype obj, out System.Exception exception)
static bool SDC.time_Stype.LoadFromFile(string fileName, out time_Stype obj)
References SDC.null.
static time_Stype SDC.time_Stype.LoadFromFile(string fileName)
static new time_Stype SDC.time_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.time_Stype.Deserialize(string input, out time_Stype obj, out Exception exception)
Deserializes workflow markup into an time_Stype object
input string workflow markup to deserialize obj Output time_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.time_Stype.Deserialize, SDC.null.
static bool SDC.time_Stype.Deserialize(string input, out time_Stype obj)
References SDC.time_Stype.Deserialize, SDC.null.
static new time_Stype SDC.time_Stype.Deserialize(string input)
References SDC.null, SDC.time_Stype.Serializer.
static time_Stype SDC.time_Stype.Deserialize(Stream s)
References SDC.time_Stype.Serializer.
static bool SDC.time_Stype.LoadFromFile(string fileName, out time_Stype obj, out Exception exception)
Deserializes xml markup from file into an time_Stype object
fileName string xml file to load and deserialize obj Output time_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.time_Stype.LoadFromFile, SDC.null.
static bool SDC.time_Stype.LoadFromFile(string fileName, out time_Stype obj)
References SDC.time_Stype.LoadFromFile, SDC.null.
static new time_Stype SDC.time_Stype.LoadFromFile(string fileName)
References SDC.time_Stype.Deserialize, SDC.null.