SDC::SectionItemType
ChildItemsType SDC.SectionItemType.ChildItemsNode
ChildItemsType SDC.SectionItemType.ChildItems_Item
ChildItemsType SDC.SectionItemType::Item
static XmlSerializer SDC.SectionItemType::Serializer
Referenced by SDC.SectionItemType.Deserialize.
ObjectChangeTracker SDC.SectionItemType.ChangeTracker
ChildItemsType SDC.SectionItemType::_item
Referenced by SDC.SectionItemType.ShouldSerializeItem.
ObjectChangeTracker SDC.SectionItemType.changeTrackerField
static XmlSerializer SDC.SectionItemType::serializer
SDC.SectionItemType.SectionItemType()
SDC.SectionItemType.SectionItemType(BaseType parentNode, bool fillData=true, string id=null)
SectionItemType SDC.SectionItemType.AddSection(Boolean fillData=true, string id=null)
QuestionItemType SDC.SectionItemType.AddQuestion(QuestionEnum qType, Boolean fillData=true, string id=null)
InjectFormType SDC.SectionItemType.AddInjectedForm(Boolean fillData=true, string id=null)
ButtonItemType SDC.SectionItemType.AddButtonAction(Boolean fillData=true, string id=null)
DisplayedType SDC.SectionItemType.AddDisplayedItem(Boolean fillData=true, string id=null)
SDC.SectionItemType.SectionItemType()
SectionItemType SDC.SectionItemType.AddSection()
QuestionItemType SDC.SectionItemType.AddQuestion(ItemType qType)
InjectFormType SDC.SectionItemType.AddInjectedForm()
ButtonItemType SDC.SectionItemType.AddButtonAction()
DisplayedType SDC.SectionItemType.AddDisplayedItem()
virtual bool SDC.SectionItemType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.null.
virtual string SDC.SectionItemType.Serialize(System.Text.Encoding encoding)
Serializes current SectionItemType object into an XML string
string XML value
virtual string SDC.SectionItemType.Serialize()
Referenced by SDC.SectionItemType.SaveToFile.
virtual bool SDC.SectionItemType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current SectionItemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.SectionItemType.SaveToFile.
virtual bool SDC.SectionItemType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.SectionItemType.SaveToFile(string fileName)
virtual void SDC.SectionItemType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.SectionItemType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.SectionItemType._item, SDC.null.
virtual string SDC.SectionItemType.Serialize()
Serializes current SectionItemType object into an XML string
string XML value
virtual bool SDC.SectionItemType.SaveToFile(string fileName, out Exception exception)
Serializes current SectionItemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.SectionItemType.SaveToFile.
virtual void SDC.SectionItemType.SaveToFile(string fileName)
References SDC.null, SDC.SectionItemType.Serialize.
virtual SectionItemType SDC.SectionItemType.Clone()
Create a clone of this SectionItemType object
static bool SDC.SectionItemType.Deserialize(string input, out SectionItemType obj, out System.Exception exception)
Deserializes workflow markup into an SectionItemType object
input string workflow markup to deserialize obj Output SectionItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.SectionItemType.Deserialize, SDC.SectionItemType.LoadFromFile.
static bool SDC.SectionItemType.Deserialize(string input, out SectionItemType obj)
References SDC.null.
static new SectionItemType SDC.SectionItemType.Deserialize(string input)
References SDC.null.
static SectionItemType SDC.SectionItemType.Deserialize(System.IO.Stream s)
static bool SDC.SectionItemType.LoadFromFile(string fileName, System.Text.Encoding encoding, out SectionItemType obj, out System.Exception exception)
Deserializes xml markup from file into an SectionItemType object
fileName string xml file to load and deserialize obj Output SectionItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.SectionItemType.LoadFromFile.
static bool SDC.SectionItemType.LoadFromFile(string fileName, out SectionItemType obj, out System.Exception exception)
static bool SDC.SectionItemType.LoadFromFile(string fileName, out SectionItemType obj)
References SDC.null.
static SectionItemType SDC.SectionItemType.LoadFromFile(string fileName)
static new SectionItemType SDC.SectionItemType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.SectionItemType.Deserialize(string input, out SectionItemType obj, out Exception exception)
Deserializes workflow markup into an SectionItemType object
input string workflow markup to deserialize obj Output SectionItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.SectionItemType.Deserialize, SDC.null.
static bool SDC.SectionItemType.Deserialize(string input, out SectionItemType obj)
References SDC.SectionItemType.Deserialize, SDC.null.
static new SectionItemType SDC.SectionItemType.Deserialize(string input)
References SDC.null, SDC.SectionItemType.Serializer.
static SectionItemType SDC.SectionItemType.Deserialize(Stream s)
References SDC.SectionItemType.Serializer.
static bool SDC.SectionItemType.LoadFromFile(string fileName, out SectionItemType obj, out Exception exception)
Deserializes xml markup from file into an SectionItemType object
fileName string xml file to load and deserialize obj Output SectionItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.SectionItemType.LoadFromFile, SDC.null.
static bool SDC.SectionItemType.LoadFromFile(string fileName, out SectionItemType obj)
References SDC.SectionItemType.LoadFromFile, SDC.null.
static new SectionItemType SDC.SectionItemType.LoadFromFile(string fileName)
References SDC.SectionItemType.Deserialize, SDC.null.