SDC::double_Stype
bool SDC.double_Stype::_shouldSerializeval
Referenced by SDC.double_Stype.ShouldSerializeval.
System Nullable< double > SDC.double_Stype::_val
Referenced by SDC.double_Stype.ShouldSerializeval.
string SDC.double_Stype::_mask
dtQuantEnum SDC.double_Stype::_quantEnum
Referenced by SDC.double_Stype.double_Stype.
ObjectChangeTracker SDC.double_Stype.changeTrackerField
static XmlSerializer SDC.double_Stype::serializer
double SDC.double_Stype::val
bool SDC.double_Stype::valSpecified
string SDC.double_Stype::mask
Referenced by SDC.double_Stype.ShouldSerializemask.
dtQuantEnum SDC.double_Stype::quantEnum
static XmlSerializer SDC.double_Stype::Serializer
Referenced by SDC.double_Stype.Deserialize.
ObjectChangeTracker SDC.double_Stype.ChangeTracker
SDC.double_Stype.double_Stype()
SDC.double_Stype.double_Stype(BaseType parentNode)
virtual bool SDC.double_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.double_Stype._shouldSerializeval, SDC.double_Stype._val.
virtual bool SDC.double_Stype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.double_Stype.mask.
virtual string SDC.double_Stype.Serialize(System.Text.Encoding encoding)
Serializes current double_Stype object into an XML string
string XML value
virtual string SDC.double_Stype.Serialize()
Referenced by SDC.double_Stype.SaveToFile.
virtual bool SDC.double_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current double_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.double_Stype.SaveToFile.
virtual bool SDC.double_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.double_Stype.SaveToFile.
virtual void SDC.double_Stype.SaveToFile(string fileName)
References SDC.double_Stype.SaveToFile.
virtual void SDC.double_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.double_Stype.Serialize.
SDC.double_Stype.double_Stype()
double_Stype class constructor
References SDC.double_Stype._quantEnum.
virtual bool SDC.double_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.double_Stype._shouldSerializeval, SDC.double_Stype._val.
virtual bool SDC.double_Stype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.double_Stype.mask.
virtual string SDC.double_Stype.Serialize()
Serializes current double_Stype object into an XML string
string XML value
virtual bool SDC.double_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current double_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.double_Stype.SaveToFile.
virtual void SDC.double_Stype.SaveToFile(string fileName)
References SDC.null, SDC.double_Stype.Serialize.
virtual double_Stype SDC.double_Stype.Clone()
Create a clone of this double_Stype object
static bool SDC.double_Stype.Deserialize(string input, out double_Stype obj, out System.Exception exception)
Deserializes workflow markup into an double_Stype object
input string workflow markup to deserialize obj Output double_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.double_Stype.Deserialize, SDC.double_Stype.LoadFromFile.
static bool SDC.double_Stype.Deserialize(string input, out double_Stype obj)
References SDC.double_Stype.Deserialize, SDC.null.
static new double_Stype SDC.double_Stype.Deserialize(string input)
References SDC.null.
static double_Stype SDC.double_Stype.Deserialize(System.IO.Stream s)
References SDC.double_Stype.Serializer.
static bool SDC.double_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out double_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an double_Stype object
fileName string xml file to load and deserialize obj Output double_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.double_Stype.LoadFromFile.
static bool SDC.double_Stype.LoadFromFile(string fileName, out double_Stype obj, out System.Exception exception)
References SDC.double_Stype.LoadFromFile.
static bool SDC.double_Stype.LoadFromFile(string fileName, out double_Stype obj)
References SDC.double_Stype.LoadFromFile, SDC.null.
static double_Stype SDC.double_Stype.LoadFromFile(string fileName)
References SDC.double_Stype.LoadFromFile.
static new double_Stype SDC.double_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.double_Stype.Deserialize, SDC.null.
static bool SDC.double_Stype.Deserialize(string input, out double_Stype obj, out Exception exception)
Deserializes workflow markup into an double_Stype object
input string workflow markup to deserialize obj Output double_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.double_Stype.Deserialize, SDC.null.
static bool SDC.double_Stype.Deserialize(string input, out double_Stype obj)
References SDC.double_Stype.Deserialize, SDC.null.
static new double_Stype SDC.double_Stype.Deserialize(string input)
References SDC.null, SDC.double_Stype.Serializer.
static double_Stype SDC.double_Stype.Deserialize(Stream s)
References SDC.double_Stype.Serializer.
static bool SDC.double_Stype.LoadFromFile(string fileName, out double_Stype obj, out Exception exception)
Deserializes xml markup from file into an double_Stype object
fileName string xml file to load and deserialize obj Output double_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.double_Stype.LoadFromFile, SDC.null.
static bool SDC.double_Stype.LoadFromFile(string fileName, out double_Stype obj)
References SDC.double_Stype.LoadFromFile, SDC.null.
static new double_Stype SDC.double_Stype.LoadFromFile(string fileName)
References SDC.double_Stype.Deserialize, SDC.null.