SDC::TargetItemXPathType
string SDC.TargetItemXPathType::_targetItemText
ObjectChangeTracker SDC.TargetItemXPathType.changeTrackerField
static XmlSerializer SDC.TargetItemXPathType::serializer
string SDC.TargetItemXPathType::targetItemText
Displayed text on the targetted item.
Referenced by SDC.TargetItemXPathType.ShouldSerializetargetItemText.
static XmlSerializer SDC.TargetItemXPathType::Serializer
Referenced by SDC.TargetItemXPathType.Deserialize.
ObjectChangeTracker SDC.TargetItemXPathType.ChangeTracker
SDC.TargetItemXPathType.TargetItemXPathType()
SDC.TargetItemXPathType.TargetItemXPathType(BaseType parentNode)
virtual bool SDC.TargetItemXPathType.ShouldSerializetargetItemText()
Test whether targetItemText should be serialized
virtual string SDC.TargetItemXPathType.Serialize(System.Text.Encoding encoding)
Serializes current TargetItemXPathType object into an XML string
string XML value
virtual string SDC.TargetItemXPathType.Serialize()
Referenced by SDC.TargetItemXPathType.SaveToFile.
virtual bool SDC.TargetItemXPathType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current TargetItemXPathType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.TargetItemXPathType.SaveToFile.
virtual bool SDC.TargetItemXPathType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.TargetItemXPathType.SaveToFile(string fileName)
virtual void SDC.TargetItemXPathType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.TargetItemXPathType.ShouldSerializetargetItemText()
Test whether targetItemText should be serialized
References SDC.TargetItemXPathType.targetItemText.
virtual string SDC.TargetItemXPathType.Serialize()
Serializes current TargetItemXPathType object into an XML string
string XML value
virtual bool SDC.TargetItemXPathType.SaveToFile(string fileName, out Exception exception)
Serializes current TargetItemXPathType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.TargetItemXPathType.SaveToFile.
virtual void SDC.TargetItemXPathType.SaveToFile(string fileName)
References SDC.null, SDC.TargetItemXPathType.Serialize.
virtual TargetItemXPathType SDC.TargetItemXPathType.Clone()
Create a clone of this TargetItemXPathType object
static bool SDC.TargetItemXPathType.Deserialize(string input, out TargetItemXPathType obj, out System.Exception exception)
Deserializes workflow markup into an TargetItemXPathType object
input string workflow markup to deserialize obj Output TargetItemXPathType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.TargetItemXPathType.Deserialize, SDC.TargetItemXPathType.LoadFromFile.
static bool SDC.TargetItemXPathType.Deserialize(string input, out TargetItemXPathType obj)
References SDC.null.
static new TargetItemXPathType SDC.TargetItemXPathType.Deserialize(string input)
References SDC.null.
static TargetItemXPathType SDC.TargetItemXPathType.Deserialize(System.IO.Stream s)
static bool SDC.TargetItemXPathType.LoadFromFile(string fileName, System.Text.Encoding encoding, out TargetItemXPathType obj, out System.Exception exception)
Deserializes xml markup from file into an TargetItemXPathType object
fileName string xml file to load and deserialize obj Output TargetItemXPathType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.TargetItemXPathType.LoadFromFile.
static bool SDC.TargetItemXPathType.LoadFromFile(string fileName, out TargetItemXPathType obj, out System.Exception exception)
static bool SDC.TargetItemXPathType.LoadFromFile(string fileName, out TargetItemXPathType obj)
References SDC.null.
static TargetItemXPathType SDC.TargetItemXPathType.LoadFromFile(string fileName)
static new TargetItemXPathType SDC.TargetItemXPathType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.TargetItemXPathType.Deserialize(string input, out TargetItemXPathType obj, out Exception exception)
Deserializes workflow markup into an TargetItemXPathType object
input string workflow markup to deserialize obj Output TargetItemXPathType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.TargetItemXPathType.Deserialize, SDC.null.
static bool SDC.TargetItemXPathType.Deserialize(string input, out TargetItemXPathType obj)
References SDC.TargetItemXPathType.Deserialize, SDC.null.
static new TargetItemXPathType SDC.TargetItemXPathType.Deserialize(string input)
References SDC.null, SDC.TargetItemXPathType.Serializer.
static TargetItemXPathType SDC.TargetItemXPathType.Deserialize(Stream s)
References SDC.TargetItemXPathType.Serializer.
static bool SDC.TargetItemXPathType.LoadFromFile(string fileName, out TargetItemXPathType obj, out Exception exception)
Deserializes xml markup from file into an TargetItemXPathType object
fileName string xml file to load and deserialize obj Output TargetItemXPathType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.TargetItemXPathType.LoadFromFile, SDC.null.
static bool SDC.TargetItemXPathType.LoadFromFile(string fileName, out TargetItemXPathType obj)
References SDC.TargetItemXPathType.LoadFromFile, SDC.null.
static new TargetItemXPathType SDC.TargetItemXPathType.LoadFromFile(string fileName)
References SDC.TargetItemXPathType.Deserialize, SDC.null.