SDC::AcceptabilityType
static XmlSerializer SDC.AcceptabilityType::serializer
static XmlSerializer SDC.AcceptabilityType::Serializer
Referenced by SDC.AcceptabilityType.Deserialize.
ObjectChangeTracker SDC.AcceptabilityType.ChangeTracker
ObjectChangeTracker SDC.AcceptabilityType.changeTrackerField
SDC.AcceptabilityType.AcceptabilityType()
SDC.AcceptabilityType.AcceptabilityType(BaseType parentNode)
virtual string SDC.AcceptabilityType.Serialize(System.Text.Encoding encoding)
Serializes current AcceptabilityType object into an XML string
string XML value
virtual string SDC.AcceptabilityType.Serialize()
Referenced by SDC.AcceptabilityType.SaveToFile.
virtual bool SDC.AcceptabilityType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current AcceptabilityType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.AcceptabilityType.SaveToFile.
virtual bool SDC.AcceptabilityType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.AcceptabilityType.SaveToFile(string fileName)
virtual void SDC.AcceptabilityType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.AcceptabilityType.Serialize()
Serializes current AcceptabilityType object into an XML string
string XML value
virtual bool SDC.AcceptabilityType.SaveToFile(string fileName, out Exception exception)
Serializes current AcceptabilityType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.AcceptabilityType.SaveToFile.
virtual void SDC.AcceptabilityType.SaveToFile(string fileName)
References SDC.null, SDC.AcceptabilityType.Serialize.
virtual AcceptabilityType SDC.AcceptabilityType.Clone()
Create a clone of this AcceptabilityType object
static bool SDC.AcceptabilityType.Deserialize(string input, out AcceptabilityType obj, out System.Exception exception)
Deserializes workflow markup into an AcceptabilityType object
input string workflow markup to deserialize obj Output AcceptabilityType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AcceptabilityType.Deserialize, SDC.AcceptabilityType.LoadFromFile.
static bool SDC.AcceptabilityType.Deserialize(string input, out AcceptabilityType obj)
References SDC.null.
static new AcceptabilityType SDC.AcceptabilityType.Deserialize(string input)
References SDC.null.
static AcceptabilityType SDC.AcceptabilityType.Deserialize(System.IO.Stream s)
static bool SDC.AcceptabilityType.LoadFromFile(string fileName, System.Text.Encoding encoding, out AcceptabilityType obj, out System.Exception exception)
Deserializes xml markup from file into an AcceptabilityType object
fileName string xml file to load and deserialize obj Output AcceptabilityType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AcceptabilityType.LoadFromFile.
static bool SDC.AcceptabilityType.LoadFromFile(string fileName, out AcceptabilityType obj, out System.Exception exception)
static bool SDC.AcceptabilityType.LoadFromFile(string fileName, out AcceptabilityType obj)
References SDC.null.
static AcceptabilityType SDC.AcceptabilityType.LoadFromFile(string fileName)
static new AcceptabilityType SDC.AcceptabilityType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.AcceptabilityType.Deserialize(string input, out AcceptabilityType obj, out Exception exception)
Deserializes workflow markup into an AcceptabilityType object
input string workflow markup to deserialize obj Output AcceptabilityType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.AcceptabilityType.Deserialize, SDC.null.
static bool SDC.AcceptabilityType.Deserialize(string input, out AcceptabilityType obj)
References SDC.AcceptabilityType.Deserialize, SDC.null.
static new AcceptabilityType SDC.AcceptabilityType.Deserialize(string input)
References SDC.null, SDC.AcceptabilityType.Serializer.
static AcceptabilityType SDC.AcceptabilityType.Deserialize(Stream s)
References SDC.AcceptabilityType.Serializer.
static bool SDC.AcceptabilityType.LoadFromFile(string fileName, out AcceptabilityType obj, out Exception exception)
Deserializes xml markup from file into an AcceptabilityType object
fileName string xml file to load and deserialize obj Output AcceptabilityType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.AcceptabilityType.LoadFromFile, SDC.null.
static bool SDC.AcceptabilityType.LoadFromFile(string fileName, out AcceptabilityType obj)
References SDC.AcceptabilityType.LoadFromFile, SDC.null.
static new AcceptabilityType SDC.AcceptabilityType.LoadFromFile(string fileName)
References SDC.AcceptabilityType.Deserialize, SDC.null.