SDC::dateTime_DEtype
bool SDC.dateTime_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.dateTime_DEtype.ShouldSerializemaxExclusive.
bool SDC.dateTime_DEtype::_shouldSerializeminExclusive
Referenced by SDC.dateTime_DEtype.ShouldSerializeminExclusive.
bool SDC.dateTime_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.dateTime_DEtype.ShouldSerializemaxInclusive.
bool SDC.dateTime_DEtype::_shouldSerializeminInclusive
Referenced by SDC.dateTime_DEtype.ShouldSerializeminInclusive.
System.Nullable<System.DateTime> SDC.dateTime_DEtype._minInclusive
Referenced by SDC.dateTime_DEtype.ShouldSerializeminInclusive.
System.Nullable<System.DateTime> SDC.dateTime_DEtype._maxInclusive
Referenced by SDC.dateTime_DEtype.ShouldSerializemaxInclusive.
System.Nullable<System.DateTime> SDC.dateTime_DEtype._minExclusive
Referenced by SDC.dateTime_DEtype.ShouldSerializeminExclusive.
System.Nullable<System.DateTime> SDC.dateTime_DEtype._maxExclusive
Referenced by SDC.dateTime_DEtype.ShouldSerializemaxExclusive.
string SDC.dateTime_DEtype::_pattern
string SDC.dateTime_DEtype::_mask
DateTime SDC.dateTime_DEtype._minInclusive
DateTime SDC.dateTime_DEtype._maxInclusive
DateTime SDC.dateTime_DEtype._minExclusive
DateTime SDC.dateTime_DEtype._maxExclusive
ObjectChangeTracker SDC.dateTime_DEtype.changeTrackerField
static XmlSerializer SDC.dateTime_DEtype::serializer
System DateTime SDC.dateTime_DEtype::minInclusive
bool SDC.dateTime_DEtype::minInclusiveSpecified
System DateTime SDC.dateTime_DEtype::maxInclusive
bool SDC.dateTime_DEtype::maxInclusiveSpecified
System DateTime SDC.dateTime_DEtype::minExclusive
bool SDC.dateTime_DEtype::minExclusiveSpecified
System DateTime SDC.dateTime_DEtype::maxExclusive
bool SDC.dateTime_DEtype::maxExclusiveSpecified
string SDC.dateTime_DEtype::pattern
Referenced by SDC.dateTime_DEtype.ShouldSerializepattern.
string SDC.dateTime_DEtype::mask
Referenced by SDC.dateTime_DEtype.ShouldSerializemask.
static XmlSerializer SDC.dateTime_DEtype::Serializer
Referenced by SDC.dateTime_DEtype.Deserialize.
ObjectChangeTracker SDC.dateTime_DEtype.ChangeTracker
SDC.dateTime_DEtype.dateTime_DEtype()
SDC.dateTime_DEtype.dateTime_DEtype(BaseType parentNode)
virtual bool SDC.dateTime_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.dateTime_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.dateTime_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.dateTime_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.dateTime_DEtype.ShouldSerializepattern()
Test whether pattern should be serialized
virtual bool SDC.dateTime_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.dateTime_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current dateTime_DEtype object into an XML string
string XML value
virtual string SDC.dateTime_DEtype.Serialize()
Referenced by SDC.dateTime_DEtype.SaveToFile.
virtual bool SDC.dateTime_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current dateTime_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.dateTime_DEtype.SaveToFile.
virtual bool SDC.dateTime_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.dateTime_DEtype.SaveToFile(string fileName)
virtual void SDC.dateTime_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.dateTime_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.dateTime_DEtype._minInclusive, SDC.dateTime_DEtype._shouldSerializeminInclusive.
virtual bool SDC.dateTime_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.dateTime_DEtype._maxInclusive, SDC.dateTime_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.dateTime_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.dateTime_DEtype._minExclusive, SDC.dateTime_DEtype._shouldSerializeminExclusive.
virtual bool SDC.dateTime_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.dateTime_DEtype._maxExclusive, SDC.dateTime_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.dateTime_DEtype.ShouldSerializepattern()
Test whether pattern should be serialized
References SDC.dateTime_DEtype.pattern.
virtual bool SDC.dateTime_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.dateTime_DEtype.mask.
virtual string SDC.dateTime_DEtype.Serialize()
Serializes current dateTime_DEtype object into an XML string
string XML value
virtual bool SDC.dateTime_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current dateTime_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.dateTime_DEtype.SaveToFile.
virtual void SDC.dateTime_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.dateTime_DEtype.Serialize.
virtual dateTime_DEtype SDC.dateTime_DEtype.Clone()
Create a clone of this dateTime_DEtype object
static bool SDC.dateTime_DEtype.Deserialize(string input, out dateTime_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an dateTime_DEtype object
input string workflow markup to deserialize obj Output dateTime_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dateTime_DEtype.Deserialize, SDC.dateTime_DEtype.LoadFromFile.
static bool SDC.dateTime_DEtype.Deserialize(string input, out dateTime_DEtype obj)
References SDC.null.
static new dateTime_DEtype SDC.dateTime_DEtype.Deserialize(string input)
References SDC.null.
static dateTime_DEtype SDC.dateTime_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.dateTime_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out dateTime_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an dateTime_DEtype object
fileName string xml file to load and deserialize obj Output dateTime_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dateTime_DEtype.LoadFromFile.
static bool SDC.dateTime_DEtype.LoadFromFile(string fileName, out dateTime_DEtype obj, out System.Exception exception)
static bool SDC.dateTime_DEtype.LoadFromFile(string fileName, out dateTime_DEtype obj)
References SDC.null.
static dateTime_DEtype SDC.dateTime_DEtype.LoadFromFile(string fileName)
static new dateTime_DEtype SDC.dateTime_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.dateTime_DEtype.Deserialize(string input, out dateTime_DEtype obj, out Exception exception)
Deserializes workflow markup into an dateTime_DEtype object
input string workflow markup to deserialize obj Output dateTime_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dateTime_DEtype.Deserialize, SDC.null.
static bool SDC.dateTime_DEtype.Deserialize(string input, out dateTime_DEtype obj)
References SDC.dateTime_DEtype.Deserialize, SDC.null.
static new dateTime_DEtype SDC.dateTime_DEtype.Deserialize(string input)
References SDC.null, SDC.dateTime_DEtype.Serializer.
static dateTime_DEtype SDC.dateTime_DEtype.Deserialize(Stream s)
References SDC.dateTime_DEtype.Serializer.
static bool SDC.dateTime_DEtype.LoadFromFile(string fileName, out dateTime_DEtype obj, out Exception exception)
Deserializes xml markup from file into an dateTime_DEtype object
fileName string xml file to load and deserialize obj Output dateTime_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dateTime_DEtype.LoadFromFile, SDC.null.
static bool SDC.dateTime_DEtype.LoadFromFile(string fileName, out dateTime_DEtype obj)
References SDC.dateTime_DEtype.LoadFromFile, SDC.null.
static new dateTime_DEtype SDC.dateTime_DEtype.LoadFromFile(string fileName)
References SDC.dateTime_DEtype.Deserialize, SDC.null.