SDC::UnitsType
string SDC.UnitsType::_unitSystem
Referenced by SDC.UnitsType.UnitsType.
ObjectChangeTracker SDC.UnitsType.changeTrackerField
static XmlSerializer SDC.UnitsType::serializer
string SDC.UnitsType::unitSystem
Referenced by SDC.UnitsType.ShouldSerializeunitSystem.
static XmlSerializer SDC.UnitsType::Serializer
Referenced by SDC.UnitsType.Deserialize.
ObjectChangeTracker SDC.UnitsType.ChangeTracker
SDC.UnitsType.UnitsType()
SDC.UnitsType.UnitsType(BaseType parentNode, bool fillData=true)
UnitsType SDC.UnitsType.FillUnitsType()
+Replaced in original class: protected UnitsType() { }
void SDC.UnitsType.Fill_UnitsType()
virtual bool SDC.UnitsType.ShouldSerializeunitSystem()
Test whether unitSystem should be serialized
virtual string SDC.UnitsType.Serialize(System.Text.Encoding encoding)
Serializes current UnitsType object into an XML string
string XML value
virtual string SDC.UnitsType.Serialize()
Referenced by SDC.UnitsType.SaveToFile.
virtual bool SDC.UnitsType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current UnitsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.UnitsType.SaveToFile.
virtual bool SDC.UnitsType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.UnitsType.SaveToFile(string fileName)
virtual void SDC.UnitsType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.UnitsType.UnitsType()
UnitsType class constructor
References SDC.UnitsType._unitSystem.
virtual bool SDC.UnitsType.ShouldSerializeunitSystem()
Test whether unitSystem should be serialized
References SDC.UnitsType.unitSystem.
virtual string SDC.UnitsType.Serialize()
Serializes current UnitsType object into an XML string
string XML value
virtual bool SDC.UnitsType.SaveToFile(string fileName, out Exception exception)
Serializes current UnitsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.UnitsType.SaveToFile.
virtual void SDC.UnitsType.SaveToFile(string fileName)
References SDC.null, SDC.UnitsType.Serialize.
virtual UnitsType SDC.UnitsType.Clone()
Create a clone of this UnitsType object
static bool SDC.UnitsType.Deserialize(string input, out UnitsType obj, out System.Exception exception)
Deserializes workflow markup into an UnitsType object
input string workflow markup to deserialize obj Output UnitsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.UnitsType.Deserialize, SDC.UnitsType.LoadFromFile.
static bool SDC.UnitsType.Deserialize(string input, out UnitsType obj)
References SDC.null.
static new UnitsType SDC.UnitsType.Deserialize(string input)
References SDC.null.
static UnitsType SDC.UnitsType.Deserialize(System.IO.Stream s)
static bool SDC.UnitsType.LoadFromFile(string fileName, System.Text.Encoding encoding, out UnitsType obj, out System.Exception exception)
Deserializes xml markup from file into an UnitsType object
fileName string xml file to load and deserialize obj Output UnitsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.UnitsType.LoadFromFile.
static bool SDC.UnitsType.LoadFromFile(string fileName, out UnitsType obj, out System.Exception exception)
static bool SDC.UnitsType.LoadFromFile(string fileName, out UnitsType obj)
References SDC.null.
static UnitsType SDC.UnitsType.LoadFromFile(string fileName)
static new UnitsType SDC.UnitsType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.UnitsType.Deserialize(string input, out UnitsType obj, out Exception exception)
Deserializes workflow markup into an UnitsType object
input string workflow markup to deserialize obj Output UnitsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.UnitsType.Deserialize, SDC.null.
static bool SDC.UnitsType.Deserialize(string input, out UnitsType obj)
References SDC.UnitsType.Deserialize, SDC.null.
static new UnitsType SDC.UnitsType.Deserialize(string input)
References SDC.null, SDC.UnitsType.Serializer.
static UnitsType SDC.UnitsType.Deserialize(Stream s)
References SDC.UnitsType.Serializer.
static bool SDC.UnitsType.LoadFromFile(string fileName, out UnitsType obj, out Exception exception)
Deserializes xml markup from file into an UnitsType object
fileName string xml file to load and deserialize obj Output UnitsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.UnitsType.LoadFromFile, SDC.null.
static bool SDC.UnitsType.LoadFromFile(string fileName, out UnitsType obj)
References SDC.UnitsType.LoadFromFile, SDC.null.
static new UnitsType SDC.UnitsType.LoadFromFile(string fileName)
References SDC.UnitsType.Deserialize, SDC.null.