SDC::unsignedInt_DEtype
bool SDC.unsignedInt_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.unsignedInt_DEtype.ShouldSerializemaxExclusive.
bool SDC.unsignedInt_DEtype::_shouldSerializeminExclusive
Referenced by SDC.unsignedInt_DEtype.ShouldSerializeminExclusive.
bool SDC.unsignedInt_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.unsignedInt_DEtype.ShouldSerializemaxInclusive.
bool SDC.unsignedInt_DEtype::_shouldSerializeminInclusive
Referenced by SDC.unsignedInt_DEtype.ShouldSerializeminInclusive.
System Nullable< uint > SDC.unsignedInt_DEtype::_minInclusive
Referenced by SDC.unsignedInt_DEtype.ShouldSerializeminInclusive.
System Nullable< uint > SDC.unsignedInt_DEtype::_maxInclusive
Referenced by SDC.unsignedInt_DEtype.ShouldSerializemaxInclusive.
System Nullable< uint > SDC.unsignedInt_DEtype::_minExclusive
Referenced by SDC.unsignedInt_DEtype.ShouldSerializeminExclusive.
System Nullable< uint > SDC.unsignedInt_DEtype::_maxExclusive
Referenced by SDC.unsignedInt_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.unsignedInt_DEtype::_totalDigits
string SDC.unsignedInt_DEtype::_mask
ObjectChangeTracker SDC.unsignedInt_DEtype.changeTrackerField
static XmlSerializer SDC.unsignedInt_DEtype::serializer
uint SDC.unsignedInt_DEtype::minInclusive
bool SDC.unsignedInt_DEtype::minInclusiveSpecified
uint SDC.unsignedInt_DEtype::maxInclusive
bool SDC.unsignedInt_DEtype::maxInclusiveSpecified
uint SDC.unsignedInt_DEtype::minExclusive
bool SDC.unsignedInt_DEtype::minExclusiveSpecified
uint SDC.unsignedInt_DEtype::maxExclusive
bool SDC.unsignedInt_DEtype::maxExclusiveSpecified
byte SDC.unsignedInt_DEtype::totalDigits
bool SDC.unsignedInt_DEtype::totalDigitsSpecified
string SDC.unsignedInt_DEtype::mask
Referenced by SDC.unsignedInt_DEtype.ShouldSerializemask.
static XmlSerializer SDC.unsignedInt_DEtype::Serializer
Referenced by SDC.unsignedInt_DEtype.Deserialize.
ObjectChangeTracker SDC.unsignedInt_DEtype.ChangeTracker
SDC.unsignedInt_DEtype.unsignedInt_DEtype()
SDC.unsignedInt_DEtype.unsignedInt_DEtype(BaseType parentNode)
virtual bool SDC.unsignedInt_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.unsignedInt_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.unsignedInt_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.unsignedInt_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.unsignedInt_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.unsignedInt_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current unsignedInt_DEtype object into an XML string
string XML value
virtual string SDC.unsignedInt_DEtype.Serialize()
Referenced by SDC.unsignedInt_DEtype.SaveToFile.
virtual bool SDC.unsignedInt_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current unsignedInt_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.unsignedInt_DEtype.SaveToFile.
virtual bool SDC.unsignedInt_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.unsignedInt_DEtype.SaveToFile(string fileName)
virtual void SDC.unsignedInt_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.unsignedInt_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.unsignedInt_DEtype._minInclusive, SDC.unsignedInt_DEtype._shouldSerializeminInclusive.
virtual bool SDC.unsignedInt_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.unsignedInt_DEtype._maxInclusive, SDC.unsignedInt_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.unsignedInt_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.unsignedInt_DEtype._minExclusive, SDC.unsignedInt_DEtype._shouldSerializeminExclusive.
virtual bool SDC.unsignedInt_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.unsignedInt_DEtype._maxExclusive, SDC.unsignedInt_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.unsignedInt_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.unsignedInt_DEtype.mask.
virtual string SDC.unsignedInt_DEtype.Serialize()
Serializes current unsignedInt_DEtype object into an XML string
string XML value
virtual bool SDC.unsignedInt_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current unsignedInt_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.unsignedInt_DEtype.SaveToFile.
virtual void SDC.unsignedInt_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.unsignedInt_DEtype.Serialize.
virtual unsignedInt_DEtype SDC.unsignedInt_DEtype.Clone()
Create a clone of this unsignedInt_DEtype object
static bool SDC.unsignedInt_DEtype.Deserialize(string input, out unsignedInt_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an unsignedInt_DEtype object
input string workflow markup to deserialize obj Output unsignedInt_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedInt_DEtype.Deserialize, SDC.unsignedInt_DEtype.LoadFromFile.
static bool SDC.unsignedInt_DEtype.Deserialize(string input, out unsignedInt_DEtype obj)
References SDC.null.
static new unsignedInt_DEtype SDC.unsignedInt_DEtype.Deserialize(string input)
References SDC.null.
static unsignedInt_DEtype SDC.unsignedInt_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.unsignedInt_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out unsignedInt_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an unsignedInt_DEtype object
fileName string xml file to load and deserialize obj Output unsignedInt_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedInt_DEtype.LoadFromFile.
static bool SDC.unsignedInt_DEtype.LoadFromFile(string fileName, out unsignedInt_DEtype obj, out System.Exception exception)
static bool SDC.unsignedInt_DEtype.LoadFromFile(string fileName, out unsignedInt_DEtype obj)
References SDC.null.
static unsignedInt_DEtype SDC.unsignedInt_DEtype.LoadFromFile(string fileName)
static new unsignedInt_DEtype SDC.unsignedInt_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.unsignedInt_DEtype.Deserialize(string input, out unsignedInt_DEtype obj, out Exception exception)
Deserializes workflow markup into an unsignedInt_DEtype object
input string workflow markup to deserialize obj Output unsignedInt_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedInt_DEtype.Deserialize, SDC.null.
static bool SDC.unsignedInt_DEtype.Deserialize(string input, out unsignedInt_DEtype obj)
References SDC.unsignedInt_DEtype.Deserialize, SDC.null.
static new unsignedInt_DEtype SDC.unsignedInt_DEtype.Deserialize(string input)
References SDC.null, SDC.unsignedInt_DEtype.Serializer.
static unsignedInt_DEtype SDC.unsignedInt_DEtype.Deserialize(Stream s)
References SDC.unsignedInt_DEtype.Serializer.
static bool SDC.unsignedInt_DEtype.LoadFromFile(string fileName, out unsignedInt_DEtype obj, out Exception exception)
Deserializes xml markup from file into an unsignedInt_DEtype object
fileName string xml file to load and deserialize obj Output unsignedInt_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedInt_DEtype.LoadFromFile, SDC.null.
static bool SDC.unsignedInt_DEtype.LoadFromFile(string fileName, out unsignedInt_DEtype obj)
References SDC.unsignedInt_DEtype.LoadFromFile, SDC.null.
static new unsignedInt_DEtype SDC.unsignedInt_DEtype.LoadFromFile(string fileName)
References SDC.unsignedInt_DEtype.Deserialize, SDC.null.