SDC::LanguageType
string_Stype SDC.LanguageType::_language
Referenced by SDC.LanguageType.ShouldSerializeLanguage.
LanguageCodeISO6393_Type SDC.LanguageType::_languageCodeISO6393
Referenced by SDC.LanguageType.ShouldSerializeLanguageCodeISO6393.
ObjectChangeTracker SDC.LanguageType.changeTrackerField
static XmlSerializer SDC.LanguageType::serializer
string_Stype SDC.LanguageType::Language
The language used for text in SDC templates.
LanguageCodeISO6393_Type SDC.LanguageType::LanguageCodeISO6393
static XmlSerializer SDC.LanguageType::Serializer
Referenced by SDC.LanguageType.Deserialize.
ObjectChangeTracker SDC.LanguageType.ChangeTracker
SDC.LanguageType.LanguageType()
SDC.LanguageType.LanguageType(BaseType parentNode)
virtual bool SDC.LanguageType.ShouldSerializeLanguage()
Test whether Language should be serialized
References SDC.null.
virtual bool SDC.LanguageType.ShouldSerializeLanguageCodeISO6393()
Test whether LanguageCodeISO6393 should be serialized
References SDC.null.
virtual string SDC.LanguageType.Serialize(System.Text.Encoding encoding)
Serializes current LanguageType object into an XML string
string XML value
virtual string SDC.LanguageType.Serialize()
Referenced by SDC.LanguageType.SaveToFile.
virtual bool SDC.LanguageType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current LanguageType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.LanguageType.SaveToFile.
virtual bool SDC.LanguageType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.LanguageType.SaveToFile(string fileName)
virtual void SDC.LanguageType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.LanguageType.ShouldSerializeLanguage()
Test whether Language should be serialized
References SDC.LanguageType._language, SDC.null.
virtual bool SDC.LanguageType.ShouldSerializeLanguageCodeISO6393()
Test whether LanguageCodeISO6393 should be serialized
References SDC.LanguageType._languageCodeISO6393, SDC.null.
virtual string SDC.LanguageType.Serialize()
Serializes current LanguageType object into an XML string
string XML value
virtual bool SDC.LanguageType.SaveToFile(string fileName, out Exception exception)
Serializes current LanguageType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.LanguageType.SaveToFile.
virtual void SDC.LanguageType.SaveToFile(string fileName)
References SDC.null, SDC.LanguageType.Serialize.
virtual LanguageType SDC.LanguageType.Clone()
Create a clone of this LanguageType object
static bool SDC.LanguageType.Deserialize(string input, out LanguageType obj, out System.Exception exception)
Deserializes workflow markup into an LanguageType object
input string workflow markup to deserialize obj Output LanguageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.LanguageType.Deserialize, SDC.LanguageType.LoadFromFile.
static bool SDC.LanguageType.Deserialize(string input, out LanguageType obj)
References SDC.null.
static new LanguageType SDC.LanguageType.Deserialize(string input)
References SDC.null.
static LanguageType SDC.LanguageType.Deserialize(System.IO.Stream s)
static bool SDC.LanguageType.LoadFromFile(string fileName, System.Text.Encoding encoding, out LanguageType obj, out System.Exception exception)
Deserializes xml markup from file into an LanguageType object
fileName string xml file to load and deserialize obj Output LanguageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.LanguageType.LoadFromFile.
static bool SDC.LanguageType.LoadFromFile(string fileName, out LanguageType obj, out System.Exception exception)
static bool SDC.LanguageType.LoadFromFile(string fileName, out LanguageType obj)
References SDC.null.
static LanguageType SDC.LanguageType.LoadFromFile(string fileName)
static new LanguageType SDC.LanguageType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.LanguageType.Deserialize(string input, out LanguageType obj, out Exception exception)
Deserializes workflow markup into an LanguageType object
input string workflow markup to deserialize obj Output LanguageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.LanguageType.Deserialize, SDC.null.
static bool SDC.LanguageType.Deserialize(string input, out LanguageType obj)
References SDC.LanguageType.Deserialize, SDC.null.
static new LanguageType SDC.LanguageType.Deserialize(string input)
References SDC.null, SDC.LanguageType.Serializer.
static LanguageType SDC.LanguageType.Deserialize(Stream s)
References SDC.LanguageType.Serializer.
static bool SDC.LanguageType.LoadFromFile(string fileName, out LanguageType obj, out Exception exception)
Deserializes xml markup from file into an LanguageType object
fileName string xml file to load and deserialize obj Output LanguageType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.LanguageType.LoadFromFile, SDC.null.
static bool SDC.LanguageType.LoadFromFile(string fileName, out LanguageType obj)
References SDC.LanguageType.LoadFromFile, SDC.null.
static new LanguageType SDC.LanguageType.LoadFromFile(string fileName)
References SDC.LanguageType.Deserialize, SDC.null.