SDC::ThenType
ExtensionBaseType [] SDC.ThenType.ThenItems_List
Replaces Items List<BaseType>: "Action", typeof(ExtensionType), "CallIfThen", typeof(ItemNameType), "IfThen", typeof(IfThenType), "Inject", typeof(ActInjectType), "RunCommand", typeof(ExpressionType), "Save", typeof(ActSaveResponsesType), "SetProperty", typeof(SetPropertyType), "SetValue", typeof(ActSetValueType), "ShowForm", typeof(ActShowFormType), "ShowMessage", typeof(ActShowMessageType), "ShowReport", typeof(ActShowReportType) "ShowURL", typeof(WebServiceType), "_SendMessage", typeof(ActSendMessageType), "_SendReport", typeof(ActSendReportType), "_ValidateForm", typeof(ActValidateFormType),
List<SDC.BaseType> SDC.ThenType.ThenItems_List
Replaces Items List<BaseType>: "Action", typeof(ExtensionType), "CallIfThen", typeof(ItemNameType), "IfThen", typeof(IfThenType), "Inject", typeof(ActInjectType), "RunCommand", typeof(ExpressionType), "Save", typeof(ActSaveResponsesType), "SetProperty", typeof(SetPropertyType), "SetValue", typeof(ActSetValueType), "ShowForm", typeof(ActShowFormType), "ShowMessage", typeof(ActShowMessageType), "ShowReport", typeof(ActShowReportType) "ShowURL", typeof(WebServiceType), "_SendMessage", typeof(ActSendMessageType), "_SendReport", typeof(ActSendReportType), "_ValidateForm", typeof(ActValidateFormType),
virtual ExtensionBaseType [] SDC.ThenType.Items
Referenced by SDC.SDCTreeBuilderEcc.AddActSendMessage, SDC.SDCTreeBuilder.AddActSendMessage, SDC.SDCTreeBuilderEcc.AddFillActSendMessage.
virtual ItemsChoiceType2 [] SDC.ThenType.ItemsElementName
static XmlSerializer SDC.ThenType::Serializer
Referenced by SDC.ThenType.Deserialize.
virtual BindingList<BaseType> SDC.ThenType.Items
ObjectChangeTracker SDC.ThenType.ChangeTracker
ExtensionBaseType [] SDC.ThenType._items
ItemsChoiceType2 [] SDC.ThenType._itemsElementName
BindingList<BaseType> SDC.ThenType._items
ObjectChangeTracker SDC.ThenType.changeTrackerField
static XmlSerializer SDC.ThenType::serializer
SDC.ThenType.ThenType()
SDC.ThenType.ThenType(BaseType parentNode, bool fillData=true)
SDC.ThenType.ThenType()
virtual string SDC.ThenType.Serialize(System.Text.Encoding encoding)
Serializes current ThenType object into an XML string
string XML value
virtual string SDC.ThenType.Serialize()
Referenced by SDC.ThenType.SaveToFile.
virtual bool SDC.ThenType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ThenType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ThenType.SaveToFile.
virtual bool SDC.ThenType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ThenType.SaveToFile(string fileName)
virtual void SDC.ThenType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ThenType.Serialize()
Serializes current ThenType object into an XML string
string XML value
virtual bool SDC.ThenType.SaveToFile(string fileName, out Exception exception)
Serializes current ThenType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ThenType.SaveToFile.
virtual void SDC.ThenType.SaveToFile(string fileName)
References SDC.null, SDC.ThenType.Serialize.
virtual ThenType SDC.ThenType.Clone()
Create a clone of this ThenType object
static bool SDC.ThenType.Deserialize(string input, out ThenType obj, out System.Exception exception)
Deserializes workflow markup into an ThenType object
input string workflow markup to deserialize obj Output ThenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ThenType.Deserialize, SDC.ThenType.LoadFromFile.
static bool SDC.ThenType.Deserialize(string input, out ThenType obj)
References SDC.null.
static new ThenType SDC.ThenType.Deserialize(string input)
References SDC.null.
static ThenType SDC.ThenType.Deserialize(System.IO.Stream s)
static bool SDC.ThenType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ThenType obj, out System.Exception exception)
Deserializes xml markup from file into an ThenType object
fileName string xml file to load and deserialize obj Output ThenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ThenType.LoadFromFile.
static bool SDC.ThenType.LoadFromFile(string fileName, out ThenType obj, out System.Exception exception)
static bool SDC.ThenType.LoadFromFile(string fileName, out ThenType obj)
References SDC.null.
static ThenType SDC.ThenType.LoadFromFile(string fileName)
static new ThenType SDC.ThenType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ThenType.Deserialize(string input, out ThenType obj, out Exception exception)
Deserializes workflow markup into an ThenType object
input string workflow markup to deserialize obj Output ThenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ThenType.Deserialize, SDC.null.
static bool SDC.ThenType.Deserialize(string input, out ThenType obj)
References SDC.ThenType.Deserialize, SDC.null.
static new ThenType SDC.ThenType.Deserialize(string input)
References SDC.null, SDC.ThenType.Serializer.
static ThenType SDC.ThenType.Deserialize(Stream s)
References SDC.ThenType.Serializer.
static bool SDC.ThenType.LoadFromFile(string fileName, out ThenType obj, out Exception exception)
Deserializes xml markup from file into an ThenType object
fileName string xml file to load and deserialize obj Output ThenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ThenType.LoadFromFile, SDC.null.
static bool SDC.ThenType.LoadFromFile(string fileName, out ThenType obj)
References SDC.ThenType.LoadFromFile, SDC.null.
static new ThenType SDC.ThenType.LoadFromFile(string fileName)
References SDC.ThenType.Deserialize, SDC.null.