SDC::HTML_DEtype
bool SDC.HTML_DEtype::_shouldSerializemaxLength
Referenced by SDC.HTML_DEtype.ShouldSerializemaxLength.
bool SDC.HTML_DEtype::_shouldSerializeminLength
Referenced by SDC.HTML_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.HTML_DEtype::_minLength
Referenced by SDC.HTML_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.HTML_DEtype::_maxLength
Referenced by SDC.HTML_DEtype.ShouldSerializemaxLength.
ObjectChangeTracker SDC.HTML_DEtype.changeTrackerField
static XmlSerializer SDC.HTML_DEtype::serializer
long SDC.HTML_DEtype::minLength
bool SDC.HTML_DEtype::minLengthSpecified
long SDC.HTML_DEtype::maxLength
bool SDC.HTML_DEtype::maxLengthSpecified
static XmlSerializer SDC.HTML_DEtype::Serializer
Referenced by SDC.HTML_DEtype.Deserialize.
ObjectChangeTracker SDC.HTML_DEtype.ChangeTracker
SDC.HTML_DEtype.HTML_DEtype()
SDC.HTML_DEtype.HTML_DEtype(BaseType parentNode)
SDC.HTML_DEtype.HTML_DEtype()
virtual bool SDC.HTML_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
virtual bool SDC.HTML_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
virtual string SDC.HTML_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current HTML_DEtype object into an XML string
string XML value
virtual string SDC.HTML_DEtype.Serialize()
Referenced by SDC.HTML_DEtype.SaveToFile.
virtual bool SDC.HTML_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current HTML_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.HTML_DEtype.SaveToFile.
virtual bool SDC.HTML_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.HTML_DEtype.SaveToFile(string fileName)
virtual void SDC.HTML_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.HTML_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
References SDC.HTML_DEtype._minLength, SDC.HTML_DEtype._shouldSerializeminLength.
virtual bool SDC.HTML_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
References SDC.HTML_DEtype._maxLength, SDC.HTML_DEtype._shouldSerializemaxLength.
virtual string SDC.HTML_DEtype.Serialize()
Serializes current HTML_DEtype object into an XML string
string XML value
virtual bool SDC.HTML_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current HTML_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.HTML_DEtype.SaveToFile.
virtual void SDC.HTML_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.HTML_DEtype.Serialize.
virtual HTML_DEtype SDC.HTML_DEtype.Clone()
Create a clone of this HTML_DEtype object
static bool SDC.HTML_DEtype.Deserialize(string input, out HTML_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an HTML_DEtype object
input string workflow markup to deserialize obj Output HTML_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.HTML_DEtype.Deserialize, SDC.HTML_DEtype.LoadFromFile.
static bool SDC.HTML_DEtype.Deserialize(string input, out HTML_DEtype obj)
References SDC.null.
static new HTML_DEtype SDC.HTML_DEtype.Deserialize(string input)
References SDC.null.
static HTML_DEtype SDC.HTML_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.HTML_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out HTML_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an HTML_DEtype object
fileName string xml file to load and deserialize obj Output HTML_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.HTML_DEtype.LoadFromFile.
static bool SDC.HTML_DEtype.LoadFromFile(string fileName, out HTML_DEtype obj, out System.Exception exception)
static bool SDC.HTML_DEtype.LoadFromFile(string fileName, out HTML_DEtype obj)
References SDC.null.
static HTML_DEtype SDC.HTML_DEtype.LoadFromFile(string fileName)
static new HTML_DEtype SDC.HTML_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.HTML_DEtype.Deserialize(string input, out HTML_DEtype obj, out Exception exception)
Deserializes workflow markup into an HTML_DEtype object
input string workflow markup to deserialize obj Output HTML_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.HTML_DEtype.Deserialize, SDC.null.
static bool SDC.HTML_DEtype.Deserialize(string input, out HTML_DEtype obj)
References SDC.HTML_DEtype.Deserialize, SDC.null.
static new HTML_DEtype SDC.HTML_DEtype.Deserialize(string input)
References SDC.null, SDC.HTML_DEtype.Serializer.
static HTML_DEtype SDC.HTML_DEtype.Deserialize(Stream s)
References SDC.HTML_DEtype.Serializer.
static bool SDC.HTML_DEtype.LoadFromFile(string fileName, out HTML_DEtype obj, out Exception exception)
Deserializes xml markup from file into an HTML_DEtype object
fileName string xml file to load and deserialize obj Output HTML_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.HTML_DEtype.LoadFromFile, SDC.null.
static bool SDC.HTML_DEtype.LoadFromFile(string fileName, out HTML_DEtype obj)
References SDC.HTML_DEtype.LoadFromFile, SDC.null.
static new HTML_DEtype SDC.HTML_DEtype.LoadFromFile(string fileName)
References SDC.HTML_DEtype.Deserialize, SDC.null.