SDC::VersionTypeChanges
List<ChangeLogType> SDC.VersionTypeChanges._change
BindingList<ChangeLogType> SDC.VersionTypeChanges._change
ObjectChangeTracker SDC.VersionTypeChanges.changeTrackerField
static XmlSerializer SDC.VersionTypeChanges::serializer
virtual List<ChangeLogType> SDC.VersionTypeChanges.Change
static XmlSerializer SDC.VersionTypeChanges::Serializer
Referenced by SDC.VersionTypeChanges.Deserialize.
virtual BindingList<ChangeLogType> SDC.VersionTypeChanges.Change
ObjectChangeTracker SDC.VersionTypeChanges.ChangeTracker
SDC.VersionTypeChanges.VersionTypeChanges()
SDC.VersionTypeChanges.VersionTypeChanges(BaseType parentNode)
virtual bool SDC.VersionTypeChanges.ShouldSerializeChange()
Test whether Change should be serialized
References SDC.null.
virtual string SDC.VersionTypeChanges.Serialize(System.Text.Encoding encoding)
Serializes current VersionTypeChanges object into an XML string
string XML value
virtual string SDC.VersionTypeChanges.Serialize()
Referenced by SDC.VersionTypeChanges.SaveToFile.
virtual bool SDC.VersionTypeChanges.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current VersionTypeChanges object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.VersionTypeChanges.SaveToFile.
virtual bool SDC.VersionTypeChanges.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.VersionTypeChanges.SaveToFile(string fileName)
virtual void SDC.VersionTypeChanges.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.VersionTypeChanges.Serialize()
Serializes current VersionTypeChanges object into an XML string
string XML value
virtual bool SDC.VersionTypeChanges.SaveToFile(string fileName, out Exception exception)
Serializes current VersionTypeChanges object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.VersionTypeChanges.SaveToFile.
virtual void SDC.VersionTypeChanges.SaveToFile(string fileName)
References SDC.null, SDC.VersionTypeChanges.Serialize.
virtual VersionTypeChanges SDC.VersionTypeChanges.Clone()
Create a clone of this VersionTypeChanges object
static bool SDC.VersionTypeChanges.Deserialize(string input, out VersionTypeChanges obj, out System.Exception exception)
Deserializes workflow markup into an VersionTypeChanges object
input string workflow markup to deserialize obj Output VersionTypeChanges object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.VersionTypeChanges.Deserialize, SDC.VersionTypeChanges.LoadFromFile.
static bool SDC.VersionTypeChanges.Deserialize(string input, out VersionTypeChanges obj)
References SDC.null.
static new VersionTypeChanges SDC.VersionTypeChanges.Deserialize(string input)
References SDC.null.
static VersionTypeChanges SDC.VersionTypeChanges.Deserialize(System.IO.Stream s)
static bool SDC.VersionTypeChanges.LoadFromFile(string fileName, System.Text.Encoding encoding, out VersionTypeChanges obj, out System.Exception exception)
Deserializes xml markup from file into an VersionTypeChanges object
fileName string xml file to load and deserialize obj Output VersionTypeChanges object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.VersionTypeChanges.LoadFromFile.
static bool SDC.VersionTypeChanges.LoadFromFile(string fileName, out VersionTypeChanges obj, out System.Exception exception)
static bool SDC.VersionTypeChanges.LoadFromFile(string fileName, out VersionTypeChanges obj)
References SDC.null.
static VersionTypeChanges SDC.VersionTypeChanges.LoadFromFile(string fileName)
static new VersionTypeChanges SDC.VersionTypeChanges.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.VersionTypeChanges.Deserialize(string input, out VersionTypeChanges obj, out Exception exception)
Deserializes workflow markup into an VersionTypeChanges object
input string workflow markup to deserialize obj Output VersionTypeChanges object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.VersionTypeChanges.Deserialize, SDC.null.
static bool SDC.VersionTypeChanges.Deserialize(string input, out VersionTypeChanges obj)
References SDC.VersionTypeChanges.Deserialize, SDC.null.
static new VersionTypeChanges SDC.VersionTypeChanges.Deserialize(string input)
References SDC.null, SDC.VersionTypeChanges.Serializer.
static VersionTypeChanges SDC.VersionTypeChanges.Deserialize(Stream s)
References SDC.VersionTypeChanges.Serializer.
static bool SDC.VersionTypeChanges.LoadFromFile(string fileName, out VersionTypeChanges obj, out Exception exception)
Deserializes xml markup from file into an VersionTypeChanges object
fileName string xml file to load and deserialize obj Output VersionTypeChanges object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.VersionTypeChanges.LoadFromFile, SDC.null.
static bool SDC.VersionTypeChanges.LoadFromFile(string fileName, out VersionTypeChanges obj)
References SDC.VersionTypeChanges.LoadFromFile, SDC.null.
static new VersionTypeChanges SDC.VersionTypeChanges.LoadFromFile(string fileName)
References SDC.VersionTypeChanges.Deserialize, SDC.null.