SDC::dayTimeDuration_Stype
string SDC.dayTimeDuration_Stype::_val
dtQuantEnum SDC.dayTimeDuration_Stype::_quantEnum
Referenced by SDC.dayTimeDuration_Stype.dayTimeDuration_Stype.
ObjectChangeTracker SDC.dayTimeDuration_Stype.changeTrackerField
static XmlSerializer SDC.dayTimeDuration_Stype::serializer
string SDC.dayTimeDuration_Stype::val
Referenced by SDC.dayTimeDuration_Stype.ShouldSerializeval.
dtQuantEnum SDC.dayTimeDuration_Stype::quantEnum
static XmlSerializer SDC.dayTimeDuration_Stype::Serializer
Referenced by SDC.dayTimeDuration_Stype.Deserialize.
ObjectChangeTracker SDC.dayTimeDuration_Stype.ChangeTracker
SDC.dayTimeDuration_Stype.dayTimeDuration_Stype()
SDC.dayTimeDuration_Stype.dayTimeDuration_Stype(BaseType parentNode)
virtual bool SDC.dayTimeDuration_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.dayTimeDuration_Stype.val.
virtual string SDC.dayTimeDuration_Stype.Serialize(System.Text.Encoding encoding)
Serializes current dayTimeDuration_Stype object into an XML string
string XML value
virtual string SDC.dayTimeDuration_Stype.Serialize()
Referenced by SDC.dayTimeDuration_Stype.SaveToFile.
virtual bool SDC.dayTimeDuration_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current dayTimeDuration_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.dayTimeDuration_Stype.SaveToFile.
virtual bool SDC.dayTimeDuration_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.dayTimeDuration_Stype.SaveToFile.
virtual void SDC.dayTimeDuration_Stype.SaveToFile(string fileName)
References SDC.dayTimeDuration_Stype.SaveToFile.
virtual void SDC.dayTimeDuration_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.dayTimeDuration_Stype.Serialize.
SDC.dayTimeDuration_Stype.dayTimeDuration_Stype()
dayTimeDuration_Stype class constructor
References SDC.dayTimeDuration_Stype._quantEnum.
virtual bool SDC.dayTimeDuration_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.dayTimeDuration_Stype.val.
virtual string SDC.dayTimeDuration_Stype.Serialize()
Serializes current dayTimeDuration_Stype object into an XML string
string XML value
virtual bool SDC.dayTimeDuration_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current dayTimeDuration_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.dayTimeDuration_Stype.SaveToFile.
virtual void SDC.dayTimeDuration_Stype.SaveToFile(string fileName)
References SDC.null, SDC.dayTimeDuration_Stype.Serialize.
virtual dayTimeDuration_Stype SDC.dayTimeDuration_Stype.Clone()
Create a clone of this dayTimeDuration_Stype object
static bool SDC.dayTimeDuration_Stype.Deserialize(string input, out dayTimeDuration_Stype obj, out System.Exception exception)
Deserializes workflow markup into an dayTimeDuration_Stype object
input string workflow markup to deserialize obj Output dayTimeDuration_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dayTimeDuration_Stype.Deserialize, SDC.dayTimeDuration_Stype.LoadFromFile.
static bool SDC.dayTimeDuration_Stype.Deserialize(string input, out dayTimeDuration_Stype obj)
References SDC.dayTimeDuration_Stype.Deserialize, SDC.null.
static new dayTimeDuration_Stype SDC.dayTimeDuration_Stype.Deserialize(string input)
References SDC.null.
static dayTimeDuration_Stype SDC.dayTimeDuration_Stype.Deserialize(System.IO.Stream s)
References SDC.dayTimeDuration_Stype.Serializer.
static bool SDC.dayTimeDuration_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out dayTimeDuration_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an dayTimeDuration_Stype object
fileName string xml file to load and deserialize obj Output dayTimeDuration_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dayTimeDuration_Stype.LoadFromFile.
static bool SDC.dayTimeDuration_Stype.LoadFromFile(string fileName, out dayTimeDuration_Stype obj, out System.Exception exception)
References SDC.dayTimeDuration_Stype.LoadFromFile.
static bool SDC.dayTimeDuration_Stype.LoadFromFile(string fileName, out dayTimeDuration_Stype obj)
References SDC.dayTimeDuration_Stype.LoadFromFile, SDC.null.
static dayTimeDuration_Stype SDC.dayTimeDuration_Stype.LoadFromFile(string fileName)
References SDC.dayTimeDuration_Stype.LoadFromFile.
static new dayTimeDuration_Stype SDC.dayTimeDuration_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.dayTimeDuration_Stype.Deserialize, SDC.null.
static bool SDC.dayTimeDuration_Stype.Deserialize(string input, out dayTimeDuration_Stype obj, out Exception exception)
Deserializes workflow markup into an dayTimeDuration_Stype object
input string workflow markup to deserialize obj Output dayTimeDuration_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dayTimeDuration_Stype.Deserialize, SDC.null.
static bool SDC.dayTimeDuration_Stype.Deserialize(string input, out dayTimeDuration_Stype obj)
References SDC.dayTimeDuration_Stype.Deserialize, SDC.null.
static new dayTimeDuration_Stype SDC.dayTimeDuration_Stype.Deserialize(string input)
References SDC.null, SDC.dayTimeDuration_Stype.Serializer.
static dayTimeDuration_Stype SDC.dayTimeDuration_Stype.Deserialize(Stream s)
References SDC.dayTimeDuration_Stype.Serializer.
static bool SDC.dayTimeDuration_Stype.LoadFromFile(string fileName, out dayTimeDuration_Stype obj, out Exception exception)
Deserializes xml markup from file into an dayTimeDuration_Stype object
fileName string xml file to load and deserialize obj Output dayTimeDuration_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dayTimeDuration_Stype.LoadFromFile, SDC.null.
static bool SDC.dayTimeDuration_Stype.LoadFromFile(string fileName, out dayTimeDuration_Stype obj)
References SDC.dayTimeDuration_Stype.LoadFromFile, SDC.null.
static new dayTimeDuration_Stype SDC.dayTimeDuration_Stype.LoadFromFile(string fileName)
References SDC.dayTimeDuration_Stype.Deserialize, SDC.null.