SDC::PredicateBetweenType
MinExclusiveType SDC.PredicateBetweenType.MinExclusive_Item
MinExclusive
MinInclusiveType SDC.PredicateBetweenType.MinInclusive_Item
MinInclusive
MaxExclusiveType SDC.PredicateBetweenType.MaxExclusive_Item
MaxExclusive
MaxInclusiveType SDC.PredicateBetweenType.Max_Inclusive_Item
MaxInclusive
virtual BaseType SDC.PredicateBetweenType.Item
virtual BaseType SDC.PredicateBetweenType.Item1
virtual bool SDC.PredicateBetweenType.not
If true, converts the function into: not Between()
virtual bool SDC.PredicateBetweenType.notSpecified
XmlSerializer SDC.PredicateBetweenType.Serializer
Referenced by SDC.PredicateBetweenType.Deserialize.
ObjectChangeTracker SDC.PredicateBetweenType.ChangeTracker
bool SDC.PredicateBetweenType._shouldSerializenot
Referenced by SDC.PredicateBetweenType.ShouldSerializenot.
BaseType SDC.PredicateBetweenType._item
Referenced by SDC.PredicateBetweenType.ShouldSerializeItem.
BaseType SDC.PredicateBetweenType._item1
Referenced by SDC.PredicateBetweenType.ShouldSerializeItem1.
bool SDC.PredicateBetweenType._not
Referenced by SDC.PredicateBetweenType.ShouldSerializenot.
ObjectChangeTracker SDC.PredicateBetweenType.changeTrackerField
XmlSerializer SDC.PredicateBetweenType.serializer
SDC.PredicateBetweenType.PredicateBetweenType()
virtual bool SDC.PredicateBetweenType.ShouldSerializenot()
Test whether not should be serialized
References SDC.PredicateBetweenType._not, SDC.PredicateBetweenType._shouldSerializenot.
virtual bool SDC.PredicateBetweenType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.PredicateBetweenType._item, SDC.null.
virtual bool SDC.PredicateBetweenType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.PredicateBetweenType._item1, SDC.null.
virtual string SDC.PredicateBetweenType.Serialize()
Serializes current PredicateBetweenType object into an XML string
string XML value
Referenced by SDC.PredicateBetweenType.SaveToFile.
virtual bool SDC.PredicateBetweenType.SaveToFile(string fileName, out Exception exception)
Serializes current PredicateBetweenType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.PredicateBetweenType.SaveToFile(string fileName)
References SDC.null, SDC.PredicateBetweenType.Serialize.
virtual PredicateBetweenType SDC.PredicateBetweenType.Clone()
Create a clone of this PredicateBetweenType object
static bool SDC.PredicateBetweenType.Deserialize(string input, out PredicateBetweenType obj, out Exception exception)
Deserializes workflow markup into an PredicateBetweenType object
input string workflow markup to deserialize obj Output PredicateBetweenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PredicateBetweenType.Deserialize, SDC.PredicateBetweenType.LoadFromFile.
static bool SDC.PredicateBetweenType.Deserialize(string input, out PredicateBetweenType obj)
References SDC.PredicateBetweenType.Deserialize, SDC.null.
static new PredicateBetweenType SDC.PredicateBetweenType.Deserialize(string input)
References SDC.null, SDC.PredicateBetweenType.Serializer.
static PredicateBetweenType SDC.PredicateBetweenType.Deserialize(Stream s)
References SDC.PredicateBetweenType.Serializer.
static bool SDC.PredicateBetweenType.LoadFromFile(string fileName, out PredicateBetweenType obj, out Exception exception)
Deserializes xml markup from file into an PredicateBetweenType object
fileName string xml file to load and deserialize obj Output PredicateBetweenType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PredicateBetweenType.LoadFromFile.
static bool SDC.PredicateBetweenType.LoadFromFile(string fileName, out PredicateBetweenType obj)
References SDC.PredicateBetweenType.LoadFromFile, SDC.null.
static new PredicateBetweenType SDC.PredicateBetweenType.LoadFromFile(string fileName)
References SDC.PredicateBetweenType.Deserialize, SDC.null.