SDC::ReturnBoolListType
BoolListType SDC.ReturnBoolListType._item1
Referenced by SDC.ReturnBoolListType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnBoolListType.serializer
virtual BoolListType SDC.ReturnBoolListType.Item1
XmlSerializer SDC.ReturnBoolListType.Serializer
Referenced by SDC.ReturnBoolListType.Deserialize.
virtual bool SDC.ReturnBoolListType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnBoolListType._item1, SDC.null.
virtual string SDC.ReturnBoolListType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnBoolListType object into an XML string
string XML value
virtual string SDC.ReturnBoolListType.Serialize()
Referenced by SDC.ReturnBoolListType.SaveToFile.
virtual bool SDC.ReturnBoolListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnBoolListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnBoolListType.SaveToFile.
virtual bool SDC.ReturnBoolListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnBoolListType.SaveToFile.
virtual void SDC.ReturnBoolListType.SaveToFile(string fileName)
References SDC.ReturnBoolListType.SaveToFile.
virtual void SDC.ReturnBoolListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnBoolListType.Serialize.
static bool SDC.ReturnBoolListType.Deserialize(string input, out ReturnBoolListType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnBoolListType object
input string workflow markup to deserialize obj Output ReturnBoolListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnBoolListType.Deserialize, SDC.ReturnBoolListType.LoadFromFile.
static bool SDC.ReturnBoolListType.Deserialize(string input, out ReturnBoolListType obj)
References SDC.ReturnBoolListType.Deserialize, SDC.null.
static new ReturnBoolListType SDC.ReturnBoolListType.Deserialize(string input)
References SDC.null.
static ReturnBoolListType SDC.ReturnBoolListType.Deserialize(System.IO.Stream s)
References SDC.ReturnBoolListType.Serializer.
static bool SDC.ReturnBoolListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnBoolListType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnBoolListType object
fileName string xml file to load and deserialize obj Output ReturnBoolListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnBoolListType.LoadFromFile.
static bool SDC.ReturnBoolListType.LoadFromFile(string fileName, out ReturnBoolListType obj, out System.Exception exception)
References SDC.ReturnBoolListType.LoadFromFile.
static bool SDC.ReturnBoolListType.LoadFromFile(string fileName, out ReturnBoolListType obj)
References SDC.ReturnBoolListType.LoadFromFile, SDC.null.
static ReturnBoolListType SDC.ReturnBoolListType.LoadFromFile(string fileName)
References SDC.ReturnBoolListType.LoadFromFile.
static new ReturnBoolListType SDC.ReturnBoolListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnBoolListType.Deserialize, SDC.null.