SDC::ParameterType
string SDC.ParameterType._itemName
string SDC.ParameterType._itemProperty
ObjectChangeTracker SDC.ParameterType.changeTrackerField
XmlSerializer SDC.ParameterType.serializer
virtual string SDC.ParameterType.itemName
Referenced by SDC.ParameterType.ShouldSerializeitemName.
virtual string SDC.ParameterType.itemProperty
Referenced by SDC.ParameterType.ShouldSerializeitemProperty.
XmlSerializer SDC.ParameterType.Serializer
Referenced by SDC.ParameterType.Deserialize.
ObjectChangeTracker SDC.ParameterType.ChangeTracker
SDC.ParameterType.ParameterType()
virtual bool SDC.ParameterType.ShouldSerializeitemName()
Test whether itemName should be serialized
References SDC.ParameterType.itemName.
virtual bool SDC.ParameterType.ShouldSerializeitemProperty()
Test whether itemProperty should be serialized
References SDC.ParameterType.itemProperty.
virtual string SDC.ParameterType.Serialize()
Serializes current ParameterType object into an XML string
string XML value
Referenced by SDC.ParameterType.SaveToFile.
virtual bool SDC.ParameterType.SaveToFile(string fileName, out Exception exception)
Serializes current ParameterType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.ParameterType.SaveToFile(string fileName)
References SDC.null, SDC.ParameterType.Serialize.
virtual ParameterType SDC.ParameterType.Clone()
Create a clone of this ParameterType object
static bool SDC.ParameterType.Deserialize(string input, out ParameterType obj, out Exception exception)
Deserializes workflow markup into an ParameterType object
input string workflow markup to deserialize obj Output ParameterType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ParameterType.Deserialize, SDC.ParameterType.LoadFromFile.
static bool SDC.ParameterType.Deserialize(string input, out ParameterType obj)
References SDC.ParameterType.Deserialize, SDC.null.
static new ParameterType SDC.ParameterType.Deserialize(string input)
References SDC.null, SDC.ParameterType.Serializer.
static ParameterType SDC.ParameterType.Deserialize(Stream s)
References SDC.ParameterType.Serializer.
static bool SDC.ParameterType.LoadFromFile(string fileName, out ParameterType obj, out Exception exception)
Deserializes xml markup from file into an ParameterType object
fileName string xml file to load and deserialize obj Output ParameterType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ParameterType.LoadFromFile.
static bool SDC.ParameterType.LoadFromFile(string fileName, out ParameterType obj)
References SDC.ParameterType.LoadFromFile, SDC.null.
static new ParameterType SDC.ParameterType.LoadFromFile(string fileName)
References SDC.ParameterType.Deserialize, SDC.null.