SDC::base64Binary_DEtype
bool SDC.base64Binary_DEtype::_shouldSerializemaxLength
Referenced by SDC.base64Binary_DEtype.ShouldSerializemaxLength.
bool SDC.base64Binary_DEtype::_shouldSerializeminLength
Referenced by SDC.base64Binary_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.base64Binary_DEtype::_minLength
Referenced by SDC.base64Binary_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.base64Binary_DEtype::_maxLength
Referenced by SDC.base64Binary_DEtype.ShouldSerializemaxLength.
ObjectChangeTracker SDC.base64Binary_DEtype.changeTrackerField
static XmlSerializer SDC.base64Binary_DEtype::serializer
long SDC.base64Binary_DEtype::minLength
bool SDC.base64Binary_DEtype::minLengthSpecified
long SDC.base64Binary_DEtype::maxLength
bool SDC.base64Binary_DEtype::maxLengthSpecified
static XmlSerializer SDC.base64Binary_DEtype::Serializer
Referenced by SDC.base64Binary_DEtype.Deserialize.
ObjectChangeTracker SDC.base64Binary_DEtype.ChangeTracker
SDC.base64Binary_DEtype.base64Binary_DEtype()
SDC.base64Binary_DEtype.base64Binary_DEtype(BaseType parentNode)
SDC.base64Binary_DEtype.base64Binary_DEtype()
virtual bool SDC.base64Binary_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
virtual bool SDC.base64Binary_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
virtual string SDC.base64Binary_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current base64Binary_DEtype object into an XML string
string XML value
virtual string SDC.base64Binary_DEtype.Serialize()
Referenced by SDC.base64Binary_DEtype.SaveToFile.
virtual bool SDC.base64Binary_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current base64Binary_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.base64Binary_DEtype.SaveToFile.
virtual bool SDC.base64Binary_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.base64Binary_DEtype.SaveToFile(string fileName)
virtual void SDC.base64Binary_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.base64Binary_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
References SDC.base64Binary_DEtype._minLength, SDC.base64Binary_DEtype._shouldSerializeminLength.
virtual bool SDC.base64Binary_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
References SDC.base64Binary_DEtype._maxLength, SDC.base64Binary_DEtype._shouldSerializemaxLength.
virtual string SDC.base64Binary_DEtype.Serialize()
Serializes current base64Binary_DEtype object into an XML string
string XML value
virtual bool SDC.base64Binary_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current base64Binary_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.base64Binary_DEtype.SaveToFile.
virtual void SDC.base64Binary_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.base64Binary_DEtype.Serialize.
virtual base64Binary_DEtype SDC.base64Binary_DEtype.Clone()
Create a clone of this base64Binary_DEtype object
static bool SDC.base64Binary_DEtype.Deserialize(string input, out base64Binary_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an base64Binary_DEtype object
input string workflow markup to deserialize obj Output base64Binary_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.base64Binary_DEtype.Deserialize, SDC.base64Binary_DEtype.LoadFromFile.
static bool SDC.base64Binary_DEtype.Deserialize(string input, out base64Binary_DEtype obj)
References SDC.null.
static new base64Binary_DEtype SDC.base64Binary_DEtype.Deserialize(string input)
References SDC.null.
static base64Binary_DEtype SDC.base64Binary_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.base64Binary_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out base64Binary_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an base64Binary_DEtype object
fileName string xml file to load and deserialize obj Output base64Binary_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.base64Binary_DEtype.LoadFromFile.
static bool SDC.base64Binary_DEtype.LoadFromFile(string fileName, out base64Binary_DEtype obj, out System.Exception exception)
static bool SDC.base64Binary_DEtype.LoadFromFile(string fileName, out base64Binary_DEtype obj)
References SDC.null.
static base64Binary_DEtype SDC.base64Binary_DEtype.LoadFromFile(string fileName)
static new base64Binary_DEtype SDC.base64Binary_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.base64Binary_DEtype.Deserialize(string input, out base64Binary_DEtype obj, out Exception exception)
Deserializes workflow markup into an base64Binary_DEtype object
input string workflow markup to deserialize obj Output base64Binary_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.base64Binary_DEtype.Deserialize, SDC.null.
static bool SDC.base64Binary_DEtype.Deserialize(string input, out base64Binary_DEtype obj)
References SDC.base64Binary_DEtype.Deserialize, SDC.null.
static new base64Binary_DEtype SDC.base64Binary_DEtype.Deserialize(string input)
References SDC.null, SDC.base64Binary_DEtype.Serializer.
static base64Binary_DEtype SDC.base64Binary_DEtype.Deserialize(Stream s)
References SDC.base64Binary_DEtype.Serializer.
static bool SDC.base64Binary_DEtype.LoadFromFile(string fileName, out base64Binary_DEtype obj, out Exception exception)
Deserializes xml markup from file into an base64Binary_DEtype object
fileName string xml file to load and deserialize obj Output base64Binary_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.base64Binary_DEtype.LoadFromFile, SDC.null.
static bool SDC.base64Binary_DEtype.LoadFromFile(string fileName, out base64Binary_DEtype obj)
References SDC.base64Binary_DEtype.LoadFromFile, SDC.null.
static new base64Binary_DEtype SDC.base64Binary_DEtype.LoadFromFile(string fileName)
References SDC.base64Binary_DEtype.Deserialize, SDC.null.