SDC::___ConversionFunctions___
bool SDC.___ConversionFunctions___._shouldSerialize___DateTimeFunctions___
Referenced by SDC.___ConversionFunctions___.ShouldSerialize___DateTimeFunctions___.
object SDC.___ConversionFunctions___.___DateTimeFunctions___Field
Referenced by SDC.___ConversionFunctions___.ShouldSerialize___DateTimeFunctions___.
XmlSerializer SDC.___ConversionFunctions___.serializer
virtual object SDC.___ConversionFunctions___.___DateTimeFunctions___
XmlSerializer SDC.___ConversionFunctions___.Serializer
Referenced by SDC.___ConversionFunctions___.Deserialize.
virtual bool SDC.___ConversionFunctions___.ShouldSerialize___DateTimeFunctions___()
Test whether ___DateTimeFunctions___ should be serialized
References SDC.___ConversionFunctions___.___DateTimeFunctions___Field, SDC.___ConversionFunctions___._shouldSerialize___DateTimeFunctions___.
virtual string SDC.___ConversionFunctions___.Serialize(System.Text.Encoding encoding)
Serializes current ___ConversionFunctions___ object into an XML string
string XML value
virtual string SDC.___ConversionFunctions___.Serialize()
Referenced by SDC.___ConversionFunctions___.SaveToFile.
virtual bool SDC.___ConversionFunctions___.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ___ConversionFunctions___ object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.___ConversionFunctions___.SaveToFile.
virtual bool SDC.___ConversionFunctions___.SaveToFile(string fileName, out System.Exception exception)
References SDC.___ConversionFunctions___.SaveToFile.
virtual void SDC.___ConversionFunctions___.SaveToFile(string fileName)
References SDC.___ConversionFunctions___.SaveToFile.
virtual void SDC.___ConversionFunctions___.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.___ConversionFunctions___.Serialize.
static bool SDC.___ConversionFunctions___.Deserialize(string input, out ___ConversionFunctions___ obj, out System.Exception exception)
Deserializes workflow markup into an ___ConversionFunctions___ object
input string workflow markup to deserialize obj Output ___ConversionFunctions___ object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.___ConversionFunctions___.Deserialize, SDC.___ConversionFunctions___.LoadFromFile.
static bool SDC.___ConversionFunctions___.Deserialize(string input, out ___ConversionFunctions___ obj)
References SDC.___ConversionFunctions___.Deserialize, SDC.null.
static ___ConversionFunctions___ SDC.___ConversionFunctions___.Deserialize(string input)
References SDC.null.
static ___ConversionFunctions___ SDC.___ConversionFunctions___.Deserialize(System.IO.Stream s)
References SDC.___ConversionFunctions___.Serializer.
static bool SDC.___ConversionFunctions___.LoadFromFile(string fileName, System.Text.Encoding encoding, out ___ConversionFunctions___ obj, out System.Exception exception)
Deserializes xml markup from file into an ___ConversionFunctions___ object
fileName string xml file to load and deserialize obj Output ___ConversionFunctions___ object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.___ConversionFunctions___.LoadFromFile.
static bool SDC.___ConversionFunctions___.LoadFromFile(string fileName, out ___ConversionFunctions___ obj, out System.Exception exception)
References SDC.___ConversionFunctions___.LoadFromFile.
static bool SDC.___ConversionFunctions___.LoadFromFile(string fileName, out ___ConversionFunctions___ obj)
References SDC.___ConversionFunctions___.LoadFromFile, SDC.null.
static ___ConversionFunctions___ SDC.___ConversionFunctions___.LoadFromFile(string fileName)
References SDC.___ConversionFunctions___.LoadFromFile.
static ___ConversionFunctions___ SDC.___ConversionFunctions___.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.___ConversionFunctions___.Deserialize, SDC.null.