SDC::dateTime_Stype
bool SDC.dateTime_Stype::_shouldSerializeval
Referenced by SDC.dateTime_Stype.ShouldSerializeval.
System.Nullable<System.DateTime> SDC.dateTime_Stype._val
Referenced by SDC.dateTime_Stype.ShouldSerializeval.
dtQuantEnum SDC.dateTime_Stype::_quantEnum
Referenced by SDC.dateTime_Stype.dateTime_Stype.
DateTime SDC.dateTime_Stype._val
ObjectChangeTracker SDC.dateTime_Stype.changeTrackerField
static XmlSerializer SDC.dateTime_Stype::serializer
System DateTime SDC.dateTime_Stype::val
bool SDC.dateTime_Stype::valSpecified
dtQuantEnum SDC.dateTime_Stype::quantEnum
static XmlSerializer SDC.dateTime_Stype::Serializer
Referenced by SDC.dateTime_Stype.Deserialize.
ObjectChangeTracker SDC.dateTime_Stype.ChangeTracker
SDC.dateTime_Stype.dateTime_Stype()
SDC.dateTime_Stype.dateTime_Stype(BaseType parentNode)
virtual bool SDC.dateTime_Stype.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.dateTime_Stype.Serialize(System.Text.Encoding encoding)
Serializes current dateTime_Stype object into an XML string
string XML value
virtual string SDC.dateTime_Stype.Serialize()
Referenced by SDC.dateTime_Stype.SaveToFile.
virtual bool SDC.dateTime_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current dateTime_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.dateTime_Stype.SaveToFile.
virtual bool SDC.dateTime_Stype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.dateTime_Stype.SaveToFile(string fileName)
virtual void SDC.dateTime_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.dateTime_Stype.dateTime_Stype()
dateTime_Stype class constructor
References SDC.dateTime_Stype._quantEnum.
virtual bool SDC.dateTime_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.dateTime_Stype._shouldSerializeval, SDC.dateTime_Stype._val.
virtual string SDC.dateTime_Stype.Serialize()
Serializes current dateTime_Stype object into an XML string
string XML value
virtual bool SDC.dateTime_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current dateTime_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.dateTime_Stype.SaveToFile.
virtual void SDC.dateTime_Stype.SaveToFile(string fileName)
References SDC.null, SDC.dateTime_Stype.Serialize.
virtual dateTime_Stype SDC.dateTime_Stype.Clone()
Create a clone of this dateTime_Stype object
static bool SDC.dateTime_Stype.Deserialize(string input, out dateTime_Stype obj, out System.Exception exception)
Deserializes workflow markup into an dateTime_Stype object
input string workflow markup to deserialize obj Output dateTime_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dateTime_Stype.Deserialize, SDC.dateTime_Stype.LoadFromFile.
static bool SDC.dateTime_Stype.Deserialize(string input, out dateTime_Stype obj)
References SDC.null.
static new dateTime_Stype SDC.dateTime_Stype.Deserialize(string input)
References SDC.null.
static dateTime_Stype SDC.dateTime_Stype.Deserialize(System.IO.Stream s)
static bool SDC.dateTime_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out dateTime_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an dateTime_Stype object
fileName string xml file to load and deserialize obj Output dateTime_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dateTime_Stype.LoadFromFile.
static bool SDC.dateTime_Stype.LoadFromFile(string fileName, out dateTime_Stype obj, out System.Exception exception)
static bool SDC.dateTime_Stype.LoadFromFile(string fileName, out dateTime_Stype obj)
References SDC.null.
static dateTime_Stype SDC.dateTime_Stype.LoadFromFile(string fileName)
static new dateTime_Stype SDC.dateTime_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.dateTime_Stype.Deserialize(string input, out dateTime_Stype obj, out Exception exception)
Deserializes workflow markup into an dateTime_Stype object
input string workflow markup to deserialize obj Output dateTime_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dateTime_Stype.Deserialize, SDC.null.
static bool SDC.dateTime_Stype.Deserialize(string input, out dateTime_Stype obj)
References SDC.dateTime_Stype.Deserialize, SDC.null.
static new dateTime_Stype SDC.dateTime_Stype.Deserialize(string input)
References SDC.null, SDC.dateTime_Stype.Serializer.
static dateTime_Stype SDC.dateTime_Stype.Deserialize(Stream s)
References SDC.dateTime_Stype.Serializer.
static bool SDC.dateTime_Stype.LoadFromFile(string fileName, out dateTime_Stype obj, out Exception exception)
Deserializes xml markup from file into an dateTime_Stype object
fileName string xml file to load and deserialize obj Output dateTime_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dateTime_Stype.LoadFromFile, SDC.null.
static bool SDC.dateTime_Stype.LoadFromFile(string fileName, out dateTime_Stype obj)
References SDC.dateTime_Stype.LoadFromFile, SDC.null.
static new dateTime_Stype SDC.dateTime_Stype.LoadFromFile(string fileName)
References SDC.dateTime_Stype.Deserialize, SDC.null.