SDC::string_Stype
string SDC.string_Stype::_val
ObjectChangeTracker SDC.string_Stype.changeTrackerField
static XmlSerializer SDC.string_Stype::serializer
string SDC.string_Stype::val
Referenced by SDC.string_Stype.ShouldSerializeval.
static XmlSerializer SDC.string_Stype::Serializer
Referenced by SDC.string_Stype.Deserialize.
ObjectChangeTracker SDC.string_Stype.ChangeTracker
SDC.string_Stype.string_Stype()
SDC.string_Stype.string_Stype(BaseType parentNode, bool fillData=true)
virtual bool SDC.string_Stype.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.string_Stype.Serialize(System.Text.Encoding encoding)
Serializes current string_Stype object into an XML string
string XML value
virtual string SDC.string_Stype.Serialize()
Referenced by SDC.string_Stype.SaveToFile.
virtual bool SDC.string_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current string_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.string_Stype.SaveToFile.
virtual bool SDC.string_Stype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.string_Stype.SaveToFile(string fileName)
virtual void SDC.string_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.string_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.string_Stype.val.
virtual string SDC.string_Stype.Serialize()
Serializes current string_Stype object into an XML string
string XML value
virtual bool SDC.string_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current string_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.string_Stype.SaveToFile.
virtual void SDC.string_Stype.SaveToFile(string fileName)
References SDC.null, SDC.string_Stype.Serialize.
virtual string_Stype SDC.string_Stype.Clone()
Create a clone of this string_Stype object
static bool SDC.string_Stype.Deserialize(string input, out string_Stype obj, out System.Exception exception)
Deserializes workflow markup into an string_Stype object
input string workflow markup to deserialize obj Output string_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.string_Stype.Deserialize, SDC.string_Stype.LoadFromFile.
static bool SDC.string_Stype.Deserialize(string input, out string_Stype obj)
References SDC.null.
static new string_Stype SDC.string_Stype.Deserialize(string input)
References SDC.null.
static string_Stype SDC.string_Stype.Deserialize(System.IO.Stream s)
static bool SDC.string_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out string_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an string_Stype object
fileName string xml file to load and deserialize obj Output string_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.string_Stype.LoadFromFile.
static bool SDC.string_Stype.LoadFromFile(string fileName, out string_Stype obj, out System.Exception exception)
static bool SDC.string_Stype.LoadFromFile(string fileName, out string_Stype obj)
References SDC.null.
static string_Stype SDC.string_Stype.LoadFromFile(string fileName)
static new string_Stype SDC.string_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.string_Stype.Deserialize(string input, out string_Stype obj, out Exception exception)
Deserializes workflow markup into an string_Stype object
input string workflow markup to deserialize obj Output string_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.string_Stype.Deserialize, SDC.null.
static bool SDC.string_Stype.Deserialize(string input, out string_Stype obj)
References SDC.string_Stype.Deserialize, SDC.null.
static new string_Stype SDC.string_Stype.Deserialize(string input)
References SDC.null, SDC.string_Stype.Serializer.
static string_Stype SDC.string_Stype.Deserialize(Stream s)
References SDC.string_Stype.Serializer.
static bool SDC.string_Stype.LoadFromFile(string fileName, out string_Stype obj, out Exception exception)
Deserializes xml markup from file into an string_Stype object
fileName string xml file to load and deserialize obj Output string_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.string_Stype.LoadFromFile, SDC.null.
static bool SDC.string_Stype.LoadFromFile(string fileName, out string_Stype obj)
References SDC.string_Stype.LoadFromFile, SDC.null.
static new string_Stype SDC.string_Stype.LoadFromFile(string fileName)
References SDC.string_Stype.Deserialize, SDC.null.