SDC::nonPositiveInteger_DEtype
string SDC.nonPositiveInteger_DEtype::_minInclusive
string SDC.nonPositiveInteger_DEtype::_maxInclusive
string SDC.nonPositiveInteger_DEtype::_minExclusive
string SDC.nonPositiveInteger_DEtype::_maxExclusive
System Nullable< byte > SDC.nonPositiveInteger_DEtype::_totalDigits
string SDC.nonPositiveInteger_DEtype::_mask
ObjectChangeTracker SDC.nonPositiveInteger_DEtype.changeTrackerField
static XmlSerializer SDC.nonPositiveInteger_DEtype::serializer
string SDC.nonPositiveInteger_DEtype::minInclusive
Referenced by SDC.nonPositiveInteger_DEtype.ShouldSerializeminInclusive.
string SDC.nonPositiveInteger_DEtype::maxInclusive
Referenced by SDC.nonPositiveInteger_DEtype.ShouldSerializemaxInclusive.
string SDC.nonPositiveInteger_DEtype::minExclusive
Referenced by SDC.nonPositiveInteger_DEtype.ShouldSerializeminExclusive.
string SDC.nonPositiveInteger_DEtype::maxExclusive
Referenced by SDC.nonPositiveInteger_DEtype.ShouldSerializemaxExclusive.
byte SDC.nonPositiveInteger_DEtype::totalDigits
bool SDC.nonPositiveInteger_DEtype::totalDigitsSpecified
string SDC.nonPositiveInteger_DEtype::mask
Referenced by SDC.nonPositiveInteger_DEtype.ShouldSerializemask.
static XmlSerializer SDC.nonPositiveInteger_DEtype::Serializer
Referenced by SDC.nonPositiveInteger_DEtype.Deserialize.
ObjectChangeTracker SDC.nonPositiveInteger_DEtype.ChangeTracker
SDC.nonPositiveInteger_DEtype.nonPositiveInteger_DEtype()
SDC.nonPositiveInteger_DEtype.nonPositiveInteger_DEtype(BaseType parentNode)
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.nonPositiveInteger_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current nonPositiveInteger_DEtype object into an XML string
string XML value
virtual string SDC.nonPositiveInteger_DEtype.Serialize()
Referenced by SDC.nonPositiveInteger_DEtype.SaveToFile.
virtual bool SDC.nonPositiveInteger_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current nonPositiveInteger_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.nonPositiveInteger_DEtype.SaveToFile.
virtual bool SDC.nonPositiveInteger_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.nonPositiveInteger_DEtype.SaveToFile(string fileName)
virtual void SDC.nonPositiveInteger_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.nonPositiveInteger_DEtype.minInclusive.
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.nonPositiveInteger_DEtype.maxInclusive.
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.nonPositiveInteger_DEtype.minExclusive.
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.nonPositiveInteger_DEtype.maxExclusive.
virtual bool SDC.nonPositiveInteger_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.nonPositiveInteger_DEtype.mask.
virtual string SDC.nonPositiveInteger_DEtype.Serialize()
Serializes current nonPositiveInteger_DEtype object into an XML string
string XML value
virtual bool SDC.nonPositiveInteger_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current nonPositiveInteger_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.nonPositiveInteger_DEtype.SaveToFile.
virtual void SDC.nonPositiveInteger_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.nonPositiveInteger_DEtype.Serialize.
virtual nonPositiveInteger_DEtype SDC.nonPositiveInteger_DEtype.Clone()
Create a clone of this nonPositiveInteger_DEtype object
static bool SDC.nonPositiveInteger_DEtype.Deserialize(string input, out nonPositiveInteger_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an nonPositiveInteger_DEtype object
input string workflow markup to deserialize obj Output nonPositiveInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.nonPositiveInteger_DEtype.Deserialize, SDC.nonPositiveInteger_DEtype.LoadFromFile.
static bool SDC.nonPositiveInteger_DEtype.Deserialize(string input, out nonPositiveInteger_DEtype obj)
References SDC.null.
static new nonPositiveInteger_DEtype SDC.nonPositiveInteger_DEtype.Deserialize(string input)
References SDC.null.
static nonPositiveInteger_DEtype SDC.nonPositiveInteger_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.nonPositiveInteger_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out nonPositiveInteger_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an nonPositiveInteger_DEtype object
fileName string xml file to load and deserialize obj Output nonPositiveInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.nonPositiveInteger_DEtype.LoadFromFile.
static bool SDC.nonPositiveInteger_DEtype.LoadFromFile(string fileName, out nonPositiveInteger_DEtype obj, out System.Exception exception)
static bool SDC.nonPositiveInteger_DEtype.LoadFromFile(string fileName, out nonPositiveInteger_DEtype obj)
References SDC.null.
static nonPositiveInteger_DEtype SDC.nonPositiveInteger_DEtype.LoadFromFile(string fileName)
static new nonPositiveInteger_DEtype SDC.nonPositiveInteger_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.nonPositiveInteger_DEtype.Deserialize(string input, out nonPositiveInteger_DEtype obj, out Exception exception)
Deserializes workflow markup into an nonPositiveInteger_DEtype object
input string workflow markup to deserialize obj Output nonPositiveInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.nonPositiveInteger_DEtype.Deserialize, SDC.null.
static bool SDC.nonPositiveInteger_DEtype.Deserialize(string input, out nonPositiveInteger_DEtype obj)
References SDC.nonPositiveInteger_DEtype.Deserialize, SDC.null.
static new nonPositiveInteger_DEtype SDC.nonPositiveInteger_DEtype.Deserialize(string input)
References SDC.null, SDC.nonPositiveInteger_DEtype.Serializer.
static nonPositiveInteger_DEtype SDC.nonPositiveInteger_DEtype.Deserialize(Stream s)
References SDC.nonPositiveInteger_DEtype.Serializer.
static bool SDC.nonPositiveInteger_DEtype.LoadFromFile(string fileName, out nonPositiveInteger_DEtype obj, out Exception exception)
Deserializes xml markup from file into an nonPositiveInteger_DEtype object
fileName string xml file to load and deserialize obj Output nonPositiveInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.nonPositiveInteger_DEtype.LoadFromFile, SDC.null.
static bool SDC.nonPositiveInteger_DEtype.LoadFromFile(string fileName, out nonPositiveInteger_DEtype obj)
References SDC.nonPositiveInteger_DEtype.LoadFromFile, SDC.null.
static new nonPositiveInteger_DEtype SDC.nonPositiveInteger_DEtype.LoadFromFile(string fileName)
References SDC.nonPositiveInteger_DEtype.Deserialize, SDC.null.