SDC::ReturnAtomicOrListType
ExtensionBaseType SDC.ReturnAtomicOrListType._item1
Referenced by SDC.ReturnAtomicOrListType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnAtomicOrListType.serializer
virtual ExtensionBaseType SDC.ReturnAtomicOrListType.Item1
XmlSerializer SDC.ReturnAtomicOrListType.Serializer
Referenced by SDC.ReturnAtomicOrListType.Deserialize.
virtual bool SDC.ReturnAtomicOrListType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnAtomicOrListType._item1, SDC.null.
virtual string SDC.ReturnAtomicOrListType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnAtomicOrListType object into an XML string
string XML value
virtual string SDC.ReturnAtomicOrListType.Serialize()
Referenced by SDC.ReturnAtomicOrListType.SaveToFile.
virtual bool SDC.ReturnAtomicOrListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnAtomicOrListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnAtomicOrListType.SaveToFile.
virtual bool SDC.ReturnAtomicOrListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnAtomicOrListType.SaveToFile.
virtual void SDC.ReturnAtomicOrListType.SaveToFile(string fileName)
References SDC.ReturnAtomicOrListType.SaveToFile.
virtual void SDC.ReturnAtomicOrListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnAtomicOrListType.Serialize.
static bool SDC.ReturnAtomicOrListType.Deserialize(string input, out ReturnAtomicOrListType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnAtomicOrListType object
input string workflow markup to deserialize obj Output ReturnAtomicOrListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnAtomicOrListType.Deserialize, SDC.ReturnAtomicOrListType.LoadFromFile.
static bool SDC.ReturnAtomicOrListType.Deserialize(string input, out ReturnAtomicOrListType obj)
References SDC.ReturnAtomicOrListType.Deserialize, SDC.null.
static new ReturnAtomicOrListType SDC.ReturnAtomicOrListType.Deserialize(string input)
References SDC.null.
static ReturnAtomicOrListType SDC.ReturnAtomicOrListType.Deserialize(System.IO.Stream s)
References SDC.ReturnAtomicOrListType.Serializer.
static bool SDC.ReturnAtomicOrListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnAtomicOrListType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnAtomicOrListType object
fileName string xml file to load and deserialize obj Output ReturnAtomicOrListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnAtomicOrListType.LoadFromFile.
static bool SDC.ReturnAtomicOrListType.LoadFromFile(string fileName, out ReturnAtomicOrListType obj, out System.Exception exception)
References SDC.ReturnAtomicOrListType.LoadFromFile.
static bool SDC.ReturnAtomicOrListType.LoadFromFile(string fileName, out ReturnAtomicOrListType obj)
References SDC.ReturnAtomicOrListType.LoadFromFile, SDC.null.
static ReturnAtomicOrListType SDC.ReturnAtomicOrListType.LoadFromFile(string fileName)
References SDC.ReturnAtomicOrListType.LoadFromFile.
static new ReturnAtomicOrListType SDC.ReturnAtomicOrListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnAtomicOrListType.Deserialize, SDC.null.