SDC::dayTimeDuration_DEtype
string SDC.dayTimeDuration_DEtype::_maxExclusive
string SDC.dayTimeDuration_DEtype::_minExclusive
string SDC.dayTimeDuration_DEtype::_maxInclusive
string SDC.dayTimeDuration_DEtype::_minInclusive
string SDC.dayTimeDuration_DEtype::_mask
ObjectChangeTracker SDC.dayTimeDuration_DEtype.changeTrackerField
static XmlSerializer SDC.dayTimeDuration_DEtype::serializer
string SDC.dayTimeDuration_DEtype::maxExclusive
Referenced by SDC.dayTimeDuration_DEtype.ShouldSerializemaxExclusive.
string SDC.dayTimeDuration_DEtype::minExclusive
Referenced by SDC.dayTimeDuration_DEtype.ShouldSerializeminExclusive.
string SDC.dayTimeDuration_DEtype::maxInclusive
Referenced by SDC.dayTimeDuration_DEtype.ShouldSerializemaxInclusive.
string SDC.dayTimeDuration_DEtype::minInclusive
Referenced by SDC.dayTimeDuration_DEtype.ShouldSerializeminInclusive.
string SDC.dayTimeDuration_DEtype::mask
Referenced by SDC.dayTimeDuration_DEtype.ShouldSerializemask.
static XmlSerializer SDC.dayTimeDuration_DEtype::Serializer
Referenced by SDC.dayTimeDuration_DEtype.Deserialize.
ObjectChangeTracker SDC.dayTimeDuration_DEtype.ChangeTracker
SDC.dayTimeDuration_DEtype.dayTimeDuration_DEtype()
SDC.dayTimeDuration_DEtype.dayTimeDuration_DEtype(BaseType parentNode)
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.dayTimeDuration_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current dayTimeDuration_DEtype object into an XML string
string XML value
virtual string SDC.dayTimeDuration_DEtype.Serialize()
Referenced by SDC.dayTimeDuration_DEtype.SaveToFile.
virtual bool SDC.dayTimeDuration_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current dayTimeDuration_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.dayTimeDuration_DEtype.SaveToFile.
virtual bool SDC.dayTimeDuration_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.dayTimeDuration_DEtype.SaveToFile(string fileName)
virtual void SDC.dayTimeDuration_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.dayTimeDuration_DEtype.maxExclusive.
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.dayTimeDuration_DEtype.minExclusive.
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.dayTimeDuration_DEtype.maxInclusive.
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.dayTimeDuration_DEtype.minInclusive.
virtual bool SDC.dayTimeDuration_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.dayTimeDuration_DEtype.mask.
virtual string SDC.dayTimeDuration_DEtype.Serialize()
Serializes current dayTimeDuration_DEtype object into an XML string
string XML value
virtual bool SDC.dayTimeDuration_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current dayTimeDuration_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.dayTimeDuration_DEtype.SaveToFile.
virtual void SDC.dayTimeDuration_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.dayTimeDuration_DEtype.Serialize.
virtual dayTimeDuration_DEtype SDC.dayTimeDuration_DEtype.Clone()
Create a clone of this dayTimeDuration_DEtype object
static bool SDC.dayTimeDuration_DEtype.Deserialize(string input, out dayTimeDuration_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an dayTimeDuration_DEtype object
input string workflow markup to deserialize obj Output dayTimeDuration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dayTimeDuration_DEtype.Deserialize, SDC.dayTimeDuration_DEtype.LoadFromFile.
static bool SDC.dayTimeDuration_DEtype.Deserialize(string input, out dayTimeDuration_DEtype obj)
References SDC.null.
static new dayTimeDuration_DEtype SDC.dayTimeDuration_DEtype.Deserialize(string input)
References SDC.null.
static dayTimeDuration_DEtype SDC.dayTimeDuration_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.dayTimeDuration_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out dayTimeDuration_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an dayTimeDuration_DEtype object
fileName string xml file to load and deserialize obj Output dayTimeDuration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dayTimeDuration_DEtype.LoadFromFile.
static bool SDC.dayTimeDuration_DEtype.LoadFromFile(string fileName, out dayTimeDuration_DEtype obj, out System.Exception exception)
static bool SDC.dayTimeDuration_DEtype.LoadFromFile(string fileName, out dayTimeDuration_DEtype obj)
References SDC.null.
static dayTimeDuration_DEtype SDC.dayTimeDuration_DEtype.LoadFromFile(string fileName)
static new dayTimeDuration_DEtype SDC.dayTimeDuration_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.dayTimeDuration_DEtype.Deserialize(string input, out dayTimeDuration_DEtype obj, out Exception exception)
Deserializes workflow markup into an dayTimeDuration_DEtype object
input string workflow markup to deserialize obj Output dayTimeDuration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dayTimeDuration_DEtype.Deserialize, SDC.null.
static bool SDC.dayTimeDuration_DEtype.Deserialize(string input, out dayTimeDuration_DEtype obj)
References SDC.dayTimeDuration_DEtype.Deserialize, SDC.null.
static new dayTimeDuration_DEtype SDC.dayTimeDuration_DEtype.Deserialize(string input)
References SDC.null, SDC.dayTimeDuration_DEtype.Serializer.
static dayTimeDuration_DEtype SDC.dayTimeDuration_DEtype.Deserialize(Stream s)
References SDC.dayTimeDuration_DEtype.Serializer.
static bool SDC.dayTimeDuration_DEtype.LoadFromFile(string fileName, out dayTimeDuration_DEtype obj, out Exception exception)
Deserializes xml markup from file into an dayTimeDuration_DEtype object
fileName string xml file to load and deserialize obj Output dayTimeDuration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dayTimeDuration_DEtype.LoadFromFile, SDC.null.
static bool SDC.dayTimeDuration_DEtype.LoadFromFile(string fileName, out dayTimeDuration_DEtype obj)
References SDC.dayTimeDuration_DEtype.LoadFromFile, SDC.null.
static new dayTimeDuration_DEtype SDC.dayTimeDuration_DEtype.LoadFromFile(string fileName)
References SDC.dayTimeDuration_DEtype.Deserialize, SDC.null.