SDC::ChangedSelectedItemsType
BindingList<ChangedListItemType> SDC.ChangedSelectedItemsType._listItem
ObjectChangeTracker SDC.ChangedSelectedItemsType.changeTrackerField
XmlSerializer SDC.ChangedSelectedItemsType.serializer
virtual BindingList<ChangedListItemType> SDC.ChangedSelectedItemsType.ListItem
Each selected ListItem from the replaced set of selected ListItems is recorded here.
XmlSerializer SDC.ChangedSelectedItemsType.Serializer
Referenced by SDC.ChangedSelectedItemsType.Deserialize.
ObjectChangeTracker SDC.ChangedSelectedItemsType.ChangeTracker
virtual string SDC.ChangedSelectedItemsType.Serialize()
Serializes current ChangedSelectedItemsType object into an XML string
string XML value
Referenced by SDC.ChangedSelectedItemsType.SaveToFile.
virtual bool SDC.ChangedSelectedItemsType.SaveToFile(string fileName, out Exception exception)
Serializes current ChangedSelectedItemsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.ChangedSelectedItemsType.SaveToFile(string fileName)
References SDC.null, SDC.ChangedSelectedItemsType.Serialize.
virtual ChangedSelectedItemsType SDC.ChangedSelectedItemsType.Clone()
Create a clone of this ChangedSelectedItemsType object
static bool SDC.ChangedSelectedItemsType.Deserialize(string input, out ChangedSelectedItemsType obj, out Exception exception)
Deserializes workflow markup into an ChangedSelectedItemsType object
input string workflow markup to deserialize obj Output ChangedSelectedItemsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangedSelectedItemsType.Deserialize, SDC.ChangedSelectedItemsType.LoadFromFile.
static bool SDC.ChangedSelectedItemsType.Deserialize(string input, out ChangedSelectedItemsType obj)
References SDC.ChangedSelectedItemsType.Deserialize, SDC.null.
static new ChangedSelectedItemsType SDC.ChangedSelectedItemsType.Deserialize(string input)
References SDC.null, SDC.ChangedSelectedItemsType.Serializer.
static ChangedSelectedItemsType SDC.ChangedSelectedItemsType.Deserialize(Stream s)
References SDC.ChangedSelectedItemsType.Serializer.
static bool SDC.ChangedSelectedItemsType.LoadFromFile(string fileName, out ChangedSelectedItemsType obj, out Exception exception)
Deserializes xml markup from file into an ChangedSelectedItemsType object
fileName string xml file to load and deserialize obj Output ChangedSelectedItemsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangedSelectedItemsType.LoadFromFile.
static bool SDC.ChangedSelectedItemsType.LoadFromFile(string fileName, out ChangedSelectedItemsType obj)
References SDC.ChangedSelectedItemsType.LoadFromFile, SDC.null.
static new ChangedSelectedItemsType SDC.ChangedSelectedItemsType.LoadFromFile(string fileName)
References SDC.ChangedSelectedItemsType.Deserialize, SDC.null.