SDC::nonNegativeInteger_DEtype
string SDC.nonNegativeInteger_DEtype::_minInclusive
string SDC.nonNegativeInteger_DEtype::_maxInclusive
string SDC.nonNegativeInteger_DEtype::_minExclusive
string SDC.nonNegativeInteger_DEtype::_maxExclusive
System Nullable< byte > SDC.nonNegativeInteger_DEtype::_totalDigits
string SDC.nonNegativeInteger_DEtype::_mask
ObjectChangeTracker SDC.nonNegativeInteger_DEtype.changeTrackerField
static XmlSerializer SDC.nonNegativeInteger_DEtype::serializer
string SDC.nonNegativeInteger_DEtype::minInclusive
Referenced by SDC.nonNegativeInteger_DEtype.ShouldSerializeminInclusive.
string SDC.nonNegativeInteger_DEtype::maxInclusive
Referenced by SDC.nonNegativeInteger_DEtype.ShouldSerializemaxInclusive.
string SDC.nonNegativeInteger_DEtype::minExclusive
Referenced by SDC.nonNegativeInteger_DEtype.ShouldSerializeminExclusive.
string SDC.nonNegativeInteger_DEtype::maxExclusive
Referenced by SDC.nonNegativeInteger_DEtype.ShouldSerializemaxExclusive.
byte SDC.nonNegativeInteger_DEtype::totalDigits
bool SDC.nonNegativeInteger_DEtype::totalDigitsSpecified
string SDC.nonNegativeInteger_DEtype::mask
Referenced by SDC.nonNegativeInteger_DEtype.ShouldSerializemask.
static XmlSerializer SDC.nonNegativeInteger_DEtype::Serializer
Referenced by SDC.nonNegativeInteger_DEtype.Deserialize.
ObjectChangeTracker SDC.nonNegativeInteger_DEtype.ChangeTracker
SDC.nonNegativeInteger_DEtype.nonNegativeInteger_DEtype()
SDC.nonNegativeInteger_DEtype.nonNegativeInteger_DEtype(BaseType parentNode)
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.nonNegativeInteger_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current nonNegativeInteger_DEtype object into an XML string
string XML value
virtual string SDC.nonNegativeInteger_DEtype.Serialize()
Referenced by SDC.nonNegativeInteger_DEtype.SaveToFile.
virtual bool SDC.nonNegativeInteger_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current nonNegativeInteger_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.nonNegativeInteger_DEtype.SaveToFile.
virtual bool SDC.nonNegativeInteger_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.nonNegativeInteger_DEtype.SaveToFile(string fileName)
virtual void SDC.nonNegativeInteger_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.nonNegativeInteger_DEtype.minInclusive.
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.nonNegativeInteger_DEtype.maxInclusive.
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.nonNegativeInteger_DEtype.minExclusive.
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.nonNegativeInteger_DEtype.maxExclusive.
virtual bool SDC.nonNegativeInteger_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.nonNegativeInteger_DEtype.mask.
virtual string SDC.nonNegativeInteger_DEtype.Serialize()
Serializes current nonNegativeInteger_DEtype object into an XML string
string XML value
virtual bool SDC.nonNegativeInteger_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current nonNegativeInteger_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.nonNegativeInteger_DEtype.SaveToFile.
virtual void SDC.nonNegativeInteger_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.nonNegativeInteger_DEtype.Serialize.
virtual nonNegativeInteger_DEtype SDC.nonNegativeInteger_DEtype.Clone()
Create a clone of this nonNegativeInteger_DEtype object
static bool SDC.nonNegativeInteger_DEtype.Deserialize(string input, out nonNegativeInteger_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an nonNegativeInteger_DEtype object
input string workflow markup to deserialize obj Output nonNegativeInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.nonNegativeInteger_DEtype.Deserialize, SDC.nonNegativeInteger_DEtype.LoadFromFile.
static bool SDC.nonNegativeInteger_DEtype.Deserialize(string input, out nonNegativeInteger_DEtype obj)
References SDC.null.
static new nonNegativeInteger_DEtype SDC.nonNegativeInteger_DEtype.Deserialize(string input)
References SDC.null.
static nonNegativeInteger_DEtype SDC.nonNegativeInteger_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.nonNegativeInteger_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out nonNegativeInteger_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an nonNegativeInteger_DEtype object
fileName string xml file to load and deserialize obj Output nonNegativeInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.nonNegativeInteger_DEtype.LoadFromFile.
static bool SDC.nonNegativeInteger_DEtype.LoadFromFile(string fileName, out nonNegativeInteger_DEtype obj, out System.Exception exception)
static bool SDC.nonNegativeInteger_DEtype.LoadFromFile(string fileName, out nonNegativeInteger_DEtype obj)
References SDC.null.
static nonNegativeInteger_DEtype SDC.nonNegativeInteger_DEtype.LoadFromFile(string fileName)
static new nonNegativeInteger_DEtype SDC.nonNegativeInteger_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.nonNegativeInteger_DEtype.Deserialize(string input, out nonNegativeInteger_DEtype obj, out Exception exception)
Deserializes workflow markup into an nonNegativeInteger_DEtype object
input string workflow markup to deserialize obj Output nonNegativeInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.nonNegativeInteger_DEtype.Deserialize, SDC.null.
static bool SDC.nonNegativeInteger_DEtype.Deserialize(string input, out nonNegativeInteger_DEtype obj)
References SDC.nonNegativeInteger_DEtype.Deserialize, SDC.null.
static new nonNegativeInteger_DEtype SDC.nonNegativeInteger_DEtype.Deserialize(string input)
References SDC.null, SDC.nonNegativeInteger_DEtype.Serializer.
static nonNegativeInteger_DEtype SDC.nonNegativeInteger_DEtype.Deserialize(Stream s)
References SDC.nonNegativeInteger_DEtype.Serializer.
static bool SDC.nonNegativeInteger_DEtype.LoadFromFile(string fileName, out nonNegativeInteger_DEtype obj, out Exception exception)
Deserializes xml markup from file into an nonNegativeInteger_DEtype object
fileName string xml file to load and deserialize obj Output nonNegativeInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.nonNegativeInteger_DEtype.LoadFromFile, SDC.null.
static bool SDC.nonNegativeInteger_DEtype.LoadFromFile(string fileName, out nonNegativeInteger_DEtype obj)
References SDC.nonNegativeInteger_DEtype.LoadFromFile, SDC.null.
static new nonNegativeInteger_DEtype SDC.nonNegativeInteger_DEtype.LoadFromFile(string fileName)
References SDC.nonNegativeInteger_DEtype.Deserialize, SDC.null.