SDC::yearMonthDuration_Stype
string SDC.yearMonthDuration_Stype::_val
dtQuantEnum SDC.yearMonthDuration_Stype::_quantEnum
Referenced by SDC.yearMonthDuration_Stype.yearMonthDuration_Stype.
ObjectChangeTracker SDC.yearMonthDuration_Stype.changeTrackerField
static XmlSerializer SDC.yearMonthDuration_Stype::serializer
string SDC.yearMonthDuration_Stype::val
Referenced by SDC.yearMonthDuration_Stype.ShouldSerializeval.
dtQuantEnum SDC.yearMonthDuration_Stype::quantEnum
static XmlSerializer SDC.yearMonthDuration_Stype::Serializer
Referenced by SDC.yearMonthDuration_Stype.Deserialize.
ObjectChangeTracker SDC.yearMonthDuration_Stype.ChangeTracker
SDC.yearMonthDuration_Stype.yearMonthDuration_Stype()
SDC.yearMonthDuration_Stype.yearMonthDuration_Stype(BaseType parentNode)
virtual bool SDC.yearMonthDuration_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.yearMonthDuration_Stype.val.
virtual string SDC.yearMonthDuration_Stype.Serialize(System.Text.Encoding encoding)
Serializes current yearMonthDuration_Stype object into an XML string
string XML value
virtual string SDC.yearMonthDuration_Stype.Serialize()
Referenced by SDC.yearMonthDuration_Stype.SaveToFile.
virtual bool SDC.yearMonthDuration_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current yearMonthDuration_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.yearMonthDuration_Stype.SaveToFile.
virtual bool SDC.yearMonthDuration_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.yearMonthDuration_Stype.SaveToFile.
virtual void SDC.yearMonthDuration_Stype.SaveToFile(string fileName)
References SDC.yearMonthDuration_Stype.SaveToFile.
virtual void SDC.yearMonthDuration_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.yearMonthDuration_Stype.Serialize.
SDC.yearMonthDuration_Stype.yearMonthDuration_Stype()
yearMonthDuration_Stype class constructor
References SDC.yearMonthDuration_Stype._quantEnum.
virtual bool SDC.yearMonthDuration_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.yearMonthDuration_Stype.val.
virtual string SDC.yearMonthDuration_Stype.Serialize()
Serializes current yearMonthDuration_Stype object into an XML string
string XML value
virtual bool SDC.yearMonthDuration_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current yearMonthDuration_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.yearMonthDuration_Stype.SaveToFile.
virtual void SDC.yearMonthDuration_Stype.SaveToFile(string fileName)
References SDC.null, SDC.yearMonthDuration_Stype.Serialize.
virtual yearMonthDuration_Stype SDC.yearMonthDuration_Stype.Clone()
Create a clone of this yearMonthDuration_Stype object
static bool SDC.yearMonthDuration_Stype.Deserialize(string input, out yearMonthDuration_Stype obj, out System.Exception exception)
Deserializes workflow markup into an yearMonthDuration_Stype object
input string workflow markup to deserialize obj Output yearMonthDuration_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.yearMonthDuration_Stype.Deserialize, SDC.yearMonthDuration_Stype.LoadFromFile.
static bool SDC.yearMonthDuration_Stype.Deserialize(string input, out yearMonthDuration_Stype obj)
References SDC.yearMonthDuration_Stype.Deserialize, SDC.null.
static new yearMonthDuration_Stype SDC.yearMonthDuration_Stype.Deserialize(string input)
References SDC.null.
static yearMonthDuration_Stype SDC.yearMonthDuration_Stype.Deserialize(System.IO.Stream s)
References SDC.yearMonthDuration_Stype.Serializer.
static bool SDC.yearMonthDuration_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out yearMonthDuration_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an yearMonthDuration_Stype object
fileName string xml file to load and deserialize obj Output yearMonthDuration_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.yearMonthDuration_Stype.LoadFromFile.
static bool SDC.yearMonthDuration_Stype.LoadFromFile(string fileName, out yearMonthDuration_Stype obj, out System.Exception exception)
References SDC.yearMonthDuration_Stype.LoadFromFile.
static bool SDC.yearMonthDuration_Stype.LoadFromFile(string fileName, out yearMonthDuration_Stype obj)
References SDC.yearMonthDuration_Stype.LoadFromFile, SDC.null.
static yearMonthDuration_Stype SDC.yearMonthDuration_Stype.LoadFromFile(string fileName)
References SDC.yearMonthDuration_Stype.LoadFromFile.
static new yearMonthDuration_Stype SDC.yearMonthDuration_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.yearMonthDuration_Stype.Deserialize, SDC.null.
static bool SDC.yearMonthDuration_Stype.Deserialize(string input, out yearMonthDuration_Stype obj, out Exception exception)
Deserializes workflow markup into an yearMonthDuration_Stype object
input string workflow markup to deserialize obj Output yearMonthDuration_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.yearMonthDuration_Stype.Deserialize, SDC.null.
static bool SDC.yearMonthDuration_Stype.Deserialize(string input, out yearMonthDuration_Stype obj)
References SDC.yearMonthDuration_Stype.Deserialize, SDC.null.
static new yearMonthDuration_Stype SDC.yearMonthDuration_Stype.Deserialize(string input)
References SDC.null, SDC.yearMonthDuration_Stype.Serializer.
static yearMonthDuration_Stype SDC.yearMonthDuration_Stype.Deserialize(Stream s)
References SDC.yearMonthDuration_Stype.Serializer.
static bool SDC.yearMonthDuration_Stype.LoadFromFile(string fileName, out yearMonthDuration_Stype obj, out Exception exception)
Deserializes xml markup from file into an yearMonthDuration_Stype object
fileName string xml file to load and deserialize obj Output yearMonthDuration_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.yearMonthDuration_Stype.LoadFromFile, SDC.null.
static bool SDC.yearMonthDuration_Stype.LoadFromFile(string fileName, out yearMonthDuration_Stype obj)
References SDC.yearMonthDuration_Stype.LoadFromFile, SDC.null.
static new yearMonthDuration_Stype SDC.yearMonthDuration_Stype.LoadFromFile(string fileName)
References SDC.yearMonthDuration_Stype.Deserialize, SDC.null.