SDC::InputStr_ReturnStrListType
bool SDC.InputStr_ReturnStrListType._shouldSerializeuseDelimiter
Referenced by SDC.InputStr_ReturnStrListType.ShouldSerializeuseDelimiter.
StringFunctionsStrType SDC.InputStr_ReturnStrListType._inputStr
Referenced by SDC.InputStr_ReturnStrListType.ShouldSerializeInputStr.
System.Nullable<bool> SDC.InputStr_ReturnStrListType._useDelimiter
Referenced by SDC.InputStr_ReturnStrListType.ShouldSerializeuseDelimiter.
InputStr_ReturnStrListTypeDelimiter SDC.InputStr_ReturnStrListType._delimiter
XmlSerializer SDC.InputStr_ReturnStrListType.serializer
virtual StringFunctionsStrType SDC.InputStr_ReturnStrListType.InputStr
virtual bool SDC.InputStr_ReturnStrListType.useDelimiter
If a delimiter is not used, then any white space will delimit the list items. The default delimiter is a space.
virtual bool SDC.InputStr_ReturnStrListType.useDelimiterSpecified
virtual InputStr_ReturnStrListTypeDelimiter SDC.InputStr_ReturnStrListType.delimiter
XmlSerializer SDC.InputStr_ReturnStrListType.Serializer
Referenced by SDC.InputStr_ReturnStrListType.Deserialize.
SDC.InputStr_ReturnStrListType.InputStr_ReturnStrListType()
InputStr_ReturnStrListType class constructor
virtual bool SDC.InputStr_ReturnStrListType.ShouldSerializeuseDelimiter()
Test whether useDelimiter should be serialized
References SDC.InputStr_ReturnStrListType._shouldSerializeuseDelimiter, SDC.InputStr_ReturnStrListType._useDelimiter.
virtual bool SDC.InputStr_ReturnStrListType.ShouldSerializeInputStr()
Test whether InputStr should be serialized
References SDC.InputStr_ReturnStrListType._inputStr, SDC.null.
virtual string SDC.InputStr_ReturnStrListType.Serialize(System.Text.Encoding encoding)
Serializes current InputStr_ReturnStrListType object into an XML string
string XML value
virtual string SDC.InputStr_ReturnStrListType.Serialize()
Referenced by SDC.InputStr_ReturnStrListType.SaveToFile.
virtual bool SDC.InputStr_ReturnStrListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InputStr_ReturnStrListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InputStr_ReturnStrListType.SaveToFile.
virtual bool SDC.InputStr_ReturnStrListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.InputStr_ReturnStrListType.SaveToFile.
virtual void SDC.InputStr_ReturnStrListType.SaveToFile(string fileName)
References SDC.InputStr_ReturnStrListType.SaveToFile.
virtual void SDC.InputStr_ReturnStrListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InputStr_ReturnStrListType.Serialize.
static bool SDC.InputStr_ReturnStrListType.Deserialize(string input, out InputStr_ReturnStrListType obj, out System.Exception exception)
Deserializes workflow markup into an InputStr_ReturnStrListType object
input string workflow markup to deserialize obj Output InputStr_ReturnStrListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnStrListType.Deserialize, SDC.InputStr_ReturnStrListType.LoadFromFile.
static bool SDC.InputStr_ReturnStrListType.Deserialize(string input, out InputStr_ReturnStrListType obj)
References SDC.InputStr_ReturnStrListType.Deserialize, SDC.null.
static new InputStr_ReturnStrListType SDC.InputStr_ReturnStrListType.Deserialize(string input)
References SDC.null.
static InputStr_ReturnStrListType SDC.InputStr_ReturnStrListType.Deserialize(System.IO.Stream s)
References SDC.InputStr_ReturnStrListType.Serializer.
static bool SDC.InputStr_ReturnStrListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out InputStr_ReturnStrListType obj, out System.Exception exception)
Deserializes xml markup from file into an InputStr_ReturnStrListType object
fileName string xml file to load and deserialize obj Output InputStr_ReturnStrListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnStrListType.LoadFromFile.
static bool SDC.InputStr_ReturnStrListType.LoadFromFile(string fileName, out InputStr_ReturnStrListType obj, out System.Exception exception)
References SDC.InputStr_ReturnStrListType.LoadFromFile.
static bool SDC.InputStr_ReturnStrListType.LoadFromFile(string fileName, out InputStr_ReturnStrListType obj)
References SDC.InputStr_ReturnStrListType.LoadFromFile, SDC.null.
static InputStr_ReturnStrListType SDC.InputStr_ReturnStrListType.LoadFromFile(string fileName)
References SDC.InputStr_ReturnStrListType.LoadFromFile.
static new InputStr_ReturnStrListType SDC.InputStr_ReturnStrListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InputStr_ReturnStrListType.Deserialize, SDC.null.