SDC::gYearMonth_DEtype
string SDC.gYearMonth_DEtype::_minInclusive
string SDC.gYearMonth_DEtype::_maxInclusive
string SDC.gYearMonth_DEtype::_minExclusive
string SDC.gYearMonth_DEtype::_maxExclusive
string SDC.gYearMonth_DEtype::_mask
ObjectChangeTracker SDC.gYearMonth_DEtype.changeTrackerField
static XmlSerializer SDC.gYearMonth_DEtype::serializer
string SDC.gYearMonth_DEtype::minInclusive
Referenced by SDC.gYearMonth_DEtype.ShouldSerializeminInclusive.
string SDC.gYearMonth_DEtype::maxInclusive
Referenced by SDC.gYearMonth_DEtype.ShouldSerializemaxInclusive.
string SDC.gYearMonth_DEtype::minExclusive
Referenced by SDC.gYearMonth_DEtype.ShouldSerializeminExclusive.
string SDC.gYearMonth_DEtype::maxExclusive
Referenced by SDC.gYearMonth_DEtype.ShouldSerializemaxExclusive.
string SDC.gYearMonth_DEtype::mask
Referenced by SDC.gYearMonth_DEtype.ShouldSerializemask.
static XmlSerializer SDC.gYearMonth_DEtype::Serializer
Referenced by SDC.gYearMonth_DEtype.Deserialize.
ObjectChangeTracker SDC.gYearMonth_DEtype.ChangeTracker
SDC.gYearMonth_DEtype.gYearMonth_DEtype()
SDC.gYearMonth_DEtype.gYearMonth_DEtype(BaseType parentNode)
virtual bool SDC.gYearMonth_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.gYearMonth_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.gYearMonth_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.gYearMonth_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.gYearMonth_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.gYearMonth_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current gYearMonth_DEtype object into an XML string
string XML value
virtual string SDC.gYearMonth_DEtype.Serialize()
Referenced by SDC.gYearMonth_DEtype.SaveToFile.
virtual bool SDC.gYearMonth_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current gYearMonth_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.gYearMonth_DEtype.SaveToFile.
virtual bool SDC.gYearMonth_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.gYearMonth_DEtype.SaveToFile(string fileName)
virtual void SDC.gYearMonth_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.gYearMonth_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.gYearMonth_DEtype.minInclusive.
virtual bool SDC.gYearMonth_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.gYearMonth_DEtype.maxInclusive.
virtual bool SDC.gYearMonth_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.gYearMonth_DEtype.minExclusive.
virtual bool SDC.gYearMonth_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.gYearMonth_DEtype.maxExclusive.
virtual bool SDC.gYearMonth_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.gYearMonth_DEtype.mask.
virtual string SDC.gYearMonth_DEtype.Serialize()
Serializes current gYearMonth_DEtype object into an XML string
string XML value
virtual bool SDC.gYearMonth_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current gYearMonth_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.gYearMonth_DEtype.SaveToFile.
virtual void SDC.gYearMonth_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.gYearMonth_DEtype.Serialize.
virtual gYearMonth_DEtype SDC.gYearMonth_DEtype.Clone()
Create a clone of this gYearMonth_DEtype object
static bool SDC.gYearMonth_DEtype.Deserialize(string input, out gYearMonth_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an gYearMonth_DEtype object
input string workflow markup to deserialize obj Output gYearMonth_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gYearMonth_DEtype.Deserialize, SDC.gYearMonth_DEtype.LoadFromFile.
static bool SDC.gYearMonth_DEtype.Deserialize(string input, out gYearMonth_DEtype obj)
References SDC.null.
static new gYearMonth_DEtype SDC.gYearMonth_DEtype.Deserialize(string input)
References SDC.null.
static gYearMonth_DEtype SDC.gYearMonth_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.gYearMonth_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out gYearMonth_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an gYearMonth_DEtype object
fileName string xml file to load and deserialize obj Output gYearMonth_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gYearMonth_DEtype.LoadFromFile.
static bool SDC.gYearMonth_DEtype.LoadFromFile(string fileName, out gYearMonth_DEtype obj, out System.Exception exception)
static bool SDC.gYearMonth_DEtype.LoadFromFile(string fileName, out gYearMonth_DEtype obj)
References SDC.null.
static gYearMonth_DEtype SDC.gYearMonth_DEtype.LoadFromFile(string fileName)
static new gYearMonth_DEtype SDC.gYearMonth_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.gYearMonth_DEtype.Deserialize(string input, out gYearMonth_DEtype obj, out Exception exception)
Deserializes workflow markup into an gYearMonth_DEtype object
input string workflow markup to deserialize obj Output gYearMonth_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gYearMonth_DEtype.Deserialize, SDC.null.
static bool SDC.gYearMonth_DEtype.Deserialize(string input, out gYearMonth_DEtype obj)
References SDC.gYearMonth_DEtype.Deserialize, SDC.null.
static new gYearMonth_DEtype SDC.gYearMonth_DEtype.Deserialize(string input)
References SDC.null, SDC.gYearMonth_DEtype.Serializer.
static gYearMonth_DEtype SDC.gYearMonth_DEtype.Deserialize(Stream s)
References SDC.gYearMonth_DEtype.Serializer.
static bool SDC.gYearMonth_DEtype.LoadFromFile(string fileName, out gYearMonth_DEtype obj, out Exception exception)
Deserializes xml markup from file into an gYearMonth_DEtype object
fileName string xml file to load and deserialize obj Output gYearMonth_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gYearMonth_DEtype.LoadFromFile, SDC.null.
static bool SDC.gYearMonth_DEtype.LoadFromFile(string fileName, out gYearMonth_DEtype obj)
References SDC.gYearMonth_DEtype.LoadFromFile, SDC.null.
static new gYearMonth_DEtype SDC.gYearMonth_DEtype.LoadFromFile(string fileName)
References SDC.gYearMonth_DEtype.Deserialize, SDC.null.