SDC::duration_DEtype
string SDC.duration_DEtype::_minInclusive
string SDC.duration_DEtype::_maxInclusive
string SDC.duration_DEtype::_minExclusive
string SDC.duration_DEtype::_maxExclusive
string SDC.duration_DEtype::_mask
ObjectChangeTracker SDC.duration_DEtype.changeTrackerField
static XmlSerializer SDC.duration_DEtype::serializer
string SDC.duration_DEtype::minInclusive
Referenced by SDC.duration_DEtype.ShouldSerializeminInclusive.
string SDC.duration_DEtype::maxInclusive
Referenced by SDC.duration_DEtype.ShouldSerializemaxInclusive.
string SDC.duration_DEtype::minExclusive
Referenced by SDC.duration_DEtype.ShouldSerializeminExclusive.
string SDC.duration_DEtype::maxExclusive
Referenced by SDC.duration_DEtype.ShouldSerializemaxExclusive.
string SDC.duration_DEtype::mask
Referenced by SDC.duration_DEtype.ShouldSerializemask.
static XmlSerializer SDC.duration_DEtype::Serializer
Referenced by SDC.duration_DEtype.Deserialize.
ObjectChangeTracker SDC.duration_DEtype.ChangeTracker
SDC.duration_DEtype.duration_DEtype()
SDC.duration_DEtype.duration_DEtype(BaseType parentNode)
virtual bool SDC.duration_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.duration_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.duration_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.duration_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.duration_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.duration_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current duration_DEtype object into an XML string
string XML value
virtual string SDC.duration_DEtype.Serialize()
Referenced by SDC.duration_DEtype.SaveToFile.
virtual bool SDC.duration_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current duration_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.duration_DEtype.SaveToFile.
virtual bool SDC.duration_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.duration_DEtype.SaveToFile(string fileName)
virtual void SDC.duration_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.duration_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.duration_DEtype.minInclusive.
virtual bool SDC.duration_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.duration_DEtype.maxInclusive.
virtual bool SDC.duration_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.duration_DEtype.minExclusive.
virtual bool SDC.duration_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.duration_DEtype.maxExclusive.
virtual bool SDC.duration_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.duration_DEtype.mask.
virtual string SDC.duration_DEtype.Serialize()
Serializes current duration_DEtype object into an XML string
string XML value
virtual bool SDC.duration_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current duration_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.duration_DEtype.SaveToFile.
virtual void SDC.duration_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.duration_DEtype.Serialize.
virtual duration_DEtype SDC.duration_DEtype.Clone()
Create a clone of this duration_DEtype object
static bool SDC.duration_DEtype.Deserialize(string input, out duration_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an duration_DEtype object
input string workflow markup to deserialize obj Output duration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.duration_DEtype.Deserialize, SDC.duration_DEtype.LoadFromFile.
static bool SDC.duration_DEtype.Deserialize(string input, out duration_DEtype obj)
References SDC.null.
static new duration_DEtype SDC.duration_DEtype.Deserialize(string input)
References SDC.null.
static duration_DEtype SDC.duration_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.duration_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out duration_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an duration_DEtype object
fileName string xml file to load and deserialize obj Output duration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.duration_DEtype.LoadFromFile.
static bool SDC.duration_DEtype.LoadFromFile(string fileName, out duration_DEtype obj, out System.Exception exception)
static bool SDC.duration_DEtype.LoadFromFile(string fileName, out duration_DEtype obj)
References SDC.null.
static duration_DEtype SDC.duration_DEtype.LoadFromFile(string fileName)
static new duration_DEtype SDC.duration_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.duration_DEtype.Deserialize(string input, out duration_DEtype obj, out Exception exception)
Deserializes workflow markup into an duration_DEtype object
input string workflow markup to deserialize obj Output duration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.duration_DEtype.Deserialize, SDC.null.
static bool SDC.duration_DEtype.Deserialize(string input, out duration_DEtype obj)
References SDC.duration_DEtype.Deserialize, SDC.null.
static new duration_DEtype SDC.duration_DEtype.Deserialize(string input)
References SDC.null, SDC.duration_DEtype.Serializer.
static duration_DEtype SDC.duration_DEtype.Deserialize(Stream s)
References SDC.duration_DEtype.Serializer.
static bool SDC.duration_DEtype.LoadFromFile(string fileName, out duration_DEtype obj, out Exception exception)
Deserializes xml markup from file into an duration_DEtype object
fileName string xml file to load and deserialize obj Output duration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.duration_DEtype.LoadFromFile, SDC.null.
static bool SDC.duration_DEtype.LoadFromFile(string fileName, out duration_DEtype obj)
References SDC.duration_DEtype.LoadFromFile, SDC.null.
static new duration_DEtype SDC.duration_DEtype.LoadFromFile(string fileName)
References SDC.duration_DEtype.Deserialize, SDC.null.