SDC::yearMonthDuration_DEtype
string SDC.yearMonthDuration_DEtype::_minInclusive
string SDC.yearMonthDuration_DEtype::_maxInclusive
string SDC.yearMonthDuration_DEtype::_minExclusive
string SDC.yearMonthDuration_DEtype::_maxExclusive
string SDC.yearMonthDuration_DEtype::_mask
ObjectChangeTracker SDC.yearMonthDuration_DEtype.changeTrackerField
static XmlSerializer SDC.yearMonthDuration_DEtype::serializer
string SDC.yearMonthDuration_DEtype::minInclusive
Referenced by SDC.yearMonthDuration_DEtype.ShouldSerializeminInclusive.
string SDC.yearMonthDuration_DEtype::maxInclusive
Referenced by SDC.yearMonthDuration_DEtype.ShouldSerializemaxInclusive.
string SDC.yearMonthDuration_DEtype::minExclusive
Referenced by SDC.yearMonthDuration_DEtype.ShouldSerializeminExclusive.
string SDC.yearMonthDuration_DEtype::maxExclusive
Referenced by SDC.yearMonthDuration_DEtype.ShouldSerializemaxExclusive.
string SDC.yearMonthDuration_DEtype::mask
Referenced by SDC.yearMonthDuration_DEtype.ShouldSerializemask.
static XmlSerializer SDC.yearMonthDuration_DEtype::Serializer
Referenced by SDC.yearMonthDuration_DEtype.Deserialize.
ObjectChangeTracker SDC.yearMonthDuration_DEtype.ChangeTracker
SDC.yearMonthDuration_DEtype.yearMonthDuration_DEtype()
SDC.yearMonthDuration_DEtype.yearMonthDuration_DEtype(BaseType parentNode)
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.yearMonthDuration_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current yearMonthDuration_DEtype object into an XML string
string XML value
virtual string SDC.yearMonthDuration_DEtype.Serialize()
Referenced by SDC.yearMonthDuration_DEtype.SaveToFile.
virtual bool SDC.yearMonthDuration_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current yearMonthDuration_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.yearMonthDuration_DEtype.SaveToFile.
virtual bool SDC.yearMonthDuration_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.yearMonthDuration_DEtype.SaveToFile(string fileName)
virtual void SDC.yearMonthDuration_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.yearMonthDuration_DEtype.minInclusive.
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.yearMonthDuration_DEtype.maxInclusive.
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.yearMonthDuration_DEtype.minExclusive.
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.yearMonthDuration_DEtype.maxExclusive.
virtual bool SDC.yearMonthDuration_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.yearMonthDuration_DEtype.mask.
virtual string SDC.yearMonthDuration_DEtype.Serialize()
Serializes current yearMonthDuration_DEtype object into an XML string
string XML value
virtual bool SDC.yearMonthDuration_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current yearMonthDuration_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.yearMonthDuration_DEtype.SaveToFile.
virtual void SDC.yearMonthDuration_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.yearMonthDuration_DEtype.Serialize.
virtual yearMonthDuration_DEtype SDC.yearMonthDuration_DEtype.Clone()
Create a clone of this yearMonthDuration_DEtype object
static bool SDC.yearMonthDuration_DEtype.Deserialize(string input, out yearMonthDuration_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an yearMonthDuration_DEtype object
input string workflow markup to deserialize obj Output yearMonthDuration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.yearMonthDuration_DEtype.Deserialize, SDC.yearMonthDuration_DEtype.LoadFromFile.
static bool SDC.yearMonthDuration_DEtype.Deserialize(string input, out yearMonthDuration_DEtype obj)
References SDC.null.
static new yearMonthDuration_DEtype SDC.yearMonthDuration_DEtype.Deserialize(string input)
References SDC.null.
static yearMonthDuration_DEtype SDC.yearMonthDuration_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.yearMonthDuration_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out yearMonthDuration_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an yearMonthDuration_DEtype object
fileName string xml file to load and deserialize obj Output yearMonthDuration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.yearMonthDuration_DEtype.LoadFromFile.
static bool SDC.yearMonthDuration_DEtype.LoadFromFile(string fileName, out yearMonthDuration_DEtype obj, out System.Exception exception)
static bool SDC.yearMonthDuration_DEtype.LoadFromFile(string fileName, out yearMonthDuration_DEtype obj)
References SDC.null.
static yearMonthDuration_DEtype SDC.yearMonthDuration_DEtype.LoadFromFile(string fileName)
static new yearMonthDuration_DEtype SDC.yearMonthDuration_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.yearMonthDuration_DEtype.Deserialize(string input, out yearMonthDuration_DEtype obj, out Exception exception)
Deserializes workflow markup into an yearMonthDuration_DEtype object
input string workflow markup to deserialize obj Output yearMonthDuration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.yearMonthDuration_DEtype.Deserialize, SDC.null.
static bool SDC.yearMonthDuration_DEtype.Deserialize(string input, out yearMonthDuration_DEtype obj)
References SDC.yearMonthDuration_DEtype.Deserialize, SDC.null.
static new yearMonthDuration_DEtype SDC.yearMonthDuration_DEtype.Deserialize(string input)
References SDC.null, SDC.yearMonthDuration_DEtype.Serializer.
static yearMonthDuration_DEtype SDC.yearMonthDuration_DEtype.Deserialize(Stream s)
References SDC.yearMonthDuration_DEtype.Serializer.
static bool SDC.yearMonthDuration_DEtype.LoadFromFile(string fileName, out yearMonthDuration_DEtype obj, out Exception exception)
Deserializes xml markup from file into an yearMonthDuration_DEtype object
fileName string xml file to load and deserialize obj Output yearMonthDuration_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.yearMonthDuration_DEtype.LoadFromFile, SDC.null.
static bool SDC.yearMonthDuration_DEtype.LoadFromFile(string fileName, out yearMonthDuration_DEtype obj)
References SDC.yearMonthDuration_DEtype.LoadFromFile, SDC.null.
static new yearMonthDuration_DEtype SDC.yearMonthDuration_DEtype.LoadFromFile(string fileName)
References SDC.yearMonthDuration_DEtype.Deserialize, SDC.null.