SDC::integer_Stype
virtual decimal SDC.integer_Stype.valDec
+Replaced in original class: protected integer_Stype() { }
Added to support proper decimal set/get; Decimal is the best data type to match W3C integer. This will not work with XML serializer, bc decimal types always serialize trailing zeros, and trailing zeros are not allowed with integer types TODO: Need to truncate (or possibly round) any digits after the decimal point in the setter/getter For positive/negative etc integers, need to check the sign and throw error if incorrect. May want to throw errors for for min/max allowed values also - not sure about this) May need to import System.Numerics.dll to use BigInteger
string SDC.integer_Stype::val
Referenced by SDC.integer_Stype.ShouldSerializeval.
dtQuantEnum SDC.integer_Stype::quantEnum
static XmlSerializer SDC.integer_Stype::Serializer
Referenced by SDC.integer_Stype.Deserialize.
virtual decimal SDC.integer_Stype.val
ObjectChangeTracker SDC.integer_Stype.ChangeTracker
string SDC.integer_Stype::_val
dtQuantEnum SDC.integer_Stype::_quantEnum
Referenced by SDC.integer_Stype.integer_Stype.
decimal SDC.integer_Stype._val
ObjectChangeTracker SDC.integer_Stype.changeTrackerField
static XmlSerializer SDC.integer_Stype::serializer
SDC.integer_Stype.integer_Stype()
SDC.integer_Stype.integer_Stype(BaseType parentNode)
virtual bool SDC.integer_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.integer_Stype.val.
virtual string SDC.integer_Stype.Serialize(System.Text.Encoding encoding)
Serializes current integer_Stype object into an XML string
string XML value
virtual string SDC.integer_Stype.Serialize()
Referenced by SDC.integer_Stype.SaveToFile, SDC.integer_Stype.Serialize.
virtual bool SDC.integer_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current integer_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.integer_Stype.SaveToFile.
virtual bool SDC.integer_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.integer_Stype.SaveToFile.
virtual void SDC.integer_Stype.SaveToFile(string fileName)
References SDC.integer_Stype.SaveToFile.
virtual void SDC.integer_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.integer_Stype.Serialize.
virtual bool SDC.integer_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.null, SDC.integer_Stype.val.
virtual string SDC.integer_Stype.Serialize(System.Text.Encoding encoding)
Serializes current integer_Stype object into an XML string
string XML value
virtual string SDC.integer_Stype.Serialize()
References SDC.integer_Stype.Serialize.
virtual bool SDC.integer_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current integer_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.integer_Stype.SaveToFile.
virtual bool SDC.integer_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.integer_Stype.SaveToFile.
virtual void SDC.integer_Stype.SaveToFile(string fileName)
References SDC.integer_Stype.SaveToFile.
virtual void SDC.integer_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.integer_Stype.Serialize.
SDC.integer_Stype.integer_Stype()
integer_Stype class constructor
References SDC.integer_Stype._quantEnum.
virtual bool SDC.integer_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.integer_Stype.val.
virtual string SDC.integer_Stype.Serialize()
Serializes current integer_Stype object into an XML string
string XML value
virtual bool SDC.integer_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current integer_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.integer_Stype.SaveToFile.
virtual void SDC.integer_Stype.SaveToFile(string fileName)
References SDC.null, SDC.integer_Stype.Serialize.
virtual integer_Stype SDC.integer_Stype.Clone()
Create a clone of this integer_Stype object
static bool SDC.integer_Stype.Deserialize(string input, out integer_Stype obj, out System.Exception exception)
Deserializes workflow markup into an integer_Stype object
input string workflow markup to deserialize obj Output integer_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.integer_Stype.Deserialize, SDC.integer_Stype.LoadFromFile.
static bool SDC.integer_Stype.Deserialize(string input, out integer_Stype obj)
References SDC.integer_Stype.Deserialize, SDC.null.
static new integer_Stype SDC.integer_Stype.Deserialize(string input)
References SDC.null.
static integer_Stype SDC.integer_Stype.Deserialize(System.IO.Stream s)
References SDC.integer_Stype.Serializer.
static bool SDC.integer_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out integer_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an integer_Stype object
fileName string xml file to load and deserialize obj Output integer_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.integer_Stype.LoadFromFile.
static bool SDC.integer_Stype.LoadFromFile(string fileName, out integer_Stype obj, out System.Exception exception)
References SDC.integer_Stype.LoadFromFile.
static bool SDC.integer_Stype.LoadFromFile(string fileName, out integer_Stype obj)
References SDC.integer_Stype.LoadFromFile, SDC.null.
static integer_Stype SDC.integer_Stype.LoadFromFile(string fileName)
References SDC.integer_Stype.LoadFromFile.
static new integer_Stype SDC.integer_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.integer_Stype.Deserialize, SDC.null.
static bool SDC.integer_Stype.Deserialize(string input, out integer_Stype obj, out System.Exception exception)
Deserializes workflow markup into an integer_Stype object
input string workflow markup to deserialize obj Output integer_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.integer_Stype.Deserialize, SDC.null.
static bool SDC.integer_Stype.Deserialize(string input, out integer_Stype obj)
References SDC.integer_Stype.Deserialize, SDC.null.
static new integer_Stype SDC.integer_Stype.Deserialize(string input)
References SDC.null.
static integer_Stype SDC.integer_Stype.Deserialize(System.IO.Stream s)
References SDC.integer_Stype.Serializer.
static bool SDC.integer_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out integer_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an integer_Stype object
fileName string xml file to load and deserialize obj Output integer_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.integer_Stype.LoadFromFile, SDC.null.
static bool SDC.integer_Stype.LoadFromFile(string fileName, out integer_Stype obj, out System.Exception exception)
References SDC.integer_Stype.LoadFromFile.
static bool SDC.integer_Stype.LoadFromFile(string fileName, out integer_Stype obj)
References SDC.integer_Stype.LoadFromFile, SDC.null.
static integer_Stype SDC.integer_Stype.LoadFromFile(string fileName)
References SDC.integer_Stype.LoadFromFile.
static new integer_Stype SDC.integer_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.integer_Stype.Deserialize, SDC.null.
static bool SDC.integer_Stype.Deserialize(string input, out integer_Stype obj, out Exception exception)
Deserializes workflow markup into an integer_Stype object
input string workflow markup to deserialize obj Output integer_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.integer_Stype.Deserialize, SDC.null.
static bool SDC.integer_Stype.Deserialize(string input, out integer_Stype obj)
References SDC.integer_Stype.Deserialize, SDC.null.
static new integer_Stype SDC.integer_Stype.Deserialize(string input)
References SDC.null, SDC.integer_Stype.Serializer.
static integer_Stype SDC.integer_Stype.Deserialize(Stream s)
References SDC.integer_Stype.Serializer.
static bool SDC.integer_Stype.LoadFromFile(string fileName, out integer_Stype obj, out Exception exception)
Deserializes xml markup from file into an integer_Stype object
fileName string xml file to load and deserialize obj Output integer_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.integer_Stype.LoadFromFile, SDC.null.
static bool SDC.integer_Stype.LoadFromFile(string fileName, out integer_Stype obj)
References SDC.integer_Stype.LoadFromFile, SDC.null.
static new integer_Stype SDC.integer_Stype.LoadFromFile(string fileName)
References SDC.integer_Stype.Deserialize, SDC.null.