SDC::decimal_DEtype
bool SDC.decimal_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.decimal_DEtype.ShouldSerializemaxExclusive.
bool SDC.decimal_DEtype::_shouldSerializeminExclusive
Referenced by SDC.decimal_DEtype.ShouldSerializeminExclusive.
bool SDC.decimal_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.decimal_DEtype.ShouldSerializemaxInclusive.
bool SDC.decimal_DEtype::_shouldSerializeminInclusive
Referenced by SDC.decimal_DEtype.ShouldSerializeminInclusive.
System Nullable< decimal > SDC.decimal_DEtype::_minInclusive
Referenced by SDC.decimal_DEtype.ShouldSerializeminInclusive.
System Nullable< decimal > SDC.decimal_DEtype::_maxInclusive
Referenced by SDC.decimal_DEtype.ShouldSerializemaxInclusive.
System Nullable< decimal > SDC.decimal_DEtype::_minExclusive
Referenced by SDC.decimal_DEtype.ShouldSerializeminExclusive.
System Nullable< decimal > SDC.decimal_DEtype::_maxExclusive
Referenced by SDC.decimal_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.decimal_DEtype::_fractionDigits
System Nullable< byte > SDC.decimal_DEtype::_totalDigits
string SDC.decimal_DEtype::_mask
ObjectChangeTracker SDC.decimal_DEtype.changeTrackerField
static XmlSerializer SDC.decimal_DEtype::serializer
decimal SDC.decimal_DEtype::minInclusive
bool SDC.decimal_DEtype::minInclusiveSpecified
decimal SDC.decimal_DEtype::maxInclusive
bool SDC.decimal_DEtype::maxInclusiveSpecified
decimal SDC.decimal_DEtype::minExclusive
bool SDC.decimal_DEtype::minExclusiveSpecified
decimal SDC.decimal_DEtype::maxExclusive
bool SDC.decimal_DEtype::maxExclusiveSpecified
byte SDC.decimal_DEtype::fractionDigits
bool SDC.decimal_DEtype::fractionDigitsSpecified
byte SDC.decimal_DEtype::totalDigits
bool SDC.decimal_DEtype::totalDigitsSpecified
string SDC.decimal_DEtype::mask
Referenced by SDC.decimal_DEtype.ShouldSerializemask.
static XmlSerializer SDC.decimal_DEtype::Serializer
Referenced by SDC.decimal_DEtype.Deserialize.
ObjectChangeTracker SDC.decimal_DEtype.ChangeTracker
SDC.decimal_DEtype.decimal_DEtype()
SDC.decimal_DEtype.decimal_DEtype(BaseType parentNode)
virtual bool SDC.decimal_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.decimal.
virtual bool SDC.decimal_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.decimal.
virtual bool SDC.decimal_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.decimal.
virtual bool SDC.decimal_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.decimal.
virtual bool SDC.decimal_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.decimal_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current decimal_DEtype object into an XML string
string XML value
virtual string SDC.decimal_DEtype.Serialize()
Referenced by SDC.decimal_DEtype.SaveToFile.
virtual bool SDC.decimal_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current decimal_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.decimal_DEtype.SaveToFile.
virtual bool SDC.decimal_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.decimal_DEtype.SaveToFile(string fileName)
virtual void SDC.decimal_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.decimal_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.decimal_DEtype._minInclusive, SDC.decimal_DEtype._shouldSerializeminInclusive, SDC.decimal.
virtual bool SDC.decimal_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.decimal_DEtype._maxInclusive, SDC.decimal_DEtype._shouldSerializemaxInclusive, SDC.decimal.
virtual bool SDC.decimal_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.decimal_DEtype._minExclusive, SDC.decimal_DEtype._shouldSerializeminExclusive, SDC.decimal.
virtual bool SDC.decimal_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.decimal_DEtype._maxExclusive, SDC.decimal_DEtype._shouldSerializemaxExclusive, SDC.decimal.
virtual bool SDC.decimal_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.decimal_DEtype.mask.
virtual string SDC.decimal_DEtype.Serialize()
Serializes current decimal_DEtype object into an XML string
string XML value
virtual bool SDC.decimal_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current decimal_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.decimal_DEtype.SaveToFile.
virtual void SDC.decimal_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.decimal_DEtype.Serialize.
virtual decimal_DEtype SDC.decimal_DEtype.Clone()
Create a clone of this decimal_DEtype object
static bool SDC.decimal_DEtype.Deserialize(string input, out decimal_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an decimal_DEtype object
input string workflow markup to deserialize obj Output decimal_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.decimal_DEtype.Deserialize, SDC.decimal_DEtype.LoadFromFile.
static bool SDC.decimal_DEtype.Deserialize(string input, out decimal_DEtype obj)
References SDC.null.
static new decimal_DEtype SDC.decimal_DEtype.Deserialize(string input)
References SDC.null.
static decimal_DEtype SDC.decimal_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.decimal_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out decimal_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an decimal_DEtype object
fileName string xml file to load and deserialize obj Output decimal_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.decimal_DEtype.LoadFromFile.
static bool SDC.decimal_DEtype.LoadFromFile(string fileName, out decimal_DEtype obj, out System.Exception exception)
static bool SDC.decimal_DEtype.LoadFromFile(string fileName, out decimal_DEtype obj)
References SDC.null.
static decimal_DEtype SDC.decimal_DEtype.LoadFromFile(string fileName)
static new decimal_DEtype SDC.decimal_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.decimal_DEtype.Deserialize(string input, out decimal_DEtype obj, out Exception exception)
Deserializes workflow markup into an decimal_DEtype object
input string workflow markup to deserialize obj Output decimal_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.decimal_DEtype.Deserialize, SDC.null.
static bool SDC.decimal_DEtype.Deserialize(string input, out decimal_DEtype obj)
References SDC.decimal_DEtype.Deserialize, SDC.null.
static new decimal_DEtype SDC.decimal_DEtype.Deserialize(string input)
References SDC.null, SDC.decimal_DEtype.Serializer.
static decimal_DEtype SDC.decimal_DEtype.Deserialize(Stream s)
References SDC.decimal_DEtype.Serializer.
static bool SDC.decimal_DEtype.LoadFromFile(string fileName, out decimal_DEtype obj, out Exception exception)
Deserializes xml markup from file into an decimal_DEtype object
fileName string xml file to load and deserialize obj Output decimal_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.decimal_DEtype.LoadFromFile, SDC.null.
static bool SDC.decimal_DEtype.LoadFromFile(string fileName, out decimal_DEtype obj)
References SDC.decimal_DEtype.LoadFromFile, SDC.null.
static new decimal_DEtype SDC.decimal_DEtype.LoadFromFile(string fileName)
References SDC.decimal_DEtype.Deserialize, SDC.null.