SDC::MinInclusiveType
string SDC.MinInclusiveType._val
ObjectChangeTracker SDC.MinInclusiveType.changeTrackerField
XmlSerializer SDC.MinInclusiveType.serializer
virtual string SDC.MinInclusiveType.val
Referenced by SDC.MinInclusiveType.ShouldSerializeval.
XmlSerializer SDC.MinInclusiveType.Serializer
Referenced by SDC.MinInclusiveType.Deserialize.
ObjectChangeTracker SDC.MinInclusiveType.ChangeTracker
SDC.MinInclusiveType.MinInclusiveType()
virtual bool SDC.MinInclusiveType.ShouldSerializeval()
Test whether val should be serialized
References SDC.MinInclusiveType.val.
virtual string SDC.MinInclusiveType.Serialize()
Serializes current MinInclusiveType object into an XML string
string XML value
Referenced by SDC.MinInclusiveType.SaveToFile.
virtual bool SDC.MinInclusiveType.SaveToFile(string fileName, out Exception exception)
Serializes current MinInclusiveType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.MinInclusiveType.SaveToFile(string fileName)
References SDC.null, SDC.MinInclusiveType.Serialize.
virtual MinInclusiveType SDC.MinInclusiveType.Clone()
Create a clone of this MinInclusiveType object
static bool SDC.MinInclusiveType.Deserialize(string input, out MinInclusiveType obj, out Exception exception)
Deserializes workflow markup into an MinInclusiveType object
input string workflow markup to deserialize obj Output MinInclusiveType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.MinInclusiveType.Deserialize, SDC.MinInclusiveType.LoadFromFile.
static bool SDC.MinInclusiveType.Deserialize(string input, out MinInclusiveType obj)
References SDC.MinInclusiveType.Deserialize, SDC.null.
static new MinInclusiveType SDC.MinInclusiveType.Deserialize(string input)
References SDC.null, SDC.MinInclusiveType.Serializer.
static MinInclusiveType SDC.MinInclusiveType.Deserialize(Stream s)
References SDC.MinInclusiveType.Serializer.
static bool SDC.MinInclusiveType.LoadFromFile(string fileName, out MinInclusiveType obj, out Exception exception)
Deserializes xml markup from file into an MinInclusiveType object
fileName string xml file to load and deserialize obj Output MinInclusiveType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.MinInclusiveType.LoadFromFile.
static bool SDC.MinInclusiveType.LoadFromFile(string fileName, out MinInclusiveType obj)
References SDC.MinInclusiveType.LoadFromFile, SDC.null.
static new MinInclusiveType SDC.MinInclusiveType.LoadFromFile(string fileName)
References SDC.MinInclusiveType.Deserialize, SDC.null.