SDC::unsignedInt_Stype
bool SDC.unsignedInt_Stype::_shouldSerializeval
Referenced by SDC.unsignedInt_Stype.ShouldSerializeval.
System Nullable< uint > SDC.unsignedInt_Stype::_val
Referenced by SDC.unsignedInt_Stype.ShouldSerializeval.
dtQuantEnum SDC.unsignedInt_Stype::_quantEnum
Referenced by SDC.unsignedInt_Stype.unsignedInt_Stype.
ObjectChangeTracker SDC.unsignedInt_Stype.changeTrackerField
static XmlSerializer SDC.unsignedInt_Stype::serializer
uint SDC.unsignedInt_Stype::val
bool SDC.unsignedInt_Stype::valSpecified
dtQuantEnum SDC.unsignedInt_Stype::quantEnum
static XmlSerializer SDC.unsignedInt_Stype::Serializer
Referenced by SDC.unsignedInt_Stype.Deserialize.
ObjectChangeTracker SDC.unsignedInt_Stype.ChangeTracker
SDC.unsignedInt_Stype.unsignedInt_Stype()
SDC.unsignedInt_Stype.unsignedInt_Stype(BaseType parentNode)
virtual bool SDC.unsignedInt_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.unsignedInt_Stype._shouldSerializeval, SDC.unsignedInt_Stype._val.
virtual string SDC.unsignedInt_Stype.Serialize(System.Text.Encoding encoding)
Serializes current unsignedInt_Stype object into an XML string
string XML value
virtual string SDC.unsignedInt_Stype.Serialize()
Referenced by SDC.unsignedInt_Stype.SaveToFile.
virtual bool SDC.unsignedInt_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current unsignedInt_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.unsignedInt_Stype.SaveToFile.
virtual bool SDC.unsignedInt_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.unsignedInt_Stype.SaveToFile.
virtual void SDC.unsignedInt_Stype.SaveToFile(string fileName)
References SDC.unsignedInt_Stype.SaveToFile.
virtual void SDC.unsignedInt_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.unsignedInt_Stype.Serialize.
SDC.unsignedInt_Stype.unsignedInt_Stype()
unsignedInt_Stype class constructor
References SDC.unsignedInt_Stype._quantEnum.
virtual bool SDC.unsignedInt_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.unsignedInt_Stype._shouldSerializeval, SDC.unsignedInt_Stype._val.
virtual string SDC.unsignedInt_Stype.Serialize()
Serializes current unsignedInt_Stype object into an XML string
string XML value
virtual bool SDC.unsignedInt_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current unsignedInt_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.unsignedInt_Stype.SaveToFile.
virtual void SDC.unsignedInt_Stype.SaveToFile(string fileName)
References SDC.null, SDC.unsignedInt_Stype.Serialize.
virtual unsignedInt_Stype SDC.unsignedInt_Stype.Clone()
Create a clone of this unsignedInt_Stype object
static bool SDC.unsignedInt_Stype.Deserialize(string input, out unsignedInt_Stype obj, out System.Exception exception)
Deserializes workflow markup into an unsignedInt_Stype object
input string workflow markup to deserialize obj Output unsignedInt_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedInt_Stype.Deserialize, SDC.unsignedInt_Stype.LoadFromFile.
static bool SDC.unsignedInt_Stype.Deserialize(string input, out unsignedInt_Stype obj)
References SDC.unsignedInt_Stype.Deserialize, SDC.null.
static new unsignedInt_Stype SDC.unsignedInt_Stype.Deserialize(string input)
References SDC.null.
static unsignedInt_Stype SDC.unsignedInt_Stype.Deserialize(System.IO.Stream s)
References SDC.unsignedInt_Stype.Serializer.
static bool SDC.unsignedInt_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out unsignedInt_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an unsignedInt_Stype object
fileName string xml file to load and deserialize obj Output unsignedInt_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedInt_Stype.LoadFromFile.
static bool SDC.unsignedInt_Stype.LoadFromFile(string fileName, out unsignedInt_Stype obj, out System.Exception exception)
References SDC.unsignedInt_Stype.LoadFromFile.
static bool SDC.unsignedInt_Stype.LoadFromFile(string fileName, out unsignedInt_Stype obj)
References SDC.unsignedInt_Stype.LoadFromFile, SDC.null.
static unsignedInt_Stype SDC.unsignedInt_Stype.LoadFromFile(string fileName)
References SDC.unsignedInt_Stype.LoadFromFile.
static new unsignedInt_Stype SDC.unsignedInt_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.unsignedInt_Stype.Deserialize, SDC.null.
static bool SDC.unsignedInt_Stype.Deserialize(string input, out unsignedInt_Stype obj, out Exception exception)
Deserializes workflow markup into an unsignedInt_Stype object
input string workflow markup to deserialize obj Output unsignedInt_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedInt_Stype.Deserialize, SDC.null.
static bool SDC.unsignedInt_Stype.Deserialize(string input, out unsignedInt_Stype obj)
References SDC.unsignedInt_Stype.Deserialize, SDC.null.
static new unsignedInt_Stype SDC.unsignedInt_Stype.Deserialize(string input)
References SDC.null, SDC.unsignedInt_Stype.Serializer.
static unsignedInt_Stype SDC.unsignedInt_Stype.Deserialize(Stream s)
References SDC.unsignedInt_Stype.Serializer.
static bool SDC.unsignedInt_Stype.LoadFromFile(string fileName, out unsignedInt_Stype obj, out Exception exception)
Deserializes xml markup from file into an unsignedInt_Stype object
fileName string xml file to load and deserialize obj Output unsignedInt_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedInt_Stype.LoadFromFile, SDC.null.
static bool SDC.unsignedInt_Stype.LoadFromFile(string fileName, out unsignedInt_Stype obj)
References SDC.unsignedInt_Stype.LoadFromFile, SDC.null.
static new unsignedInt_Stype SDC.unsignedInt_Stype.LoadFromFile(string fileName)
References SDC.unsignedInt_Stype.Deserialize, SDC.null.