SDC::WebServiceType
BindingList<RichTextType> SDC.WebServiceType._otherText
anyURI_Stype SDC.WebServiceType._uRI
Referenced by SDC.WebServiceType.ShouldSerializeURI.
RichTextType SDC.WebServiceType._security
Referenced by SDC.WebServiceType.ShouldSerializeSecurity.
BindingList<ParameterType> SDC.WebServiceType._parameter
ObjectChangeTracker SDC.WebServiceType.changeTrackerField
XmlSerializer SDC.WebServiceType.serializer
virtual BindingList<RichTextType> SDC.WebServiceType.OtherText
OtherText is any type of secondary text that is associated with any form item (e.g., section, question, list item) in any context. The Description context is specified by the attribute. Examples of Description values may include: -alternate language representations, -explanations for the user of the form, -tooltips, -pop-up help, -outlining (such as question numbering)
The enumerations must be defined and documented for the particular use case, and are currently out of scope in this schema definition.
virtual anyURI_Stype SDC.WebServiceType.URI
THe URI/URL may use the parameter list and transmit the item name, property and value for each parameter. The URI must understand the parameters and return an appropriate repsonse of the correct data type. Guidelines for URI/URI construction syntax will be defined external to this Schema.
virtual RichTextType SDC.WebServiceType.Security
Information about securly accessing the web service. More detailed service patterns may be required.
virtual BindingList<ParameterType> SDC.WebServiceType.Parameter
Parameters are named FormDesign items which have property values that need to be supplied to a scripted function or a web service URI.
XmlSerializer SDC.WebServiceType.Serializer
Referenced by SDC.WebServiceType.Deserialize.
ObjectChangeTracker SDC.WebServiceType.ChangeTracker
SDC.WebServiceType.WebServiceType()
virtual bool SDC.WebServiceType.ShouldSerializeURI()
Test whether URI should be serialized
References SDC.WebServiceType._uRI, SDC.null.
virtual bool SDC.WebServiceType.ShouldSerializeSecurity()
Test whether Security should be serialized
References SDC.WebServiceType._security, SDC.null.
virtual string SDC.WebServiceType.Serialize()
Serializes current WebServiceType object into an XML string
string XML value
Referenced by SDC.WebServiceType.SaveToFile.
virtual bool SDC.WebServiceType.SaveToFile(string fileName, out Exception exception)
Serializes current WebServiceType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.WebServiceType.SaveToFile(string fileName)
References SDC.null, SDC.WebServiceType.Serialize.
virtual WebServiceType SDC.WebServiceType.Clone()
Create a clone of this WebServiceType object
static bool SDC.WebServiceType.Deserialize(string input, out WebServiceType obj, out Exception exception)
Deserializes workflow markup into an WebServiceType object
input string workflow markup to deserialize obj Output WebServiceType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.WebServiceType.Deserialize, SDC.WebServiceType.LoadFromFile.
static bool SDC.WebServiceType.Deserialize(string input, out WebServiceType obj)
References SDC.WebServiceType.Deserialize, SDC.null.
static new WebServiceType SDC.WebServiceType.Deserialize(string input)
References SDC.null, SDC.WebServiceType.Serializer.
static WebServiceType SDC.WebServiceType.Deserialize(Stream s)
References SDC.WebServiceType.Serializer.
static bool SDC.WebServiceType.LoadFromFile(string fileName, out WebServiceType obj, out Exception exception)
Deserializes xml markup from file into an WebServiceType object
fileName string xml file to load and deserialize obj Output WebServiceType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.WebServiceType.LoadFromFile.
static bool SDC.WebServiceType.LoadFromFile(string fileName, out WebServiceType obj)
References SDC.WebServiceType.LoadFromFile, SDC.null.
static new WebServiceType SDC.WebServiceType.LoadFromFile(string fileName)
References SDC.WebServiceType.Deserialize, SDC.null.