SDC::gMonthDay_DEtype
string SDC.gMonthDay_DEtype::_minInclusive
string SDC.gMonthDay_DEtype::_maxInclusive
string SDC.gMonthDay_DEtype::_minExclusive
string SDC.gMonthDay_DEtype::_maxExclusive
string SDC.gMonthDay_DEtype::_mask
ObjectChangeTracker SDC.gMonthDay_DEtype.changeTrackerField
static XmlSerializer SDC.gMonthDay_DEtype::serializer
string SDC.gMonthDay_DEtype::minInclusive
Referenced by SDC.gMonthDay_DEtype.ShouldSerializeminInclusive.
string SDC.gMonthDay_DEtype::maxInclusive
Referenced by SDC.gMonthDay_DEtype.ShouldSerializemaxInclusive.
string SDC.gMonthDay_DEtype::minExclusive
Referenced by SDC.gMonthDay_DEtype.ShouldSerializeminExclusive.
string SDC.gMonthDay_DEtype::maxExclusive
Referenced by SDC.gMonthDay_DEtype.ShouldSerializemaxExclusive.
string SDC.gMonthDay_DEtype::mask
Referenced by SDC.gMonthDay_DEtype.ShouldSerializemask.
static XmlSerializer SDC.gMonthDay_DEtype::Serializer
Referenced by SDC.gMonthDay_DEtype.Deserialize.
ObjectChangeTracker SDC.gMonthDay_DEtype.ChangeTracker
SDC.gMonthDay_DEtype.gMonthDay_DEtype()
SDC.gMonthDay_DEtype.gMonthDay_DEtype(BaseType parentNode)
virtual bool SDC.gMonthDay_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.gMonthDay_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.gMonthDay_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.gMonthDay_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.gMonthDay_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.gMonthDay_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current gMonthDay_DEtype object into an XML string
string XML value
virtual string SDC.gMonthDay_DEtype.Serialize()
Referenced by SDC.gMonthDay_DEtype.SaveToFile.
virtual bool SDC.gMonthDay_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current gMonthDay_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.gMonthDay_DEtype.SaveToFile.
virtual bool SDC.gMonthDay_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.gMonthDay_DEtype.SaveToFile(string fileName)
virtual void SDC.gMonthDay_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.gMonthDay_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.gMonthDay_DEtype.minInclusive.
virtual bool SDC.gMonthDay_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.gMonthDay_DEtype.maxInclusive.
virtual bool SDC.gMonthDay_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.gMonthDay_DEtype.minExclusive.
virtual bool SDC.gMonthDay_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.gMonthDay_DEtype.maxExclusive.
virtual bool SDC.gMonthDay_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.gMonthDay_DEtype.mask.
virtual string SDC.gMonthDay_DEtype.Serialize()
Serializes current gMonthDay_DEtype object into an XML string
string XML value
virtual bool SDC.gMonthDay_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current gMonthDay_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.gMonthDay_DEtype.SaveToFile.
virtual void SDC.gMonthDay_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.gMonthDay_DEtype.Serialize.
virtual gMonthDay_DEtype SDC.gMonthDay_DEtype.Clone()
Create a clone of this gMonthDay_DEtype object
static bool SDC.gMonthDay_DEtype.Deserialize(string input, out gMonthDay_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an gMonthDay_DEtype object
input string workflow markup to deserialize obj Output gMonthDay_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gMonthDay_DEtype.Deserialize, SDC.gMonthDay_DEtype.LoadFromFile.
static bool SDC.gMonthDay_DEtype.Deserialize(string input, out gMonthDay_DEtype obj)
References SDC.null.
static new gMonthDay_DEtype SDC.gMonthDay_DEtype.Deserialize(string input)
References SDC.null.
static gMonthDay_DEtype SDC.gMonthDay_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.gMonthDay_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out gMonthDay_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an gMonthDay_DEtype object
fileName string xml file to load and deserialize obj Output gMonthDay_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.gMonthDay_DEtype.LoadFromFile.
static bool SDC.gMonthDay_DEtype.LoadFromFile(string fileName, out gMonthDay_DEtype obj, out System.Exception exception)
static bool SDC.gMonthDay_DEtype.LoadFromFile(string fileName, out gMonthDay_DEtype obj)
References SDC.null.
static gMonthDay_DEtype SDC.gMonthDay_DEtype.LoadFromFile(string fileName)
static new gMonthDay_DEtype SDC.gMonthDay_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.gMonthDay_DEtype.Deserialize(string input, out gMonthDay_DEtype obj, out Exception exception)
Deserializes workflow markup into an gMonthDay_DEtype object
input string workflow markup to deserialize obj Output gMonthDay_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gMonthDay_DEtype.Deserialize, SDC.null.
static bool SDC.gMonthDay_DEtype.Deserialize(string input, out gMonthDay_DEtype obj)
References SDC.gMonthDay_DEtype.Deserialize, SDC.null.
static new gMonthDay_DEtype SDC.gMonthDay_DEtype.Deserialize(string input)
References SDC.null, SDC.gMonthDay_DEtype.Serializer.
static gMonthDay_DEtype SDC.gMonthDay_DEtype.Deserialize(Stream s)
References SDC.gMonthDay_DEtype.Serializer.
static bool SDC.gMonthDay_DEtype.LoadFromFile(string fileName, out gMonthDay_DEtype obj, out Exception exception)
Deserializes xml markup from file into an gMonthDay_DEtype object
fileName string xml file to load and deserialize obj Output gMonthDay_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.gMonthDay_DEtype.LoadFromFile, SDC.null.
static bool SDC.gMonthDay_DEtype.LoadFromFile(string fileName, out gMonthDay_DEtype obj)
References SDC.gMonthDay_DEtype.LoadFromFile, SDC.null.
static new gMonthDay_DEtype SDC.gMonthDay_DEtype.LoadFromFile(string fileName)
References SDC.gMonthDay_DEtype.Deserialize, SDC.null.