SDC::ChangeType
TargetItemIDType SDC.ChangeType::_targetItemID
Referenced by SDC.ChangeType.ShouldSerializeTargetItemID.
TargetItemNameType SDC.ChangeType::_targetItemName
Referenced by SDC.ChangeType.ShouldSerializeTargetItemName.
TargetItemXPathType SDC.ChangeType::_targetItemXPath
Referenced by SDC.ChangeType.ShouldSerializeTargetItemXPath.
DataTypes_SType SDC.ChangeType::_newValue
Referenced by SDC.ChangeType.ShouldSerializeNewValue.
ObjectChangeTracker SDC.ChangeType.changeTrackerField
static XmlSerializer SDC.ChangeType::serializer
TargetItemIDType SDC.ChangeType::TargetItemID
TargetItemNameType SDC.ChangeType::TargetItemName
TargetItemXPathType SDC.ChangeType::TargetItemXPath
DataTypes_SType SDC.ChangeType::NewValue
The new value that the targeted item's content is set to.
static XmlSerializer SDC.ChangeType::Serializer
Referenced by SDC.ChangeType.Deserialize.
ObjectChangeTracker SDC.ChangeType.ChangeTracker
virtual bool SDC.ChangeType.ShouldSerializeTargetItemID()
Test whether TargetItemID should be serialized
References SDC.null.
virtual bool SDC.ChangeType.ShouldSerializeTargetItemName()
Test whether TargetItemName should be serialized
References SDC.null.
virtual bool SDC.ChangeType.ShouldSerializeTargetItemXPath()
Test whether TargetItemXPath should be serialized
References SDC.null.
virtual bool SDC.ChangeType.ShouldSerializeNewValue()
Test whether NewValue should be serialized
References SDC.null.
virtual string SDC.ChangeType.Serialize(System.Text.Encoding encoding)
Serializes current ChangeType object into an XML string
string XML value
virtual string SDC.ChangeType.Serialize()
Referenced by SDC.ChangeType.SaveToFile.
virtual bool SDC.ChangeType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ChangeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ChangeType.SaveToFile.
virtual bool SDC.ChangeType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ChangeType.SaveToFile(string fileName)
virtual void SDC.ChangeType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ChangeType.ShouldSerializeTargetItemID()
Test whether TargetItemID should be serialized
References SDC.ChangeType._targetItemID, SDC.null.
virtual bool SDC.ChangeType.ShouldSerializeTargetItemName()
Test whether TargetItemName should be serialized
References SDC.ChangeType._targetItemName, SDC.null.
virtual bool SDC.ChangeType.ShouldSerializeTargetItemXPath()
Test whether TargetItemXPath should be serialized
References SDC.ChangeType._targetItemXPath, SDC.null.
virtual bool SDC.ChangeType.ShouldSerializeNewValue()
Test whether NewValue should be serialized
References SDC.ChangeType._newValue, SDC.null.
virtual string SDC.ChangeType.Serialize()
Serializes current ChangeType object into an XML string
string XML value
virtual bool SDC.ChangeType.SaveToFile(string fileName, out Exception exception)
Serializes current ChangeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ChangeType.SaveToFile.
virtual void SDC.ChangeType.SaveToFile(string fileName)
References SDC.null, SDC.ChangeType.Serialize.
virtual ChangeType SDC.ChangeType.Clone()
Create a clone of this ChangeType object
static bool SDC.ChangeType.Deserialize(string input, out ChangeType obj, out System.Exception exception)
Deserializes workflow markup into an ChangeType object
input string workflow markup to deserialize obj Output ChangeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangeType.Deserialize, SDC.ChangeType.LoadFromFile.
static bool SDC.ChangeType.Deserialize(string input, out ChangeType obj)
References SDC.null.
static new ChangeType SDC.ChangeType.Deserialize(string input)
References SDC.null.
static ChangeType SDC.ChangeType.Deserialize(System.IO.Stream s)
static bool SDC.ChangeType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ChangeType obj, out System.Exception exception)
Deserializes xml markup from file into an ChangeType object
fileName string xml file to load and deserialize obj Output ChangeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangeType.LoadFromFile.
static bool SDC.ChangeType.LoadFromFile(string fileName, out ChangeType obj, out System.Exception exception)
static bool SDC.ChangeType.LoadFromFile(string fileName, out ChangeType obj)
References SDC.null.
static ChangeType SDC.ChangeType.LoadFromFile(string fileName)
static new ChangeType SDC.ChangeType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ChangeType.Deserialize(string input, out ChangeType obj, out Exception exception)
Deserializes workflow markup into an ChangeType object
input string workflow markup to deserialize obj Output ChangeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChangeType.Deserialize, SDC.null.
static bool SDC.ChangeType.Deserialize(string input, out ChangeType obj)
References SDC.ChangeType.Deserialize, SDC.null.
static new ChangeType SDC.ChangeType.Deserialize(string input)
References SDC.null, SDC.ChangeType.Serializer.
static ChangeType SDC.ChangeType.Deserialize(Stream s)
References SDC.ChangeType.Serializer.
static bool SDC.ChangeType.LoadFromFile(string fileName, out ChangeType obj, out Exception exception)
Deserializes xml markup from file into an ChangeType object
fileName string xml file to load and deserialize obj Output ChangeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ChangeType.LoadFromFile, SDC.null.
static bool SDC.ChangeType.LoadFromFile(string fileName, out ChangeType obj)
References SDC.ChangeType.LoadFromFile, SDC.null.
static new ChangeType SDC.ChangeType.LoadFromFile(string fileName)
References SDC.ChangeType.Deserialize, SDC.null.