SDC::long_DEtype
bool SDC.long_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.long_DEtype.ShouldSerializemaxExclusive.
bool SDC.long_DEtype::_shouldSerializeminExclusive
Referenced by SDC.long_DEtype.ShouldSerializeminExclusive.
bool SDC.long_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.long_DEtype.ShouldSerializemaxInclusive.
bool SDC.long_DEtype::_shouldSerializeminInclusive
Referenced by SDC.long_DEtype.ShouldSerializeminInclusive.
System Nullable< long > SDC.long_DEtype::_minInclusive
Referenced by SDC.long_DEtype.ShouldSerializeminInclusive.
System Nullable< long > SDC.long_DEtype::_maxInclusive
Referenced by SDC.long_DEtype.ShouldSerializemaxInclusive.
System Nullable< long > SDC.long_DEtype::_minExclusive
Referenced by SDC.long_DEtype.ShouldSerializeminExclusive.
System Nullable< long > SDC.long_DEtype::_maxExclusive
Referenced by SDC.long_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.long_DEtype::_totalDigits
string SDC.long_DEtype::_mask
ObjectChangeTracker SDC.long_DEtype.changeTrackerField
static XmlSerializer SDC.long_DEtype::serializer
long SDC.long_DEtype::minInclusive
bool SDC.long_DEtype::minInclusiveSpecified
long SDC.long_DEtype::maxInclusive
bool SDC.long_DEtype::maxInclusiveSpecified
long SDC.long_DEtype::minExclusive
bool SDC.long_DEtype::minExclusiveSpecified
long SDC.long_DEtype::maxExclusive
bool SDC.long_DEtype::maxExclusiveSpecified
byte SDC.long_DEtype::totalDigits
bool SDC.long_DEtype::totalDigitsSpecified
string SDC.long_DEtype::mask
Referenced by SDC.long_DEtype.ShouldSerializemask.
static XmlSerializer SDC.long_DEtype::Serializer
Referenced by SDC.long_DEtype.Deserialize.
ObjectChangeTracker SDC.long_DEtype.ChangeTracker
SDC.long_DEtype.long_DEtype()
SDC.long_DEtype.long_DEtype(BaseType parentNode)
virtual bool SDC.long_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.long_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.long_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.long_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.long_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.long_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current long_DEtype object into an XML string
string XML value
virtual string SDC.long_DEtype.Serialize()
Referenced by SDC.long_DEtype.SaveToFile.
virtual bool SDC.long_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current long_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.long_DEtype.SaveToFile.
virtual bool SDC.long_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.long_DEtype.SaveToFile(string fileName)
virtual void SDC.long_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.long_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.long_DEtype._minInclusive, SDC.long_DEtype._shouldSerializeminInclusive.
virtual bool SDC.long_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.long_DEtype._maxInclusive, SDC.long_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.long_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.long_DEtype._minExclusive, SDC.long_DEtype._shouldSerializeminExclusive.
virtual bool SDC.long_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.long_DEtype._maxExclusive, SDC.long_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.long_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.long_DEtype.mask.
virtual string SDC.long_DEtype.Serialize()
Serializes current long_DEtype object into an XML string
string XML value
virtual bool SDC.long_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current long_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.long_DEtype.SaveToFile.
virtual void SDC.long_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.long_DEtype.Serialize.
virtual long_DEtype SDC.long_DEtype.Clone()
Create a clone of this long_DEtype object
static bool SDC.long_DEtype.Deserialize(string input, out long_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an long_DEtype object
input string workflow markup to deserialize obj Output long_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.long_DEtype.Deserialize, SDC.long_DEtype.LoadFromFile.
static bool SDC.long_DEtype.Deserialize(string input, out long_DEtype obj)
References SDC.null.
static new long_DEtype SDC.long_DEtype.Deserialize(string input)
References SDC.null.
static long_DEtype SDC.long_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.long_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out long_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an long_DEtype object
fileName string xml file to load and deserialize obj Output long_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.long_DEtype.LoadFromFile.
static bool SDC.long_DEtype.LoadFromFile(string fileName, out long_DEtype obj, out System.Exception exception)
static bool SDC.long_DEtype.LoadFromFile(string fileName, out long_DEtype obj)
References SDC.null.
static long_DEtype SDC.long_DEtype.LoadFromFile(string fileName)
static new long_DEtype SDC.long_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.long_DEtype.Deserialize(string input, out long_DEtype obj, out Exception exception)
Deserializes workflow markup into an long_DEtype object
input string workflow markup to deserialize obj Output long_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.long_DEtype.Deserialize, SDC.null.
static bool SDC.long_DEtype.Deserialize(string input, out long_DEtype obj)
References SDC.long_DEtype.Deserialize, SDC.null.
static new long_DEtype SDC.long_DEtype.Deserialize(string input)
References SDC.null, SDC.long_DEtype.Serializer.
static long_DEtype SDC.long_DEtype.Deserialize(Stream s)
References SDC.long_DEtype.Serializer.
static bool SDC.long_DEtype.LoadFromFile(string fileName, out long_DEtype obj, out Exception exception)
Deserializes xml markup from file into an long_DEtype object
fileName string xml file to load and deserialize obj Output long_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.long_DEtype.LoadFromFile, SDC.null.
static bool SDC.long_DEtype.LoadFromFile(string fileName, out long_DEtype obj)
References SDC.long_DEtype.LoadFromFile, SDC.null.
static new long_DEtype SDC.long_DEtype.LoadFromFile(string fileName)
References SDC.long_DEtype.Deserialize, SDC.null.