SDC::ActShowFormType
string SDC.ActShowFormType::_formID
string SDC.ActShowFormType::_packageID
string SDC.ActShowFormType::_displayState
ObjectChangeTracker SDC.ActShowFormType.changeTrackerField
static XmlSerializer SDC.ActShowFormType::serializer
string SDC.ActShowFormType::formID
This ID represents the form to be displayed.
Referenced by SDC.ActShowFormType.ShouldSerializeformID.
string SDC.ActShowFormType::packageID
This ID represents the Package that contains the form to be displayed.
Referenced by SDC.ActShowFormType.ShouldSerializepackageID.
string SDC.ActShowFormType::displayState
Referenced by SDC.ActShowFormType.ShouldSerializedisplayState.
static XmlSerializer SDC.ActShowFormType::Serializer
Referenced by SDC.ActShowFormType.Deserialize.
ObjectChangeTracker SDC.ActShowFormType.ChangeTracker
SDC.ActShowFormType.ActShowFormType()
SDC.ActShowFormType.ActShowFormType(ThenType parentNode)
SDC.ActShowFormType.ActShowFormType()
virtual bool SDC.ActShowFormType.ShouldSerializeformID()
Test whether formID should be serialized
virtual bool SDC.ActShowFormType.ShouldSerializepackageID()
Test whether packageID should be serialized
virtual bool SDC.ActShowFormType.ShouldSerializedisplayState()
Test whether displayState should be serialized
virtual string SDC.ActShowFormType.Serialize(System.Text.Encoding encoding)
Serializes current ActShowFormType object into an XML string
string XML value
virtual string SDC.ActShowFormType.Serialize()
Referenced by SDC.ActShowFormType.SaveToFile.
virtual bool SDC.ActShowFormType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ActShowFormType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ActShowFormType.SaveToFile.
virtual bool SDC.ActShowFormType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ActShowFormType.SaveToFile(string fileName)
virtual void SDC.ActShowFormType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ActShowFormType.ShouldSerializeformID()
Test whether formID should be serialized
References SDC.ActShowFormType.formID.
virtual bool SDC.ActShowFormType.ShouldSerializepackageID()
Test whether packageID should be serialized
References SDC.ActShowFormType.packageID.
virtual bool SDC.ActShowFormType.ShouldSerializedisplayState()
Test whether displayState should be serialized
References SDC.ActShowFormType.displayState.
virtual string SDC.ActShowFormType.Serialize()
Serializes current ActShowFormType object into an XML string
string XML value
virtual bool SDC.ActShowFormType.SaveToFile(string fileName, out Exception exception)
Serializes current ActShowFormType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ActShowFormType.SaveToFile.
virtual void SDC.ActShowFormType.SaveToFile(string fileName)
References SDC.null, SDC.ActShowFormType.Serialize.
virtual ActShowFormType SDC.ActShowFormType.Clone()
Create a clone of this ActShowFormType object
static bool SDC.ActShowFormType.Deserialize(string input, out ActShowFormType obj, out System.Exception exception)
Deserializes workflow markup into an ActShowFormType object
input string workflow markup to deserialize obj Output ActShowFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActShowFormType.Deserialize, SDC.ActShowFormType.LoadFromFile.
static bool SDC.ActShowFormType.Deserialize(string input, out ActShowFormType obj)
References SDC.null.
static new ActShowFormType SDC.ActShowFormType.Deserialize(string input)
References SDC.null.
static ActShowFormType SDC.ActShowFormType.Deserialize(System.IO.Stream s)
static bool SDC.ActShowFormType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ActShowFormType obj, out System.Exception exception)
Deserializes xml markup from file into an ActShowFormType object
fileName string xml file to load and deserialize obj Output ActShowFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActShowFormType.LoadFromFile.
static bool SDC.ActShowFormType.LoadFromFile(string fileName, out ActShowFormType obj, out System.Exception exception)
static bool SDC.ActShowFormType.LoadFromFile(string fileName, out ActShowFormType obj)
References SDC.null.
static ActShowFormType SDC.ActShowFormType.LoadFromFile(string fileName)
static new ActShowFormType SDC.ActShowFormType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ActShowFormType.Deserialize(string input, out ActShowFormType obj, out Exception exception)
Deserializes workflow markup into an ActShowFormType object
input string workflow markup to deserialize obj Output ActShowFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActShowFormType.Deserialize, SDC.null.
static bool SDC.ActShowFormType.Deserialize(string input, out ActShowFormType obj)
References SDC.ActShowFormType.Deserialize, SDC.null.
static new ActShowFormType SDC.ActShowFormType.Deserialize(string input)
References SDC.null, SDC.ActShowFormType.Serializer.
static ActShowFormType SDC.ActShowFormType.Deserialize(Stream s)
References SDC.ActShowFormType.Serializer.
static bool SDC.ActShowFormType.LoadFromFile(string fileName, out ActShowFormType obj, out Exception exception)
Deserializes xml markup from file into an ActShowFormType object
fileName string xml file to load and deserialize obj Output ActShowFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActShowFormType.LoadFromFile, SDC.null.
static bool SDC.ActShowFormType.LoadFromFile(string fileName, out ActShowFormType obj)
References SDC.ActShowFormType.LoadFromFile, SDC.null.
static new ActShowFormType SDC.ActShowFormType.LoadFromFile(string fileName)
References SDC.ActShowFormType.Deserialize, SDC.null.