SDC::date_DEtype
bool SDC.date_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.date_DEtype.ShouldSerializemaxExclusive.
bool SDC.date_DEtype::_shouldSerializeminExclusive
Referenced by SDC.date_DEtype.ShouldSerializeminExclusive.
bool SDC.date_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.date_DEtype.ShouldSerializemaxInclusive.
bool SDC.date_DEtype::_shouldSerializeminInclusive
Referenced by SDC.date_DEtype.ShouldSerializeminInclusive.
System.Nullable<System.DateTime> SDC.date_DEtype._minInclusive
Referenced by SDC.date_DEtype.ShouldSerializeminInclusive.
System.Nullable<System.DateTime> SDC.date_DEtype._maxInclusive
Referenced by SDC.date_DEtype.ShouldSerializemaxInclusive.
System.Nullable<System.DateTime> SDC.date_DEtype._minExclusive
Referenced by SDC.date_DEtype.ShouldSerializeminExclusive.
System.Nullable<System.DateTime> SDC.date_DEtype._maxExclusive
Referenced by SDC.date_DEtype.ShouldSerializemaxExclusive.
string SDC.date_DEtype::_mask
DateTime SDC.date_DEtype._minInclusive
DateTime SDC.date_DEtype._maxInclusive
DateTime SDC.date_DEtype._minExclusive
DateTime SDC.date_DEtype._maxExclusive
ObjectChangeTracker SDC.date_DEtype.changeTrackerField
static XmlSerializer SDC.date_DEtype::serializer
System DateTime SDC.date_DEtype::minInclusive
bool SDC.date_DEtype::minInclusiveSpecified
System DateTime SDC.date_DEtype::maxInclusive
bool SDC.date_DEtype::maxInclusiveSpecified
System DateTime SDC.date_DEtype::minExclusive
bool SDC.date_DEtype::minExclusiveSpecified
System DateTime SDC.date_DEtype::maxExclusive
bool SDC.date_DEtype::maxExclusiveSpecified
string SDC.date_DEtype::mask
Referenced by SDC.date_DEtype.ShouldSerializemask.
static XmlSerializer SDC.date_DEtype::Serializer
Referenced by SDC.date_DEtype.Deserialize.
ObjectChangeTracker SDC.date_DEtype.ChangeTracker
SDC.date_DEtype.date_DEtype()
SDC.date_DEtype.date_DEtype(BaseType parentNode)
virtual bool SDC.date_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.date_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.date_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.date_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.date_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.date_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current date_DEtype object into an XML string
string XML value
virtual string SDC.date_DEtype.Serialize()
Referenced by SDC.date_DEtype.SaveToFile.
virtual bool SDC.date_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current date_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.date_DEtype.SaveToFile.
virtual bool SDC.date_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.date_DEtype.SaveToFile(string fileName)
virtual void SDC.date_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.date_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.date_DEtype._minInclusive, SDC.date_DEtype._shouldSerializeminInclusive.
virtual bool SDC.date_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.date_DEtype._maxInclusive, SDC.date_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.date_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.date_DEtype._minExclusive, SDC.date_DEtype._shouldSerializeminExclusive.
virtual bool SDC.date_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.date_DEtype._maxExclusive, SDC.date_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.date_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.date_DEtype.mask.
virtual string SDC.date_DEtype.Serialize()
Serializes current date_DEtype object into an XML string
string XML value
virtual bool SDC.date_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current date_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.date_DEtype.SaveToFile.
virtual void SDC.date_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.date_DEtype.Serialize.
virtual date_DEtype SDC.date_DEtype.Clone()
Create a clone of this date_DEtype object
static bool SDC.date_DEtype.Deserialize(string input, out date_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an date_DEtype object
input string workflow markup to deserialize obj Output date_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.date_DEtype.Deserialize, SDC.date_DEtype.LoadFromFile.
static bool SDC.date_DEtype.Deserialize(string input, out date_DEtype obj)
References SDC.null.
static new date_DEtype SDC.date_DEtype.Deserialize(string input)
References SDC.null.
static date_DEtype SDC.date_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.date_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out date_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an date_DEtype object
fileName string xml file to load and deserialize obj Output date_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.date_DEtype.LoadFromFile.
static bool SDC.date_DEtype.LoadFromFile(string fileName, out date_DEtype obj, out System.Exception exception)
static bool SDC.date_DEtype.LoadFromFile(string fileName, out date_DEtype obj)
References SDC.null.
static date_DEtype SDC.date_DEtype.LoadFromFile(string fileName)
static new date_DEtype SDC.date_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.date_DEtype.Deserialize(string input, out date_DEtype obj, out Exception exception)
Deserializes workflow markup into an date_DEtype object
input string workflow markup to deserialize obj Output date_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.date_DEtype.Deserialize, SDC.null.
static bool SDC.date_DEtype.Deserialize(string input, out date_DEtype obj)
References SDC.date_DEtype.Deserialize, SDC.null.
static new date_DEtype SDC.date_DEtype.Deserialize(string input)
References SDC.null, SDC.date_DEtype.Serializer.
static date_DEtype SDC.date_DEtype.Deserialize(Stream s)
References SDC.date_DEtype.Serializer.
static bool SDC.date_DEtype.LoadFromFile(string fileName, out date_DEtype obj, out Exception exception)
Deserializes xml markup from file into an date_DEtype object
fileName string xml file to load and deserialize obj Output date_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.date_DEtype.LoadFromFile, SDC.null.
static bool SDC.date_DEtype.LoadFromFile(string fileName, out date_DEtype obj)
References SDC.date_DEtype.LoadFromFile, SDC.null.
static new date_DEtype SDC.date_DEtype.LoadFromFile(string fileName)
References SDC.date_DEtype.Deserialize, SDC.null.