SDC::DisplayedType
bool SDC.DisplayedType::_shouldSerializemustImplement
Referenced by SDC.DisplayedType.ShouldSerializemustImplement.
bool SDC.DisplayedType::_shouldSerializevisible
Referenced by SDC.DisplayedType.ShouldSerializevisible.
bool SDC.DisplayedType::_shouldSerializeenabled
Referenced by SDC.DisplayedType.ShouldSerializeenabled.
List<LinkType> SDC.DisplayedType._link
List<BlobType> SDC.DisplayedType._blobContent
List<ContactType> SDC.DisplayedType._contact
List<CodingType> SDC.DisplayedType._codedValue
List<EventType> SDC.DisplayedType._onEnter
List<EventType> SDC.DisplayedType._onExit
List<OnEventType> SDC.DisplayedType._onEvent
WatchedPropertyType SDC.DisplayedType::_activateIf
Referenced by SDC.DisplayedType.ShouldSerializeActivateIf.
WatchedPropertyType SDC.DisplayedType::_deActivateIf
Referenced by SDC.DisplayedType.ShouldSerializeDeActivateIf.
string SDC.DisplayedType::_title
bool SDC.DisplayedType::_enabled
Referenced by SDC.DisplayedType.DisplayedType, SDC.DisplayedType.ShouldSerializeenabled.
bool SDC.DisplayedType::_visible
Referenced by SDC.DisplayedType.DisplayedType, SDC.DisplayedType.ShouldSerializevisible.
bool SDC.DisplayedType::_mustImplement
Referenced by SDC.DisplayedType.DisplayedType, SDC.DisplayedType.ShouldSerializemustImplement.
DisplayedTypeShowInReport SDC.DisplayedType._showInReport
Referenced by SDC.DisplayedType.DisplayedType, SDC.DisplayedType.ShouldSerializeshowInReport.
bool SDC.DisplayedType._shouldSerializeshowInReport
Referenced by SDC.DisplayedType.ShouldSerializeshowInReport.
BindingList<RichTextType> SDC.DisplayedType._otherText
BindingList<LinkType> SDC.DisplayedType._link
BindingList<BlobType> SDC.DisplayedType._blobContent
BindingList<ContactType> SDC.DisplayedType._contact
BindingList<CodingType> SDC.DisplayedType._codedValue
BindingList<IfThenType> SDC.DisplayedType._onEnter
BindingList<IfThenType> SDC.DisplayedType._onExit
BindingList<OnEventType> SDC.DisplayedType._onEvent
bool SDC.DisplayedType._showInReport
ObjectChangeTracker SDC.DisplayedType.changeTrackerField
static XmlSerializer SDC.DisplayedType::serializer
virtual List<LinkType> SDC.DisplayedType.Link
DisplayedType class constructor
Link to external information.
Referenced by SDC.SDCTreeBuilderEcc.AddLink, SDC.SDCTreeBuilder.AddLink.
virtual List<BlobType> SDC.DisplayedType.BlobContent
Blob information associated with the current DisplayedType. The blob may contain any type of special media, but must be base 64 encoded.
Referenced by SDC.SDCTreeBuilder.AddBlob.
virtual List<ContactType> SDC.DisplayedType.Contact
Any desired contact information regarding, e.g., the form item, authoring process, certifications, code or coding processs.
Referenced by SDC.SDCTreeBuilder.AddContact, SDC.SDCTreeBuilder.AddPerson.
virtual List<CodingType> SDC.DisplayedType.CodedValue
Coding, terminology, classification, keyword, or local values
Referenced by SDC.SDCTreeBuilder.AddCodingList.
virtual List<EventType> SDC.DisplayedType.OnEnter
virtual List<EventType> SDC.DisplayedType.OnExit
virtual List<OnEventType> SDC.DisplayedType.OnEvent
Generic event handler - eventName must be specified.
WatchedPropertyType SDC.DisplayedType::ActivateIf
Activate the DisplayedType item if the contained conditions are met.
WatchedPropertyType SDC.DisplayedType::DeActivateIf
DeActivate the DisplayedType item if the contained conditions are met.
string SDC.DisplayedType::title
The primary text to show on the form. Also known as "prompt" or "label" or "visibleText" or "caption"
Referenced by SDC.SDCTreeBuilderEcc.FillListItemBase, SDC.SDCTreeBuilderEcc.FillRepeatingTypeItemData, SDC.DisplayedType.ShouldSerializetitle.
bool SDC.DisplayedType::enabled
Determines whether the user can interact with the displayed item when the form is first displayed.
bool SDC.DisplayedType::visible
Determines whether the item should be visible on a computer screen when the form is first displayed.
bool SDC.DisplayedType::mustImplement
If this attribute is set to "true" (the default), then the form implementation must make this item available for use on the form. If this attribute is set to "false" on a parent or ancestor item, then all child/descendant items inherit this "false" setting, even if they have this attribute set to "true." In other words, the child/descendent items do not need to be implemented if any parent/ancestor item has this attribute set to false.
Referenced by SDC.SDCTreeBuilderEcc.FillDisplayedTypeListItemData.
virtual DisplayedTypeShowInReport SDC.DisplayedType.showInReport
CHANGED to T/F/Optional
If on a Question is false, then the Question and its ListItems (if any) should not be present in a typical report derived from this template. If this attribute appears on a ListItem, then the entire question and all ListItems should be omitted from the report. If this attribute appears on a Section, then the entire Section and all Section contents (descendents) should be omitted from the report. If appears on a DisplayedItem, then the DisplayedItem (and all sub-items) should be omitted from the report.This attribute is usually set to false when a Question is used to control form behavior (e.g., skip logic), or when the Question provides unhelpful "negative" information about actions that did not occur or were not performed, or things that were not observed.
static XmlSerializer SDC.DisplayedType::Serializer
Referenced by SDC.DisplayedType.Deserialize.
virtual BindingList<RichTextType> SDC.DisplayedType.OtherText
OtherText is any type of secondary text that is associated with any form item (e.g., section, question, list item) in any context. The Description context is specified by the attribute. Examples of Description values may include: -alternate language representations, -explanations for the user of the form, -tooltips, -pop-up help, -outlining (such as question numbering)
The enumerations must be defined and documented for the particular use case, and are currently out of scope in this schema definition.
Referenced by SDC.SDCTreeBuilder.AddOtherText.
virtual BindingList<LinkType> SDC.DisplayedType.Link
Link to external information.
virtual BindingList<BlobType> SDC.DisplayedType.BlobContent
Blob information associated with the current DisplayedType. The blob may contain any type of special media, but must be base 64 encoded.
virtual BindingList<ContactType> SDC.DisplayedType.Contact
Any desired contact information regarding, e.g., the form item, authoring process, certifications, code or coding processs.
virtual BindingList<CodingType> SDC.DisplayedType.CodedValue
Coding, terminology, classification, keyword, or local values
virtual BindingList<IfThenType> SDC.DisplayedType.OnEnter
virtual BindingList<IfThenType> SDC.DisplayedType.OnExit
virtual BindingList<OnEventType> SDC.DisplayedType.OnEvent
Generic event handler - eventName must be specified.
virtual bool SDC.DisplayedType.showInReport
If on a Question is false, then the Question and its ListItems (if any) should not be present in a typical report derived from this template. If this attribute appears on a ListItem, then the entire question and all ListItems should be omitted from the report. If this attribute appears on a Section, then the entire Section and all Section contents (descendents) should be omitted from the report. If appears on a DisplayedItem, then the DisplayedItem (and all sub-items) should be omitted from the report.
This attribute is usually set to false when a Question is used to control form behavior (e.g., skip logic), or when the Question provides unhelpful "negative" information about actions that did not occur or were not performed, or things that were not observed.
ObjectChangeTracker SDC.DisplayedType.ChangeTracker
SDC.DisplayedType.DisplayedType(BaseType parentNode, bool fillData=true, string id=null)
PropertyType SDC.DisplayedType.AddProperty(Boolean fillData=true)
+Replaced in original class: protected DisplayedType() { }
LinkType SDC.DisplayedType.AddLink(Boolean fillData=true)
BlobType SDC.DisplayedType.AddBlob(Boolean fillData=true)
ContactType SDC.DisplayedType.AddContact(Boolean fillData=true)
CodingType SDC.DisplayedType.AddCoding(Boolean fillData=true)
IfThenType SDC.DisplayedType.AddOnEvent(Boolean fillData=true)
IfThenType SDC.DisplayedType.AddOnEnter(Boolean fillData=true)
OnEventType SDC.DisplayedType.AddOnExit(Boolean fillData=true)
WatchedPropertyType SDC.DisplayedType.AddActivateIf(Boolean fillData=true)
WatchedPropertyType SDC.DisplayedType.AddDeActivateIf(Boolean fillData=true)
RichTextType SDC.DisplayedType.AddOtherText()
LinkType SDC.DisplayedType.AddLink()
BlobType SDC.DisplayedType.AddBlob()
ContactType SDC.DisplayedType.AddContact()
CodingType SDC.DisplayedType.AddCoding()
IfThenType SDC.DisplayedType.AddOnEvent()
IfThenType SDC.DisplayedType.AddOnEnter()
OnEventType SDC.DisplayedType.AddOnExit()
WatchedPropertyType SDC.DisplayedType.AddActivateIf()
WatchedPropertyType SDC.DisplayedType.AddDeActivateIf()
virtual bool SDC.DisplayedType.ShouldSerializeLink()
Test whether Link should be serialized
References SDC.Link, SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeBlobContent()
Test whether BlobContent should be serialized
References SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeContact()
Test whether Contact should be serialized
References SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeCodedValue()
Test whether CodedValue should be serialized
References SDC.CodedValue, SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeOnEnter()
Test whether OnEnter should be serialized
References SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeOnExit()
Test whether OnExit should be serialized
References SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeOnEvent()
Test whether OnEvent should be serialized
References SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeenabled()
Test whether enabled should be serialized
virtual bool SDC.DisplayedType.ShouldSerializevisible()
Test whether visible should be serialized
virtual bool SDC.DisplayedType.ShouldSerializemustImplement()
Test whether mustImplement should be serialized
virtual bool SDC.DisplayedType.ShouldSerializeActivateIf()
Test whether ActivateIf should be serialized
References SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeDeActivateIf()
Test whether DeActivateIf should be serialized
References SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializetitle()
Test whether title should be serialized
virtual string SDC.DisplayedType.Serialize(System.Text.Encoding encoding)
Serializes current DisplayedType object into an XML string
string XML value
virtual string SDC.DisplayedType.Serialize()
Referenced by SDC.DisplayedType.SaveToFile.
virtual bool SDC.DisplayedType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current DisplayedType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.DisplayedType.SaveToFile.
virtual bool SDC.DisplayedType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.DisplayedType.SaveToFile(string fileName)
virtual void SDC.DisplayedType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.DisplayedType.DisplayedType()
DisplayedType class constructor
References SDC.DisplayedType._enabled, SDC.DisplayedType._mustImplement, SDC.DisplayedType._showInReport, SDC.DisplayedType._visible.
virtual bool SDC.DisplayedType.ShouldSerializeenabled()
Test whether enabled should be serialized
References SDC.DisplayedType._enabled, SDC.DisplayedType._shouldSerializeenabled.
virtual bool SDC.DisplayedType.ShouldSerializevisible()
Test whether visible should be serialized
References SDC.DisplayedType._shouldSerializevisible, SDC.DisplayedType._visible.
virtual bool SDC.DisplayedType.ShouldSerializemustImplement()
Test whether mustImplement should be serialized
References SDC.DisplayedType._mustImplement, SDC.DisplayedType._shouldSerializemustImplement.
virtual bool SDC.DisplayedType.ShouldSerializeshowInReport()
Test whether showInReport should be serialized
References SDC.DisplayedType._shouldSerializeshowInReport, SDC.DisplayedType._showInReport.
virtual bool SDC.DisplayedType.ShouldSerializeActivateIf()
Test whether ActivateIf should be serialized
References SDC.DisplayedType._activateIf, SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializeDeActivateIf()
Test whether DeActivateIf should be serialized
References SDC.DisplayedType._deActivateIf, SDC.null.
virtual bool SDC.DisplayedType.ShouldSerializetitle()
Test whether title should be serialized
References SDC.DisplayedType.title.
virtual string SDC.DisplayedType.Serialize()
Serializes current DisplayedType object into an XML string
string XML value
virtual bool SDC.DisplayedType.SaveToFile(string fileName, out Exception exception)
Serializes current DisplayedType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.DisplayedType.SaveToFile.
virtual void SDC.DisplayedType.SaveToFile(string fileName)
References SDC.null, SDC.DisplayedType.Serialize.
virtual DisplayedType SDC.DisplayedType.Clone()
Create a clone of this DisplayedType object
SDC.DisplayedType.DisplayedType()
DisplayedType SDC.DisplayedType.FillDisplayedType()
static bool SDC.DisplayedType.Deserialize(string input, out DisplayedType obj, out System.Exception exception)
Deserializes workflow markup into an DisplayedType object
input string workflow markup to deserialize obj Output DisplayedType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DisplayedType.Deserialize, SDC.DisplayedType.LoadFromFile.
static bool SDC.DisplayedType.Deserialize(string input, out DisplayedType obj)
References SDC.null.
static new DisplayedType SDC.DisplayedType.Deserialize(string input)
References SDC.null.
static DisplayedType SDC.DisplayedType.Deserialize(System.IO.Stream s)
static bool SDC.DisplayedType.LoadFromFile(string fileName, System.Text.Encoding encoding, out DisplayedType obj, out System.Exception exception)
Deserializes xml markup from file into an DisplayedType object
fileName string xml file to load and deserialize obj Output DisplayedType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.DisplayedType.LoadFromFile.
static bool SDC.DisplayedType.LoadFromFile(string fileName, out DisplayedType obj, out System.Exception exception)
static bool SDC.DisplayedType.LoadFromFile(string fileName, out DisplayedType obj)
References SDC.null.
static DisplayedType SDC.DisplayedType.LoadFromFile(string fileName)
static new DisplayedType SDC.DisplayedType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.DisplayedType.Deserialize(string input, out DisplayedType obj, out Exception exception)
Deserializes workflow markup into an DisplayedType object
input string workflow markup to deserialize obj Output DisplayedType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.DisplayedType.Deserialize, SDC.null.
static bool SDC.DisplayedType.Deserialize(string input, out DisplayedType obj)
References SDC.DisplayedType.Deserialize, SDC.null.
static new DisplayedType SDC.DisplayedType.Deserialize(string input)
References SDC.null, SDC.DisplayedType.Serializer.
static DisplayedType SDC.DisplayedType.Deserialize(Stream s)
References SDC.DisplayedType.Serializer.
static bool SDC.DisplayedType.LoadFromFile(string fileName, out DisplayedType obj, out Exception exception)
Deserializes xml markup from file into an DisplayedType object
fileName string xml file to load and deserialize obj Output DisplayedType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.DisplayedType.LoadFromFile, SDC.null.
static bool SDC.DisplayedType.LoadFromFile(string fileName, out DisplayedType obj)
References SDC.DisplayedType.LoadFromFile, SDC.null.
static new DisplayedType SDC.DisplayedType.LoadFromFile(string fileName)
References SDC.DisplayedType.Deserialize, SDC.null.