SDC::ReturnDateTimeListType
DateTimeListType SDC.ReturnDateTimeListType._item1
Referenced by SDC.ReturnDateTimeListType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnDateTimeListType.serializer
virtual DateTimeListType SDC.ReturnDateTimeListType.Item1
XmlSerializer SDC.ReturnDateTimeListType.Serializer
Referenced by SDC.ReturnDateTimeListType.Deserialize.
virtual bool SDC.ReturnDateTimeListType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnDateTimeListType._item1, SDC.null.
virtual string SDC.ReturnDateTimeListType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnDateTimeListType object into an XML string
string XML value
virtual string SDC.ReturnDateTimeListType.Serialize()
Referenced by SDC.ReturnDateTimeListType.SaveToFile.
virtual bool SDC.ReturnDateTimeListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnDateTimeListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnDateTimeListType.SaveToFile.
virtual bool SDC.ReturnDateTimeListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnDateTimeListType.SaveToFile.
virtual void SDC.ReturnDateTimeListType.SaveToFile(string fileName)
References SDC.ReturnDateTimeListType.SaveToFile.
virtual void SDC.ReturnDateTimeListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnDateTimeListType.Serialize.
static bool SDC.ReturnDateTimeListType.Deserialize(string input, out ReturnDateTimeListType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnDateTimeListType object
input string workflow markup to deserialize obj Output ReturnDateTimeListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnDateTimeListType.Deserialize, SDC.ReturnDateTimeListType.LoadFromFile.
static bool SDC.ReturnDateTimeListType.Deserialize(string input, out ReturnDateTimeListType obj)
References SDC.ReturnDateTimeListType.Deserialize, SDC.null.
static new ReturnDateTimeListType SDC.ReturnDateTimeListType.Deserialize(string input)
References SDC.null.
static ReturnDateTimeListType SDC.ReturnDateTimeListType.Deserialize(System.IO.Stream s)
References SDC.ReturnDateTimeListType.Serializer.
static bool SDC.ReturnDateTimeListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnDateTimeListType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnDateTimeListType object
fileName string xml file to load and deserialize obj Output ReturnDateTimeListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnDateTimeListType.LoadFromFile.
static bool SDC.ReturnDateTimeListType.LoadFromFile(string fileName, out ReturnDateTimeListType obj, out System.Exception exception)
References SDC.ReturnDateTimeListType.LoadFromFile.
static bool SDC.ReturnDateTimeListType.LoadFromFile(string fileName, out ReturnDateTimeListType obj)
References SDC.ReturnDateTimeListType.LoadFromFile, SDC.null.
static ReturnDateTimeListType SDC.ReturnDateTimeListType.LoadFromFile(string fileName)
References SDC.ReturnDateTimeListType.LoadFromFile.
static new ReturnDateTimeListType SDC.ReturnDateTimeListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnDateTimeListType.Deserialize, SDC.null.