SDC::dateTimeStamp_Stype
bool SDC.dateTimeStamp_Stype::_shouldSerializeval
Referenced by SDC.dateTimeStamp_Stype.ShouldSerializeval.
System.Nullable<System.DateTime> SDC.dateTimeStamp_Stype._val
Referenced by SDC.dateTimeStamp_Stype.ShouldSerializeval.
DateTime SDC.dateTimeStamp_Stype._val
ObjectChangeTracker SDC.dateTimeStamp_Stype.changeTrackerField
static XmlSerializer SDC.dateTimeStamp_Stype::serializer
System DateTime SDC.dateTimeStamp_Stype::val
bool SDC.dateTimeStamp_Stype::valSpecified
static XmlSerializer SDC.dateTimeStamp_Stype::Serializer
Referenced by SDC.dateTimeStamp_Stype.Deserialize.
ObjectChangeTracker SDC.dateTimeStamp_Stype.ChangeTracker
SDC.dateTimeStamp_Stype.dateTimeStamp_Stype()
SDC.dateTimeStamp_Stype.dateTimeStamp_Stype(BaseType parentNode)
virtual bool SDC.dateTimeStamp_Stype.ShouldSerializeval()
Test whether val should be serialized
virtual string SDC.dateTimeStamp_Stype.Serialize(System.Text.Encoding encoding)
Serializes current dateTimeStamp_Stype object into an XML string
string XML value
virtual string SDC.dateTimeStamp_Stype.Serialize()
Referenced by SDC.dateTimeStamp_Stype.SaveToFile.
virtual bool SDC.dateTimeStamp_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current dateTimeStamp_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.dateTimeStamp_Stype.SaveToFile.
virtual bool SDC.dateTimeStamp_Stype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.dateTimeStamp_Stype.SaveToFile(string fileName)
virtual void SDC.dateTimeStamp_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.dateTimeStamp_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.dateTimeStamp_Stype._shouldSerializeval, SDC.dateTimeStamp_Stype._val.
virtual string SDC.dateTimeStamp_Stype.Serialize()
Serializes current dateTimeStamp_Stype object into an XML string
string XML value
virtual bool SDC.dateTimeStamp_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current dateTimeStamp_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.dateTimeStamp_Stype.SaveToFile.
virtual void SDC.dateTimeStamp_Stype.SaveToFile(string fileName)
References SDC.null, SDC.dateTimeStamp_Stype.Serialize.
virtual dateTimeStamp_Stype SDC.dateTimeStamp_Stype.Clone()
Create a clone of this dateTimeStamp_Stype object
static bool SDC.dateTimeStamp_Stype.Deserialize(string input, out dateTimeStamp_Stype obj, out System.Exception exception)
Deserializes workflow markup into an dateTimeStamp_Stype object
input string workflow markup to deserialize obj Output dateTimeStamp_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dateTimeStamp_Stype.Deserialize, SDC.dateTimeStamp_Stype.LoadFromFile.
static bool SDC.dateTimeStamp_Stype.Deserialize(string input, out dateTimeStamp_Stype obj)
References SDC.null.
static new dateTimeStamp_Stype SDC.dateTimeStamp_Stype.Deserialize(string input)
References SDC.null.
static dateTimeStamp_Stype SDC.dateTimeStamp_Stype.Deserialize(System.IO.Stream s)
static bool SDC.dateTimeStamp_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out dateTimeStamp_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an dateTimeStamp_Stype object
fileName string xml file to load and deserialize obj Output dateTimeStamp_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dateTimeStamp_Stype.LoadFromFile.
static bool SDC.dateTimeStamp_Stype.LoadFromFile(string fileName, out dateTimeStamp_Stype obj, out System.Exception exception)
static bool SDC.dateTimeStamp_Stype.LoadFromFile(string fileName, out dateTimeStamp_Stype obj)
References SDC.null.
static dateTimeStamp_Stype SDC.dateTimeStamp_Stype.LoadFromFile(string fileName)
static new dateTimeStamp_Stype SDC.dateTimeStamp_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.dateTimeStamp_Stype.Deserialize(string input, out dateTimeStamp_Stype obj, out Exception exception)
Deserializes workflow markup into an dateTimeStamp_Stype object
input string workflow markup to deserialize obj Output dateTimeStamp_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dateTimeStamp_Stype.Deserialize, SDC.null.
static bool SDC.dateTimeStamp_Stype.Deserialize(string input, out dateTimeStamp_Stype obj)
References SDC.dateTimeStamp_Stype.Deserialize, SDC.null.
static new dateTimeStamp_Stype SDC.dateTimeStamp_Stype.Deserialize(string input)
References SDC.null, SDC.dateTimeStamp_Stype.Serializer.
static dateTimeStamp_Stype SDC.dateTimeStamp_Stype.Deserialize(Stream s)
References SDC.dateTimeStamp_Stype.Serializer.
static bool SDC.dateTimeStamp_Stype.LoadFromFile(string fileName, out dateTimeStamp_Stype obj, out Exception exception)
Deserializes xml markup from file into an dateTimeStamp_Stype object
fileName string xml file to load and deserialize obj Output dateTimeStamp_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dateTimeStamp_Stype.LoadFromFile, SDC.null.
static bool SDC.dateTimeStamp_Stype.LoadFromFile(string fileName, out dateTimeStamp_Stype obj)
References SDC.dateTimeStamp_Stype.LoadFromFile, SDC.null.
static new dateTimeStamp_Stype SDC.dateTimeStamp_Stype.LoadFromFile(string fileName)
References SDC.dateTimeStamp_Stype.Deserialize, SDC.null.