SDC::base64Binary_Stype
string SDC.base64Binary_Stype::_base64StringVal
bool SDC.base64Binary_Stype::_shouldSerializelength
Referenced by SDC.base64Binary_Stype.ShouldSerializelength.
string SDC.base64Binary_Stype::_mimeType
System Nullable< long > SDC.base64Binary_Stype::_length
Referenced by SDC.base64Binary_Stype.ShouldSerializelength.
byte [] SDC.base64Binary_Stype._val
ObjectChangeTracker SDC.base64Binary_Stype.changeTrackerField
string SDC.base64Binary_Stype::valBase64
string SDC.base64Binary_Stype::mimeType
TBD: Must be a valid MIME type
Referenced by SDC.base64Binary_Stype.ShouldSerializemimeType.
long SDC.base64Binary_Stype::length
bool SDC.base64Binary_Stype::lengthSpecified
virtual byte [] SDC.base64Binary_Stype.val
static XmlSerializer SDC.base64Binary_Stype::Serializer
Referenced by SDC.base64Binary_Stype.Deserialize.
ObjectChangeTracker SDC.base64Binary_Stype.ChangeTracker
static XmlSerializer SDC.base64Binary_Stype::serializer
SDC.base64Binary_Stype.base64Binary_Stype()
SDC.base64Binary_Stype.base64Binary_Stype(BaseType parentNode)
SDC.base64Binary_Stype.base64Binary_Stype()
virtual bool SDC.base64Binary_Stype.ShouldSerializelength()
Test whether length should be serialized
virtual bool SDC.base64Binary_Stype.ShouldSerializemimeType()
Test whether mimeType should be serialized
virtual string SDC.base64Binary_Stype.Serialize(System.Text.Encoding encoding)
Serializes current base64Binary_Stype object into an XML string
string XML value
virtual string SDC.base64Binary_Stype.Serialize()
Referenced by SDC.base64Binary_Stype.SaveToFile.
virtual bool SDC.base64Binary_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current base64Binary_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.base64Binary_Stype.SaveToFile.
virtual bool SDC.base64Binary_Stype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.base64Binary_Stype.SaveToFile(string fileName)
virtual void SDC.base64Binary_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.base64Binary_Stype.ShouldSerializelength()
Test whether length should be serialized
References SDC.base64Binary_Stype._length, SDC.base64Binary_Stype._shouldSerializelength.
virtual bool SDC.base64Binary_Stype.ShouldSerializemimeType()
Test whether mimeType should be serialized
References SDC.base64Binary_Stype.mimeType.
virtual string SDC.base64Binary_Stype.Serialize()
Serializes current base64Binary_Stype object into an XML string
string XML value
virtual bool SDC.base64Binary_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current base64Binary_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.base64Binary_Stype.SaveToFile.
virtual void SDC.base64Binary_Stype.SaveToFile(string fileName)
References SDC.null, SDC.base64Binary_Stype.Serialize.
virtual base64Binary_Stype SDC.base64Binary_Stype.Clone()
Create a clone of this base64Binary_Stype object
static bool SDC.base64Binary_Stype.Deserialize(string input, out base64Binary_Stype obj, out System.Exception exception)
Deserializes workflow markup into an base64Binary_Stype object
input string workflow markup to deserialize obj Output base64Binary_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.base64Binary_Stype.Deserialize, SDC.base64Binary_Stype.LoadFromFile.
static bool SDC.base64Binary_Stype.Deserialize(string input, out base64Binary_Stype obj)
References SDC.null.
static new base64Binary_Stype SDC.base64Binary_Stype.Deserialize(string input)
References SDC.null.
static base64Binary_Stype SDC.base64Binary_Stype.Deserialize(System.IO.Stream s)
static bool SDC.base64Binary_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out base64Binary_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an base64Binary_Stype object
fileName string xml file to load and deserialize obj Output base64Binary_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.base64Binary_Stype.LoadFromFile.
static bool SDC.base64Binary_Stype.LoadFromFile(string fileName, out base64Binary_Stype obj, out System.Exception exception)
static bool SDC.base64Binary_Stype.LoadFromFile(string fileName, out base64Binary_Stype obj)
References SDC.null.
static base64Binary_Stype SDC.base64Binary_Stype.LoadFromFile(string fileName)
static new base64Binary_Stype SDC.base64Binary_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.base64Binary_Stype.Deserialize(string input, out base64Binary_Stype obj, out Exception exception)
Deserializes workflow markup into an base64Binary_Stype object
input string workflow markup to deserialize obj Output base64Binary_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.base64Binary_Stype.Deserialize, SDC.null.
static bool SDC.base64Binary_Stype.Deserialize(string input, out base64Binary_Stype obj)
References SDC.base64Binary_Stype.Deserialize, SDC.null.
static new base64Binary_Stype SDC.base64Binary_Stype.Deserialize(string input)
References SDC.null, SDC.base64Binary_Stype.Serializer.
static base64Binary_Stype SDC.base64Binary_Stype.Deserialize(Stream s)
References SDC.base64Binary_Stype.Serializer.
static bool SDC.base64Binary_Stype.LoadFromFile(string fileName, out base64Binary_Stype obj, out Exception exception)
Deserializes xml markup from file into an base64Binary_Stype object
fileName string xml file to load and deserialize obj Output base64Binary_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.base64Binary_Stype.LoadFromFile, SDC.null.
static bool SDC.base64Binary_Stype.LoadFromFile(string fileName, out base64Binary_Stype obj)
References SDC.base64Binary_Stype.LoadFromFile, SDC.null.
static new base64Binary_Stype SDC.base64Binary_Stype.LoadFromFile(string fileName)
References SDC.base64Binary_Stype.Deserialize, SDC.null.