SDC::CodeSystemType
string_Stype SDC.CodeSystemType::_codeSystemName
Referenced by SDC.CodeSystemType.ShouldSerializeCodeSystemName.
dateTime_Stype SDC.CodeSystemType::_releaseDate
Referenced by SDC.CodeSystemType.ShouldSerializeReleaseDate.
string_Stype SDC.CodeSystemType::_version
Referenced by SDC.CodeSystemType.ShouldSerializeVersion.
string_Stype SDC.CodeSystemType::_oID
Referenced by SDC.CodeSystemType.ShouldSerializeOID.
anyURI_Stype SDC.CodeSystemType::_codeSystemURI
Referenced by SDC.CodeSystemType.ShouldSerializeCodeSystemURI.
ObjectChangeTracker SDC.CodeSystemType.changeTrackerField
static XmlSerializer SDC.CodeSystemType::serializer
string_Stype SDC.CodeSystemType::CodeSystemName
The name of the coding system, as recommended by the coding system curators, or as recommended by the agency that creates standards for the code map in use.
dateTime_Stype SDC.CodeSystemType::ReleaseDate
The day that the selected version of the coding system was released for general use by the coding system curators.
string_Stype SDC.CodeSystemType::Version
Version of the coding system, using the version format defined by the coding system
string_Stype SDC.CodeSystemType::OID
The ISO object identifier (OID) for the coding system, as found at the HL7 OID Registry: https://www.hl7.org/oid/index.cfm
anyURI_Stype SDC.CodeSystemType::CodeSystemURI
Web resource that uniquely identifies the coding system
static XmlSerializer SDC.CodeSystemType::Serializer
Referenced by SDC.CodeSystemType.Deserialize.
ObjectChangeTracker SDC.CodeSystemType.ChangeTracker
SDC.CodeSystemType.CodeSystemType()
SDC.CodeSystemType.CodeSystemType(BaseType parentNode, bool fillData=true)
virtual bool SDC.CodeSystemType.ShouldSerializeCodeSystemName()
Test whether CodeSystemName should be serialized
References SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeReleaseDate()
Test whether ReleaseDate should be serialized
References SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeVersion()
Test whether Version should be serialized
References SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeOID()
Test whether OID should be serialized
References SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeCodeSystemURI()
Test whether CodeSystemURI should be serialized
References SDC.null.
virtual string SDC.CodeSystemType.Serialize(System.Text.Encoding encoding)
Serializes current CodeSystemType object into an XML string
string XML value
virtual string SDC.CodeSystemType.Serialize()
Referenced by SDC.CodeSystemType.SaveToFile.
virtual bool SDC.CodeSystemType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current CodeSystemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.CodeSystemType.SaveToFile.
virtual bool SDC.CodeSystemType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.CodeSystemType.SaveToFile(string fileName)
virtual void SDC.CodeSystemType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeCodeSystemName()
Test whether CodeSystemName should be serialized
References SDC.CodeSystemType._codeSystemName, SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeReleaseDate()
Test whether ReleaseDate should be serialized
References SDC.CodeSystemType._releaseDate, SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeVersion()
Test whether Version should be serialized
References SDC.CodeSystemType._version, SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeOID()
Test whether OID should be serialized
References SDC.CodeSystemType._oID, SDC.null.
virtual bool SDC.CodeSystemType.ShouldSerializeCodeSystemURI()
Test whether CodeSystemURI should be serialized
References SDC.CodeSystemType._codeSystemURI, SDC.null.
virtual string SDC.CodeSystemType.Serialize()
Serializes current CodeSystemType object into an XML string
string XML value
virtual bool SDC.CodeSystemType.SaveToFile(string fileName, out Exception exception)
Serializes current CodeSystemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.CodeSystemType.SaveToFile.
virtual void SDC.CodeSystemType.SaveToFile(string fileName)
References SDC.null, SDC.CodeSystemType.Serialize.
virtual CodeSystemType SDC.CodeSystemType.Clone()
Create a clone of this CodeSystemType object
static bool SDC.CodeSystemType.Deserialize(string input, out CodeSystemType obj, out System.Exception exception)
Deserializes workflow markup into an CodeSystemType object
input string workflow markup to deserialize obj Output CodeSystemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CodeSystemType.Deserialize, SDC.CodeSystemType.LoadFromFile.
static bool SDC.CodeSystemType.Deserialize(string input, out CodeSystemType obj)
References SDC.null.
static new CodeSystemType SDC.CodeSystemType.Deserialize(string input)
References SDC.null.
static CodeSystemType SDC.CodeSystemType.Deserialize(System.IO.Stream s)
static bool SDC.CodeSystemType.LoadFromFile(string fileName, System.Text.Encoding encoding, out CodeSystemType obj, out System.Exception exception)
Deserializes xml markup from file into an CodeSystemType object
fileName string xml file to load and deserialize obj Output CodeSystemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CodeSystemType.LoadFromFile.
static bool SDC.CodeSystemType.LoadFromFile(string fileName, out CodeSystemType obj, out System.Exception exception)
static bool SDC.CodeSystemType.LoadFromFile(string fileName, out CodeSystemType obj)
References SDC.null.
static CodeSystemType SDC.CodeSystemType.LoadFromFile(string fileName)
static new CodeSystemType SDC.CodeSystemType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.CodeSystemType.Deserialize(string input, out CodeSystemType obj, out Exception exception)
Deserializes workflow markup into an CodeSystemType object
input string workflow markup to deserialize obj Output CodeSystemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CodeSystemType.Deserialize, SDC.null.
static bool SDC.CodeSystemType.Deserialize(string input, out CodeSystemType obj)
References SDC.CodeSystemType.Deserialize, SDC.null.
static new CodeSystemType SDC.CodeSystemType.Deserialize(string input)
References SDC.null, SDC.CodeSystemType.Serializer.
static CodeSystemType SDC.CodeSystemType.Deserialize(Stream s)
References SDC.CodeSystemType.Serializer.
static bool SDC.CodeSystemType.LoadFromFile(string fileName, out CodeSystemType obj, out Exception exception)
Deserializes xml markup from file into an CodeSystemType object
fileName string xml file to load and deserialize obj Output CodeSystemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CodeSystemType.LoadFromFile, SDC.null.
static bool SDC.CodeSystemType.LoadFromFile(string fileName, out CodeSystemType obj)
References SDC.CodeSystemType.LoadFromFile, SDC.null.
static new CodeSystemType SDC.CodeSystemType.LoadFromFile(string fileName)
References SDC.CodeSystemType.Deserialize, SDC.null.