SDC::SubmissionRuleType
List<DestinationType> SDC.SubmissionRuleType._destination
string_Stype SDC.SubmissionRuleType::_ruleDescription
Referenced by SDC.SubmissionRuleType.ShouldSerializeRuleDescription.
string SDC.SubmissionRuleType::_formID
string SDC.SubmissionRuleType::_ruleID
BindingList<DestinationType> SDC.SubmissionRuleType._destination
ObjectChangeTracker SDC.SubmissionRuleType.changeTrackerField
static XmlSerializer SDC.SubmissionRuleType::serializer
virtual List<DestinationType> SDC.SubmissionRuleType.Destination
string_Stype SDC.SubmissionRuleType::RuleDescription
string SDC.SubmissionRuleType::formID
Referenced by SDC.SubmissionRuleType.ShouldSerializeformID.
string SDC.SubmissionRuleType::ruleID
Referenced by SDC.SubmissionRuleType.ShouldSerializeruleID.
static XmlSerializer SDC.SubmissionRuleType::Serializer
Referenced by SDC.SubmissionRuleType.Deserialize.
virtual BindingList<DestinationType> SDC.SubmissionRuleType.Destination
ObjectChangeTracker SDC.SubmissionRuleType.ChangeTracker
SDC.SubmissionRuleType.SubmissionRuleType()
SDC.SubmissionRuleType.SubmissionRuleType(BaseType parentNode)
virtual bool SDC.SubmissionRuleType.ShouldSerializeDestination()
Test whether Destination should be serialized
References SDC.null.
virtual bool SDC.SubmissionRuleType.ShouldSerializeRuleDescription()
Test whether RuleDescription should be serialized
References SDC.null.
virtual bool SDC.SubmissionRuleType.ShouldSerializeformID()
Test whether formID should be serialized
virtual bool SDC.SubmissionRuleType.ShouldSerializeruleID()
Test whether ruleID should be serialized
virtual string SDC.SubmissionRuleType.Serialize(System.Text.Encoding encoding)
Serializes current SubmissionRuleType object into an XML string
string XML value
virtual string SDC.SubmissionRuleType.Serialize()
Referenced by SDC.SubmissionRuleType.SaveToFile.
virtual bool SDC.SubmissionRuleType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current SubmissionRuleType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.SubmissionRuleType.SaveToFile.
virtual bool SDC.SubmissionRuleType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.SubmissionRuleType.SaveToFile(string fileName)
virtual void SDC.SubmissionRuleType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.SubmissionRuleType.ShouldSerializeRuleDescription()
Test whether RuleDescription should be serialized
References SDC.SubmissionRuleType._ruleDescription, SDC.null.
virtual bool SDC.SubmissionRuleType.ShouldSerializeformID()
Test whether formID should be serialized
References SDC.SubmissionRuleType.formID.
virtual bool SDC.SubmissionRuleType.ShouldSerializeruleID()
Test whether ruleID should be serialized
References SDC.SubmissionRuleType.ruleID.
virtual string SDC.SubmissionRuleType.Serialize()
Serializes current SubmissionRuleType object into an XML string
string XML value
virtual bool SDC.SubmissionRuleType.SaveToFile(string fileName, out Exception exception)
Serializes current SubmissionRuleType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.SubmissionRuleType.SaveToFile.
virtual void SDC.SubmissionRuleType.SaveToFile(string fileName)
References SDC.null, SDC.SubmissionRuleType.Serialize.
virtual SubmissionRuleType SDC.SubmissionRuleType.Clone()
Create a clone of this SubmissionRuleType object
static bool SDC.SubmissionRuleType.Deserialize(string input, out SubmissionRuleType obj, out System.Exception exception)
Deserializes workflow markup into an SubmissionRuleType object
input string workflow markup to deserialize obj Output SubmissionRuleType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.SubmissionRuleType.Deserialize, SDC.SubmissionRuleType.LoadFromFile.
static bool SDC.SubmissionRuleType.Deserialize(string input, out SubmissionRuleType obj)
References SDC.null.
static new SubmissionRuleType SDC.SubmissionRuleType.Deserialize(string input)
References SDC.null.
static SubmissionRuleType SDC.SubmissionRuleType.Deserialize(System.IO.Stream s)
static bool SDC.SubmissionRuleType.LoadFromFile(string fileName, System.Text.Encoding encoding, out SubmissionRuleType obj, out System.Exception exception)
Deserializes xml markup from file into an SubmissionRuleType object
fileName string xml file to load and deserialize obj Output SubmissionRuleType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.SubmissionRuleType.LoadFromFile.
static bool SDC.SubmissionRuleType.LoadFromFile(string fileName, out SubmissionRuleType obj, out System.Exception exception)
static bool SDC.SubmissionRuleType.LoadFromFile(string fileName, out SubmissionRuleType obj)
References SDC.null.
static SubmissionRuleType SDC.SubmissionRuleType.LoadFromFile(string fileName)
static new SubmissionRuleType SDC.SubmissionRuleType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.SubmissionRuleType.Deserialize(string input, out SubmissionRuleType obj, out Exception exception)
Deserializes workflow markup into an SubmissionRuleType object
input string workflow markup to deserialize obj Output SubmissionRuleType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.SubmissionRuleType.Deserialize, SDC.null.
static bool SDC.SubmissionRuleType.Deserialize(string input, out SubmissionRuleType obj)
References SDC.SubmissionRuleType.Deserialize, SDC.null.
static new SubmissionRuleType SDC.SubmissionRuleType.Deserialize(string input)
References SDC.null, SDC.SubmissionRuleType.Serializer.
static SubmissionRuleType SDC.SubmissionRuleType.Deserialize(Stream s)
References SDC.SubmissionRuleType.Serializer.
static bool SDC.SubmissionRuleType.LoadFromFile(string fileName, out SubmissionRuleType obj, out Exception exception)
Deserializes xml markup from file into an SubmissionRuleType object
fileName string xml file to load and deserialize obj Output SubmissionRuleType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.SubmissionRuleType.LoadFromFile, SDC.null.
static bool SDC.SubmissionRuleType.LoadFromFile(string fileName, out SubmissionRuleType obj)
References SDC.SubmissionRuleType.LoadFromFile, SDC.null.
static new SubmissionRuleType SDC.SubmissionRuleType.LoadFromFile(string fileName)
References SDC.SubmissionRuleType.Deserialize, SDC.null.