SDC::RepeatingType
bool SDC.RepeatingType::_shouldSerializemaxCard
Referenced by SDC.RepeatingType.ShouldSerializemaxCard.
bool SDC.RepeatingType::_shouldSerializeminCard
Referenced by SDC.RepeatingType.ShouldSerializeminCard.
ushort SDC.RepeatingType::_minCard
Referenced by SDC.RepeatingType.RepeatingType, SDC.RepeatingType.ShouldSerializeminCard.
ushort SDC.RepeatingType::_maxCard
Referenced by SDC.RepeatingType.RepeatingType, SDC.RepeatingType.ShouldSerializemaxCard.
string SDC.RepeatingType::_repeat
Referenced by SDC.RepeatingType.RepeatingType.
string SDC.RepeatingType::_instanceGUID
string SDC.RepeatingType::_parentGUID
ObjectChangeTracker SDC.RepeatingType.changeTrackerField
static XmlSerializer SDC.RepeatingType::serializer
ushort SDC.RepeatingType::minCard
RepeatingType class constructor
is the minimum number of repetitions allowed for a section or question. The default value is 1, indicating that the user must answer any question(s) that has this attribute set. If is set to 0, then the item and all descendent questions are optional to answer.
Referenced by SDC.SDCTreeBuilderEcc.FillRepeatingTypeItemData.
ushort SDC.RepeatingType::maxCard
is the maximum number of repetitions allowed for a section or question. The default value is 1, indicating that the section or question cannot be repeated on the data entry form. A value of 0 indicates that the number of repeats is unlimited. If is not 0, then Must be greater than or equal to minCard.
string SDC.RepeatingType::repeat
Referenced by SDC.RepeatingType.ShouldSerializerepeat.
string SDC.RepeatingType::instanceGUID
Referenced by SDC.RepeatingType.ShouldSerializeinstanceGUID.
string SDC.RepeatingType::parentGUID
Referenced by SDC.RepeatingType.ShouldSerializeparentGUID.
static XmlSerializer SDC.RepeatingType::Serializer
Referenced by SDC.RepeatingType.Deserialize.
ObjectChangeTracker SDC.RepeatingType.ChangeTracker
SDC.RepeatingType.RepeatingType()
SDC.RepeatingType.RepeatingType(BaseType parentNode, bool fillData=true, string id=null)
void SDC.RepeatingType.Fill_RepeatingType()
virtual bool SDC.RepeatingType.ShouldSerializeminCard()
Test whether minCard should be serialized
virtual bool SDC.RepeatingType.ShouldSerializemaxCard()
Test whether maxCard should be serialized
virtual bool SDC.RepeatingType.ShouldSerializerepeat()
Test whether repeat should be serialized
virtual bool SDC.RepeatingType.ShouldSerializeinstanceGUID()
Test whether instanceGUID should be serialized
virtual bool SDC.RepeatingType.ShouldSerializeparentGUID()
Test whether parentGUID should be serialized
virtual string SDC.RepeatingType.Serialize(System.Text.Encoding encoding)
Serializes current RepeatingType object into an XML string
string XML value
virtual string SDC.RepeatingType.Serialize()
Referenced by SDC.RepeatingType.SaveToFile.
virtual bool SDC.RepeatingType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current RepeatingType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.RepeatingType.SaveToFile.
virtual bool SDC.RepeatingType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.RepeatingType.SaveToFile(string fileName)
virtual void SDC.RepeatingType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.RepeatingType.RepeatingType()
RepeatingType class constructor
References SDC.RepeatingType._maxCard, SDC.RepeatingType._minCard, SDC.RepeatingType._repeat.
virtual bool SDC.RepeatingType.ShouldSerializeminCard()
Test whether minCard should be serialized
References SDC.RepeatingType._minCard, SDC.RepeatingType._shouldSerializeminCard.
virtual bool SDC.RepeatingType.ShouldSerializemaxCard()
Test whether maxCard should be serialized
References SDC.RepeatingType._maxCard, SDC.RepeatingType._shouldSerializemaxCard.
virtual bool SDC.RepeatingType.ShouldSerializerepeat()
Test whether repeat should be serialized
References SDC.RepeatingType.repeat.
virtual bool SDC.RepeatingType.ShouldSerializeinstanceGUID()
Test whether instanceGUID should be serialized
References SDC.RepeatingType.instanceGUID.
virtual bool SDC.RepeatingType.ShouldSerializeparentGUID()
Test whether parentGUID should be serialized
References SDC.RepeatingType.parentGUID.
virtual string SDC.RepeatingType.Serialize()
Serializes current RepeatingType object into an XML string
string XML value
virtual bool SDC.RepeatingType.SaveToFile(string fileName, out Exception exception)
Serializes current RepeatingType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.RepeatingType.SaveToFile.
virtual void SDC.RepeatingType.SaveToFile(string fileName)
References SDC.null, SDC.RepeatingType.Serialize.
virtual RepeatingType SDC.RepeatingType.Clone()
Create a clone of this RepeatingType object
static bool SDC.RepeatingType.Deserialize(string input, out RepeatingType obj, out System.Exception exception)
Deserializes workflow markup into an RepeatingType object
input string workflow markup to deserialize obj Output RepeatingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.RepeatingType.Deserialize, SDC.RepeatingType.LoadFromFile.
static bool SDC.RepeatingType.Deserialize(string input, out RepeatingType obj)
References SDC.null.
static new RepeatingType SDC.RepeatingType.Deserialize(string input)
References SDC.null.
static RepeatingType SDC.RepeatingType.Deserialize(System.IO.Stream s)
static bool SDC.RepeatingType.LoadFromFile(string fileName, System.Text.Encoding encoding, out RepeatingType obj, out System.Exception exception)
Deserializes xml markup from file into an RepeatingType object
fileName string xml file to load and deserialize obj Output RepeatingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.RepeatingType.LoadFromFile.
static bool SDC.RepeatingType.LoadFromFile(string fileName, out RepeatingType obj, out System.Exception exception)
static bool SDC.RepeatingType.LoadFromFile(string fileName, out RepeatingType obj)
References SDC.null.
static RepeatingType SDC.RepeatingType.LoadFromFile(string fileName)
static new RepeatingType SDC.RepeatingType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.RepeatingType.Deserialize(string input, out RepeatingType obj, out Exception exception)
Deserializes workflow markup into an RepeatingType object
input string workflow markup to deserialize obj Output RepeatingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.RepeatingType.Deserialize, SDC.null.
static bool SDC.RepeatingType.Deserialize(string input, out RepeatingType obj)
References SDC.RepeatingType.Deserialize, SDC.null.
static new RepeatingType SDC.RepeatingType.Deserialize(string input)
References SDC.null, SDC.RepeatingType.Serializer.
static RepeatingType SDC.RepeatingType.Deserialize(Stream s)
References SDC.RepeatingType.Serializer.
static bool SDC.RepeatingType.LoadFromFile(string fileName, out RepeatingType obj, out Exception exception)
Deserializes xml markup from file into an RepeatingType object
fileName string xml file to load and deserialize obj Output RepeatingType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.RepeatingType.LoadFromFile, SDC.null.
static bool SDC.RepeatingType.LoadFromFile(string fileName, out RepeatingType obj)
References SDC.RepeatingType.LoadFromFile, SDC.null.
static new RepeatingType SDC.RepeatingType.LoadFromFile(string fileName)
References SDC.RepeatingType.Deserialize, SDC.null.