SDC::positiveInteger_DEtype
string SDC.positiveInteger_DEtype::_minInclusive
string SDC.positiveInteger_DEtype::_maxInclusive
string SDC.positiveInteger_DEtype::_minExclusive
string SDC.positiveInteger_DEtype::_maxExclusive
System Nullable< byte > SDC.positiveInteger_DEtype::_totalDigits
string SDC.positiveInteger_DEtype::_mask
ObjectChangeTracker SDC.positiveInteger_DEtype.changeTrackerField
static XmlSerializer SDC.positiveInteger_DEtype::serializer
string SDC.positiveInteger_DEtype::minInclusive
Referenced by SDC.positiveInteger_DEtype.ShouldSerializeminInclusive.
string SDC.positiveInteger_DEtype::maxInclusive
Referenced by SDC.positiveInteger_DEtype.ShouldSerializemaxInclusive.
string SDC.positiveInteger_DEtype::minExclusive
Referenced by SDC.positiveInteger_DEtype.ShouldSerializeminExclusive.
string SDC.positiveInteger_DEtype::maxExclusive
Referenced by SDC.positiveInteger_DEtype.ShouldSerializemaxExclusive.
byte SDC.positiveInteger_DEtype::totalDigits
bool SDC.positiveInteger_DEtype::totalDigitsSpecified
string SDC.positiveInteger_DEtype::mask
Referenced by SDC.positiveInteger_DEtype.ShouldSerializemask.
static XmlSerializer SDC.positiveInteger_DEtype::Serializer
Referenced by SDC.positiveInteger_DEtype.Deserialize.
ObjectChangeTracker SDC.positiveInteger_DEtype.ChangeTracker
SDC.positiveInteger_DEtype.positiveInteger_DEtype()
SDC.positiveInteger_DEtype.positiveInteger_DEtype(BaseType parentNode)
virtual bool SDC.positiveInteger_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.positiveInteger_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.positiveInteger_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.positiveInteger_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.positiveInteger_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.positiveInteger_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current positiveInteger_DEtype object into an XML string
string XML value
virtual string SDC.positiveInteger_DEtype.Serialize()
Referenced by SDC.positiveInteger_DEtype.SaveToFile.
virtual bool SDC.positiveInteger_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current positiveInteger_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.positiveInteger_DEtype.SaveToFile.
virtual bool SDC.positiveInteger_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.positiveInteger_DEtype.SaveToFile(string fileName)
virtual void SDC.positiveInteger_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.positiveInteger_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.positiveInteger_DEtype.minInclusive.
virtual bool SDC.positiveInteger_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.positiveInteger_DEtype.maxInclusive.
virtual bool SDC.positiveInteger_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.positiveInteger_DEtype.minExclusive.
virtual bool SDC.positiveInteger_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.positiveInteger_DEtype.maxExclusive.
virtual bool SDC.positiveInteger_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.positiveInteger_DEtype.mask.
virtual string SDC.positiveInteger_DEtype.Serialize()
Serializes current positiveInteger_DEtype object into an XML string
string XML value
virtual bool SDC.positiveInteger_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current positiveInteger_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.positiveInteger_DEtype.SaveToFile.
virtual void SDC.positiveInteger_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.positiveInteger_DEtype.Serialize.
virtual positiveInteger_DEtype SDC.positiveInteger_DEtype.Clone()
Create a clone of this positiveInteger_DEtype object
static bool SDC.positiveInteger_DEtype.Deserialize(string input, out positiveInteger_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an positiveInteger_DEtype object
input string workflow markup to deserialize obj Output positiveInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.positiveInteger_DEtype.Deserialize, SDC.positiveInteger_DEtype.LoadFromFile.
static bool SDC.positiveInteger_DEtype.Deserialize(string input, out positiveInteger_DEtype obj)
References SDC.null.
static new positiveInteger_DEtype SDC.positiveInteger_DEtype.Deserialize(string input)
References SDC.null.
static positiveInteger_DEtype SDC.positiveInteger_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.positiveInteger_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out positiveInteger_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an positiveInteger_DEtype object
fileName string xml file to load and deserialize obj Output positiveInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.positiveInteger_DEtype.LoadFromFile.
static bool SDC.positiveInteger_DEtype.LoadFromFile(string fileName, out positiveInteger_DEtype obj, out System.Exception exception)
static bool SDC.positiveInteger_DEtype.LoadFromFile(string fileName, out positiveInteger_DEtype obj)
References SDC.null.
static positiveInteger_DEtype SDC.positiveInteger_DEtype.LoadFromFile(string fileName)
static new positiveInteger_DEtype SDC.positiveInteger_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.positiveInteger_DEtype.Deserialize(string input, out positiveInteger_DEtype obj, out Exception exception)
Deserializes workflow markup into an positiveInteger_DEtype object
input string workflow markup to deserialize obj Output positiveInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.positiveInteger_DEtype.Deserialize, SDC.null.
static bool SDC.positiveInteger_DEtype.Deserialize(string input, out positiveInteger_DEtype obj)
References SDC.positiveInteger_DEtype.Deserialize, SDC.null.
static new positiveInteger_DEtype SDC.positiveInteger_DEtype.Deserialize(string input)
References SDC.null, SDC.positiveInteger_DEtype.Serializer.
static positiveInteger_DEtype SDC.positiveInteger_DEtype.Deserialize(Stream s)
References SDC.positiveInteger_DEtype.Serializer.
static bool SDC.positiveInteger_DEtype.LoadFromFile(string fileName, out positiveInteger_DEtype obj, out Exception exception)
Deserializes xml markup from file into an positiveInteger_DEtype object
fileName string xml file to load and deserialize obj Output positiveInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.positiveInteger_DEtype.LoadFromFile, SDC.null.
static bool SDC.positiveInteger_DEtype.LoadFromFile(string fileName, out positiveInteger_DEtype obj)
References SDC.positiveInteger_DEtype.LoadFromFile, SDC.null.
static new positiveInteger_DEtype SDC.positiveInteger_DEtype.LoadFromFile(string fileName)
References SDC.positiveInteger_DEtype.Deserialize, SDC.null.