SDC::RulesType
virtual BindingList<IfThenType> SDC.RulesType.ReferenceRule
static XmlSerializer SDC.RulesType::Serializer
Referenced by SDC.RulesType.Deserialize.
virtual BindingList<ExclusiveItemPairsType> SDC.RulesType.ExclusiveListItems
ObjectChangeTracker SDC.RulesType.ChangeTracker
virtual string SDC.RulesType.Serialize()
Serializes current RulesType object into an XML string
string XML value
virtual bool SDC.RulesType.SaveToFile(string fileName, out Exception exception)
Serializes current RulesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.RulesType.SaveToFile.
virtual void SDC.RulesType.SaveToFile(string fileName)
References SDC.null, SDC.RulesType.Serialize.
virtual RulesType SDC.RulesType.Clone()
Create a clone of this RulesType object
static bool SDC.RulesType.Deserialize(string input, out RulesType obj, out Exception exception)
Deserializes workflow markup into an RulesType object
input string workflow markup to deserialize obj Output RulesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.RulesType.Deserialize, SDC.null.
static bool SDC.RulesType.Deserialize(string input, out RulesType obj)
References SDC.RulesType.Deserialize, SDC.null.
static new RulesType SDC.RulesType.Deserialize(string input)
References SDC.null, SDC.RulesType.Serializer.
static RulesType SDC.RulesType.Deserialize(Stream s)
References SDC.RulesType.Serializer.
static bool SDC.RulesType.LoadFromFile(string fileName, out RulesType obj, out Exception exception)
Deserializes xml markup from file into an RulesType object
fileName string xml file to load and deserialize obj Output RulesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.RulesType.LoadFromFile, SDC.null.
static bool SDC.RulesType.LoadFromFile(string fileName, out RulesType obj)
References SDC.RulesType.LoadFromFile, SDC.null.
static new RulesType SDC.RulesType.LoadFromFile(string fileName)
References SDC.RulesType.Deserialize, SDC.null.
RulesCollectionType [] SDC.RulesType._items
ItemsChoiceType [] SDC.RulesType._itemsElementName
BindingList<IfThenType> SDC.RulesType._pollingRule
BindingList<IfThenType> SDC.RulesType._validationRule
BindingList<IfThenType> SDC.RulesType._referenceRule
BindingList<ExclusiveItemPairsType> SDC.RulesType._exclusiveListItems
ObjectChangeTracker SDC.RulesType.changeTrackerField
static XmlSerializer SDC.RulesType::serializer
virtual RulesCollectionType [] SDC.RulesType.Items
virtual ItemsChoiceType [] SDC.RulesType.ItemsElementName
virtual BindingList<IfThenType> SDC.RulesType.PollingRule
Polling rules run "If clauses" periodically (e.g., when a user changes a response value or clicks a ListItem) and run any indicated "Then clause." In general, these rules should run without the need for any user interaction. The form can use the observer (publish-subscribe or event) pattern to implement this functionality.
virtual BindingList<IfThenType> SDC.RulesType.ValidationRule
A validation rule or set of rules is run only when the user requests that a form validation should be run, and/or at the time the user submits the form data to a form receiver. The implementation must supply a button or other mechanism to run the validation rule(s).
SDC.RulesType.RulesType()
SDC.RulesType.RulesType(BaseType parentNode)
SDC.RulesType.RulesType()
virtual string SDC.RulesType.Serialize(System.Text.Encoding encoding)
Serializes current RulesType object into an XML string
string XML value
virtual string SDC.RulesType.Serialize()
Referenced by SDC.RulesType.SaveToFile.
virtual bool SDC.RulesType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current RulesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.RulesType.SaveToFile.
virtual bool SDC.RulesType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.RulesType.SaveToFile(string fileName)
virtual void SDC.RulesType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.RulesType.Deserialize(string input, out RulesType obj, out System.Exception exception)
Deserializes workflow markup into an RulesType object
input string workflow markup to deserialize obj Output RulesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.RulesType.Deserialize, SDC.RulesType.LoadFromFile.
static bool SDC.RulesType.Deserialize(string input, out RulesType obj)
References SDC.null.
static new RulesType SDC.RulesType.Deserialize(string input)
References SDC.null.
static RulesType SDC.RulesType.Deserialize(System.IO.Stream s)
static bool SDC.RulesType.LoadFromFile(string fileName, System.Text.Encoding encoding, out RulesType obj, out System.Exception exception)
Deserializes xml markup from file into an RulesType object
fileName string xml file to load and deserialize obj Output RulesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.RulesType.LoadFromFile.
static bool SDC.RulesType.LoadFromFile(string fileName, out RulesType obj, out System.Exception exception)
static bool SDC.RulesType.LoadFromFile(string fileName, out RulesType obj)
References SDC.null.
static RulesType SDC.RulesType.LoadFromFile(string fileName)
static new RulesType SDC.RulesType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.