SDC::nonNegativeInteger_Stype
string SDC.nonNegativeInteger_Stype::_val
dtQuantEnum SDC.nonNegativeInteger_Stype::_quantEnum
Referenced by SDC.nonNegativeInteger_Stype.nonNegativeInteger_Stype.
ObjectChangeTracker SDC.nonNegativeInteger_Stype.changeTrackerField
static XmlSerializer SDC.nonNegativeInteger_Stype::serializer
string SDC.nonNegativeInteger_Stype::val
Referenced by SDC.nonNegativeInteger_Stype.ShouldSerializeval.
dtQuantEnum SDC.nonNegativeInteger_Stype::quantEnum
static XmlSerializer SDC.nonNegativeInteger_Stype::Serializer
Referenced by SDC.nonNegativeInteger_Stype.Deserialize.
ObjectChangeTracker SDC.nonNegativeInteger_Stype.ChangeTracker
SDC.nonNegativeInteger_Stype.nonNegativeInteger_Stype()
SDC.nonNegativeInteger_Stype.nonNegativeInteger_Stype(BaseType parentNode)
virtual bool SDC.nonNegativeInteger_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.nonNegativeInteger_Stype.val.
virtual string SDC.nonNegativeInteger_Stype.Serialize(System.Text.Encoding encoding)
Serializes current nonNegativeInteger_Stype object into an XML string
string XML value
virtual string SDC.nonNegativeInteger_Stype.Serialize()
Referenced by SDC.nonNegativeInteger_Stype.SaveToFile.
virtual bool SDC.nonNegativeInteger_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current nonNegativeInteger_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.nonNegativeInteger_Stype.SaveToFile.
virtual bool SDC.nonNegativeInteger_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.nonNegativeInteger_Stype.SaveToFile.
virtual void SDC.nonNegativeInteger_Stype.SaveToFile(string fileName)
References SDC.nonNegativeInteger_Stype.SaveToFile.
virtual void SDC.nonNegativeInteger_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.nonNegativeInteger_Stype.Serialize.
SDC.nonNegativeInteger_Stype.nonNegativeInteger_Stype()
nonNegativeInteger_Stype class constructor
References SDC.nonNegativeInteger_Stype._quantEnum.
virtual bool SDC.nonNegativeInteger_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.nonNegativeInteger_Stype.val.
virtual string SDC.nonNegativeInteger_Stype.Serialize()
Serializes current nonNegativeInteger_Stype object into an XML string
string XML value
virtual bool SDC.nonNegativeInteger_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current nonNegativeInteger_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.nonNegativeInteger_Stype.SaveToFile.
virtual void SDC.nonNegativeInteger_Stype.SaveToFile(string fileName)
References SDC.null, SDC.nonNegativeInteger_Stype.Serialize.
virtual nonNegativeInteger_Stype SDC.nonNegativeInteger_Stype.Clone()
Create a clone of this nonNegativeInteger_Stype object
static bool SDC.nonNegativeInteger_Stype.Deserialize(string input, out nonNegativeInteger_Stype obj, out System.Exception exception)
Deserializes workflow markup into an nonNegativeInteger_Stype object
input string workflow markup to deserialize obj Output nonNegativeInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.nonNegativeInteger_Stype.Deserialize, SDC.nonNegativeInteger_Stype.LoadFromFile.
static bool SDC.nonNegativeInteger_Stype.Deserialize(string input, out nonNegativeInteger_Stype obj)
References SDC.nonNegativeInteger_Stype.Deserialize, SDC.null.
static new nonNegativeInteger_Stype SDC.nonNegativeInteger_Stype.Deserialize(string input)
References SDC.null.
static nonNegativeInteger_Stype SDC.nonNegativeInteger_Stype.Deserialize(System.IO.Stream s)
References SDC.nonNegativeInteger_Stype.Serializer.
static bool SDC.nonNegativeInteger_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out nonNegativeInteger_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an nonNegativeInteger_Stype object
fileName string xml file to load and deserialize obj Output nonNegativeInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.nonNegativeInteger_Stype.LoadFromFile.
static bool SDC.nonNegativeInteger_Stype.LoadFromFile(string fileName, out nonNegativeInteger_Stype obj, out System.Exception exception)
References SDC.nonNegativeInteger_Stype.LoadFromFile.
static bool SDC.nonNegativeInteger_Stype.LoadFromFile(string fileName, out nonNegativeInteger_Stype obj)
References SDC.nonNegativeInteger_Stype.LoadFromFile, SDC.null.
static nonNegativeInteger_Stype SDC.nonNegativeInteger_Stype.LoadFromFile(string fileName)
References SDC.nonNegativeInteger_Stype.LoadFromFile.
static new nonNegativeInteger_Stype SDC.nonNegativeInteger_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.nonNegativeInteger_Stype.Deserialize, SDC.null.
static bool SDC.nonNegativeInteger_Stype.Deserialize(string input, out nonNegativeInteger_Stype obj, out Exception exception)
Deserializes workflow markup into an nonNegativeInteger_Stype object
input string workflow markup to deserialize obj Output nonNegativeInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.nonNegativeInteger_Stype.Deserialize, SDC.null.
static bool SDC.nonNegativeInteger_Stype.Deserialize(string input, out nonNegativeInteger_Stype obj)
References SDC.nonNegativeInteger_Stype.Deserialize, SDC.null.
static new nonNegativeInteger_Stype SDC.nonNegativeInteger_Stype.Deserialize(string input)
References SDC.null, SDC.nonNegativeInteger_Stype.Serializer.
static nonNegativeInteger_Stype SDC.nonNegativeInteger_Stype.Deserialize(Stream s)
References SDC.nonNegativeInteger_Stype.Serializer.
static bool SDC.nonNegativeInteger_Stype.LoadFromFile(string fileName, out nonNegativeInteger_Stype obj, out Exception exception)
Deserializes xml markup from file into an nonNegativeInteger_Stype object
fileName string xml file to load and deserialize obj Output nonNegativeInteger_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.nonNegativeInteger_Stype.LoadFromFile, SDC.null.
static bool SDC.nonNegativeInteger_Stype.LoadFromFile(string fileName, out nonNegativeInteger_Stype obj)
References SDC.nonNegativeInteger_Stype.LoadFromFile, SDC.null.
static new nonNegativeInteger_Stype SDC.nonNegativeInteger_Stype.LoadFromFile(string fileName)
References SDC.nonNegativeInteger_Stype.Deserialize, SDC.null.