SDC::ContactsType
List<ContactType> SDC.ContactsType._contact
BindingList<ContactType> SDC.ContactsType._contact
ObjectChangeTracker SDC.ContactsType.changeTrackerField
static XmlSerializer SDC.ContactsType::serializer
virtual List<ContactType> SDC.ContactsType.Contact
static XmlSerializer SDC.ContactsType::Serializer
Referenced by SDC.ContactsType.Deserialize.
virtual BindingList<ContactType> SDC.ContactsType.Contact
ObjectChangeTracker SDC.ContactsType.ChangeTracker
SDC.ContactsType.ContactsType(BaseType parentNode)
virtual bool SDC.ContactsType.ShouldSerializeContact()
Test whether Contact should be serialized
References SDC.null.
virtual string SDC.ContactsType.Serialize(System.Text.Encoding encoding)
Serializes current ContactsType object into an XML string
string XML value
virtual string SDC.ContactsType.Serialize()
Referenced by SDC.ContactsType.SaveToFile.
virtual bool SDC.ContactsType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ContactsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ContactsType.SaveToFile.
virtual bool SDC.ContactsType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ContactsType.SaveToFile(string fileName)
virtual void SDC.ContactsType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ContactsType.Serialize()
Serializes current ContactsType object into an XML string
string XML value
virtual bool SDC.ContactsType.SaveToFile(string fileName, out Exception exception)
Serializes current ContactsType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ContactsType.SaveToFile.
virtual void SDC.ContactsType.SaveToFile(string fileName)
References SDC.null, SDC.ContactsType.Serialize.
virtual ContactsType SDC.ContactsType.Clone()
Create a clone of this ContactsType object
SDC.ContactsType.ContactsType()
static bool SDC.ContactsType.Deserialize(string input, out ContactsType obj, out System.Exception exception)
Deserializes workflow markup into an ContactsType object
input string workflow markup to deserialize obj Output ContactsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ContactsType.Deserialize, SDC.ContactsType.LoadFromFile.
static bool SDC.ContactsType.Deserialize(string input, out ContactsType obj)
References SDC.null.
static new ContactsType SDC.ContactsType.Deserialize(string input)
References SDC.null.
static ContactsType SDC.ContactsType.Deserialize(System.IO.Stream s)
static bool SDC.ContactsType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ContactsType obj, out System.Exception exception)
Deserializes xml markup from file into an ContactsType object
fileName string xml file to load and deserialize obj Output ContactsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ContactsType.LoadFromFile.
static bool SDC.ContactsType.LoadFromFile(string fileName, out ContactsType obj, out System.Exception exception)
static bool SDC.ContactsType.LoadFromFile(string fileName, out ContactsType obj)
References SDC.null.
static ContactsType SDC.ContactsType.LoadFromFile(string fileName)
static new ContactsType SDC.ContactsType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ContactsType.Deserialize(string input, out ContactsType obj, out Exception exception)
Deserializes workflow markup into an ContactsType object
input string workflow markup to deserialize obj Output ContactsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ContactsType.Deserialize, SDC.null.
static bool SDC.ContactsType.Deserialize(string input, out ContactsType obj)
References SDC.ContactsType.Deserialize, SDC.null.
static new ContactsType SDC.ContactsType.Deserialize(string input)
References SDC.null, SDC.ContactsType.Serializer.
static ContactsType SDC.ContactsType.Deserialize(Stream s)
References SDC.ContactsType.Serializer.
static bool SDC.ContactsType.LoadFromFile(string fileName, out ContactsType obj, out Exception exception)
Deserializes xml markup from file into an ContactsType object
fileName string xml file to load and deserialize obj Output ContactsType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ContactsType.LoadFromFile, SDC.null.
static bool SDC.ContactsType.LoadFromFile(string fileName, out ContactsType obj)
References SDC.ContactsType.LoadFromFile, SDC.null.
static new ContactsType SDC.ContactsType.LoadFromFile(string fileName)
References SDC.ContactsType.Deserialize, SDC.null.