SDC::hexBinary_DEtype
bool SDC.hexBinary_DEtype::_shouldSerializemaxLength
Referenced by SDC.hexBinary_DEtype.ShouldSerializemaxLength.
bool SDC.hexBinary_DEtype::_shouldSerializeminLength
Referenced by SDC.hexBinary_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.hexBinary_DEtype::_minLength
Referenced by SDC.hexBinary_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.hexBinary_DEtype::_maxLength
Referenced by SDC.hexBinary_DEtype.ShouldSerializemaxLength.
string SDC.hexBinary_DEtype::_mask
ObjectChangeTracker SDC.hexBinary_DEtype.changeTrackerField
static XmlSerializer SDC.hexBinary_DEtype::serializer
long SDC.hexBinary_DEtype::minLength
bool SDC.hexBinary_DEtype::minLengthSpecified
long SDC.hexBinary_DEtype::maxLength
bool SDC.hexBinary_DEtype::maxLengthSpecified
string SDC.hexBinary_DEtype::mask
Referenced by SDC.hexBinary_DEtype.ShouldSerializemask.
static XmlSerializer SDC.hexBinary_DEtype::Serializer
Referenced by SDC.hexBinary_DEtype.Deserialize.
ObjectChangeTracker SDC.hexBinary_DEtype.ChangeTracker
SDC.hexBinary_DEtype.hexBinary_DEtype()
SDC.hexBinary_DEtype.hexBinary_DEtype(BaseType parentNode)
virtual bool SDC.hexBinary_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
virtual bool SDC.hexBinary_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
virtual bool SDC.hexBinary_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.hexBinary_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current hexBinary_DEtype object into an XML string
string XML value
virtual string SDC.hexBinary_DEtype.Serialize()
Referenced by SDC.hexBinary_DEtype.SaveToFile.
virtual bool SDC.hexBinary_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current hexBinary_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.hexBinary_DEtype.SaveToFile.
virtual bool SDC.hexBinary_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.hexBinary_DEtype.SaveToFile(string fileName)
virtual void SDC.hexBinary_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.hexBinary_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
References SDC.hexBinary_DEtype._minLength, SDC.hexBinary_DEtype._shouldSerializeminLength.
virtual bool SDC.hexBinary_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
References SDC.hexBinary_DEtype._maxLength, SDC.hexBinary_DEtype._shouldSerializemaxLength.
virtual bool SDC.hexBinary_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.hexBinary_DEtype.mask.
virtual string SDC.hexBinary_DEtype.Serialize()
Serializes current hexBinary_DEtype object into an XML string
string XML value
virtual bool SDC.hexBinary_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current hexBinary_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.hexBinary_DEtype.SaveToFile.
virtual void SDC.hexBinary_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.hexBinary_DEtype.Serialize.
virtual hexBinary_DEtype SDC.hexBinary_DEtype.Clone()
Create a clone of this hexBinary_DEtype object
static bool SDC.hexBinary_DEtype.Deserialize(string input, out hexBinary_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an hexBinary_DEtype object
input string workflow markup to deserialize obj Output hexBinary_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.hexBinary_DEtype.Deserialize, SDC.hexBinary_DEtype.LoadFromFile.
static bool SDC.hexBinary_DEtype.Deserialize(string input, out hexBinary_DEtype obj)
References SDC.null.
static new hexBinary_DEtype SDC.hexBinary_DEtype.Deserialize(string input)
References SDC.null.
static hexBinary_DEtype SDC.hexBinary_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.hexBinary_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out hexBinary_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an hexBinary_DEtype object
fileName string xml file to load and deserialize obj Output hexBinary_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.hexBinary_DEtype.LoadFromFile.
static bool SDC.hexBinary_DEtype.LoadFromFile(string fileName, out hexBinary_DEtype obj, out System.Exception exception)
static bool SDC.hexBinary_DEtype.LoadFromFile(string fileName, out hexBinary_DEtype obj)
References SDC.null.
static hexBinary_DEtype SDC.hexBinary_DEtype.LoadFromFile(string fileName)
static new hexBinary_DEtype SDC.hexBinary_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.hexBinary_DEtype.Deserialize(string input, out hexBinary_DEtype obj, out Exception exception)
Deserializes workflow markup into an hexBinary_DEtype object
input string workflow markup to deserialize obj Output hexBinary_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.hexBinary_DEtype.Deserialize, SDC.null.
static bool SDC.hexBinary_DEtype.Deserialize(string input, out hexBinary_DEtype obj)
References SDC.hexBinary_DEtype.Deserialize, SDC.null.
static new hexBinary_DEtype SDC.hexBinary_DEtype.Deserialize(string input)
References SDC.null, SDC.hexBinary_DEtype.Serializer.
static hexBinary_DEtype SDC.hexBinary_DEtype.Deserialize(Stream s)
References SDC.hexBinary_DEtype.Serializer.
static bool SDC.hexBinary_DEtype.LoadFromFile(string fileName, out hexBinary_DEtype obj, out Exception exception)
Deserializes xml markup from file into an hexBinary_DEtype object
fileName string xml file to load and deserialize obj Output hexBinary_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.hexBinary_DEtype.LoadFromFile, SDC.null.
static bool SDC.hexBinary_DEtype.LoadFromFile(string fileName, out hexBinary_DEtype obj)
References SDC.hexBinary_DEtype.LoadFromFile, SDC.null.
static new hexBinary_DEtype SDC.hexBinary_DEtype.LoadFromFile(string fileName)
References SDC.hexBinary_DEtype.Deserialize, SDC.null.