SDC::IfType
PredicateType SDC.IfType.Predicate_Item
Predicate (PredicateType)
ExclusiveItemPairsType SDC.IfType.ExclusiveSelectedItems_Item
ExclusiveSelectedItems (ExclusiveItemPairsType)
GetPropertyValuesType SDC.IfType.PropertyValues_Item
PropertyValues (GetPropertyValuesType)
List<IfBoolCompareType> SDC.IfType.BoolCompare_ItemList
Replaces Items: BoolCompare (If blocks)
static XmlSerializer SDC.IfType::Serializer
Referenced by SDC.IfType.Deserialize.
virtual ExtensionBaseType SDC.IfType.Item
virtual BindingList<IfBoolCompareType> SDC.IfType.Items
ObjectChangeTracker SDC.IfType.ChangeTracker
static XmlSerializer SDC.IfType::serializer
ExtensionBaseType SDC.IfType._item
Referenced by SDC.IfType.ShouldSerializeItem.
BindingList<IfBoolCompareType> SDC.IfType._items
ObjectChangeTracker SDC.IfType.changeTrackerField
SDC.IfType.IfType(BaseType parentNode, bool fillData=true)
SDC.IfType.IfType()
virtual string SDC.IfType.Serialize(System.Text.Encoding encoding)
Serializes current IfType object into an XML string
string XML value
virtual string SDC.IfType.Serialize()
Referenced by SDC.IfType.SaveToFile.
virtual bool SDC.IfType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current IfType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.IfType.SaveToFile.
virtual bool SDC.IfType.SaveToFile(string fileName, out System.Exception exception)
References SDC.IfType.SaveToFile.
virtual void SDC.IfType.SaveToFile(string fileName)
References SDC.IfType.SaveToFile.
virtual void SDC.IfType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.IfType.Serialize.
virtual bool SDC.IfType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.IfType._item, SDC.null.
virtual string SDC.IfType.Serialize()
Serializes current IfType object into an XML string
string XML value
virtual bool SDC.IfType.SaveToFile(string fileName, out Exception exception)
Serializes current IfType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.IfType.SaveToFile.
virtual void SDC.IfType.SaveToFile(string fileName)
References SDC.null, SDC.IfType.Serialize.
virtual IfType SDC.IfType.Clone()
Create a clone of this IfType object
SDC.IfType.IfType()
static bool SDC.IfType.Deserialize(string input, out IfType obj, out System.Exception exception)
Deserializes workflow markup into an IfType object
input string workflow markup to deserialize obj Output IfType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.IfType.Deserialize, SDC.IfType.LoadFromFile.
static bool SDC.IfType.Deserialize(string input, out IfType obj)
References SDC.IfType.Deserialize, SDC.null.
static new IfType SDC.IfType.Deserialize(string input)
References SDC.null.
static IfType SDC.IfType.Deserialize(System.IO.Stream s)
References SDC.IfType.Serializer.
static bool SDC.IfType.LoadFromFile(string fileName, System.Text.Encoding encoding, out IfType obj, out System.Exception exception)
Deserializes xml markup from file into an IfType object
fileName string xml file to load and deserialize obj Output IfType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.IfType.LoadFromFile.
static bool SDC.IfType.LoadFromFile(string fileName, out IfType obj, out System.Exception exception)
References SDC.IfType.LoadFromFile.
static bool SDC.IfType.LoadFromFile(string fileName, out IfType obj)
References SDC.IfType.LoadFromFile, SDC.null.
static IfType SDC.IfType.LoadFromFile(string fileName)
References SDC.IfType.LoadFromFile.
static new IfType SDC.IfType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.IfType.Deserialize, SDC.null.
static bool SDC.IfType.Deserialize(string input, out IfType obj, out Exception exception)
Deserializes workflow markup into an IfType object
input string workflow markup to deserialize obj Output IfType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.IfType.Deserialize, SDC.null.
static bool SDC.IfType.Deserialize(string input, out IfType obj)
References SDC.IfType.Deserialize, SDC.null.
static new IfType SDC.IfType.Deserialize(string input)
References SDC.null, SDC.IfType.Serializer.
static IfType SDC.IfType.Deserialize(Stream s)
References SDC.IfType.Serializer.
static bool SDC.IfType.LoadFromFile(string fileName, out IfType obj, out Exception exception)
Deserializes xml markup from file into an IfType object
fileName string xml file to load and deserialize obj Output IfType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.IfType.LoadFromFile, SDC.null.
static bool SDC.IfType.LoadFromFile(string fileName, out IfType obj)
References SDC.IfType.LoadFromFile, SDC.null.
static new IfType SDC.IfType.LoadFromFile(string fileName)
References SDC.IfType.Deserialize, SDC.null.