SDC::int_DEtype
bool SDC.int_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.int_DEtype.ShouldSerializemaxExclusive.
bool SDC.int_DEtype::_shouldSerializeminExclusive
Referenced by SDC.int_DEtype.ShouldSerializeminExclusive.
bool SDC.int_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.int_DEtype.ShouldSerializemaxInclusive.
bool SDC.int_DEtype::_shouldSerializeminInclusive
Referenced by SDC.int_DEtype.ShouldSerializeminInclusive.
System.Nullable<int> SDC.int_DEtype._minInclusive
Referenced by SDC.int_DEtype.ShouldSerializeminInclusive.
System.Nullable<int> SDC.int_DEtype._maxInclusive
Referenced by SDC.int_DEtype.ShouldSerializemaxInclusive.
System.Nullable<int> SDC.int_DEtype._minExclusive
Referenced by SDC.int_DEtype.ShouldSerializeminExclusive.
System.Nullable<int> SDC.int_DEtype._maxExclusive
Referenced by SDC.int_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.int_DEtype::_totalDigits
string SDC.int_DEtype::_mask
int SDC.int_DEtype._minInclusive
int SDC.int_DEtype._maxInclusive
int SDC.int_DEtype._minExclusive
int SDC.int_DEtype._maxExclusive
ObjectChangeTracker SDC.int_DEtype.changeTrackerField
static XmlSerializer SDC.int_DEtype::serializer
int SDC.int_DEtype::minInclusive
bool SDC.int_DEtype::minInclusiveSpecified
int SDC.int_DEtype::maxInclusive
bool SDC.int_DEtype::maxInclusiveSpecified
int SDC.int_DEtype::minExclusive
bool SDC.int_DEtype::minExclusiveSpecified
int SDC.int_DEtype::maxExclusive
bool SDC.int_DEtype::maxExclusiveSpecified
byte SDC.int_DEtype::totalDigits
bool SDC.int_DEtype::totalDigitsSpecified
string SDC.int_DEtype::mask
Referenced by SDC.int_DEtype.ShouldSerializemask.
static XmlSerializer SDC.int_DEtype::Serializer
Referenced by SDC.int_DEtype.Deserialize.
ObjectChangeTracker SDC.int_DEtype.ChangeTracker
SDC.int_DEtype.int_DEtype()
SDC.int_DEtype.int_DEtype(BaseType parentNode)
virtual bool SDC.int_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.int_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.int_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.int_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.int_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.int_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current int_DEtype object into an XML string
string XML value
virtual string SDC.int_DEtype.Serialize()
Referenced by SDC.int_DEtype.SaveToFile.
virtual bool SDC.int_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current int_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.int_DEtype.SaveToFile.
virtual bool SDC.int_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.int_DEtype.SaveToFile(string fileName)
virtual void SDC.int_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.int_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.int_DEtype._minInclusive, SDC.int_DEtype._shouldSerializeminInclusive.
virtual bool SDC.int_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.int_DEtype._maxInclusive, SDC.int_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.int_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.int_DEtype._minExclusive, SDC.int_DEtype._shouldSerializeminExclusive.
virtual bool SDC.int_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.int_DEtype._maxExclusive, SDC.int_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.int_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.int_DEtype.mask.
virtual string SDC.int_DEtype.Serialize()
Serializes current int_DEtype object into an XML string
string XML value
virtual bool SDC.int_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current int_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.int_DEtype.SaveToFile.
virtual void SDC.int_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.int_DEtype.Serialize.
virtual int_DEtype SDC.int_DEtype.Clone()
Create a clone of this int_DEtype object
static bool SDC.int_DEtype.Deserialize(string input, out int_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an int_DEtype object
input string workflow markup to deserialize obj Output int_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.int_DEtype.Deserialize, SDC.int_DEtype.LoadFromFile.
static bool SDC.int_DEtype.Deserialize(string input, out int_DEtype obj)
References SDC.null.
static new int_DEtype SDC.int_DEtype.Deserialize(string input)
References SDC.null.
static int_DEtype SDC.int_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.int_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out int_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an int_DEtype object
fileName string xml file to load and deserialize obj Output int_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.int_DEtype.LoadFromFile.
static bool SDC.int_DEtype.LoadFromFile(string fileName, out int_DEtype obj, out System.Exception exception)
static bool SDC.int_DEtype.LoadFromFile(string fileName, out int_DEtype obj)
References SDC.null.
static int_DEtype SDC.int_DEtype.LoadFromFile(string fileName)
static new int_DEtype SDC.int_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.int_DEtype.Deserialize(string input, out int_DEtype obj, out Exception exception)
Deserializes workflow markup into an int_DEtype object
input string workflow markup to deserialize obj Output int_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.int_DEtype.Deserialize, SDC.null.
static bool SDC.int_DEtype.Deserialize(string input, out int_DEtype obj)
References SDC.int_DEtype.Deserialize, SDC.null.
static new int_DEtype SDC.int_DEtype.Deserialize(string input)
References SDC.null, SDC.int_DEtype.Serializer.
static int_DEtype SDC.int_DEtype.Deserialize(Stream s)
References SDC.int_DEtype.Serializer.
static bool SDC.int_DEtype.LoadFromFile(string fileName, out int_DEtype obj, out Exception exception)
Deserializes xml markup from file into an int_DEtype object
fileName string xml file to load and deserialize obj Output int_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.int_DEtype.LoadFromFile, SDC.null.
static bool SDC.int_DEtype.LoadFromFile(string fileName, out int_DEtype obj)
References SDC.int_DEtype.LoadFromFile, SDC.null.
static new int_DEtype SDC.int_DEtype.LoadFromFile(string fileName)
References SDC.int_DEtype.Deserialize, SDC.null.