SDC::InjectFormType
IdentifiedExtensionType SDC.InjectFormType._item
Referenced by SDC.InjectFormType.ShouldSerializeItem.
string SDC.InjectFormType::_packageID
string SDC.InjectFormType::_rootItemID
string SDC.InjectFormType::_injectionID
ObjectChangeTracker SDC.InjectFormType.changeTrackerField
static XmlSerializer SDC.InjectFormType::serializer
virtual IdentifiedExtensionType SDC.InjectFormType.Item
string SDC.InjectFormType::packageID
This ID represents the Package that contains the form to be injected.
Referenced by SDC.InjectFormType.ShouldSerializepackageID.
string SDC.InjectFormType::rootItemID
The rootItemID is the ID of the form part that will be injected. If empty, then the entre form shoudl be injected under the FormDesign element node. If not empty, it must point to a valid Section or Question.
The RootItemID may be specified to restrict the injection to a specific root node (with descendents) in the form.
Referenced by SDC.InjectFormType.ShouldSerializerootItemID.
string SDC.InjectFormType::injectionID
Unique ID (GUID) to distinguish multiple instances of the same injected node.
Referenced by SDC.InjectFormType.ShouldSerializeinjectionID.
static XmlSerializer SDC.InjectFormType::Serializer
Referenced by SDC.InjectFormType.Deserialize.
ObjectChangeTracker SDC.InjectFormType.ChangeTracker
SDC.InjectFormType.InjectFormType()
SDC.InjectFormType.InjectFormType(BaseType parentNode, bool fillData=true, string id=null)
SDC.InjectFormType.InjectFormType()
virtual bool SDC.InjectFormType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.InjectFormType._item, SDC.null.
virtual bool SDC.InjectFormType.ShouldSerializepackageID()
Test whether packageID should be serialized
References SDC.InjectFormType.packageID.
virtual bool SDC.InjectFormType.ShouldSerializerootItemID()
Test whether rootItemID should be serialized
References SDC.InjectFormType.rootItemID.
virtual bool SDC.InjectFormType.ShouldSerializeinjectionID()
Test whether injectionID should be serialized
References SDC.InjectFormType.injectionID.
virtual string SDC.InjectFormType.Serialize(System.Text.Encoding encoding)
Serializes current InjectFormType object into an XML string
string XML value
virtual string SDC.InjectFormType.Serialize()
Referenced by SDC.InjectFormType.SaveToFile.
virtual bool SDC.InjectFormType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InjectFormType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InjectFormType.SaveToFile.
virtual bool SDC.InjectFormType.SaveToFile(string fileName, out System.Exception exception)
References SDC.InjectFormType.SaveToFile.
virtual void SDC.InjectFormType.SaveToFile(string fileName)
References SDC.InjectFormType.SaveToFile.
virtual void SDC.InjectFormType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InjectFormType.Serialize.
virtual bool SDC.InjectFormType.ShouldSerializepackageID()
Test whether packageID should be serialized
References SDC.InjectFormType.packageID.
virtual bool SDC.InjectFormType.ShouldSerializerootItemID()
Test whether rootItemID should be serialized
References SDC.InjectFormType.rootItemID.
virtual bool SDC.InjectFormType.ShouldSerializeinjectionID()
Test whether injectionID should be serialized
References SDC.InjectFormType.injectionID.
virtual string SDC.InjectFormType.Serialize()
Serializes current InjectFormType object into an XML string
string XML value
virtual bool SDC.InjectFormType.SaveToFile(string fileName, out Exception exception)
Serializes current InjectFormType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.InjectFormType.SaveToFile.
virtual void SDC.InjectFormType.SaveToFile(string fileName)
References SDC.null, SDC.InjectFormType.Serialize.
virtual InjectFormType SDC.InjectFormType.Clone()
Create a clone of this InjectFormType object
static bool SDC.InjectFormType.Deserialize(string input, out InjectFormType obj, out System.Exception exception)
Deserializes workflow markup into an InjectFormType object
input string workflow markup to deserialize obj Output InjectFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InjectFormType.Deserialize, SDC.InjectFormType.LoadFromFile.
static bool SDC.InjectFormType.Deserialize(string input, out InjectFormType obj)
References SDC.InjectFormType.Deserialize, SDC.null.
static new InjectFormType SDC.InjectFormType.Deserialize(string input)
References SDC.null.
static InjectFormType SDC.InjectFormType.Deserialize(System.IO.Stream s)
References SDC.InjectFormType.Serializer.
static bool SDC.InjectFormType.LoadFromFile(string fileName, System.Text.Encoding encoding, out InjectFormType obj, out System.Exception exception)
Deserializes xml markup from file into an InjectFormType object
fileName string xml file to load and deserialize obj Output InjectFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InjectFormType.LoadFromFile.
static bool SDC.InjectFormType.LoadFromFile(string fileName, out InjectFormType obj, out System.Exception exception)
References SDC.InjectFormType.LoadFromFile.
static bool SDC.InjectFormType.LoadFromFile(string fileName, out InjectFormType obj)
References SDC.InjectFormType.LoadFromFile, SDC.null.
static InjectFormType SDC.InjectFormType.LoadFromFile(string fileName)
References SDC.InjectFormType.LoadFromFile.
static new InjectFormType SDC.InjectFormType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InjectFormType.Deserialize, SDC.null.
static bool SDC.InjectFormType.Deserialize(string input, out InjectFormType obj, out Exception exception)
Deserializes workflow markup into an InjectFormType object
input string workflow markup to deserialize obj Output InjectFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.InjectFormType.Deserialize, SDC.null.
static bool SDC.InjectFormType.Deserialize(string input, out InjectFormType obj)
References SDC.InjectFormType.Deserialize, SDC.null.
static new InjectFormType SDC.InjectFormType.Deserialize(string input)
References SDC.null, SDC.InjectFormType.Serializer.
static InjectFormType SDC.InjectFormType.Deserialize(Stream s)
References SDC.InjectFormType.Serializer.
static bool SDC.InjectFormType.LoadFromFile(string fileName, out InjectFormType obj, out Exception exception)
Deserializes xml markup from file into an InjectFormType object
fileName string xml file to load and deserialize obj Output InjectFormType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.InjectFormType.LoadFromFile, SDC.null.
static bool SDC.InjectFormType.LoadFromFile(string fileName, out InjectFormType obj)
References SDC.InjectFormType.LoadFromFile, SDC.null.
static new InjectFormType SDC.InjectFormType.LoadFromFile(string fileName)
References SDC.InjectFormType.Deserialize, SDC.null.