SDC::FileDatesType
dateTime_Stype SDC.FileDatesType::_fileDate
Referenced by SDC.FileDatesType.ShouldSerializeFileDate.
List<dateTime_Stype> SDC.FileDatesType._previousRevisionDate
dateTime_Stype SDC.FileDatesType::_releaseDate
Referenced by SDC.FileDatesType.ShouldSerializeReleaseDate.
dateTime_Stype SDC.FileDatesType::_effectiveDate
Referenced by SDC.FileDatesType.ShouldSerializeEffectiveDate.
dateTime_Stype SDC.FileDatesType::_firstReleaseDate
Referenced by SDC.FileDatesType.ShouldSerializeFirstReleaseDate.
dateTime_Stype SDC.FileDatesType::_usageStartDate
Referenced by SDC.FileDatesType.ShouldSerializeUsageStartDate.
dateTime_Stype SDC.FileDatesType::_retirementDate
Referenced by SDC.FileDatesType.ShouldSerializeRetirementDate.
List<dateTime_Stype> SDC.FileDatesType._otherDate
BindingList<dateTime_Stype> SDC.FileDatesType._previousRevisionDate
BindingList<dateTime_Stype> SDC.FileDatesType._otherDate
ObjectChangeTracker SDC.FileDatesType.changeTrackerField
static XmlSerializer SDC.FileDatesType::serializer
dateTime_Stype SDC.FileDatesType::FileDate
virtual List<dateTime_Stype> SDC.FileDatesType.PreviousRevisionDate
dateTime_Stype SDC.FileDatesType::ReleaseDate
dateTime_Stype SDC.FileDatesType::EffectiveDate
dateTime_Stype SDC.FileDatesType::FirstReleaseDate
dateTime_Stype SDC.FileDatesType::UsageStartDate
dateTime_Stype SDC.FileDatesType::RetirementDate
virtual List<dateTime_Stype> SDC.FileDatesType.OtherDate
static XmlSerializer SDC.FileDatesType::Serializer
Referenced by SDC.FileDatesType.Deserialize.
virtual BindingList<dateTime_Stype> SDC.FileDatesType.PreviousRevisionDate
virtual BindingList<dateTime_Stype> SDC.FileDatesType.OtherDate
ObjectChangeTracker SDC.FileDatesType.ChangeTracker
SDC.FileDatesType.FileDatesType()
SDC.FileDatesType.FileDatesType(BaseType parentNode)
virtual bool SDC.FileDatesType.ShouldSerializePreviousRevisionDate()
Test whether PreviousRevisionDate should be serialized
References SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeOtherDate()
Test whether OtherDate should be serialized
References SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeFileDate()
Test whether FileDate should be serialized
References SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeReleaseDate()
Test whether ReleaseDate should be serialized
References SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeEffectiveDate()
Test whether EffectiveDate should be serialized
References SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeFirstReleaseDate()
Test whether FirstReleaseDate should be serialized
References SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeUsageStartDate()
Test whether UsageStartDate should be serialized
References SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeRetirementDate()
Test whether RetirementDate should be serialized
References SDC.null.
virtual string SDC.FileDatesType.Serialize(System.Text.Encoding encoding)
Serializes current FileDatesType object into an XML string
string XML value
virtual string SDC.FileDatesType.Serialize()
Referenced by SDC.FileDatesType.SaveToFile.
virtual bool SDC.FileDatesType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current FileDatesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.FileDatesType.SaveToFile.
virtual bool SDC.FileDatesType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.FileDatesType.SaveToFile(string fileName)
virtual void SDC.FileDatesType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeFileDate()
Test whether FileDate should be serialized
References SDC.FileDatesType._fileDate, SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeReleaseDate()
Test whether ReleaseDate should be serialized
References SDC.FileDatesType._releaseDate, SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeEffectiveDate()
Test whether EffectiveDate should be serialized
References SDC.FileDatesType._effectiveDate, SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeFirstReleaseDate()
Test whether FirstReleaseDate should be serialized
References SDC.FileDatesType._firstReleaseDate, SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeUsageStartDate()
Test whether UsageStartDate should be serialized
References SDC.FileDatesType._usageStartDate, SDC.null.
virtual bool SDC.FileDatesType.ShouldSerializeRetirementDate()
Test whether RetirementDate should be serialized
References SDC.FileDatesType._retirementDate, SDC.null.
virtual string SDC.FileDatesType.Serialize()
Serializes current FileDatesType object into an XML string
string XML value
virtual bool SDC.FileDatesType.SaveToFile(string fileName, out Exception exception)
Serializes current FileDatesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.FileDatesType.SaveToFile.
virtual void SDC.FileDatesType.SaveToFile(string fileName)
References SDC.null, SDC.FileDatesType.Serialize.
virtual FileDatesType SDC.FileDatesType.Clone()
Create a clone of this FileDatesType object
static bool SDC.FileDatesType.Deserialize(string input, out FileDatesType obj, out System.Exception exception)
Deserializes workflow markup into an FileDatesType object
input string workflow markup to deserialize obj Output FileDatesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.FileDatesType.Deserialize, SDC.FileDatesType.LoadFromFile.
static bool SDC.FileDatesType.Deserialize(string input, out FileDatesType obj)
References SDC.null.
static new FileDatesType SDC.FileDatesType.Deserialize(string input)
References SDC.null.
static FileDatesType SDC.FileDatesType.Deserialize(System.IO.Stream s)
static bool SDC.FileDatesType.LoadFromFile(string fileName, System.Text.Encoding encoding, out FileDatesType obj, out System.Exception exception)
Deserializes xml markup from file into an FileDatesType object
fileName string xml file to load and deserialize obj Output FileDatesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.FileDatesType.LoadFromFile.
static bool SDC.FileDatesType.LoadFromFile(string fileName, out FileDatesType obj, out System.Exception exception)
static bool SDC.FileDatesType.LoadFromFile(string fileName, out FileDatesType obj)
References SDC.null.
static FileDatesType SDC.FileDatesType.LoadFromFile(string fileName)
static new FileDatesType SDC.FileDatesType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.FileDatesType.Deserialize(string input, out FileDatesType obj, out Exception exception)
Deserializes workflow markup into an FileDatesType object
input string workflow markup to deserialize obj Output FileDatesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.FileDatesType.Deserialize, SDC.null.
static bool SDC.FileDatesType.Deserialize(string input, out FileDatesType obj)
References SDC.FileDatesType.Deserialize, SDC.null.
static new FileDatesType SDC.FileDatesType.Deserialize(string input)
References SDC.null, SDC.FileDatesType.Serializer.
static FileDatesType SDC.FileDatesType.Deserialize(Stream s)
References SDC.FileDatesType.Serializer.
static bool SDC.FileDatesType.LoadFromFile(string fileName, out FileDatesType obj, out Exception exception)
Deserializes xml markup from file into an FileDatesType object
fileName string xml file to load and deserialize obj Output FileDatesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.FileDatesType.LoadFromFile, SDC.null.
static bool SDC.FileDatesType.LoadFromFile(string fileName, out FileDatesType obj)
References SDC.FileDatesType.LoadFromFile, SDC.null.
static new FileDatesType SDC.FileDatesType.LoadFromFile(string fileName)
References SDC.FileDatesType.Deserialize, SDC.null.