SDC::AnyFunctionsNumType
List<object> SDC.AnyFunctionsNumType._items
XmlSerializer SDC.AnyFunctionsNumType.serializer
virtual List<object> SDC.AnyFunctionsNumType.Items
Referenced by SDC.AnyFunctionsNumType.ShouldSerializeItems.
XmlSerializer SDC.AnyFunctionsNumType.Serializer
Referenced by SDC.AnyFunctionsNumType.Deserialize.
virtual bool SDC.AnyFunctionsNumType.ShouldSerializeItems()
Test whether Items should be serialized
References SDC.AnyFunctionsNumType.Items, SDC.null.
virtual string SDC.AnyFunctionsNumType.Serialize(System.Text.Encoding encoding)
Serializes current AnyFunctionsNumType object into an XML string
string XML value
virtual string SDC.AnyFunctionsNumType.Serialize()
Referenced by SDC.AnyFunctionsNumType.SaveToFile.
virtual bool SDC.AnyFunctionsNumType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current AnyFunctionsNumType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.AnyFunctionsNumType.SaveToFile.
virtual bool SDC.AnyFunctionsNumType.SaveToFile(string fileName, out System.Exception exception)
References SDC.AnyFunctionsNumType.SaveToFile.
virtual void SDC.AnyFunctionsNumType.SaveToFile(string fileName)
References SDC.AnyFunctionsNumType.SaveToFile.
virtual void SDC.AnyFunctionsNumType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.AnyFunctionsNumType.Serialize.
static bool SDC.AnyFunctionsNumType.Deserialize(string input, out AnyFunctionsNumType obj, out System.Exception exception)
Deserializes workflow markup into an AnyFunctionsNumType object
input string workflow markup to deserialize obj Output AnyFunctionsNumType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AnyFunctionsNumType.Deserialize, SDC.AnyFunctionsNumType.LoadFromFile.
static bool SDC.AnyFunctionsNumType.Deserialize(string input, out AnyFunctionsNumType obj)
References SDC.AnyFunctionsNumType.Deserialize, SDC.null.
static new AnyFunctionsNumType SDC.AnyFunctionsNumType.Deserialize(string input)
References SDC.null.
static AnyFunctionsNumType SDC.AnyFunctionsNumType.Deserialize(System.IO.Stream s)
References SDC.AnyFunctionsNumType.Serializer.
static bool SDC.AnyFunctionsNumType.LoadFromFile(string fileName, System.Text.Encoding encoding, out AnyFunctionsNumType obj, out System.Exception exception)
Deserializes xml markup from file into an AnyFunctionsNumType object
fileName string xml file to load and deserialize obj Output AnyFunctionsNumType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AnyFunctionsNumType.LoadFromFile.
static bool SDC.AnyFunctionsNumType.LoadFromFile(string fileName, out AnyFunctionsNumType obj, out System.Exception exception)
References SDC.AnyFunctionsNumType.LoadFromFile.
static bool SDC.AnyFunctionsNumType.LoadFromFile(string fileName, out AnyFunctionsNumType obj)
References SDC.AnyFunctionsNumType.LoadFromFile, SDC.null.
static AnyFunctionsNumType SDC.AnyFunctionsNumType.LoadFromFile(string fileName)
References SDC.AnyFunctionsNumType.LoadFromFile.
static new AnyFunctionsNumType SDC.AnyFunctionsNumType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.AnyFunctionsNumType.Deserialize, SDC.null.