SDC::ReturnStrListType
StrListType SDC.ReturnStrListType._item1
Referenced by SDC.ReturnStrListType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnStrListType.serializer
virtual StrListType SDC.ReturnStrListType.Item1
XmlSerializer SDC.ReturnStrListType.Serializer
Referenced by SDC.ReturnStrListType.Deserialize.
virtual bool SDC.ReturnStrListType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnStrListType._item1, SDC.null.
virtual string SDC.ReturnStrListType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnStrListType object into an XML string
string XML value
virtual string SDC.ReturnStrListType.Serialize()
Referenced by SDC.ReturnStrListType.SaveToFile.
virtual bool SDC.ReturnStrListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnStrListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnStrListType.SaveToFile.
virtual bool SDC.ReturnStrListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnStrListType.SaveToFile.
virtual void SDC.ReturnStrListType.SaveToFile(string fileName)
References SDC.ReturnStrListType.SaveToFile.
virtual void SDC.ReturnStrListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnStrListType.Serialize.
static bool SDC.ReturnStrListType.Deserialize(string input, out ReturnStrListType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnStrListType object
input string workflow markup to deserialize obj Output ReturnStrListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnStrListType.Deserialize, SDC.ReturnStrListType.LoadFromFile.
static bool SDC.ReturnStrListType.Deserialize(string input, out ReturnStrListType obj)
References SDC.ReturnStrListType.Deserialize, SDC.null.
static new ReturnStrListType SDC.ReturnStrListType.Deserialize(string input)
References SDC.null.
static ReturnStrListType SDC.ReturnStrListType.Deserialize(System.IO.Stream s)
References SDC.ReturnStrListType.Serializer.
static bool SDC.ReturnStrListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnStrListType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnStrListType object
fileName string xml file to load and deserialize obj Output ReturnStrListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnStrListType.LoadFromFile.
static bool SDC.ReturnStrListType.LoadFromFile(string fileName, out ReturnStrListType obj, out System.Exception exception)
References SDC.ReturnStrListType.LoadFromFile.
static bool SDC.ReturnStrListType.LoadFromFile(string fileName, out ReturnStrListType obj)
References SDC.ReturnStrListType.LoadFromFile, SDC.null.
static ReturnStrListType SDC.ReturnStrListType.LoadFromFile(string fileName)
References SDC.ReturnStrListType.LoadFromFile.
static new ReturnStrListType SDC.ReturnStrListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnStrListType.Deserialize, SDC.null.