SDC::ReturnIntegerListType
IntegerListType SDC.ReturnIntegerListType._item1
Referenced by SDC.ReturnIntegerListType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnIntegerListType.serializer
virtual IntegerListType SDC.ReturnIntegerListType.Item1
XmlSerializer SDC.ReturnIntegerListType.Serializer
Referenced by SDC.ReturnIntegerListType.Deserialize.
virtual bool SDC.ReturnIntegerListType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnIntegerListType._item1, SDC.null.
virtual string SDC.ReturnIntegerListType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnIntegerListType object into an XML string
string XML value
virtual string SDC.ReturnIntegerListType.Serialize()
Referenced by SDC.ReturnIntegerListType.SaveToFile.
virtual bool SDC.ReturnIntegerListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnIntegerListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnIntegerListType.SaveToFile.
virtual bool SDC.ReturnIntegerListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnIntegerListType.SaveToFile.
virtual void SDC.ReturnIntegerListType.SaveToFile(string fileName)
References SDC.ReturnIntegerListType.SaveToFile.
virtual void SDC.ReturnIntegerListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnIntegerListType.Serialize.
static bool SDC.ReturnIntegerListType.Deserialize(string input, out ReturnIntegerListType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnIntegerListType object
input string workflow markup to deserialize obj Output ReturnIntegerListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnIntegerListType.Deserialize, SDC.ReturnIntegerListType.LoadFromFile.
static bool SDC.ReturnIntegerListType.Deserialize(string input, out ReturnIntegerListType obj)
References SDC.ReturnIntegerListType.Deserialize, SDC.null.
static new ReturnIntegerListType SDC.ReturnIntegerListType.Deserialize(string input)
References SDC.null.
static ReturnIntegerListType SDC.ReturnIntegerListType.Deserialize(System.IO.Stream s)
References SDC.ReturnIntegerListType.Serializer.
static bool SDC.ReturnIntegerListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnIntegerListType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnIntegerListType object
fileName string xml file to load and deserialize obj Output ReturnIntegerListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnIntegerListType.LoadFromFile.
static bool SDC.ReturnIntegerListType.LoadFromFile(string fileName, out ReturnIntegerListType obj, out System.Exception exception)
References SDC.ReturnIntegerListType.LoadFromFile.
static bool SDC.ReturnIntegerListType.LoadFromFile(string fileName, out ReturnIntegerListType obj)
References SDC.ReturnIntegerListType.LoadFromFile, SDC.null.
static ReturnIntegerListType SDC.ReturnIntegerListType.LoadFromFile(string fileName)
References SDC.ReturnIntegerListType.LoadFromFile.
static new ReturnIntegerListType SDC.ReturnIntegerListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnIntegerListType.Deserialize, SDC.null.