SDC::BaseType
BaseType SDC.BaseType._ParentObj
IdentifiedExtensionType SDC.BaseType._parentIETypeObject
bool SDC.BaseType::_shouldSerializeorder
Referenced by SDC.BaseType.ShouldSerializeorder.
string SDC.BaseType::_name
string SDC.BaseType::_type
string SDC.BaseType::_styleClass
System Nullable< decimal > SDC.BaseType::_order
Referenced by SDC.BaseType.ShouldSerializeorder.
ObjectChangeTracker SDC.BaseType.changeTrackerField
int SDC.BaseType._ObjectCounter
Referenced by SDC.BaseType.BaseType.
static XmlSerializer SDC.BaseType::serializer
static ITreeBuilder SDC.BaseType::sdcTreeBuilder
Referenced by SDC.BaseType.FillBaseTypeItem, SDC.FormDesignType.FormDesignType.
Dictionary<int, BaseType> SDC.BaseType.Nodes
Dictionary. Given an Node ID (int), returns the Node's object reference.
Dictionary<int, BaseType> SDC.BaseType.ParentNodes
Dictionary. Given a NodeID, return the parent Node's object reference
Dictionary<string, IdentifiedExtensionType> SDC.BaseType.IdentifiedTypes
Dictionary<string, SectionItemType> SDC.BaseType.Sections
Dictionary<string, QuestionItemType> SDC.BaseType.Questions
Dictionary<string, ListItemType> SDC.BaseType.ListItemsAll
Dictionary<string, ListItemResponseFieldType> SDC.BaseType.ListItemResponses
Dictionary<string, InjectFormType> SDC.BaseType.InjectedItems
Dictionary<string, DisplayedType> SDC.BaseType.DisplayedItems
Dictionary<string, ButtonItemType> SDC.BaseType.Buttons
Dictionary<string, BaseType> SDC.BaseType.NamedNodes
Dictionary<String, IChildItems> SDC.BaseType.sdcParentNodes
Dictionary that hold IChildItems nodes (Sections, Questions, ListItems) and their IDs
Referenced by SDC.BaseType.GetParentObject.
readonly int SDC.BaseType.ObjectID
Referenced by SDC.BaseType.BaseType, SDC.BaseType.RegisterParents< T >.
readonly Guid SDC.BaseType.ObjectGUID
Referenced by SDC.IdentifiedExtensionType.AddToIdentExtNodes, SDC.BaseType.BaseType.
ItemTypeEnum SDC.BaseType.NodeType
Referenced by SDC.SDCTreeBuilderEcc.FillBaseTypeItemData.
string SDC.BaseType.ParentIETypeID
Returns the ID property of the closest ancestor of type DisplayedType. For eCC, this is the Parent node's ID, which is derived from the parent node's CTI_Ckey, a.k.a. ParentItemCkey.
int SDC.BaseType.ParentObjID
Returns the ID of the parent object (representing the parent XML element) This is the ObjectID, which is a sequentially assigned integer value.
IdentifiedExtensionType SDC.BaseType.ParentIETypeObject
BaseType SDC.BaseType.ParentNode
Retrieve the BaseType object that is the immediate parent of the current object in the object tree
Referenced by SDC.SDCTreeBuilderEcc.FillListItemResponseField.
string SDC.BaseType.ParentID
string SDC.BaseType::name
Developer assigned identifier, similar to a unique control/object name, used to provide the ability for programmatic manipulation of an element.
Referenced by SDC.BaseType.ShouldSerializename.
string SDC.BaseType::type
The attribute can contain custom metadata "tokens" for the element, chosen from a standardized list of terms. Tokens are short alphanumeric text strings, defined by the W3C Schema NMTOKEN specification, that are defined in an Implementation Guide. The type xsd:NMTOKEN represents a single string token. NMTOKEN values may consist of letters, digits, periods ( . ), hyphens ( - ), underscores ( _ ), and colons ( : ). They may start with any of these characters. (www.datypic.com/sc/xsd/t-xsd_NMTOKEN.html) tokens may be specific for one or more kinds of SDC elements. Multiple tokens in the type attribute should be separated by whitespace. Type tokens may be used to specify special handling by an application, and are usually used to define form display constraints, but may include other custom metadata as well. Style metadata should generally be handled with rather than . token examples include: tooltip, statusLineText, alignTopLeft, align:bottom, _pageBreak-after, etc. metadata should generally not affect the information content of a form.
Referenced by SDC.BaseType.ShouldSerializetype.
string SDC.BaseType::styleClass
Developer assigned class name for display styling, generally for use with an external style sheet.
Referenced by SDC.BaseType.ShouldSerializestyleClass.
decimal SDC.BaseType::order
allows the form template developer to define a sequential order for elements in a template. This serves the purpose of providing a definitive/original order to sections, questions, answer choices, etc., when required for display purposes. This is important when the original XML ordering may become disrupted due to the use of an implementation technology that does not natively support ordering (e.g., object collections), and it can also provide a check on the proper importing of the XML tree during implementation.
bool SDC.BaseType::orderSpecified
static XmlSerializer SDC.BaseType::Serializer
Referenced by SDC.BaseType.Deserialize.
ObjectChangeTracker SDC.BaseType.ChangeTracker
System.ComponentModel.PropertyChangedEventHandler SDC.BaseType.PropertyChanged
Referenced by SDC.BaseType.OnPropertyChanged.
SDC.BaseType.BaseType(BaseType parentNode, bool fillData=true)
References SDC.BaseType._ObjectCounter, SDC.BaseType.FillBaseTypeItem, SDC.BaseType.ObjectGUID, SDC.BaseType.ObjectID.
SDC.BaseType.BaseType()
virtual void SDC.BaseType.AddFill(SDCtypes sdcType=SDCtypes.BaseType, Boolean fillData=true)
Referenced by SDC.BaseType.AddFill.
virtual void SDC.BaseType.AddFill(string typeName=nameof(BaseType), Boolean fillData=true)
References SDC.BaseType.AddFill, SDC.var.
BaseType SDC.BaseType.FillBaseTypeItem()
References SDC.null, SDC.BaseType.sdcTreeBuilder.
Referenced by SDC.BaseType.BaseType.
SDC.BaseType.BaseType()
BaseType SDC.BaseType.FillBaseType()
IChildItems SDC.BaseType.GetParentObject()
References SDC.BaseType.sdcParentNodes, SDC.var.
virtual bool SDC.BaseType.ShouldSerializeorder()
Test whether order should be serialized
References SDC.BaseType._order, SDC.BaseType._shouldSerializeorder, SDC.decimal.
virtual bool SDC.BaseType.ShouldSerializename()
Test whether name should be serialized
References SDC.BaseType.name.
virtual bool SDC.BaseType.ShouldSerializetype()
Test whether type should be serialized
References SDC.BaseType.type.
virtual bool SDC.BaseType.ShouldSerializestyleClass()
Test whether styleClass should be serialized
References SDC.BaseType.styleClass.
virtual string SDC.BaseType.Serialize(System.Text.Encoding encoding)
Serializes current BaseType object into an XML string
string XML value
virtual string SDC.BaseType.Serialize()
Referenced by SDC.BaseType.SaveToFile.
virtual bool SDC.BaseType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current BaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.BaseType.SaveToFile.
virtual bool SDC.BaseType.SaveToFile(string fileName, out System.Exception exception)
References SDC.BaseType.SaveToFile.
virtual void SDC.BaseType.SaveToFile(string fileName)
References SDC.BaseType.SaveToFile.
virtual void SDC.BaseType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.BaseType.Serialize.
virtual bool SDC.BaseType.ShouldSerializeorder()
Test whether order should be serialized
References SDC.BaseType._order, SDC.BaseType._shouldSerializeorder, SDC.decimal.
virtual bool SDC.BaseType.ShouldSerializename()
Test whether name should be serialized
References SDC.BaseType.name.
virtual bool SDC.BaseType.ShouldSerializetype()
Test whether type should be serialized
References SDC.BaseType.type.
virtual bool SDC.BaseType.ShouldSerializestyleClass()
Test whether styleClass should be serialized
References SDC.BaseType.styleClass.
virtual void SDC.BaseType.OnPropertyChanged(string propertyName, object value)
References SDC.null, SDC.BaseType.PropertyChanged.
virtual string SDC.BaseType.Serialize()
Serializes current BaseType object into an XML string
string XML value
virtual bool SDC.BaseType.SaveToFile(string fileName, out Exception exception)
Serializes current BaseType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.BaseType.SaveToFile.
virtual void SDC.BaseType.SaveToFile(string fileName)
References SDC.null, SDC.BaseType.Serialize.
virtual BaseType SDC.BaseType.Clone()
Create a clone of this BaseType object
void SDC.BaseType.RegisterParents< T >(T parentNode)
References SDC.IdentifiedExtensionType, SDC.null, SDC.BaseType.ObjectID.
static IChildItems SDC.BaseType.GetParentObject(BaseType node)
Returns the parent node of the input node.
node
References SDC.BaseType.sdcParentNodes, SDC.var.
static bool SDC.BaseType.Deserialize(string input, out BaseType obj, out System.Exception exception)
Deserializes workflow markup into an BaseType object
input string workflow markup to deserialize obj Output BaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.BaseType.Deserialize, SDC.BaseType.LoadFromFile.
static bool SDC.BaseType.Deserialize(string input, out BaseType obj)
References SDC.BaseType.Deserialize, SDC.null.
static BaseType SDC.BaseType.Deserialize(string input)
References SDC.null.
static BaseType SDC.BaseType.Deserialize(System.IO.Stream s)
References SDC.BaseType.Serializer.
static bool SDC.BaseType.LoadFromFile(string fileName, System.Text.Encoding encoding, out BaseType obj, out System.Exception exception)
Deserializes xml markup from file into an BaseType object
fileName string xml file to load and deserialize obj Output BaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.BaseType.LoadFromFile.
static bool SDC.BaseType.LoadFromFile(string fileName, out BaseType obj, out System.Exception exception)
References SDC.BaseType.LoadFromFile.
static bool SDC.BaseType.LoadFromFile(string fileName, out BaseType obj)
References SDC.BaseType.LoadFromFile, SDC.null.
static BaseType SDC.BaseType.LoadFromFile(string fileName)
References SDC.BaseType.LoadFromFile.
static BaseType SDC.BaseType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.BaseType.Deserialize, SDC.null.
static bool SDC.BaseType.Deserialize(string input, out BaseType obj, out Exception exception)
Deserializes workflow markup into an BaseType object
input string workflow markup to deserialize obj Output BaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.BaseType.Deserialize, SDC.null.
static bool SDC.BaseType.Deserialize(string input, out BaseType obj)
References SDC.BaseType.Deserialize, SDC.null.
static new BaseType SDC.BaseType.Deserialize(string input)
References SDC.null, SDC.BaseType.Serializer.
static BaseType SDC.BaseType.Deserialize(Stream s)
References SDC.BaseType.Serializer.
static bool SDC.BaseType.LoadFromFile(string fileName, out BaseType obj, out Exception exception)
Deserializes xml markup from file into an BaseType object
fileName string xml file to load and deserialize obj Output BaseType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.BaseType.LoadFromFile, SDC.null.
static bool SDC.BaseType.LoadFromFile(string fileName, out BaseType obj)
References SDC.BaseType.LoadFromFile, SDC.null.
static new BaseType SDC.BaseType.LoadFromFile(string fileName)
References SDC.BaseType.Deserialize, SDC.null.