SDC::dt
bool SDC.dt._shouldSerializeallowAPPROX
Referenced by SDC.dt.ShouldSerializeallowAPPROX.
bool SDC.dt._shouldSerializeallowLTE
Referenced by SDC.dt.ShouldSerializeallowLTE.
bool SDC.dt._shouldSerializeallowLT
Referenced by SDC.dt.ShouldSerializeallowLT.
bool SDC.dt._shouldSerializeallowGTE
Referenced by SDC.dt.ShouldSerializeallowGTE.
bool SDC.dt._shouldSerializeallowGT
Referenced by SDC.dt.ShouldSerializeallowGT.
dtQuantEnum SDC.dt::_quantEnum
Referenced by SDC.dt.dt.
bool SDC.dt._allowGT
Referenced by SDC.dt.ShouldSerializeallowGT.
bool SDC.dt._allowGTE
Referenced by SDC.dt.ShouldSerializeallowGTE.
bool SDC.dt._allowLT
Referenced by SDC.dt.ShouldSerializeallowLT.
bool SDC.dt._allowLTE
Referenced by SDC.dt.ShouldSerializeallowLTE.
bool SDC.dt._allowAPPROX
Referenced by SDC.dt.ShouldSerializeallowAPPROX.
ObjectChangeTracker SDC.dt.changeTrackerField
static XmlSerializer SDC.dt::serializer
dtQuantEnum SDC.dt::quantEnum
virtual bool SDC.dt.allowGT
virtual bool SDC.dt.allowGTE
virtual bool SDC.dt.allowLT
virtual bool SDC.dt.allowLTE
virtual bool SDC.dt.allowAPPROX
static XmlSerializer SDC.dt::Serializer
Referenced by SDC.dt.Deserialize.
ObjectChangeTracker SDC.dt.ChangeTracker
System.ComponentModel.PropertyChangedEventHandler SDC.dt.PropertyChanged
Referenced by SDC.dt.OnPropertyChanged.
SDC.dt.dt()
dt class constructor
virtual bool SDC.dt.ShouldSerializeallowGT()
Test whether allowGT should be serialized
References SDC.dt._allowGT, SDC.dt._shouldSerializeallowGT.
virtual bool SDC.dt.ShouldSerializeallowGTE()
Test whether allowGTE should be serialized
References SDC.dt._allowGTE, SDC.dt._shouldSerializeallowGTE.
virtual bool SDC.dt.ShouldSerializeallowLT()
Test whether allowLT should be serialized
References SDC.dt._allowLT, SDC.dt._shouldSerializeallowLT.
virtual bool SDC.dt.ShouldSerializeallowLTE()
Test whether allowLTE should be serialized
References SDC.dt._allowLTE, SDC.dt._shouldSerializeallowLTE.
virtual bool SDC.dt.ShouldSerializeallowAPPROX()
Test whether allowAPPROX should be serialized
References SDC.dt._allowAPPROX, SDC.dt._shouldSerializeallowAPPROX.
virtual string SDC.dt.Serialize(System.Text.Encoding encoding)
Serializes current dt object into an XML string
string XML value
virtual string SDC.dt.Serialize()
Referenced by SDC.dt.SaveToFile.
virtual bool SDC.dt.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current dt object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.dt.SaveToFile.
virtual bool SDC.dt.SaveToFile(string fileName, out System.Exception exception)
References SDC.dt.SaveToFile.
virtual void SDC.dt.SaveToFile(string fileName)
References SDC.dt.SaveToFile.
virtual void SDC.dt.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.dt.Serialize.
SDC.dt.dt()
dt class constructor
References SDC.dt._quantEnum.
virtual void SDC.dt.OnPropertyChanged(string propertyName, object value)
References SDC.null, SDC.dt.PropertyChanged.
virtual string SDC.dt.Serialize()
Serializes current dt object into an XML string
string XML value
virtual bool SDC.dt.SaveToFile(string fileName, out Exception exception)
Serializes current dt object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.dt.SaveToFile.
virtual void SDC.dt.SaveToFile(string fileName)
References SDC.null, SDC.dt.Serialize.
virtual dt SDC.dt.Clone()
Create a clone of this dt object
static bool SDC.dt.Deserialize(string input, out dt obj, out System.Exception exception)
Deserializes workflow markup into an dt object
input string workflow markup to deserialize obj Output dt object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dt.Deserialize, SDC.dt.LoadFromFile.
static bool SDC.dt.Deserialize(string input, out dt obj)
References SDC.dt.Deserialize, SDC.null.
static dt SDC.dt.Deserialize(string input)
References SDC.null.
static dt SDC.dt.Deserialize(System.IO.Stream s)
References SDC.dt.Serializer.
static bool SDC.dt.LoadFromFile(string fileName, System.Text.Encoding encoding, out dt obj, out System.Exception exception)
Deserializes xml markup from file into an dt object
fileName string xml file to load and deserialize obj Output dt object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dt.LoadFromFile.
static bool SDC.dt.LoadFromFile(string fileName, out dt obj, out System.Exception exception)
References SDC.dt.LoadFromFile.
static bool SDC.dt.LoadFromFile(string fileName, out dt obj)
References SDC.dt.LoadFromFile, SDC.null.
static dt SDC.dt.LoadFromFile(string fileName)
References SDC.dt.LoadFromFile.
static dt SDC.dt.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.dt.Deserialize, SDC.null.
static bool SDC.dt.Deserialize(string input, out dt obj, out Exception exception)
Deserializes workflow markup into an dt object
input string workflow markup to deserialize obj Output dt object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dt.Deserialize, SDC.null.
static bool SDC.dt.Deserialize(string input, out dt obj)
References SDC.dt.Deserialize, SDC.null.
static new dt SDC.dt.Deserialize(string input)
References SDC.null, SDC.dt.Serializer.
static dt SDC.dt.Deserialize(Stream s)
References SDC.dt.Serializer.
static bool SDC.dt.LoadFromFile(string fileName, out dt obj, out Exception exception)
Deserializes xml markup from file into an dt object
fileName string xml file to load and deserialize obj Output dt object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dt.LoadFromFile, SDC.null.
static bool SDC.dt.LoadFromFile(string fileName, out dt obj)
References SDC.dt.LoadFromFile, SDC.null.
static new dt SDC.dt.LoadFromFile(string fileName)
References SDC.dt.Deserialize, SDC.null.