SDC::unsignedShort_Stype
bool SDC.unsignedShort_Stype::_shouldSerializeval
Referenced by SDC.unsignedShort_Stype.ShouldSerializeval.
System Nullable< ushort > SDC.unsignedShort_Stype::_val
Referenced by SDC.unsignedShort_Stype.ShouldSerializeval.
dtQuantEnum SDC.unsignedShort_Stype::_quantEnum
Referenced by SDC.unsignedShort_Stype.unsignedShort_Stype.
ObjectChangeTracker SDC.unsignedShort_Stype.changeTrackerField
static XmlSerializer SDC.unsignedShort_Stype::serializer
ushort SDC.unsignedShort_Stype::val
bool SDC.unsignedShort_Stype::valSpecified
dtQuantEnum SDC.unsignedShort_Stype::quantEnum
static XmlSerializer SDC.unsignedShort_Stype::Serializer
Referenced by SDC.unsignedShort_Stype.Deserialize.
ObjectChangeTracker SDC.unsignedShort_Stype.ChangeTracker
SDC.unsignedShort_Stype.unsignedShort_Stype()
SDC.unsignedShort_Stype.unsignedShort_Stype(BaseType parentNode)
virtual bool SDC.unsignedShort_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.unsignedShort_Stype._shouldSerializeval, SDC.unsignedShort_Stype._val.
virtual string SDC.unsignedShort_Stype.Serialize(System.Text.Encoding encoding)
Serializes current unsignedShort_Stype object into an XML string
string XML value
virtual string SDC.unsignedShort_Stype.Serialize()
Referenced by SDC.unsignedShort_Stype.SaveToFile.
virtual bool SDC.unsignedShort_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current unsignedShort_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.unsignedShort_Stype.SaveToFile.
virtual bool SDC.unsignedShort_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.unsignedShort_Stype.SaveToFile.
virtual void SDC.unsignedShort_Stype.SaveToFile(string fileName)
References SDC.unsignedShort_Stype.SaveToFile.
virtual void SDC.unsignedShort_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.unsignedShort_Stype.Serialize.
SDC.unsignedShort_Stype.unsignedShort_Stype()
unsignedShort_Stype class constructor
References SDC.unsignedShort_Stype._quantEnum.
virtual bool SDC.unsignedShort_Stype.ShouldSerializeval()
Test whether val should be serialized
References SDC.unsignedShort_Stype._shouldSerializeval, SDC.unsignedShort_Stype._val.
virtual string SDC.unsignedShort_Stype.Serialize()
Serializes current unsignedShort_Stype object into an XML string
string XML value
virtual bool SDC.unsignedShort_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current unsignedShort_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.unsignedShort_Stype.SaveToFile.
virtual void SDC.unsignedShort_Stype.SaveToFile(string fileName)
References SDC.null, SDC.unsignedShort_Stype.Serialize.
virtual unsignedShort_Stype SDC.unsignedShort_Stype.Clone()
Create a clone of this unsignedShort_Stype object
static bool SDC.unsignedShort_Stype.Deserialize(string input, out unsignedShort_Stype obj, out System.Exception exception)
Deserializes workflow markup into an unsignedShort_Stype object
input string workflow markup to deserialize obj Output unsignedShort_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedShort_Stype.Deserialize, SDC.unsignedShort_Stype.LoadFromFile.
static bool SDC.unsignedShort_Stype.Deserialize(string input, out unsignedShort_Stype obj)
References SDC.unsignedShort_Stype.Deserialize, SDC.null.
static new unsignedShort_Stype SDC.unsignedShort_Stype.Deserialize(string input)
References SDC.null.
static unsignedShort_Stype SDC.unsignedShort_Stype.Deserialize(System.IO.Stream s)
References SDC.unsignedShort_Stype.Serializer.
static bool SDC.unsignedShort_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out unsignedShort_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an unsignedShort_Stype object
fileName string xml file to load and deserialize obj Output unsignedShort_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedShort_Stype.LoadFromFile.
static bool SDC.unsignedShort_Stype.LoadFromFile(string fileName, out unsignedShort_Stype obj, out System.Exception exception)
References SDC.unsignedShort_Stype.LoadFromFile.
static bool SDC.unsignedShort_Stype.LoadFromFile(string fileName, out unsignedShort_Stype obj)
References SDC.unsignedShort_Stype.LoadFromFile, SDC.null.
static unsignedShort_Stype SDC.unsignedShort_Stype.LoadFromFile(string fileName)
References SDC.unsignedShort_Stype.LoadFromFile.
static new unsignedShort_Stype SDC.unsignedShort_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.unsignedShort_Stype.Deserialize, SDC.null.
static bool SDC.unsignedShort_Stype.Deserialize(string input, out unsignedShort_Stype obj, out Exception exception)
Deserializes workflow markup into an unsignedShort_Stype object
input string workflow markup to deserialize obj Output unsignedShort_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedShort_Stype.Deserialize, SDC.null.
static bool SDC.unsignedShort_Stype.Deserialize(string input, out unsignedShort_Stype obj)
References SDC.unsignedShort_Stype.Deserialize, SDC.null.
static new unsignedShort_Stype SDC.unsignedShort_Stype.Deserialize(string input)
References SDC.null, SDC.unsignedShort_Stype.Serializer.
static unsignedShort_Stype SDC.unsignedShort_Stype.Deserialize(Stream s)
References SDC.unsignedShort_Stype.Serializer.
static bool SDC.unsignedShort_Stype.LoadFromFile(string fileName, out unsignedShort_Stype obj, out Exception exception)
Deserializes xml markup from file into an unsignedShort_Stype object
fileName string xml file to load and deserialize obj Output unsignedShort_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedShort_Stype.LoadFromFile, SDC.null.
static bool SDC.unsignedShort_Stype.LoadFromFile(string fileName, out unsignedShort_Stype obj)
References SDC.unsignedShort_Stype.LoadFromFile, SDC.null.
static new unsignedShort_Stype SDC.unsignedShort_Stype.LoadFromFile(string fileName)
References SDC.unsignedShort_Stype.Deserialize, SDC.null.