SDC::___FunctionGroupers___
bool SDC.___FunctionGroupers___._shouldSerialize___DateTimeFunctions___
Referenced by SDC.___FunctionGroupers___.ShouldSerialize___DateTimeFunctions___.
object SDC.___FunctionGroupers___.___DateTimeFunctions___Field
Referenced by SDC.___FunctionGroupers___.ShouldSerialize___DateTimeFunctions___.
XmlSerializer SDC.___FunctionGroupers___.serializer
virtual object SDC.___FunctionGroupers___.___DateTimeFunctions___
XmlSerializer SDC.___FunctionGroupers___.Serializer
Referenced by SDC.___FunctionGroupers___.Deserialize.
virtual bool SDC.___FunctionGroupers___.ShouldSerialize___DateTimeFunctions___()
Test whether ___DateTimeFunctions___ should be serialized
References SDC.___FunctionGroupers___.___DateTimeFunctions___Field, SDC.___FunctionGroupers___._shouldSerialize___DateTimeFunctions___.
virtual string SDC.___FunctionGroupers___.Serialize(System.Text.Encoding encoding)
Serializes current ___FunctionGroupers___ object into an XML string
string XML value
virtual string SDC.___FunctionGroupers___.Serialize()
Referenced by SDC.___FunctionGroupers___.SaveToFile.
virtual bool SDC.___FunctionGroupers___.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ___FunctionGroupers___ object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.___FunctionGroupers___.SaveToFile.
virtual bool SDC.___FunctionGroupers___.SaveToFile(string fileName, out System.Exception exception)
References SDC.___FunctionGroupers___.SaveToFile.
virtual void SDC.___FunctionGroupers___.SaveToFile(string fileName)
References SDC.___FunctionGroupers___.SaveToFile.
virtual void SDC.___FunctionGroupers___.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.___FunctionGroupers___.Serialize.
static bool SDC.___FunctionGroupers___.Deserialize(string input, out ___FunctionGroupers___ obj, out System.Exception exception)
Deserializes workflow markup into an ___FunctionGroupers___ object
input string workflow markup to deserialize obj Output ___FunctionGroupers___ object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.___FunctionGroupers___.Deserialize, SDC.___FunctionGroupers___.LoadFromFile.
static bool SDC.___FunctionGroupers___.Deserialize(string input, out ___FunctionGroupers___ obj)
References SDC.___FunctionGroupers___.Deserialize, SDC.null.
static ___FunctionGroupers___ SDC.___FunctionGroupers___.Deserialize(string input)
References SDC.null.
static ___FunctionGroupers___ SDC.___FunctionGroupers___.Deserialize(System.IO.Stream s)
References SDC.___FunctionGroupers___.Serializer.
static bool SDC.___FunctionGroupers___.LoadFromFile(string fileName, System.Text.Encoding encoding, out ___FunctionGroupers___ obj, out System.Exception exception)
Deserializes xml markup from file into an ___FunctionGroupers___ object
fileName string xml file to load and deserialize obj Output ___FunctionGroupers___ object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.___FunctionGroupers___.LoadFromFile.
static bool SDC.___FunctionGroupers___.LoadFromFile(string fileName, out ___FunctionGroupers___ obj, out System.Exception exception)
References SDC.___FunctionGroupers___.LoadFromFile.
static bool SDC.___FunctionGroupers___.LoadFromFile(string fileName, out ___FunctionGroupers___ obj)
References SDC.___FunctionGroupers___.LoadFromFile, SDC.null.
static ___FunctionGroupers___ SDC.___FunctionGroupers___.LoadFromFile(string fileName)
References SDC.___FunctionGroupers___.LoadFromFile.
static ___FunctionGroupers___ SDC.___FunctionGroupers___.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.___FunctionGroupers___.Deserialize, SDC.null.