SDC::ProvenanceType
List<FileType> SDC.ProvenanceType._replacedFile
BindingList<FileType> SDC.ProvenanceType._replacedFile
ObjectChangeTracker SDC.ProvenanceType.changeTrackerField
static XmlSerializer SDC.ProvenanceType::serializer
virtual List<FileType> SDC.ProvenanceType.ReplacedFile
static XmlSerializer SDC.ProvenanceType::Serializer
Referenced by SDC.ProvenanceType.Deserialize.
virtual BindingList<FileType> SDC.ProvenanceType.ReplacedFile
ObjectChangeTracker SDC.ProvenanceType.ChangeTracker
SDC.ProvenanceType.ProvenanceType()
SDC.ProvenanceType.ProvenanceType(BaseType parentNode)
virtual bool SDC.ProvenanceType.ShouldSerializeReplacedFile()
Test whether ReplacedFile should be serialized
References SDC.null.
virtual string SDC.ProvenanceType.Serialize(System.Text.Encoding encoding)
Serializes current ProvenanceType object into an XML string
string XML value
virtual string SDC.ProvenanceType.Serialize()
Referenced by SDC.ProvenanceType.SaveToFile.
virtual bool SDC.ProvenanceType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ProvenanceType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ProvenanceType.SaveToFile.
virtual bool SDC.ProvenanceType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ProvenanceType.SaveToFile(string fileName)
virtual void SDC.ProvenanceType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.ProvenanceType.Serialize()
Serializes current ProvenanceType object into an XML string
string XML value
virtual bool SDC.ProvenanceType.SaveToFile(string fileName, out Exception exception)
Serializes current ProvenanceType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ProvenanceType.SaveToFile.
virtual void SDC.ProvenanceType.SaveToFile(string fileName)
References SDC.null, SDC.ProvenanceType.Serialize.
virtual ProvenanceType SDC.ProvenanceType.Clone()
Create a clone of this ProvenanceType object
static bool SDC.ProvenanceType.Deserialize(string input, out ProvenanceType obj, out System.Exception exception)
Deserializes workflow markup into an ProvenanceType object
input string workflow markup to deserialize obj Output ProvenanceType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ProvenanceType.Deserialize, SDC.ProvenanceType.LoadFromFile.
static bool SDC.ProvenanceType.Deserialize(string input, out ProvenanceType obj)
References SDC.null.
static new ProvenanceType SDC.ProvenanceType.Deserialize(string input)
References SDC.null.
static ProvenanceType SDC.ProvenanceType.Deserialize(System.IO.Stream s)
static bool SDC.ProvenanceType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ProvenanceType obj, out System.Exception exception)
Deserializes xml markup from file into an ProvenanceType object
fileName string xml file to load and deserialize obj Output ProvenanceType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ProvenanceType.LoadFromFile.
static bool SDC.ProvenanceType.LoadFromFile(string fileName, out ProvenanceType obj, out System.Exception exception)
static bool SDC.ProvenanceType.LoadFromFile(string fileName, out ProvenanceType obj)
References SDC.null.
static ProvenanceType SDC.ProvenanceType.LoadFromFile(string fileName)
static new ProvenanceType SDC.ProvenanceType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ProvenanceType.Deserialize(string input, out ProvenanceType obj, out Exception exception)
Deserializes workflow markup into an ProvenanceType object
input string workflow markup to deserialize obj Output ProvenanceType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ProvenanceType.Deserialize, SDC.null.
static bool SDC.ProvenanceType.Deserialize(string input, out ProvenanceType obj)
References SDC.ProvenanceType.Deserialize, SDC.null.
static new ProvenanceType SDC.ProvenanceType.Deserialize(string input)
References SDC.null, SDC.ProvenanceType.Serializer.
static ProvenanceType SDC.ProvenanceType.Deserialize(Stream s)
References SDC.ProvenanceType.Serializer.
static bool SDC.ProvenanceType.LoadFromFile(string fileName, out ProvenanceType obj, out Exception exception)
Deserializes xml markup from file into an ProvenanceType object
fileName string xml file to load and deserialize obj Output ProvenanceType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ProvenanceType.LoadFromFile, SDC.null.
static bool SDC.ProvenanceType.LoadFromFile(string fileName, out ProvenanceType obj)
References SDC.ProvenanceType.LoadFromFile, SDC.null.
static new ProvenanceType SDC.ProvenanceType.LoadFromFile(string fileName)
References SDC.ProvenanceType.Deserialize, SDC.null.