SDC::ListItemResponseFieldType
bool SDC.ListItemResponseFieldType::_shouldSerializeresponseRequired
Referenced by SDC.ListItemResponseFieldType.ShouldSerializeresponseRequired.
bool SDC.ListItemResponseFieldType::_responseRequired
Referenced by SDC.ListItemResponseFieldType.ListItemResponseFieldType, SDC.ListItemResponseFieldType.ShouldSerializeresponseRequired.
ObjectChangeTracker SDC.ListItemResponseFieldType.changeTrackerField
static XmlSerializer SDC.ListItemResponseFieldType::serializer
bool SDC.ListItemResponseFieldType::responseRequired
If is set to true, then the appropriate text or Blob must be entered in the data-entry field associated with this list item.
static XmlSerializer SDC.ListItemResponseFieldType::Serializer
Referenced by SDC.ListItemResponseFieldType.Deserialize.
ObjectChangeTracker SDC.ListItemResponseFieldType.ChangeTracker
SDC.ListItemResponseFieldType.ListItemResponseFieldType(BaseType parentNode, bool fillData=true)
ListItemResponseFieldType SDC.ListItemResponseFieldType.FillListItemResponseFieldType()
Replaced in original class: protected ListItemResponseFieldType (){}.
ResponseFieldType SDC.ListItemResponseFieldType.GetResponseField()
void SDC.ListItemResponseFieldType.Fill_ListItemResponseFieldType()
ResponseFieldType SDC.ListItemResponseFieldType.GetResponseField()
virtual bool SDC.ListItemResponseFieldType.ShouldSerializeresponseRequired()
Test whether responseRequired should be serialized
virtual string SDC.ListItemResponseFieldType.Serialize(System.Text.Encoding encoding)
Serializes current ListItemResponseFieldType object into an XML string
string XML value
virtual string SDC.ListItemResponseFieldType.Serialize()
Referenced by SDC.ListItemResponseFieldType.SaveToFile.
virtual bool SDC.ListItemResponseFieldType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ListItemResponseFieldType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ListItemResponseFieldType.SaveToFile.
virtual bool SDC.ListItemResponseFieldType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ListItemResponseFieldType.SaveToFile(string fileName)
virtual void SDC.ListItemResponseFieldType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.ListItemResponseFieldType.ListItemResponseFieldType()
ListItemResponseFieldType class constructor
References SDC.ListItemResponseFieldType._responseRequired.
virtual bool SDC.ListItemResponseFieldType.ShouldSerializeresponseRequired()
Test whether responseRequired should be serialized
References SDC.ListItemResponseFieldType._responseRequired, SDC.ListItemResponseFieldType._shouldSerializeresponseRequired.
virtual string SDC.ListItemResponseFieldType.Serialize()
Serializes current ListItemResponseFieldType object into an XML string
string XML value
virtual bool SDC.ListItemResponseFieldType.SaveToFile(string fileName, out Exception exception)
Serializes current ListItemResponseFieldType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ListItemResponseFieldType.SaveToFile.
virtual void SDC.ListItemResponseFieldType.SaveToFile(string fileName)
References SDC.null, SDC.ListItemResponseFieldType.Serialize.
virtual ListItemResponseFieldType SDC.ListItemResponseFieldType.Clone()
Create a clone of this ListItemResponseFieldType object
SDC.ListItemResponseFieldType.ListItemResponseFieldType()
static bool SDC.ListItemResponseFieldType.Deserialize(string input, out ListItemResponseFieldType obj, out System.Exception exception)
Deserializes workflow markup into an ListItemResponseFieldType object
input string workflow markup to deserialize obj Output ListItemResponseFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListItemResponseFieldType.Deserialize, SDC.ListItemResponseFieldType.LoadFromFile.
static bool SDC.ListItemResponseFieldType.Deserialize(string input, out ListItemResponseFieldType obj)
References SDC.null.
static new ListItemResponseFieldType SDC.ListItemResponseFieldType.Deserialize(string input)
References SDC.null.
static ListItemResponseFieldType SDC.ListItemResponseFieldType.Deserialize(System.IO.Stream s)
static bool SDC.ListItemResponseFieldType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ListItemResponseFieldType obj, out System.Exception exception)
Deserializes xml markup from file into an ListItemResponseFieldType object
fileName string xml file to load and deserialize obj Output ListItemResponseFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListItemResponseFieldType.LoadFromFile.
static bool SDC.ListItemResponseFieldType.LoadFromFile(string fileName, out ListItemResponseFieldType obj, out System.Exception exception)
static bool SDC.ListItemResponseFieldType.LoadFromFile(string fileName, out ListItemResponseFieldType obj)
References SDC.null.
static ListItemResponseFieldType SDC.ListItemResponseFieldType.LoadFromFile(string fileName)
static new ListItemResponseFieldType SDC.ListItemResponseFieldType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ListItemResponseFieldType.Deserialize(string input, out ListItemResponseFieldType obj, out Exception exception)
Deserializes workflow markup into an ListItemResponseFieldType object
input string workflow markup to deserialize obj Output ListItemResponseFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListItemResponseFieldType.Deserialize, SDC.null.
static bool SDC.ListItemResponseFieldType.Deserialize(string input, out ListItemResponseFieldType obj)
References SDC.ListItemResponseFieldType.Deserialize, SDC.null.
static new ListItemResponseFieldType SDC.ListItemResponseFieldType.Deserialize(string input)
References SDC.null, SDC.ListItemResponseFieldType.Serializer.
static ListItemResponseFieldType SDC.ListItemResponseFieldType.Deserialize(Stream s)
References SDC.ListItemResponseFieldType.Serializer.
static bool SDC.ListItemResponseFieldType.LoadFromFile(string fileName, out ListItemResponseFieldType obj, out Exception exception)
Deserializes xml markup from file into an ListItemResponseFieldType object
fileName string xml file to load and deserialize obj Output ListItemResponseFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListItemResponseFieldType.LoadFromFile, SDC.null.
static bool SDC.ListItemResponseFieldType.LoadFromFile(string fileName, out ListItemResponseFieldType obj)
References SDC.ListItemResponseFieldType.LoadFromFile, SDC.null.
static new ListItemResponseFieldType SDC.ListItemResponseFieldType.LoadFromFile(string fileName)
References SDC.ListItemResponseFieldType.Deserialize, SDC.null.