SDC::unsignedByte_Stype
System Nullable< byte > SDC.unsignedByte_Stype::_val
dtQuantEnum SDC.unsignedByte_Stype::_quantEnum
Referenced by SDC.unsignedByte_Stype.unsignedByte_Stype.
ObjectChangeTracker SDC.unsignedByte_Stype.changeTrackerField
static XmlSerializer SDC.unsignedByte_Stype::serializer
byte SDC.unsignedByte_Stype::val
bool SDC.unsignedByte_Stype::valSpecified
dtQuantEnum SDC.unsignedByte_Stype::quantEnum
static XmlSerializer SDC.unsignedByte_Stype::Serializer
Referenced by SDC.unsignedByte_Stype.Deserialize.
ObjectChangeTracker SDC.unsignedByte_Stype.ChangeTracker
SDC.unsignedByte_Stype.unsignedByte_Stype()
SDC.unsignedByte_Stype.unsignedByte_Stype(BaseType parentNode)
virtual string SDC.unsignedByte_Stype.Serialize(System.Text.Encoding encoding)
Serializes current unsignedByte_Stype object into an XML string
string XML value
virtual string SDC.unsignedByte_Stype.Serialize()
Referenced by SDC.unsignedByte_Stype.SaveToFile.
virtual bool SDC.unsignedByte_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current unsignedByte_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.unsignedByte_Stype.SaveToFile.
virtual bool SDC.unsignedByte_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.unsignedByte_Stype.SaveToFile.
virtual void SDC.unsignedByte_Stype.SaveToFile(string fileName)
References SDC.unsignedByte_Stype.SaveToFile.
virtual void SDC.unsignedByte_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.unsignedByte_Stype.Serialize.
SDC.unsignedByte_Stype.unsignedByte_Stype()
unsignedByte_Stype class constructor
References SDC.unsignedByte_Stype._quantEnum.
virtual string SDC.unsignedByte_Stype.Serialize()
Serializes current unsignedByte_Stype object into an XML string
string XML value
virtual bool SDC.unsignedByte_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current unsignedByte_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.unsignedByte_Stype.SaveToFile.
virtual void SDC.unsignedByte_Stype.SaveToFile(string fileName)
References SDC.null, SDC.unsignedByte_Stype.Serialize.
virtual unsignedByte_Stype SDC.unsignedByte_Stype.Clone()
Create a clone of this unsignedByte_Stype object
static bool SDC.unsignedByte_Stype.Deserialize(string input, out unsignedByte_Stype obj, out System.Exception exception)
Deserializes workflow markup into an unsignedByte_Stype object
input string workflow markup to deserialize obj Output unsignedByte_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedByte_Stype.Deserialize, SDC.unsignedByte_Stype.LoadFromFile.
static bool SDC.unsignedByte_Stype.Deserialize(string input, out unsignedByte_Stype obj)
References SDC.unsignedByte_Stype.Deserialize, SDC.null.
static new unsignedByte_Stype SDC.unsignedByte_Stype.Deserialize(string input)
References SDC.null.
static unsignedByte_Stype SDC.unsignedByte_Stype.Deserialize(System.IO.Stream s)
References SDC.unsignedByte_Stype.Serializer.
static bool SDC.unsignedByte_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out unsignedByte_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an unsignedByte_Stype object
fileName string xml file to load and deserialize obj Output unsignedByte_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedByte_Stype.LoadFromFile.
static bool SDC.unsignedByte_Stype.LoadFromFile(string fileName, out unsignedByte_Stype obj, out System.Exception exception)
References SDC.unsignedByte_Stype.LoadFromFile.
static bool SDC.unsignedByte_Stype.LoadFromFile(string fileName, out unsignedByte_Stype obj)
References SDC.unsignedByte_Stype.LoadFromFile, SDC.null.
static unsignedByte_Stype SDC.unsignedByte_Stype.LoadFromFile(string fileName)
References SDC.unsignedByte_Stype.LoadFromFile.
static new unsignedByte_Stype SDC.unsignedByte_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.unsignedByte_Stype.Deserialize, SDC.null.
static bool SDC.unsignedByte_Stype.Deserialize(string input, out unsignedByte_Stype obj, out Exception exception)
Deserializes workflow markup into an unsignedByte_Stype object
input string workflow markup to deserialize obj Output unsignedByte_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedByte_Stype.Deserialize, SDC.null.
static bool SDC.unsignedByte_Stype.Deserialize(string input, out unsignedByte_Stype obj)
References SDC.unsignedByte_Stype.Deserialize, SDC.null.
static new unsignedByte_Stype SDC.unsignedByte_Stype.Deserialize(string input)
References SDC.null, SDC.unsignedByte_Stype.Serializer.
static unsignedByte_Stype SDC.unsignedByte_Stype.Deserialize(Stream s)
References SDC.unsignedByte_Stype.Serializer.
static bool SDC.unsignedByte_Stype.LoadFromFile(string fileName, out unsignedByte_Stype obj, out Exception exception)
Deserializes xml markup from file into an unsignedByte_Stype object
fileName string xml file to load and deserialize obj Output unsignedByte_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedByte_Stype.LoadFromFile, SDC.null.
static bool SDC.unsignedByte_Stype.LoadFromFile(string fileName, out unsignedByte_Stype obj)
References SDC.unsignedByte_Stype.LoadFromFile, SDC.null.
static new unsignedByte_Stype SDC.unsignedByte_Stype.LoadFromFile(string fileName)
References SDC.unsignedByte_Stype.Deserialize, SDC.null.