SDC::unsignedLong_DEtype
bool SDC.unsignedLong_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.unsignedLong_DEtype.ShouldSerializemaxExclusive.
bool SDC.unsignedLong_DEtype::_shouldSerializeminExclusive
Referenced by SDC.unsignedLong_DEtype.ShouldSerializeminExclusive.
bool SDC.unsignedLong_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.unsignedLong_DEtype.ShouldSerializemaxInclusive.
bool SDC.unsignedLong_DEtype::_shouldSerializeminInclusive
Referenced by SDC.unsignedLong_DEtype.ShouldSerializeminInclusive.
System Nullable< ulong > SDC.unsignedLong_DEtype::_minInclusive
Referenced by SDC.unsignedLong_DEtype.ShouldSerializeminInclusive.
System Nullable< ulong > SDC.unsignedLong_DEtype::_maxInclusive
Referenced by SDC.unsignedLong_DEtype.ShouldSerializemaxInclusive.
System Nullable< ulong > SDC.unsignedLong_DEtype::_minExclusive
Referenced by SDC.unsignedLong_DEtype.ShouldSerializeminExclusive.
System Nullable< ulong > SDC.unsignedLong_DEtype::_maxExclusive
Referenced by SDC.unsignedLong_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.unsignedLong_DEtype::_totalDigits
string SDC.unsignedLong_DEtype::_mask
ObjectChangeTracker SDC.unsignedLong_DEtype.changeTrackerField
static XmlSerializer SDC.unsignedLong_DEtype::serializer
ulong SDC.unsignedLong_DEtype::minInclusive
bool SDC.unsignedLong_DEtype::minInclusiveSpecified
ulong SDC.unsignedLong_DEtype::maxInclusive
bool SDC.unsignedLong_DEtype::maxInclusiveSpecified
ulong SDC.unsignedLong_DEtype::minExclusive
bool SDC.unsignedLong_DEtype::minExclusiveSpecified
ulong SDC.unsignedLong_DEtype::maxExclusive
bool SDC.unsignedLong_DEtype::maxExclusiveSpecified
byte SDC.unsignedLong_DEtype::totalDigits
bool SDC.unsignedLong_DEtype::totalDigitsSpecified
string SDC.unsignedLong_DEtype::mask
Referenced by SDC.unsignedLong_DEtype.ShouldSerializemask.
static XmlSerializer SDC.unsignedLong_DEtype::Serializer
Referenced by SDC.unsignedLong_DEtype.Deserialize.
ObjectChangeTracker SDC.unsignedLong_DEtype.ChangeTracker
SDC.unsignedLong_DEtype.unsignedLong_DEtype()
SDC.unsignedLong_DEtype.unsignedLong_DEtype(BaseType parentNode)
virtual bool SDC.unsignedLong_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.unsignedLong_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.unsignedLong_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.unsignedLong_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.unsignedLong_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.unsignedLong_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current unsignedLong_DEtype object into an XML string
string XML value
virtual string SDC.unsignedLong_DEtype.Serialize()
Referenced by SDC.unsignedLong_DEtype.SaveToFile.
virtual bool SDC.unsignedLong_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current unsignedLong_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.unsignedLong_DEtype.SaveToFile.
virtual bool SDC.unsignedLong_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.unsignedLong_DEtype.SaveToFile(string fileName)
virtual void SDC.unsignedLong_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.unsignedLong_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.unsignedLong_DEtype._minInclusive, SDC.unsignedLong_DEtype._shouldSerializeminInclusive.
virtual bool SDC.unsignedLong_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.unsignedLong_DEtype._maxInclusive, SDC.unsignedLong_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.unsignedLong_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.unsignedLong_DEtype._minExclusive, SDC.unsignedLong_DEtype._shouldSerializeminExclusive.
virtual bool SDC.unsignedLong_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.unsignedLong_DEtype._maxExclusive, SDC.unsignedLong_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.unsignedLong_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.unsignedLong_DEtype.mask.
virtual string SDC.unsignedLong_DEtype.Serialize()
Serializes current unsignedLong_DEtype object into an XML string
string XML value
virtual bool SDC.unsignedLong_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current unsignedLong_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.unsignedLong_DEtype.SaveToFile.
virtual void SDC.unsignedLong_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.unsignedLong_DEtype.Serialize.
virtual unsignedLong_DEtype SDC.unsignedLong_DEtype.Clone()
Create a clone of this unsignedLong_DEtype object
static bool SDC.unsignedLong_DEtype.Deserialize(string input, out unsignedLong_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an unsignedLong_DEtype object
input string workflow markup to deserialize obj Output unsignedLong_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedLong_DEtype.Deserialize, SDC.unsignedLong_DEtype.LoadFromFile.
static bool SDC.unsignedLong_DEtype.Deserialize(string input, out unsignedLong_DEtype obj)
References SDC.null.
static new unsignedLong_DEtype SDC.unsignedLong_DEtype.Deserialize(string input)
References SDC.null.
static unsignedLong_DEtype SDC.unsignedLong_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.unsignedLong_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out unsignedLong_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an unsignedLong_DEtype object
fileName string xml file to load and deserialize obj Output unsignedLong_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.unsignedLong_DEtype.LoadFromFile.
static bool SDC.unsignedLong_DEtype.LoadFromFile(string fileName, out unsignedLong_DEtype obj, out System.Exception exception)
static bool SDC.unsignedLong_DEtype.LoadFromFile(string fileName, out unsignedLong_DEtype obj)
References SDC.null.
static unsignedLong_DEtype SDC.unsignedLong_DEtype.LoadFromFile(string fileName)
static new unsignedLong_DEtype SDC.unsignedLong_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.unsignedLong_DEtype.Deserialize(string input, out unsignedLong_DEtype obj, out Exception exception)
Deserializes workflow markup into an unsignedLong_DEtype object
input string workflow markup to deserialize obj Output unsignedLong_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedLong_DEtype.Deserialize, SDC.null.
static bool SDC.unsignedLong_DEtype.Deserialize(string input, out unsignedLong_DEtype obj)
References SDC.unsignedLong_DEtype.Deserialize, SDC.null.
static new unsignedLong_DEtype SDC.unsignedLong_DEtype.Deserialize(string input)
References SDC.null, SDC.unsignedLong_DEtype.Serializer.
static unsignedLong_DEtype SDC.unsignedLong_DEtype.Deserialize(Stream s)
References SDC.unsignedLong_DEtype.Serializer.
static bool SDC.unsignedLong_DEtype.LoadFromFile(string fileName, out unsignedLong_DEtype obj, out Exception exception)
Deserializes xml markup from file into an unsignedLong_DEtype object
fileName string xml file to load and deserialize obj Output unsignedLong_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.unsignedLong_DEtype.LoadFromFile, SDC.null.
static bool SDC.unsignedLong_DEtype.LoadFromFile(string fileName, out unsignedLong_DEtype obj)
References SDC.unsignedLong_DEtype.LoadFromFile, SDC.null.
static new unsignedLong_DEtype SDC.unsignedLong_DEtype.LoadFromFile(string fileName)
References SDC.unsignedLong_DEtype.Deserialize, SDC.null.