SDC::ReturnBoolType
boolean_DEtype SDC.ReturnBoolType._item1
Referenced by SDC.ReturnBoolType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnBoolType.serializer
virtual boolean_DEtype SDC.ReturnBoolType.Item1
XmlSerializer SDC.ReturnBoolType.Serializer
Referenced by SDC.ReturnBoolType.Deserialize.
SDC.ReturnBoolType.ReturnBoolType(BaseType parentNode, bool fillData=true)
virtual bool SDC.ReturnBoolType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnBoolType._item1, SDC.null.
virtual string SDC.ReturnBoolType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnBoolType object into an XML string
string XML value
virtual string SDC.ReturnBoolType.Serialize()
Referenced by SDC.ReturnBoolType.SaveToFile.
virtual bool SDC.ReturnBoolType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnBoolType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnBoolType.SaveToFile.
virtual bool SDC.ReturnBoolType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnBoolType.SaveToFile.
virtual void SDC.ReturnBoolType.SaveToFile(string fileName)
References SDC.ReturnBoolType.SaveToFile.
virtual void SDC.ReturnBoolType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnBoolType.Serialize.
SDC.ReturnBoolType.ReturnBoolType()
static bool SDC.ReturnBoolType.Deserialize(string input, out ReturnBoolType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnBoolType object
input string workflow markup to deserialize obj Output ReturnBoolType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnBoolType.Deserialize, SDC.ReturnBoolType.LoadFromFile.
static bool SDC.ReturnBoolType.Deserialize(string input, out ReturnBoolType obj)
References SDC.ReturnBoolType.Deserialize, SDC.null.
static new ReturnBoolType SDC.ReturnBoolType.Deserialize(string input)
References SDC.null.
static ReturnBoolType SDC.ReturnBoolType.Deserialize(System.IO.Stream s)
References SDC.ReturnBoolType.Serializer.
static bool SDC.ReturnBoolType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnBoolType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnBoolType object
fileName string xml file to load and deserialize obj Output ReturnBoolType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnBoolType.LoadFromFile.
static bool SDC.ReturnBoolType.LoadFromFile(string fileName, out ReturnBoolType obj, out System.Exception exception)
References SDC.ReturnBoolType.LoadFromFile.
static bool SDC.ReturnBoolType.LoadFromFile(string fileName, out ReturnBoolType obj)
References SDC.ReturnBoolType.LoadFromFile, SDC.null.
static ReturnBoolType SDC.ReturnBoolType.LoadFromFile(string fileName)
References SDC.ReturnBoolType.LoadFromFile.
static new ReturnBoolType SDC.ReturnBoolType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnBoolType.Deserialize, SDC.null.