SDC::negativeInteger_DEtype
string SDC.negativeInteger_DEtype::_minInclusive
string SDC.negativeInteger_DEtype::_maxInclusive
string SDC.negativeInteger_DEtype::_minExclusive
string SDC.negativeInteger_DEtype::_maxExclusive
System Nullable< byte > SDC.negativeInteger_DEtype::_totalDigits
string SDC.negativeInteger_DEtype::_mask
ObjectChangeTracker SDC.negativeInteger_DEtype.changeTrackerField
static XmlSerializer SDC.negativeInteger_DEtype::serializer
string SDC.negativeInteger_DEtype::minInclusive
Referenced by SDC.negativeInteger_DEtype.ShouldSerializeminInclusive.
string SDC.negativeInteger_DEtype::maxInclusive
Referenced by SDC.negativeInteger_DEtype.ShouldSerializemaxInclusive.
string SDC.negativeInteger_DEtype::minExclusive
Referenced by SDC.negativeInteger_DEtype.ShouldSerializeminExclusive.
string SDC.negativeInteger_DEtype::maxExclusive
Referenced by SDC.negativeInteger_DEtype.ShouldSerializemaxExclusive.
byte SDC.negativeInteger_DEtype::totalDigits
bool SDC.negativeInteger_DEtype::totalDigitsSpecified
string SDC.negativeInteger_DEtype::mask
Referenced by SDC.negativeInteger_DEtype.ShouldSerializemask.
static XmlSerializer SDC.negativeInteger_DEtype::Serializer
Referenced by SDC.negativeInteger_DEtype.Deserialize.
ObjectChangeTracker SDC.negativeInteger_DEtype.ChangeTracker
SDC.negativeInteger_DEtype.negativeInteger_DEtype()
SDC.negativeInteger_DEtype.negativeInteger_DEtype(BaseType parentNode)
virtual bool SDC.negativeInteger_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.negativeInteger_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.negativeInteger_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.negativeInteger_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.negativeInteger_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.negativeInteger_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current negativeInteger_DEtype object into an XML string
string XML value
virtual string SDC.negativeInteger_DEtype.Serialize()
Referenced by SDC.negativeInteger_DEtype.SaveToFile.
virtual bool SDC.negativeInteger_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current negativeInteger_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.negativeInteger_DEtype.SaveToFile.
virtual bool SDC.negativeInteger_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.negativeInteger_DEtype.SaveToFile(string fileName)
virtual void SDC.negativeInteger_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.negativeInteger_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.negativeInteger_DEtype.minInclusive.
virtual bool SDC.negativeInteger_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.negativeInteger_DEtype.maxInclusive.
virtual bool SDC.negativeInteger_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.negativeInteger_DEtype.minExclusive.
virtual bool SDC.negativeInteger_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.negativeInteger_DEtype.maxExclusive.
virtual bool SDC.negativeInteger_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.negativeInteger_DEtype.mask.
virtual string SDC.negativeInteger_DEtype.Serialize()
Serializes current negativeInteger_DEtype object into an XML string
string XML value
virtual bool SDC.negativeInteger_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current negativeInteger_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.negativeInteger_DEtype.SaveToFile.
virtual void SDC.negativeInteger_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.negativeInteger_DEtype.Serialize.
virtual negativeInteger_DEtype SDC.negativeInteger_DEtype.Clone()
Create a clone of this negativeInteger_DEtype object
static bool SDC.negativeInteger_DEtype.Deserialize(string input, out negativeInteger_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an negativeInteger_DEtype object
input string workflow markup to deserialize obj Output negativeInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.negativeInteger_DEtype.Deserialize, SDC.negativeInteger_DEtype.LoadFromFile.
static bool SDC.negativeInteger_DEtype.Deserialize(string input, out negativeInteger_DEtype obj)
References SDC.null.
static new negativeInteger_DEtype SDC.negativeInteger_DEtype.Deserialize(string input)
References SDC.null.
static negativeInteger_DEtype SDC.negativeInteger_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.negativeInteger_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out negativeInteger_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an negativeInteger_DEtype object
fileName string xml file to load and deserialize obj Output negativeInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.negativeInteger_DEtype.LoadFromFile.
static bool SDC.negativeInteger_DEtype.LoadFromFile(string fileName, out negativeInteger_DEtype obj, out System.Exception exception)
static bool SDC.negativeInteger_DEtype.LoadFromFile(string fileName, out negativeInteger_DEtype obj)
References SDC.null.
static negativeInteger_DEtype SDC.negativeInteger_DEtype.LoadFromFile(string fileName)
static new negativeInteger_DEtype SDC.negativeInteger_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.negativeInteger_DEtype.Deserialize(string input, out negativeInteger_DEtype obj, out Exception exception)
Deserializes workflow markup into an negativeInteger_DEtype object
input string workflow markup to deserialize obj Output negativeInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.negativeInteger_DEtype.Deserialize, SDC.null.
static bool SDC.negativeInteger_DEtype.Deserialize(string input, out negativeInteger_DEtype obj)
References SDC.negativeInteger_DEtype.Deserialize, SDC.null.
static new negativeInteger_DEtype SDC.negativeInteger_DEtype.Deserialize(string input)
References SDC.null, SDC.negativeInteger_DEtype.Serializer.
static negativeInteger_DEtype SDC.negativeInteger_DEtype.Deserialize(Stream s)
References SDC.negativeInteger_DEtype.Serializer.
static bool SDC.negativeInteger_DEtype.LoadFromFile(string fileName, out negativeInteger_DEtype obj, out Exception exception)
Deserializes xml markup from file into an negativeInteger_DEtype object
fileName string xml file to load and deserialize obj Output negativeInteger_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.negativeInteger_DEtype.LoadFromFile, SDC.null.
static bool SDC.negativeInteger_DEtype.LoadFromFile(string fileName, out negativeInteger_DEtype obj)
References SDC.negativeInteger_DEtype.LoadFromFile, SDC.null.
static new negativeInteger_DEtype SDC.negativeInteger_DEtype.LoadFromFile(string fileName)
References SDC.negativeInteger_DEtype.Deserialize, SDC.null.