SDC::ActSaveResponsesType
RichTextType SDC.ActSaveResponsesType::_messageText
Referenced by SDC.ActSaveResponsesType.ShouldSerializeMessageText.
ObjectChangeTracker SDC.ActSaveResponsesType.changeTrackerField
static XmlSerializer SDC.ActSaveResponsesType::serializer
RichTextType SDC.ActSaveResponsesType::MessageText
static XmlSerializer SDC.ActSaveResponsesType::Serializer
Referenced by SDC.ActSaveResponsesType.Deserialize.
ObjectChangeTracker SDC.ActSaveResponsesType.ChangeTracker
SDC.ActSaveResponsesType.ActSaveResponsesType()
SDC.ActSaveResponsesType.ActSaveResponsesType(ThenType parentNode)
virtual bool SDC.ActSaveResponsesType.ShouldSerializeMessageText()
Test whether MessageText should be serialized
References SDC.null.
virtual string SDC.ActSaveResponsesType.Serialize(System.Text.Encoding encoding)
Serializes current ActSaveResponsesType object into an XML string
string XML value
virtual string SDC.ActSaveResponsesType.Serialize()
Referenced by SDC.ActSaveResponsesType.SaveToFile.
virtual bool SDC.ActSaveResponsesType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ActSaveResponsesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ActSaveResponsesType.SaveToFile.
virtual bool SDC.ActSaveResponsesType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ActSaveResponsesType.SaveToFile(string fileName)
virtual void SDC.ActSaveResponsesType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ActSaveResponsesType.ShouldSerializeMessageText()
Test whether MessageText should be serialized
References SDC.ActSaveResponsesType._messageText, SDC.null.
virtual string SDC.ActSaveResponsesType.Serialize()
Serializes current ActSaveResponsesType object into an XML string
string XML value
virtual bool SDC.ActSaveResponsesType.SaveToFile(string fileName, out Exception exception)
Serializes current ActSaveResponsesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ActSaveResponsesType.SaveToFile.
virtual void SDC.ActSaveResponsesType.SaveToFile(string fileName)
References SDC.null, SDC.ActSaveResponsesType.Serialize.
virtual ActSaveResponsesType SDC.ActSaveResponsesType.Clone()
Create a clone of this ActSaveResponsesType object
static bool SDC.ActSaveResponsesType.Deserialize(string input, out ActSaveResponsesType obj, out System.Exception exception)
Deserializes workflow markup into an ActSaveResponsesType object
input string workflow markup to deserialize obj Output ActSaveResponsesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActSaveResponsesType.Deserialize, SDC.ActSaveResponsesType.LoadFromFile.
static bool SDC.ActSaveResponsesType.Deserialize(string input, out ActSaveResponsesType obj)
References SDC.null.
static new ActSaveResponsesType SDC.ActSaveResponsesType.Deserialize(string input)
References SDC.null.
static ActSaveResponsesType SDC.ActSaveResponsesType.Deserialize(System.IO.Stream s)
static bool SDC.ActSaveResponsesType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ActSaveResponsesType obj, out System.Exception exception)
Deserializes xml markup from file into an ActSaveResponsesType object
fileName string xml file to load and deserialize obj Output ActSaveResponsesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ActSaveResponsesType.LoadFromFile.
static bool SDC.ActSaveResponsesType.LoadFromFile(string fileName, out ActSaveResponsesType obj, out System.Exception exception)
static bool SDC.ActSaveResponsesType.LoadFromFile(string fileName, out ActSaveResponsesType obj)
References SDC.null.
static ActSaveResponsesType SDC.ActSaveResponsesType.LoadFromFile(string fileName)
static new ActSaveResponsesType SDC.ActSaveResponsesType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ActSaveResponsesType.Deserialize(string input, out ActSaveResponsesType obj, out Exception exception)
Deserializes workflow markup into an ActSaveResponsesType object
input string workflow markup to deserialize obj Output ActSaveResponsesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActSaveResponsesType.Deserialize, SDC.null.
static bool SDC.ActSaveResponsesType.Deserialize(string input, out ActSaveResponsesType obj)
References SDC.ActSaveResponsesType.Deserialize, SDC.null.
static new ActSaveResponsesType SDC.ActSaveResponsesType.Deserialize(string input)
References SDC.null, SDC.ActSaveResponsesType.Serializer.
static ActSaveResponsesType SDC.ActSaveResponsesType.Deserialize(Stream s)
References SDC.ActSaveResponsesType.Serializer.
static bool SDC.ActSaveResponsesType.LoadFromFile(string fileName, out ActSaveResponsesType obj, out Exception exception)
Deserializes xml markup from file into an ActSaveResponsesType object
fileName string xml file to load and deserialize obj Output ActSaveResponsesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ActSaveResponsesType.LoadFromFile, SDC.null.
static bool SDC.ActSaveResponsesType.LoadFromFile(string fileName, out ActSaveResponsesType obj)
References SDC.ActSaveResponsesType.LoadFromFile, SDC.null.
static new ActSaveResponsesType SDC.ActSaveResponsesType.LoadFromFile(string fileName)
References SDC.ActSaveResponsesType.Deserialize, SDC.null.