SDC::PredicateInListType
bool SDC.PredicateInListType._shouldSerializenot
Referenced by SDC.PredicateInListType.ShouldSerializenot.
string SDC.PredicateInListType._list
bool SDC.PredicateInListType._not
Referenced by SDC.PredicateInListType.ShouldSerializenot.
ObjectChangeTracker SDC.PredicateInListType.changeTrackerField
XmlSerializer SDC.PredicateInListType.serializer
virtual string SDC.PredicateInListType.list
Space-delimited list of numeric or string values. The implementation must check for type compatability between the LHS and the RHS.
Referenced by SDC.PredicateInListType.ShouldSerializelist.
virtual bool SDC.PredicateInListType.not
If true, converts the function into: not InList()
virtual bool SDC.PredicateInListType.notSpecified
XmlSerializer SDC.PredicateInListType.Serializer
Referenced by SDC.PredicateInListType.Deserialize.
ObjectChangeTracker SDC.PredicateInListType.ChangeTracker
virtual bool SDC.PredicateInListType.ShouldSerializenot()
Test whether not should be serialized
References SDC.PredicateInListType._not, SDC.PredicateInListType._shouldSerializenot.
virtual bool SDC.PredicateInListType.ShouldSerializelist()
Test whether list should be serialized
References SDC.PredicateInListType.list.
virtual string SDC.PredicateInListType.Serialize()
Serializes current PredicateInListType object into an XML string
string XML value
Referenced by SDC.PredicateInListType.SaveToFile.
virtual bool SDC.PredicateInListType.SaveToFile(string fileName, out Exception exception)
Serializes current PredicateInListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.PredicateInListType.SaveToFile(string fileName)
References SDC.null, SDC.PredicateInListType.Serialize.
virtual PredicateInListType SDC.PredicateInListType.Clone()
Create a clone of this PredicateInListType object
static bool SDC.PredicateInListType.Deserialize(string input, out PredicateInListType obj, out Exception exception)
Deserializes workflow markup into an PredicateInListType object
input string workflow markup to deserialize obj Output PredicateInListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PredicateInListType.Deserialize, SDC.PredicateInListType.LoadFromFile.
static bool SDC.PredicateInListType.Deserialize(string input, out PredicateInListType obj)
References SDC.PredicateInListType.Deserialize, SDC.null.
static new PredicateInListType SDC.PredicateInListType.Deserialize(string input)
References SDC.null, SDC.PredicateInListType.Serializer.
static PredicateInListType SDC.PredicateInListType.Deserialize(Stream s)
References SDC.PredicateInListType.Serializer.
static bool SDC.PredicateInListType.LoadFromFile(string fileName, out PredicateInListType obj, out Exception exception)
Deserializes xml markup from file into an PredicateInListType object
fileName string xml file to load and deserialize obj Output PredicateInListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.PredicateInListType.LoadFromFile.
static bool SDC.PredicateInListType.LoadFromFile(string fileName, out PredicateInListType obj)
References SDC.PredicateInListType.LoadFromFile, SDC.null.
static new PredicateInListType SDC.PredicateInListType.LoadFromFile(string fileName)
References SDC.PredicateInListType.Deserialize, SDC.null.