SDC::ChangedListItemType
DataTypes_SType SDC.ChangedListItemType._listItemResponse
Referenced by SDC.ChangedListItemType.ShouldSerializeListItemResponse.
ObjectChangeTracker SDC.ChangedListItemType.changeTrackerField
XmlSerializer SDC.ChangedListItemType.serializer
virtual DataTypes_SType SDC.ChangedListItemType.ListItemResponse
If the selected ListItem contained a fill-in Response, then the value is recorded here.
XmlSerializer SDC.ChangedListItemType.Serializer
Referenced by SDC.ChangedListItemType.Deserialize.
ObjectChangeTracker SDC.ChangedListItemType.ChangeTracker
virtual bool SDC.ChangedListItemType.ShouldSerializeListItemResponse()
Test whether ListItemResponse should be serialized
References SDC.ChangedListItemType._listItemResponse, SDC.null.
virtual string SDC.ChangedListItemType.Serialize()
Serializes current ChangedListItemType object into an XML string
string XML value
Referenced by SDC.ChangedListItemType.SaveToFile.
virtual bool SDC.ChangedListItemType.SaveToFile(string fileName, out Exception exception)
Serializes current ChangedListItemType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
virtual void SDC.ChangedListItemType.SaveToFile(string fileName)
References SDC.null, SDC.ChangedListItemType.Serialize.
virtual ChangedListItemType SDC.ChangedListItemType.Clone()
Create a clone of this ChangedListItemType object
static bool SDC.ChangedListItemType.Deserialize(string input, out ChangedListItemType obj, out Exception exception)
Deserializes workflow markup into an ChangedListItemType object
input string workflow markup to deserialize obj Output ChangedListItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangedListItemType.Deserialize, SDC.ChangedListItemType.LoadFromFile.
static bool SDC.ChangedListItemType.Deserialize(string input, out ChangedListItemType obj)
References SDC.ChangedListItemType.Deserialize, SDC.null.
static new ChangedListItemType SDC.ChangedListItemType.Deserialize(string input)
References SDC.null, SDC.ChangedListItemType.Serializer.
static ChangedListItemType SDC.ChangedListItemType.Deserialize(Stream s)
References SDC.ChangedListItemType.Serializer.
static bool SDC.ChangedListItemType.LoadFromFile(string fileName, out ChangedListItemType obj, out Exception exception)
Deserializes xml markup from file into an ChangedListItemType object
fileName string xml file to load and deserialize obj Output ChangedListItemType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ChangedListItemType.LoadFromFile.
static bool SDC.ChangedListItemType.LoadFromFile(string fileName, out ChangedListItemType obj)
References SDC.ChangedListItemType.LoadFromFile, SDC.null.
static new ChangedListItemType SDC.ChangedListItemType.LoadFromFile(string fileName)
References SDC.ChangedListItemType.Deserialize, SDC.null.