SDC::EventType
List<ExtensionBaseType> SDC.EventType._items
XmlSerializer SDC.EventType.serializer
virtual List<ExtensionBaseType> SDC.EventType.Items
Referenced by SDC.EventType.ShouldSerializeItems.
XmlSerializer SDC.EventType.Serializer
Referenced by SDC.EventType.Deserialize.
SDC.EventType.EventType()
SDC.EventType.EventType(BaseType parentNode, bool fillData=true)
virtual bool SDC.EventType.ShouldSerializeItems()
Test whether Items should be serialized
References SDC.EventType.Items, SDC.null.
virtual string SDC.EventType.Serialize(System.Text.Encoding encoding)
Serializes current EventType object into an XML string
string XML value
virtual string SDC.EventType.Serialize()
Referenced by SDC.EventType.SaveToFile.
virtual bool SDC.EventType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current EventType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.EventType.SaveToFile.
virtual bool SDC.EventType.SaveToFile(string fileName, out System.Exception exception)
References SDC.EventType.SaveToFile.
virtual void SDC.EventType.SaveToFile(string fileName)
References SDC.EventType.SaveToFile.
virtual void SDC.EventType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.EventType.Serialize.
static bool SDC.EventType.Deserialize(string input, out EventType obj, out System.Exception exception)
Deserializes workflow markup into an EventType object
input string workflow markup to deserialize obj Output EventType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.EventType.Deserialize, SDC.EventType.LoadFromFile.
static bool SDC.EventType.Deserialize(string input, out EventType obj)
References SDC.EventType.Deserialize, SDC.null.
static new EventType SDC.EventType.Deserialize(string input)
References SDC.null.
static EventType SDC.EventType.Deserialize(System.IO.Stream s)
References SDC.EventType.Serializer.
static bool SDC.EventType.LoadFromFile(string fileName, System.Text.Encoding encoding, out EventType obj, out System.Exception exception)
Deserializes xml markup from file into an EventType object
fileName string xml file to load and deserialize obj Output EventType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.EventType.LoadFromFile.
static bool SDC.EventType.LoadFromFile(string fileName, out EventType obj, out System.Exception exception)
References SDC.EventType.LoadFromFile.
static bool SDC.EventType.LoadFromFile(string fileName, out EventType obj)
References SDC.EventType.LoadFromFile, SDC.null.
static EventType SDC.EventType.LoadFromFile(string fileName)
References SDC.EventType.LoadFromFile.
static new EventType SDC.EventType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.EventType.Deserialize, SDC.null.