SDC::ReturnAtomicType
DataTypes_DEType SDC.ReturnAtomicType._item1
Referenced by SDC.ReturnAtomicType.ShouldSerializeItem1.
XmlSerializer SDC.ReturnAtomicType.serializer
virtual DataTypes_DEType SDC.ReturnAtomicType.Item1
XmlSerializer SDC.ReturnAtomicType.Serializer
Referenced by SDC.ReturnAtomicType.Deserialize.
virtual bool SDC.ReturnAtomicType.ShouldSerializeItem1()
Test whether Item1 should be serialized
References SDC.ReturnAtomicType._item1, SDC.null.
virtual string SDC.ReturnAtomicType.Serialize(System.Text.Encoding encoding)
Serializes current ReturnAtomicType object into an XML string
string XML value
virtual string SDC.ReturnAtomicType.Serialize()
Referenced by SDC.ReturnAtomicType.SaveToFile.
virtual bool SDC.ReturnAtomicType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ReturnAtomicType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ReturnAtomicType.SaveToFile.
virtual bool SDC.ReturnAtomicType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ReturnAtomicType.SaveToFile.
virtual void SDC.ReturnAtomicType.SaveToFile(string fileName)
References SDC.ReturnAtomicType.SaveToFile.
virtual void SDC.ReturnAtomicType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ReturnAtomicType.Serialize.
static bool SDC.ReturnAtomicType.Deserialize(string input, out ReturnAtomicType obj, out System.Exception exception)
Deserializes workflow markup into an ReturnAtomicType object
input string workflow markup to deserialize obj Output ReturnAtomicType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnAtomicType.Deserialize, SDC.ReturnAtomicType.LoadFromFile.
static bool SDC.ReturnAtomicType.Deserialize(string input, out ReturnAtomicType obj)
References SDC.ReturnAtomicType.Deserialize, SDC.null.
static new ReturnAtomicType SDC.ReturnAtomicType.Deserialize(string input)
References SDC.null.
static ReturnAtomicType SDC.ReturnAtomicType.Deserialize(System.IO.Stream s)
References SDC.ReturnAtomicType.Serializer.
static bool SDC.ReturnAtomicType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ReturnAtomicType obj, out System.Exception exception)
Deserializes xml markup from file into an ReturnAtomicType object
fileName string xml file to load and deserialize obj Output ReturnAtomicType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ReturnAtomicType.LoadFromFile.
static bool SDC.ReturnAtomicType.LoadFromFile(string fileName, out ReturnAtomicType obj, out System.Exception exception)
References SDC.ReturnAtomicType.LoadFromFile.
static bool SDC.ReturnAtomicType.LoadFromFile(string fileName, out ReturnAtomicType obj)
References SDC.ReturnAtomicType.LoadFromFile, SDC.null.
static ReturnAtomicType SDC.ReturnAtomicType.LoadFromFile(string fileName)
References SDC.ReturnAtomicType.LoadFromFile.
static new ReturnAtomicType SDC.ReturnAtomicType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ReturnAtomicType.Deserialize, SDC.null.