SDC::ResponseFieldType
DataTypes_DEType SDC.ResponseFieldType::_response
Referenced by SDC.ResponseFieldType.ShouldSerializeResponse.
AnyFunctionsAnyType SDC.ResponseFieldType._setValue
Referenced by SDC.ResponseFieldType.ShouldSerializeSetValue.
List<ExtensionType> SDC.ResponseFieldType._x_Extension
RichTextType SDC.ResponseFieldType::_textAfterResponse
Referenced by SDC.ResponseFieldType.ShouldSerializeTextAfterResponse.
UnitsType SDC.ResponseFieldType::_responseUnits
Referenced by SDC.ResponseFieldType.ShouldSerializeResponseUnits.
List<EventType> SDC.ResponseFieldType._afterChange
List<OnEventType> SDC.ResponseFieldType._onEvent
BindingList<ExtensionType> SDC.ResponseFieldType._extension1
BindingList<IfThenType> SDC.ResponseFieldType._afterChange
BindingList<OnEventType> SDC.ResponseFieldType._onEvent
ExpressionType SDC.ResponseFieldType._setResponseValue
Referenced by SDC.ResponseFieldType.ShouldSerializeSetResponseValue.
ObjectChangeTracker SDC.ResponseFieldType.changeTrackerField
static XmlSerializer SDC.ResponseFieldType::serializer
DataTypes_DEType SDC.ResponseFieldType::Response
W3C Schema data type details
Referenced by SDC.SDCTreeBuilderEcc.AddDataTypesDE, SDC.SDCTreeBuilder.AddDataTypesDE, SDC.SDCTreeBuilderEcc.AddFillDataTypesDE.
virtual AnyFunctionsAnyType SDC.ResponseFieldType.SetValue
NEW
virtual List<ExtensionType> SDC.ResponseFieldType.X_Extension
Referenced by SDC.ResponseFieldType.ShouldSerializeX_Extension.
RichTextType SDC.ResponseFieldType::TextAfterResponse
TextAfterResponse is fixed text that appears after (to the right of) the user's response on the data entry form. This may be text for units such as "mm", "cm", etc.
UnitsType SDC.ResponseFieldType::ResponseUnits
virtual List<EventType> SDC.ResponseFieldType.AfterChange
Event that occurs after the Response value is changed, usually fired after a user leaves the Response field.
Referenced by SDC.ResponseFieldType.ShouldSerializeAfterChange.
virtual List<OnEventType> SDC.ResponseFieldType.OnEvent
Referenced by SDC.ResponseFieldType.ShouldSerializeOnEvent.
static XmlSerializer SDC.ResponseFieldType::Serializer
Referenced by SDC.ResponseFieldType.Deserialize.
virtual BindingList<ExtensionType> SDC.ResponseFieldType.Extension1
virtual BindingList<IfThenType> SDC.ResponseFieldType.AfterChange
Event that occurs after the Response value is changed, usually fired after a user leaves the Response field.
virtual BindingList<OnEventType> SDC.ResponseFieldType.OnEvent
virtual ExpressionType SDC.ResponseFieldType.SetResponseValue
Expression that is used to automaticaly set the Response value
ObjectChangeTracker SDC.ResponseFieldType.ChangeTracker
SDC.ResponseFieldType.ResponseFieldType()
SDC.ResponseFieldType.ResponseFieldType(BaseType parentNode, bool fillData=true)
SDC.ResponseFieldType.ResponseFieldType()
virtual bool SDC.ResponseFieldType.ShouldSerializeX_Extension()
Test whether X_Extension should be serialized
References SDC.null, SDC.ResponseFieldType.X_Extension.
virtual bool SDC.ResponseFieldType.ShouldSerializeAfterChange()
Test whether AfterChange should be serialized
References SDC.ResponseFieldType.AfterChange, SDC.null.
virtual bool SDC.ResponseFieldType.ShouldSerializeOnEvent()
Test whether OnEvent should be serialized
References SDC.null, SDC.ResponseFieldType.OnEvent.
virtual bool SDC.ResponseFieldType.ShouldSerializeResponse()
Test whether Response should be serialized
References SDC.ResponseFieldType._response, SDC.null.
virtual bool SDC.ResponseFieldType.ShouldSerializeSetValue()
Test whether SetValue should be serialized
References SDC.ResponseFieldType._setValue, SDC.null.
virtual bool SDC.ResponseFieldType.ShouldSerializeTextAfterResponse()
Test whether TextAfterResponse should be serialized
References SDC.ResponseFieldType._textAfterResponse, SDC.null.
virtual bool SDC.ResponseFieldType.ShouldSerializeResponseUnits()
Test whether ResponseUnits should be serialized
References SDC.ResponseFieldType._responseUnits, SDC.null.
virtual string SDC.ResponseFieldType.Serialize(System.Text.Encoding encoding)
Serializes current ResponseFieldType object into an XML string
string XML value
virtual string SDC.ResponseFieldType.Serialize()
Referenced by SDC.ResponseFieldType.SaveToFile.
virtual bool SDC.ResponseFieldType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ResponseFieldType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ResponseFieldType.SaveToFile.
virtual bool SDC.ResponseFieldType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ResponseFieldType.SaveToFile.
virtual void SDC.ResponseFieldType.SaveToFile(string fileName)
References SDC.ResponseFieldType.SaveToFile.
virtual void SDC.ResponseFieldType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ResponseFieldType.Serialize.
virtual bool SDC.ResponseFieldType.ShouldSerializeResponse()
Test whether Response should be serialized
References SDC.ResponseFieldType._response, SDC.null.
virtual bool SDC.ResponseFieldType.ShouldSerializeTextAfterResponse()
Test whether TextAfterResponse should be serialized
References SDC.ResponseFieldType._textAfterResponse, SDC.null.
virtual bool SDC.ResponseFieldType.ShouldSerializeResponseUnits()
Test whether ResponseUnits should be serialized
References SDC.ResponseFieldType._responseUnits, SDC.null.
virtual bool SDC.ResponseFieldType.ShouldSerializeSetResponseValue()
Test whether SetResponseValue should be serialized
References SDC.ResponseFieldType._setResponseValue, SDC.null.
virtual string SDC.ResponseFieldType.Serialize()
Serializes current ResponseFieldType object into an XML string
string XML value
virtual bool SDC.ResponseFieldType.SaveToFile(string fileName, out Exception exception)
Serializes current ResponseFieldType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ResponseFieldType.SaveToFile.
virtual void SDC.ResponseFieldType.SaveToFile(string fileName)
References SDC.null, SDC.ResponseFieldType.Serialize.
virtual ResponseFieldType SDC.ResponseFieldType.Clone()
Create a clone of this ResponseFieldType object
static bool SDC.ResponseFieldType.Deserialize(string input, out ResponseFieldType obj, out System.Exception exception)
Deserializes workflow markup into an ResponseFieldType object
input string workflow markup to deserialize obj Output ResponseFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ResponseFieldType.Deserialize, SDC.ResponseFieldType.LoadFromFile.
static bool SDC.ResponseFieldType.Deserialize(string input, out ResponseFieldType obj)
References SDC.ResponseFieldType.Deserialize, SDC.null.
static new ResponseFieldType SDC.ResponseFieldType.Deserialize(string input)
References SDC.null.
static ResponseFieldType SDC.ResponseFieldType.Deserialize(System.IO.Stream s)
References SDC.ResponseFieldType.Serializer.
static bool SDC.ResponseFieldType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ResponseFieldType obj, out System.Exception exception)
Deserializes xml markup from file into an ResponseFieldType object
fileName string xml file to load and deserialize obj Output ResponseFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ResponseFieldType.LoadFromFile.
static bool SDC.ResponseFieldType.LoadFromFile(string fileName, out ResponseFieldType obj, out System.Exception exception)
References SDC.ResponseFieldType.LoadFromFile.
static bool SDC.ResponseFieldType.LoadFromFile(string fileName, out ResponseFieldType obj)
References SDC.ResponseFieldType.LoadFromFile, SDC.null.
static ResponseFieldType SDC.ResponseFieldType.LoadFromFile(string fileName)
References SDC.ResponseFieldType.LoadFromFile.
static new ResponseFieldType SDC.ResponseFieldType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ResponseFieldType.Deserialize, SDC.null.
static bool SDC.ResponseFieldType.Deserialize(string input, out ResponseFieldType obj, out Exception exception)
Deserializes workflow markup into an ResponseFieldType object
input string workflow markup to deserialize obj Output ResponseFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ResponseFieldType.Deserialize, SDC.null.
static bool SDC.ResponseFieldType.Deserialize(string input, out ResponseFieldType obj)
References SDC.ResponseFieldType.Deserialize, SDC.null.
static new ResponseFieldType SDC.ResponseFieldType.Deserialize(string input)
References SDC.null, SDC.ResponseFieldType.Serializer.
static ResponseFieldType SDC.ResponseFieldType.Deserialize(Stream s)
References SDC.ResponseFieldType.Serializer.
static bool SDC.ResponseFieldType.LoadFromFile(string fileName, out ResponseFieldType obj, out Exception exception)
Deserializes xml markup from file into an ResponseFieldType object
fileName string xml file to load and deserialize obj Output ResponseFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ResponseFieldType.LoadFromFile, SDC.null.
static bool SDC.ResponseFieldType.LoadFromFile(string fileName, out ResponseFieldType obj)
References SDC.ResponseFieldType.LoadFromFile, SDC.null.
static new ResponseFieldType SDC.ResponseFieldType.LoadFromFile(string fileName)
References SDC.ResponseFieldType.Deserialize, SDC.null.