SDC::ContactType
PersonType SDC.ContactType._person
OrganizationType SDC.ContactType._organization
ExtensionBaseType SDC.ContactType._item
Referenced by SDC.ContactType.ShouldSerializeItem.
ObjectChangeTracker SDC.ContactType.changeTrackerField
static XmlSerializer SDC.ContactType::serializer
virtual PersonType SDC.ContactType.Person
virtual OrganizationType SDC.ContactType.Organization
static XmlSerializer SDC.ContactType::Serializer
Referenced by SDC.ContactType.Deserialize.
virtual ExtensionBaseType SDC.ContactType.Item
ObjectChangeTracker SDC.ContactType.ChangeTracker
SDC.ContactType.ContactType(BaseType parentNode)
PersonType SDC.ContactType.AddPerson()
OrganizationType SDC.ContactType.AddOrganization()
SDC.ContactType.ContactType()
PersonType SDC.ContactType.AddPerson()
OrganizationType SDC.ContactType.AddOrganization()
virtual bool SDC.ContactType.ShouldSerializePerson()
Test whether Person should be serialized
References SDC.null.
virtual bool SDC.ContactType.ShouldSerializeOrganization()
Test whether Organization should be serialized
References SDC.null.
virtual string SDC.ContactType.Serialize(System.Text.Encoding encoding)
Serializes current ContactType object into an XML string
string XML value
virtual string SDC.ContactType.Serialize()
Referenced by SDC.ContactType.SaveToFile.
virtual bool SDC.ContactType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ContactType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ContactType.SaveToFile.
virtual bool SDC.ContactType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ContactType.SaveToFile(string fileName)
virtual void SDC.ContactType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.ContactType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.ContactType._item, SDC.null.
virtual string SDC.ContactType.Serialize()
Serializes current ContactType object into an XML string
string XML value
virtual bool SDC.ContactType.SaveToFile(string fileName, out Exception exception)
Serializes current ContactType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ContactType.SaveToFile.
virtual void SDC.ContactType.SaveToFile(string fileName)
References SDC.null, SDC.ContactType.Serialize.
virtual ContactType SDC.ContactType.Clone()
Create a clone of this ContactType object
SDC.ContactType.ContactType()
static bool SDC.ContactType.Deserialize(string input, out ContactType obj, out System.Exception exception)
Deserializes workflow markup into an ContactType object
input string workflow markup to deserialize obj Output ContactType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ContactType.Deserialize, SDC.ContactType.LoadFromFile.
static bool SDC.ContactType.Deserialize(string input, out ContactType obj)
References SDC.null.
static new ContactType SDC.ContactType.Deserialize(string input)
References SDC.null.
static ContactType SDC.ContactType.Deserialize(System.IO.Stream s)
static bool SDC.ContactType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ContactType obj, out System.Exception exception)
Deserializes xml markup from file into an ContactType object
fileName string xml file to load and deserialize obj Output ContactType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ContactType.LoadFromFile.
static bool SDC.ContactType.LoadFromFile(string fileName, out ContactType obj, out System.Exception exception)
static bool SDC.ContactType.LoadFromFile(string fileName, out ContactType obj)
References SDC.null.
static ContactType SDC.ContactType.LoadFromFile(string fileName)
static new ContactType SDC.ContactType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ContactType.Deserialize(string input, out ContactType obj, out Exception exception)
Deserializes workflow markup into an ContactType object
input string workflow markup to deserialize obj Output ContactType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ContactType.Deserialize, SDC.null.
static bool SDC.ContactType.Deserialize(string input, out ContactType obj)
References SDC.ContactType.Deserialize, SDC.null.
static new ContactType SDC.ContactType.Deserialize(string input)
References SDC.null, SDC.ContactType.Serializer.
static ContactType SDC.ContactType.Deserialize(Stream s)
References SDC.ContactType.Serializer.
static bool SDC.ContactType.LoadFromFile(string fileName, out ContactType obj, out Exception exception)
Deserializes xml markup from file into an ContactType object
fileName string xml file to load and deserialize obj Output ContactType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ContactType.LoadFromFile, SDC.null.
static bool SDC.ContactType.LoadFromFile(string fileName, out ContactType obj)
References SDC.ContactType.LoadFromFile, SDC.null.
static new ContactType SDC.ContactType.LoadFromFile(string fileName)
References SDC.ContactType.Deserialize, SDC.null.