SDC::XML_Stype
List<System.Xml.XmlElement> SDC.XML_Stype._any
string SDC.XML_Stype::_schema
BindingList<System.Xml.XmlElement> SDC.XML_Stype._any
ObjectChangeTracker SDC.XML_Stype.changeTrackerField
static XmlSerializer SDC.XML_Stype::serializer
virtual List<System.Xml.XmlElement> SDC.XML_Stype.Any
Referenced by SDC.XML_Stype.ShouldSerializeAny.
string SDC.XML_Stype::schema
Referenced by SDC.XML_Stype.ShouldSerializeschema.
static XmlSerializer SDC.XML_Stype::Serializer
Referenced by SDC.XML_Stype.Deserialize.
virtual BindingList<System.Xml.XmlElement> SDC.XML_Stype.Any
ObjectChangeTracker SDC.XML_Stype.ChangeTracker
SDC.XML_Stype.XML_Stype()
SDC.XML_Stype.XML_Stype(BaseType parentNode)
SDC.XML_Stype.XML_Stype()
virtual bool SDC.XML_Stype.ShouldSerializeAny()
Test whether Any should be serialized
References SDC.XML_Stype.Any, SDC.null.
virtual bool SDC.XML_Stype.ShouldSerializeschema()
Test whether schema should be serialized
References SDC.XML_Stype.schema.
virtual string SDC.XML_Stype.Serialize(System.Text.Encoding encoding)
Serializes current XML_Stype object into an XML string
string XML value
virtual string SDC.XML_Stype.Serialize()
Referenced by SDC.XML_Stype.SaveToFile.
virtual bool SDC.XML_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current XML_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.XML_Stype.SaveToFile.
virtual bool SDC.XML_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.XML_Stype.SaveToFile.
virtual void SDC.XML_Stype.SaveToFile(string fileName)
References SDC.XML_Stype.SaveToFile.
virtual void SDC.XML_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.XML_Stype.Serialize.
virtual bool SDC.XML_Stype.ShouldSerializeschema()
Test whether schema should be serialized
References SDC.XML_Stype.schema.
virtual string SDC.XML_Stype.Serialize()
Serializes current XML_Stype object into an XML string
string XML value
virtual bool SDC.XML_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current XML_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.XML_Stype.SaveToFile.
virtual void SDC.XML_Stype.SaveToFile(string fileName)
References SDC.null, SDC.XML_Stype.Serialize.
virtual XML_Stype SDC.XML_Stype.Clone()
Create a clone of this XML_Stype object
static bool SDC.XML_Stype.Deserialize(string input, out XML_Stype obj, out System.Exception exception)
Deserializes workflow markup into an XML_Stype object
input string workflow markup to deserialize obj Output XML_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.XML_Stype.Deserialize, SDC.XML_Stype.LoadFromFile.
static bool SDC.XML_Stype.Deserialize(string input, out XML_Stype obj)
References SDC.XML_Stype.Deserialize, SDC.null.
static new XML_Stype SDC.XML_Stype.Deserialize(string input)
References SDC.null.
static XML_Stype SDC.XML_Stype.Deserialize(System.IO.Stream s)
References SDC.XML_Stype.Serializer.
static bool SDC.XML_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out XML_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an XML_Stype object
fileName string xml file to load and deserialize obj Output XML_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.XML_Stype.LoadFromFile.
static bool SDC.XML_Stype.LoadFromFile(string fileName, out XML_Stype obj, out System.Exception exception)
References SDC.XML_Stype.LoadFromFile.
static bool SDC.XML_Stype.LoadFromFile(string fileName, out XML_Stype obj)
References SDC.XML_Stype.LoadFromFile, SDC.null.
static XML_Stype SDC.XML_Stype.LoadFromFile(string fileName)
References SDC.XML_Stype.LoadFromFile.
static new XML_Stype SDC.XML_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.XML_Stype.Deserialize, SDC.null.
static bool SDC.XML_Stype.Deserialize(string input, out XML_Stype obj, out Exception exception)
Deserializes workflow markup into an XML_Stype object
input string workflow markup to deserialize obj Output XML_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.XML_Stype.Deserialize, SDC.null.
static bool SDC.XML_Stype.Deserialize(string input, out XML_Stype obj)
References SDC.XML_Stype.Deserialize, SDC.null.
static new XML_Stype SDC.XML_Stype.Deserialize(string input)
References SDC.null, SDC.XML_Stype.Serializer.
static XML_Stype SDC.XML_Stype.Deserialize(Stream s)
References SDC.XML_Stype.Serializer.
static bool SDC.XML_Stype.LoadFromFile(string fileName, out XML_Stype obj, out Exception exception)
Deserializes xml markup from file into an XML_Stype object
fileName string xml file to load and deserialize obj Output XML_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.XML_Stype.LoadFromFile, SDC.null.
static bool SDC.XML_Stype.LoadFromFile(string fileName, out XML_Stype obj)
References SDC.XML_Stype.LoadFromFile, SDC.null.
static new XML_Stype SDC.XML_Stype.LoadFromFile(string fileName)
References SDC.XML_Stype.Deserialize, SDC.null.