SDC::InputStr_ReturnBoolType
StringFunctionsBoolType SDC.InputStr_ReturnBoolType._stringPredicate
Referenced by SDC.InputStr_ReturnBoolType.ShouldSerializeStringPredicate.
XmlSerializer SDC.InputStr_ReturnBoolType.serializer
virtual StringFunctionsBoolType SDC.InputStr_ReturnBoolType.StringPredicate
XmlSerializer SDC.InputStr_ReturnBoolType.Serializer
Referenced by SDC.InputStr_ReturnBoolType.Deserialize.
virtual bool SDC.InputStr_ReturnBoolType.ShouldSerializeStringPredicate()
Test whether StringPredicate should be serialized
References SDC.InputStr_ReturnBoolType._stringPredicate, SDC.null.
virtual string SDC.InputStr_ReturnBoolType.Serialize(System.Text.Encoding encoding)
Serializes current InputStr_ReturnBoolType object into an XML string
string XML value
virtual string SDC.InputStr_ReturnBoolType.Serialize()
Referenced by SDC.InputStr_ReturnBoolType.SaveToFile.
virtual bool SDC.InputStr_ReturnBoolType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InputStr_ReturnBoolType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InputStr_ReturnBoolType.SaveToFile.
virtual bool SDC.InputStr_ReturnBoolType.SaveToFile(string fileName, out System.Exception exception)
References SDC.InputStr_ReturnBoolType.SaveToFile.
virtual void SDC.InputStr_ReturnBoolType.SaveToFile(string fileName)
References SDC.InputStr_ReturnBoolType.SaveToFile.
virtual void SDC.InputStr_ReturnBoolType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InputStr_ReturnBoolType.Serialize.
static bool SDC.InputStr_ReturnBoolType.Deserialize(string input, out InputStr_ReturnBoolType obj, out System.Exception exception)
Deserializes workflow markup into an InputStr_ReturnBoolType object
input string workflow markup to deserialize obj Output InputStr_ReturnBoolType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnBoolType.Deserialize, SDC.InputStr_ReturnBoolType.LoadFromFile.
static bool SDC.InputStr_ReturnBoolType.Deserialize(string input, out InputStr_ReturnBoolType obj)
References SDC.InputStr_ReturnBoolType.Deserialize, SDC.null.
static new InputStr_ReturnBoolType SDC.InputStr_ReturnBoolType.Deserialize(string input)
References SDC.null.
static InputStr_ReturnBoolType SDC.InputStr_ReturnBoolType.Deserialize(System.IO.Stream s)
References SDC.InputStr_ReturnBoolType.Serializer.
static bool SDC.InputStr_ReturnBoolType.LoadFromFile(string fileName, System.Text.Encoding encoding, out InputStr_ReturnBoolType obj, out System.Exception exception)
Deserializes xml markup from file into an InputStr_ReturnBoolType object
fileName string xml file to load and deserialize obj Output InputStr_ReturnBoolType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnBoolType.LoadFromFile.
static bool SDC.InputStr_ReturnBoolType.LoadFromFile(string fileName, out InputStr_ReturnBoolType obj, out System.Exception exception)
References SDC.InputStr_ReturnBoolType.LoadFromFile.
static bool SDC.InputStr_ReturnBoolType.LoadFromFile(string fileName, out InputStr_ReturnBoolType obj)
References SDC.InputStr_ReturnBoolType.LoadFromFile, SDC.null.
static InputStr_ReturnBoolType SDC.InputStr_ReturnBoolType.LoadFromFile(string fileName)
References SDC.InputStr_ReturnBoolType.LoadFromFile.
static new InputStr_ReturnBoolType SDC.InputStr_ReturnBoolType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InputStr_ReturnBoolType.Deserialize, SDC.null.