SDC::dateTimeStamp_DEtype
bool SDC.dateTimeStamp_DEtype::_shouldSerializeminInclusive
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializeminInclusive.
bool SDC.dateTimeStamp_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializemaxInclusive.
bool SDC.dateTimeStamp_DEtype::_shouldSerializeminExclusive
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializeminExclusive.
bool SDC.dateTimeStamp_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializemaxExclusive.
System.Nullable<System.DateTime> SDC.dateTimeStamp_DEtype._maxExclusive
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializemaxExclusive.
System.Nullable<System.DateTime> SDC.dateTimeStamp_DEtype._minExclusive
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializeminExclusive.
System.Nullable<System.DateTime> SDC.dateTimeStamp_DEtype._maxInclusive
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializemaxInclusive.
System.Nullable<System.DateTime> SDC.dateTimeStamp_DEtype._minInclusive
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializeminInclusive.
string SDC.dateTimeStamp_DEtype::_mask
DateTime SDC.dateTimeStamp_DEtype._maxExclusive
DateTime SDC.dateTimeStamp_DEtype._minExclusive
DateTime SDC.dateTimeStamp_DEtype._maxInclusive
DateTime SDC.dateTimeStamp_DEtype._minInclusive
ObjectChangeTracker SDC.dateTimeStamp_DEtype.changeTrackerField
static XmlSerializer SDC.dateTimeStamp_DEtype::serializer
System DateTime SDC.dateTimeStamp_DEtype::maxExclusive
bool SDC.dateTimeStamp_DEtype::maxExclusiveSpecified
System DateTime SDC.dateTimeStamp_DEtype::minExclusive
bool SDC.dateTimeStamp_DEtype::minExclusiveSpecified
System DateTime SDC.dateTimeStamp_DEtype::maxInclusive
bool SDC.dateTimeStamp_DEtype::maxInclusiveSpecified
System DateTime SDC.dateTimeStamp_DEtype::minInclusive
bool SDC.dateTimeStamp_DEtype::minInclusiveSpecified
string SDC.dateTimeStamp_DEtype::mask
Referenced by SDC.dateTimeStamp_DEtype.ShouldSerializemask.
static XmlSerializer SDC.dateTimeStamp_DEtype::Serializer
Referenced by SDC.dateTimeStamp_DEtype.Deserialize.
ObjectChangeTracker SDC.dateTimeStamp_DEtype.ChangeTracker
SDC.dateTimeStamp_DEtype.dateTimeStamp_DEtype()
SDC.dateTimeStamp_DEtype.dateTimeStamp_DEtype(BaseType parentNode)
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.dateTimeStamp_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current dateTimeStamp_DEtype object into an XML string
string XML value
virtual string SDC.dateTimeStamp_DEtype.Serialize()
Referenced by SDC.dateTimeStamp_DEtype.SaveToFile.
virtual bool SDC.dateTimeStamp_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current dateTimeStamp_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.dateTimeStamp_DEtype.SaveToFile.
virtual bool SDC.dateTimeStamp_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.dateTimeStamp_DEtype.SaveToFile(string fileName)
virtual void SDC.dateTimeStamp_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.dateTimeStamp_DEtype._maxExclusive, SDC.dateTimeStamp_DEtype._shouldSerializemaxExclusive.
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.dateTimeStamp_DEtype._minExclusive, SDC.dateTimeStamp_DEtype._shouldSerializeminExclusive.
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.dateTimeStamp_DEtype._maxInclusive, SDC.dateTimeStamp_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.dateTimeStamp_DEtype._minInclusive, SDC.dateTimeStamp_DEtype._shouldSerializeminInclusive.
virtual bool SDC.dateTimeStamp_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.dateTimeStamp_DEtype.mask.
virtual string SDC.dateTimeStamp_DEtype.Serialize()
Serializes current dateTimeStamp_DEtype object into an XML string
string XML value
virtual bool SDC.dateTimeStamp_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current dateTimeStamp_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.dateTimeStamp_DEtype.SaveToFile.
virtual void SDC.dateTimeStamp_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.dateTimeStamp_DEtype.Serialize.
virtual dateTimeStamp_DEtype SDC.dateTimeStamp_DEtype.Clone()
Create a clone of this dateTimeStamp_DEtype object
static bool SDC.dateTimeStamp_DEtype.Deserialize(string input, out dateTimeStamp_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an dateTimeStamp_DEtype object
input string workflow markup to deserialize obj Output dateTimeStamp_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dateTimeStamp_DEtype.Deserialize, SDC.dateTimeStamp_DEtype.LoadFromFile.
static bool SDC.dateTimeStamp_DEtype.Deserialize(string input, out dateTimeStamp_DEtype obj)
References SDC.null.
static new dateTimeStamp_DEtype SDC.dateTimeStamp_DEtype.Deserialize(string input)
References SDC.null.
static dateTimeStamp_DEtype SDC.dateTimeStamp_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.dateTimeStamp_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out dateTimeStamp_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an dateTimeStamp_DEtype object
fileName string xml file to load and deserialize obj Output dateTimeStamp_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.dateTimeStamp_DEtype.LoadFromFile.
static bool SDC.dateTimeStamp_DEtype.LoadFromFile(string fileName, out dateTimeStamp_DEtype obj, out System.Exception exception)
static bool SDC.dateTimeStamp_DEtype.LoadFromFile(string fileName, out dateTimeStamp_DEtype obj)
References SDC.null.
static dateTimeStamp_DEtype SDC.dateTimeStamp_DEtype.LoadFromFile(string fileName)
static new dateTimeStamp_DEtype SDC.dateTimeStamp_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.dateTimeStamp_DEtype.Deserialize(string input, out dateTimeStamp_DEtype obj, out Exception exception)
Deserializes workflow markup into an dateTimeStamp_DEtype object
input string workflow markup to deserialize obj Output dateTimeStamp_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dateTimeStamp_DEtype.Deserialize, SDC.null.
static bool SDC.dateTimeStamp_DEtype.Deserialize(string input, out dateTimeStamp_DEtype obj)
References SDC.dateTimeStamp_DEtype.Deserialize, SDC.null.
static new dateTimeStamp_DEtype SDC.dateTimeStamp_DEtype.Deserialize(string input)
References SDC.null, SDC.dateTimeStamp_DEtype.Serializer.
static dateTimeStamp_DEtype SDC.dateTimeStamp_DEtype.Deserialize(Stream s)
References SDC.dateTimeStamp_DEtype.Serializer.
static bool SDC.dateTimeStamp_DEtype.LoadFromFile(string fileName, out dateTimeStamp_DEtype obj, out Exception exception)
Deserializes xml markup from file into an dateTimeStamp_DEtype object
fileName string xml file to load and deserialize obj Output dateTimeStamp_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.dateTimeStamp_DEtype.LoadFromFile, SDC.null.
static bool SDC.dateTimeStamp_DEtype.LoadFromFile(string fileName, out dateTimeStamp_DEtype obj)
References SDC.dateTimeStamp_DEtype.LoadFromFile, SDC.null.
static new dateTimeStamp_DEtype SDC.dateTimeStamp_DEtype.LoadFromFile(string fileName)
References SDC.dateTimeStamp_DEtype.Deserialize, SDC.null.