SDC::ListFieldType
ListType SDC.ListFieldType::List_Item
+Replaced in original class: protected ListFieldType (){}
ListType to group ListItems
Referenced by SDC.SDCTreeBuilder.AddListToListField.
LookupEndPointType SDC.ListFieldType::LookupEndpoint_Item
Replaces Item
RichTextType SDC.ListFieldType::ListHeaderText
ListFieldType class constructor
The header row for a set of list items. If the list has more than one column, the column text is separated by the colTextDelimiter.
DataTypes_DEType SDC.ListFieldType::DefaultListItemDataType
Data type enumeration derived from W3C XML Schema. This element is used only if the ListItems are all associated with coded values from a single coding system.
CodeSystemType SDC.ListFieldType::DefaultCodeSystem
If coded values are used for items in a List (including ListItem and LookupEndPoint lists), then the default coding system should be specified here. For ListItem nodes, any exceptions to the coding system may be specified on the individual ListItem nodes. For LookupEndPoints, the endpoint data can optionally specify any exceptions in a dedicated CodeSystem column in the returned list data.
ExtensionBaseType SDC.ListFieldType::Item
virtual List<RuleSelectionTestType> SDC.ListFieldType.IllegalListItemPairings
virtual List<RuleSingleSelectionSetsType> SDC.ListFieldType.IllegalCoSelectedListItems
virtual List<EventType> SDC.ListFieldType.AfterChange
Event that occurs after List Field selections are changed.
virtual List<OnEventType> SDC.ListFieldType.OnEvent
string SDC.ListFieldType::colTextDelimiter
Character in the DisplayText that separates the columns and rows in a single or multi-column list.
Referenced by SDC.ListFieldType.ShouldSerializecolTextDelimiter.
byte SDC.ListFieldType::numCols
Number of columns in the list
byte SDC.ListFieldType::storedCol
Determines which column of the list is stored in a database. This list is one-based.
ushort SDC.ListFieldType::minSelections
Minimum number of answer choices (list items) that must be selected by the user. Default value is 1.
Minimum number of answer choices (list items) that must be selected by the user. If set to 0, then this question need not be answered by the user. NEW: changed minimum value to 1. Removed: If set to 0, then this question need not be answered by the user.
ushort SDC.ListFieldType::maxSelections
Maximum number of answer choices (list items) that can be selected by the user. Must be greater than or equal to minSelections, and no larger than the total number of list items.
Maximum number of answer choices (list items) that can be selected by the user. Must be greater than or equal to minSelections, and no larger than the total number of list itmes.A value of 0 indicates no limit to the number of selected list items (answers). This effectively means that the question is multi-select. (Abbreviated as QM)A value of 1 (the default) indicates that the question list is single-select. (Abbreviated as QS) A value of 0 indicates no limit to the number of selected list items (answers). This effectively means that the question is multi-select. (Abbreviated as QM)A value of 1 indicates that the question list is single-select. (Abbreviated as QS)
bool SDC.ListFieldType::ordered
If false, then the form implementation may change the order of items in the list.
static XmlSerializer SDC.ListFieldType::Serializer
Referenced by SDC.ListFieldType.Deserialize.
virtual BindingList<ExclusiveItemPairsType> SDC.ListFieldType.IllegalListItemPairings
virtual BindingList<IfThenType> SDC.ListFieldType.AfterChange
Event that occurs after List Field selections are changed.
virtual BindingList<OnEventType> SDC.ListFieldType.OnEvent
ObjectChangeTracker SDC.ListFieldType.ChangeTracker
bool SDC.ListFieldType::_shouldSerializeordered
Referenced by SDC.ListFieldType.ShouldSerializeordered.
bool SDC.ListFieldType::_shouldSerializemaxSelections
Referenced by SDC.ListFieldType.ShouldSerializemaxSelections.
bool SDC.ListFieldType::_shouldSerializeminSelections
Referenced by SDC.ListFieldType.ShouldSerializeminSelections.
RichTextType SDC.ListFieldType::_listHeaderText
Referenced by SDC.ListFieldType.ShouldSerializeListHeaderText.
DataTypes_DEType SDC.ListFieldType::_defaultListItemDataType
Referenced by SDC.ListFieldType.ShouldSerializeDefaultListItemDataType.
CodeSystemType SDC.ListFieldType::_defaultCodeSystem
Referenced by SDC.ListFieldType.ShouldSerializeDefaultCodeSystem.
ExtensionBaseType SDC.ListFieldType::_item
Referenced by SDC.ListFieldType.ShouldSerializeItem.
List<RuleSelectionTestType> SDC.ListFieldType._illegalListItemPairings
List<RuleSingleSelectionSetsType> SDC.ListFieldType._illegalCoSelectedListItems
List<EventType> SDC.ListFieldType._afterChange
List<OnEventType> SDC.ListFieldType._onEvent
string SDC.ListFieldType::_colTextDelimiter
Referenced by SDC.ListFieldType.ListFieldType.
byte SDC.ListFieldType::_numCols
Referenced by SDC.ListFieldType.ListFieldType.
byte SDC.ListFieldType::_storedCol
Referenced by SDC.ListFieldType.ListFieldType.
ushort SDC.ListFieldType::_minSelections
Referenced by SDC.ListFieldType.ListFieldType, SDC.ListFieldType.ShouldSerializeminSelections.
ushort SDC.ListFieldType::_maxSelections
Referenced by SDC.ListFieldType.ListFieldType, SDC.ListFieldType.ShouldSerializemaxSelections.
bool SDC.ListFieldType::_ordered
Referenced by SDC.ListFieldType.ListFieldType, SDC.ListFieldType.ShouldSerializeordered.
BindingList<ExclusiveItemPairsType> SDC.ListFieldType._illegalListItemPairings
BindingList<IfThenType> SDC.ListFieldType._afterChange
BindingList<OnEventType> SDC.ListFieldType._onEvent
ObjectChangeTracker SDC.ListFieldType.changeTrackerField
static XmlSerializer SDC.ListFieldType::serializer
SDC.ListFieldType.ListFieldType()
SDC.ListFieldType.ListFieldType(BaseType parentNode, bool fillData=true)
References SDC.byte.
void SDC.ListFieldType.Fill_ListFieldType()
virtual bool SDC.ListFieldType.ShouldSerializeIllegalListItemPairings()
Test whether IllegalListItemPairings should be serialized
References SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeIllegalCoSelectedListItems()
Test whether IllegalCoSelectedListItems should be serialized
References SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeAfterChange()
Test whether AfterChange should be serialized
References SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeOnEvent()
Test whether OnEvent should be serialized
References SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeminSelections()
Test whether minSelections should be serialized
virtual bool SDC.ListFieldType.ShouldSerializemaxSelections()
Test whether maxSelections should be serialized
virtual bool SDC.ListFieldType.ShouldSerializeordered()
Test whether ordered should be serialized
virtual bool SDC.ListFieldType.ShouldSerializeListHeaderText()
Test whether ListHeaderText should be serialized
References SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeDefaultListItemDataType()
Test whether DefaultListItemDataType should be serialized
References SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeDefaultCodeSystem()
Test whether DefaultCodeSystem should be serialized
References SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializecolTextDelimiter()
Test whether colTextDelimiter should be serialized
virtual string SDC.ListFieldType.Serialize(System.Text.Encoding encoding)
Serializes current ListFieldType object into an XML string
string XML value
virtual string SDC.ListFieldType.Serialize()
Referenced by SDC.ListFieldType.SaveToFile.
virtual bool SDC.ListFieldType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ListFieldType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ListFieldType.SaveToFile.
virtual bool SDC.ListFieldType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.ListFieldType.SaveToFile(string fileName)
virtual void SDC.ListFieldType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.ListFieldType.ListFieldType()
ListFieldType class constructor
References SDC.ListFieldType._colTextDelimiter, SDC.ListFieldType._maxSelections, SDC.ListFieldType._minSelections, SDC.ListFieldType._numCols, SDC.ListFieldType._ordered, SDC.ListFieldType._storedCol, SDC.byte.
virtual bool SDC.ListFieldType.ShouldSerializeminSelections()
Test whether minSelections should be serialized
References SDC.ListFieldType._minSelections, SDC.ListFieldType._shouldSerializeminSelections.
virtual bool SDC.ListFieldType.ShouldSerializemaxSelections()
Test whether maxSelections should be serialized
References SDC.ListFieldType._maxSelections, SDC.ListFieldType._shouldSerializemaxSelections.
virtual bool SDC.ListFieldType.ShouldSerializeordered()
Test whether ordered should be serialized
References SDC.ListFieldType._ordered, SDC.ListFieldType._shouldSerializeordered.
virtual bool SDC.ListFieldType.ShouldSerializeListHeaderText()
Test whether ListHeaderText should be serialized
References SDC.ListFieldType._listHeaderText, SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeDefaultListItemDataType()
Test whether DefaultListItemDataType should be serialized
References SDC.ListFieldType._defaultListItemDataType, SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeDefaultCodeSystem()
Test whether DefaultCodeSystem should be serialized
References SDC.ListFieldType._defaultCodeSystem, SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializeItem()
Test whether Item should be serialized
References SDC.ListFieldType._item, SDC.null.
virtual bool SDC.ListFieldType.ShouldSerializecolTextDelimiter()
Test whether colTextDelimiter should be serialized
References SDC.ListFieldType.colTextDelimiter.
virtual string SDC.ListFieldType.Serialize()
Serializes current ListFieldType object into an XML string
string XML value
virtual bool SDC.ListFieldType.SaveToFile(string fileName, out Exception exception)
Serializes current ListFieldType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ListFieldType.SaveToFile.
virtual void SDC.ListFieldType.SaveToFile(string fileName)
References SDC.null, SDC.ListFieldType.Serialize.
virtual ListFieldType SDC.ListFieldType.Clone()
Create a clone of this ListFieldType object
static bool SDC.ListFieldType.Deserialize(string input, out ListFieldType obj, out System.Exception exception)
Deserializes workflow markup into an ListFieldType object
input string workflow markup to deserialize obj Output ListFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListFieldType.Deserialize, SDC.ListFieldType.LoadFromFile.
static bool SDC.ListFieldType.Deserialize(string input, out ListFieldType obj)
References SDC.null.
static new ListFieldType SDC.ListFieldType.Deserialize(string input)
References SDC.null.
static ListFieldType SDC.ListFieldType.Deserialize(System.IO.Stream s)
static bool SDC.ListFieldType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ListFieldType obj, out System.Exception exception)
Deserializes xml markup from file into an ListFieldType object
fileName string xml file to load and deserialize obj Output ListFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ListFieldType.LoadFromFile.
static bool SDC.ListFieldType.LoadFromFile(string fileName, out ListFieldType obj, out System.Exception exception)
static bool SDC.ListFieldType.LoadFromFile(string fileName, out ListFieldType obj)
References SDC.null.
static ListFieldType SDC.ListFieldType.LoadFromFile(string fileName)
static new ListFieldType SDC.ListFieldType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.ListFieldType.Deserialize(string input, out ListFieldType obj, out Exception exception)
Deserializes workflow markup into an ListFieldType object
input string workflow markup to deserialize obj Output ListFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListFieldType.Deserialize, SDC.null.
static bool SDC.ListFieldType.Deserialize(string input, out ListFieldType obj)
References SDC.ListFieldType.Deserialize, SDC.null.
static new ListFieldType SDC.ListFieldType.Deserialize(string input)
References SDC.null, SDC.ListFieldType.Serializer.
static ListFieldType SDC.ListFieldType.Deserialize(Stream s)
References SDC.ListFieldType.Serializer.
static bool SDC.ListFieldType.LoadFromFile(string fileName, out ListFieldType obj, out Exception exception)
Deserializes xml markup from file into an ListFieldType object
fileName string xml file to load and deserialize obj Output ListFieldType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ListFieldType.LoadFromFile, SDC.null.
static bool SDC.ListFieldType.LoadFromFile(string fileName, out ListFieldType obj)
References SDC.ListFieldType.LoadFromFile, SDC.null.
static new ListFieldType SDC.ListFieldType.LoadFromFile(string fileName)
References SDC.ListFieldType.Deserialize, SDC.null.