SDC::InputStr_ReturnBoolListType
bool SDC.InputStr_ReturnBoolListType._shouldSerializeuseDelimiter
Referenced by SDC.InputStr_ReturnBoolListType.ShouldSerializeuseDelimiter.
StringFunctionsStrType SDC.InputStr_ReturnBoolListType._inputStr
Referenced by SDC.InputStr_ReturnBoolListType.ShouldSerializeInputStr.
System.Nullable<bool> SDC.InputStr_ReturnBoolListType._useDelimiter
Referenced by SDC.InputStr_ReturnBoolListType.ShouldSerializeuseDelimiter.
InputStr_ReturnStrListTypeDelimiter SDC.InputStr_ReturnBoolListType._delimiter
XmlSerializer SDC.InputStr_ReturnBoolListType.serializer
virtual StringFunctionsStrType SDC.InputStr_ReturnBoolListType.InputStr
virtual bool SDC.InputStr_ReturnBoolListType.useDelimiter
If a delimiter is not used, then any white space will delimit the list items. The default delimiter is a space.
virtual bool SDC.InputStr_ReturnBoolListType.useDelimiterSpecified
virtual InputStr_ReturnStrListTypeDelimiter SDC.InputStr_ReturnBoolListType.delimiter
XmlSerializer SDC.InputStr_ReturnBoolListType.Serializer
Referenced by SDC.InputStr_ReturnBoolListType.Deserialize.
SDC.InputStr_ReturnBoolListType.InputStr_ReturnBoolListType()
InputStr_ReturnBoolListType class constructor
virtual bool SDC.InputStr_ReturnBoolListType.ShouldSerializeuseDelimiter()
Test whether useDelimiter should be serialized
References SDC.InputStr_ReturnBoolListType._shouldSerializeuseDelimiter, SDC.InputStr_ReturnBoolListType._useDelimiter.
virtual bool SDC.InputStr_ReturnBoolListType.ShouldSerializeInputStr()
Test whether InputStr should be serialized
References SDC.InputStr_ReturnBoolListType._inputStr, SDC.null.
virtual string SDC.InputStr_ReturnBoolListType.Serialize(System.Text.Encoding encoding)
Serializes current InputStr_ReturnBoolListType object into an XML string
string XML value
virtual string SDC.InputStr_ReturnBoolListType.Serialize()
Referenced by SDC.InputStr_ReturnBoolListType.SaveToFile.
virtual bool SDC.InputStr_ReturnBoolListType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current InputStr_ReturnBoolListType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.InputStr_ReturnBoolListType.SaveToFile.
virtual bool SDC.InputStr_ReturnBoolListType.SaveToFile(string fileName, out System.Exception exception)
References SDC.InputStr_ReturnBoolListType.SaveToFile.
virtual void SDC.InputStr_ReturnBoolListType.SaveToFile(string fileName)
References SDC.InputStr_ReturnBoolListType.SaveToFile.
virtual void SDC.InputStr_ReturnBoolListType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.InputStr_ReturnBoolListType.Serialize.
static bool SDC.InputStr_ReturnBoolListType.Deserialize(string input, out InputStr_ReturnBoolListType obj, out System.Exception exception)
Deserializes workflow markup into an InputStr_ReturnBoolListType object
input string workflow markup to deserialize obj Output InputStr_ReturnBoolListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnBoolListType.Deserialize, SDC.InputStr_ReturnBoolListType.LoadFromFile.
static bool SDC.InputStr_ReturnBoolListType.Deserialize(string input, out InputStr_ReturnBoolListType obj)
References SDC.InputStr_ReturnBoolListType.Deserialize, SDC.null.
static new InputStr_ReturnBoolListType SDC.InputStr_ReturnBoolListType.Deserialize(string input)
References SDC.null.
static InputStr_ReturnBoolListType SDC.InputStr_ReturnBoolListType.Deserialize(System.IO.Stream s)
References SDC.InputStr_ReturnBoolListType.Serializer.
static bool SDC.InputStr_ReturnBoolListType.LoadFromFile(string fileName, System.Text.Encoding encoding, out InputStr_ReturnBoolListType obj, out System.Exception exception)
Deserializes xml markup from file into an InputStr_ReturnBoolListType object
fileName string xml file to load and deserialize obj Output InputStr_ReturnBoolListType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.InputStr_ReturnBoolListType.LoadFromFile.
static bool SDC.InputStr_ReturnBoolListType.LoadFromFile(string fileName, out InputStr_ReturnBoolListType obj, out System.Exception exception)
References SDC.InputStr_ReturnBoolListType.LoadFromFile.
static bool SDC.InputStr_ReturnBoolListType.LoadFromFile(string fileName, out InputStr_ReturnBoolListType obj)
References SDC.InputStr_ReturnBoolListType.LoadFromFile, SDC.null.
static InputStr_ReturnBoolListType SDC.InputStr_ReturnBoolListType.LoadFromFile(string fileName)
References SDC.InputStr_ReturnBoolListType.LoadFromFile.
static new InputStr_ReturnBoolListType SDC.InputStr_ReturnBoolListType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.InputStr_ReturnBoolListType.Deserialize, SDC.null.