SDC::AssociatedFilesType
List<FileType> SDC.AssociatedFilesType._file
BindingList<FileType> SDC.AssociatedFilesType._file
ObjectChangeTracker SDC.AssociatedFilesType.changeTrackerField
static XmlSerializer SDC.AssociatedFilesType::serializer
virtual List<FileType> SDC.AssociatedFilesType.File
static XmlSerializer SDC.AssociatedFilesType::Serializer
Referenced by SDC.AssociatedFilesType.Deserialize.
virtual BindingList<FileType> SDC.AssociatedFilesType.File
ObjectChangeTracker SDC.AssociatedFilesType.ChangeTracker
SDC.AssociatedFilesType.AssociatedFilesType()
SDC.AssociatedFilesType.AssociatedFilesType(BaseType parentNode)
virtual bool SDC.AssociatedFilesType.ShouldSerializeFile()
Test whether File should be serialized
References SDC.null.
virtual string SDC.AssociatedFilesType.Serialize(System.Text.Encoding encoding)
Serializes current AssociatedFilesType object into an XML string
string XML value
virtual string SDC.AssociatedFilesType.Serialize()
Referenced by SDC.AssociatedFilesType.SaveToFile.
virtual bool SDC.AssociatedFilesType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current AssociatedFilesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.AssociatedFilesType.SaveToFile.
virtual bool SDC.AssociatedFilesType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.AssociatedFilesType.SaveToFile(string fileName)
virtual void SDC.AssociatedFilesType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.AssociatedFilesType.Serialize()
Serializes current AssociatedFilesType object into an XML string
string XML value
virtual bool SDC.AssociatedFilesType.SaveToFile(string fileName, out Exception exception)
Serializes current AssociatedFilesType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.AssociatedFilesType.SaveToFile.
virtual void SDC.AssociatedFilesType.SaveToFile(string fileName)
References SDC.null, SDC.AssociatedFilesType.Serialize.
virtual AssociatedFilesType SDC.AssociatedFilesType.Clone()
Create a clone of this AssociatedFilesType object
static bool SDC.AssociatedFilesType.Deserialize(string input, out AssociatedFilesType obj, out System.Exception exception)
Deserializes workflow markup into an AssociatedFilesType object
input string workflow markup to deserialize obj Output AssociatedFilesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AssociatedFilesType.Deserialize, SDC.AssociatedFilesType.LoadFromFile.
static bool SDC.AssociatedFilesType.Deserialize(string input, out AssociatedFilesType obj)
References SDC.null.
static new AssociatedFilesType SDC.AssociatedFilesType.Deserialize(string input)
References SDC.null.
static AssociatedFilesType SDC.AssociatedFilesType.Deserialize(System.IO.Stream s)
static bool SDC.AssociatedFilesType.LoadFromFile(string fileName, System.Text.Encoding encoding, out AssociatedFilesType obj, out System.Exception exception)
Deserializes xml markup from file into an AssociatedFilesType object
fileName string xml file to load and deserialize obj Output AssociatedFilesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.AssociatedFilesType.LoadFromFile.
static bool SDC.AssociatedFilesType.LoadFromFile(string fileName, out AssociatedFilesType obj, out System.Exception exception)
static bool SDC.AssociatedFilesType.LoadFromFile(string fileName, out AssociatedFilesType obj)
References SDC.null.
static AssociatedFilesType SDC.AssociatedFilesType.LoadFromFile(string fileName)
static new AssociatedFilesType SDC.AssociatedFilesType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.AssociatedFilesType.Deserialize(string input, out AssociatedFilesType obj, out Exception exception)
Deserializes workflow markup into an AssociatedFilesType object
input string workflow markup to deserialize obj Output AssociatedFilesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.AssociatedFilesType.Deserialize, SDC.null.
static bool SDC.AssociatedFilesType.Deserialize(string input, out AssociatedFilesType obj)
References SDC.AssociatedFilesType.Deserialize, SDC.null.
static new AssociatedFilesType SDC.AssociatedFilesType.Deserialize(string input)
References SDC.null, SDC.AssociatedFilesType.Serializer.
static AssociatedFilesType SDC.AssociatedFilesType.Deserialize(Stream s)
References SDC.AssociatedFilesType.Serializer.
static bool SDC.AssociatedFilesType.LoadFromFile(string fileName, out AssociatedFilesType obj, out Exception exception)
Deserializes xml markup from file into an AssociatedFilesType object
fileName string xml file to load and deserialize obj Output AssociatedFilesType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.AssociatedFilesType.LoadFromFile, SDC.null.
static bool SDC.AssociatedFilesType.LoadFromFile(string fileName, out AssociatedFilesType obj)
References SDC.AssociatedFilesType.LoadFromFile, SDC.null.
static new AssociatedFilesType SDC.AssociatedFilesType.LoadFromFile(string fileName)
References SDC.AssociatedFilesType.Deserialize, SDC.null.