SDC::double_DEtype
bool SDC.double_DEtype::_shouldSerializemaxExclusive
Referenced by SDC.double_DEtype.ShouldSerializemaxExclusive.
bool SDC.double_DEtype::_shouldSerializeminExclusive
Referenced by SDC.double_DEtype.ShouldSerializeminExclusive.
bool SDC.double_DEtype::_shouldSerializemaxInclusive
Referenced by SDC.double_DEtype.ShouldSerializemaxInclusive.
bool SDC.double_DEtype::_shouldSerializeminInclusive
Referenced by SDC.double_DEtype.ShouldSerializeminInclusive.
System Nullable< double > SDC.double_DEtype::_minInclusive
Referenced by SDC.double_DEtype.ShouldSerializeminInclusive.
System Nullable< double > SDC.double_DEtype::_maxInclusive
Referenced by SDC.double_DEtype.ShouldSerializemaxInclusive.
System Nullable< double > SDC.double_DEtype::_minExclusive
Referenced by SDC.double_DEtype.ShouldSerializeminExclusive.
System Nullable< double > SDC.double_DEtype::_maxExclusive
Referenced by SDC.double_DEtype.ShouldSerializemaxExclusive.
System Nullable< byte > SDC.double_DEtype::_fractionDigits
System Nullable< byte > SDC.double_DEtype::_totalDigits
ObjectChangeTracker SDC.double_DEtype.changeTrackerField
static XmlSerializer SDC.double_DEtype::serializer
double SDC.double_DEtype::minInclusive
bool SDC.double_DEtype::minInclusiveSpecified
double SDC.double_DEtype::maxInclusive
bool SDC.double_DEtype::maxInclusiveSpecified
double SDC.double_DEtype::minExclusive
bool SDC.double_DEtype::minExclusiveSpecified
double SDC.double_DEtype::maxExclusive
bool SDC.double_DEtype::maxExclusiveSpecified
byte SDC.double_DEtype::fractionDigits
bool SDC.double_DEtype::fractionDigitsSpecified
byte SDC.double_DEtype::totalDigits
bool SDC.double_DEtype::totalDigitsSpecified
static XmlSerializer SDC.double_DEtype::Serializer
Referenced by SDC.double_DEtype.Deserialize.
ObjectChangeTracker SDC.double_DEtype.ChangeTracker
SDC.double_DEtype.double_DEtype()
SDC.double_DEtype.double_DEtype(BaseType parentNode)
virtual bool SDC.double_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
virtual bool SDC.double_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
virtual bool SDC.double_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
virtual bool SDC.double_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
virtual string SDC.double_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current double_DEtype object into an XML string
string XML value
virtual string SDC.double_DEtype.Serialize()
Referenced by SDC.double_DEtype.SaveToFile.
virtual bool SDC.double_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current double_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.double_DEtype.SaveToFile.
virtual bool SDC.double_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.double_DEtype.SaveToFile(string fileName)
virtual void SDC.double_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.double_DEtype.ShouldSerializeminInclusive()
Test whether minInclusive should be serialized
References SDC.double_DEtype._minInclusive, SDC.double_DEtype._shouldSerializeminInclusive.
virtual bool SDC.double_DEtype.ShouldSerializemaxInclusive()
Test whether maxInclusive should be serialized
References SDC.double_DEtype._maxInclusive, SDC.double_DEtype._shouldSerializemaxInclusive.
virtual bool SDC.double_DEtype.ShouldSerializeminExclusive()
Test whether minExclusive should be serialized
References SDC.double_DEtype._minExclusive, SDC.double_DEtype._shouldSerializeminExclusive.
virtual bool SDC.double_DEtype.ShouldSerializemaxExclusive()
Test whether maxExclusive should be serialized
References SDC.double_DEtype._maxExclusive, SDC.double_DEtype._shouldSerializemaxExclusive.
virtual string SDC.double_DEtype.Serialize()
Serializes current double_DEtype object into an XML string
string XML value
virtual bool SDC.double_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current double_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.double_DEtype.SaveToFile.
virtual void SDC.double_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.double_DEtype.Serialize.
virtual double_DEtype SDC.double_DEtype.Clone()
Create a clone of this double_DEtype object
static bool SDC.double_DEtype.Deserialize(string input, out double_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an double_DEtype object
input string workflow markup to deserialize obj Output double_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.double_DEtype.Deserialize, SDC.double_DEtype.LoadFromFile.
static bool SDC.double_DEtype.Deserialize(string input, out double_DEtype obj)
References SDC.null.
static new double_DEtype SDC.double_DEtype.Deserialize(string input)
References SDC.null.
static double_DEtype SDC.double_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.double_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out double_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an double_DEtype object
fileName string xml file to load and deserialize obj Output double_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.double_DEtype.LoadFromFile.
static bool SDC.double_DEtype.LoadFromFile(string fileName, out double_DEtype obj, out System.Exception exception)
static bool SDC.double_DEtype.LoadFromFile(string fileName, out double_DEtype obj)
References SDC.null.
static double_DEtype SDC.double_DEtype.LoadFromFile(string fileName)
static new double_DEtype SDC.double_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.double_DEtype.Deserialize(string input, out double_DEtype obj, out Exception exception)
Deserializes workflow markup into an double_DEtype object
input string workflow markup to deserialize obj Output double_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.double_DEtype.Deserialize, SDC.null.
static bool SDC.double_DEtype.Deserialize(string input, out double_DEtype obj)
References SDC.double_DEtype.Deserialize, SDC.null.
static new double_DEtype SDC.double_DEtype.Deserialize(string input)
References SDC.null, SDC.double_DEtype.Serializer.
static double_DEtype SDC.double_DEtype.Deserialize(Stream s)
References SDC.double_DEtype.Serializer.
static bool SDC.double_DEtype.LoadFromFile(string fileName, out double_DEtype obj, out Exception exception)
Deserializes xml markup from file into an double_DEtype object
fileName string xml file to load and deserialize obj Output double_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.double_DEtype.LoadFromFile, SDC.null.
static bool SDC.double_DEtype.LoadFromFile(string fileName, out double_DEtype obj)
References SDC.double_DEtype.LoadFromFile, SDC.null.
static new double_DEtype SDC.double_DEtype.LoadFromFile(string fileName)
References SDC.double_DEtype.Deserialize, SDC.null.