SDC::hexBinary_Stype
string SDC.hexBinary_Stype::_hexBinaryStringVal
bool SDC.hexBinary_Stype::_shouldSerializelength
Referenced by SDC.hexBinary_Stype.ShouldSerializelength.
string SDC.hexBinary_Stype::_mimeType
System Nullable< long > SDC.hexBinary_Stype::_length
Referenced by SDC.hexBinary_Stype.ShouldSerializelength.
byte [] SDC.hexBinary_Stype._val
ObjectChangeTracker SDC.hexBinary_Stype.changeTrackerField
string SDC.hexBinary_Stype::valHex
string SDC.hexBinary_Stype::mimeType
TBD: Must be a valid MIME type - needs enumeration
Referenced by SDC.hexBinary_Stype.ShouldSerializemimeType.
long SDC.hexBinary_Stype::length
bool SDC.hexBinary_Stype::lengthSpecified
virtual byte [] SDC.hexBinary_Stype.val
static XmlSerializer SDC.hexBinary_Stype::Serializer
Referenced by SDC.hexBinary_Stype.Deserialize.
ObjectChangeTracker SDC.hexBinary_Stype.ChangeTracker
static XmlSerializer SDC.hexBinary_Stype::serializer
SDC.hexBinary_Stype.hexBinary_Stype()
SDC.hexBinary_Stype.hexBinary_Stype(BaseType parentNode)
virtual bool SDC.hexBinary_Stype.ShouldSerializelength()
Test whether length should be serialized
References SDC.hexBinary_Stype._length, SDC.hexBinary_Stype._shouldSerializelength.
virtual bool SDC.hexBinary_Stype.ShouldSerializemimeType()
Test whether mimeType should be serialized
References SDC.hexBinary_Stype.mimeType.
virtual string SDC.hexBinary_Stype.Serialize(System.Text.Encoding encoding)
Serializes current hexBinary_Stype object into an XML string
string XML value
virtual string SDC.hexBinary_Stype.Serialize()
Referenced by SDC.hexBinary_Stype.SaveToFile.
virtual bool SDC.hexBinary_Stype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current hexBinary_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.hexBinary_Stype.SaveToFile.
virtual bool SDC.hexBinary_Stype.SaveToFile(string fileName, out System.Exception exception)
References SDC.hexBinary_Stype.SaveToFile.
virtual void SDC.hexBinary_Stype.SaveToFile(string fileName)
References SDC.hexBinary_Stype.SaveToFile.
virtual void SDC.hexBinary_Stype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.hexBinary_Stype.Serialize.
virtual bool SDC.hexBinary_Stype.ShouldSerializelength()
Test whether length should be serialized
References SDC.hexBinary_Stype._length, SDC.hexBinary_Stype._shouldSerializelength.
virtual bool SDC.hexBinary_Stype.ShouldSerializemimeType()
Test whether mimeType should be serialized
References SDC.hexBinary_Stype.mimeType.
virtual string SDC.hexBinary_Stype.Serialize()
Serializes current hexBinary_Stype object into an XML string
string XML value
virtual bool SDC.hexBinary_Stype.SaveToFile(string fileName, out Exception exception)
Serializes current hexBinary_Stype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.hexBinary_Stype.SaveToFile.
virtual void SDC.hexBinary_Stype.SaveToFile(string fileName)
References SDC.null, SDC.hexBinary_Stype.Serialize.
virtual hexBinary_Stype SDC.hexBinary_Stype.Clone()
Create a clone of this hexBinary_Stype object
static bool SDC.hexBinary_Stype.Deserialize(string input, out hexBinary_Stype obj, out System.Exception exception)
Deserializes workflow markup into an hexBinary_Stype object
input string workflow markup to deserialize obj Output hexBinary_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.hexBinary_Stype.Deserialize, SDC.hexBinary_Stype.LoadFromFile.
static bool SDC.hexBinary_Stype.Deserialize(string input, out hexBinary_Stype obj)
References SDC.hexBinary_Stype.Deserialize, SDC.null.
static new hexBinary_Stype SDC.hexBinary_Stype.Deserialize(string input)
References SDC.null.
static hexBinary_Stype SDC.hexBinary_Stype.Deserialize(System.IO.Stream s)
References SDC.hexBinary_Stype.Serializer.
static bool SDC.hexBinary_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding, out hexBinary_Stype obj, out System.Exception exception)
Deserializes xml markup from file into an hexBinary_Stype object
fileName string xml file to load and deserialize obj Output hexBinary_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.hexBinary_Stype.LoadFromFile.
static bool SDC.hexBinary_Stype.LoadFromFile(string fileName, out hexBinary_Stype obj, out System.Exception exception)
References SDC.hexBinary_Stype.LoadFromFile.
static bool SDC.hexBinary_Stype.LoadFromFile(string fileName, out hexBinary_Stype obj)
References SDC.hexBinary_Stype.LoadFromFile, SDC.null.
static hexBinary_Stype SDC.hexBinary_Stype.LoadFromFile(string fileName)
References SDC.hexBinary_Stype.LoadFromFile.
static new hexBinary_Stype SDC.hexBinary_Stype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.hexBinary_Stype.Deserialize, SDC.null.
static bool SDC.hexBinary_Stype.Deserialize(string input, out hexBinary_Stype obj, out Exception exception)
Deserializes workflow markup into an hexBinary_Stype object
input string workflow markup to deserialize obj Output hexBinary_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.hexBinary_Stype.Deserialize, SDC.null.
static bool SDC.hexBinary_Stype.Deserialize(string input, out hexBinary_Stype obj)
References SDC.hexBinary_Stype.Deserialize, SDC.null.
static new hexBinary_Stype SDC.hexBinary_Stype.Deserialize(string input)
References SDC.null, SDC.hexBinary_Stype.Serializer.
static hexBinary_Stype SDC.hexBinary_Stype.Deserialize(Stream s)
References SDC.hexBinary_Stype.Serializer.
static bool SDC.hexBinary_Stype.LoadFromFile(string fileName, out hexBinary_Stype obj, out Exception exception)
Deserializes xml markup from file into an hexBinary_Stype object
fileName string xml file to load and deserialize obj Output hexBinary_Stype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.hexBinary_Stype.LoadFromFile, SDC.null.
static bool SDC.hexBinary_Stype.LoadFromFile(string fileName, out hexBinary_Stype obj)
References SDC.hexBinary_Stype.LoadFromFile, SDC.null.
static new hexBinary_Stype SDC.hexBinary_Stype.LoadFromFile(string fileName)
References SDC.hexBinary_Stype.Deserialize, SDC.null.