SDC::LookupEndPointType
bool SDC.LookupEndPointType::_shouldSerializeincludesHeaderRow
Referenced by SDC.LookupEndPointType.ShouldSerializeincludesHeaderRow.
List<CodingType> SDC.LookupEndPointType._responseValue
bool SDC.LookupEndPointType::_includesHeaderRow
Referenced by SDC.LookupEndPointType.LookupEndPointType, SDC.LookupEndPointType.ShouldSerializeincludesHeaderRow.
BindingList<CodingType> SDC.LookupEndPointType._responseValue
ObjectChangeTracker SDC.LookupEndPointType.changeTrackerField
static XmlSerializer SDC.LookupEndPointType::serializer
virtual List<CodingType> SDC.LookupEndPointType.ResponseValue
LookupEndPointType class constructor
The user's response to the lookup list. The response is recorded as a coding, terminology, classification, keyword, or local value. Multiple selections from the lookup list may be allowed.
Referenced by SDC.SDCTreeBuilder.AddCodingList, SDC.SDCTreeBuilderEcc.FillLookupEndpoint.
bool SDC.LookupEndPointType::includesHeaderRow
static XmlSerializer SDC.LookupEndPointType::Serializer
Referenced by SDC.LookupEndPointType.Deserialize.
virtual BindingList<CodingType> SDC.LookupEndPointType.ResponseValue
The user's response to the lookup list. The response is recorded as a coding, terminology, classification, keyword, or local value. Multiple selections from the lookup list may be allowed.
ObjectChangeTracker SDC.LookupEndPointType.ChangeTracker
SDC.LookupEndPointType.LookupEndPointType()
SDC.LookupEndPointType.LookupEndPointType(BaseType parentNode, bool fillData=true)
void SDC.LookupEndPointType.Fill_LookupEndPointType()
virtual bool SDC.LookupEndPointType.ShouldSerializeResponseValue()
Test whether ResponseValue should be serialized
References SDC.null.
virtual bool SDC.LookupEndPointType.ShouldSerializeincludesHeaderRow()
Test whether includesHeaderRow should be serialized
virtual string SDC.LookupEndPointType.Serialize(System.Text.Encoding encoding)
Serializes current LookupEndPointType object into an XML string
string XML value
virtual string SDC.LookupEndPointType.Serialize()
Referenced by SDC.LookupEndPointType.SaveToFile.
virtual bool SDC.LookupEndPointType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current LookupEndPointType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.LookupEndPointType.SaveToFile.
virtual bool SDC.LookupEndPointType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.LookupEndPointType.SaveToFile(string fileName)
virtual void SDC.LookupEndPointType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
SDC.LookupEndPointType.LookupEndPointType()
LookupEndPointType class constructor
References SDC.LookupEndPointType._includesHeaderRow.
virtual bool SDC.LookupEndPointType.ShouldSerializeincludesHeaderRow()
Test whether includesHeaderRow should be serialized
References SDC.LookupEndPointType._includesHeaderRow, SDC.LookupEndPointType._shouldSerializeincludesHeaderRow.
virtual string SDC.LookupEndPointType.Serialize()
Serializes current LookupEndPointType object into an XML string
string XML value
virtual bool SDC.LookupEndPointType.SaveToFile(string fileName, out Exception exception)
Serializes current LookupEndPointType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.LookupEndPointType.SaveToFile.
virtual void SDC.LookupEndPointType.SaveToFile(string fileName)
References SDC.null, SDC.LookupEndPointType.Serialize.
virtual LookupEndPointType SDC.LookupEndPointType.Clone()
Create a clone of this LookupEndPointType object
static bool SDC.LookupEndPointType.Deserialize(string input, out LookupEndPointType obj, out System.Exception exception)
Deserializes workflow markup into an LookupEndPointType object
input string workflow markup to deserialize obj Output LookupEndPointType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.LookupEndPointType.Deserialize, SDC.LookupEndPointType.LoadFromFile.
static bool SDC.LookupEndPointType.Deserialize(string input, out LookupEndPointType obj)
References SDC.null.
static new LookupEndPointType SDC.LookupEndPointType.Deserialize(string input)
References SDC.null.
static LookupEndPointType SDC.LookupEndPointType.Deserialize(System.IO.Stream s)
static bool SDC.LookupEndPointType.LoadFromFile(string fileName, System.Text.Encoding encoding, out LookupEndPointType obj, out System.Exception exception)
Deserializes xml markup from file into an LookupEndPointType object
fileName string xml file to load and deserialize obj Output LookupEndPointType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.LookupEndPointType.LoadFromFile.
static bool SDC.LookupEndPointType.LoadFromFile(string fileName, out LookupEndPointType obj, out System.Exception exception)
static bool SDC.LookupEndPointType.LoadFromFile(string fileName, out LookupEndPointType obj)
References SDC.null.
static LookupEndPointType SDC.LookupEndPointType.LoadFromFile(string fileName)
static new LookupEndPointType SDC.LookupEndPointType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.LookupEndPointType.Deserialize(string input, out LookupEndPointType obj, out Exception exception)
Deserializes workflow markup into an LookupEndPointType object
input string workflow markup to deserialize obj Output LookupEndPointType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.LookupEndPointType.Deserialize, SDC.null.
static bool SDC.LookupEndPointType.Deserialize(string input, out LookupEndPointType obj)
References SDC.LookupEndPointType.Deserialize, SDC.null.
static new LookupEndPointType SDC.LookupEndPointType.Deserialize(string input)
References SDC.null, SDC.LookupEndPointType.Serializer.
static LookupEndPointType SDC.LookupEndPointType.Deserialize(Stream s)
References SDC.LookupEndPointType.Serializer.
static bool SDC.LookupEndPointType.LoadFromFile(string fileName, out LookupEndPointType obj, out Exception exception)
Deserializes xml markup from file into an LookupEndPointType object
fileName string xml file to load and deserialize obj Output LookupEndPointType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.LookupEndPointType.LoadFromFile, SDC.null.
static bool SDC.LookupEndPointType.LoadFromFile(string fileName, out LookupEndPointType obj)
References SDC.LookupEndPointType.LoadFromFile, SDC.null.
static new LookupEndPointType SDC.LookupEndPointType.LoadFromFile(string fileName)
References SDC.LookupEndPointType.Deserialize, SDC.null.