SDC::ItemNameType
string SDC.ItemNameType::itemName
Referenced by SDC.ItemNameType.ShouldSerializeitemName.
static XmlSerializer SDC.ItemNameType::Serializer
Referenced by SDC.ItemNameType.Deserialize.
virtual bool SDC.ItemNameType.ShouldSerializeitemName()
Test whether itemName should be serialized
References SDC.ItemNameType.itemName.
virtual string SDC.ItemNameType.Serialize(System.Text.Encoding encoding)
Serializes current ItemNameType object into an XML string
string XML value
virtual string SDC.ItemNameType.Serialize()
Referenced by SDC.ItemNameType.SaveToFile.
virtual bool SDC.ItemNameType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current ItemNameType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.ItemNameType.SaveToFile.
virtual bool SDC.ItemNameType.SaveToFile(string fileName, out System.Exception exception)
References SDC.ItemNameType.SaveToFile.
virtual void SDC.ItemNameType.SaveToFile(string fileName)
References SDC.ItemNameType.SaveToFile.
virtual void SDC.ItemNameType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null, SDC.ItemNameType.Serialize.
static bool SDC.ItemNameType.Deserialize(string input, out ItemNameType obj, out System.Exception exception)
Deserializes workflow markup into an ItemNameType object
input string workflow markup to deserialize obj Output ItemNameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ItemNameType.Deserialize, SDC.ItemNameType.LoadFromFile.
static bool SDC.ItemNameType.Deserialize(string input, out ItemNameType obj)
References SDC.ItemNameType.Deserialize, SDC.null.
static new ItemNameType SDC.ItemNameType.Deserialize(string input)
References SDC.null.
static ItemNameType SDC.ItemNameType.Deserialize(System.IO.Stream s)
References SDC.ItemNameType.Serializer.
static bool SDC.ItemNameType.LoadFromFile(string fileName, System.Text.Encoding encoding, out ItemNameType obj, out System.Exception exception)
Deserializes xml markup from file into an ItemNameType object
fileName string xml file to load and deserialize obj Output ItemNameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.ItemNameType.LoadFromFile.
static bool SDC.ItemNameType.LoadFromFile(string fileName, out ItemNameType obj, out System.Exception exception)
References SDC.ItemNameType.LoadFromFile.
static bool SDC.ItemNameType.LoadFromFile(string fileName, out ItemNameType obj)
References SDC.ItemNameType.LoadFromFile, SDC.null.
static ItemNameType SDC.ItemNameType.LoadFromFile(string fileName)
References SDC.ItemNameType.LoadFromFile.
static new ItemNameType SDC.ItemNameType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.ItemNameType.Deserialize, SDC.null.
string SDC.ItemNameType::_itemName
ObjectChangeTracker SDC.ItemNameType.changeTrackerField
static XmlSerializer SDC.ItemNameType::serializer
ObjectChangeTracker SDC.ItemNameType.ChangeTracker
SDC.ItemNameType.ItemNameType()
SDC.ItemNameType.ItemNameType(BaseType parentNode)
SDC.ItemNameType.ItemNameType()
virtual bool SDC.ItemNameType.ShouldSerializeitemName()
Test whether itemName should be serialized
References SDC.ItemNameType.itemName.
virtual string SDC.ItemNameType.Serialize()
Serializes current ItemNameType object into an XML string
string XML value
virtual bool SDC.ItemNameType.SaveToFile(string fileName, out Exception exception)
Serializes current ItemNameType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.ItemNameType.SaveToFile.
virtual void SDC.ItemNameType.SaveToFile(string fileName)
References SDC.null, SDC.ItemNameType.Serialize.
virtual ItemNameType SDC.ItemNameType.Clone()
Create a clone of this ItemNameType object
static bool SDC.ItemNameType.Deserialize(string input, out ItemNameType obj, out Exception exception)
Deserializes workflow markup into an ItemNameType object
input string workflow markup to deserialize obj Output ItemNameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ItemNameType.Deserialize, SDC.null.
static bool SDC.ItemNameType.Deserialize(string input, out ItemNameType obj)
References SDC.ItemNameType.Deserialize, SDC.null.
static new ItemNameType SDC.ItemNameType.Deserialize(string input)
References SDC.null, SDC.ItemNameType.Serializer.
static ItemNameType SDC.ItemNameType.Deserialize(Stream s)
References SDC.ItemNameType.Serializer.
static bool SDC.ItemNameType.LoadFromFile(string fileName, out ItemNameType obj, out Exception exception)
Deserializes xml markup from file into an ItemNameType object
fileName string xml file to load and deserialize obj Output ItemNameType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.ItemNameType.LoadFromFile, SDC.null.
static bool SDC.ItemNameType.LoadFromFile(string fileName, out ItemNameType obj)
References SDC.ItemNameType.LoadFromFile, SDC.null.
static new ItemNameType SDC.ItemNameType.LoadFromFile(string fileName)
References SDC.ItemNameType.Deserialize, SDC.null.