SDC::OnEventType
string SDC.OnEventType::_eventName
ObjectChangeTracker SDC.OnEventType.changeTrackerField
static XmlSerializer SDC.OnEventType::serializer
string SDC.OnEventType::eventName
Referenced by SDC.OnEventType.ShouldSerializeeventName.
static XmlSerializer SDC.OnEventType::Serializer
Referenced by SDC.OnEventType.Deserialize.
ObjectChangeTracker SDC.OnEventType.ChangeTracker
SDC.OnEventType.OnEventType(BaseType parentNode)
SDC.OnEventType.OnEventType()
virtual bool SDC.OnEventType.ShouldSerializeeventName()
Test whether eventName should be serialized
virtual string SDC.OnEventType.Serialize(System.Text.Encoding encoding)
Serializes current OnEventType object into an XML string
string XML value
virtual string SDC.OnEventType.Serialize()
Referenced by SDC.OnEventType.SaveToFile.
virtual bool SDC.OnEventType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current OnEventType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.OnEventType.SaveToFile.
virtual bool SDC.OnEventType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.OnEventType.SaveToFile(string fileName)
virtual void SDC.OnEventType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.OnEventType.ShouldSerializeeventName()
Test whether eventName should be serialized
References SDC.OnEventType.eventName.
virtual string SDC.OnEventType.Serialize()
Serializes current OnEventType object into an XML string
string XML value
virtual bool SDC.OnEventType.SaveToFile(string fileName, out Exception exception)
Serializes current OnEventType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.OnEventType.SaveToFile.
virtual void SDC.OnEventType.SaveToFile(string fileName)
References SDC.null, SDC.OnEventType.Serialize.
virtual OnEventType SDC.OnEventType.Clone()
Create a clone of this OnEventType object
SDC.OnEventType.OnEventType()
static bool SDC.OnEventType.Deserialize(string input, out OnEventType obj, out System.Exception exception)
Deserializes workflow markup into an OnEventType object
input string workflow markup to deserialize obj Output OnEventType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.OnEventType.Deserialize, SDC.OnEventType.LoadFromFile.
static bool SDC.OnEventType.Deserialize(string input, out OnEventType obj)
References SDC.null.
static new OnEventType SDC.OnEventType.Deserialize(string input)
References SDC.null.
static OnEventType SDC.OnEventType.Deserialize(System.IO.Stream s)
static bool SDC.OnEventType.LoadFromFile(string fileName, System.Text.Encoding encoding, out OnEventType obj, out System.Exception exception)
Deserializes xml markup from file into an OnEventType object
fileName string xml file to load and deserialize obj Output OnEventType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.OnEventType.LoadFromFile.
static bool SDC.OnEventType.LoadFromFile(string fileName, out OnEventType obj, out System.Exception exception)
static bool SDC.OnEventType.LoadFromFile(string fileName, out OnEventType obj)
References SDC.null.
static OnEventType SDC.OnEventType.LoadFromFile(string fileName)
static new OnEventType SDC.OnEventType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.OnEventType.Deserialize(string input, out OnEventType obj, out Exception exception)
Deserializes workflow markup into an OnEventType object
input string workflow markup to deserialize obj Output OnEventType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.OnEventType.Deserialize, SDC.null.
static bool SDC.OnEventType.Deserialize(string input, out OnEventType obj)
References SDC.OnEventType.Deserialize, SDC.null.
static new OnEventType SDC.OnEventType.Deserialize(string input)
References SDC.null, SDC.OnEventType.Serializer.
static OnEventType SDC.OnEventType.Deserialize(Stream s)
References SDC.OnEventType.Serializer.
static bool SDC.OnEventType.LoadFromFile(string fileName, out OnEventType obj, out Exception exception)
Deserializes xml markup from file into an OnEventType object
fileName string xml file to load and deserialize obj Output OnEventType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.OnEventType.LoadFromFile, SDC.null.
static bool SDC.OnEventType.LoadFromFile(string fileName, out OnEventType obj)
References SDC.OnEventType.LoadFromFile, SDC.null.
static new OnEventType SDC.OnEventType.LoadFromFile(string fileName)
References SDC.OnEventType.Deserialize, SDC.null.