SDC::LinkType
RichTextType SDC.LinkType::_linkText
Referenced by SDC.LinkType.ShouldSerializeLinkText.
anyURI_Stype SDC.LinkType::_linkURI
Referenced by SDC.LinkType.ShouldSerializeLinkURI.
BindingList<RichTextType> SDC.LinkType._description
ObjectChangeTracker SDC.LinkType.changeTrackerField
static XmlSerializer SDC.LinkType::serializer
RichTextType SDC.LinkType::LinkText
A description of the URI link, usually for display purposes.
Referenced by SDC.SDCTreeBuilderEcc.FillLinkText.
anyURI_Stype SDC.LinkType::LinkURI
Link to external information.
static XmlSerializer SDC.LinkType::Serializer
Referenced by SDC.LinkType.Deserialize.
virtual BindingList<RichTextType> SDC.LinkType.Description
Alternative description(s) of the URI link, not usually for display purposes, but available for special purposes.
ObjectChangeTracker SDC.LinkType.ChangeTracker
SDC.LinkType.LinkType()
SDC.LinkType.LinkType(BaseType parentNode, bool fillData=true)
virtual bool SDC.LinkType.ShouldSerializeLinkText()
Test whether LinkText should be serialized
References SDC.null.
virtual bool SDC.LinkType.ShouldSerializeLinkURI()
Test whether LinkURI should be serialized
References SDC.null.
virtual string SDC.LinkType.Serialize(System.Text.Encoding encoding)
Serializes current LinkType object into an XML string
string XML value
virtual string SDC.LinkType.Serialize()
Referenced by SDC.LinkType.SaveToFile.
virtual bool SDC.LinkType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current LinkType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.LinkType.SaveToFile.
virtual bool SDC.LinkType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.LinkType.SaveToFile(string fileName)
virtual void SDC.LinkType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.LinkType.ShouldSerializeLinkText()
Test whether LinkText should be serialized
References SDC.LinkType._linkText, SDC.null.
virtual bool SDC.LinkType.ShouldSerializeLinkURI()
Test whether LinkURI should be serialized
References SDC.LinkType._linkURI, SDC.null.
virtual string SDC.LinkType.Serialize()
Serializes current LinkType object into an XML string
string XML value
virtual bool SDC.LinkType.SaveToFile(string fileName, out Exception exception)
Serializes current LinkType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.LinkType.SaveToFile.
virtual void SDC.LinkType.SaveToFile(string fileName)
References SDC.null, SDC.LinkType.Serialize.
virtual LinkType SDC.LinkType.Clone()
Create a clone of this LinkType object
static bool SDC.LinkType.Deserialize(string input, out LinkType obj, out System.Exception exception)
Deserializes workflow markup into an LinkType object
input string workflow markup to deserialize obj Output LinkType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.LinkType.Deserialize, SDC.LinkType.LoadFromFile.
static bool SDC.LinkType.Deserialize(string input, out LinkType obj)
References SDC.null.
static new LinkType SDC.LinkType.Deserialize(string input)
References SDC.null.
static LinkType SDC.LinkType.Deserialize(System.IO.Stream s)
static bool SDC.LinkType.LoadFromFile(string fileName, System.Text.Encoding encoding, out LinkType obj, out System.Exception exception)
Deserializes xml markup from file into an LinkType object
fileName string xml file to load and deserialize obj Output LinkType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.LinkType.LoadFromFile.
static bool SDC.LinkType.LoadFromFile(string fileName, out LinkType obj, out System.Exception exception)
static bool SDC.LinkType.LoadFromFile(string fileName, out LinkType obj)
References SDC.null.
static LinkType SDC.LinkType.LoadFromFile(string fileName)
static new LinkType SDC.LinkType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.LinkType.Deserialize(string input, out LinkType obj, out Exception exception)
Deserializes workflow markup into an LinkType object
input string workflow markup to deserialize obj Output LinkType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.LinkType.Deserialize, SDC.null.
static bool SDC.LinkType.Deserialize(string input, out LinkType obj)
References SDC.LinkType.Deserialize, SDC.null.
static new LinkType SDC.LinkType.Deserialize(string input)
References SDC.null, SDC.LinkType.Serializer.
static LinkType SDC.LinkType.Deserialize(Stream s)
References SDC.LinkType.Serializer.
static bool SDC.LinkType.LoadFromFile(string fileName, out LinkType obj, out Exception exception)
Deserializes xml markup from file into an LinkType object
fileName string xml file to load and deserialize obj Output LinkType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.LinkType.LoadFromFile, SDC.null.
static bool SDC.LinkType.LoadFromFile(string fileName, out LinkType obj)
References SDC.LinkType.LoadFromFile, SDC.null.
static new LinkType SDC.LinkType.LoadFromFile(string fileName)
References SDC.LinkType.Deserialize, SDC.null.