SDC::FileHashType
string SDC.FileHashType::_hashType
ObjectChangeTracker SDC.FileHashType.changeTrackerField
static XmlSerializer SDC.FileHashType::serializer
string SDC.FileHashType::hashType
Referenced by SDC.FileHashType.ShouldSerializehashType.
static XmlSerializer SDC.FileHashType::Serializer
Referenced by SDC.FileHashType.Deserialize.
ObjectChangeTracker SDC.FileHashType.ChangeTracker
SDC.FileHashType.FileHashType()
SDC.FileHashType.FileHashType(BaseType parentNode)
virtual bool SDC.FileHashType.ShouldSerializehashType()
Test whether hashType should be serialized
virtual string SDC.FileHashType.Serialize(System.Text.Encoding encoding)
Serializes current FileHashType object into an XML string
string XML value
virtual string SDC.FileHashType.Serialize()
Referenced by SDC.FileHashType.SaveToFile.
virtual bool SDC.FileHashType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current FileHashType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.FileHashType.SaveToFile.
virtual bool SDC.FileHashType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.FileHashType.SaveToFile(string fileName)
virtual void SDC.FileHashType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.FileHashType.ShouldSerializehashType()
Test whether hashType should be serialized
References SDC.FileHashType.hashType.
virtual string SDC.FileHashType.Serialize()
Serializes current FileHashType object into an XML string
string XML value
virtual bool SDC.FileHashType.SaveToFile(string fileName, out Exception exception)
Serializes current FileHashType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.FileHashType.SaveToFile.
virtual void SDC.FileHashType.SaveToFile(string fileName)
References SDC.null, SDC.FileHashType.Serialize.
virtual FileHashType SDC.FileHashType.Clone()
Create a clone of this FileHashType object
static bool SDC.FileHashType.Deserialize(string input, out FileHashType obj, out System.Exception exception)
Deserializes workflow markup into an FileHashType object
input string workflow markup to deserialize obj Output FileHashType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.FileHashType.Deserialize, SDC.FileHashType.LoadFromFile.
static bool SDC.FileHashType.Deserialize(string input, out FileHashType obj)
References SDC.null.
static new FileHashType SDC.FileHashType.Deserialize(string input)
References SDC.null.
static FileHashType SDC.FileHashType.Deserialize(System.IO.Stream s)
static bool SDC.FileHashType.LoadFromFile(string fileName, System.Text.Encoding encoding, out FileHashType obj, out System.Exception exception)
Deserializes xml markup from file into an FileHashType object
fileName string xml file to load and deserialize obj Output FileHashType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.FileHashType.LoadFromFile.
static bool SDC.FileHashType.LoadFromFile(string fileName, out FileHashType obj, out System.Exception exception)
static bool SDC.FileHashType.LoadFromFile(string fileName, out FileHashType obj)
References SDC.null.
static FileHashType SDC.FileHashType.LoadFromFile(string fileName)
static new FileHashType SDC.FileHashType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.FileHashType.Deserialize(string input, out FileHashType obj, out Exception exception)
Deserializes workflow markup into an FileHashType object
input string workflow markup to deserialize obj Output FileHashType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.FileHashType.Deserialize, SDC.null.
static bool SDC.FileHashType.Deserialize(string input, out FileHashType obj)
References SDC.FileHashType.Deserialize, SDC.null.
static new FileHashType SDC.FileHashType.Deserialize(string input)
References SDC.null, SDC.FileHashType.Serializer.
static FileHashType SDC.FileHashType.Deserialize(Stream s)
References SDC.FileHashType.Serializer.
static bool SDC.FileHashType.LoadFromFile(string fileName, out FileHashType obj, out Exception exception)
Deserializes xml markup from file into an FileHashType object
fileName string xml file to load and deserialize obj Output FileHashType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.FileHashType.LoadFromFile, SDC.null.
static bool SDC.FileHashType.LoadFromFile(string fileName, out FileHashType obj)
References SDC.FileHashType.LoadFromFile, SDC.null.
static new FileHashType SDC.FileHashType.LoadFromFile(string fileName)
References SDC.FileHashType.Deserialize, SDC.null.