SDC::CountryCodeType
byte SDC.CountryCodeType::_val
ObjectChangeTracker SDC.CountryCodeType.changeTrackerField
static XmlSerializer SDC.CountryCodeType::serializer
byte SDC.CountryCodeType::val
static XmlSerializer SDC.CountryCodeType::Serializer
Referenced by SDC.CountryCodeType.Deserialize.
ObjectChangeTracker SDC.CountryCodeType.ChangeTracker
SDC.CountryCodeType.CountryCodeType()
SDC.CountryCodeType.CountryCodeType(BaseType parentNode)
virtual string SDC.CountryCodeType.Serialize(System.Text.Encoding encoding)
Serializes current CountryCodeType object into an XML string
string XML value
virtual string SDC.CountryCodeType.Serialize()
Referenced by SDC.CountryCodeType.SaveToFile.
virtual bool SDC.CountryCodeType.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current CountryCodeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.CountryCodeType.SaveToFile.
virtual bool SDC.CountryCodeType.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.CountryCodeType.SaveToFile(string fileName)
virtual void SDC.CountryCodeType.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual string SDC.CountryCodeType.Serialize()
Serializes current CountryCodeType object into an XML string
string XML value
virtual bool SDC.CountryCodeType.SaveToFile(string fileName, out Exception exception)
Serializes current CountryCodeType object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.CountryCodeType.SaveToFile.
virtual void SDC.CountryCodeType.SaveToFile(string fileName)
References SDC.null, SDC.CountryCodeType.Serialize.
virtual CountryCodeType SDC.CountryCodeType.Clone()
Create a clone of this CountryCodeType object
static bool SDC.CountryCodeType.Deserialize(string input, out CountryCodeType obj, out System.Exception exception)
Deserializes workflow markup into an CountryCodeType object
input string workflow markup to deserialize obj Output CountryCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CountryCodeType.Deserialize, SDC.CountryCodeType.LoadFromFile.
static bool SDC.CountryCodeType.Deserialize(string input, out CountryCodeType obj)
References SDC.null.
static new CountryCodeType SDC.CountryCodeType.Deserialize(string input)
References SDC.null.
static CountryCodeType SDC.CountryCodeType.Deserialize(System.IO.Stream s)
static bool SDC.CountryCodeType.LoadFromFile(string fileName, System.Text.Encoding encoding, out CountryCodeType obj, out System.Exception exception)
Deserializes xml markup from file into an CountryCodeType object
fileName string xml file to load and deserialize obj Output CountryCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.CountryCodeType.LoadFromFile.
static bool SDC.CountryCodeType.LoadFromFile(string fileName, out CountryCodeType obj, out System.Exception exception)
static bool SDC.CountryCodeType.LoadFromFile(string fileName, out CountryCodeType obj)
References SDC.null.
static CountryCodeType SDC.CountryCodeType.LoadFromFile(string fileName)
static new CountryCodeType SDC.CountryCodeType.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.CountryCodeType.Deserialize(string input, out CountryCodeType obj, out Exception exception)
Deserializes workflow markup into an CountryCodeType object
input string workflow markup to deserialize obj Output CountryCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CountryCodeType.Deserialize, SDC.null.
static bool SDC.CountryCodeType.Deserialize(string input, out CountryCodeType obj)
References SDC.CountryCodeType.Deserialize, SDC.null.
static new CountryCodeType SDC.CountryCodeType.Deserialize(string input)
References SDC.null, SDC.CountryCodeType.Serializer.
static CountryCodeType SDC.CountryCodeType.Deserialize(Stream s)
References SDC.CountryCodeType.Serializer.
static bool SDC.CountryCodeType.LoadFromFile(string fileName, out CountryCodeType obj, out Exception exception)
Deserializes xml markup from file into an CountryCodeType object
fileName string xml file to load and deserialize obj Output CountryCodeType object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.CountryCodeType.LoadFromFile, SDC.null.
static bool SDC.CountryCodeType.LoadFromFile(string fileName, out CountryCodeType obj)
References SDC.CountryCodeType.LoadFromFile, SDC.null.
static new CountryCodeType SDC.CountryCodeType.LoadFromFile(string fileName)
References SDC.CountryCodeType.Deserialize, SDC.null.