SDC::string_DEtype
bool SDC.string_DEtype::_shouldSerializemaxLength
Referenced by SDC.string_DEtype.ShouldSerializemaxLength.
bool SDC.string_DEtype::_shouldSerializeminLength
Referenced by SDC.string_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.string_DEtype::_minLength
Referenced by SDC.string_DEtype.ShouldSerializeminLength.
System Nullable< long > SDC.string_DEtype::_maxLength
Referenced by SDC.string_DEtype.ShouldSerializemaxLength.
string SDC.string_DEtype::_pattern
string SDC.string_DEtype::_mask
ObjectChangeTracker SDC.string_DEtype.changeTrackerField
static XmlSerializer SDC.string_DEtype::serializer
long SDC.string_DEtype::minLength
bool SDC.string_DEtype::minLengthSpecified
long SDC.string_DEtype::maxLength
bool SDC.string_DEtype::maxLengthSpecified
string SDC.string_DEtype::pattern
Referenced by SDC.string_DEtype.ShouldSerializepattern.
string SDC.string_DEtype::mask
Referenced by SDC.string_DEtype.ShouldSerializemask.
static XmlSerializer SDC.string_DEtype::Serializer
Referenced by SDC.string_DEtype.Deserialize.
ObjectChangeTracker SDC.string_DEtype.ChangeTracker
SDC.string_DEtype.string_DEtype()
SDC.string_DEtype.string_DEtype(BaseType parentNode)
virtual bool SDC.string_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
virtual bool SDC.string_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
virtual bool SDC.string_DEtype.ShouldSerializepattern()
Test whether pattern should be serialized
virtual bool SDC.string_DEtype.ShouldSerializemask()
Test whether mask should be serialized
virtual string SDC.string_DEtype.Serialize(System.Text.Encoding encoding)
Serializes current string_DEtype object into an XML string
string XML value
virtual string SDC.string_DEtype.Serialize()
Referenced by SDC.string_DEtype.SaveToFile.
virtual bool SDC.string_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
Serializes current string_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null.
Referenced by SDC.string_DEtype.SaveToFile.
virtual bool SDC.string_DEtype.SaveToFile(string fileName, out System.Exception exception)
virtual void SDC.string_DEtype.SaveToFile(string fileName)
virtual void SDC.string_DEtype.SaveToFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
virtual bool SDC.string_DEtype.ShouldSerializeminLength()
Test whether minLength should be serialized
References SDC.string_DEtype._minLength, SDC.string_DEtype._shouldSerializeminLength.
virtual bool SDC.string_DEtype.ShouldSerializemaxLength()
Test whether maxLength should be serialized
References SDC.string_DEtype._maxLength, SDC.string_DEtype._shouldSerializemaxLength.
virtual bool SDC.string_DEtype.ShouldSerializepattern()
Test whether pattern should be serialized
References SDC.string_DEtype.pattern.
virtual bool SDC.string_DEtype.ShouldSerializemask()
Test whether mask should be serialized
References SDC.string_DEtype.mask.
virtual string SDC.string_DEtype.Serialize()
Serializes current string_DEtype object into an XML string
string XML value
virtual bool SDC.string_DEtype.SaveToFile(string fileName, out Exception exception)
Serializes current string_DEtype object into file
fileName full path of outupt xml file exception output Exception value if failed true if can serialize and save into file; otherwise, false
References SDC.e, SDC.null, SDC.string_DEtype.SaveToFile.
virtual void SDC.string_DEtype.SaveToFile(string fileName)
References SDC.null, SDC.string_DEtype.Serialize.
virtual string_DEtype SDC.string_DEtype.Clone()
Create a clone of this string_DEtype object
static bool SDC.string_DEtype.Deserialize(string input, out string_DEtype obj, out System.Exception exception)
Deserializes workflow markup into an string_DEtype object
input string workflow markup to deserialize obj Output string_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.string_DEtype.Deserialize, SDC.string_DEtype.LoadFromFile.
static bool SDC.string_DEtype.Deserialize(string input, out string_DEtype obj)
References SDC.null.
static new string_DEtype SDC.string_DEtype.Deserialize(string input)
References SDC.null.
static string_DEtype SDC.string_DEtype.Deserialize(System.IO.Stream s)
static bool SDC.string_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding, out string_DEtype obj, out System.Exception exception)
Deserializes xml markup from file into an string_DEtype object
fileName string xml file to load and deserialize obj Output string_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.null.
Referenced by SDC.string_DEtype.LoadFromFile.
static bool SDC.string_DEtype.LoadFromFile(string fileName, out string_DEtype obj, out System.Exception exception)
static bool SDC.string_DEtype.LoadFromFile(string fileName, out string_DEtype obj)
References SDC.null.
static string_DEtype SDC.string_DEtype.LoadFromFile(string fileName)
static new string_DEtype SDC.string_DEtype.LoadFromFile(string fileName, System.Text.Encoding encoding)
References SDC.null.
static bool SDC.string_DEtype.Deserialize(string input, out string_DEtype obj, out Exception exception)
Deserializes workflow markup into an string_DEtype object
input string workflow markup to deserialize obj Output string_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.string_DEtype.Deserialize, SDC.null.
static bool SDC.string_DEtype.Deserialize(string input, out string_DEtype obj)
References SDC.string_DEtype.Deserialize, SDC.null.
static new string_DEtype SDC.string_DEtype.Deserialize(string input)
References SDC.null, SDC.string_DEtype.Serializer.
static string_DEtype SDC.string_DEtype.Deserialize(Stream s)
References SDC.string_DEtype.Serializer.
static bool SDC.string_DEtype.LoadFromFile(string fileName, out string_DEtype obj, out Exception exception)
Deserializes xml markup from file into an string_DEtype object
fileName string xml file to load and deserialize obj Output string_DEtype object exception output Exception value if deserialize failed true if this Serializer can deserialize the object; otherwise, false
References SDC.string_DEtype.LoadFromFile, SDC.null.
static bool SDC.string_DEtype.LoadFromFile(string fileName, out string_DEtype obj)
References SDC.string_DEtype.LoadFromFile, SDC.null.
static new string_DEtype SDC.string_DEtype.LoadFromFile(string fileName)
References SDC.string_DEtype.Deserialize, SDC.null.