// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.Collections.ObjectModel;
using System.Reflection;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://healthIT.gov/sdc")]
[DataContractAttribute(Name="ActValidateFormType", Namespace="http://healthIT.gov/sdc")]
public partial class ActValidateFormType : ExtensionBaseType
{
    
    private bool _shouldSerializevalidateRules;
    
    private bool _shouldSerializevalidateDataTypes;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private WebServiceType _validationWebService;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private bool _validateDataTypes;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private bool _validateRules;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string _validationType;
    
    private static XmlSerializer serializer;
    
    private ObjectChangeTracker changeTrackerField;
    
    /// <summary>
    /// ActValidateFormType class constructor
    /// </summary>
    public ActValidateFormType()
    {
        _validateDataTypes = false;
        _validateRules = false;
    }
    
    [XmlElementAttribute(Order=0)]
    [DataMemberAttribute(Order=0)]
    public virtual WebServiceType ValidationWebService
    {
        get
        {
            return _validationWebService;
        }
        set
        {
            if ((_validationWebService == value))
            {
                return;
            }
            if (((_validationWebService == null) 
                        || (_validationWebService.Equals(value) != true)))
            {
                _validationWebService = value;
                OnPropertyChanged("ValidationWebService", value);
            }
        }
    }
    
    [XmlAttribute]
    [System.ComponentModel.DefaultValueAttribute(false)]
    [DataMember]
    public virtual bool validateDataTypes
    {
        get
        {
            return _validateDataTypes;
        }
        set
        {
            if ((_validateDataTypes.Equals(value) != true))
            {
                _validateDataTypes = value;
                OnPropertyChanged("validateDataTypes", value);
            }
            _shouldSerializevalidateDataTypes = true;
        }
    }
    
    [XmlAttribute]
    [System.ComponentModel.DefaultValueAttribute(false)]
    [DataMember]
    public virtual bool validateRules
    {
        get
        {
            return _validateRules;
        }
        set
        {
            if ((_validateRules.Equals(value) != true))
            {
                _validateRules = value;
                OnPropertyChanged("validateRules", value);
            }
            _shouldSerializevalidateRules = true;
        }
    }
    
    [XmlAttribute]
    [DataMember]
    public virtual string validationType
    {
        get
        {
            return _validationType;
        }
        set
        {
            if ((_validationType == value))
            {
                return;
            }
            if (((_validationType == null) 
                        || (_validationType.Equals(value) != true)))
            {
                _validationType = value;
                OnPropertyChanged("validationType", value);
            }
        }
    }
    
    private static XmlSerializer Serializer
    {
        get
        {
            if ((serializer == null))
            {
                serializer = new XmlSerializerFactory().CreateSerializer(typeof(ActValidateFormType));
            }
            return serializer;
        }
    }
    
    [XmlIgnore()]
    public ObjectChangeTracker ChangeTracker
    {
        get
        {
            if ((changeTrackerField == null))
            {
                changeTrackerField = new ObjectChangeTracker(this);
            }
            return changeTrackerField;
        }
    }
    
    /// <summary>
    /// Test whether validateDataTypes should be serialized
    /// </summary>
    public virtual bool ShouldSerializevalidateDataTypes()
    {
        if (_shouldSerializevalidateDataTypes)
        {
            return true;
        }
        return (_validateDataTypes != default(bool));
    }
    
    /// <summary>
    /// Test whether validateRules should be serialized
    /// </summary>
    public virtual bool ShouldSerializevalidateRules()
    {
        if (_shouldSerializevalidateRules)
        {
            return true;
        }
        return (_validateRules != default(bool));
    }
    
    /// <summary>
    /// Test whether ValidationWebService should be serialized
    /// </summary>
    public virtual bool ShouldSerializeValidationWebService()
    {
        return (_validationWebService != null);
    }
    
    /// <summary>
    /// Test whether validationType should be serialized
    /// </summary>
    public virtual bool ShouldSerializevalidationType()
    {
        return !string.IsNullOrEmpty(validationType);
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current ActValidateFormType object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public virtual string Serialize()
    {
        StreamReader streamReader = null;
        MemoryStream memoryStream = null;
        try
        {
            memoryStream = new MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Indent = true;
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, SeekOrigin.Begin);
            streamReader = new StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes workflow markup into an ActValidateFormType object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output ActValidateFormType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out ActValidateFormType obj, out Exception exception)
    {
        exception = null;
        obj = default(ActValidateFormType);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out ActValidateFormType obj)
    {
        Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public new static ActValidateFormType Deserialize(string input)
    {
        StringReader stringReader = null;
        try
        {
            stringReader = new StringReader(input);
            return ((ActValidateFormType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }
    
    public static ActValidateFormType Deserialize(Stream s)
    {
        return ((ActValidateFormType)(Serializer.Deserialize(s)));
    }
    #endregion
    
    /// <summary>
    /// Serializes current ActValidateFormType object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, out Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName);
            return true;
        }
        catch (Exception e)
        {
            exception = e;
            return false;
        }
    }
    
    public virtual void SaveToFile(string fileName)
    {
        StreamWriter streamWriter = null;
        try
        {
            string xmlString = Serialize();
            FileInfo xmlFile = new FileInfo(fileName);
            streamWriter = xmlFile.CreateText();
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes xml markup from file into an ActValidateFormType object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output ActValidateFormType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, out ActValidateFormType obj, out Exception exception)
    {
        exception = null;
        obj = default(ActValidateFormType);
        try
        {
            obj = LoadFromFile(fileName);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool LoadFromFile(string fileName, out ActValidateFormType obj)
    {
        Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }
    
    public new static ActValidateFormType LoadFromFile(string fileName)
    {
        FileStream file = null;
        StreamReader sr = null;
        try
        {
            file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new StreamReader(file);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
    
    #region Clone method
    /// <summary>
    /// Create a clone of this ActValidateFormType object
    /// </summary>
    public virtual ActValidateFormType Clone()
    {
        return ((ActValidateFormType)(MemberwiseClone()));
    }
    #endregion
}
}
#pragma warning restore
