// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.Collections.ObjectModel;
using System.Reflection;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;

/// <summary>
/// Information about a file, usually thought of as a binary byte stream
/// stored on disk. A FileType can also represent a "virtual" file, such as an XML
/// module in a larger XML document. Such a virtual file could theoretically be stored
/// as a byte stream, as an independant file on disk or as a database record or set of
/// records, even if this byte stream is never actually persisted as an independant disk
/// file.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://healthIT.gov/sdc")]
[DataContractAttribute(Name="FileType", Namespace="http://healthIT.gov/sdc")]
public partial class FileType : ExtensionBaseType
{
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _fileID;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private anyURI_Stype _fileURI;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _displayName;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _title;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private VersionType _version;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _fileName;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _fileExtension;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _fileClass;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private positiveInteger_Stype _fileSizeKB;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private BindingList<string_Stype> _description;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _copyright;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _termsofUse;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private FileUsageType _usage;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private FileDatesType _dates;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ContactsType _contacts;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private BindingList<ApprovalType> _approval;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private FileHashType _fileHash;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private BindingList<LanguageType> _language;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private AssociatedFilesType _associatedFiles;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ProvenanceType _provenance;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private BindingList<SubmissionRuleType> _defaultSubmissionRule;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private BindingList<ComplianceRuleType> _defaultComplianceRule;
    
    private static XmlSerializer serializer;
    
    private ObjectChangeTracker changeTrackerField;
    
    /// <summary>
    /// Internal/local File ID, not necessarily in the format
    /// of the FileURI used for all SDC FormDesign items.
    /// </summary>
    [XmlElementAttribute(Order=0)]
    [DataMemberAttribute(Order=0)]
    public virtual string_Stype FileID
    {
        get
        {
            return _fileID;
        }
        set
        {
            if ((_fileID == value))
            {
                return;
            }
            if (((_fileID == null) 
                        || (_fileID.Equals(value) != true)))
            {
                _fileID = value;
                OnPropertyChanged("FileID", value);
            }
        }
    }
    
    [XmlElementAttribute(Order=1)]
    [DataMemberAttribute(Order=1)]
    public virtual anyURI_Stype FileURI
    {
        get
        {
            return _fileURI;
        }
        set
        {
            if ((_fileURI == value))
            {
                return;
            }
            if (((_fileURI == null) 
                        || (_fileURI.Equals(value) != true)))
            {
                _fileURI = value;
                OnPropertyChanged("FileURI", value);
            }
        }
    }
    
    /// <summary>
    /// Text to be displayed that encapulates the file
    /// contents. This may be the same as the internal Title of the
    /// file.
    /// </summary>
    [XmlElementAttribute(Order=2)]
    [DataMemberAttribute(Order=2)]
    public virtual string_Stype DisplayName
    {
        get
        {
            return _displayName;
        }
        set
        {
            if ((_displayName == value))
            {
                return;
            }
            if (((_displayName == null) 
                        || (_displayName.Equals(value) != true)))
            {
                _displayName = value;
                OnPropertyChanged("DisplayName", value);
            }
        }
    }
    
    /// <summary>
    /// Official title of the file.
    /// </summary>
    [XmlElementAttribute(Order=3)]
    [DataMemberAttribute(Order=3)]
    public virtual string_Stype Title
    {
        get
        {
            return _title;
        }
        set
        {
            if ((_title == value))
            {
                return;
            }
            if (((_title == null) 
                        || (_title.Equals(value) != true)))
            {
                _title = value;
                OnPropertyChanged("Title", value);
            }
        }
    }
    
    /// <summary>
    /// File version
    /// </summary>
    [XmlElementAttribute(Order=4)]
    [DataMemberAttribute(Order=4)]
    public virtual VersionType Version
    {
        get
        {
            return _version;
        }
        set
        {
            if ((_version == value))
            {
                return;
            }
            if (((_version == null) 
                        || (_version.Equals(value) != true)))
            {
                _version = value;
                OnPropertyChanged("Version", value);
            }
        }
    }
    
    /// <summary>
    /// The name of the file as saved on disk or other persistant storage.
    /// </summary>
    [XmlElementAttribute(Order=5)]
    [DataMemberAttribute(Order=5)]
    public virtual string_Stype FileName
    {
        get
        {
            return _fileName;
        }
        set
        {
            if ((_fileName == value))
            {
                return;
            }
            if (((_fileName == null) 
                        || (_fileName.Equals(value) != true)))
            {
                _fileName = value;
                OnPropertyChanged("FileName", value);
            }
        }
    }
    
    /// <summary>
    /// The file type extension that describes the file's
    /// internal format. This is usually the 3-4 character text that appears
    /// after the last period in the file name, e.g., txt, docx,
    /// etc.
    /// </summary>
    [XmlElementAttribute(Order=6)]
    [DataMemberAttribute(Order=6)]
    public virtual string_Stype FileExtension
    {
        get
        {
            return _fileExtension;
        }
        set
        {
            if ((_fileExtension == value))
            {
                return;
            }
            if (((_fileExtension == null) 
                        || (_fileExtension.Equals(value) != true)))
            {
                _fileExtension = value;
                OnPropertyChanged("FileExtension", value);
            }
        }
    }
    
    /// <summary>
    /// A short description of the class of file, such as "FormDesign XML"
    /// </summary>
    [XmlElementAttribute(Order=7)]
    [DataMemberAttribute(Order=7)]
    public virtual string_Stype FileClass
    {
        get
        {
            return _fileClass;
        }
        set
        {
            if ((_fileClass == value))
            {
                return;
            }
            if (((_fileClass == null) 
                        || (_fileClass.Equals(value) != true)))
            {
                _fileClass = value;
                OnPropertyChanged("FileClass", value);
            }
        }
    }
    
    [XmlElementAttribute(Order=8)]
    [DataMemberAttribute(Order=8)]
    public virtual positiveInteger_Stype FileSizeKB
    {
        get
        {
            return _fileSizeKB;
        }
        set
        {
            if ((_fileSizeKB == value))
            {
                return;
            }
            if (((_fileSizeKB == null) 
                        || (_fileSizeKB.Equals(value) != true)))
            {
                _fileSizeKB = value;
                OnPropertyChanged("FileSizeKB", value);
            }
        }
    }
    
    /// <summary>
    /// Any additional information about the template or file. The type of information should be specified in the @type
    /// attribute.
    /// </summary>
    [XmlElementAttribute("Description", Order=9)]
    [DataMemberAttribute(Order=9)]
    public virtual BindingList<string_Stype> Description
    {
        get
        {
            return _description;
        }
        set
        {
            if ((_description == value))
            {
                return;
            }
            if (((_description == null) 
                        || (_description.Equals(value) != true)))
            {
                _description = value;
                OnPropertyChanged("Description", value);
            }
        }
    }
    
    [XmlElementAttribute(Order=10)]
    [DataMemberAttribute(Order=10)]
    public virtual string_Stype Copyright
    {
        get
        {
            return _copyright;
        }
        set
        {
            if ((_copyright == value))
            {
                return;
            }
            if (((_copyright == null) 
                        || (_copyright.Equals(value) != true)))
            {
                _copyright = value;
                OnPropertyChanged("Copyright", value);
            }
        }
    }
    
    [XmlElementAttribute(Order=11)]
    [DataMemberAttribute(Order=11)]
    public virtual string_Stype TermsofUse
    {
        get
        {
            return _termsofUse;
        }
        set
        {
            if ((_termsofUse == value))
            {
                return;
            }
            if (((_termsofUse == null) 
                        || (_termsofUse.Equals(value) != true)))
            {
                _termsofUse = value;
                OnPropertyChanged("TermsofUse", value);
            }
        }
    }
    
    /// <summary>
    /// Guidenace for when this file should be used, and when it should not be used.
    /// </summary>
    [XmlElementAttribute(Order=12)]
    [DataMemberAttribute(Order=12)]
    public virtual FileUsageType Usage
    {
        get
        {
            return _usage;
        }
        set
        {
            if ((_usage == value))
            {
                return;
            }
            if (((_usage == null) 
                        || (_usage.Equals(value) != true)))
            {
                _usage = value;
                OnPropertyChanged("Usage", value);
            }
        }
    }
    
    /// <summary>
    /// Various dates associated with the file release, versioning and usage.
    /// </summary>
    [XmlElementAttribute(Order=13)]
    [DataMemberAttribute(Order=13)]
    public virtual FileDatesType Dates
    {
        get
        {
            return _dates;
        }
        set
        {
            if ((_dates == value))
            {
                return;
            }
            if (((_dates == null) 
                        || (_dates.Equals(value) != true)))
            {
                _dates = value;
                OnPropertyChanged("Dates", value);
            }
        }
    }
    
    /// <summary>
    /// People and Organizations associated with the file.
    /// Specify the type of Contact in the @type attribute. Examples of
    /// @type include Curator, Author, and Authority.
    /// </summary>
    [XmlElementAttribute(Order=14)]
    [DataMemberAttribute(Order=14)]
    public virtual ContactsType Contacts
    {
        get
        {
            return _contacts;
        }
        set
        {
            if ((_contacts == value))
            {
                return;
            }
            if (((_contacts == null) 
                        || (_contacts.Equals(value) != true)))
            {
                _contacts = value;
                OnPropertyChanged("Contacts", value);
            }
        }
    }
    
    /// <summary>
    /// Documentation of review and acceptance of the file for production usage.
    /// </summary>
    [XmlElementAttribute("Approval", Order=15)]
    [DataMemberAttribute(Order=15)]
    public virtual BindingList<ApprovalType> Approval
    {
        get
        {
            return _approval;
        }
        set
        {
            if ((_approval == value))
            {
                return;
            }
            if (((_approval == null) 
                        || (_approval.Equals(value) != true)))
            {
                _approval = value;
                OnPropertyChanged("Approval", value);
            }
        }
    }
    
    [XmlElementAttribute(Order=16)]
    [DataMemberAttribute(Order=16)]
    public virtual FileHashType FileHash
    {
        get
        {
            return _fileHash;
        }
        set
        {
            if ((_fileHash == value))
            {
                return;
            }
            if (((_fileHash == null) 
                        || (_fileHash.Equals(value) != true)))
            {
                _fileHash = value;
                OnPropertyChanged("FileHash", value);
            }
        }
    }
    
    [XmlElementAttribute("Language", Order=17)]
    [DataMemberAttribute(Order=17)]
    public virtual BindingList<LanguageType> Language
    {
        get
        {
            return _language;
        }
        set
        {
            if ((_language == value))
            {
                return;
            }
            if (((_language == null) 
                        || (_language.Equals(value) != true)))
            {
                _language = value;
                OnPropertyChanged("Language", value);
            }
        }
    }
    
    /// <summary>
    /// Link to any associated files, such as schemas, reference documents, manuals, etc.
    /// </summary>
    [XmlElementAttribute(Order=18)]
    [DataMemberAttribute(Order=18)]
    public virtual AssociatedFilesType AssociatedFiles
    {
        get
        {
            return _associatedFiles;
        }
        set
        {
            if ((_associatedFiles == value))
            {
                return;
            }
            if (((_associatedFiles == null) 
                        || (_associatedFiles.Equals(value) != true)))
            {
                _associatedFiles = value;
                OnPropertyChanged("AssociatedFiles", value);
            }
        }
    }
    
    [XmlElementAttribute(Order=19)]
    [DataMemberAttribute(Order=19)]
    public virtual ProvenanceType Provenance
    {
        get
        {
            return _provenance;
        }
        set
        {
            if ((_provenance == value))
            {
                return;
            }
            if (((_provenance == null) 
                        || (_provenance.Equals(value) != true)))
            {
                _provenance = value;
                OnPropertyChanged("Provenance", value);
            }
        }
    }
    
    [XmlElementAttribute("DefaultSubmissionRule", Order=20)]
    [DataMemberAttribute(Order=20)]
    public virtual BindingList<SubmissionRuleType> DefaultSubmissionRule
    {
        get
        {
            return _defaultSubmissionRule;
        }
        set
        {
            if ((_defaultSubmissionRule == value))
            {
                return;
            }
            if (((_defaultSubmissionRule == null) 
                        || (_defaultSubmissionRule.Equals(value) != true)))
            {
                _defaultSubmissionRule = value;
                OnPropertyChanged("DefaultSubmissionRule", value);
            }
        }
    }
    
    [XmlElementAttribute("DefaultComplianceRule", Order=21)]
    [DataMemberAttribute(Order=21)]
    public virtual BindingList<ComplianceRuleType> DefaultComplianceRule
    {
        get
        {
            return _defaultComplianceRule;
        }
        set
        {
            if ((_defaultComplianceRule == value))
            {
                return;
            }
            if (((_defaultComplianceRule == null) 
                        || (_defaultComplianceRule.Equals(value) != true)))
            {
                _defaultComplianceRule = value;
                OnPropertyChanged("DefaultComplianceRule", value);
            }
        }
    }
    
    private static XmlSerializer Serializer
    {
        get
        {
            if ((serializer == null))
            {
                serializer = new XmlSerializerFactory().CreateSerializer(typeof(FileType));
            }
            return serializer;
        }
    }
    
    [XmlIgnore()]
    public ObjectChangeTracker ChangeTracker
    {
        get
        {
            if ((changeTrackerField == null))
            {
                changeTrackerField = new ObjectChangeTracker(this);
            }
            return changeTrackerField;
        }
    }
    
    /// <summary>
    /// Test whether FileID should be serialized
    /// </summary>
    public virtual bool ShouldSerializeFileID()
    {
        return (_fileID != null);
    }
    
    /// <summary>
    /// Test whether FileURI should be serialized
    /// </summary>
    public virtual bool ShouldSerializeFileURI()
    {
        return (_fileURI != null);
    }
    
    /// <summary>
    /// Test whether DisplayName should be serialized
    /// </summary>
    public virtual bool ShouldSerializeDisplayName()
    {
        return (_displayName != null);
    }
    
    /// <summary>
    /// Test whether Title should be serialized
    /// </summary>
    public virtual bool ShouldSerializeTitle()
    {
        return (_title != null);
    }
    
    /// <summary>
    /// Test whether Version should be serialized
    /// </summary>
    public virtual bool ShouldSerializeVersion()
    {
        return (_version != null);
    }
    
    /// <summary>
    /// Test whether FileName should be serialized
    /// </summary>
    public virtual bool ShouldSerializeFileName()
    {
        return (_fileName != null);
    }
    
    /// <summary>
    /// Test whether FileExtension should be serialized
    /// </summary>
    public virtual bool ShouldSerializeFileExtension()
    {
        return (_fileExtension != null);
    }
    
    /// <summary>
    /// Test whether FileClass should be serialized
    /// </summary>
    public virtual bool ShouldSerializeFileClass()
    {
        return (_fileClass != null);
    }
    
    /// <summary>
    /// Test whether FileSizeKB should be serialized
    /// </summary>
    public virtual bool ShouldSerializeFileSizeKB()
    {
        return (_fileSizeKB != null);
    }
    
    /// <summary>
    /// Test whether Copyright should be serialized
    /// </summary>
    public virtual bool ShouldSerializeCopyright()
    {
        return (_copyright != null);
    }
    
    /// <summary>
    /// Test whether TermsofUse should be serialized
    /// </summary>
    public virtual bool ShouldSerializeTermsofUse()
    {
        return (_termsofUse != null);
    }
    
    /// <summary>
    /// Test whether Usage should be serialized
    /// </summary>
    public virtual bool ShouldSerializeUsage()
    {
        return (_usage != null);
    }
    
    /// <summary>
    /// Test whether Dates should be serialized
    /// </summary>
    public virtual bool ShouldSerializeDates()
    {
        return (_dates != null);
    }
    
    /// <summary>
    /// Test whether Contacts should be serialized
    /// </summary>
    public virtual bool ShouldSerializeContacts()
    {
        return (_contacts != null);
    }
    
    /// <summary>
    /// Test whether FileHash should be serialized
    /// </summary>
    public virtual bool ShouldSerializeFileHash()
    {
        return (_fileHash != null);
    }
    
    /// <summary>
    /// Test whether AssociatedFiles should be serialized
    /// </summary>
    public virtual bool ShouldSerializeAssociatedFiles()
    {
        return (_associatedFiles != null);
    }
    
    /// <summary>
    /// Test whether Provenance should be serialized
    /// </summary>
    public virtual bool ShouldSerializeProvenance()
    {
        return (_provenance != null);
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current FileType object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public virtual string Serialize()
    {
        StreamReader streamReader = null;
        MemoryStream memoryStream = null;
        try
        {
            memoryStream = new MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Indent = true;
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, SeekOrigin.Begin);
            streamReader = new StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes workflow markup into an FileType object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output FileType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out FileType obj, out Exception exception)
    {
        exception = null;
        obj = default(FileType);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out FileType obj)
    {
        Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public new static FileType Deserialize(string input)
    {
        StringReader stringReader = null;
        try
        {
            stringReader = new StringReader(input);
            return ((FileType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }
    
    public static FileType Deserialize(Stream s)
    {
        return ((FileType)(Serializer.Deserialize(s)));
    }
    #endregion
    
    /// <summary>
    /// Serializes current FileType object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, out Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName);
            return true;
        }
        catch (Exception e)
        {
            exception = e;
            return false;
        }
    }
    
    public virtual void SaveToFile(string fileName)
    {
        StreamWriter streamWriter = null;
        try
        {
            string xmlString = Serialize();
            FileInfo xmlFile = new FileInfo(fileName);
            streamWriter = xmlFile.CreateText();
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes xml markup from file into an FileType object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output FileType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, out FileType obj, out Exception exception)
    {
        exception = null;
        obj = default(FileType);
        try
        {
            obj = LoadFromFile(fileName);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool LoadFromFile(string fileName, out FileType obj)
    {
        Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }
    
    public new static FileType LoadFromFile(string fileName)
    {
        FileStream file = null;
        StreamReader sr = null;
        try
        {
            file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new StreamReader(file);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
    
    #region Clone method
    /// <summary>
    /// Create a clone of this FileType object
    /// </summary>
    public virtual FileType Clone()
    {
        return ((FileType)(MemberwiseClone()));
    }
    #endregion
}
}
#pragma warning restore
