// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.Collections.ObjectModel;
using System.Reflection;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;

/// <summary>
/// This type presents any display objects that may be repeated based upon on the user's interaction with the form objects.  Items derived from this type include Sections and Questions.
/// </summary>
[XmlIncludeAttribute(typeof(QuestionItemBaseType))]
[XmlIncludeAttribute(typeof(QuestionItemType))]
[XmlIncludeAttribute(typeof(SectionBaseType))]
[XmlIncludeAttribute(typeof(SectionItemType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
[Serializable]
[DebuggerStepThrough]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="http://healthIT.gov/sdc")]
[DataContractAttribute(Name="RepeatingType", Namespace="http://healthIT.gov/sdc")]
public abstract partial class RepeatingType : DisplayedType
{
    
    private bool _shouldSerializemaxCard;
    
    private bool _shouldSerializeminCard;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ushort _minCard;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ushort _maxCard;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string _repeat;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string _instanceGUID;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string _parentGUID;
    
    private static XmlSerializer serializer;
    
    private ObjectChangeTracker changeTrackerField;
    
    /// <summary>
    /// RepeatingType class constructor
    /// </summary>
    public RepeatingType()
    {
        _minCard = ((ushort)(1));
        _maxCard = ((ushort)(1));
        _repeat = "1";
    }
    
    /// <summary>
    /// @minCard is the minimum number of repetitions allowed for a section or question.  The default value is 1, indicating that the user must answer any question(s) that has this attribute set.  If @minCard is set to 0, then the item and all descendent questions are optional to answer.
    /// </summary>
    [XmlAttribute]
    [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "1")]
    [DataMember]
    public virtual ushort minCard
    {
        get
        {
            return _minCard;
        }
        set
        {
            if ((_minCard == value))
            {
                return;
            }
            _shouldSerializeminCard = true;
            if (((_minCard == null) 
                        || (_minCard.Equals(value) != true)))
            {
                _minCard = value;
                OnPropertyChanged("minCard", value);
            }
        }
    }
    
    /// <summary>
    /// @maxCard is the maximum number of repetitions allowed for a section or question.  The default value is 1, indicating that the section or question cannot be repeated on the data entry form.  A value of 0 indicates that the number of repeats is unlimited.  If @maxCard is not 0, then Must be greater than or equal to minCard.
    /// </summary>
    [XmlAttribute]
    [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "1")]
    [DataMember]
    public virtual ushort maxCard
    {
        get
        {
            return _maxCard;
        }
        set
        {
            if ((_maxCard == value))
            {
                return;
            }
            _shouldSerializemaxCard = true;
            if (((_maxCard == null) 
                        || (_maxCard.Equals(value) != true)))
            {
                _maxCard = value;
                OnPropertyChanged("maxCard", value);
            }
        }
    }
    
    [XmlAttributeAttribute(DataType="positiveInteger")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    [DataMember]
    public virtual string repeat
    {
        get
        {
            return _repeat;
        }
        set
        {
            if ((_repeat == value))
            {
                return;
            }
            if (((_repeat == null) 
                        || (_repeat.Equals(value) != true)))
            {
                _repeat = value;
                OnPropertyChanged("repeat", value);
            }
        }
    }
    
    [XmlAttribute]
    [DataMember]
    public virtual string instanceGUID
    {
        get
        {
            return _instanceGUID;
        }
        set
        {
            if ((_instanceGUID == value))
            {
                return;
            }
            if (((_instanceGUID == null) 
                        || (_instanceGUID.Equals(value) != true)))
            {
                _instanceGUID = value;
                OnPropertyChanged("instanceGUID", value);
            }
        }
    }
    
    [XmlAttribute]
    [DataMember]
    public virtual string parentGUID
    {
        get
        {
            return _parentGUID;
        }
        set
        {
            if ((_parentGUID == value))
            {
                return;
            }
            if (((_parentGUID == null) 
                        || (_parentGUID.Equals(value) != true)))
            {
                _parentGUID = value;
                OnPropertyChanged("parentGUID", value);
            }
        }
    }
    
    private static XmlSerializer Serializer
    {
        get
        {
            if ((serializer == null))
            {
                serializer = new XmlSerializerFactory().CreateSerializer(typeof(RepeatingType));
            }
            return serializer;
        }
    }
    
    [XmlIgnore()]
    public ObjectChangeTracker ChangeTracker
    {
        get
        {
            if ((changeTrackerField == null))
            {
                changeTrackerField = new ObjectChangeTracker(this);
            }
            return changeTrackerField;
        }
    }
    
    /// <summary>
    /// Test whether minCard should be serialized
    /// </summary>
    public virtual bool ShouldSerializeminCard()
    {
        if (_shouldSerializeminCard)
        {
            return true;
        }
        return (_minCard != default(ushort));
    }
    
    /// <summary>
    /// Test whether maxCard should be serialized
    /// </summary>
    public virtual bool ShouldSerializemaxCard()
    {
        if (_shouldSerializemaxCard)
        {
            return true;
        }
        return (_maxCard != default(ushort));
    }
    
    /// <summary>
    /// Test whether repeat should be serialized
    /// </summary>
    public virtual bool ShouldSerializerepeat()
    {
        return !string.IsNullOrEmpty(repeat);
    }
    
    /// <summary>
    /// Test whether instanceGUID should be serialized
    /// </summary>
    public virtual bool ShouldSerializeinstanceGUID()
    {
        return !string.IsNullOrEmpty(instanceGUID);
    }
    
    /// <summary>
    /// Test whether parentGUID should be serialized
    /// </summary>
    public virtual bool ShouldSerializeparentGUID()
    {
        return !string.IsNullOrEmpty(parentGUID);
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current RepeatingType object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public virtual string Serialize()
    {
        StreamReader streamReader = null;
        MemoryStream memoryStream = null;
        try
        {
            memoryStream = new MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Indent = true;
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, SeekOrigin.Begin);
            streamReader = new StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes workflow markup into an RepeatingType object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output RepeatingType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out RepeatingType obj, out Exception exception)
    {
        exception = null;
        obj = default(RepeatingType);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out RepeatingType obj)
    {
        Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public new static RepeatingType Deserialize(string input)
    {
        StringReader stringReader = null;
        try
        {
            stringReader = new StringReader(input);
            return ((RepeatingType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }
    
    public static RepeatingType Deserialize(Stream s)
    {
        return ((RepeatingType)(Serializer.Deserialize(s)));
    }
    #endregion
    
    /// <summary>
    /// Serializes current RepeatingType object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, out Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName);
            return true;
        }
        catch (Exception e)
        {
            exception = e;
            return false;
        }
    }
    
    public virtual void SaveToFile(string fileName)
    {
        StreamWriter streamWriter = null;
        try
        {
            string xmlString = Serialize();
            FileInfo xmlFile = new FileInfo(fileName);
            streamWriter = xmlFile.CreateText();
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes xml markup from file into an RepeatingType object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output RepeatingType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, out RepeatingType obj, out Exception exception)
    {
        exception = null;
        obj = default(RepeatingType);
        try
        {
            obj = LoadFromFile(fileName);
            return true;
        }
        catch (Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool LoadFromFile(string fileName, out RepeatingType obj)
    {
        Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }
    
    public new static RepeatingType LoadFromFile(string fileName)
    {
        FileStream file = null;
        StreamReader sr = null;
        try
        {
            file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new StreamReader(file);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
    
    #region Clone method
    /// <summary>
    /// Create a clone of this RepeatingType object
    /// </summary>
    public virtual RepeatingType Clone()
    {
        return ((RepeatingType)(MemberwiseClone()));
    }
    #endregion
}
}
#pragma warning restore
