<?xml version="1.0" encoding="utf-8"?><Database Name="PERC_eCC" Class="ActiveTemplateList_LINQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PappEcc;Initial Catalog=PERC_eCC;Integrated Security=True" SettingsObjectName="SDT_XML_Main.MySettings" SettingsPropertyName="PERC_eCC_Con" Provider="System.Data.SqlClient" />
</Database>