// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

/// <summary>
/// Inforamtion about changes to file or part of a
/// file.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://healthIT.gov/sdc")]
public partial class ChangeLogType : ExtensionBaseType
{
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ChangedFieldType _changedField;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private DataTypes_SType _changedTo;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private DataTypes_SType _changedFrom;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private List<string_Stype> _changeType;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ReplacedIDsType _replaces;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private dateTime_Stype _changeDate;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private string_Stype _changeDescription;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ContactsType _editors;
    
    [EditorBrowsable(EditorBrowsableState.Never)]
    private ChangeTrackingType _changeTracking;
    
    private static XmlSerializer serializer;
    
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public virtual ChangedFieldType ChangedField
    {
        get
        {
            return this._changedField;
        }
        set
        {
            this._changedField = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public virtual DataTypes_SType ChangedTo
    {
        get
        {
            return this._changedTo;
        }
        set
        {
            this._changedTo = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public virtual DataTypes_SType ChangedFrom
    {
        get
        {
            return this._changedFrom;
        }
        set
        {
            this._changedFrom = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("ChangeType", Order=3)]
    public virtual List<string_Stype> ChangeType
    {
        get
        {
            return this._changeType;
        }
        set
        {
            this._changeType = value;
        }
    }
    
    /// <summary>
    /// The retired/deprecated item that is being replaced.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public virtual ReplacedIDsType Replaces
    {
        get
        {
            return this._replaces;
        }
        set
        {
            this._replaces = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public virtual dateTime_Stype ChangeDate
    {
        get
        {
            return this._changeDate;
        }
        set
        {
            this._changeDate = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public virtual string_Stype ChangeDescription
    {
        get
        {
            return this._changeDescription;
        }
        set
        {
            this._changeDescription = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public virtual ContactsType Editors
    {
        get
        {
            return this._editors;
        }
        set
        {
            this._editors = value;
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public virtual ChangeTrackingType ChangeTracking
    {
        get
        {
            return this._changeTracking;
        }
        set
        {
            this._changeTracking = value;
        }
    }
    
    private static XmlSerializer Serializer
    {
        get
        {
            if ((serializer == null))
            {
                serializer = new XmlSerializerFactory().CreateSerializer(typeof(ChangeLogType));
            }
            return serializer;
        }
    }
    
    /// <summary>
    /// Test whether ChangeType should be serialized
    /// </summary>
    public virtual bool ShouldSerializeChangeType()
    {
        return ChangeType != null && ChangeType.Count > 0;
    }
    
    /// <summary>
    /// Test whether ChangedField should be serialized
    /// </summary>
    public virtual bool ShouldSerializeChangedField()
    {
        return (_changedField != null);
    }
    
    /// <summary>
    /// Test whether ChangedTo should be serialized
    /// </summary>
    public virtual bool ShouldSerializeChangedTo()
    {
        return (_changedTo != null);
    }
    
    /// <summary>
    /// Test whether ChangedFrom should be serialized
    /// </summary>
    public virtual bool ShouldSerializeChangedFrom()
    {
        return (_changedFrom != null);
    }
    
    /// <summary>
    /// Test whether Replaces should be serialized
    /// </summary>
    public virtual bool ShouldSerializeReplaces()
    {
        return (_replaces != null);
    }
    
    /// <summary>
    /// Test whether ChangeDate should be serialized
    /// </summary>
    public virtual bool ShouldSerializeChangeDate()
    {
        return (_changeDate != null);
    }
    
    /// <summary>
    /// Test whether ChangeDescription should be serialized
    /// </summary>
    public virtual bool ShouldSerializeChangeDescription()
    {
        return (_changeDescription != null);
    }
    
    /// <summary>
    /// Test whether Editors should be serialized
    /// </summary>
    public virtual bool ShouldSerializeEditors()
    {
        return (_editors != null);
    }
    
    /// <summary>
    /// Test whether ChangeTracking should be serialized
    /// </summary>
    public virtual bool ShouldSerializeChangeTracking()
    {
        return (_changeTracking != null);
    }
    
    #region Serialize/Deserialize
    /// <summary>
    /// Serializes current ChangeLogType object into an XML string
    /// </summary>
    /// <returns>string XML value</returns>
    public virtual string Serialize()
    {
        System.IO.StreamReader streamReader = null;
        System.IO.MemoryStream memoryStream = null;
        try
        {
            memoryStream = new System.IO.MemoryStream();
            System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
            xmlWriterSettings.Indent = true;
            System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
            Serializer.Serialize(xmlWriter, this);
            memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
            streamReader = new System.IO.StreamReader(memoryStream);
            return streamReader.ReadToEnd();
        }
        finally
        {
            if ((streamReader != null))
            {
                streamReader.Dispose();
            }
            if ((memoryStream != null))
            {
                memoryStream.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes workflow markup into an ChangeLogType object
    /// </summary>
    /// <param name="input">string workflow markup to deserialize</param>
    /// <param name="obj">Output ChangeLogType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool Deserialize(string input, out ChangeLogType obj, out System.Exception exception)
    {
        exception = null;
        obj = default(ChangeLogType);
        try
        {
            obj = Deserialize(input);
            return true;
        }
        catch (System.Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool Deserialize(string input, out ChangeLogType obj)
    {
        System.Exception exception = null;
        return Deserialize(input, out obj, out exception);
    }
    
    public new static ChangeLogType Deserialize(string input)
    {
        System.IO.StringReader stringReader = null;
        try
        {
            stringReader = new System.IO.StringReader(input);
            return ((ChangeLogType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
        }
        finally
        {
            if ((stringReader != null))
            {
                stringReader.Dispose();
            }
        }
    }
    
    public static ChangeLogType Deserialize(System.IO.Stream s)
    {
        return ((ChangeLogType)(Serializer.Deserialize(s)));
    }
    #endregion
    
    /// <summary>
    /// Serializes current ChangeLogType object into file
    /// </summary>
    /// <param name="fileName">full path of outupt xml file</param>
    /// <param name="exception">output Exception value if failed</param>
    /// <returns>true if can serialize and save into file; otherwise, false</returns>
    public virtual bool SaveToFile(string fileName, out System.Exception exception)
    {
        exception = null;
        try
        {
            SaveToFile(fileName);
            return true;
        }
        catch (System.Exception e)
        {
            exception = e;
            return false;
        }
    }
    
    public virtual void SaveToFile(string fileName)
    {
        System.IO.StreamWriter streamWriter = null;
        try
        {
            string xmlString = Serialize();
            System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
            streamWriter = xmlFile.CreateText();
            streamWriter.WriteLine(xmlString);
            streamWriter.Close();
        }
        finally
        {
            if ((streamWriter != null))
            {
                streamWriter.Dispose();
            }
        }
    }
    
    /// <summary>
    /// Deserializes xml markup from file into an ChangeLogType object
    /// </summary>
    /// <param name="fileName">string xml file to load and deserialize</param>
    /// <param name="obj">Output ChangeLogType object</param>
    /// <param name="exception">output Exception value if deserialize failed</param>
    /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
    public static bool LoadFromFile(string fileName, out ChangeLogType obj, out System.Exception exception)
    {
        exception = null;
        obj = default(ChangeLogType);
        try
        {
            obj = LoadFromFile(fileName);
            return true;
        }
        catch (System.Exception ex)
        {
            exception = ex;
            return false;
        }
    }
    
    public static bool LoadFromFile(string fileName, out ChangeLogType obj)
    {
        System.Exception exception = null;
        return LoadFromFile(fileName, out obj, out exception);
    }
    
    public new static ChangeLogType LoadFromFile(string fileName)
    {
        System.IO.FileStream file = null;
        System.IO.StreamReader sr = null;
        try
        {
            file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
            sr = new System.IO.StreamReader(file);
            string xmlString = sr.ReadToEnd();
            sr.Close();
            file.Close();
            return Deserialize(xmlString);
        }
        finally
        {
            if ((file != null))
            {
                file.Dispose();
            }
            if ((sr != null))
            {
                sr.Dispose();
            }
        }
    }
}
}
#pragma warning restore
