// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.87.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// Function or web service that returns a string
/// value.
/// </summary>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LookupEndPointType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public partial class CallFuncActionType : CallFuncType
{
    
    #region Private fields
    private PredActionType _conditionalActions;
    #endregion
    
    /// <summary>
    /// Actions to take, usually based on the return @val
    /// value of the function. Condiitons may be specified for each action.
    /// Conditions may be combined by Boolean operators and nested to any
    /// level.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public virtual PredActionType ConditionalActions
    {
        get
        {
            return this._conditionalActions;
        }
        set
        {
            if ((this._conditionalActions == value))
            {
                return;
            }
            if (((this._conditionalActions == null) 
                        || (_conditionalActions.Equals(value) != true)))
            {
                this._conditionalActions = value;
                this.OnPropertyChanged("ConditionalActions", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether ConditionalActions should be serialized
    /// </summary>
    public virtual bool ShouldSerializeConditionalActions()
    {
        return (_conditionalActions != null);
    }
}
}
#pragma warning restore
