// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.87.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016", IncludeInSchema=false)]
public enum ItemsChoiceType1
{
    
    Action,
    
    AddCode,
    
    CallFunction,
    
    ConditionalGroupAction,
    
    Inject,
    
    PreviewReport,
    
    RunCode,
    
    Save,
    
    SelectMatchingListItems,
    
    SendMessage111,
    
    SendReport,
    
    SetAttributeValue,
    
    SetAttributeValueScript,
    
    SetBoolAttributeValueCode,
    
    ShowForm,
    
    ShowMessage,
    
    ShowReport,
    
    ShowURL,
    
    ValidateForm,
}
}
#pragma warning restore
