// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.87.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// A generic structure for recording languages.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public partial class LanguageType : ExtensionBaseType
{
    
    #region Private fields
    private string_Stype _language;
    
    private LanguageCodeISO6393_Type _languageCodeISO6393;
    #endregion
    
    /// <summary>
    /// The language used for text in SDC templates.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public virtual string_Stype Language
    {
        get
        {
            return this._language;
        }
        set
        {
            if ((this._language == value))
            {
                return;
            }
            if (((this._language == null) 
                        || (_language.Equals(value) != true)))
            {
                this._language = value;
                this.OnPropertyChanged("Language", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute("LanguageCode.ISO.639.3", Order=1)]
    public virtual LanguageCodeISO6393_Type LanguageCodeISO6393
    {
        get
        {
            return this._languageCodeISO6393;
        }
        set
        {
            if ((this._languageCodeISO6393 == value))
            {
                return;
            }
            if (((this._languageCodeISO6393 == null) 
                        || (_languageCodeISO6393.Equals(value) != true)))
            {
                this._languageCodeISO6393 = value;
                this.OnPropertyChanged("LanguageCodeISO6393", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether Language should be serialized
    /// </summary>
    public virtual bool ShouldSerializeLanguage()
    {
        return (_language != null);
    }
    
    /// <summary>
    /// Test whether LanguageCodeISO6393 should be serialized
    /// </summary>
    public virtual bool ShouldSerializeLanguageCodeISO6393()
    {
        return (_languageCodeISO6393 != null);
    }
}
}
#pragma warning restore
