// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.87.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// A hyperlink to an Internet endpoint such as a web page or web service.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public partial class LinkType : ExtensionBaseType
{
    
    #region Private fields
    private RichTextType _linkText;
    
    private anyURI_Stype _linkURI;
    #endregion
    
    /// <summary>
    /// A description of the URI link, usually for display purposes.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public virtual RichTextType LinkText
    {
        get
        {
            return this._linkText;
        }
        set
        {
            if ((this._linkText == value))
            {
                return;
            }
            if (((this._linkText == null) 
                        || (_linkText.Equals(value) != true)))
            {
                this._linkText = value;
                this.OnPropertyChanged("LinkText", value);
            }
        }
    }
    
    /// <summary>
    /// Link to external information.
    /// </summary>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public virtual anyURI_Stype LinkURI
    {
        get
        {
            return this._linkURI;
        }
        set
        {
            if ((this._linkURI == value))
            {
                return;
            }
            if (((this._linkURI == null) 
                        || (_linkURI.Equals(value) != true)))
            {
                this._linkURI = value;
                this.OnPropertyChanged("LinkURI", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether LinkText should be serialized
    /// </summary>
    public virtual bool ShouldSerializeLinkText()
    {
        return (_linkText != null);
    }
    
    /// <summary>
    /// Test whether LinkURI should be serialized
    /// </summary>
    public virtual bool ShouldSerializeLinkURI()
    {
        return (_linkURI != null);
    }
}
}
#pragma warning restore
