// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.87.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// This type provides a structure to record status information about a file, template or package stored in a registry.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public partial class RegisteredItemStateType : ExtensionBaseType
{
    
    #region Private fields
    private AcceptabilityType _acceptability;
    
    private string_Stype _administrativeStatus;
    
    private string_Stype _administrativeNote;
    
    private string_Stype _registrationStatus;
    
    private date_Stype _registrationStatusDate;
    
    private date_Stype _effectiveDate;
    
    private date_Stype _untilDate;
    
    private string_Stype _previousStatus;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public virtual AcceptabilityType Acceptability
    {
        get
        {
            return this._acceptability;
        }
        set
        {
            if ((this._acceptability == value))
            {
                return;
            }
            if (((this._acceptability == null) 
                        || (_acceptability.Equals(value) != true)))
            {
                this._acceptability = value;
                this.OnPropertyChanged("Acceptability", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public virtual string_Stype AdministrativeStatus
    {
        get
        {
            return this._administrativeStatus;
        }
        set
        {
            if ((this._administrativeStatus == value))
            {
                return;
            }
            if (((this._administrativeStatus == null) 
                        || (_administrativeStatus.Equals(value) != true)))
            {
                this._administrativeStatus = value;
                this.OnPropertyChanged("AdministrativeStatus", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public virtual string_Stype AdministrativeNote
    {
        get
        {
            return this._administrativeNote;
        }
        set
        {
            if ((this._administrativeNote == value))
            {
                return;
            }
            if (((this._administrativeNote == null) 
                        || (_administrativeNote.Equals(value) != true)))
            {
                this._administrativeNote = value;
                this.OnPropertyChanged("AdministrativeNote", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public virtual string_Stype RegistrationStatus
    {
        get
        {
            return this._registrationStatus;
        }
        set
        {
            if ((this._registrationStatus == value))
            {
                return;
            }
            if (((this._registrationStatus == null) 
                        || (_registrationStatus.Equals(value) != true)))
            {
                this._registrationStatus = value;
                this.OnPropertyChanged("RegistrationStatus", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public virtual date_Stype RegistrationStatusDate
    {
        get
        {
            return this._registrationStatusDate;
        }
        set
        {
            if ((this._registrationStatusDate == value))
            {
                return;
            }
            if (((this._registrationStatusDate == null) 
                        || (_registrationStatusDate.Equals(value) != true)))
            {
                this._registrationStatusDate = value;
                this.OnPropertyChanged("RegistrationStatusDate", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public virtual date_Stype EffectiveDate
    {
        get
        {
            return this._effectiveDate;
        }
        set
        {
            if ((this._effectiveDate == value))
            {
                return;
            }
            if (((this._effectiveDate == null) 
                        || (_effectiveDate.Equals(value) != true)))
            {
                this._effectiveDate = value;
                this.OnPropertyChanged("EffectiveDate", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public virtual date_Stype UntilDate
    {
        get
        {
            return this._untilDate;
        }
        set
        {
            if ((this._untilDate == value))
            {
                return;
            }
            if (((this._untilDate == null) 
                        || (_untilDate.Equals(value) != true)))
            {
                this._untilDate = value;
                this.OnPropertyChanged("UntilDate", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public virtual string_Stype PreviousStatus
    {
        get
        {
            return this._previousStatus;
        }
        set
        {
            if ((this._previousStatus == value))
            {
                return;
            }
            if (((this._previousStatus == null) 
                        || (_previousStatus.Equals(value) != true)))
            {
                this._previousStatus = value;
                this.OnPropertyChanged("PreviousStatus", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether Acceptability should be serialized
    /// </summary>
    public virtual bool ShouldSerializeAcceptability()
    {
        return (_acceptability != null);
    }
    
    /// <summary>
    /// Test whether AdministrativeStatus should be serialized
    /// </summary>
    public virtual bool ShouldSerializeAdministrativeStatus()
    {
        return (_administrativeStatus != null);
    }
    
    /// <summary>
    /// Test whether AdministrativeNote should be serialized
    /// </summary>
    public virtual bool ShouldSerializeAdministrativeNote()
    {
        return (_administrativeNote != null);
    }
    
    /// <summary>
    /// Test whether RegistrationStatus should be serialized
    /// </summary>
    public virtual bool ShouldSerializeRegistrationStatus()
    {
        return (_registrationStatus != null);
    }
    
    /// <summary>
    /// Test whether RegistrationStatusDate should be serialized
    /// </summary>
    public virtual bool ShouldSerializeRegistrationStatusDate()
    {
        return (_registrationStatusDate != null);
    }
    
    /// <summary>
    /// Test whether EffectiveDate should be serialized
    /// </summary>
    public virtual bool ShouldSerializeEffectiveDate()
    {
        return (_effectiveDate != null);
    }
    
    /// <summary>
    /// Test whether UntilDate should be serialized
    /// </summary>
    public virtual bool ShouldSerializeUntilDate()
    {
        return (_untilDate != null);
    }
    
    /// <summary>
    /// Test whether PreviousStatus should be serialized
    /// </summary>
    public virtual bool ShouldSerializePreviousStatus()
    {
        return (_previousStatus != null);
    }
}
}
#pragma warning restore
