// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.87.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// Contains information about a registered package, including a description of the package contents and purpose (PackageDescription), information about the registry that contains the package XML (RegistryData), and information about the package file characteristics (TemplateFile).
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:qrph:sdc:2016")]
public partial class TemplateAdminTypeDigitalSignature : ExtensionBaseType
{
    
    #region Private fields
    private TemplateAdminTypeDigitalSignaturePackageSignature _packageSignature;
    
    private TemplateAdminTypeDigitalSignatureSignatureProperties _signatureProperties;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public virtual TemplateAdminTypeDigitalSignaturePackageSignature PackageSignature
    {
        get
        {
            return this._packageSignature;
        }
        set
        {
            if ((this._packageSignature == value))
            {
                return;
            }
            if (((this._packageSignature == null) 
                        || (_packageSignature.Equals(value) != true)))
            {
                this._packageSignature = value;
                this.OnPropertyChanged("PackageSignature", value);
            }
        }
    }
    
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public virtual TemplateAdminTypeDigitalSignatureSignatureProperties SignatureProperties
    {
        get
        {
            return this._signatureProperties;
        }
        set
        {
            if ((this._signatureProperties == value))
            {
                return;
            }
            if (((this._signatureProperties == null) 
                        || (_signatureProperties.Equals(value) != true)))
            {
                this._signatureProperties = value;
                this.OnPropertyChanged("SignatureProperties", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether PackageSignature should be serialized
    /// </summary>
    public virtual bool ShouldSerializePackageSignature()
    {
        return (_packageSignature != null);
    }
    
    /// <summary>
    /// Test whether SignatureProperties should be serialized
    /// </summary>
    public virtual bool ShouldSerializeSignatureProperties()
    {
        return (_signatureProperties != null);
    }
}
}
#pragma warning restore
