// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.87.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema2
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// A generic structure for recording file version metadata.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:qrph:sdc:2016")]
public partial class VersionTypeChanges : ExtensionBaseType
{
    
    #region Private fields
    private List<ChangeLogType> _change;
    #endregion
    
    [System.Xml.Serialization.XmlElementAttribute("Change", Order=0)]
    public virtual List<ChangeLogType> Change
    {
        get
        {
            return this._change;
        }
        set
        {
            if ((this._change == value))
            {
                return;
            }
            if (((this._change == null) 
                        || (_change.Equals(value) != true)))
            {
                this._change = value;
                this.OnPropertyChanged("Change", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether Change should be serialized
    /// </summary>
    public virtual bool ShouldSerializeChange()
    {
        return Change != null && Change.Count > 0;
    }
}
}
#pragma warning restore
